### ISSUE TITLE
Can't build/run with Homebrew on Linux

### ISSUE THREAD

**Issue by dawidd6** [crystal-lang/crystal#9148] opened 2020-04-21 08:53 UTC
We are currently trying to build `crystal` for Homebrew on Linux and it fails:

```
==> make deps
Using /home/linuxbrew/.linuxbrew/opt/llvm/bin/llvm-config [version=10.0.0]
g++-5 -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/home/linuxbrew/.linuxbrew/Cellar/llvm/10.0.0_5/include -std=c++14    -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
gcc-5 -fPIC    -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
==> bin/crystal build -D without_openssl -D without_zlib -D preview_overflow -o .build/crystal src/compiler/crystal.cr --release --no-debug --threads=1
Invalid memory access (signal 11) at address 0x7fae414d4f28
[0x7fae92196ee6] ???
[0x7fae920eda6b] ???
[0x7fae92f64491] ???
```

Note that it pops up randomly and we are able to get it to build sometimes, but then when running `crystal` another errors show up:

```
[0x7f0e987029c9] _ZN4llvm16DwarfCompileUnit37applySubprogramAttributesToDefinitionEPKNS_12DISubprogramERNS_3DIEE +121
[0x7f0e98718a12] _ZN4llvm10DwarfDebug27finishSubprogramDefinitionsEv +82
[0x7f0e98718a7a] _ZN4llvm10DwarfDebug18finalizeModuleInfoEv +42
[0x7f0e98721bd0] _ZN4llvm10DwarfDebug9endModuleEv +80
[0x7f0e986d9fef] _ZN4llvm10AsmPrinter14doFinalizationERNS_6ModuleE +575
[0x7f0e98067a81] _ZN4llvm13FPPassManager14doFinalizationERNS_6ModuleE +97
[0x7f0e980731ec] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +1212
[0x7f0e996e3f8f] ???
[0x7f0e996e41e4] LLVMTargetMachineEmitToFile +212
[0xa0f1bf] ???
[0xa0f9cd] ???
[0x437160] ???
[0x0] ???
gcc: error: _main.o: No such file or directory
gcc: error: S-lice40U-I-nt841.o: No such file or directory
gcc: error: P-ointer40U-I-nt841.o: No such file or directory
gcc: error: A-rgumentE-rror.o: No such file or directory
gcc: error: C-allS-tack.o: No such file or directory
gcc: error: A-rray40P-ointer40V-oid4141.o: No such file or directory
gcc: error: P-ointer40P-ointer40V-oid4141.o: No such file or directory
gcc: error: E-xception.o: No such file or directory
```

This situation didn't happen with previous release of `crystal`.

We are building our packages (bottles) in a Ubuntu 16.04 Docker container on Github Actions.

https://github.com/Homebrew/linuxbrew-core/pull/20041

**Comment by xmonader** [comment] 2020-05-07 14:04
Facing the same.

**Comment by snadon** [comment] 2020-05-08 00:36
Facing the same issue. It builds okay with my Github Action but when deploying on Heroku I'm having this kind of error:
```
Installing selenium (0.4.0 at bda2fd406c1a118251c5a2883f1e1f3af242116e)
Installing db (0.9.0)
Postinstall of lucky: script/precompile_tasks
Postinstall of avram: script/precompile_tasks
done
-----> Compiling src/my-site.cr (auto-detected from shard.yml)... Invalid memory access (signal 11) at address 0x7f07489fa6d8
[0x7f076dc965e6] ???
[0x7f076dbe52cb] ???
[0x7f076ea63b91] ???
 !     Push rejected, failed to compile Crystal app.
 !     Push failed
```

**Comment by paulcsmith** [comment] 2020-05-08 00:37
Worth noting that this is being reported in the Lucky community somewhat often and it is just intermittent. Often another push or compile works, so it is extremely hard to figure out what's actually wrong. I believe I started seeing these reports around when 0.34.0 was released. So maybe something in 0.34.0 changed something

**Comment by RX14** [comment] 2020-05-08 09:34
If anyone can get reproducible code, or any kind of method which *sometimes* fails, it would be absolutely wonderful.

**Comment by dawidd6** [comment] 2020-05-08 11:23
Just try to build `crystal` Homebrew formula on Linux from source, preferably in `homebrew/brew` Docker container. That should give you the results discussed here.

**Comment by RX14** [comment] 2020-05-08 14:13
@dawidd6 could you provide the commands to do that? I'm not familiar with homebrew at all.

**Comment by waj** [comment] 2020-05-08 14:15
@RX14 I just created a `t3.2xlarge` instance on EC2 with 100GB of SSD (gp2).
Then I executed the install like this:
```
$ sudo snap install docker
$ sudo docker run -it homebrew/brew
$ brew install crystal
```

The build went well, but then I get the segfaults when trying to compile. I'll do some more research.

**Comment by jwoertink** [comment] 2020-05-08 15:23
I get this locally when I deploy my app. Locally I'm on macOS. I boot up a docker container and build the app binary, then I zip that up and deploy to AWS EB. During the build process on Docker, I will get `Invalid memory access (signal 11)` error. To fix this, I just run `docker system prune`, and then I deploy and it's fine. I noticed when I do this after it's happening a lot, I usually recover 50+GB. I run Docker for Mac, and haven't configured anything, so maybe there's some sort of memory limit where crystal needs more memory and hits that limit somehow.

**Comment by RX14** [comment] 2020-05-08 15:45
It's debug info. `--no-debug` for a workaround for now.

Probably changed is we started using the CPP DWARF language, which means we're passing [this](https://github.com/llvm/llvm-project/blob/aad3d578da0ddf6d0d3d95e5e09a32e47f6dfeb8/llvm/lib/CodeGen/AsmPrinter/DwarfUnit.cpp#L735). Entirely unsure why this is only on linuxbrew.

**Comment by jwoertink** [comment] 2020-05-08 15:52
@RX14 if it helps, I'm not using linuxbrew at all, but I'm also not using `--no-debug`. I can try and add that flag in to see if it goes away, but would that get rid of any info I send to Bugsnag?

**Comment by RX14** [comment] 2020-05-08 16:18
Well it's not reproducing on my arch linux box, which is also on LLVM 10, which makes this whole thing rather mysterious.

**Comment by jwoertink** [comment] 2020-05-08 16:20
Hey @russ, since you use Arch, can you share any other info for when you get this `Invalid memory access` error during the deploys?

**Comment by russ** [comment] 2020-05-08 16:48
Just as @waj, the build went fine, but when I went to compile it throws the error. I copied that whole session here: https://gist.github.com/russ/bdd118b7ce343923dd4d678a98f15812

If there are any flags I should try when doing that let me know.

**Comment by RX14** [comment] 2020-05-08 17:21
I mean, using linuxbrew in docker reproduces on my arch laptop. Using the `crystal` arch package - same crystal and LLVM versions - on the same laptop does not reproduce.

**Comment by paulcsmith** [comment] 2020-05-11 14:21
@jwoertink I think @rx14 was suggesting to use `--no-debug` as a workaround, not that it is the problem. Might be worth trying to see if that helps! If so we can also add `--no-debug` to our heroku buildpack in the meantime as well

**Comment by jwoertink** [comment] 2020-05-11 15:03
Oh yeah, for sure. We don't deploy to heroku though. It's not really a show stopper for us since our current work around is to just prune docker. I've also seen when it does happen on heroku, you can clear your build cache with `heroku repo:purge_cache -a appname` and it'll start working. 

Actually, that might be interesting to see if @RX14 was able to reproduce. Run it with linuxbrew in docker and get the error, then prune the docker system, then run it again and see if the error goes away...

**Comment by paulcsmith** [comment] 2020-05-11 15:11
@jwoertink Ah gotcha. I was thinking you could do `--no-debug` to see if that fixes the issue and help narrow down if the debug info is the problem.

If so then we can change the heroku buildpack to help with the Lucky issue of getting this error. We could also do the no debug right now in Heroku but it is harder to test since we'd need to rely on the community to report whether it helps which may or may not be reliable. So maybe you could try `--no-debug` in your container and see if that "solves" the issue?

**Comment by jwoertink** [comment] 2020-05-11 15:29
Sure! I'll give that a shot and report back on that.

**Comment by miry** [comment] 2020-05-18 23:40
@paulcsmith Using `--no-debug` fixed the issue for Fedora 32 linux Crystal 0.34.0 LLVM 10 at least for `Hello World` application .

**Comment by paulcsmith** [comment] 2020-05-20 14:36
Thans @miry for checking and posting your results. It looks like @RX14's hunch was right and the debug info is the most likely cause here. Not sure why it is intermittent though 🤔

**Comment by dawidd6** [comment] 2020-05-20 14:42
We are building with `--no-debug` in linuxbrew and yet it still fails.

**Comment by waj** [comment] 2020-05-21 16:29
@dawidd6 are you using `--no-debug` when running `crystal`? That flag is needed until this issue is fixed.

I did some research and I found that LLVM-10 doesn't like much that we use a custom language identifier: https://github.com/llvm/llvm-project/blob/llvmorg-10.0.0/llvm/include/llvm/BinaryFormat/Dwarf.h#L235

Crystal 0.34 uses a custom ID for the debug metadata: https://github.com/crystal-lang/crystal/blob/0.34.0/src/compiler/crystal/codegen/debug.cr#L5

For 0.35 (not yet released) this already changed and we're using C++ identifier instead. That should fix the issue. However, it's still a mystery for me, why using LLVM-10 on macOS (installed with Homebrew) or other platforms doesn't raise the same issue.

**Comment by waj** [comment] 2020-05-21 22:15
Ok, this seems to be quite random actually, or it depends on how LLVM was built, but I'm not exactly sure. I guess the unreachable assertion is removed in MinSizeRel mode and that's why this doesn't happen in some distributions. But at the end I think this is a LLVM bug and I just opened an issue: https://bugs.llvm.org/show_bug.cgi?id=46027

@dawidd6 can you try the patch I sent attached to that issue in LLVM10?

**Comment by dawidd6** [comment] 2020-05-22 20:25
@waj Can confirm the patch for LLVM you provided does fix the issue.

**Comment by waj** [comment] 2020-05-25 13:42
@RX14 why is this reopened? is there anything else we can do?

**Comment by RX14** [comment] 2020-05-25 15:01
I like to keep issues open until they're closed in the upstream project, since it's not actually fixed yet.

Otherwise it's extremely difficult to keep track of what actually has been fixed and what's in upstream limbo.

**Closed** 2020-11-26 10:30 UTC
Labels: kind:bug
