### ISSUE TITLE
Compilation on crystal 0.13

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2287] opened 2016-03-09 08:41 UTC
Hi,

Updating to last crystal release `0.13.0 [60777f3]`, I have this error when compiling any software.

~~~crystal
Error while requiring "prelude": can't find file 'prelude'
~~~

Regards,

**Comment by jhass** [comment] 2016-03-09 08:44
What's your OS and installation method?

**Comment by waghanza** [comment] 2016-03-09 08:44
Fedora 23

**Comment by jhass** [comment] 2016-03-09 09:06
I got a Fedora 23 chroot and installed Crystal following http://crystal-lang.org/docs/installation/on_redhat_and_centos.html. I cannot reproduce any issue.

**Comment by waghanza** [comment] 2016-03-09 09:06
if it's helpful, there is stderr produced when compiling `crystal` on `fedora` **23** **GCC 5.3.1**
https://gist.github.com/anonymous/b5219eb8cccdccb50f8a

**Comment by ysbaddaden** [comment] 2016-03-09 09:07
Second problem: what LLVM version is installed? You need LLVM 3.5 or 3.6 to compile Crystal, maybe you have 3.7 installed.

**Comment by waghanza** [comment] 2016-03-09 09:09
exactly, fedora `23` has `3.7.0`

**Comment by jhass** [comment] 2016-03-09 09:10
Yes that's  due to a too new LLVM version, but seems unrelated to the initial report.

**Comment by asterite** [comment] 2016-03-09 13:21
@waghanza Can you provide the output of this?

```
crystal --version
which crystal
```

**Comment by waghanza** [comment] 2016-03-10 09:44
@asterite sorry for the delay
 `crystal --version` => `Crystal 0.13.0 [60777f3] (Mon Mar  7 17:12:47 UTC 2016)`
`which crystal` => `/opt/crystal/embedded/bin/crystal`

**Comment by ysbaddaden** [comment] 2016-03-10 10:03
`which crystal` should return `/opt/crystal/bin/crystal` (or `/usr/bin/crystal` that links to this file) which is a shell script that sets a few environment variables like `CRYSTAL_PATH` aka where to find the `src` folder.

Question is, why is `/opt/crystal/embedded/bin` in your `PATH`?

**Comment by waghanza** [comment] 2016-03-10 10:44
i simply don't remember, probably a modification done after investigating on my problem 

it's solved my problem, thanks

**Comment by waghanza** [comment] 2016-03-10 11:07
who should I know which `llvm` version `crystal` use

**Comment by waghanza** [comment] 2016-03-11 08:57
I think I have made this cause `sards` is in `/opt/crystal/embedded/bin`

**Comment by ysbaddaden** [comment] 2016-03-11 09:01
Ah, that explains it. You may either symlink `/opt/crystal/embedded/bin/shards` to `/usr/local/bin` or use `crystal deps` instead, which merely calls the bundled shards binary, so you may call `crystal deps install` for example.

**Comment by waghanza** [comment] 2016-03-11 09:02
@ysbaddaden thanks, but what is the difference beetween `crystal deps` and `shards`

**Comment by ysbaddaden** [comment] 2016-03-11 09:58
None. `crystal deps` merely calls `shards` which is found because the shell script appends `/opt/crystal/embedded/bin` to PATH.

**Comment by waghanza** [comment] 2016-03-11 10:07
@ysbaddaden ah ok, just an alias, ok

**Comment by waterlink** [comment] 2016-03-11 10:58
It sounds like we might want to make sure all the
installers/packages/whatever make the symlink for `shards` properly.

--
Best Regards,
Oleksii Fedorov,
Competent Programmer,
TDD, Microservices, Ruby, Clojure, Go and more,
+49 15757 486 476

**Comment by waghanza** [comment] 2016-03-11 15:41
I've create a `rpm` file https://www.dropbox.com/s/og66hxbl7nu3w6e/crystal-0.13.0-1.x86_64.rpm containing only 

* /usr/local/bin/crystal
* /usr/local/bin/shards

I don't know have any `prelude.cr` file on my disk and I have still this **error**
Error while requiring "prelude": can't find file 'prelude'`
should I have all crystal source code somewere on my disk ? I thought all needed was in the binary file

**Comment by ysbaddaden** [comment] 2016-03-11 18:53
You need the core and stdlib that are the `src` folder.

Aren't the Centos RPM enough? AFAIK the Crystal binary is statically linked to the LLVM libraries, and thus not required. LLVM is only required to build Crystal or when Crystal is dynamically linked against LLVM.

**Comment by waghanza** [comment] 2016-03-11 20:03
i want to build an rpm for my distro, `fedora` **23**

**Comment by asterite** [comment] 2016-05-27 17:28
@waghanza Are you still having problems with this? Otherwise I'll close this in a few days.

**Closed** 2016-06-04 21:44 UTC
Labels: needs more info, project infrastructure
