### ISSUE TITLE
Binding TCPServer to the same port from different processes

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4019] opened 2017-02-11 16:44 UTC
After I had a server process lingering around and running the exact same program again, I noticed that different crystal processes *can* bind to the same port (without any special setup as suggested in #3586). I used [this simple test server](https://github.com/straight-shoota/nginx-cache-test/blob/master/backend.cr) which returns an incrementing counter. With two process listening on the same port, every incoming connection is randomly assigned to one of them:

```
> for i in `seq 1 10`; do curl localhost:8022/; echo -e "" ; done
2
2
3
4
3
4
5
5
6
7
```

I find this behaviour quite odd. By default a second binding should fail with a port already in use exception. I believe, most people would expect this.
It is almost never desired to have different processes  listening on the same port (unless it is intentionally set up), and the user possibly being unaware of this.

Then I tested things further and investigated how other languages implementations work. Pythons oneliner `python -m SimpleHTTPServer 8022` threw an error `[Errno 98] Address already in use` when the crystal server was already bound to the same port. The crystal server also failed when the python server was run first (`Address already in use (Errno)`).
Really interesting is Ruby's WebRick (`ruby -run -e httpd . -p8022`): It seems to hijack the socket and no request is let through to the crystal server and every connection goes to WebRick. Once the ruby process is stopped, the crystal server receives again. The other way around, crystal also fails with `Address already in use (Errno)` when WebRrick was started first. That is, unless another crystal server was started before WebRick. Then the second one also succeeds but does not receive any connection as long as WebRick is running.

Besides the odd WebRick behaviour, it seems like the crystal implementation succeeds to bind to an already occupied port as long as at least one other crystal process is also bound to this port. Why this happens, I have no idea... but I would argue that it shouldn't and instead fail with an port already in use exception.

>  crystal --version
>  Crystal 0.20.5 [ccf46c0] (2017-01-20)

**Comment by bararchy** [comment] 2017-02-11 16:52
Linux 3.9 added the option SO_REUSEPORT to Linux as well. This option allows two (or more) sockets, TCP or UDP, listening (server) or non-listening (client), to be bound to exactly the same address and port combination as long as all sockets (including the very first one) had this flag set prior to binding them. To prevent "port hijacking", there is one special limitation, though: All sockets that want to share the same address and port combination must belong to processes that share the same effective user ID! So one user cannot "steal" ports of another user. Additionally the kernel performs some "special magic" for SO_REUSEPORT sockets that isn't found in any other operating system so far: For UDP sockets, it tries to distribute datagrams evenly, for TCP listening sockets, it tries to distribute incoming connect requests (those accepted by calling accept()) evenly across all the sockets that share the same address and port combination. That means while it is more or less random which socket receives a datagram or connect request in other operating systems that allow full address reuse, Linux tries to optimize distribution so that, for example, multiple instances of a simple server process can easily use SO_REUSEPORT sockets to achieve a kind of simple load balancing and that absolutely for free as the kernel is doing "all the hard work" for them.

**Comment by straight-shoota** [comment] 2017-02-11 17:03
@bararchy Thanks for the great explanation! That explains, why this is happening. Though I still can't figure how the ruby process seems to take over every single connection instead of an even distribution.

In #3686 @ysbaddaden [stated](https://github.com/crystal-lang/crystal/issues/3586#issuecomment-264797555) `SO_REUSEPORT` was not set because this behaviour would not be desired by default. But apparently `SO_REUSEPORT` *is* set... And I also think that shouldn't be the default.

**Comment by bararchy** [comment] 2017-02-11 17:19
I guess , because Ruby does not set SO_REUSEPORT and crystal does (?) , so Crystal binds to port , sets reuse , Ruby reuses but won't set the reuse flag too , Ruby hijacked the port while Crystal lost it

**Comment by RX14** [comment] 2017-02-11 18:42
I think that reuseport should not be the default. Its  infused me quite a few times myself.

**Comment by rdp** [comment] 2017-02-14 03:56
It is definitely useful for micro benchmarks however..since you can use multiple processes [i.e. cores] to serve off a single socket easily...

**Comment by RX14** [comment] 2017-02-14 10:03
@rdp sure, but micro benchmarks can just turn it on.

**Comment by luislavena** [comment] 2017-02-14 14:51
@RX14 it is now exposed with `#reuse_port=`, perhaps we should introduce the `shared: true` option I mentioned in [this comment](https://github.com/crystal-lang/crystal/issues/3586#issuecomment-264850418)?

Making `shared` to be false by default, but allowing someone that wants to use micro benchmarks (or any other option) without issues.

If that sounds reasonable, I can work on that change over the weekend (if nobody else wants to tackle it).

**Comment by asterite** [comment] 2017-02-14 15:10
Shouldn't we simply remove [these lines](https://github.com/crystal-lang/crystal/blob/f0770cd9595c47b46eb568ca0f2524c603ca5d8f/src/socket/tcp_server.cr#L30-L33) to fix this?

**Comment by luislavena** [comment] 2017-02-14 15:12
@asterite was going to suggest remove these lines and expand `HTTP::Server` to allow setting it on your behalf.

**Comment by bararchy** [comment] 2017-02-14 15:18
@asterite 
Both 
https://github.com/crystal-lang/crystal/blob/f0770cd9595c47b46eb568ca0f2524c603ca5d8f/src/socket/tcp_server.cr#L29-L33

As this is unexpected behavior at best, if someone needs this kind of functionality then they should know about it and define it them selves 

maybe 
```crystal
server = TCPServer(socket_reuse: true, port_reuse: true)
```
etc...

**Comment by luislavena** [comment] 2017-02-14 15:21
@bararchy `socket_reuse` is not the same as `reuse_address`, so we need to be consistent between the initializer flags and the instance properties. (even that we know it refers to the socket).

**Comment by bararchy** [comment] 2017-02-14 15:21
@luislavena  -- Typo sorry(edited)

**Comment by RX14** [comment] 2017-02-14 15:24
Isn't `reuse_address` a sensible default?

**Comment by bararchy** [comment] 2017-02-14 15:25
@RX14 Not when it behaves differently on each OS. (Windows, MAC, Linux, BSD, etc..)

**Comment by RX14** [comment] 2017-02-14 15:35
@bararchy Not that differently. `SO_REUSEADDR` seems like a good default on the BSDs and linux. Windows is an entirely different problem that we don't have to worry about for now.

**Comment by rdp** [comment] 2017-02-14 15:43
FWIW the current functionality actually allows port "re binding" in linux
but it doesn't work on OS X quite right.  I guess the world of sockets is a
twisted one: http://stackoverflow.com/a/14388707/32453

**Comment by ysbaddaden** [comment] 2017-02-14 15:53
@straight-shoota this wasn't set at the time, but things change quickly.

Micro-benchmarks don't design an API, but real-world apps do, and they *do* benefit from the `SO_REUSEPORT` option, especially on Linux. The options must be set before binding the socket (obviously) so we can't just remove them.

There are *no* reason to disable `SO_REUSEADDR` except being painful. Who wants to wait one long minute for a lingering socket to be cleared because a crashed server can restarts? Nobody. Allowing to disable it in `TCPServer` is out of scope, one should deal with `Socket` manually if they really don't want this option, because they certainly need better control over the socket anyway.

There may be a reason to disable `SO_REUSEPORT` but I can't think of any (neither are there in this thread). Please be explicit about potential issues and problems, and I may consider to disable the option by default and add an initializer argument to TCPServer, then to everywhere else that initializes a TCPServer to pass the option. This adds to API complexity, so I would like to avoid unnecessary cruft.

**Comment by RX14** [comment] 2017-02-14 16:01
@ysbaddaden Many applications use port 8080 by default. MANY a time have I opened crystal play and wondered why my webapp is failing exactly half of it's HTTP requests. It's because linux is distributing the HTTP requests between crystal play (bound on 8080) and my crystal webapp (bound on 8080). The expected behaviour (and behaviour **every** other application I've ever seen has by default) is to fail to start up if something is already bound on that port. And I have no idea why crystal would break that expectation.

**Comment by bararchy** [comment] 2017-02-14 16:22
I can argue that indeed SO_REUSEADDR is less critical as default , it has a good benefit and most likely will be used by most people , having said that , SO_REUSEPORT is a completely different matter and is against the principal of least astonishment.

When I open a TCPServer and the port is already  binded , I expect it to fail unless explicitly configured otherwise .

**Comment by straight-shoota** [comment] 2017-02-14 16:40
Exactly. If you want your application to listen on the same port from multiple processes, that could be easily be opted in through a flag like `reuse_port: true` on `TCPServer`. This would probably be rarely the case.

But if any other application is already listening on the same port `TCPServer` is trying to bind to, it should  not just silently proceed but instead throw an exception and allow this issue to be noticed and resolved. I mean we're not only talking about developers running their self-written code, who might be aware of that behaviour - although I did not and expected otherwise, @RX14 and probably others as well.
There are also sysadmins using software with crystals `TCPServer`. As a sysadmin I would *most definitly* not want any software to bind to a port that is already in use (and I don't know any that does that). This could cause some serious head-ache trying to debug faulty connections to both applications. If a port is already in use, this is usually an error and a well designed software should fail fast.

**Comment by rdp** [comment] 2017-02-15 05:16
I'll admit it has surprised me in the past as well (in dev), in OS X if you start up a second server today, you might wonder "wait, why are none of my requests making it through" (answer: they all go to a first server still running accidentally in a different tab). FWIW...

**Comment by ysbaddaden** [comment] 2017-02-15 08:53
Thank you, that's the kind of details I wanted. Saying "it confused me" and nothing more doesn't help to understand the issue.

**Comment by spalladino** [comment] 2017-02-16 17:55
Trying to sum up, we should:

1- Add optional arguments to TCPServer to set reuse_addr and reuse_port
2- Set reuse_addr to true and reuse_port to false by default
3- Add properties reuse_addr and reuse_port to HTTP server, which are forwarded to the TCPServer when it is created in the call to [bind](https://github.com/crystal-lang/crystal/blob/master/src/http/server.cr#L142)

Agree? Did I get something wrong from the discussion?

**Comment by Bew78LesellB** [comment] 2017-02-16 18:01
> Add properties reuse_addr and reuse_port to HTTP server, which are forwarded to the TCPServer when it is created in the call to bind

I don't know if making them properties of `HTTPServer` is a good idea, because since `bind` has been called, thoses properties are non-sense, I would rather put them as `bind` arguments

**Comment by asterite** [comment] 2017-02-16 18:05
@Bew78LesellB Note that for `HTTP::Server` you first create one with `new` and then invoke `listen` on it, which will internally invoke `HTTP::Server#bind`. This creates a `TCPServer` where `TCPServer#bind` is invoked. So we can set properties of the HTTP server *before* listening and it will work.

We *could* add these as named arguments in `listen` and `bind`, but maybe it's more convenient to have it as a configuration of the HTTP server. In any case, both scenarios work.

**Comment by rdp** [comment] 2017-02-16 21:35
Or possibly let people pass in a proc that takes a Socket parameter [?]
(before listen)...

**Closed** 2017-02-20 15:59 UTC
Labels: status:discussion

**Comment by whidbey** [comment] 2019-09-30 07:40
want to bookmark this feature.
