### ISSUE TITLE
Incorrect method called in inheritance - possibly related to generics

### ISSUE THREAD

**Issue by icy-arctic-fox** [crystal-lang/crystal#7813] opened 2019-05-22 20:08 UTC
Sorry in advance, but I'm having trouble distilling the code that reproduces the issue. The issue reproduces itself in a shard I wrote.

What I'm seeing is that the wrong method in an inheritance hierarchy is being called. Given a hierarchy like this:

```crystal
class A
  def foo
    puts self.class
  end
end

class B < A
  def foo
    puts self.class
  end
end

class C(T) < B
  def foo
    puts self.class
  end
end

list = [] of B
list << C(Int32).new
list << C(Symbol).new

list.each do |item|
  item.foo
end

# Output:
# C(Int32)
# B
```

The example above works on it's own, and I'm having trouble reproducing in a simpler context. Sorry about that.

So the first instantiation works fine, but subsequent objects with a different generic type don't.
The parent type's `#foo` is called instead of the object's actual `#foo`. There's no calls to `super`.

Here's a gist that reproduces the issue.
https://gist.github.com/icy-arctic-fox/4043b16ecfa496144684e3b66350a09b
Just save all files into a directory, run `shards`, then `crystal main.cr`.

I've monkey-patched the relevant code to add debug lines. It shows that `self.class` is the correct type, but that the parent's method was called instead. The debug lines show the method that was called and the value of `self.class`. The last line before it breaks shows it calls the wrong method.

I believe this has something to do with generics. I know they're [basically broken atm](https://github.com/crystal-lang/crystal/issues/2665), but adding it to the pile so that you're aware.

Crystal v0.28.0

**Comment by jhass** [comment] 2019-05-22 20:43
Seems to be fixed on latest master, I can reproduce with 0.28.0 but not `0.29.0-dev [6b6f2c43d]`

**Comment by icy-arctic-fox** [comment] 2019-05-22 20:45
Nice! That's good to know. Hopefully a short-lived issue then.

**Comment by asterite** [comment] 2019-05-22 20:48
@jhass Yay! Thanks. I was going to suggest that it might be fixed because I fixed a bunch of issues related to generics.

Should we close this and reopen just in case when 0.29.0 is released it doesn't work anymore (because of other changes)?

**Comment by icy-arctic-fox** [comment] 2019-05-22 21:01
That's fine by me. Glad to hear there's generics fixes going in.

**Closed** 2019-05-22 21:02 UTC

**Comment by oprypin** [comment] 2019-05-24 05:17
> Should we close this and reopen just in case when 0.29.0 is released it doesn't work anymore (because of other changes)?

Thaaat's a unittest asking to be added

**Comment by asterite** [comment] 2019-05-24 11:47
But for that I'll need a reduced example.
