### ISSUE TITLE
def Array(T).foo fails in 0.19.0

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#3265] opened 2016-09-06 05:58 UTC
Defining class method to Generic class on crystal ...

- 0.18.7 : :ok_woman: 
- 0.19.0 : :no_good: 
- master: :no_good: 

#### test.cr (a minimum reproducible code)

```crystal
class Foo
end

def Array(Foo).parse
  1
end
```

#### 0.18.7

```shell
% crystal -v
Crystal 0.18.7 [68783f1] (2016-07-03)
% crystal test.cr
# works
```

#### 0.19.0
```shell
% crystal -v
Crystal 0.19.0 [dcfb2b6] (2016-09-02)
% crystal test.cr
Syntax error in ./test.cr:4: unexpected token: (

def Array(Foo).parse
         ^
```

#### 0.19.0 (master)

as well as in master

```shell
% ./bin/crystal -v
Using compiled compiler at .build/crystal
Crystal 0.19.0+23 [e9ab595] (2016-09-06)
% ./bin/crystal test.cr
Using compiled compiler at .build/crystal
Syntax error in ./test.cr:4: unexpected token: (

def Array(Foo).parse
         ^
```

#### FYI : real code
- https://github.com/maiha/redis-cluster.cr/blob/master/src/cluster/node_info_parser.cr#L32

Thanks.

**Comment by asterite** [comment] 2016-09-06 11:29
Duplicate of #3190

This used to parse but it actually defined the method on every `Array` instance. Basically, there's no way to define methods on particular instantiations, so now the compiler gives an error for that.

**Comment by asterite** [comment] 2016-09-06 11:29
(I should have created an issue when I "fixed" this, and included this in the changelog)

**Closed by asterite** 2016-09-06 11:29 UTC

**Comment by asterite** [comment] 2016-09-06 11:31
Proof: https://play.crystal-lang.org/#/r/18ql
