### ISSUE TITLE
crystal 0.23 bug compiling in release on ubuntu

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#4744] opened 2017-07-24 15:48 UTC
Ubuntu 14.04.1 LTS
Crystal 0.23.1 [e2a1389e8] (2017-07-13) LLVM 3.8.1 (downloaded from releases page)

```
crystal eval 'p 1'
1
```

```
crystal eval 'p 1' --release
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/opt/crystal-0.23.1-3/bin/crystal: line 102:  5263 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by straight-shoota** [comment] 2017-07-24 16:27
Duplicate of #4719 
Please look for existing issues before posting a new one

**Closed** 2017-07-24 16:30 UTC
