### ISSUE TITLE
`JSON#as_a` and `JSON#as_h` should return `JSON::Any` instead of `JSON::Type`

### ISSUE THREAD

**Issue by Qwerp-Derp** [crystal-lang/crystal#5071] opened 2017-10-02 23:49 UTC
When `JSON#as_a` is used, it returns an array of `JSON::Type`. This is the same for `JSON#as_h` - it returns a hash of `(String, JSON::Type)`. We have essentially two separate JSON data types that we have to look for, when in reality we only really need one.

It's easy to convert a `JSON::Type` into a `JSON::Any`, and `JSON::Any` is easier to work with. I think we can change the `as_a` and `as_h` methods to return `Array(JSON::Any)` and `Hash(String, JSON::Any)` instead.

**Comment by asterite** [comment] 2017-10-03 12:39
Duplicate of #3158

**Closed by asterite** 2017-10-03 12:39 UTC

**Comment by Qwerp-Derp** [comment] 2017-10-03 23:18
Oh :P didn't see that, sorry!
