### ISSUE TITLE
Static build does not work on the latest alpine docker image with Crystal v1.8.0

### ISSUE THREAD

**Issue by pikapika2020** [crystal-lang/crystal#13329] opened 2023-04-17 16:31 UTC
Subj.

Steps to reproduce:
- `docker run -it crystallang/crystal:1.8.0-alpine sh`
- `echo 'require "xml"' > test.cr`
- `crystal build --static test.cr`

Output:
```
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -lxml2 (this usually means you need to install the development package for libxml2): No such file or directory
/usr/lib/gcc/x86_64-alpine-linux-musl/12.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -llzma (this usually means you need to install the development package for liblzma): No such file or directory
collect2: error: ld returned 1 exit status
Error: execution of command failed with exit status 1: cc "${@}" -o /test  -rdynamic -static -L/usr/bin/../lib/crystal -lxml2 -L/lib -lz -llzma -lm -lpcre2-8 -lgc -levent
```

Installation of libxml2-dev does not help.

`crystallang/crystal:1.7.3-alpine` docker image works fine

**Comment by Sija** [comment] 2023-04-17 16:55
The same happens for non-alpine images too.

**Comment by Blacksmoke16** [comment] 2023-04-17 16:57
This'll be resolved by https://github.com/crystal-lang/distribution-scripts/pull/242.

**Comment by straight-shoota** [comment] 2023-04-17 18:22
Duplicate of https://github.com/crystal-lang/distribution-scripts/issues/241

**Closed by straight-shoota** 2023-04-17 18:22 UTC
Labels: kind:bug
