### ISSUE TITLE
Flaky type inference when macro within {{ yield }} macro returns early

### ISSUE THREAD

**Issue by ysbaddaden** [crystal-lang/crystal#821] opened 2015-06-17 07:16 UTC
```crystal
macro pass
  return :pass
end

macro test(name, &block)
  def {{ name.id }}
    {{ yield }}
    nil
  end
end

test(:me) do
  pass
  ""
end

p me     # => nil
```

There are many things happening here, and I think I abused macros quite a bit. Yet, `me` should actually return `:pass` but since the generated method returns a `nil`, Crystal expects the return value to be a Nil. From this example it is very easy to generate segfaults (try to `puts "never reached"` before `nil`).

Workarounds:

- return from the block itself, so Crystal will infer from the block return types.
- return a Symbol instead of nil in the generated method (eg: `:ok`), so Crystal knows the return type is a Symbol (but it can't be anything else).

**Comment by asterite** [comment] 2015-06-17 13:43
@ysbaddaden Thanks! This is definitely a bug. I was able to reduce it to this:

```crystal
macro pass
  return :pass
end

def me
  pass
  nil
end

p me # nil
```

Note that this works well when not using a macro:

```crystal
def me
  return :pass
  nil
end

p me # :pass
```

On further investigation, if you do `p typeof(me)` at the end of each example you'll see the first one prints `(Symbol | Nil)` while the second one prints `Symbol`.

Luckily the fix was really easy. I'll explain the problem (why it fails because of the way it's implemented):

* Macro expansion happens at the first type inference stage (there are two stages): when "me" is instantiated, the "pass" call is found to be a macro, so it's expanded and is stored in that node (a `Call` node) as an "expanded" property.
* In the second phase we traverse the tree again. If we find a "return", "break" or "next" in a series of expressions, we drop the next ones so that the codegen phase doesn't have to deal with them (they are unreacahble). We also rebind the type to that return expression (this should never give an error because it will be a smaller type).

The problem was that we didn't traverse the "expanded" property of a Call to check for returns, etc. This explains why the type was incorrect. And the codegen was wrong too because it generated that last "nil" expression, resulting in two "ret" instructions (you can check this by using `VERIFY=1 crystal build foo.cr`, which runs LLVM validation... we don't always do this because it's slow).

The solution was a different one: the second phase transforms the resulting AST. I don't know why but previously we transformed the "expanded" property of a Call and stored it there. Now I changed it to return the "expanded" property, effecitvely (looking at the diff is easier to understand :-P). This also eliminated the "does this node have an expansion?" checks in the codegen phase, so it's a win-win :-)

**Comment by ysbaddaden** [comment] 2015-06-17 13:58
Thanks! Great explanation and quick fix, as always.

**Comment by ysbaddaden** [comment] 2015-06-22 09:16
I have a new issue that may be related. The following example won't pass on 0.7.3 but used to with the help of macros, as explained above, and it won't pass anymore on current master. The example doesn't make sense by itself, but I reduced a situation that happens in Artanis' test suite

```crystal
def call
  res = begin
    nil
    return
  end
end

call
```

This results in:
```
can't execute `res = begin
  nil
  return
end`
```

I suppose Crystal won't peek after the return (with good reasons) then decides that the begin/end is a NoReturn, has no type, and thus can't be assigned.

A workaround is to add a trailing condition that always evaluates to true, like this: `return if TRUE` — I use a constant since Crystal is smart enough to discard a trailing `if true`. Yet, I was wondering if it should actually pass, or not? Actually the `res =` part should never be reached.

NOTE: I'm using returns to pass/halt execution because there ain't no light throw/catch in Crystal, and raising an exception seems overkill.

**Comment by asterite** [comment] 2015-06-22 13:50
Interesting. In Ruby that gives a syntax error: "void value expression". If you do this in crystal:

```crystal
a = return
```

you will get the same error. I think in Crystal it should be the same.

Ruby seems pretty "smart" about this. For example:

```ruby
res = begin
  if 1 == 2
    return
  end
end
```

also gives the "void value expression". It seems you can't do a "return" inside an assignment. We should *probably* do the same thing.

**Comment by ysbaddaden** [comment] 2015-06-22 15:26
I suppose, yes.

For completeness: Ruby either discards the "begin" expression in your second example or the void expression bounces from "if" to "begin". Whatever the conditional, it won't accept the last statement to return. But... it passes with an unreachable statement or literal. Is Ruby tricked into thinking that the statement now evaluates to something? I'd expect Ruby to discard whatever is unreachable, but it doesn't:

```ruby
def call
  res = begin
    return
    1
  end
end

call
```

**Comment by asterite** [comment] 2016-05-08 18:06
@ysbaddaden I can't seem to reproduce the error of all of the above snippets. Do you think this is fixed now, in master?

**Comment by ysbaddaden** [comment] 2016-05-08 21:26
Itay be so. I think I still needed the `if return TRUE` trick in Artanis recently.

**Comment by asterite** [comment] 2016-09-29 11:45
@ysbaddaden I'm closing this because all the snippets above seem to be working for some time now, and fixing #3364 might have fixed some other cases like the reported one there. Please reopen if you bump into this again! :-)

**Closed by asterite** 2016-09-29 11:45 UTC
Labels: bug, compiler
