### ISSUE TITLE
Temporary variables from MultiAssign, Case, etc clash with local ones

### ISSUE THREAD

**Issue by zlotnleo** [crystal-lang/crystal#7332] opened 2019-01-22 15:25 UTC
I'm not entirely sure where 282 comes from, so I can't guarantee reproducibility in this exact form, but it seems to work repeatedly on my machine, so the numbers don't seem to be randomised.

When expanding the MultiAssign, Case and potentially other ASTNode's, the compiler doesn't check for the existence of temporary variables it uses in the current scope.

In the examples below `# => something` shows what the `puts` statement prints.

e.g. for MultiAssign:

    __temp_282 = 10
    a, b = 3, 4
    puts __temp_282 # => 3

Case is a bit more confusing, since it works "correctly" in this situation:

    __temp_282 = 10
    a = 4
    case a
    when Object
    end
    puts __temp_282 # => 10

However, the behaviour changes if there's a method call or a literal:

    __temp_282 = 10
    case 4
    when Object
    end
    puts __temp_282 # => 4

or

    __temp_282 = 10
    a = 4
    case a.to_s
    when Object
    end
    puts __temp_282 # => 4

I assume this could be fixed by either checking the scope or simply disallowing local variable names that begin with `__temp`.

**Comment by zlotnleo** [comment] 2019-01-22 15:40
It might be worth issuing a compile-time warning and adding it to the online reference

**Comment by asterite** [comment] 2019-01-22 15:42
The problem is that these variables are sometimes generated and copied to macros and parsed, and the compiler can't know whether a user or the compiler itself wrote them.

**Comment by zlotnleo** [comment] 2019-01-22 18:32
> why are you trying to use `__temp_xxx` variable names anyway?

To see if the compiler would notice them and change the names of the ones it generates, which it evidently doesn't.

**Comment by asterite** [comment] 2019-01-22 18:34
I assumed so. It's basically:
1. Check what the compiler generates
2. Try to use those variables
3. See how the compiler fails to handle this case

This is why I think fixing this has a very low priority, because unless you are trying to break the compiler this won't happen in real code (unless for some reason you like to name your vars `__temp_...`).

**Comment by j8r** [comment] 2019-01-22 18:55
Can it clash with temp vars generated by other macros?

**Comment by RX14** [comment] 2019-01-23 13:14
@j8r no, all the `__temp_` variable names are unique with a global counter.

**Comment by RX14** [comment] 2019-01-25 00:36
Should we close this?

**Closed** 2019-01-25 06:40 UTC
