### ISSUE TITLE
[Win32] Compiler crashes

### ISSUE THREAD

**Issue by tmssngr** [crystal-lang/crystal#12972] opened 2023-01-18 10:08 UTC
## Bug Report

I've unpacked `crystal-1.7.1-windows-x86_64-msvc-unsupported.zip` from https://github.com/crystal-lang/crystal/releases/tag/1.7.1 on a Windows 10 machine into an empy directory `C:\crystal`. I've created a file `main.cr` with the following content:

```
main

def main()
	puts "hello world"
end
```
and invoke the command `C:\crystal\crystal.exe main.cr` from the same directory. I'm getting following crash:
```
Error executing process: 'cl.exe /nologo _main.obj U-I-nt32.obj E-xception5858C-allS-tack.obj A-rray40S-tring41.obj P-ointer40S-tring41.obj I-nt32.obj F-loat64.obj I-nt64.obj A-rgumentE-rror.obj P-ointer40L-ibC-5858C-O-N-T-E-X-T-41.obj A-rray40P-ointer40V-oid4141.obj P-ointer40P-ointer40V-oid4141.obj E-N-V-.obj C-rystal5858S-ystem5858E-nv.obj C-rystal5858S-ystem.obj S-tring.obj P-ointer40U-I-nt841.obj T-uple40S-tring4432S-tring4432S-tring41.obj E-numerable5858R-eflect40I-nt3241.obj G-C-.obj U-I-nt64.obj S-lice40T-41.obj S-lice40U-I-nt841.obj P-ointer40U-I-nt1641.obj S-lice40U-I-nt1641.obj I-ndexE-rror.obj C-har5858R-eader.obj E-xception.obj S-taticA-rray40U-I-nt16443225641.obj W-inE-rror.obj C-har.obj R-untimeE-rror.obj U-nicode.obj A-rray40T-uple40I-nt324432I-nt324432I-nt324141.obj S-tring5858B-uilder.obj M-ath.obj S-taticA-rray40U-I-nt84432441.obj S-taticA-rray40U-I-nt8443212941.obj D-ivisionB-yZ-eroE-rror.obj P-ointer40T-uple40I-nt324432I-nt324432I-nt324141.obj R-ange40B-4432E-41.obj R-ange40I-nt324432I-nt3241.obj B-ool.obj T-ypeC-astE-rror.obj P-rocess.obj F-ile.obj C-rystal5858S-ystem5858F-ile.obj F-ile5858E-rror.obj U-I-nt8.obj T-uple40S-tring4432S-tring4432S-tring4432S-tring41.obj E-rrno.obj F-ile5858N-otF-oundE-rror.obj F-ile5858A-lreadyE-xistsE-rror.obj F-ile5858A-ccessD-eniedE-rror.obj F-ile5858E-rror43.obj P-ath.obj P-ath5858K-ind.obj T-uple4042T-41.obj T-uple40I-nt3241.obj T-uple40I-nt324432I-nt3241.obj N-il.obj E-numerable5858E-mptyE-rror.obj T-uple40C-har41.obj T-uple40C-har4432C-har41.obj S-taticA-rray40I-nt8443225641.obj P-ointer40I-nt841.obj T-uple40C-har4432-809e6e92b20f8837d04aeb284952aba9.obj R-ange40C-har4432C-har41.obj T-uple40C-har4432-da0bae55c641cf3666f281b8fea01988.obj T-uple40S-tring4432S-tring41.obj S-taticA-rray40U-I-nt8443251241.obj E-xception43.obj P-ointer40L-ibC-5-c47a0e048fdbf37e7b6d1e4778e5f8d3.obj D-ir.obj C-rystal5858S-ystem5858D-ir.obj U-nicode5858C-aseO-ptions.obj H-ash40I-nt324432-c36c7b59ada9577e04b34b7156d26117.obj P-ointer40H-ash58-df002967aa38240c2ffc8370480b96df.obj C-rystal5858H-asher.obj S-taticA-rray40U-I-nt644432241.obj P-ointer40U-I-nt6441.obj I-ntrinsics.obj H-ash5858E-ntry40-ea883736b6a497e8c0f2d29083b2162a.obj P-ointer40U-I-nt3241.obj A-rray40T-uple40I-nt324432I-nt324141.obj P-ointer40T-uple40I-nt324432I-nt324141.obj P-ath5858P-artI-terator.obj I-terator40T-41.obj I-terator5858S-top.obj S-taticA-rray40U-I-nt164432141.obj L-ibC-5858S-T-A-C-K-F-R-A-M-E-64.obj P-ointer40V-oid41.obj E-xception5858C-allS-tack5858R-epeatedF-rame.obj C-rystal5858A-tE-xitH-andlers.obj A-rray40P-roc40I--412183da1a81233e2c20c488cb2e890d.obj P-ointer40P-roc40-6252237c86bac28658266374d639ebc8.obj T-hread5858L-inke-203c55f1c4be503afabe353d210e31e7.obj T-hread5858M-utex.obj F-iber5858S-tackP-ool.obj D-eque40P-ointer40V-oid4141.obj F-iber.obj T-hread5858L-inkedL-ist40F-iber41.obj S-lice40U-I-nt6441.obj C-rystal5858S-ystem5858R-andom.obj I-nt128.obj U-I-nt128.obj I-O-5858F-ileD-escriptor.obj C-rystal5858S-ystem5858F-ileD-escriptor.obj A-tomic40T-41.obj A-tomic40I-nt3241.obj I-O-5858E-rror.obj F-ile5858I-nfo.obj L-ibC-5858B-Y-_H--6cfa1b255452e05129f70d8a5abeedfc.obj F-ile5858T-ype.obj N-otI-mplementedE-rror.obj I-O-5858F-ileD-escriptor43.obj T-ime5858S-pan.obj C-rystal5858S-cheduler.obj T-hread.obj A-tomic40U-I-nt841.obj A-tomic40T-hread3212432N-il41.obj P-roc40N-il41.obj F-iber5858C-ontext.obj T-hread5858L-inkedL-ist40T-hread41.obj N-ilA-ssertionE-rror.obj C-rystal5858E-ventL-oop.obj C-rystal5858I-ocp5858E-ventL-oop.obj D-eque40C-rystal5858I-ocp5858E-vent41.obj P-ointer40C-rystal5858I-ocp5858E-vent41.obj C-rystal5858S-pinL-ock.obj D-eque40F-iber41.obj P-ointer40F-iber41.obj C-rystal5858I-ocp5858E-vent.obj T-ime.obj C-rystal5858S-ystem5858T-ime.obj C-rystal5858S-ystem5858P-rocess.obj L-ibG-C-5858S-tackB-ase.obj S-taticA-rray40L--aa9c3495927510a36f0144adf6252906.obj P-ointer40L-ibC-5-a1f86dffb0160510ac15a075aa5b591a.obj B-ox40I-O-5858O-v-2232051b5dbe000225c59a6ca5d8444a.obj I-O-5858O-verlapp-c4a74ab6b0b5a3a9eab30c616cb39de6.obj I-O-5858O-verlapped5858O-verlappedO-peration.obj C-hannel5858T-imeoutA-ction.obj C-hannel5858S-electC-ontext40N-il41.obj C-hannel5858S-electC-ontextS-haredS-tate.obj A-tomic40C-hannel5858S-electS-tate41.obj C-rystal5858S-ystem5858F-iber.obj I-O-5858E-ncoder.obj C-rystal5858I-conv.obj S-taticA-rray40U-I-nt84432102441.obj T-ime5858L-ocatio-c92d7ae948ed8f4d38520c6d460d1469.obj T-ime5858L-ocation5858I-nvalidL-ocationN-ameE-rror.obj T-ime5858L-ocation5858I-nvalidT-Z-D-ataE-rror.obj T-ime5858F-ormat5858E-rror.obj T-ime5858F-loatingT-imeC-onversionE-rror.obj P-ath5858E-rror.obj F-ile5858B-adP-atternE-rror.obj C-hannel5858C-losedE-rror.obj B-ase645858E-rror.obj I-O-5858E-O-F-E-rror.obj I-O-5858T-imeoutE-rror.obj E-numerable5858N-otF-oundE-rror.obj O-verflowE-rror.obj K-eyE-rror.obj I-nvalidB-yteS-equenceE-rror.obj P-roc40F-iber4432-6eb246a0a45118d3c5507cc830b14a70.obj S-taticA-rray40U-I-nt6444321541.obj H-ash40T-uple40U-I-nt644432S-ymbol414432B-ool41.obj P-ointer40H-ash58-60a3eb55c544b99184778abc7dcee256.obj H-ash40U-I-nt644432U-I-nt6441.obj P-ointer40H-ash58-6ca1ab2004fcb02b740a9bf3b468352a.obj H-ash40S-tring443-d0ef6a484ca24b5e9e1cd150630d96a3.obj P-ointer40H-ash58-78e716075e5ec360a5549c235b8e9c11.obj C-rystal5858O-nceS-tate.obj A-rray40P-ointer40B-ool4141.obj P-ointer40P-ointer40B-ool4141.obj P-ointer40B-ool41.obj F-loat32.obj C-rystal.obj /FeC:\\Users\\tom\\AppData\\Local\\crystal\\cache\\crystal-run-main.tmp.exe /link /DEBUG:FULL /PDBALTPATH:%_PDB% /INCREMENTAL:NO /STACK:0x800000 /LIBPATH:C:\\crystal\\lib gc.lib /ENTRY:wmainCRTStartup libcmt.lib iconv.lib advapi32.lib Kernel32.lib shell32.lib ole32.lib WS2_32.lib kernel32.lib legacy_stdio_definitions.lib DbgHelp.lib libucrt.lib': The system cannot find the file specified. (File::NotFoundError)
  from C:\crystal\crystal.exe +277238 in '??'
  from C:\crystal\crystal.exe +277134 in '??'
  from C:\crystal\crystal.exe +277098 in '??'
  from C:\crystal\crystal.exe +8559 in '??'
  from C:\crystal\crystal.exe +2080070 in '??'
  from C:\crystal\crystal.exe +1613636 in '??'
  from C:\crystal\crystal.exe +1613357 in '??'
  from C:\crystal\crystal.exe +15917174 in '??'
  from C:\crystal\crystal.exe +15909061 in '??'
  from C:\crystal\crystal.exe +15927341 in '??'
  from C:\crystal\crystal.exe +18904821 in '??'
  from C:\crystal\crystal.exe +18866919 in '??'
  from C:\crystal\crystal.exe +18846769 in '??'
  from C:\crystal\crystal.exe +18844683 in '??'
  from C:\crystal\crystal.exe +18844618 in '??'
  from C:\crystal\crystal.exe +6618 in '??'
  from C:\crystal\crystal.exe +2175417 in '??'
  from C:\crystal\crystal.exe +2175194 in '??'
  from C:\crystal\crystal.exe +94329 in '??'
  from C:\crystal\crystal.exe +94611 in '??'
  from C:\crystal\crystal.exe +47565300 in '??'
  from C:\WINDOWS\System32\KERNEL32.DLL +95764 in 'BaseThreadInitThunk'
  from C:\WINDOWS\SYSTEM32\ntdll.dll +337569 in 'RtlUserThreadStart'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
Even if some required tool is missing, it should show a meaningful error message and not crash.

**Comment by Blacksmoke16** [comment] 2023-01-18 14:10
Given this is the newest one, going to close it as a duplicate of #12877, #12839, and #12631.

See https://github.com/crystal-lang/crystal/issues/12839#issuecomment-1351130764 for a possible solution.

**Closed by Blacksmoke16** 2023-01-18 14:10 UTC
Labels: kind:bug, status:duplicate, platform:windows, topic:compiler:codegen

**Comment by tmssngr** [comment] 2023-01-18 18:04
Like I wrote, please ensure that the bundle does not crash, even if some essential part is missing. Instead, please catch this case and report an error, e.g. "The required xxxx is missing. Aborting."

**Comment by Blacksmoke16** [comment] 2023-01-18 18:09
@tmssngr https://github.com/crystal-lang/crystal/pull/12899 should help with that yea.
