### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#8471] opened 2019-11-14 20:34 UTC
Hi,

I think I've found a issue in `compiler`.

I have posted the logfile in https://gist.github.com/waghanza/8b2971e2ee76b6443412b03ee307d65b

Apparently the https://github.com/tbrand/neph is not compilable on my environment

+ Crystal version : `Crystal 0.31.1 (2019-10-01)`
+ LLVM version : `LLVM: 9.0.0`
+ Compilation target : `Default target: x86_64-unknown-linux-gnu`
+ OS
   + LSB Version:	:core-4.1-amd64:core-4.1-noarch
   + Distributor ID:	Fedora
   + Description:	Fedora release 31 (Thirty One)
   + Release:	31
   + Codename:	ThirtyOne

Regards,

PS : I have used https://copr.fedorainfracloud.org/coprs/zawertun/crystal @zawertun

----------
/cc @tbrand As the `author` of **neph**

------
The original `shard.yml` is in https://github.com/waghanza/http-benchmark/blob/use_alpine/shard.yml

-----
Using `--release` **flag**, I have not the issue

**Comment by ZaWertun** [comment] 2019-11-14 20:55
Hello!
Maybe it's packaging issue 🤔
I can rebuild crystal package with llvm-8 for Fedora 31.

**Comment by asterite** [comment] 2019-11-14 20:59
Duplicate of https://github.com/crystal-lang/crystal/issues/8236

Will be fixed in 0.32.0 (already fixed in `master`)

**Comment by asterite** [comment] 2019-11-14 21:00
Forgot to say: it's because you are using LLVM 9, which is not yet supported by Crystal (but will be in the next release).

**Closed by asterite** 2019-11-14 20:59 UTC
