### ISSUE TITLE
Unable to assign ivar of type `Proc(M)` to value of type `Proc(C)` when class `C` includes module `M`

### ISSUE THREAD

**Issue by decademoon** [crystal-lang/crystal#12370] opened 2022-08-08 23:33 UTC
Crystal 1.5.0 (2022-07-06)
LLVM: 14.0.6
Default target: aarch64-apple-darwin21.6.0

The following code fails to compile ([play](https://play.crystal-lang.org/#/r/dkqa)):

```crystal
module M
end
 
class C
  include M
end
 
class K
  @m : -> M
  
  def initialize
    @m = -> do # Error
      C.new
    end
  end
end
 
K.new
```

```text
error in line 12
Error: instance variable '@m' of K must be Proc(M), not Proc(C)
```

But if I do this equivalent code it works ([play](https://play.crystal-lang.org/#/r/dkqc)):

```crystal
module M
end
 
class C
  include M
end
 
class K
  @m : -> M
  
  def initialize
    @m = -> do
      m = uninitialized M
      if true
      	m = C.new
      end
      m
    end
  end
end
 
K.new
```

**Comment by HertzDevil** [comment] 2022-08-09 01:04
`Proc` is invariant. This is intentional.

**Comment by decademoon** [comment] 2022-08-09 01:31
Why does my second code work? It's functionally equivalent to the first code.

**Comment by straight-shoota** [comment] 2022-08-09 10:56
The code is not equivalent. In the second example, there's a conditional branch of control flow (even though `if true` always matches). In the then branch, the assigned type is `C` but in the else branch, the type is unchanged (`M`), thus when combining both branches, you get a union of `C` and `M`. The compiler implicitly summarizes that as `M` (because `C` is a subtype).

**Comment by straight-shoota** [comment] 2022-08-09 11:01
I suppose the compiler could potentially be smarter and recognize that `if true` is always truthy and eliminate the possibility of an else branch entirely. This already happens in codegen. There is no actual conditional in the generated code. But the semantic analysis doesn't take that into account. Not sure if there's a specific reason for that (probably there is, I just don't recall).

**Comment by decademoon** [comment] 2022-08-09 11:22
I just realized I can get the first code to compile if I force the type to `M` ([play](https://play.crystal-lang.org/#/r/dkui)):

```crystal
module M
end

class C
  include M
end

class K
  @m : -> M
  
  def initialize
    @m = -> do
      C.new.as M
    end
  end
end

K.new
```

But I'm not sure why this is necessary. Is this to do with Crystal not supporting covariance and contravariance?

**Comment by straight-shoota** [comment] 2022-08-09 11:28
Yes, it's necessary because the type arguments of `Proc` are invariant (https://github.com/crystal-lang/crystal/issues/12370#issuecomment-1208774821).

**Comment by straight-shoota** [comment] 2022-08-09 11:30
Duplicate of #7306

**Closed by straight-shoota** 2022-08-09 11:30 UTC
Labels: status:duplicate, kind:question

**Comment by straight-shoota** [comment] 2022-08-09 11:31
FTR: Casting the return type to the expected type is the best cause of action.
