### ISSUE TITLE
What about using MCJIT for crystal eval/run?

### ISSUE THREAD

**Issue by vifino** [crystal-lang/crystal#852] opened 2015-06-24 17:03 UTC
Hey guys.

First up, awesome job! :+1:

`crystal eval` uses tempfiles as it's output and then runs them, I'd like to avoid this, because `crystal eval` may get called absurdly often.
Same with `crystal run`.

What about using [MCJIT](http://llvm.org/docs/MCJITDesignAndImplementation.html) and maybe a fallback interpreter, just like `lli`, instead of the tempfile way?

It would be a very nice alternative from my point of view.

I toyed around a little in the codebase, sadly I think I need a while to understand what is going on :P

Greetings,
vifino

**Comment by ozra** [comment] 2015-06-24 19:05
Did you see this one for getting up to speed? https://github.com/manastech/crystal/wiki/Compiler-internals

Would be great if similar functionality like concepts and macros in Nim could become part of the language and utilize JIT tech or other way of avoiding writing an entire crystal interpreter in order to run macros etc. Disclaimer: I don't know much about the macros yet, they just looked simplistic in the doc..

On a side note: What if temp files where stored in temp ram disk - good enough?

**Comment by kirbyfan64** [comment] 2015-06-24 19:06
@ozra I think RAM disks are insanely not-portable. If someone wants to use one, I believe they can override the temporary directory Crystal uses and create the disk themselves.

**Comment by asterite** [comment] 2015-06-24 19:35
@vifino Hi! We are actually using the MCJIT for some specs, the ones that don't require the full prelude. As far as I remember, we had some issues with it and exception handling. For example you can write this program:

```crystal
# interpreter.cr
require "compiler/crystal/**"

program = Crystal::Program.new
program.run File.read(ARGV[0])
```

Compile it:

```
crystal build interpreter.cr
```

And give it this file:

```crystal
# boom.cr
require "prelude"

puts "hello"
if 1 == 1
  raise "OH NO"
end
```

Now run it:

```
CRYSTAL_PATH=~/Projects/crystal/src ./interpreter boom.cr
```

(I'm setting CRYSTAL_PATH to the `src` directory of the compiler because the default one is just "libs"). This will result in a segfault and I have no idea why. Maybe if we solve this we can switch to use the MCJIT.

BUT... what if the MCJIT doesn't behave **exactly** the same as an executable? (maybe because of a bug in the JIT). Then we will have to deal with two "implementations" of the language, which makes things harder.

The same applies if we ever decide to interpret part of the language: we will have to maintain two different behaviours.

Now I'll talk a bit about macros :-)

The reason why macros are simple is because they are intended for simple things. If you want to do a complex thing you can use the [run](http://crystal-lang.org/api/index.html#http%3A//crystal-lang.org/api/Macros.html%23run%2528filename%252C%2520%252Aargs%2529%2520%253A%2520MacroId-instance-method) macro method, in which you get to program in Crystal, its full set, not just a subset. This means there's only one language and one implementation. 

I personally (and this is just my personal opinion, my guess is that @waj and @bcardiff  might disagree with me) don't like abusing macros because then it becomes harder to understand the code. It makes you spend more time thinking about how to make the code cleaner, avoid redundancy and squeeze the compiler to its maximum rather than just focus on the problem at hand. The macros I remember in the std are:

* `getter`, `setter`, etc., which are just to avoid a small boilerplate
* `pp`: just for nicer debugging
* `record`: to define an immutable struct with some properties (like a record :-)
* `spawn`: to abstract away the fact that a Fiber is created
* `ecr`: to transform a file in another language to crystal (with this you could implement things like haml, slim, etc., although all of these are less powerful than in Ruby)
* some macros in `Enum` to traverse its constants and provide `to_s` or `parse` methods
* macro defs `to_s` and `inspect`: just iterate through the instance variables to show them (they are also used for `Struct#==` and `Struct#hash`). `def_hash`, `def_equals`, etc. also fall in this category (using the instance variables of a type for something)
* `json_mapping`: which, given a description of a JSON object, basically generates a specific JSON parser, but this is made possible very easily because other things (notably a pull parser) are already implemented. The macro itself is less than 100 lines of code and relies on no other macros. To get to this point we first thought how would we make it without a macro and just then figured out the pattern that needed to be extracted.
* `marshal`: this is in a branch, but @waj was working on this. It basically inspects an object's instance varaibles at compile time to know what needs to be marshalled. This could easily be done without macros, but this way it avoids boilerplate code.

I think macros should be used to avoid small boilerplate. But once it becomes hard to understand the macros themselves I think that's when one is abusing them. But, again, this is just my personal opinion. I also feel that successful (at the industry) languages have no, or a limited form, of macros. I think that makes everyone being capable of understanding what's going on without having to decipher obscure code.

**Comment by waj** [comment] 2015-06-24 19:42
@asterite I see you don't mention metaprogramming. Ruby is said to be strong in this aspect and for a compiled language that don't want to rely on runtime reflection, macros is the best choice in my opinion.

**Comment by vifino** [comment] 2015-06-24 19:52
@ozra: Thanks, didn't see that before! :+1: 

Hello @asterite!

That is awesome!
I'm thinking that making it optional, with a flag like `--mcjit` or via environment variables, would be awesome.
While I don't think there is much of a difference since they are going the same code paths, I do see the problem.
Maybe implement it and use it only for `crystal eval` by default, making it available as a flag for `crystal run`?

Sadly I can't run the interpreter :(

```
[vifino:~/code/crystaljit]$ CRYSTAL_PATH=~/code/crystal/src ./interpreter boom.cr
LLVM ERROR: Cannot select: 0x48c4c70: i64 = X86ISD::WrapperRIP 0x48bc2d0 [ORD=2] [ID=6]
  0x48bc2d0: i64 = TargetGlobalTLSAddress<i32* @errno> 0 [TF=10] [ORD=2] [ID=4]
In function: *FileDescriptorIO#unbuffered_write<FileDescriptorIO, Slice(UInt8), Int32>:Int32

```

**Comment by asterite** [comment] 2015-06-24 19:55
@vifino what code are you feeding the interpreter? For example if you always raise instead of doing it conditionally then it crashes, but that's a known issue (but doesn't matter much because you can't trigger it via the compiler).

**Comment by vifino** [comment] 2015-06-24 19:56
@asterite: I'm running your example code, compiled with yesterdays git :)

**Comment by ozra** [comment] 2015-06-24 20:59
The interpreter example above: does the `run` method use mcjit? Or did I get that wrong?

Regarding macros (at the risk of OT tainting this issue). There are successful languages in the industry that are homo-iconic, and they're growing in numbers.
Not all code can be understood by all people. In projects I've worked on there's often a "black box" part of the system that is _way more_ advanced - and risky - then the rest, in order to make the rest of the coding effortless to others on the team working "on the surface" of the system.
I find macros very good for facilitating and making development safer and with less boiler plate for a majority, while maybe one or two coders are concerned with the gory intestines, which often can be hardened and then rarely have to be touched once in place. It's great for DSL like things.

Perhaps `eval` as complement to `run` should be avail in macros, keeping the "external code" in the macro?

Out of the box crazy idea: Would it be possible to pass an entire function body / block to a macro, send that off as a string via 'run', use the compiler class in the external file (like your example) to parse it, then work on the AST, let the compiler render it to crystal source again, then return it to the calling macro!?

How separated are the compilation stages when using the compiler class?

**Comment by asterite** [comment] 2015-06-24 21:47
@vifino Strange, I'll try to reproduce it.

@ozra That's one thing that you can do with `run`. For example there's [this](https://github.com/manastech/crystal_ruby/blob/master/sample/test_ruby.cr), which basically lets you write a class and it generates (if one day we decide to continue it) a class using Ruby's C API, together with its methods. Here's the [macro](https://github.com/manastech/crystal_ruby/blob/master/src/ruby.cr#L56) and here's the [implementation](https://github.com/manastech/crystal_ruby/blob/master/src/processor.cr).

When using the compiler class all the stages are mixed. You'd use the `Program` class to parse, infer types and do the codegen if you want to do those separately (the compiler uses it so you can learn how it's done).

**Comment by ozra** [comment] 2015-06-25 00:30
@asterite - thanks for the links - that kicks serious butt! Then most everything imaginable is possible :-)

**Comment by vifino** [comment] 2015-06-25 19:32
@asterite In case you didn't know, that issue is related to LLVM 3.6.X.

It changed some things :)

**Comment by asterite** [comment] 2016-03-18 20:48
I'll close this. We prefer not to use the JIT when doing `crystal eval` because it might behave different than not using a JIT, so it'll be another point of pain.

**Closed by asterite** 2016-03-18 20:48 UTC
Labels: compiler, draft, RFC
