### ISSUE TITLE
Wrong resolution of macros

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#3993] opened 2017-02-03 12:47 UTC
```cr
class Foo
  @buffer = [] of String

  def record(line : String)
    @buffer.shift?
    @buffer << line
  end

  def record(line : String? = nil)
    line ||= ""
    yield line
    # works when using `self.record`
    record line
  end
end

Foo.new.record { }
```

Above example fails with:

```
Error in line 17: instantiating 'Foo#record()'

in line 13: macro didn't expand to a valid program, it expanded to:

================================================================================
--------------------------------------------------------------------------------
   1.   struct line
   2.     
   3. 
   4.     def initialize()
   5.     end
   6. 
   7.     
   8. 
   9.     def clone
  10.       line.new()
  11.     end
  12.   end
--------------------------------------------------------------------------------
Syntax error in expanded macro: record:1: can't define struct inside def

  struct line
  ^

================================================================================
```

Problem is that `record` call is resolved to `macro record` instead of `#record` instance method.

**Comment by asterite** [comment] 2017-02-07 22:55
Duplicate of #236

**Closed by asterite** 2017-02-07 22:55 UTC
