### ISSUE TITLE
`BigDecimal#round` regression

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#10599] opened 2021-04-04 19:07 UTC
## Bug Report

Used to work before v1.0:

```cr
require "big"
```

```cr
1.2345.to_big_d.round(1) # => 1.2
```

Crystal 1.0 borks with:

```
In /usr/lib/crystal/number.cr:410:22

 410 | shifted = self * multiplier
                      ^
Error: no overload matches 'BigDecimal#*' with type Float64

Overloads are:
 - BigDecimal#*(other : BigDecimal)
 - BigDecimal#*(other : Int)
 - Number#*(other : BigFloat)
```

---

Probably broken by #10413.

**Comment by straight-shoota** [comment] 2021-04-05 11:43
`Number#round` doesn't work for `BigDecimal` yet anyway because the new rounding methods introduced in #10413 are not implemented. This is essentially a duplicate of #5714.

**Comment by Sija** [comment] 2021-04-05 12:03
@straight-shoota It's not a duplicate but a separate bug report, since the `Number#round` method was working for `BigDecimal` before.

**Comment by straight-shoota** [comment] 2021-04-05 12:22
Just fixing this specific error won't do any good without #5714 because it just moves on to another error 🤷

**Comment by Sija** [comment] 2021-04-05 12:38
Yes, I know, we better have #5714 resolved but it's still a regression, whatever is the reason.

**Comment by hugopl** [comment] 2021-06-01 22:07
Got hit by this today trying to recompile an old code (that worked on 0.36.1) on 1.0.0. Just to confirm that this is really a 1.0.0 regression.

**Closed** 2021-06-17 23:06 UTC
Labels: kind:bug, kind:regression, topic:stdlib:numeric
