### ISSUE TITLE
Typing of ivars does not play well with macros

### ISSUE THREAD

**Issue by beta-ziliani** [crystal-lang/crystal#14976] opened 2024-09-05 16:39 UTC
Consider the following code:

```cr
class A
  def initialize
  {% if true %}
    @test = 1
  {% end %}
  end
end

A.new
```

It fails with

```
There was a problem expanding macro 'macro_4784306592'

Which expanded to:
 > 1 | 
 > 2 |     @test = 1
           ^----
Error: can't infer the type of instance variable '@test' of A
```

However, the macro-generated code is semantically valid.

**Comment by straight-shoota** [comment] 2024-09-05 16:41
Duplicate of #7975

**Closed by straight-shoota** 2024-09-05 16:41 UTC
Labels: kind:bug, topic:compiler:semantic, topic:lang:macros
