### ISSUE TITLE
OptionParser silently ignores subcommands with hyphens

### ISSUE THREAD

**Issue by fdr** [crystal-lang/crystal#9908] opened 2020-11-12 03:54 UTC
Demonstrated in this program is one subcommand that works, and one that does not. The one that works contains interior hyphens that I don't think should be ambiguous with any flag-like meaning, but probably are causing some trouble:

```crystal
require "option_parser"

parser = OptionParser.new do |parser|
  parser.on("hello-world", "print 'hello world'") do
    puts "hello world"
  end

  parser.on("goodbye_world", "print 'goodbye world'") do
    puts "goodbye world"
  end
end

puts parser
parser.parse
```

It gives output like this. Note that only running the `goodbye_world` subcommand delivers the `puts` output.

```
$ crystal run src/bug.cr -- hello-world
    hello-world                      print 'hello world'
    goodbye_world                    print 'goodbye world'
$ crystal run src/bug.cr -- goodbye_world
    hello-world                      print 'hello world'
    goodbye_world                    print 'goodbye world'
goodbye world
```

**Comment by straight-shoota** [comment] 2020-11-12 11:23
This is already fixed in master. Duplicate of #9465.

To get it working for you, you can try a nightly release, wait for 1.0.0-pre1 or just simply copy the fixed version of `parse_flag_definition` into your source code.

**Closed by straight-shoota** 2020-11-12 11:23 UTC
