### ISSUE TITLE
cast to Crystal::NonGenericOrGenericClassInstanceType failed

### ISSUE THREAD

**Issue by trapped** [crystal-lang/crystal#1716] opened 2015-10-09 17:23 UTC
I'm getting this [error](https://gist.github.com/trapped/d53bf9947bc917e6ddac) when trying to do this:
```crystal
require "active_record"
class User < ActiveRecord::Model
# ...
end

def func : Array(Class.class)
  models = [User]
  models.map(&.not_nil! as Class) as Array(Object.class)
end
```

**Comment by jhass** [comment] 2016-06-06 18:35
Closing this as it was never reduced to a testcase that's quickly to triage on carc.in and I can't reproduce on 0.17.4 with the provided one (after fixing active_record.cr for it).

**Closed by jhass** 2016-06-06 18:35 UTC
Labels: bug, compiler
