### ISSUE TITLE
forall in enums is broken?

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7532] opened 2019-03-09 15:20 UTC
https://carc.in/#/r/6gid:

```crystal
enum Foo
  Bar

  def type
    case value
    when 0 then Int32
    else
      raise "BUG"
    end
  end
end

def foo(foo : Foo, type : T.class = foo.type) forall T
  {% pp! T %}
end

foo(:bar)
```

```
# Expected:
T # => Int32

# Got (as expected):
T # => Int32
```

https://carc.in/#/r/6gif:

```crystal
enum Foo
  Bar
  Baz

  def type
    case value
    when 0 then Int32
    when 1 then String
    else
      raise "BUG"
    end
  end
end

def foo(foo : Foo, type : T.class = foo.type) forall T
  {% pp! T %}
end

foo(:bar)
```

```
# Expected:
T # => Int32
T # => String

# Got:
T # => Int32
```

https://carc.in/#/r/6gii:

```crystal
enum Foo
  Bab
  Bar
  Baz

  def type
    case value
    when 0 then Float32
    when 1 then Int32
    when 2 then String
    else
      raise "BUG"
    end
  end
end

def foo(foo : Foo, type : T.class = foo.type) forall T
  {% pp! T %}
end

foo(:bar)
```

```
# Expected:
T # => Float32
T # => Int32
T # => String

# Got:
T # => Float32
```

As @asterite mentioned in #7533, 

> Arguments are solved first. The compiler doesn't know what T is in the restriction for y.

But looks like the compiler actually _knows_ the restriction and it does it wrong. I expect either of these:

1. Get the expected output
2. Raise `undefined constant T` in all cases

**Comment by vladfaust** [comment] 2019-03-09 15:29
Ugh, it's too specific

**Comment by vladfaust** [comment] 2019-03-09 15:53
Okay, this is actually a bug.

**Comment by r00ster91** [comment] 2019-03-09 18:54
It should work with the **Edit** button next to **New issue** (in the top right).
![Unbenannt](https://user-images.githubusercontent.com/35064754/54075904-f987b100-42a4-11e9-886f-eaf242248169.PNG)

**Comment by asterite** [comment] 2019-03-10 11:38
I'm sorry but it's not clear to me what the issue is. Bug reports shouldn't include what the compiler does right now. You should explain how it behaves now, how's that's wrong, and what's your expected behaviour.

**Comment by vladfaust** [comment] 2019-03-10 13:33
@asterite I've updated the issue

**Comment by asterite** [comment] 2019-03-10 14:47
I still don't get it. You expect the method to be invoked or instantiated multiple times?

**Comment by vladfaust** [comment] 2019-03-10 14:53
I expect it to either do not instantiate at all (raising `undefined constant T`) or instantiate multiple times.

**Comment by bew** [comment] 2019-03-10 15:59
I don't get it, how could it instantiate multiple times? you only call `foo` once..
Also, `typeof(Foo::Bar.type)` is the union of all the return values, how could it only one since `Foo::Bar.type` is 'evaluated' at runtime only?

I'm guessing you want something like:
```cr
enum Foo
  Bar
  Bazzz

  def type
    {% if @enum.value == 0 %}
      Int32
    {% elsif @enum.value == 1 %}
      String
    {% end %}
  end
end

typeof(Foo::Bar.type) # => Int32
typeof(Foo::Bazzz.type) # => String
```
Where `@enum` would be available in an enum' instance method, and represent the current instance of the enum, with its value / member' name / ...

**Comment by asterite** [comment] 2019-03-10 16:05
So, I think there might be a bug with a type restriction against a default value (that has a special logic, which I didn't code). But what you want is impossible. You seem to want a runtime type at compile time.

**Comment by jhass** [comment] 2020-01-08 07:37
@asterite wanna open a new issue about the bug you mention?

In any case I think there's no action for this issue and would vote to close it.

**Comment by asterite** [comment] 2020-01-08 11:21
No, sorry, I'm taking some vacations from Crystal.

**Comment by HertzDevil** [comment] 2021-08-06 04:38
Reduced:

```crystal
def foo
  rand > 0.5 ? Int32 : String
end

def bar(x : T.class = foo) forall T
  T
end

bar # => Int32
```

**Comment by straight-shoota** [comment] 2022-10-27 16:17
Calling the method with an argument instead of using the default value gives a semantic error:
```cr
def foo
  rand > 0.5 ? Int32 : String
end

def bar(x : T.class = foo) forall T
  T
end

bar(foo) # Error: no overload matches 'bar' with type (Int32.class | String.class)
```

**Comment by straight-shoota** [comment] 2022-12-09 11:25
Closing in favour of https://github.com/crystal-lang/crystal/issues/12829 for a clean focus

**Closed by straight-shoota** 2022-12-09 11:25 UTC
Labels: kind:bug, topic:compiler:semantic
