### ISSUE TITLE
Array of arrays crashes Playground

### ISSUE THREAD

**Issue by marynowac** [crystal-lang/crystal#7325] opened 2019-01-19 17:35 UTC
When I run a below code at Crystal Playground

    c = Array(Array(Int32 | Char | String)).new
    c << ['a']
    c << ['b', 99, "foo"]

the bug is returned

    E, [2019-01-19 14:30:15 +01:00 #91140] ERROR -- : Instrumention bug found (session=1, tag=1).

and exception throwed

    Module validation failed: Function return type does not match operand type of return inst!
      ret i32* %1, !dbg !11
     %"Array(Char | Int32 | String)"*

Outside the playground that code works as expected [link](https://carc.in/#/r/61fr)

**Comment by RX14** [comment] 2019-01-19 17:46
Duplicate of https://github.com/crystal-lang/crystal/issues/6997

**Closed by RX14** 2019-01-19 17:46 UTC
