### ISSUE TITLE
Inifinite loop on iteration

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3510] opened 2016-11-06 21:58 UTC
I imagine it has something to do with Int32 vs Int64, nonetheless...

```
(0..10000000000).each{ |x| x }
```

probably shouldn't loop forever. (I let it run for 35 minutes before I gave up.) Note,

```
(0..1000000000).each{ |x| x }
```

took just 1.82 seconds.

**Comment by asterite** [comment] 2016-11-07 09:43
This is because `10000000000` is a Int64, and the iterated value is Int32, so it eventually overflows. In the future this will raise an overflow exception.

**Comment by trans** [comment] 2016-11-07 12:35
You can't make it smart enough to use a larger iterator? Can't it look at the return type of `#size`?

**Comment by lbguilherme** [comment] 2016-11-08 11:35
A possible solution is to disallow Ranges with two different types. But that may be too much of a limitation in some scenario.

**Comment by rdp** [comment] 2016-11-30 13:24
you'd think/hope you could make this a compile time failure ideally...maybe .each could only accept ranges within Int32 range somehow?

**Comment by bcardiff** [comment] 2016-11-30 13:48
Maybe when parsing a range tokens if they are literals we could use the larger type BUT that special rule will open the scenario of `int32_variable...int64_literal`, should it be cast?

So maybe the solution is for the current value of the range while iterating be something that depends on both `B` and `E` of a `Range(B, E)`.

For people to followup from the code. https://github.com/crystal-lang/crystal/blob/master/src/range.cr#L101 the `current` is of type B (beginning) despite the type E (end). This happens on the range iterators as well.

Note that `(1..3.5).to_a => [1, 2, 3] : Array(Int32)` and that was something intentional.

**Comment by asterite** [comment] 2016-12-13 18:56
Closing as duplicate of #3103 . We'll eventually handle overflows in a better way.

**Closed by asterite** 2016-12-13 18:56 UTC
