### ISSUE TITLE
Macro raise doesn't keep location

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#7147] opened 2018-12-05 00:54 UTC
Extracted from #6125 (https://github.com/crystal-lang/crystal/issues/6125#issuecomment-423640385)

```cr
macro raise_on(node)
  {% node.raise "node '#{node}' is here!" %}
end

macro will_raise_soon(node)
  # this is a helper macro
  raise_on {{node}}
end

macro will_raise(node)
  # this is a helper macro
  will_raise_soon {{node}}
end

will_raise :this
```
I think this should report the error `node ':this' is here!` at the last line (`will_raise :this`), without any trace (but allow to show it with `--error-trace`)

(might need a change in how macro's `raise` is reported)

---
_thought on this by @MakeNowJust:_ https://github.com/crystal-lang/crystal/pull/7008#issuecomment-434555247
> The reason what [#6125 (comment)](https://github.com/crystal-lang/crystal/issues/6125#issuecomment-423640385) does not work is for re-raising an error with node calling macro location [here](https://github.com/crystal-lang/crystal/blob/43010c806cab99290b9361790159268fa3761c76/src/compiler/crystal/semantic/semantic_visitor.cr#L417-L418):
> 
> ```crystal
>   def eval_macro(node)
>     yield
>   rescue ex : MacroRaiseException
>     node.raise ex.message, exception_type: MacroRaiseException
>   rescue ex : Crystal::Exception
>     node.raise "expanding macro", ex
>   end
> ```

**Comment by bew** [comment] 2019-02-08 12:27
Actually it doesn't even work correctly (IMO) currently with a single macro call:

For exemple, with this (normal macro raise):
```cr
macro macro_raise
  {% raise "Raised in here" %}
end

macro_raise
```
We get:
```
Error in macro_raise.cr:5: Raised in here

macro_raise
^~~~~~~~~~~

```
Which is nice.

---

Now if we raise on a specific node in a macro (doesn't work as I would expect):
```cr
macro macro_raise_on(arg)
  {% arg.raise "Raised here on #{arg}" %}
end

macro_raise_on :this
```
We get:
```
Error in macro_raise.cr:5: Raised here on :this

macro_raise_on :this
^~~~~~~~~~~~~~

```
But I would expect:
```
Error in macro_raise.cr:5: Raised here on :this

macro_raise_on :this
               ^~~~~

```

Fixing this might fix the original code (https://github.com/crystal-lang/crystal/issues/7147#issue-387545421), but I'm not sure.

**Comment by asterite** [comment] 2019-02-21 14:11
Yes, this is strange. I think it used to work in the past.

**Comment by franciscoadasme** [comment] 2019-03-26 23:44
edit: I just realized that I meant to post this here instead of the other, related issue #7394.

Another (more problematic) case is when requiring a file that calls a macro that raises, where the error message points to the require statement instead of the macro call location, e.g.,

```crystal
# foo.cr
struct Foo
  macro foo
    {{ raise "error when calling foo" }}
  end
end

# bar.cr
require "./foo"

Foo.foo

# baz.cr
require "./bar.cr"
```

when running `bar.cr`, you get (expected behavior)

```
Error in bar.cr:3: error on foo

Foo.foo
    ^~~
```

but if you run `baz.cr`, you get

```
Error in baz.cr:1: error on foo

require "./bar"
^
```

If you have several nested files (or when bar.cr is very large), it'll be very difficult to find the aggravating line

**Comment by Blacksmoke16** [comment] 2020-05-09 00:58
@bew, would you not expect the trace to show the line that was raised in macro land when using `arg.raise`?  I.e.

```cr
In test.cr:2:11

 2 | {% node.raise "node '#{node}' is here!" %}
             ^----
Error: node ':this' is here!
```

then using `--error-trace` would go up the tree:
```cr
ccrystal test.cr --error-trace
Using compiled compiler at .build/crystal
There was a problem expanding macro 'will_raise'

Called macro defined in test.cr:10:1

 10 | macro will_raise(node)

Which expanded to:

 > 1 | # this is a helper macro
 > 2 | will_raise_soon :this
Error: expanding macro


There was a problem expanding macro 'will_raise_soon'

Called macro defined in test.cr:5:1

 5 | macro will_raise_soon(node)

Which expanded to:

 > 1 | # this is a helper macro
 > 2 | raise_on :this
Error: expanding macro


In test.cr:2:11

 2 | {% node.raise "node '#{node}' is here!" %}
             ^----
Error: node ':this' is here!
```

**Comment by bew** [comment] 2020-05-09 08:34
No, that's the whole point of this issue: when I use node.raise, I expect to see the error pointing to the node in question, where it is actually written in the original code.

In your trace I find it hard to find the node you raised on for example.

**Comment by asterite** [comment] 2020-05-09 11:16
I agree with @bew

**Comment by Blacksmoke16** [comment] 2020-05-09 14:38
Ah, you mean like:
```bash
Error in macro_raise.cr:5: Raised here on :this

macro_raise_on :this
               ^~~~~
```
like you mentioned earlier.

Yea that makes sense.

Maybe this is a slightly different issue then.  In Athena I provide a fair bit of compile time errors by raising on specific nodes (like a specific class/method).  However currently this is what happens:
```
Showing last frame. Use --error-trace for full trace.

In test.cr:26:18

 26 | pp RouteResolver.new
                       ^--
Error: Routes can only be defined as instance methods.  Did you mean 'RoutingController#user'?
```
https://play.crystal-lang.org/#/r/91b6

Which isn't really helpful at all.

IMO ideally it would be like:

```
 8 | def self.user : Nil
         ^--------
Error: Routes can only be defined as instance methods.  Did you mean 'RoutingController#user'?
```

**Comment by asterite** [comment] 2020-05-09 15:04
You both want the same thing. The problem is that raise on a node doesn't retain that location and it's swallowed by the call that invokes the macro. That's the bug. If we fix that, both cases will be fixed.

**Comment by straight-shoota** [comment] 2023-03-30 07:26
> My question now is there a way to create a new exception that retains the trace of the last one? Mainly given the trace is handled via some C lib and not really part of the exception API. 

The source code traces are actually not unrelated to libunwind. The frames are represented as nested instances of `CodeError`, each with an associated source location.

OT: If it *was* an actual runtime stacktrace, the `Exception#callstack` property can be freely assigned and copied (example: https://carc.in/#/r/es60).

**Comment by Blacksmoke16** [comment] 2023-03-31 04:26
Okay, so I was playing around with this more today. I was able to have it generate full traces like the following by changing https://github.com/crystal-lang/crystal/blob/38155d19a9297a2b24f5b39953c5bcfde9fc4b76/src/compiler/crystal/semantic/semantic_visitor.cr#L458 to simply be `raise ex` so it retains the location of the previous node, not the this new one.

```cr
In test.cr:28:5

 28 | foo(1)
          ^
Error: OH

NO
```
and
```cr
In test.cr:31:6

 31 | {{ raise "OH NO" }}
         ^----
Error: OH NO
```
with correct locations, but without the extra `expanding macro` and such. However the more complex Athena based example isn't working exactly like I'd expect and is acting like it in master.

I did some debugging by updating https://github.com/crystal-lang/crystal/blob/38155d19a9297a2b24f5b39953c5bcfde9fc4b76/src/compiler/crystal/semantic/ast.cr#L12 to be `pp!(exception_type.for_node(self, message, inner))` and the previous examples produce a single line like `exception_type.for_node(self, message, inner) # => #<Crystal::MacroRaiseException:OH NO>`. However the more complex example is like:

```cr
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant U>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant U>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant T>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant T>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant T>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant T>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant T>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Number in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use Hash(K, V) in unions yet, use a more specific type>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:can't use underscore as generic type argument>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant ADVD::Valdatable
Did you mean 'AVD'?>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:undefined constant ADVD::Valdatable
Did you mean 'AVD'?>
exception_type.for_node(self, message, inner) # => #<Crystal::MacroRaiseException:Routes can only be defined as instance methods. Did you mean 'RoutingController#user'?>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:Routes can only be defined as instance methods. Did you mean 'RoutingController#user'?>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:expanding macro>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:expanding macro>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:expanding macro>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:expanding macro>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:expanding macro>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:instantiating 'Athena::DependencyInjection::ServiceContainer#athena_route_handler()'>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:instantiating 'Athena::Framework::Server.class#new(Int32, String, Bool, Nil, Array(HTTP::Handler))'>
exception_type.for_node(self, message, inner) # => #<Crystal::TypeException:instantiating 'Athena::Framework:Module#run()'>
```

So to me it seems there's a bunch of other random errors that muddy the trace/location of the error such that it uses the location of my actual `Routes can only be defined as instance methods. Did you mean 'RoutingController#user'` error on the `Def` node.

Imma try to reduce this behavior to something easier to debug. Could just be a different bug :shrug:.

**Closed** 2023-04-27 07:42 UTC
Labels: kind:bug, topic:compiler
