### ISSUE TITLE
Hash-like Type Literal doesn't work for empty hashes

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#9616] opened 2020-07-17 03:51 UTC
https://crystal-lang.org/reference/syntax_and_semantics/literals/hash.html#hash-like-type-literal

```cr
Hash(String, String).new # => OK
{} of String => String # => OK
Hash(String, String){} # => Error: for empty hashes use '{} of KeyType => ValueType'
```

If this is expected I'll create a PR to add a note to the book.

**Comment by asterite** [comment] 2020-07-17 11:09
Duplicate of #9551

**Comment by asterite** [comment] 2020-07-17 11:10
Well, this is for Hash, not Set, but it's understood it should work for all these types.

**Closed by asterite** 2020-07-17 11:09 UTC
