### ISSUE TITLE
Compiler cannot infer type of instance variable when using macro

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang/crystal#6976] opened 2018-10-22 06:40 UTC
```crystal
struct Foo
  def initialize
    @data = Float32.static_array(0f32, 0f32)
  end
end

Foo.new
```

If you run this code (see it in playground: [link](https://play.crystal-lang.org/#/r/5ama)) you will see that compiler was unable to guess the type of **data** instance variable. 

If you look at the source code of **Number.static_array** macro (here: [link](
https://github.com/crystal-lang/crystal/blob/391785249f66aaf5929b787b29810aeb4af0e1e8/src/number.cr#L65)), you will see that it's basically creating uninitialized StaticArray and returning it.

This should work if you recall that there is a rule about inferring type from use of uninitialized. I suppose the problem lies in the macro.

Someone trying to fix this, might be interested in somewhat similar issue: https://github.com/crystal-lang/crystal/issues/6935

**Comment by z64** [comment] 2018-10-22 14:08
This is expected when you assign an ivar to something that has been called, and its type can no longer be inferred

Basically: https://carc.in/#/r/5aq8

Expanding the macro: https://play.crystal-lang.org/#/r/5aqa

The compiler isn't "smart" enough to do this yet, which is why #6935 is marked as a feature request. I would indeed say this is a duplicate of #6935 ; I don't think there's anything different happening here - macros don't play into the type system this way.

**Comment by asterite** [comment] 2018-11-29 13:44
Yes, "type inference" for instance vars doesn't work with macros, and will never work.

**Closed by asterite** 2018-11-29 13:44 UTC
