### ISSUE TITLE
formatter delete blank line between comment.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#12826] opened 2022-12-08 13:28 UTC
## Bug Report

Following is a example:

```crystal
require "socket"

# line 1

# line 2
```

After save, it formatted to:

```crystal
require "socket"

# line 1
# line 2
```

I consider this is not a correct behavior, because the commented line probably is commented code, it should't change commented code.

Thanks

**Comment by straight-shoota** [comment] 2022-12-08 13:37
Note that this only happens for single comment lines.

Blocks of multiple comments are not merged:
```cr
# line 1
# line 2

# line 3
# line 4
```

If the latter comment is a doc comment, the empty line is not removed either:

```cr
# line 1

# line 2
def foo
end
```

So I'm wondering if this might be at least semi-intended behaviour?
I don't see a real benefit though, and I probably wouldn't expect the formatter to remove the empty line.

**Closed** 2023-02-02 18:07 UTC
Labels: kind:bug, topic:tools:formatter
