### ISSUE TITLE
BUG: `value` at eval:17:12 has no type

### ISSUE THREAD

**Issue by docelic** [crystal-lang/crystal#4668] opened 2017-07-04 12:16 UTC
1) Code to reproduce

```crystal
require "yaml"

module X
  alias Virtual = Nil | Int32 | Bool

  
  class Y
    def initialize
    end
    def initialize( arg)
      end
    
    def self.from_yaml(value : YAML::PullParser) : Virtual
      true
    end
    def self.to_yaml(value : Virtual, yaml : YAML::Builder)
      case value
      when Int32,Bool
      	yaml.scalar value
      when Range
      	yaml.scalar "range"
    end
    end
  end
end

class X::Z
    YAML.mapping({
        value:  { type: Virtual, nilable: true, converter: X::Y},
        })
  def initialize
  end

end

a= X::Z.new
a.value= true
puts a.to_yaml  # ==> BUG: `value` at eval:17:12 has no type
```

2) Code on play: https://play.crystal-lang.org/#/r/2atg

3) Similar bug? (not sure) https://github.com/crystal-lang/crystal/issues/4158

**Comment by akzhan** [comment] 2017-07-04 13:19
It will work when you set concrete type once, https://play.crystal-lang.org/#/r/2av9

**Comment by vlazar** [comment] 2019-10-13 15:30
No crash in Crystal 0.31.1 anymore. Fixed?

```
$ crystal --version
Crystal 0.31.1 (2019-10-02)

LLVM: 8.0.1
Default target: x86_64-apple-macosx
```

```
$ crystal test.cr
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'mapping'

Code in test.cr:29:3

 29 | YAML.mapping({
      ^
Called macro defined in /usr/local/Cellar/crystal/0.31.1/src/yaml/mapping.cr:70:3

 70 | macro mapping(_properties_, strict = false)

Which expanded to:

 > 114 |               X::Y.to_yaml(_value, __temp_26)
 > 115 |
 > 116 |           end
                            ^------
Error: no overload matches 'X::Y.to_yaml' with types (Bool | Int32), YAML::Nodes::Builder

Overloads are:
 - X::Y.to_yaml(value : Virtual, yaml : YAML::Builder)
 - Object#to_yaml(io : IO)
 - Object#to_yaml()
```

**Comment by asterite** [comment] 2019-10-13 23:24
Yes, it doesn't reproduce anymore, and now it gives a compile error because the YAML interface changed.

But I updated the code to use the latest YAML API and it compiles fine.

So I'll close this. But please open if you find a similar way to reproduce the issue.

**Closed by asterite** 2019-10-13 23:24 UTC
Labels: kind:bug, topic:compiler
