### ISSUE TITLE
Bool type for YAML::Type

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2235] opened 2016-02-26 16:28 UTC
Is there any reason that the [`Type` alias](https://github.com/crystal-lang/crystal/blob/master/src/yaml/yaml.cr#L54) doesn't include Bool? Especially since we have the following available: https://github.com/crystal-lang/crystal/blob/90eaec10cef83941628409cf4e064acaba140fdb/src/yaml/from_yaml.cr#L26

JSON::Type includes Bool. We also don't have as easy `as_bool` method for YAML::Any, which I can understand since YAML types aren't quite as simple. However, without Bool being included in `YAML::Type`, I can't even `as Bool` on a value.

**Comment by asterite** [comment] 2016-02-29 14:48
Right now we implement the [failsafe schema](http://www.yaml.org/spec/1.2/spec.html#id2802346). We might want to implement the [core schema](http://www.yaml.org/spec/1.2/spec.html#id2804923), though.

**Comment by asterite** [comment] 2016-08-06 16:19
I'm closing this as a duplicate of #3101, which has a more general title

**Closed by asterite** 2016-08-06 16:19 UTC
Labels: enhancement, standard library
