### ISSUE TITLE
Complier allow to instanciate an abstract (virtual) class

### ISSUE THREAD

**Issue by I3oris** [crystal-lang/crystal#10635] opened 2021-04-14 18:04 UTC
Hello,

I found a hack to instantiate an abstract class, that shouldn't be possible:

```crystal
abstract class Foo
end

class Bar < Foo
end

class Baz < Foo
end

{Bar | Baz}[0].new # => #<Foo:0x7ff30d4c6ea0>
```
So, you can make it crash with an abstract def:
```crystal
abstract class Foo
  abstract def abstract_def
end

class Bar < Foo
  def abstract_def
  end
end

class Baz < Foo
  def abstract_def
  end
end

foo = {Bar | Baz}[0].new

foo.abstract_def # => Invalid memory access (signal 11)
```

**Comment by HertzDevil** [comment] 2021-04-14 18:10
Duplicate of #3835

**Comment by I3oris** [comment] 2021-04-14 18:17
Oh!, that an old issue, i didn't see it when i have searched 'abstract'..

**Closed** 2021-04-14 18:18 UTC
Labels: kind:bug
