### ISSUE TITLE
Inconsistent UX with float parsing between Any and Float64

### ISSUE THREAD

**Issue by z64** [crystal-lang/crystal#10438] opened 2021-02-23 12:27 UTC
It would be nice if `as_f` had the same ergonomics as `Float64`:
```cr
require "json"

p Float64.from_json("123.45") # => 123.45
p Float64.from_json("123")    # => 123.0

p JSON.parse("123.45").as_f # => 123.45

# but this fails:
begin
  p JSON.parse("123").as_f
rescue ex
  puts(ex.inspect_with_backtrace)
end

# workaround for same behavior with Any:
any = JSON.parse("123")
p (any.as_f? || any.as_i).to_f # => 123.0
```

**Comment by asterite** [comment] 2021-02-23 12:31
Maybe Float64 from_json is wrong, I don't know what happens with a really big int number. Maybe it doesn't matter.

**Comment by z64** [comment] 2021-02-23 12:41
On the eve of 1.0, making `Any#as_f` consistent is a non-breaking change - at least I don't think so. 

Anyone who wanted the above behavior would already be doing something like `any.as_f? || any.as_i`, but `Float64` has handled both.... forever at this point? Users who need to handle servers that give them numbers like this would have to switch to using `Union` deserialization at the least (which is not great IMO)

```cr
struct T
  include JSON::Serializable
  getter value : Int64 | Float64
end
```
or do the dance of writing a converter.

Someone can survey other langs maybe; thats about all I have to add here.

**Comment by straight-shoota** [comment] 2021-02-23 12:48
There's no inconsistency here. `as_f` is explicitly not a conversion method (hence it's called `as`, not `to`). It just gives type safe access to the raw value of `JSON::Any`. `123` is parsed as an integer, so `as_f` fails because the raw value is not a float.

Changing `as_f` to cast the value would probably be unexpected. Instead, we could consider adding `#as_number` which you could then use to call `to_f`. Or add `to_i` and `to_f` directly to `Any` but I suppose that could be ambiguous about numeric strings.

`JSON::Serializable` is an entirely different thing It doesn't even use `JSON::Any`. So I don't see a connection with the serializable example.

**Comment by asterite** [comment] 2021-02-23 13:00
I guess there's some logic to this request. If you parse an API response and want to get a float, you would use as_f. But if the API choses to omit the decimal point for some values then your program has a latent bug.

I think we should introduce to_i and to_f that just fo their best to get an Int32 or Float64 out of the underlying values, even converting from strings if the underlying value is a string. After all all these methods will end up in a runtime error if used in correctly.

**Comment by z64** [comment] 2021-02-23 13:01
> JSON::Serializable is an entirely different thing It doesn't even use JSON::Any. So I don't see a connection with the serializable example.

Of course they are not the same... inconsistency, whatever you want to call it - I just had to explain all of the above to a new Crystal user why `Float64.from_json` and `as_f` are different behavior and it feels bad.

`Any` already confuses users enough, I answer questions about it all the time. Now they have to do `as_number`?

`to_i` / `to_f` sounds good if we want to flag that a conversion is happening.

**Comment by z64** [comment] 2021-02-23 13:13
The `JSON::Serializable` example, I was just walking through what I think would happen if we made `Float64.from_json` raise on `123`, just like `as_f` raises on that token. It indeed had nothing to do with `Any`, or my question in the OP.

Users who use `Float64.new(pull)` - *via `Serializable`* - would have to resort to union deseraizliation or a converter to retain the same behavior.

**Comment by straight-shoota** [comment] 2021-02-23 13:14
> Users who use Float64.new(pull) - via Serializable - would have to resort to union deseraizliation or a converter to retain the same behavior.

Sorry, I don't follow. What same behaviour?

**Comment by asterite** [comment] 2021-02-23 13:17
@straight-shoota he means, why Float64.from_json succeeds for int values instead of raising? I think that's inconsistent.

**Comment by z64** [comment] 2021-02-23 13:17
`Float64.new(pull)` already handles int or float tokens

https://github.com/crystal-lang/crystal/blob/0.36.1/src/json/from_json.cr#L116-L125

If we hypothetically went the "other way" and made this raise on `kind.int?`, they would have to do something else to get that behavior back if they were relying on it, like the person who asked me a question that started this issue.

(And I don't think we should do this)

**Comment by straight-shoota** [comment] 2021-02-23 13:30
Just to clarify: That scenario doesn't make any sense (so it's not going to happen). `Float64.from_json` should never fail for a numeric value. In JSON `1` is as much a float as `1.0`, they're both just a number. If we explicitly parse a float, both are obviously valid.

The relevant difference between `Floa64.from_json` and `JSON::Any` is that the former has a Crystal type associated. Parsing `JSON::Any` there's no type information, it just matches JSON values to the best fitting Crystal type. And here `1` and `1.0` differ. `as_f` just represents that difference. And nothing else.

**Comment by z64** [comment] 2021-02-23 13:34
Yes. We were just exploring it because @asterite mentioned an off the cuff concern for large values. https://github.com/crystal-lang/crystal/issues/10438#issuecomment-784168010

On top of that `Float64.new(pull)` has already had this behavior for a very long time (AFAIK) so I don't think it makes sense to break it even if there was an actual motivation.

**Comment by HertzDevil** [comment] 2021-08-06 04:42
Duplicate of #8618.

**Closed by HertzDevil** 2021-08-06 04:42 UTC
Labels: kind:feature, topic:stdlib:serialization
