### ISSUE TITLE
abstract struct require class variables to be initialized

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#2957] opened 2016-07-05 19:39 UTC
```crystal
abstract struct Foo
  @@a : Int32
end

struct Bar < Foo
  @@a = 0
end
```

Compiles in 0.18.6 but it doesn't in 0.18.7

https://play.crystal-lang.org/#/r/1344
https://play.crystal-lang.org/#/r/1343

I don't think the changes in 0.18.7 aimed for this to happen.
But maybe I missed something.

**Comment by asterite** [comment] 2016-07-05 19:42
Probably shouldn't have compiled in 0.18.6 either.

This is a duplicate of #2827 and I don't think it's a bug (but of course it can be discussed)

**Closed** 2016-07-05 19:42 UTC
Labels: bug, compiler, duplicate
