### ISSUE TITLE
iterative flat_map on iterators crashes the compiler by infinite memory growth

### ISSUE THREAD

**Issue by f-fr** [crystal-lang/crystal#11459] opened 2021-11-16 09:49 UTC
Consider the following code
```crystal
list = { {1, 2, 3}, {4, 5, 6} }.each
2.times do
  list = list.flat_map do |list|
    { {1, 2, 3}, {4, 5, 6} }.each
  end
end
```
Compiling this will cause the compiler to eat up all the memory (so probably some kind of infinite loop). The code compiles fine if, e.g., the initial value of `list` is not an iterator but a plain tuple:
```crystal
list = { {1, 2, 3}, {4, 5, 6} }   # this compiles fine
2.times do
  list = list.flat_map do |list|
    { {1, 2, 3}, {4, 5, 6} }.each
  end
end
```
Crystal version: 
```
% crystal --version
Crystal 1.2.2 [6529d725a] (2021-11-10)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by HertzDevil** [comment] 2021-11-16 09:52
Duplicate of #7044.

**Closed by HertzDevil** 2021-11-16 09:52 UTC
Labels: kind:bug
