### ISSUE TITLE
Including JSON::Serializable lets you invoke a default constructor

### ISSUE THREAD

**Issue by Indribell** [crystal-lang/crystal#7308] opened 2019-01-13 01:25 UTC
Here we have the following examples:

```
class Address
  include JSON::Serializable

  property id : Int64
  property latitude : Float64
  property longitude : Float64
end

class User
  include JSON::Serializable

  property id : Int64
  property firstname : String
  property lastname : String
  property address : Address
end
```

Working example:
```
user = User.new()
user.firstname = "J"
user.lastname = "M"
user.address = Address.new()
user.address.latitude = 0.11111
```

The following code works perfectly.

Now, if we "forgot" to initialize the address class...

```
user = User.new()
user.firstname = "J"
user.lastname = "M"
#### user.address = Address.new()
user.address.latitude = 0.11111
```

We are greeted with a unreadable dump in the logs:

```
Invalid memory access (signal 11) at address 0x10
[0x55e21f622836] *CallStack::print_backtrace:Int32 +118
[0x55e21f60c850] __crystal_sigfault_handler +192
[0x7f3cba294dd0] ???
[0x55e21f72be30] ???
[0x55e21f6e524f] *ServiceLogin#get_login<HTTP::Server::Response, HTTP::Request>:IO+ +239
[0x55e21f6e4cc0] *ServiceLogin#run_routes<HTTP::Server::Response, HTTP::Request>:(IO+ | Int32 | Nil) +192
[0x55e21f613bec] ~procProc(HTTP::Server::Context, Nil) +252
[0x55e21f7293a4] *HTTP::ErrorHandler +708
[0x55e21f728f80] *HTTP::ErrorHandler#call<HTTP::Server::Context>:(Bool | IO+ | Int32 | Nil) +32
[0x55e21f728b47] *HTTP::LogHandler +375
[0x55e21f7286bc] *HTTP::LogHandler#call<HTTP::Server::Context>:Nil +156
[0x55e21f73b705] *HTTP::Server::RequestProcessor#process<IO+, IO+, IO::FileDescriptor>:Nil +2149
[0x55e21f73ae99] *HTTP::Server::RequestProcessor#process<IO+, IO+>:Nil +57
[0x55e21f73aa9b] *HTTP::Server#handle_client<IO+>:Nil +315
[0x55e21f614378] ~procProc(Nil) +24
[0x55e21f643d16] *Fiber#run:(IO::FileDescriptor | Nil) +182
[0x55e21f60bfa6] ~proc2Proc(Fiber, (IO::FileDescriptor | Nil)) +6
[0x0] ???
```

Crystal is not able to pick up, that we are addressing a property that does not exist during the the compilation. And thus crashes during runtime, when we indeed try to access a non-existing property.

Only by forcing nil:

```
class User
  include JSON::Serializable

  property id : Int64
  property firstname : String
  property lastname : String
  property address : Address?
end
```

Does the compiler actually check

```

instantiating 'get_login(HTTP::Server::Response, HTTP::Request)'
in src/ServiceLogin.cr:40: undefined method 'latitude=' for Nil (compile-time type is (Address | Nil))

    user.address.latitude = 0.11111
                 ^~~~~~~~

Rerun with --error-trace to show a complete error trace.
```

This leaves me with a few questions:

1. Why are there no compiler checks on the "property address : Address" being performed? This leaves Crystal open to runtime crashes with error reports that are frankly unreadable. If code like this got into production, even by accident...

2. Why can Crystal not auto initiate the Address class, when the compiler knows its part of the property. This makes sense as to easy things for us developers :)

**Comment by asterite** [comment] 2019-01-13 01:39
It's a compiler bug that is triggered by the constructor defined in JSON::Serializable

**Comment by asterite** [comment] 2019-01-17 22:54
Duplicate of #7007

**Closed by asterite** 2019-01-17 22:54 UTC
Labels: kind:bug, topic:compiler

**Comment by kostya** [comment] 2019-01-17 23:14
you can generate initialize method with: https://github.com/kostya/auto_initialize

```crystal
require "json"
require "auto_initialize"

class Address
  include JSON::Serializable
  include AutoInitialize

  property id : Int64
  property latitude : Float64
  property longitude : Float64
end

class User
  include JSON::Serializable
  include AutoInitialize

  property id : Int64
  property firstname : String
  property lastname : String
  property address : Address
end

user = User.new(firstname: "J", lastname: "M", id: 0_i64, address: Address.new(id: 1_i64, latitude: 1.0, longitude: 2.0))
p user
p user.to_json
```
