### ISSUE TITLE
GZip IO Fails on Very Large gzip Files

### ISSUE THREAD

**Issue by rvictory** [crystal-lang/crystal#8418] opened 2019-11-01 18:41 UTC
I have a very large gzip file (the .COM TLD Zone file, it is 3.2GB compressed and about 14GB uncompressed). I am reading it using crystal's GZip library in the STDLIB. The issue I run into is that there appears to be a problem with an integer counter in the library overflowing due to the size of the data that has been decompressed. Here's the error (Crystal 0.31.1 on both Ubuntu 16.04 LTS and macOS):

```
Unhandled exception: Arithmetic overflow (OverflowError)
  from /usr/share/crystal/src/gzip/reader.cr:0:16 in 'unbuffered_read'
  from /usr/share/crystal/src/io/buffered.cr:214:12 in 'fill_buffer'
  from /usr/share/crystal/src/io/buffered.cr:102:7 in 'peek'
  from /usr/share/crystal/src/io.cr:692:18 in 'gets_peek'
  from /usr/share/crystal/src/io.cr:636:9 in 'gets'
  from /usr/share/crystal/src/io.cr:605:5 in 'gets'
  from /usr/share/crystal/src/io.cr:575:5 in 'gets'
  from /usr/share/crystal/src/io.cr:574:3 in 'gets'
  from fast_scanner.cr:25:9 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:97:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:86:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:106:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

Here would be some example code to trigger the error, however you'd need a sufficiently large gzip file to do so:

```
require "gzip"
io = File.open("large_gzip_file.gz")
gzip_reader = GZip::Reader.new(io)
while line = gzip_reader.gets
  # Do something
end
gzip_reader.close
```

I have tried changing `@isize` in gzip/reader.cr to be an unsigned 64 bit int but that introduced another problem with comparisons later down the line. I am no expert on how gzip works, so I don't know what I can fix it any further. Let me know if you need more clarification.

Thanks!

**Comment by j8r** [comment] 2019-11-01 19:46
The size goes beyond `UInt32::MAX`, which is used to read bytes.
This type is used, partly because `Int32` is the default type.
https://github.com/crystal-lang/crystal/issues/8111 could solve this.

**Comment by rvictory** [comment] 2019-11-01 20:18
Right, I am aware of that issue, the other issue is if you change it to be a UInt64 it still doesn't work.

**Comment by straight-shoota** [comment] 2019-11-01 20:21
This seems like a duplicate of #3209

**Comment by rvictory** [comment] 2019-11-01 20:22
@straight-shoota I don't think so. I am reading line by line, not into memory.

**Comment by straight-shoota** [comment] 2019-11-01 20:34
Yes, it shows differently, but the core issue is that size counters are only 32 bits wide when they need to be able to count to 64 bit numbers. In one case it's `Slice#@size` in the other it's `Gzip::Reader#@isize`. The reason is identical. And needs to be fixed. #8111 is a proposal to do that.

**Comment by rvictory** [comment] 2019-11-01 20:35
Ah, this makes sense. I agree they should be 64 bits or more, however (and I'm sure there is discussion about this) would that maybe cause some performance issues since I think that large files are not the norm?

**Comment by straight-shoota** [comment] 2019-11-01 20:47
On 64 bit systems there is no penalty for using 64 bit numbers. The trouble is 32 bit systems and how to choose default types (should they depend on the architecture?) and how to apply them.

Large files might not be everyone's regular use case, but they're certainly not uncommon. Crystal needs to be able to handle that. There is no way we can seriously declare Crystal not-fit for file sizes > 4 GB.

**Comment by straight-shoota** [comment] 2019-11-01 20:57
As it turns out, this is actually a different issue. In the gzip format `isize` is defined as `UInt32`, it can't hold a 64 bit value and implementations just store the last bits if the file size is bigger than `UInt32::MAX`.. So it seems the addition should actually just wrap and everything works.

You can try passing `-Ddisable_overflow` to the compiler.

**Closed** 2019-11-02 00:35 UTC
