### ISSUE TITLE
alias using generic types

### ISSUE THREAD

**Issue by pbrusco** [crystal-lang/crystal#3049] opened 2016-07-26 03:51 UTC
Is it possible to define generic aliases? 

I would like to have something like `alias AB(T) = T | Tuple(AB(T), AB(T))` to represent Haskell like, binary trees.

**Comment by pbrusco** [comment] 2016-07-26 03:52
Example I want to generalize:
 
```crystal
# alias AB(T) = T | Tuple(AB(T), AB(T))
alias ABInt = Int32 | Tuple(ABInt, ABInt)

def fold(e : ABInt, fLeaf : Int32 -> T, fRec : Proc(T, T, T)) : T
  case e
  when Int32
    fLeaf.call(e)
  when Tuple(ABInt, ABInt)
    rec1 = fold(e.fst, fLeaf, fRec)
    rec2 = fold(e.snd, fLeaf, fRec)
    fRec.call(rec1, rec2)
  else
    raise "type Error"
  end
end

struct Tuple
  def fst
    self[0].not_nil!
  end

  def snd
    self[1].not_nil!
  end
end

puts fold( {13,{15,16}}, ->(b : Int32){b}, ->(reci : Int32, recd : Int32){reci + recd } )
```

**Comment by asterite** [comment] 2016-07-26 12:21
Duplicate of #2803 :-)

**Closed by asterite** 2016-07-26 12:21 UTC
