### ISSUE TITLE
Index out of bounds (IndexError) vs returning nil like ruby.

### ISSUE THREAD

**Issue by isaacsloan** [crystal-lang/crystal#2437] opened 2016-04-09 04:57 UTC
It would be sweet if
```
   a = [1,2,3]
   a[3] 
```

returned nil like ruby instead of throwing an error. Is there a performance reason this can't happen?

**Comment by jhass** [comment] 2016-04-09 06:30
duplicate of #1034 (also check all the references there for existing discussion around this)

**Closed by jhass** 2016-04-09 06:30 UTC

**Comment by isaacsloan** [comment] 2016-04-09 08:10
Thanks.
