### ISSUE TITLE
Multi-line with CRLF files

### ISSUE THREAD

**Issue by alex-lairan** [crystal-lang/crystal#11727] opened 2022-01-08 16:00 UTC
## Bug Report

Given a crystal file with 

```crystal
puts \
  "hello world"
```

When I compile the file with CRLF format, an error happens.

```
$ crystal.exe src/test.cr
In src\test.cr:1:7

 1 | puts \
           ^
Error: unknown token: '\r'
```

Expected : 
```
$ crystal.exe src/test.cr
hello world
```

## Complement

With a file using `CR` formating, everything works.

## Context

Windows 10
Cygwin

```
$ crystal -v
Crystal 1.3.0 [a3ee70ca0] (2022-01-06)

LLVM: 10.0.0
Default target: x86_64-pc-windows-msvc
```

**Comment by alex-lairan** [comment] 2022-01-08 16:15
Just tested with a Linux machine.

It does not work either with CRLF.

```
In src/test.cr:1:7

 1 | puts \
           ^
Error: unknown token: '\r'
```

**Comment by alex-lairan** [comment] 2022-01-08 16:17
I think it's a duplicate from https://github.com/crystal-lang/crystal/issues/5831

**Comment by HertzDevil** [comment] 2022-01-08 16:26
Crystal on Linux has every right to reject CRLF. Crystal on Windows should "just" work if `File.open` and friends respect the binary mode flag, but this is currently not the case: https://github.com/crystal-lang/crystal/issues/11586#issuecomment-993537371

**Comment by straight-shoota** [comment] 2022-01-08 20:15
Duplicate of #5831

**Closed by straight-shoota** 2022-01-08 20:15 UTC
Labels: kind:bug, topic:compiler:parser, platform:windows
