### ISSUE TITLE
Invalid memory access in Array#push

### ISSUE THREAD

**Issue by vlazar** [crystal-lang/crystal#8594] opened 2019-12-17 12:46 UTC
[Array#push fails](https://play.crystal-lang.org/#/r/87od)

```crystal
ary=[] of UInt32
p! ary.push(3)
```

Output
```
Invalid memory access (signal 11) at address 0x0
[0x55d1aecf1b06] *CallStack::print_backtrace:Int32 +118
[0x55d1aece4981] __crystal_sigfault_handler +209
[0x7f42fe0ad930] ???
[0x0] ???
```

[Array#<< works](https://play.crystal-lang.org/#/r/87of)

```crystal
ary=[] of UInt32
p! ary << 3 # => [3]
```

Note however that locally I have this error instead for Array#push:
```crystal
ary=[] of UInt32
p! ary.push(3) # => Program received and didn't handle signal ILL (4)
```

<details>
  <summary>Crystal 0.32.0 on MacOS</summary>

```
$ crystal --version
Crystal 0.32.0 (2019-12-12)

LLVM: 9.0.0
Default target: x86_64-apple-macosx
```
</details>

The behavior changed many times in previous versions of Crystal. Although I'm not sure if I can trust playground.

In Crystal 0.24.2 both [Array#push](https://play.crystal-lang.org/#/r/87og) and [Array#<<](https://play.crystal-lang.org/#/r/87oh) gives `no overload matches` error.

Since Crystal 0.25.0 [Array#push](https://play.crystal-lang.org/#/r/87oo) is broken and [Array#<<](https://play.crystal-lang.org/#/r/87on) works.

Since Crystal 0.27.0 [Array#push](https://play.crystal-lang.org/#/r/87oo) gives `ambiguous call, implicit cast of 3 matches all of UInt32` and [Array#<<](https://play.crystal-lang.org/#/r/87or) works.

SInce Crystal 0.29.0 [Array#push](https://play.crystal-lang.org/#/r/87p6) gives `Program received and didn't handle signal SYS (31)` and [Array#<<](https://play.crystal-lang.org/#/r/87p1) works.

SInce Crystal 0.31.0 [Array#push](https://play.crystal-lang.org/#/r/87p9) gives `Invalid memory access` and [Array#<<](https://play.crystal-lang.org/#/r/87pa) works.

**Comment by vlazar** [comment] 2019-12-17 12:48
Seem to be related to #6074 #6618 and #7747

**Comment by vlazar** [comment] 2019-12-17 12:49
Only `Int32` is working with `Array#push`

```crystal
# ary=[] of UInt64
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

# ary=[] of UInt32
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

# ary=[] of UInt16
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

# ary=[] of UInt8
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

# ary=[] of Int64
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

ary=[] of Int32
p! ary.push(3) # => [3]

# ary=[] of Int16
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)

# ary=[] of Int8
# p! ary.push(3) # => Program received and didn't handle signal ILL (4)
```

<details>
  <summary>Crystal 0.32.0 on MacOS</summary>

```
$ crystal --version
Crystal 0.32.0 (2019-12-12)

LLVM: 9.0.0
Default target: x86_64-apple-macosx
```
</details>

**Comment by asterite** [comment] 2019-12-17 13:03
It seems to be a bug with autocasting. It works fine if you do `push(3_u32)`.

**Comment by vlazar** [comment] 2019-12-17 13:40
BTW, is that by design that `Array#push` has overloads for single value and multiple values, but `Array#<<` works only for single value?

Should't there be this variant too?
```crystal
class Array(T)
  def <<(*values : T)
   push(*values)
  end
end
```

Then `Array#<<` will fail as `Array#push` in this issue.

**Comment by asterite** [comment] 2019-12-17 13:45
@vlazar there syntax doesn't allow calling `<<` with multiple arguments, unless you do `a.<<(1, 2, 3)`, but for that you can use `push`.

**Comment by vlazar** [comment] 2019-12-17 13:48
@asterite Thanks. Yeah, that was my though. I just wanted to be sure it was not forgotten, but deliberately not added in the first place.

**Comment by RX14** [comment] 2019-12-19 13:13
I'm certain this is https://github.com/crystal-lang/crystal/issues/8217.

**Comment by asterite** [comment] 2019-12-19 13:42
Duplicate of #8217

**Closed by asterite** 2019-12-19 13:42 UTC
Labels: kind:bug, topic:compiler
