### ISSUE TITLE
Bug compiling --release kemal example

### ISSUE THREAD

**Issue by itwars** [crystal-lang/crystal#4888] opened 2017-08-27 12:39 UTC
Crystal 0.23.1 (2017-07-13) LLVM 4.0.1
Darwin xxx 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

- crystal run -> OK
- crystal build -> OK
- crystal build --release -> error in compilation

*Shard.yml*
``` yaml
name: test
version: 1
dependencies:
  kemal:
    github: kemalcr/kemal
    branch: master
```

*Code Source*
``` crystal
require "kemal"
require "json"

# You can easily access the context and set content_type like 'application/json'.
# Look how easy to build a JSON serving API.
get "/" do |env|
  env.response.content_type = "application/json"
  {name: "Serdar", age: 27}.to_json
end

Kemal.run
```
*Error Output*
```
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  %4 = call i8* @__crystal_malloc(i32 ptrtoint (i1** getelementptr (i1*, i1** null, i32 1) to i32))

0x10ab503f3: *raise<String>:NoReturn at ??
0x10b3198b1: *Crystal::CodeGenVisitor#finish:Nil at ??
0x10b28dc4d: *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) at ??
0x10b5f0174: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x10aba8b1c: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x10ab7fb86: main at ??
```

**Comment by akzhan** [comment] 2017-08-27 12:49
Try to compile with `--no-debug` option.

It's known issue (looks like related to LLVM < 3.9), see #4719 for example.

Another way is - wait for statically linked compiler (looks like it should be 0.23.2).

Yet another way is to build compiler by yourself with LLVM >= 3.9 (LLVM 4.0.1 is ok).

**Comment by RX14** [comment] 2017-08-27 12:54
This is not related to #4719. Dupe of #4600. ( 90% sure)

**Comment by itwars** [comment] 2017-08-27 13:00
Hi,

--no-debug : make the job and compilation is OK now!
But, executing the binary give me: 
```
[development] Kemal is ready to lead at http://0.0.0.0:3000
```

Is **development** a Kemal status or Crystal?

**Comment by RX14** [comment] 2017-08-27 13:37
Its a kemal status.

**Comment by RX14** [comment] 2017-08-27 13:41
Closing because I think it's a dupe

**Closed by RX14** 2017-08-27 13:41 UTC

**Comment by kazzkiq** [comment] 2017-08-27 14:32
@itwars try running your binary with `KEMAL_ENV=production` environment variable before it, and see if it removes the development status.
