### ISSUE TITLE
Issue compiling on M1 Pro MacBook.

### ISSUE THREAD

**Issue by l3gacyb3ta** [crystal-lang/crystal#12046] opened 2022-05-04 18:50 UTC
## Bug Report

Hello! I'm having an issue compiling a basic hello world on my computer.

The code I am using
```crystal
puts "hello world"
```
I run it with `crystal run test.cr`
and I get the following error:
```
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      _*Crystal::Iconv#convert<Pointer(Pointer(UInt8)), Pointer(UInt64), Pointer(Pointer(UInt8)), Pointer(UInt64)>:UInt64 in C-rystal5858I-conv.o
  "_iconv_close", referenced from:
      _*Crystal::Iconv#close:Nil in C-rystal5858I-conv.o
  "_iconv_open", referenced from:
      _*Crystal::Iconv#initialize<String, String, (Symbol | Nil)>:Nil in C-rystal5858I-conv.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc "${@}" -o /Users/arc/.cache/crystal/crystal-run-test.tmp  -rdynamic -L/opt/crystal/embedded/lib -lpcre -lgc -L/opt/homebrew/Cellar/libevent/2.1.12/lib -levent -liconv`
```

I am using the crystal installed from the .pkg file. Here is my `crystal -v`:
```
Crystal 1.4.1 [b7377c041] (2022-04-22)

LLVM: 10.0.0
Default target: aarch64-apple-darwin
```

And here is `uname -a` if it helps:
```
Darwin Caryophyllus.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
```

**Comment by l3gacyb3ta** [comment] 2022-05-04 18:53
Update:
adding `--link-flags -L/usr/lib` makes it work???

**Comment by Blacksmoke16** [comment] 2022-05-04 18:55
Duplicate of https://github.com/crystal-lang/crystal/issues/10653?

**Comment by l3gacyb3ta** [comment] 2022-05-04 18:57
Seems to be, but this shouldn't be something I have to fix. Also #10653 was closed

**Comment by straight-shoota** [comment] 2022-05-04 19:06
It seems odd that `/usr/lib` is apparently not available as default path.

Can you please share the output of `crystal env`?
And the manpage for your linker?

**Comment by tjbarber** [comment] 2022-10-29 13:19
This is still an issue as of Crystal 1.6.1. Running on a M1 Max MacBook Pro.

**Comment by clanmills** [comment] 2023-02-15 05:49
I concur.  This issue exists on my MBP+M1.
```
507 rmills@rmillsm1:~ $ sw_vers
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
508 rmills@rmillsm1:~ $ 
```
My investigation is incomplete.  Here's what I know:

With macOS BigSur, Monterey and Ventura (macOS 11, 12,13) the file /usr/lib/libiconv.2.dylib is not installed.  This is in the release notes:  https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes search for 62986286

There is magic to enable dlopen() to access /usr/lib/libiconv.2.dylib although the file is not in the file system.  crystal has been correctly compiled to use that library, yet it fails to do so at run-time.

```
516 rmills@rmillsm1:/opt $ otool -L /opt/crystal/embedded/bin/crystal 
/opt/crystal/embedded/bin/crystal (architecture x86_64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
/opt/crystal/embedded/bin/crystal (architecture arm64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
517 rmills@rmillsm1:/opt $ 
```

crystal crashes at runtime:

```
519 rmills@rmillsm1:/opt $ cat ~/gnu/crystal/hello/src/hello.cr 
# TODO: Write documentation for `Hello`
module Hello
  VERSION = "0.1.0"

  puts "Hello World!"
end
520 rmills@rmillsm1:/opt $ crystal run ~/gnu/crystal/hello/src/hello.cr 
Undefined symbols for architecture arm64:
  "_iconv", referenced from:
      _*Crystal::Iconv#convert<Pointer(Pointer(UInt8)), Pointer(UInt64), Pointer(Pointer(UInt8)), Pointer(UInt64)>:UInt64 in C-rystal5858I-conv.o
  "_iconv_close", referenced from:
```

I will continue to investigate.   

Here is a confusing red-herring.  Programs access libiconv.2.dylib differently on Apple and GNU.  When you call _iconv with GNU (/usr/local/lib/libiconv.2.dylib) uses entry _libiconv_XXX.  Apple uses entry _iconv_XXX.  Apple support for my 10 year old MacMini terminated with Calalina (10.15) and has both /usr/lib/libiconv.2.dylib (provided by Apple) and /usr/local/lib/libiconv.2.dylib (which I built from source),

```
530 rmills@rmillsmm-local:~/gnu/libiconv/libiconv-1.15 $ nm -g /usr/local/lib/libiconv.2.dylib  | grep conv
00000000000e4090 D __libiconv_version
00000000000052e0 T _iconv_canonicalize
0000000000004b20 T _libiconv
0000000000004b50 T _libiconv_close
00000000000036a0 T _libiconv_open
0000000000004b60 T _libiconv_open_into
0000000000017410 T _libiconv_set_relocation_prefix
0000000000004fd0 T _libiconvctl
00000000000050e0 T _libiconvlist
531 rmills@rmillsmm-local:~/gnu/libiconv/libiconv-1.15 $ nm -g /usr/lib/libiconv.2.dylib | grep conv
00000000000f2710 D __libiconv_version
0000000000002390 T _iconv
00000000000026ab T _iconv_canonicalize
00000000000023b2 T _iconv_close
0000000000001095 T _iconv_open
00000000000023bf T _iconvctl
00000000000024b4 T _iconvlist
0000000000013fac T _libiconv_set_relocation_prefix
532 rmills@rmillsmm-local:~/gnu/libiconv/libiconv-1.15 $ 
```

**Comment by clanmills** [comment] 2023-02-15 11:26
Apple's libiconv magic in their SDK works.  I can compile and link the program test-to-wchar.c from libiconv-1.17 to use the fictional /usr/lib/libiconv.2.dylib

Conclusion:
1. crystal is linked correctly.
2. /opt/local/lib/libxml2.2.dylib has been incorrectly linked and searching for _libiconv

```
680 rmills@rmillsm1:/opt $ /opt/crystal/embedded/bin/crystal run ~/gnu/crystal/hello/src/hello.cr 
dyld[37150]: Symbol not found: _libiconv
  Referenced from: <9A70615A-9B35-3C97-8E8D-9E596C8A51CE> /opt/local/lib/libxml2.2.dylib
  Expected in:     <E6B7DE43-596F-32E8-8EDD-2CA0ED0DFD3D> /usr/lib/libiconv.2.dylib
Abort trap: 6
681 rmills@rmillsm1:/opt $ 
```

Here's my investigation:

```
665 rmills@rmillsm1:~/temp $ cc     test-to-wchar.c   -o test-to-wchar -I/Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/lib/libiconv.tbd
666 rmills@rmillsm1:~/temp $ ./test-to-wchar 
667 rmills@rmillsm1:~/temp $ otool -L test-to-wchar
test-to-wchar:
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
668 rmills@rmillsm1:~/temp $ nm test-to-wchar | grep iconv
                 U _iconv
                 U _iconv_open
669 rmills@rmillsm1:~/temp $ 
```

crystal and test-to-wchar have been linked in the same way:
```
678 rmills@rmillsm1:/opt $ otool -L /opt/crystal/embedded/bin/crystal 
/opt/crystal/embedded/bin/crystal (architecture x86_64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
/opt/crystal/embedded/bin/crystal (architecture arm64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
679 rmills@rmillsm1:/opt $ nm  /opt/crystal/embedded/bin/crystal | grep iconv
                 U _iconv
                 U _iconv_close
                 U _iconv_open
680 rmills@rmillsm1:/opt $ 
```

I made two tiny changes to the 1.17 code:
```
672 rmills@rmillsm1:~/gnu/libiconv-1.17 $ diff ./tests/test-to-wchar.c ~/temp/test-to-wchar.c 
18c18
< #include "config.h"
---
> /* #include "config.h" */
43c43
<                       (ICONV_CONST char **) &inptr, &inbytesleft,
---
>                       /*(ICONV_CONST char **)*/ &inptr, &inbytesleft,
673 rmills@rmillsm1:~/gnu/libiconv-1.17 $ 
```

How to fix this?  I don't know.  I will be motivated to continue this investigation with encouragement from Team Chrystal.  Specifically, I would like to discuss this bash script:
```
501 rmills@rmillsm1:~ $ cat /opt/crystal/bin/crystal 
#!/usr/bin/env bash
...
realpath() {
    canonicalize_path "$(resolve_symlinks "$1")"
}
...
SCRIPT_PATH="$(dirname "$(realpath "$0" || echo $0)")"
INSTALL_DIR="$(realpath "$SCRIPT_PATH/..")"
EMBEDDED_CRYSTAL_PATH=$("$INSTALL_DIR/embedded/bin/crystal" env CRYSTAL_PATH)
export CRYSTAL_PATH="${CRYSTAL_PATH:-"$EMBEDDED_CRYSTAL_PATH:$INSTALL_DIR/src"}"
export CRYSTAL_LIBRARY_PATH="${CRYSTAL_LIBRARY_PATH:+$CRYSTAL_LIBRARY_PATH:}$INSTALL_DIR/embedded/lib"
"$INSTALL_DIR/embedded/bin/crystal" "$@"
502 rmills@rmillsm1:~ $ 
```

**Comment by clanmills** [comment] 2023-02-17 08:03
Solved!

From my analysis above, I believe crystal is correctly built and the executable is experiencing a dynamic library loading crisis (probably involving libiconv.2.dylib) 

I have this working by installing the pkg from github.  I used:
https://github.com/crystal-lang/crystal/releases/download/1.7.2/crystal-1.7.2-1.universal.pkg

Before installing I did the following:
1.  Clean out `sudo rm -rf /opt/*`
2. Removed all references to /opt in my bash profile script (~/.profile)
3. Simplified the libraries in /usr/local/lib and /usr/local/include.  I have:
```
596 rmills@rmillsm1:~/gnu/crystal $ ls -l /usr/local/lib/*.dylib | grep -v ^l
-rwxr-xr-x  1 root  wheel    34271 14 Feb 13:07 /usr/local/lib/libcharset.1.dylib
-rwxr-xr-x  1 root  wheel  2948312 16 Feb 16:59 /usr/local/lib/libexiv2.0.27.6.dylib
-rwxr-xr-x  1 root  wheel  3128792 16 Feb 09:22 /usr/local/lib/libexiv2.1.0.0.9.dylib
-rwxr-xr-x  1 root  wheel   189197 16 Feb 16:57 /usr/local/lib/libexpat.1.8.10.dylib
-rwxr-xr-x  1 root  wheel   106025 16 Feb 16:56 /usr/local/lib/libz.1.2.13.dylib
597 rmills@rmillsm1:~/gnu/crystal $ 
```

Crystal (and supporting artefacts) are in /opt/crystal.  The executable is in `/opt/crystal/embedded/bin/crystal`:
```
510 rmills@rmillsm1:/opt $ ls -l $(which crystal)
lrwxr-xr-x  1 root  wheel  24 16 Feb 17:30 /usr/local/bin/crystal -> /opt/crystal/bin/crystal
511 rmills@rmillsm1:/opt $ otool -L /opt/crystal/embedded/bin/crystal 
/opt/crystal/embedded/bin/crystal (architecture x86_64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
/opt/crystal/embedded/bin/crystal (architecture arm64):
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1858.112.0)
512 rmills@rmillsm1:/opt $ 
```

This will not run crystal play:
```
503 rmills@rmillsm1:~ $ crystal play
Listening on http://127.0.0.1:8080
Undefined symbols for architecture arm64:
  "_ERR_load_crypto_strings", referenced from:
      ___crystal_main in _main.o
  "_OPENSSL_add_all_algorithms_noconf", referenced from:
      ___crystal_main in _main.o
```
So, I installed brew using the instructions here:  https://brew.sh  Then installed crystal using brew:
```
$ 507 rmills@rmillsm1:~ $ brew list
==> Formulae
bdw-gc		ca-certificates	crystal		gmp		libevent	libyaml		llvm@14		openssl@1.1	openssl@3	pcre		pkg-config

508 rmills@rmillsm1:~ $ brew play
Listening on http://127.0.0.1:8080

.... happiness in the browser http://localhost:8080 ...
^C
509 rmills@rmillsm1:~ $
```

I can successfully run `$ crystal play` on both /usr/local/bin/crystal on and /opt/homebrew/bin/crystal.

```
510 rmills@rmillsm1:/opt $ finder crystal $L | grep -v ^d | grep -v ^l
-rwxr-xr-x  1 rmills  admin  13073808 17 Feb 07:39 ./homebrew/Cellar/crystal/1.7.2/libexec/crystal  <--- from brew 
-rwxr-xr-x  1 root  wheel  136228538 23 Jan 20:18 ./crystal/embedded/bin/crystal  <--- from universal.pkg
511 rmills@rmillsm1:/opt $ otool -L homebrew/Cellar/crystal/1.7.2/libexec/crystal
homebrew/Cellar/crystal/1.7.2/libexec/crystal:
	/opt/homebrew/opt/llvm@14/lib/libLLVM.dylib (compatibility version 1.0.0, current version 14.0.6)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.32.0)
	/opt/homebrew/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.13.0)
	/opt/homebrew/opt/bdw-gc/lib/libgc.1.dylib (compatibility version 7.0.0, current version 7.1.0)
	/opt/homebrew/opt/libevent/lib/libevent-2.1.7.dylib (compatibility version 8.0.0, current version 8.1.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libffi.dylib (compatibility version 1.0.0, current version 30.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1319.0.0)
512 rmills@rmillsm1:/opt $ 
```

**Comment by straight-shoota** [comment] 2023-03-16 18:48
It seems this can be closed. Please report if you keep seeing this issue, we'll reopen.

**Closed by straight-shoota** 2023-03-16 18:48 UTC
Labels: kind:bug, platform:darwin, platform:aarch64
