### ISSUE TITLE
Numeric type math differences, no BigInt.to_(i|u)128 methods

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#13301] opened 2023-04-07 20:09 UTC
Here I get different (incorrect) answers when `m` is a `u32|64`.
Also the last 2 tests with `m.to_(1|u)128` gives

```
➜  crystal-projects crystal run  --release powmod-test.cr
Showing last frame. Use --error-trace for full trace.

In /home/jzakiya/crystal/share/crystal/src/int.cr:1266:11

 1266 | value.to_i128
              ^------
Error: undefined method 'to_i128' for BigInt

Did you mean 'to_i8'?
➜  crystal-projects crystal run  --release powmod-test.cr
Showing last frame. Use --error-trace for full trace.

In /home/jzakiya/crystal/share/crystal/src/int.cr:1789:11

 1789 | value.to_u128
              ^------
Error: undefined method 'to_u128' for BigInt

Did you mean 'to_u8'?
```

```cr
require "big"

@[Link("gmp")]
lib LibGMP
  fun mpz_powm = __gmpz_powm(rop : MPZ*, base : MPZ*, exp : MPZ*, mod : MPZ*)
end

def powmodgmp(b, e, m)
  y = BigInt.new
  LibGMP.mpz_powm(y, b.to_big_i, e.to_big_i, m.to_big_i)
  y
end

def powmodint(b, e, m)
  r = typeof(m).new(1)
  while e > 0
    r = (r &* b) % m if e.odd?
    e >>= 1
    b = (b &* b) % m
  end
  r
end

def powmod(b, e, m)
  if typeof(m) == typeof(BigInt.new)
    powmodgmp(b, e, m)
  else
    b = b % m;  b = typeof(m).new(b)
    powmodint(b, e, m)
  end
end

b = "329832983".to_big_i
e = 4843
m = "498422".to_big_i
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = 329832983
e = 4843
m = 498422
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = 4843.to_u32
m = 498422
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = 329832983.to_u64
e = 4843
m = 498422.to_i32
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = 4843.to_u64
m = 498422.to_u64
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = 4843.to_u64
m = 498422.to_i64
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = "4843".to_big_i
m = 498422.to_u32
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = 4843.to_u64
m = 498422.to_u128
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts

b = "329832983".to_big_i
e = "4843".to_big_i
m = 498422.to_u128
puts "r = #{r = powmod(b, e, m)} of class #{r.class}"
puts
```
The correct values, verified in Ruby is:
```
3.2.2 :002 > 329832983.pow(4843, 498422)
 => 107323 
```
Here are the outputs for the values shown. 
When `m` is a `(U|I)nt32` the outputs are incorrect, but correct when `(U|I)nt64`
However the output is well within the numerical range for both.

```
➜  crystal-projects crystal run  --release powmod-test.cr
r = 107323 of class BigInt

r = 107795 of class Int32

r = 107795 of class Int32

r = 107795 of class Int32

r = 107323 of class UInt64

r = 107323 of class Int64

r = 3759 of class UInt32
```

**Comment by Blacksmoke16** [comment] 2023-04-07 20:17
Part duplicate of https://github.com/crystal-lang/crystal/issues/12771.

**Comment by HertzDevil** [comment] 2023-06-15 05:40
The other part is more or less the same thing as https://github.com/crystal-lang/crystal/issues/13244#issuecomment-1492498676 (`r`'s type in `powmodint` is too small).

**Closed by HertzDevil** 2023-06-15 05:40 UTC
Labels: kind:bug, topic:stdlib:numeric
