### ISSUE TITLE
0.29.0 compiler bug in enum (different than #7877)

### ISSUE THREAD

**Issue by jimm** [crystal-lang/crystal#7878] opened 2019-06-10 12:51 UTC
This is happening with Crystal 0.29.0 on MacOS 10.14.5. The following code throws an error during compilation. The error message is below. Note that this seems related to #7877 because it's happening when the compiler is supposed to add one to the previous value. In this case, it should go from -10000 to -9999 but instead there is an overflow error.

```crystal
lib LibPortMIDI
  enum PmError : Int32
    HostError          = -10000
    InvalidDeviceId # out of range or
    InsufficientMemory
  end
end
```
The error:
```
crystal bug_trigger.cr 
Error in bug_trigger.cr:5: value of enum member InsufficientMemory would overflow the base type Int32

    InsufficientMemory
    ^~~~~~~~~~~~~~~~~~
```

**Comment by jimm** [comment] 2019-06-10 13:45
Correction: the compiler doesn't throw an error. It outputs an error message to the user. It looks like an incorrect value is generated by the compiler while adding one to the previous value in the enum.

**Comment by asterite** [comment] 2019-06-10 14:10
Duplicate of #7874 ?

**Comment by jimm** [comment] 2019-06-10 14:28
Yes, looks like this might be a dupe. I opened it because I'd also just opened #7877 which is another (?) enum bug.

**Closed** 2019-06-10 14:41 UTC
Labels: status:duplicate
