### ISSUE TITLE
Compiler bug

### ISSUE THREAD

**Issue by tliff** [crystal-lang/crystal#5923] opened 2018-04-05 12:50 UTC
I get the following  when trying to run my code:
```
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-lang-20180310-76015-tfxflp/crystal-0.24.2/src/compiler/crystal/types.cr:1428:20:1428
Crystal::TypeParameter#solve<Crystal::NonGenericClassType>:Crystal::ASTNode+
Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::NonGenericClassType>:Crystal::Type+
Crystal::TypeDeclarationProcessor#process_owner_guessed_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::InstanceVarTypeInfo>:(Crystal::MetaTypeVar | Crystal::TypeDeclarationProcessor::Error | Nil)
Crystal::TypeDeclarationProcessor#process_instance_vars_declarations:Nil
Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor)
Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+
Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
Crystal::Command#run_command<Bool>:Nil
Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil)
main
```

Minimal example:

```crystal
class Foo
  def initialize()
    @data = Array.new(10){|i| 1}
  end
end
```

Crystal 0.24.2 (2018-03-10)
LLVM: 5.0.1
Default target: x86_64-apple-macosx

On OSX 10.13.1

**Comment by asterite** [comment] 2018-04-05 20:28
Duplicate of https://github.com/crystal-lang/crystal/issues/5666

**Closed by asterite** 2018-04-05 20:28 UTC
Labels: kind:bug, topic:compiler
