### ISSUE TITLE
Propose: Incremental compilation

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14201] opened 2024-01-10 05:25 UTC
## Discussion

every file can be compiled into a compilation unit of bytecode,
let's call it *.crgb, (*.crc well is crc...), so I choose to use *.crb here
which means crystal bytecode, then *.crgb means crystal general
bytecode. the gb is kind of same of *.cr, it only includes the prototype of function.

```
#sum.cr
def sum(a,b)
  a+b
end
```

then let's say foo.cr depends on sum.cr
```
#foo.cr
sum(1,2)
```
crystal foo.cr, the compiler process will fetch foo.{cr,crgb} and sum.crgb to produce final result,
no need to recompile sum.cr. when sum(1,2), compiler realize it needs to instantiate the
function to a sum(Int32,Int32) instance, it will do it, whether it choose to save the bytecode
to sum.crb that's an another choice.

```
#foo.cr
sum("a","b")
```
crystal foo.cr, the compiler process will fetch foo.{cr,crgb} and sum.crgb to produce final result,
no need to recompile sum.cr. when sum(1,2), compiler realize it needs to instantiate the
function to a sum(String,String) instance, it will do it.

step 1 --> *.crgb is already performance improvement and I think can already handle very large projects.

step 2--> *.crb is problematic because we don't know beforehand all the instantiations, there may be
some optimization in the future to clever knows a *.crb doesn't needs to recompile. for now let's just only
compile to  *.crgb

**Comment by Blacksmoke16** [comment] 2024-01-10 05:36
Going to call this a duplicate of #10568

**Closed by Blacksmoke16** 2024-01-10 05:36 UTC
Labels: status:discussion
