### ISSUE TITLE
cross-compilation to aarch64 mysterious error

### ISSUE THREAD

**Issue by silmanduin66** [crystal-lang/crystal#7299] opened 2019-01-11 16:04 UTC
This is not a real issue as it sometimes works

Crystal: 0.27.0
LLVM: 6.0.1
OS: archLinux
arch: x86-64 to aarch64 (PC to raspberry Pi3)

I cross-compile my crystal files to aarch64 , and i get this error every time i cross-compile a file for the 1st time. But if i try to cross-compile it again , it mysteriously works. ( sometimes i have to do it 3 times in a row)

```
[root@archLinux blogsy]# crystal build src/blogsy.cr --cross-compile --target "aarch64-unknown-linux-gnu"
Invalid memory access (signal 11) at address 0x7ffcbbf770b0
[0x5599e0bcfe86] ???
[0x5599e032123e] __crystal_sigfault_handler +238
[0x7fdd154313c0] ???
[0x7fdd15314f10] ???
[0x7fdd16220380] _ZN4llvm15SmallVectorBase8grow_podEPvmm +128
[0x7fdd175b3d2a] _ZNK4llvm19AArch64CallLowering17splitToValueTypesERKNS_12CallLowering7ArgInfoERNS_15SmallVectorImplIS2_EERKNS_10DataLayoutERNS_19MachineRegisterInfoEjRKSt8functionIFvjmEE +1146
[0x7fdd175b4116] _ZNK4llvm19AArch64CallLowering9lowerCallERNS_16MachineIRBuilderEjRKNS_14MachineOperandERKNS_12CallLowering7ArgInfoENS_8ArrayRefIS7_EE +326
[0x7fdd169acbbb] _ZNK4llvm12CallLowering9lowerCallERNS_16MachineIRBuilderENS_17ImmutableCallSiteEjNS_8ArrayRefIjEESt8functionIFjvEE +1387
[0x7fdd169b4c8c] _ZN4llvm12IRTranslator13translateCallERKNS_4UserERNS_16MachineIRBuilderE +1132
[0x7fdd169b83fe] _ZN4llvm12IRTranslator20runOnMachineFunctionERNS_15MachineFunctionE +2894
[0x7fdd16554870] _ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE +144
[0x7fdd16369b98] _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE +792
[0x7fdd16369c12] _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE +50
[0x7fdd163692a4] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +756
[0x7fdd175a9979] ???
[0x7fdd175a9b0c] LLVMTargetMachineEmitToFile +252
[0x5599e07dcb9e] ???
[0x5599e0b49173] ???
[0x5599e033652b] ???
[0x5599e0302bc7] __crystal_main +13927
[0x5599e0306b55] main +37
[0x7fdd151fc223] __libc_start_main +243
[0x5599e02ff48e] _start +46
[0x0] ???
[root@archLinux blogsy]# crystal build src/blogsy.cr --cross-compile --target "aarch64-unknown-linux-gnu"
cc 'blogsy.o' -o 'blogsy'  -rdynamic  `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lz -lsqlite3  -lyaml -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib
```

i tried this with simple ```hello.cr``` as well as the basic crystal http server ```server.cr``` and now with the tutorial blogsy app ( Amber Framework) . After trying a few times to cross-compile them, the result is successful and all the file run perfectly on my aarch64 device.

(feel free to close this issue because it actually sometimes works, i just wanted to notify this as i didn't see anyone else mention that before )

**Comment by RX14** [comment] 2019-01-11 19:51
Looks like an LLVM bug :(

**Comment by beta-ziliani** [comment] 2021-11-05 18:02
I'm closing this issue since there is no way to reproduce it. @silmanduin66 if you happen to still be experience something similar, let us know.

**Closed by beta-ziliani** 2021-11-05 18:02 UTC
Labels: kind:bug, status:needs-more-info, platform:aarch64
