### ISSUE TITLE
Adding Prime support

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14188] opened 2024-01-09 08:08 UTC
## Discussion

I see prime is included in rubysl (ruby stdlib),

```
require "prime"
```
so I propose crystal adds it.

If this is approved, then I can work on it.

**Comment by devnote-dev** [comment] 2024-01-09 13:00
While there are many similarities between Crystal and Ruby, important to remember that they are different languages with different goals. Just because Ruby has something doesn't mean Crystal also needs it, there needs to be reasonable justification for adding features or modules like this.

I can't see what exactly this would be needed in the standard library, it's not something that I've seen be requested by the community either. Wouldn't this be better suited as a shard?

**Comment by femto** [comment] 2024-01-09 13:15
hi, in ruby it's gem also first. But later add to ruby
because it's convinent when others installed ruby,
they don't need to install that stuff.

**Comment by Blacksmoke16** [comment] 2024-01-09 13:51
Duplicate of #8845

**Closed by Blacksmoke16** 2024-01-09 13:51 UTC
Labels: status:duplicate, status:discussion, topic:stdlib:numeric
