### ISSUE TITLE
Inconsistency with the String class's chomp & strip

### ISSUE THREAD

**Issue by exts** [crystal-lang/crystal#3773] opened 2016-12-24 19:24 UTC
So I'm new to crystal and I was looking at the standard library and I realized that there's an inconsistency with a few of the functions and I'm not sure about others as I haven't checked, but you have two different functions that follow the same rules eg.: `chomp` and `strip`

The problem is with `strip` the main definition strips the beginning and end of a `string` whilist the `chomp` definition strips the end of a `string `. Now that's fine if they didn't attempt to follow the same rules. `strip` has a `lstrip` and a `rstrip` variation which only purpose is to strip only the left or right of a `string` while `chomp` only has a `lchomp` while if `rchomp`'s expected functionality currently resides in `chomp` since `rchomp` doesn't actually exist.

Wouldn't it be appropriate for `chomp` to follow the same rules as `strip` and have an `lchomp` and `rchomp` while `chomp` strips the `string | char` from the beginning AND end of a `string`?

Just seems like a weird inconsistency with the standard library that I wanted to address while there's still breaking changes being made.

Kind regards.

**Comment by Sija** [comment] 2016-12-24 19:39
See #3729

**Comment by exts** [comment] 2016-12-24 20:14
Thanks @Sija, I thought I searched properly, but the results were different.

**Comment by ysbaddaden** [comment] 2016-12-25 20:09
Closing, the issue is an exact duplicate of #3729

**Closed by ysbaddaden** 2016-12-25 20:09 UTC
