### ISSUE TITLE
Error missing for chained assignment for constant

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7201] opened 2018-12-18 20:52 UTC
For some reason this isn't allowed:
```cr
CONSTANT1, CONSTANT2 = 1, 2
```
and gives a proper error:
```
Syntax error in constant.cr:1: Multiple assignment is not allowed for constants
```
---
But this kind of assignment which is similar to the one above doesn't seem to results in an error:
```cr
CONSTANT1 = CONSTANT2 = 12
```
Now trying to read from `CONSTANT2` results in:
```
Error in line 3: undefined constant CONSTANT2 (did you mean 'CONSTANT1')
```
and trying to read from `CONSTANT1` results in:
````
Nil assertion failed at /build/crystal/src/crystal-0.27.0/src/compiler/crystal/semantic/cleanup_transformer.cr:192 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
````

**Comment by asterite** [comment] 2018-12-18 20:54
Duplicate of #2874

**Closed by asterite** 2018-12-18 20:54 UTC
