### ISSUE TITLE
Generates wrong API documentation for reopened classes

### ISSUE THREAD

**Issue by jan-zajic** [crystal-lang/crystal#8393] opened 2019-10-29 10:47 UTC
When class is reopened, generated documentation is very confusing. 

For example from stdlib, see UUID struct:
https://crystal-lang.org/api/UUID.html
generated documentation contains only text from uuid/json.cr, which is reopen of this class. So if you open doc for UUID, you read whole bunch of info how used it in JSON, but nothing about basic purpose of UUID class.

**Comment by jan-zajic** [comment] 2019-10-29 10:47
I think at least we would merge doc from all definitions, first at top. But better would be, if something from #1647 will be implemented (so we can know which occurrences consider as reopen and which treat as first definition), to not include documentation from reopened occurrences at all, or to always prefer the primary one. I imagine different page for reopened occurrence in this specific example of json stuff, including aditional methods, even when it is opt-in, but other times it makes sense to only append it to main doc, so this is for discussion (maybe it would be best somehow mark this in doc markup source?)

**Comment by jan-zajic** [comment] 2019-10-29 10:51
Sorry, i find just right now issue #7988 that solves that particular example with UUID. But supplied fix is only workaround, general problem remains same. If anybody put comments to type when reopening it, primary doc will be overwritten.

**Comment by straight-shoota** [comment] 2019-10-29 11:10
Thanks for bringing this up, but there is already an issue for this.

Duplicate of #8338

**Closed by straight-shoota** 2019-10-29 11:10 UTC
