### ISSUE TITLE
Return type of abstract method is ignored

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7367] opened 2019-02-03 16:06 UTC
The following compiles:
```crystal
module A
  abstract def method : String
end

module B
  extend self
  include A
  
  def method
    123
  end
end

B.method
```
But actually `B.method` returns an `Int32`, not a `String` which I specified in the abstract method definition.

**Comment by ysbaddaden** [comment] 2019-02-03 16:38
Duplicate of #3546
Similar to #160

**Closed by ysbaddaden** 2019-02-03 16:38 UTC
