### ISSUE TITLE
type must be...?

### ISSUE THREAD

**Issue by stugol** [crystal-lang/crystal#1242] opened 2015-08-20 03:14 UTC
I can't reproduce this on the REPL, because I'm not sure what causes it. But my code won't compile and says ```type must be (StringIO | ArrayStream), not (StringIO | ArrayStream | DeltaChecker::RangedSubStream)```. I was assigning an instance variable at the time.

Shouldn't the type unioning system figure "well, obviously this variable has to be a (StringIO | ArrayStream | RangedSubStream) so I'll make it be one of those"? Why does it pick the first two and then fall apart when I assign it later on? Isn't that the whole *point* of the unioning system? That it's automatic?

I could really use an explanation for this one. If necessary, I'll zip my entire project and upload it somewhere for you guys to examine.

**Comment by bjmllr** [comment] 2015-08-20 04:12
I don't think I can help with this particular question, but I'll attempt to review your project if you upload it to github. Kinda curious to see what your range operations do.

**Comment by asterite** [comment] 2015-08-20 12:51
Please send your code, because without it there's no way we can reproduce the issue.

**Comment by stugol** [comment] 2015-08-21 12:08
That is very strange. Yesterday I replied to this thread and gave you guys a link to my code. And today....that post is gone. Wtf?

**Comment by stugol** [comment] 2015-08-21 12:43
Anyhow, here's the link: https://www.dropbox.com/s/4umuwctvqs0sdh3/DeltaBackup-crystal.zip?dl=0

The entry point is the tests file.

**Comment by asterite** [comment] 2015-08-21 14:05
I was able to reproduce this with this:

```crystal
def match_block(&block : Int32 -> U)
  yield 1
end

class Foo
  def initialize(@value)
  end

  def value
    @value
  end
end

f = Foo.new(1)
match_block { |x| f.value }

Foo.new("hello")
```

The problem is that that "U" is freezed to be the type of the block (Int32), but then it changes when you create an instance of Foo, and the compiler disallows that. This is a current limitation but for some reason it doesn't happen that often. We need to fix this, but it'll probably require some rewrite of the type inference algorithm.

As a workaround for now you can do:

```
@stream :: StringIO | ArrayStream | DeltaChecker::RangedSubStream
```

That'll tell you that ArrayStream and RangeSubStream are not defined so you'll have to forward-declare them:

```crystal
class DeltaChecker; class RangedSubStream; end; end
class ArrayStream; end
```

**Comment by stugol** [comment] 2015-08-21 15:17
That workaround ain't gonna be much help. I don't know ahead of time what types I will be using. It's a generalised class, and needs to support any type that has the necessary methods.

How do I write a container class that won't freeze?

**Comment by asterite** [comment] 2015-08-21 17:08
@stugol It's a bug that we need to fix. Until we fix it you'll have to workaround it...

**Comment by asterite** [comment] 2015-08-21 17:15
We have some ideas on how to fix it but, as I said, it's not trivial.

**Comment by stugol** [comment] 2015-08-21 19:34
Well, that's unfortunate. Because if you're saying that a non-freezing container class cannot be done at present, this basically means development of DeltaBackup stops.

**Comment by asterite** [comment] 2015-08-21 22:38
@stugol With the above commit and this diff:

```diff
diff --git a/src/array.cr b/src/array.cr
index f165201..445d97c 100644
--- a/src/array.cr
+++ b/src/array.cr
@@ -120,8 +120,8 @@ class Array(T)
   # ary[0][0] = 2
   # puts ary #=> [[2], [1], [1]]
   # ```
-  def self.new(size : Int, &block : Int32 -> T)
-    Array(T).build(size) do |buffer|
+  def self.new(size : Int)#, &block : Int32 -> T)
+    Array(typeof(yield 0)).build(size) do |buffer|
       size.times do |i|
         buffer[i] = yield i
       end
@@ -786,8 +786,8 @@ class Array(T)
     @length = length.to_i
   end
 
-  def map(&block : T -> U)
-    Array(U).new(length) { |i| yield buffer[i] }
+  def map
+    Array.new(length) { |i| yield buffer[i] }
   end
 
   def map!
```

your project compiles. We still need to fix a few things, which are more complicated than the above fix, but eventually we'll get it :-)

**Comment by stugol** [comment] 2015-08-21 23:34
What do the ```@@ -786,8 +786,8 @@``` bits mean?

**Comment by kirbyfan64** [comment] 2015-08-21 23:47
@stugol Line numbers. They're input for `git diff`. Copy the patch into a file and run `git apply filename`.

**Comment by stugol** [comment] 2015-08-22 12:07
Thanks guys. I'll give it a try.

I'm not sure if this is even possible, depending on how the compiler works internally, but... Not all code needs the performance of static typing. It would be nice to be able to declare an "any type" variable, that basically works like Ruby variables, and uses dynamic dispatch.

**Comment by asterite** [comment] 2016-04-13 19:43
After #2443, the suggested workaround of specifying a type is now the regular solution to the problem, so I'm closing this.

**Closed by asterite** 2016-04-13 19:43 UTC
Labels: bug, compiler
