### ISSUE TITLE
Hexadecimal number subtraction error

### ISSUE THREAD

**Issue by ethe** [crystal-lang/crystal#2238] opened 2016-02-27 16:34 UTC
Compiler version: 0.12
```crystal
0x20000_0000-0x10000_0000 # unexpected token: 0
0x20000_0000 - 0x10000_0000 #=> 4294967296
0x10000_0000-0x10000_0000 # unexpected token: 0
0x10000_0000 - 0x10000_0000 # => 0
```

**Comment by asterite** [comment] 2016-02-27 21:45
Actually a duplicate of #2165, already fixed in master

**Closed by asterite** 2016-02-27 21:45 UTC
Labels: bug, compiler
