### ISSUE TITLE
Support for OpenSSL 3.2.0

### ISSUE THREAD

**Issue by femto** [crystal-lang/crystal#14168] opened 2024-01-04 12:45 UTC
## Bug Report

the commit cb333fed2 when make std_spec
```
Invalid memory access (signal 11) at address 0x(???)
[0x1064ef57b] *Exception::CallStack::print_backtrace:Nil +107 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x105a6889d] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil)@src/crystal/system/unix/signal.cr:131 +285 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x7ff80f17adfd] _sigtramp +29 in /usr/lib/system/libsystem_platform.dylib
[0x7ff816939a7b] xmlFindCharEncodingHandler +175 in /usr/lib/libxml2.2.dylib
[0x7ff8169a22b1] xmlNewSaveCtxt +103 in /usr/lib/libxml2.2.dylib
[0x7ff8169a2490] xmlSaveToIO +31 in /usr/lib/libxml2.2.dylib
[0x1070201e1] *XML::Node#to_xml<String::Builder>:String::Builder +513 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x10701ffd9] *XML::Node#to_s<String::Builder>:Nil +9 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x10715cade] *XML::NodeSet@Enumerable(T)#join<String::Builder, Char>:Nil +158 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x10715ca3e] *XML::NodeSet#to_s<String::Builder>:Nil +14 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x10715ca12] *XML::NodeSet@Object#to_s:String +66 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106458ffd] ~procProc(Nil)@spec/std/xml/xpath_spec.cr:210 +141 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106a285a0] *Spec::Example#internal_run<Time::Span, Proc(Nil)>:(Array(Spec::Result) | Nil) +224 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106a28492] *Spec::Example#run:Nil +1234 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106a2ba4a] *Spec::ExampleGroup@Spec::Context#internal_run:Nil +122 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106a2b8f7] *Spec::ExampleGroup#run:Nil +359 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x1068fe204] *Spec::RootContext+@Spec::Context#internal_run:Nil +164 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x1068fe15a] *Spec::RootContext+@Spec::RootContext#run:Nil +26 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x1068b7140] *Spec::execute_examples:Nil +32 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x105aadd30] ~procProc(Int32, (Exception | Nil), Nil)@src/spec/dsl.cr:208 +64 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106838c7e] *Crystal::AtExitHandlers::run<Int32, (Exception+ | Nil)>:Int32 +142 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106ae17e1] *Crystal::exit<Int32, (Exception+ | Nil)>:Int32 +33 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x106ae1761] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +97 in /Users/femtozheng/c-project/crystal/.build/std_spec
[0x1059ea049] main +9 in /Users/femtozheng/c-project/crystal/.build/std_spec
make: *** [std_spec] Error 11
```
I've built crystal several commits earlier, so probably this one is not using lastest crystal?
so I tried : make && make std_spec
now:
```
Unhandled exception in spawn: SSL_read: I/O error (OpenSSL::SSL::Error)
  from src/openssl/ssl/socket.cr:137:9 in 'unbuffered_read'
  from src/io/buffered.cr:82:16 in 'read'
  from src/io.cr:1176:12 in 'copy'
  from src/io.cr:566:9 in 'gets_to_end'
  from spec/std/openssl/ssl/socket_spec.cr:167:20 in '->'
  from src/fiber.cr:146:11 in 'run'
  from src/fiber.cr:98:34 in '->'
Caused by: SSL_read: Undefined error: 0 (RuntimeError)
```
and it hangs

one question, would make std_spec automatically call make? or do I need to make && make std_spec?

**Comment by straight-shoota** [comment] 2024-01-04 13:49
These errors doent seem very related, except that they're both involving some external libraries.
My guess would be some dependency incompatibility perhaps?
What versions of libxml and libssl are you using?

> would make std_spec automatically call make? or do I need to make && make std_spec?

No, `make std_spec` does not build the compiler. It calls the wrapper script `bin/crystal` which uses a local compiler build if available (`.build/crystal`) or whatever compiler executable you have in `$PATH`. The script should print a notifcation (`Using compiled compiler at .build/crystal`) to stderr if it uses a local build.
If you want to make sure to have a local build, you need to run `make`. To get rid of it, run `make clean`.

**Comment by femto** [comment] 2024-01-04 14:13
my `make std_spec` doesn't print out using local compiler
xml2-config --version 
reports 2.9.4
openssl version 
reports
OpenSSL 3.2.0 23 Nov 2023 (Library: OpenSSL 3.2.0 23 Nov 2023)

**Comment by straight-shoota** [comment] 2024-01-04 14:21
Thanks. I can reproduce the error with OpenSSL 3.2.0.

**Comment by straight-shoota** [comment] 2024-01-04 14:52
This seems to be an issue with our error handling code for `SSL_read`. Unfortunately, it is quite convoluted.

https://github.com/crystal-lang/crystal/blob/e3200d9eb8814e92849503e646325b09647cfe9e/src/openssl/ssl/socket.cr#L129-L139

The error constructor tries to determine the reason for the error, particularly if it's an EOF (lines 92-98):

https://github.com/crystal-lang/crystal/blob/e3200d9eb8814e92849503e646325b09647cfe9e/src/openssl.cr#L83-L110

Apparently the error return value of `SSL_read` changed in OpenSSL 3.2 from `0` to `-1`. But our codes usese this differenceto tell EOF from other errors.
According to the [current OpenSSL docs](https://www.openssl.org/docs/man1.0.2/man3/SSL_get_error.html) for `SSL_ERROR_SYSCALL`, you should rather consult `errno` in this case. And it seems that a success value there means EOF.
So I'll try that.

**Comment by Blacksmoke16** [comment] 2024-01-10 05:44
Resolved via https://github.com/crystal-lang/crystal/pull/14169

**Comment by straight-shoota** [comment] 2024-01-11 20:19
https://github.com/crystal-lang/crystal/pull/14169 was eventually reverted. A new approach is growing in https://github.com/crystal-lang/crystal/pull/14219

**Closed** 2024-03-15 10:48 UTC
Labels: kind:feature, topic:stdlib:crypto
