### ISSUE TITLE
macro def doesn't have access to constants of child class

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2616] opened 2016-05-18 23:21 UTC
Regression from 0.17: https://carc.in/#/r/yv9 (0.17) https://carc.in/#/r/yva (0.16)

```cr
class Base
  macro def foo : Int32
     FOO
  end
end

class Foo < Base
  FOO = 1
end

p Foo.new.foo
```
```
Error in line 11: instantiating 'Foo#foo()'

in line 3: undefined constant FOO (did you mean 'Foo'?)
```
Expected:
```
1
```

Surrounding in `{% begin %} / {% end %}` doesn't help either.

This breaks artanis design.

**Comment by jhass** [comment] 2016-05-18 23:26
Well, ok, it can be worked around with `{{@type}}::FOO`, still feels like a regression, if wrapped in `{% begin %} / {% end %}` at least.

**Comment by asterite** [comment] 2016-05-18 23:51
I actually changed this on purpose but we should discuss what to do with this. I checked [the](https://github.com/crystal-lang/crystal/commit/2e675598f6036b8cc1affd1c5a5dce8b2e9891d9) [relevant](https://github.com/crystal-lang/crystal/commit/e780cee1fd67e9175a7948ac29029719b9af42c9) [commits](https://github.com/crystal-lang/crystal/commit/d57027429b2923bbfd33011fe37c5147c3ebf4f5) and I didn't change existing specs, which means that how constant resolution worked was never documented (though I did have to use the `{{@type}}::Foo` trick [here](https://github.com/crystal-lang/crystal/commit/e780cee1fd67e9175a7948ac29029719b9af42c9), in Enum).

My reason was this:

```crystal
class Foo
  # :nodoc:
  class Internal
  end

  macro def foo
    Internal.new(...)
  end
end

class Bar < Foo
  # I define a class that's kind of internal to Bar,
  # but oops, I just broke `foo`
  class Internal
  end
end
```

In regular methods, type lookup starts from the type that defined the method, exactly because of the above reason, so a subclass doesn't "hijacks" Foo's intended behaviour (this is also how Ruby works, you can try it, and then you can do `self.class::Internal` if you want the lookup to be relative to the real `self`).

We have two choices:
1. Continue this way, and use `{{@type}::...`
2. Revert and use the old way, adding a spec and documenting this behaviour

I'm not sure. I'm more inclined towards 1 because it's more explicit about types that should be resolved relative to the type where the macro is finally expanded. However, since the macro is expanded in each subtype, maybe 2 should be the default behaviour, but then you kind of have to do `::Foo::Bar` and `::Foo::Baz` or `::String` to make sure a subtype doesn't overrides a type you intended to be there.

Point 1 is also more similar to how Ruby works.

What do you think?

**Comment by asterite** [comment] 2016-05-18 23:52
What I mean with the above is that I changed it because I considered the behaviour before 0.17.0 to be buggy (I thought it was a bug, because the compiler worked in that way for some methods too, before), so I decided to "fix" it.

**Comment by jhass** [comment] 2016-05-19 07:15
What about 1 normally and 2 inside the macro language, that is within `{{}}`, `{%%}`, `{% begin %} {% end %}` etc?

**Comment by ozra** [comment] 2016-05-19 08:19
I still haven't used macros as extensively as to make them the basis of some project, so my 2c here are of lower value in that respect, but with my limited use I definitely think using `{{@type}}` in the above scenario is "the right thing to do".

**Comment by asterite** [comment] 2016-05-27 19:30
I'm closing this. I think it's better to force the usage of `{{@type}}`, specially because that means the method will automatically be marked as a macro def.

**Closed by asterite** 2016-05-27 19:30 UTC
Labels: bug, compiler
