### ISSUE TITLE
Bug in case?

### ISSUE THREAD

**Issue by DebugReport** [crystal-lang/crystal#4008] opened 2017-02-07 06:31 UTC
```
int = 3
case int
when 0
    puts 0
when 1, 2, Int32
    puts "1 | 2 | Int32"
else
    puts int
end
```
Output:
```
laptop% crystal build ./test.cr
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  call void @"*raise<String>:NoReturn"(%String* bitcast ({ i32, i32, i32, [87 x i8] }* @"'can't execute `puts...'" to %String*))

Error opening file 'crystal' with mode 'r': No such file or directory (Errno)
Failed to raise an exception: END_OF_STACK
[4233386] __crystal_raise +202
[4252558] ???
[4323338] ???
[4304319] ???
[4298527] ???
[4271090] ???
[4385730] main +19394
[140623209939601] __libc_start_main +241
[4232282] _start +42
[0] ???
laptop% crystal --version
Crystal 0.20.5 (2017-01-25)
```

**Comment by MakeNowJust** [comment] 2017-02-07 14:18
Reduced version:

```crystal
i = 1
1 || i.is_a?(Int32) ? "" : i
```

**Comment by asterite** [comment] 2017-02-07 22:37
@MakeNowJust It seems to be a different bug (the error given by the compiler is different), I opened #4009. Thank you for reducing it, though, and finding another bug! :-)

**Comment by asterite** [comment] 2017-02-07 22:39
This is actually a duplicate of #4008 (same symptom)

**Closed by asterite** 2017-02-07 22:39 UTC
Labels: kind:bug, topic:debugger
