### ISSUE TITLE
Array#products(*args) not working with multiple arrays.

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#9190] opened 2020-04-27 20:41 UTC
When passing arrays as args to `Array#product` I get an error for wrong number of arguments.  It seems like this should be implemented by this API https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L1395.

Does not work:
```crystal
[1, 2, 3].product([3, 4], [5, 6])
```

Does work:
```crystal
[1, 2, 3].product([[3, 4], [5, 6]])
```

**Comment by jhass** [comment] 2020-04-27 20:47
No, that's `Array.product`, not `[].product` :)

**Comment by wontruefree** [comment] 2020-04-27 21:41
To follow Ruby should we have `[].product`?

**Comment by asterite** [comment] 2020-04-27 21:43
`product` is already a thing, it multiplies all the values in the array. That's why you have to use `Array.product` and not `Array#product`.

Duplicate of #3790

**Closed by asterite** 2020-04-27 21:43 UTC
