### ISSUE TITLE
External Lib Opaque Types don't define Pointer class methods

### ISSUE THREAD

**Issue by Groogy** [crystal-lang/crystal#4736] opened 2017-07-22 13:39 UTC
So stumbled across this and don't think I saw any previous report on it. But I had a problem where I needed to reset a pointer defined in an external library to null so I didn't get an unnecessary union type of Lib::Type | Nil. However I then discovered that opaque type's defined in a C library don't get the class methods of the type they are defined based on making the null method not available.

```crystal
lib Test
  type T = Void*
end

value = Test::T.null
```

Will give a compile error while this will work just fine

```crystal
lib Test
  type T = Void*
end

a = Pointer(Void).null.as(Test::T)
```

Would look a lot better if I could just use `Test::T.null` instead.

**Comment by bew** [comment] 2017-07-23 08:52
This issue is the same as #4682 in a way: a lib-type is not the same as the typed type. My issue was about constants (and inspect), yours is about methods, but I think it's the same underlying problem:
Quote from @ysbaddaden:
> Not a bug: you create a new type. Any constant (or methods) defined on the previous type simply don't exist in the new namespace.

FWIW: This is what I think it should be https://github.com/crystal-lang/crystal/issues/4682#issuecomment-315665354.

**Comment by ysbaddaden** [comment] 2017-07-24 08:45
You may just use `nil`, Crystal will automatically cast it to a NULL pointer when passed to C functions.

**Comment by Groogy** [comment] 2017-07-24 10:07
That would be highly impractical since the variable would be a union type of Lib::OpaqueType | Nil which has a range of complications besides making functions using that having to both check for .nil? and then .null? to make sure it is not misusing values. But then another problem appears, Nil does not implement .null? and being a union type now it will provide a compile error. 

Here's an example of what I am talking about as a minimal example but should demonstrate a common use case that would occur.
```crystal
lib Test
  type T = Void*
  
  fun createStuff() : T
  fun killStuff(val : T) : Void
end

class Foobar
  def initialize(@ptr : Test::T)
  end

  def finalize()
    unless @ptr.nil? || @ptr.null?
      Test.killStuff(@ptr)
      @ptr = nil
    end
  end
end

ptr = Test.createStuff()
obj = Foobar.new(ptr)
```
Will give me the compile error that Nil does not implement the .null? method which I think is more important to check for than the value nil since the Test.createStuff function might have returned null for all we know.

In my opinion, being able to null the value of a opaque library type that permits it should be easy to do since it is a common behavior you should be dealing with when it comes to external C libraries.

**Comment by konovod** [comment] 2017-07-24 10:47
Doesn't
```crystal
lib Test
  type T = Void*
  INVALID_T = nil.as(Test::T)
end

value = Test::INVALID_T
```
solves the problem and looks better (as it provides additional information about what actually `null` means in case of T)?

**Comment by ysbaddaden** [comment] 2017-07-24 10:50
Opaque C types should only be generated from C, you should never have to generate or define them in Crystal. Either the pointer is returned, or you can use the `out` keyword.

You don't have to check `pointer.null?` specifically, because a NULL pointer is always false.

Your initialiser is good, but you finalizer should make a local copy. You don't need the instance variable to be a nilable either:

```crystal
def initialize(@ptr : Test::T)
end

def finalize
  if ptr = @ptr
    Test.killStuff(ptr)
  end
end
```

And you're done.

**Comment by Groogy** [comment] 2017-07-24 11:01
The finalizer in the case here is called by not only the GC because it needs to guarantee that if the entire subsystem is closing down that the acquired pointer needs to be destroyed first or you will call the "destroy" library function on memory that has already been destroyed as the subsystem is shutting down which does also mean you need to reset the value to some invalid state telling your code to not try and destroy it again hence the reset to a null state.

This is a normal problem with GC since you can't guarantee in what order memory will be reclaimed and as such you can end up trying to destroy something inadvertently twice. The code you suggest would have quite high probability to just crash but you can't really be sure. (I learned this while working in D where this happened quite consistently for the reasons I just gave)

**Comment by asterite** [comment] 2017-09-10 15:11
Duplicate of #4682

**Closed by asterite** 2017-09-10 15:11 UTC
Labels: status:discussion, topic:compiler
