### ISSUE TITLE
Feature Request: Interfaces

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang/crystal#4404] opened 2017-05-12 15:22 UTC
I would love to see Interfaces as a language feature in crystal. Similar to go, an interface...

* Can be the type of an argument.
* Should only expose the methods of the underlying object that are part of the interface.
* Should not have to tell a class that it implements the interface, but if the object "fits" the interface definition then the class implements it.
* Are strong contracts.

See the following example of how an interface my be specified and used within Crystal.

```crystal
class MyInt
  def test(one : String, two : String) : Nil
    puts one
    puts two
  end

  def test(one : String, two : Int) : String
    "#{one} #{two}"
  end

  def best : Int
    42
  end
end

interface AInt
  test(String, String) : Nil
  test(String, Int) : String
  best : Int
end

def uses_a_int(a : AInt)
  a.test("1", "2")
  puts a.test("1", 2)
  puts a.best
end

uses_a_int MyInt.new
```

**Comment by kirbyfan64** [comment] 2017-05-12 15:28
#3489

**Comment by ysbaddaden** [comment] 2017-05-13 07:57
Duplicate of #3489

**Closed by ysbaddaden** 2017-05-13 07:57 UTC
