### ISSUE TITLE
0.26.1 compilation fails at Arch Linux

### ISSUE THREAD

**Issue by anatol** [crystal-lang/crystal#6672] opened 2018-09-06 22:37 UTC
Trying to build 0.2.6.1 package in a clear build chroot environment at Arch Linux and I get following failure:

```
Using /usr/bin/llvm-config [version=6.0.1]
g++ -c -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/include -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -W -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wno-maybe-uninitialized -Wdelete-non-virtual-dtor -Wno-comment -ffunction-sections -fdata-sections -O3 -DNDEBUG  -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -fPIC  -D_FORTIFY_SOURCE=2  -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
./bin/crystal build --release --no-debug --release --link-flags="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Using /usr/bin/llvm-config [version=6.0.1]
./bin/crystal docs -b https://crystal-lang.org/api/latest src/docs_main.cr
Using compiled compiler at `.build/crystal'
Unhandled exception: fcntl() failed: Bad file descriptor (Errno)
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
make: *** [Makefile:97: docs] Error 1
```

**Comment by Timbus** [comment] 2018-09-06 22:52
Almost definitely a duplicate of #6624
My apologies :(

**Comment by bararchy** [comment] 2018-09-07 05:03
@anatol it seems a fix landed in Master, @Timbus asked if you could retest using master branch (or @Timbus can you offer specific commit point?)

I guess we won't get an official 0.26.1 but at least we might get 0.26.2

**Comment by anatol** [comment] 2018-09-07 05:06
I prefer to test a fix commit alone rather than master with many changes. If the fix is going to work then I can release 0.26.1 package to Arch repos.

**Comment by Timbus** [comment] 2018-09-07 05:30
I guess the fix commit is here: https://github.com/crystal-lang/crystal/commit/b697de03deed7647a7bebe0e0987cb660854bdac

You could possibly apply that as a patch, or check it out at that commit. Would recommend you try building master first and making sure it has been fixed.

**Comment by anatol** [comment] 2018-09-07 06:01
Thanks for the pointer.

master branch builds fine, and 0.26.1 release with the patch above also builds fine. I just pushed 0.26.1 package to Arch [testing] repo. @bararchy please verify that it works as expected.

**Comment by bararchy** [comment] 2018-09-07 07:28
@anatol The testing package works great for me and the team, we tested on 6 different systems and compiled 9 internal + external projects.

**Closed** 2018-09-07 09:28 UTC

**Comment by drosehn** [comment] 2018-09-07 17:12
FWIW, I'm seeing the same result:
> Unhandled exception: fcntl() failed: Bad file descriptor (Errno)
  from ???
  from ???
  from __crystal_main
  ...etc...

When I tried to build crystal 0.26.1 on macOS 10.11.6 (El Capitan) using homebrew.  I have not tried with the fix.   (I had not noticed this PR until about 10 minutes ago...).
