### ISSUE TITLE
OptionParser fails when combining two short options

### ISSUE THREAD

**Issue by spinscale** [crystal-lang/crystal#11026] opened 2021-07-27 10:15 UTC
## Bug Report

Version: 1.1.0

When you use the `OptionParser`, then two short options cannot be combined. I would consider this as normal, as noone writes `ls -a -l` instead of `ls -al`

```crystal
require "option_parser"

seccomp = false
log = false

OptionParser.parse do |parser|
  parser.banner = "Usage: webserver [arguments]"
  parser.on("-s", "--seccomp", "Enable seccomp policy") { seccomp = true }
  parser.on("-l", "--log", "Log seccomp violation only") { log = true }
  parser.on("-h", "--help", "Show this help") do
    puts parser
    exit
  end
  parser.invalid_option do |flag|
    STDERR.puts "ERROR: #{flag} is not a valid option."
    STDERR.puts parser
    exit(1)
  end
end

STDOUT.print "logging enabled #{log}\n"
STDOUT.print "seccomp enabled #{seccomp}\n"
```

Build via `crystal build crystal-options-parser-test.cr`

Then run

```bash
❯ ./crystal-options-parser-test -l
logging enabled true
seccomp enabled false

❯ ./crystal-options-parser-test -s
logging enabled false
seccomp enabled true

❯ ./crystal-options-parser-test -l -s
logging enabled true
seccomp enabled true

❯ ./crystal-options-parser-test -ls
ERROR: -ls is not a valid option.
Usage: webserver [arguments]
    -s, --seccomp                    Enable seccomp policy
    -l, --log                        Log seccomp violation only
    -h, --help                       Show this help
```

The last error is IMO unexpected and a bug.

**Comment by HertzDevil** [comment] 2021-07-27 10:17
Duplicate of #10981.

**Comment by Sija** [comment] 2021-07-27 10:17
Duplicate of #10981

**Closed** 2021-07-27 10:58 UTC
Labels: status:duplicate
