### ISSUE TITLE
For loop cannot locates in a single block in Macro

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6747] opened 2018-09-19 10:50 UTC
Explain this bug using an example.

This works, of course. [play.crystal](https://play.crystal-lang.org/#/r/51j1)
``` crystal
macro for_loop(arr)
{% for a in arr %}
  {% p a %}
{% end %}
end

for_loop [1,2,3]
```
But this fail, [play.crystal](https://play.crystal-lang.org/#/r/51j3):
``` crystal
macro for_loop(arr)
{%
  for a in arr
    p a
  end
%}
end

for_loop [1,2,3]
```

I'm not sure whether it's a standard way, but `if ... end` could be in a single block and it's sometimes really useful and brief.

**Comment by vladfaust** [comment] 2018-09-19 12:33
Duplicate of https://github.com/crystal-lang/crystal/issues/6644

**Closed** 2018-09-19 12:34 UTC
