### ISSUE TITLE
Issue with the scoping of `with ... yield`

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#5117] opened 2017-10-14 09:00 UTC
The compiler get lost when we use a `with ... yield` structure and pass the block through more than 1 level.

The same happens if I want to type my block as `&block : -> _` for example.

```crystal
class Test
  def self.test(&block)
    with Test.new yield
  end

  def x
    "Hello world"
  end
end

def calling_of_test(&block)
  Test.test(&block)
end

# => works well
p Test.test { x }

# Error in weird.cr:19: undefined local variable or method 'hello'
calling_of_test { x }
```

**Comment by anykeyh** [comment] 2017-10-14 09:03
Note: I just saw #4436 and I think I reported a duplicate

**Comment by asterite** [comment] 2017-10-14 13:32
Not a bug and not a duplicate of #4436

There's no way to forward a block that is used in `with ... yield`. You can do this however:

```crystal
class Test
  def self.test(&block)
    test = new
    with test yield test
  end

  def x
    "Hello world"
  end
end

def calling_of_test(&block)
  Test.test do |test|
    with test yield test
  end
end

# => works well
p Test.test { x }

# => works well too
calling_of_test { x }
```

But this is not a workaround, it's the only way to do it and I doubt we'll improve this (at least soon).

**Comment by anykeyh** [comment] 2017-10-14 16:00
Ok, I understand it's not a bug (unexpected behavior) but more like a missing feature (unpossible behavior). It reduces the scope of usability of `with ... yield` structure for DSL.

How I wish I had competency to give help to improve Crystal 😉, keep doing the good work 👍

**Closed** 2017-10-14 16:32 UTC
