### ISSUE TITLE
Global exception/sigfault handler

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#4183] opened 2017-03-24 02:10 UTC
I'd like to suggest adding global sigfault and uncaught exception handler.
It would be run just before main code in `__crystal_sigfault_handler` and `__crystal_exception_handler` respectively.

API similar to below would imho be flexible 'nuff:

```cr
previous_handler = exception_handler # we can chain the handlers
exception_handler do |klass, msg, backtrace|
  # ...
  previous_handler.try &.call(klass, msg, backtrace)
end
```

I could make a stab at PR if there's a consensus about feasibility of such feature.

Below as a reference, the same feature implementation in other languages:
- Python: https://pymotw.com/2/sys/exceptions.html
- Java: http://docs.oracle.com/javase/6/docs/api/java/lang/Thread.html#getUncaughtExceptionHandler%28%29
- C#: https://msdn.microsoft.com/en-us/library/system.appdomain.unhandledexception(v=vs.110).aspx

**Comment by RX14** [comment] 2017-03-24 09:13
The C# and Java solutions only capture unhandled exceptions, which is a bit different to what there is here. In addition, I don't think there's actually a way to find out if an exception is meaningfully handled or not (all exceptions are handled, just in the stdlib).

**Comment by Sija** [comment] 2017-03-24 11:00
You write:
> The above solutions only capture unhandled exceptions, which is a bit different to what you propose.

First sentence of this issue states:
> I'd like to suggest adding global sigfault and uncaught exception handler.

You write:
> I don't think there's actually a way to find out if an exception is meaningfully handled or not in crystal (all exceptions are handled, just in the stdlib).

`__crystal_sigfault_handler` and `__crystal_exception_handler` could imo be the way to exactly achieve that.

**Comment by RX14** [comment] 2017-03-24 17:32
@Sija What I meant was that simply adding a callback to `__crystal_raise` wouldn't work because it would trigger on all exceptions not just uncaught ones.

On further thought, adding a handler [here](https://github.com/crystal-lang/crystal/blob/917971dedc08e57f18f794f8d47ffc02a63b6159/src/main.cr#L6) and [here](https://github.com/crystal-lang/crystal/blob/917971dedc08e57f18f794f8d47ffc02a63b6159/src/fiber.cr#L114) would be enough.

**Comment by ysbaddaden** [comment] 2017-03-27 13:58
What is the expected behaviour? May the handler prevent the process from exiting? This would be fine for unhandled exceptions, but maybe it would be a bad idea for the segfault handler.

**Comment by Sija** [comment] 2017-03-27 18:41
@RX14 you're right, I somehow got confused between `__crystal_sigfault_handler` and `__crystal_raise` creating `__crystal_exception_handler` which seems sensible but unfortunately doesn't exists ;)

@ysbaddaden I'd think so, exception handler could for instance return false to abort exiting, while sigfault handler would run without ability to halt exit.

**Comment by akzhan** [comment] 2017-06-05 19:46
Looks like we need `Fiber.on_unhandled_exception` exception handler, but without resuming of fiber execution. 

Some exceptions that corrupts process state should be not handled (out of memory, for example). May be by common parent class.

**Comment by straight-shoota** [comment] 2020-12-03 19:40
The exact use case scenario of this feature isn't clear to me. Some aspects might've changed since then, so not even sure this is still relevant. I'm closing this, can be-opened if necessary.

**Closed by straight-shoota** 2020-12-03 19:40 UTC
Labels: kind:feature, status:discussion
