### ISSUE TITLE
http/client fails running in Alpine Linux 3.10 docker image

### ISSUE THREAD

**Issue by steve-baldwin** [crystal-lang/crystal#7926] opened 2019-06-27 00:35 UTC
I posted about this on the [forum](https://forum.crystal-lang.org/t/utf8-issues-with-alpine-linux/888) but so far no response.

I've only seen the issue on Alpine Linux.  My [test case](https://github.com/horrendo/t-alpine)  runs fine on debian and OS/X.

**Comment by relistan** [comment] 2019-10-14 19:09
I am seeing this with 0.31.1 on Alpine linux as well. This worked on previous builds of Crystal.

**Comment by horrendo** [comment] 2019-10-14 20:00
I've found the `-Dmusl` seems to fix things. Have you tried that?  From my test case, the build command is `RUN shards build -Dmusl --production`, and I can't reproduce the error any more.

**Comment by relistan** [comment] 2019-10-15 10:14
Thanks, it looks like adding `-Dmusl` does solve the general compilation issues. The remaining issues I'm having seem to be that the gc lib on Alpine is not compatible with `-Dmt_preview` (missing symbols) but that is a different issue.

**Comment by straight-shoota** [comment] 2019-10-15 12:07
That's helpful. It seems that the default target detection doesn't work correctly:
```shell
alpine $ crystal --version
Crystal 0.29.0 [58cdadabf6] (2019-06-07)

LLVM: 5.0.2
Default target: x86_64-alpine-linux-gnu
```

It should be `x86_64-alpine-linux-musl`.
A better workaround than passing `-Dmusl` is `--target x86_64-alpine-linux-musl`.

Investigating the detection process on alpine, it happens that `ldd --version` (which is used to tell musl vs gnu) changed behaviour in alpine 3.10:

```shell
alpine:3.9 $ ldd --version
musl libc (x86_64)
Version 1.1.20
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```
```shell
alpine:3.10 $ ldd --version
/lib/ld-musl-x86_64.so.1: cannot load --version: No such file or directory
```

This is a regression bug in alpine 3.10 and has been fixed in edge (https://gitlab.alpinelinux.org/alpine/aports/commit/2f2f995d9d52484720dbe8b4b1649c132ec1feee)
```shell
alpine:edge $ ldd --version
musl libc (x86_64)
Version 1.1.23
Dynamic Program Loader
Usage: /lib/ld-musl-x86_64.so.1 [options] [--] pathname
```

**Comment by relistan** [comment] 2019-10-15 12:20
Thanks @straight-shoota, great info!

**Comment by straight-shoota** [comment] 2019-10-15 13:16
So this is essentially a duplicate of #8330

**Closed by straight-shoota** 2019-10-15 13:16 UTC
