### ISSUE TITLE
RFC: Manual control of allocation

### ISSUE THREAD

**Issue by jkthorne** [crystal-lang/crystal#9532] opened 2020-06-22 20:39 UTC
## Context
Some projects like cockroachdb are written in languages that have a GC and express they like those languages and they are a good choice.  However there are few hot paths that they have to be concerned about GC.  This is where abstractions break down and the code becomes less semantic as they try and manipulate the GC for tuning.

## Solution
Crystal can provide an escape hatch from the GC for more control when needed.  Crystal can provide an interface where objects will be mallocated and deallocted independently of the GC.

### Solution 1: Annotation
Pros: Easy to implement both allocations in a class and switch on the annotations.
Cons: This is at a class level and would be require more work for someone to use in the example above.

```crystal
@[Allocation("manual")]
class Foo
end

Foo.new # => not managed by GC
Bar.new # => managed by GC
```

### Solution 2: Macro
Crystal would provide a macro for allocating an object that was not managed by the GC.
Pro: This could be object specific.
Con: There would still need to be an interface to implement.

```crystal
manual Foo.new # => not managed by GC
Foo.new        # => managed by GC
```

### Solution 3: Alternative initializer
Crystal could provide and alternative initializer that would create an un-managed object. 
Pros: can be more easily implemented at an Object level.
Cons: Introduces new interface to objects

```crystal
Foo.gen # => not managed by GC
Foo.new # => managed by GC
```

**Comment by bcardiff** [comment] 2020-06-22 21:08
The proposal needs to consider

* how the deallocation will happen
* what is expected during the creation of objects within the manual allocation

The implementation will need to register that object as root in the GC to prevent collection of referenced objects. Or, the proposal should consider the scenario of nested objects.

**Comment by wontruefree** [comment] 2020-06-22 21:18
I did not cover deallocation in the RFC but I think you would have to free it by calling free or another method on it.

I would expect something similar to `GC_MALLOC_UNCOLLECTABLE` in boehm to be called.  I think it has expected behavior for the rest of Crystal.  The one thing I dont know is if something like `GC_MALLOC_UNCOLLECTABLE` would reduce the GC pressure as expected for projects like cockroachdb.  I would imagine it would be better then nothing.

Ideally the feature would allocate completely outside GC for complete manual control but I think that would be too unpredictable for managed language.  I think this feature would just help people that want to move in that direction.

**Comment by lbguilherme** [comment] 2020-06-25 16:15
If the manual allocation is specified at allocation time and not per class, this feature can later be utilized by the compiler itself to perform escape analysis of objects and transform what would be a GC allocation into a manual allocation, also adding the "free" call at the appropriate location.

Something like `x = Foo.allocate(false); x.initialize(...);` could do the job, with a later `GC.free_manual(x)`? Not sure.

**Comment by asterite** [comment] 2020-06-25 16:24
`allocate` already does `GC.malloc`. If any, escape analysis can be implemented without anything of this (just embedded in the compiler/codegen).

**Comment by yxhuvud** [comment] 2020-07-07 15:52
If the allocation would be defined on a per class level, then one option that hasn't been mentioned is to overload the `allocate` method for that class. This can be done by including a module that redefine it, so it would be perfectly reusable without having to resort to annotations or the like. Allocate is not (or at least not yet) a complicated method - the only issue with it for this use case is that it is not called directly by the user so it is inconvenient to parameterize. 

That would leave the actual functionality of allocating outside the control of the GC, and deallocating to be implemented elsewhere as a separate question. Perhaps it is better to start with the raw low-level functionality of how to provide that in a sane way (that cover brians points) rather than starting with the user interface.

**Comment by yxhuvud** [comment] 2020-07-07 16:00
BTW, a somewhat related area would be to give some control over alignment. In that case allocation strategy would probably need to be at instance level (ie, a particular instance of `Slice(UInt8)` should perhaps benefit from an alignment, but that doesn't mean all of them should). That might also be relevant to consider, depending on what path is chosen.

**Comment by straight-shoota** [comment] 2024-04-16 08:28
I think this is essentially a duplicate of #13481 (actually this one is older, but the other one has progressed further)
There are already some experimental features available: `Reference.pre_initialize` and `Reference.unsafe_construct` as well as `ReferenceStorage(T)`.

**Closed by straight-shoota** 2024-04-16 08:28 UTC
Labels: status:discussion, topic:lang
