### ISSUE TITLE
Discussion: Disambiguation of requires

### ISSUE THREAD

**Issue by jwaldrip** [crystal-lang/crystal#2891] opened 2016-06-21 22:53 UTC
> This is just to start a dialog. I love crystal and what the team has done thus far.

One thing I dislike about ruby is the ambiguity of the require syntax. I don't think requires should become global objects or constants. You should be able to control the assignment of other dependencies in the language. As someone who is debugging a certain file, I believe it is much easier to chase the rabbit when your dependencies are specified locally. 

Other languages where this exists:

* Go
* Python
* Node.js
* ES6

**Comment by jhass** [comment] 2016-06-22 10:33
See #140, #265, #1146, #2090, to some degree #1446 and https://github.com/crystal-lang/shards/issues/16

I think we discussed this pretty throughout by now and I still feel like it doesn't fit into some of the core language design decisions already taken, at all.

**Comment by ysbaddaden** [comment] 2016-06-22 12:44
Yes, closing as duplicate of #140 along with [this statement](https://github.com/crystal-lang/crystal/issues/140#issuecomment-128035557) by @asterite:
> we won't change the require system. We might introduce a concept similar to refinements if we later find the need for it.

**Closed by ysbaddaden** 2016-06-22 12:44 UTC
Labels: duplicate
