### ISSUE TITLE
crystal spec hangs when running Kemal specs with interpreter

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#13182] opened 2023-03-12 11:05 UTC
When running Kemal specs with interpreter the following spec just hangs on MBP M1 Mac 👇 You can't even `
Command + C` it, need to kill with process id 🌵 

```
ccrystal i spec/run_spec.cr
```

Source: https://github.com/kemalcr/kemal/blob/master/spec/run_spec.cr

Crystal version

```
Crystal 1.8.0-dev [01be77aec] (2023-03-11)

LLVM: 15.0.6
Default target: aarch64-apple-darwin22.3.0
```

**Comment by straight-shoota** [comment] 2023-03-12 11:12
This is most likely https://github.com/crystal-lang/crystal/issues/12241

**Comment by ysbaddaden** [comment] 2023-03-13 13:06
Reporter even stated that the only *Kemal* specs not passing were those related to `Process` :smile: 

https://github.com/crystal-lang/crystal/issues/12241#issuecomment-1179635029

**Comment by straight-shoota** [comment] 2023-03-13 13:08
Duplicate of https://github.com/crystal-lang/crystal/issues/12241

**Closed by straight-shoota** 2023-03-13 13:08 UTC
Labels: kind:bug
