### ISSUE TITLE
Fix/Implement own DNS resolver

### ISSUE THREAD

**Issue by jhass** [crystal-lang/crystal#2660] opened 2016-05-27 15:04 UTC
The current DNS resolver is broken for some usecases, buggy for others and some setups. We should replace it. See #2568 #2653 #2426.

A resolver written in Crystal is tricky since it would need to hook into OS specific APIs in order to resolve hosts from `/etc/hosts`, mDNS etc. Most POSIX API is blocking making it tricky to rely on in a language focused on asynchronous IO, see https://github.com/crystal-lang/crystal/issues/2426#issuecomment-221973912

This issue exists to collect issues in the current implementation and ways to mitigate them in possible replacements.

**Comment by lbguilherme** [comment] 2016-05-27 15:27
A possible implementation route would be using a library such as https://github.com/c-ares/c-ares instead of creating it from scratch. This one seems to be portable across POSIX and Windows and can integrate with libevent. For example:

> The `ares_fds` function retrieves the set of file descriptors which the calling application should select on for reading and writing for the processing of name service queries pending on the name service channel identified by channel.

From a very quick search, there are other libraries with similar functionality.

**Comment by asterite** [comment] 2016-06-01 14:55
I propose to use C's `getaddrinfo` until we solve this well in a non-blocking fashion. I think it's preferable to have a blocking thing that works well than a non-blocking thing that's broken (and sometimes in a subtle way). Yes, sometimes a program will have hiccups of up to 5 seconds, but it will eventually work well.

We'd have to revert [this commit](https://github.com/crystal-lang/crystal/commit/3bbf8b4c) and a maybe some others.

**Comment by zamith** [comment] 2016-06-04 02:32
At this point with Crystal 0.17.4 I cannot use `http/client` because of this. Is it something related to my system, or is it broken?

**Comment by ysbaddaden** [comment] 2018-05-15 14:01
Closing: this should have been fixed by #2745.

**Closed by ysbaddaden** 2018-05-15 14:01 UTC
Labels: kind:feature, topic:stdlib

**Comment by Sija** [comment] 2018-05-15 14:30
@ysbaddaden But was it? If so, why #6099 then?

**Comment by rdp** [comment] 2019-11-10 08:23
For followers, appears #6099 was caused by a shared v. static linking issue...FWIW...
