### ISSUE TITLE
missing documentation for JSON::PullParser

### ISSUE THREAD

**Issue by sam0x17** [crystal-lang/crystal#9643] opened 2020-07-29 22:45 UTC
`JSON::PullParser` is currently the most performant way of parsing JSON, however there are no docs and the API is extremely non-obvious. I've tried playing around with the methods a bunch of times (never got anything to work) so I can attest that it is not self-explanatory. Would love to see some docs on this.

**Comment by ibraheemdev** [comment] 2020-09-18 16:16
Duplicate of #8050

**Closed** 2020-11-26 22:37 UTC
Labels: kind:docs, kind:feature
