### ISSUE TITLE
Playground fails with C union due to instrumentation bug

### ISSUE THREAD

**Issue by Papierkorb** [crystal-lang/crystal#3171] opened 2016-08-17 15:41 UTC
Hello,

While toying around in the playground, I tried to use a C union. It doesn't seem to work properly, as a popup was shown telling me to report an issue here :)

**Crystal Version:** `Crystal 0.18.7 (2016-07-04)` *Installed via pacman*
**Platform:** `ArchLinux x64 on Linux 4.7.0`

I tried restarting the playground, but the problem persisted.

## Code

```crystal
lib U
  union Foo
    one : Int32
    two : Int16
  end
end
```

## CLI output
    Listening on http://localhost:8080
    E, [2016-08-17 17:34:21 +0200 #11669] ERROR -- : Instrumention bug found (session=1, tag=1).

## Exception

    Error in line 3: instantiating 'Crystal::Playground::Agent:Class#new(String, Int32)'

    instantiating 'Crystal::Playground::Agent#initialize(String, Int32)'

    in /usr/lib/crystal/compiler/crystal/tools/playground/agent.cr:8: instantiating 'HTTP::WebSocket:Class#new(URI)'

        @ws = HTTP::WebSocket.new(URI.parse(url))
                              ^~~

    in /usr/lib/crystal/http/web_socket.cr:26: instantiating 'HTTP::WebSocket::Protocol:Class#new(URI)'

        new(Protocol.new(uri))
                     ^~~

    in /usr/lib/crystal/http/web_socket/protocol.cr:267: instantiating 'new(String, String, (Int32 | Nil), Bool)'

          return new(host, path, uri.port, tls)
                 ^~~

    in /usr/lib/crystal/http/web_socket/protocol.cr:253: instantiating 'HTTP::Request#to_io((OpenSSL::SSL::Socket::Client | TCPSocket))'

        handshake.to_io(socket)
                  ^~~~~

    in /usr/lib/crystal/http/request.cr:51: instantiating 'HTTP::Cookies#add_request_headers(HTTP::Headers)'

        headers = cookies ? cookies.add_request_headers(@headers) : @headers
                                    ^~~~~~~~~~~~~~~~~~~

    in /usr/lib/crystal/http/cookie.cr:249: instantiating 'map()'

          headers.add("Cookie", map(&.to_cookie_header).join("; "))
                                ^~~

    in /usr/lib/crystal/enumerable.cr:465: no overload matches 'Array(U)#<<' with type String
    Overloads are:
     - Array(T)#<<(value : T)

        each { |e| ary << yield e }
                       ^~

**Comment by jhass** [comment] 2016-08-17 15:43
Duplicate of #3112

**Closed by jhass** 2016-08-17 15:43 UTC
