### ISSUE TITLE
Compiler bug

### ISSUE THREAD

**Issue by datanoise** [crystal-lang/crystal#1789] opened 2015-10-20 03:59 UTC
I've started porting my amqp.cr library to crystal 0.9 and run into the compiler bug:

```
Bug: trying to upcast Nil <- ((AMQP::Protocol::Frame+ -> Void))?
[4420353394] *CallStack::unwind:Array(Pointer(Void)) +82
[4420353297] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4420353256] *CallStack::new:CallStack +40
[4420356865] *Exception#initialize<Exception, String, Nil>:CallStack +33
[4420356796] *Exception::new<String>:Exception +92
[4420189673] *raise<String>:NoReturn +9
[4430583777] *Crystal::CodeGenVisitor#upcast_distinct<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+>:NoReturn +97
[4430581612] *Crystal::CodeGenVisitor#upcast<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+>:LLVM::Value +2860
[4430940913] *Crystal::CodeGenVisitor::Phi#add<Crystal::CodeGenVisitor::Phi, LLVM::Value, Crystal::Type+, Bool>:(Nil | LLVM::Value) +321
[4430940571] *Crystal::CodeGenVisitor::Phi#add<Crystal::CodeGenVisitor::Phi, LLVM::Value, Crystal::Type+>:(Nil | LLVM::Value) +203
[4430734939] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::ExceptionHandler>:Bool +1435
[4420838159] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4415
[4430554824] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4430600000] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +256
[4420835049] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1305
[4430554824] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4430672623] *Crystal::CodeGenVisitor#codegen_call_with_block<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Block, Crystal::Type+, Array(LLVM::Value)>:LLVM::Value +1055
[4430640238] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +750
[4420838288] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4544
[4430554824] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4430600000] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +256
[4423986850] *Crystal::Expressions@Crystal::ASTNode#accept<Crystal::Expressions, Crystal::CodeGenVisitor>:Nil +50
[4421190752] *Crystal::Program#codegen<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +112
[4421190621] *Crystal::Program#codegen:debug:single_module:expose_crystal_main<Crystal::Program, Crystal::Expressions, Bool, (Nil | String | Bool | Array(String)), Bool>:Hash(String, LLVM::Module) +109
[4430028569] *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:Nil +1113
[4430024019] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +499
[4431144540] *Crystal::Command::CompilerConfig#compile<Crystal::Command::CompilerConfig, String>:Crystal::Compiler::Result +92
[4431111519] *Crystal::Command#run_command<Crystal::Command>:Nil +399
[4431101516] *Crystal::Command#run<Crystal::Command>:(Nil | Bool | Process::Status | Array(String) | IO::FileDescriptor+ | Crystal::Compiler::Result | Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class)) +1596
[4431099596] *Crystal::Command::run<Array(String)>:(Nil | Bool | Process::Status | Array(String) | IO::FileDescriptor+ | Crystal::Compiler::Result | Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class)) +44
[4431099469] *Crystal::Command::run:(Nil | Bool | Process::Status | Array(String) | IO::FileDescriptor+ | Crystal::Compiler::Result | Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class)) +45
[4420189186] __crystal_main +35858
[4420220663] main +39

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues
```

the code is located at github.com/datanoise/amqp.cr

**Comment by asterite** [comment] 2016-05-24 16:14
I'm closing this as there's no way to reproduce it. HEAD of amqp.cr compiles fine, and the old revision doesn't compile anymore because of language changes. Please reopen if needed.

**Closed by asterite** 2016-05-24 16:14 UTC
Labels: bug, compiler
