### ISSUE TITLE
Error running specs using HEAD on Ubuntu 14.04

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#4358] opened 2017-04-30 18:59 UTC
llvm: 4
Crash_Logs: 
```bash
root@RSAccessINT:/opt/build/crystal# make -j 4
Using /usr/bin/llvm-config [version=4.0.0]
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compile
r/crystal.cr -D without_openssl -D without_zlib
root@RSAccessINT:/opt/build/crystal# make spec
Using /usr/bin/llvm-config [version=4.0.0]
./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
fork: Cannot allocate memory
GC Warning: Repeated allocation of very large block (appr. size 266240):
        May lead to memory leak and poor performance.
GC Warning: Repeated allocation of very large block (appr. size 528384):
        May lead to memory leak and poor performance.
GC Warning: Repeated allocation of very large block (appr. size 528384):
        May lead to memory leak and poor performance.
0x7a3327: *CallStack::unwind:Array(Pointer(Void)) at ??
0x8c8162: fork_internal at /opt/build/crystal/src/process.cr 127:7
0x8c8fa3: initialize at /opt/build/crystal/src/process.cr 100:11
0x8c8ad2: new at /opt/build/crystal/src/process.cr 197:3
0x8c89db: run:output at /opt/build/crystal/src/process.cr 145:14
0x910e3c: lib_flags at /opt/build/crystal/src/compiler/crystal/codegen/link.cr 96:32
0x13ec95c: codegen at /opt/build/crystal/src/compiler/crystal/compiler.cr 244:7
0x13ef103: compile at /opt/build/crystal/src/compiler/crystal/compiler.cr 138:16
0x152f8b9: compile at /opt/build/crystal/src/compiler/crystal/command.cr 259:7
0x152f862: compile at /opt/build/crystal/src/compiler/crystal/command.cr 257:5
0x8cdc42: build at /opt/build/crystal/src/compiler/crystal/command.cr 175:5
0x8ccf44: run at /opt/build/crystal/src/compiler/crystal/command.cr 72:9
0x8ccc0b: run at /opt/build/crystal/src/compiler/crystal/command.cr 49:5
0x8ccbc9: run at /opt/build/crystal/src/compiler/crystal/command.cr 48:3
0x7724c7: __crystal_main at /opt/build/crystal/src/compiler/crystal.cr 8:1
0x787bb9: main at /opt/build/crystal/src/main.cr 12:15
0x2ab03968cf45: __libc_start_main at ??
0x771699: ??? at ??
0x0: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
make: *** [.build/all_spec] Error 1

```

**Comment by RX14** [comment] 2017-04-30 22:53
This is very very likely a dupe of https://github.com/crystal-lang/crystal/issues/4343, https://github.com/crystal-lang/crystal/issues/4142, and https://github.com/crystal-lang/crystal/issues/4341.

**Comment by mverzilli** [comment] 2017-05-03 13:01
Closing as duplicate of #4341. Let's try to keep the conversation there.

**Closed by mverzilli** 2017-05-03 13:01 UTC
