### ISSUE TITLE
Invalid memory access when adding additional C call

### ISSUE THREAD

**Issue by halfdan** [crystal-lang/crystal#8776] opened 2020-02-10 07:18 UTC
Apologies for the poor title. I don't know how else to describe this. The code below produces an invalid memory access but only if the last line is added (call to database_info). To compile you need libhs (brew install hyperscan) installed.

```crystal
@[Link(ldflags: "`command -v pkg-config > /dev/null && pkg-config --libs libhs 2> /dev/null|| printf %s '-lhs'`")]
lib LibHyperscan
    @[Extern]
    struct HsPlatformInfo
        # Information about the target platform which may be used to guide the optimisation process of the compile.
        tune : LibC::UInt
        # Relevant CPU features available on the target platform
        cpu_features : LibC::ULongLong
        # Reserved for future use.
        reserved1 : LibC::ULongLong
        # Reserved for future use.
        reserved2 : LibC::ULongLong
    end

    @[Extern]
    struct HsCompileError
        # A human-readable error message describing the error.
        message : LibC::Char*
        # The zero-based number of the expression that caused the error (if this can be determined). If the error is not specific to an expression, then this value will be less than zero.
        expression : LibC::Int
    end

    @[Extern]
    struct HsDatabase
        magic : UInt32
        version : UInt32
        length : UInt32
        platform : UInt64
        crc32 : UInt32
        reserved0 : UInt32
        foo : UInt32
        bytecode : UInt32
        padding : UInt32[16]
        bytes : LibC::Char*
    end
    alias HsErrorT = LibC::Int
    # The basic regular expression compiler.
    fun compile = hs_compile(expression : LibC::Char*, flags : LibC::UInt, mode : LibC::UInt, platform : HsPlatformInfo*, db : HsDatabase*, error : HsCompileError**) : HsErrorT
    # Utility function providing information about a database.
    fun database_info = hs_database_info(database : HsDatabase, info : LibC::Char**) : HsErrorT
    # Provides the size of the given database in bytes.
    fun database_size = hs_database_size(database : HsDatabase, database_size : LibC::SizeT*) : HsErrorT

    HS_SUCCESS = 0
    HS_MODE_BLOCK = 1
end

database = uninitialized LibHyperscan::HsDatabase
platform = LibHyperscan::HsPlatformInfo.new

x = "abc123"
expr = x.to_unsafe()
error = LibHyperscan.compile(expr, 0, LibHyperscan::HS_MODE_BLOCK, pointerof(platform), pointerof(database), out errorT)

if errorT
    puts String.new(errorT.value.message)
    exit 
end

if database
    LibHyperscan.database_size(database, out size)
    puts "Database size: #{size}"

    # Adding this line breaks the previous
    LibHyperscan.database_info(database, out info)
end
```

Output without breaking line: `Database size: 3`. Output with breaking line:

```
Database size: 0
Invalid memory access (signal 11) at address 0x0
[0x1046d65db] *CallStack::print_backtrace:Int32 +107
[0x1046b97d6] __crystal_sigfault_handler +198
[0x7fff6b94fb5d] _sigtramp +29
```

Somehow adding the call to database_info breaks the call to database_size.

**Comment by asterite** [comment] 2020-02-10 11:41
When it crashes like that at runtime it usually means the bindings are wrong or the C API is misused.

In this case it seems `hs_database_info` and `hs_database_size` take **a pointer** to the database, but you specified those as non-pointers. Fixing that still doesn't work for me, but at least I get an error when calling those functions.

I'm going to close this because it's not a bug in the compiler. You can post to https://forum.crystal-lang.org/ to discuss how to fix/improve the bindings.

**Closed by asterite** 2020-02-10 11:41 UTC
