### ISSUE TITLE
Formatter bug: expecting ), not `IDENT, end`

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7260] opened 2019-01-03 18:01 UTC
Trying to format
```cr
Type(typeof(begin
  var.is_a?(Something)
end))
```
results in:
```
Error: couldn't format './cr.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

expecting ), not `IDENT, end`, at :3:1 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```
Originally found in [`src/iterator.cr:750`](https://github.com/crystal-lang/crystal/blob/master/src/iterator.cr#L750).

**Comment by asterite** [comment] 2019-01-03 18:03
Duplicate of #7229

**Comment by Sija** [comment] 2019-01-03 18:04
Duplicate of #7176

**Closed by asterite** 2019-01-03 18:03 UTC
