### ISSUE TITLE
Range.size inconsistencies

### ISSUE THREAD

**Issue by willcosgrove** [crystal-lang/crystal#3744] opened 2016-12-21 05:36 UTC
I noticed an issue in a program when I had a range of `Range.new(0_u32, UInt32::MAX)` and I asked it for its size.  It gives back `0`.

I tried `Range.new(0, UInt32::MAX).size` and this actually caused my program to hang (indefinitely as far as I could stand to tell).

I'm not sure what the result of `size` should be... as far as the Type is concerned, but I do know that the current behavior probably isn't the right one.

The only thing I could find relating to this was #1895.

I'm running `Crystal 0.20.1 (2016-12-05)` on macOS 10.12.2.  And the problems existed in both a normal build, and a release build.

**Comment by asterite** [comment] 2016-12-21 10:27
The problem is that 0 is `Int32` and when counting up it will overflow and never reach `UInt32::MAX` so it will count forever. This will be solved once we do something about overflows. So I'll close this as a duplicate (or in favor of) #3103

**Closed by asterite** 2016-12-21 10:27 UTC
