### ISSUE TITLE
Interpreter hangs on Process.new("sleep", ["1"]).wait

### ISSUE THREAD

**Issue by philipp-classen** [crystal-lang/crystal#13417] opened 2023-05-01 01:22 UTC
```
Process.new("sleep", ["1"]).wait
```

Running it with `crystal run` works: as expected it terminates after one second. Yet in the interpreter the `wait` call hangs forever. It is also using 100 % CPU.

Crystal 1.9.0-dev [95e1270b6] (2023-04-29)
LLVM: 15.0.7
Default target: x86_64-pc-linux-gnu
OS: Arch Linux

`perf top` says:

```
  41.94%  crystal                                         [.] *Crystal::Repl::Interpreter#interpret<Crystal::ASTNode+, Crystal::Type+>:Crystal::Repl::Value                                                                                  ◆
   6.29%  crystal                                         [.] *Array(Crystal::Repl::Interpreter::CallFrame)@Indexable(T)#last:Crystal::Repl::Interpreter::CallFrame                                                                          ▒
   4.83%  crystal                                         [.] *Array(Crystal::Repl::Interpreter::CallFrame)@Array(T)#<<<Crystal::Repl::Interpreter::CallFrame>:Array(Crystal::Repl::Interpreter::CallFrame)                                  ▒
   2.96%  crystal                                         [.] *Crystal::Type+@Crystal::Type#implements?<Crystal::Type+>:Bool                                                                                                                 ▒
   2.08%  crystal                                         [.] *Array(Crystal::Repl::Interpreter::CallFrame)@Array(T)#pop:Crystal::Repl::Interpreter::CallFrame                                                                               ▒
   1.68%  crystal                                         [.] *Crystal::Type+@Crystal::Type#filter_by<Crystal::Type+>:(Crystal::Type+ | Nil)                                                                                                 ▒
   1.60%  crystal                                         [.] *Crystal::Type::common_descendent_base<Crystal::Type+, Crystal::Type+>:(Crystal::Type+ | Nil)                                                                                  ▒
   0.86%  crystal                                         [.] 0x0000000000c3c320                                                                                                                                                             ▒
   0.81%  libevent-2.1.so.7.0.1                           [.] event_base_loop                                                                                                                                                                ▒
   0.80%  crystal                                         [.] *Crystal::LLVMTyper#llvm_type<Crystal::Type+, Bool>:LLVM::Type                                                                                                                 ▒
```

**Comment by straight-shoota** [comment] 2023-05-01 15:54
Duplicate of #12241

**Closed by straight-shoota** 2023-05-01 15:54 UTC
Labels: kind:bug, topic:compiler:interpreter
