### ISSUE TITLE
`...=` methods don't work without an explicit receiver

### ISSUE THREAD

**Issue by LoadingBG** [crystal-lang/crystal#12491] opened 2022-09-17 17:32 UTC
```cr
def a=(value)
  puts "Got #{value}"
end
a = 0
```
This program outputs nothing. `a=0` is interpreted as assignment instead of the method call. `a=` cannot be invoked.

The same happens in a `with ... yield` block:
```cr
class A
  def field=(value)
    puts "Got #{value}"
  end
  
  def with_self
    with self yield
  end
end

A.new.with_self do
  field = "hi"
end
```
This also produces no output. `field=` would only work if there is an explicit receiver:
```cr
a = A.new
a.field = "hi"
```
This produces the expected `Got hi` output.

**Comment by Blacksmoke16** [comment] 2022-09-17 18:01
Duplicate of #8402

The second example can also be resolved via:
```cr
A.new.with_self do
  itself.field = "hi"
end
```

**Closed by Blacksmoke16** 2022-09-17 18:01 UTC
Labels: kind:bug, status:duplicate, topic:compiler:parser

**Comment by Blacksmoke16** [comment] 2022-09-17 18:03
Duplicate of #8402
