### ISSUE TITLE
Compiler bug when a macro uses run() with spaces in the path

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#5919] opened 2018-04-04 22:33 UTC
Try the following examples, lifted more or less straight from [the docs](https://crystal-lang.org/api/0.19.4/Crystal/Macros.html#run%28filename%2C%2Aargs%29%3AMacroId-instance-method):

`directory with spaces/print_gotten_string.cr`:
```crystal
macro get_version
    {{ run("./get_string").stringify }}
end

puts get_version
```

`directory with spaces/get_string.cr`:
```crystal
puts "Hi!"
```

Running `crystal run print_gotten_string.cr` errors out with the following message:
```
can't specify arguments in both, command and args without including "${@}" into your command
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

It looks like [`Process.prepare_argv` is getting the parts of the path as arguments](https://github.com/crystal-lang/crystal/blob/106d44dc8bbf3a0d4f486318e39543d4142fc1ca/src/process.cr#L320) instead of the entire path being passed in as the command.

**Comment by obskyr** [comment] 2018-04-05 15:12
Changed title to reflect the fact that it doesn't error out gracefully.

**Comment by asterite** [comment] 2018-04-05 20:37
Should have been fixed by https://github.com/crystal-lang/crystal/pull/5543 , but probably not released in some of the past releases because of GitFlow.

**Comment by straight-shoota** [comment] 2018-04-05 21:08
There has only been the release of 0.24.2 since the merge and that did only include some bugfixes but not #5543

But I can confirm this issue is fixed in master.

**Closed** 2018-04-05 21:26 UTC
Labels: kind:bug, topic:compiler

**Comment by obskyr** [comment] 2018-04-05 21:28
Terrific, thanks!
