### ISSUE TITLE
&. when block method has arguments

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#7549] opened 2019-03-14 21:37 UTC
```crystal
["a", "b"].join(",") &.upcase
# Syntax error in eval:1: unexpected token: .
```

However, this code works as expected:

```crystal
["a", "b"].join(",") { |s| s.upcase }
```

Hm......... :thinking: Maybe we need to **revisit** the `&` syntax? :wink: 

_Or, this is just a small bug which is easy to fix._

**Comment by Sija** [comment] 2019-03-14 21:55
Proper syntax is:

```cr
["a", "b"].join(",", &.upcase)
```

**Comment by vladfaust** [comment] 2019-03-14 22:02
TIL. Should be added to https://crystal-lang.org/reference/syntax_and_semantics/blocks_and_procs.html.

**Comment by straight-shoota** [comment] 2019-03-14 23:51
The short syntax is already explained on this page. What are you missing?

**Comment by asterite** [comment] 2019-03-14 23:53
I think the form with arguments and a block is missing.

**Comment by ysbaddaden** [comment] 2019-03-15 08:20
Closing. Not a bug.

**Closed by ysbaddaden** 2019-03-15 08:20 UTC
