### ISSUE TITLE
Playground: Chained assignments might fail

### ISSUE THREAD

**Issue by bcardiff** [crystal-lang/crystal#6236] opened 2018-06-21 16:02 UTC
From https://github.com/crystal-lang/crystal/issues/6210#issuecomment-398224432

```crystal
a = b = 2
puts b
```

is instrumented as

```crystal
a = _p.i(1) do
  b = 2
end
puts(_p.i(2) do
  b
end)
```

So `b` is scoped in the instrumentation of the first line.

A solution would be to instrument it as follow:

```crystal
a = b = _p.i(1) do
  2
end
puts(_p.i(2) do
  b
end)
```

**Comment by erdnaxeli** [comment] 2020-10-31 10:27
I just got the same bug today. Here is what the playground says about it:
```
Code

a = b = 2
puts a
puts b

Exception

error in line 7
Error: instantiating 'Crystal::Playground::Agent#i(Int32)'


error in line 7
Error: instantiating 'Crystal::Playground::Agent#i(Int32)'


error in line 8
Error: undefined local variable or method 'b' for top-level

Did you mean 'p'?
```

**Comment by HertzDevil** [comment] 2021-06-14 21:18
Duplicate of #3494.

**Closed** 2021-06-14 21:58 UTC
Labels: kind:bug, topic:tools:playground
