### ISSUE TITLE
Formatter bug

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4799] opened 2017-08-06 13:52 UTC
Hi @MakeNowJust, I found a formatter bug :sweat_smile: 

Crystal version `0.23.1`

This working code:

```crystal
Claves = {
  "arreglo": "",
  "uno": 1,
  "dos": 2,
  "tres": 3,
  "en": "",
}
```

https://carc.in/#/r/2hbj

Is formatted to failing code:

```crystal
Claves = {
  "arregl    o": "",
  "uno":     1,
  "dos": 2   ,
  "tres"     : 3,
  "en": "",
}
```

https://carc.in/#/r/2hbi

Thanks you on advance :+1:

**Comment by faustinoaq** [comment] 2017-08-06 13:59
Also happens with hashes :sweat_smile: 

```crystal
Claves = {
  "arreglo" => "",
  "uno" => 1,
  "dos" => 2,
  "tres" => 3,
  "en" => ""
}
```

Is formatted as:

```crystal
Claves = {
  "arre    glo" => "",
  "uno"     => 1,
  "dos"    => 2,
  "tre     s" => 3,
  "en" => "",
}
```

**Comment by MakeNowJust** [comment] 2017-08-06 14:00
Why Crystal version `0.21.3`?

**Comment by faustinoaq** [comment] 2017-08-06 14:01
Sorry, a typo :sweat_smile:

**Comment by MakeNowJust** [comment] 2017-08-06 14:06
Your report does not have reproducibility.

```console
$ crystal version
Crystal 0.23.1 (2017-07-13) LLVM 4.0.1
$ cat foo.cr
Claves = {
  "arreglo": "",
  "uno": 1,
  "dos": 2,
  "tres": 3,
  "en": "",
}
$ cat foo.cr | crystal tool format -
Claves = {
  "arreglo": "",
  "uno":     1,
  "dos":     2,
  "tres":    3,
  "en":      "",
}
```

I guess your example is the part of entire code, and real problem is caused in another place (it seems like line counting error.).

**Comment by faustinoaq** [comment] 2017-08-06 14:10
Yeah, you're right.

The entire code is :point_down: 

```crystal
Val = [] of Int32

{% for w in ["el", "del"] %}
  def {{w.id}}(f)
    f
  end
{% end %}

def muéstrame(m)
  puts m
end

def incremento(f)
  Val.map(&.+ Val.first)
  Val.shift
  Val.pop
  Val.reverse
end

Claves = {
  "arreglo": "",
  "uno": 1,
  "dos": 2,
  "tres": 3,
  "en": ""
}

{% for e, i in Claves.keys %}
  def {{e.id}}(val = nil)
    Val << val if val
    {{i}}
  end
{% end %}

muéstrame el incremento del arreglo uno dos tres en uno
```

is formatted as:

```crystal
Val = [] of Int32

{% for w in ["el", "del"] %}
  def {{w.id}}(f)
    f
  end
{% end %}

def muéstrame(m)
  puts m
end

def incremento(f)
  Val.map(&.+ Val.first)
  Val.shift
  Val.pop
  Val.reverse
end

Claves = {
  "arregl    o": "",
  "uno":     1,
  "dos": 2   ,
  "tres"     : 3,
  "en": "",
}

{% for e, i in Claves.keys %}
  def {{e.id}}(val = nil)
    Val << val if val
    {{i}}
  end
{% end %}

muéstrame el incremento del arreglo uno dos tres en uno
```

**Comment by MakeNowJust** [comment] 2017-08-06 14:22
This issue is same as #4656. And this is already fixed in #4659. Please see #4659 to need more information. (In this case, `f` inside `def {{w.id}}(f)` becomes the prefix of keyword `fun`.)

**Comment by faustinoaq** [comment] 2017-08-06 14:25
Thank you so much @MakeNowJust :smile:

**Comment by RX14** [comment] 2017-08-14 21:08
Duplicate of #4656.

**Closed by RX14** 2017-08-14 21:08 UTC
