### ISSUE TITLE
Crashed when modify class variable in catch-all initialization (default initialization) of instance variable

### ISSUE THREAD

**Issue by xqyww123** [crystal-lang/crystal#6613] opened 2018-08-27 12:35 UTC
Something like this triggers a runtime crash.
```
class A
  @@count : Int32 = 0
  @id : Int32 = (@@count += 1)

  def id
    @id
  end
end

p A.new.id
```
The program outputs `BUG: '@@count = @@count + 1' at eval:3:18 has no type (Exception)`. It also happens in https://play.crystal-lang.org/#/r/4tsa

The bug also happens for the code `@id : Int32 = (@@count = 1)` ([play crystal](https://play.crystal-lang.org/#/r/4tsi)), so I guess modification to the class variable in catch-all initialization triggers this bug.

**Comment by xqyww123** [comment] 2018-08-27 12:38
The bug doesn't happen after I warp `@@count += 1` in a class method.

**Comment by asterite** [comment] 2018-08-27 12:39
Duplicate of #6440

**Closed by asterite** 2018-08-27 12:39 UTC
