### ISSUE TITLE
Example for String#colorize(u8, u8, u8) doesn't work

### ISSUE THREAD

**Issue by kjarex** [crystal-lang/crystal#11874] opened 2022-03-05 12:28 UTC
When I use the copy/pasted example from the docs (in module Colorize > Overview) 
```
require "colorize"

"foo".colorize(0, 255, 255) # => "foo" in aqua
```

I receive 
```
 3 | "foo".colorize(0, 255, 255) # => "foo" in aqua
           ^-------
Error: wrong number of arguments for 'String#colorize' (given 3, expected 0..1)
```

I initially thought it might have been dropped intentionally in favour of `.colorize(Colorize::ColorRGB.new 0, 255, 255)`?), but it seems to be a bug somewhere else as it's still [here](https://github.com/crystal-lang/crystal/blob/master/src/colorize.cr#L183) (I have also tried it with parameters being uint8s, but it was the same).

If relevant: tested on/with OSX 10.14, Crystal 1.3.2 (2022-01-18), LLVM: 13.0.1, and only those lines mentioned (no other code)

**Comment by asterite** [comment] 2022-03-05 12:44
Duplicate of https://github.com/crystal-lang/crystal/issues/11828

It's already fixed in master and it will be released in 1.4

**Closed by asterite** 2022-03-05 12:44 UTC
Labels: kind:bug
