### ISSUE TITLE
Module validation failed: with sidekiq.cr get started

### ISSUE THREAD

**Issue by dotswing** [crystal-lang/crystal#4139] opened 2017-03-12 16:23 UTC
I was playing with sidekiq.cr and follow the basic get started when I reach the Web UI part I copied this code in web.cr

```
require 'sidekiq/web'

Kemal.config do |config|
end

Sidekiq::Client.default_context = Sidekiq::Client::Context.new

Kemal.run

```
And after run 'crystal run web.cr' I got error

```
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  %605 = call i8* @__crystal_malloc(i32 ptrtoint (i1** getelementptr (i1*, i1** null, i32 1) to i32))

0x10cb61c13: *raise<String>:NoReturn at ??
0x10db32c6b: *Crystal::CodeGenVisitor#finish:Nil at ??
0x10da5e53e: *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) at ??
0x10e3041b4: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x10e3ab219: *Crystal::Command#run_command<Bool>:Nil at ??
0x10cbc1229: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x10cb8b99d: main at ??
```

I was using crystal Crystal 0.21.1 (2017-03-07) LLVM 3.9.1
My os is OSX 10.11.5 El Capitan

**Comment by asterite** [comment] 2017-03-23 19:49
Seems to be a duplicate of #4166 (will be fixed in the next release)

**Closed by asterite** 2017-03-23 19:49 UTC
