### ISSUE TITLE
[RFC] Universal support for chained assignment

### ISSUE THREAD

**Issue by HertzDevil** [crystal-lang/crystal#10067] opened 2020-12-10 08:32 UTC
Setter methods (including `#[]=`) aren't currently required to return the same value that gets assigned, so the ability to chain multiple assignments is in general not supported. For example, `BitArray` breaks because the last statement of its `#[]=` refers to the internal buffer:

```crystal
  a = BitArray.new(6)
  a[0] = a[4] = true
#  ^
# Error: no overload matches 'BitArray#[]=' with types Int32, UInt32
#
# Overloads are:
#  - BitArray#[]=(index, value : Bool)
```

This leads to surprises, and I believe the language should avoid such surprises. Uses of `=` that don't support chained assignments should only appear in DSLs, and that is supposed to be taken care of by macros, not regular methods. Consider the following snippet:

```crystal
class Foo
  def []=(k, v)
    p [k, v]
    123
  end
end

a = Foo.new
a[0] = a[4] = true
a.[]=(0, a.[]=(4, true))
```

This snippet is both valid Crystal and Ruby code. In Crystal it prints

```
[4, true]
[0, 123]
[4, true]
[0, 123]
```

Whereas in Ruby it prints

```
[4, true]
[0, true]
[4, true]
[0, 123]
```

Thus it seems Ruby rewrites the operator syntax as follows:

```ruby
a[0] = a[4] = true
a[0] = (__tmp2 = true; a.[]=(4, __tmp2); __tmp2)
__tmp1 = (__tmp2 = true; a.[]=(4, __tmp2); __tmp2); a.[]=(0, __tmp1); __tmp1
```

We should follow suit, but we may also go one step further and rewrite the *definitions* of all setter methods instead; that is, the compiler automatically injects the value argument as the return value, equivalent to something like

```crystal
class Foo
  # the original setter body (whose return type and value are ignored,
  # including early returns)
  @[AlwaysInline]
  private def index_assign_impl(k, v)
    p [k, v]
    123
  end

  def []=(k, v)
    index_assign_impl(k, v)
    v
  end
end
```

Then we would always have the same return values whether the setters are invoked through the operator or call syntax.

**Comment by asterite** [comment] 2020-12-10 09:13
I wanted to do this a couple of times but failed for some reason. I think the easiest thing is to do it the first way, not the second way.

**Comment by straight-shoota** [comment] 2020-12-10 13:31
This is a duplicate of #7707, let's continue the discussion there.

**Closed** 2020-12-10 13:31 UTC
Labels: status:duplicate
