### ISSUE TITLE
Defaulting Instance Variable to X.to_json Causes Compiler Bug

### ISSUE THREAD

**Issue by kinxer** [crystal-lang/crystal#8343] opened 2019-10-17 19:00 UTC
Crystal 0.27.1-0.31.1

When using a call to `X.to_json` (where `X` is `JSON::Serializable`) to set a default instance variable, the compiler gives the following message (where ellipses are where noise has been removed):

```
BUG: trying to downcast (Slice(UInt8) | Nil) <- Slice(UInt8) (Exception)
  from Crystal::CodeGenVisitor#downcast_distinct<LLVM::Value, Crystal::Type+, Crystal::Type+>:NoReturn
  from Crystal::CodeGenVisitor#downcast<LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value
  from Crystal::CodeGenVisitor#visit<Crystal::Var+>:(LLVM::Value | Nil)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#codegen_cond<Crystal::ASTNode+>:LLVM::Value
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil
  from Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool
  ...
```
(stack trace provided by @Blacksmoke16; I personally only see lines of `from ???`)

Code reproducing this bug is below:
```
require "json"

class A
  include JSON::Serializable
  
  property name : String?
end

class B
  @a = A.from_json(%({"name": "Abner"}))
end

pp B.new
```
[Playground Link for 0.31.1](https://play.crystal-lang.org/#/r/7tvp)
[Playground Link for 0.27.1](https://play.crystal-lang.org/#/r/7tv2)
[Playground Link for 0.27.0](https://play.crystal-lang.org/#/r/7tv1)

The compiler should either handle this case (like it apparently did pre-0.27.1) or provide a more informative error message.

**Comment by asterite** [comment] 2019-10-17 19:30
Duplicate of #8163

**Closed by asterite** 2019-10-17 19:30 UTC
