### ISSUE TITLE
Custom generic bug?

### ISSUE THREAD

**Issue by rmosolgo** [crystal-lang/crystal#1910] opened 2015-11-26 15:28 UTC
I was trying to learn about some data structures: https://github.com/rmosolgo/immutable-crystal

But, running the specs gives this error: 

```
~/projects/immutable-crystal $ crystal spec
Error in ./spec/immutable/trie_spec.cr:17: instantiating 'Immutable::Trie(Int32, Int32)#put(Int32, Int32)'

    trie2 = trie2.put(5, 50).put(4, 40)
                  ^~~

in ./src/immutable/trie.cr:45: instantiating 'Immutable::Trie::Subtrie(K, V)#put(Int32, Int32, Int32)'

          subtrie.put(index, key, value)
                  ^~~

in ./src/immutable/trie.cr:97: no overload matches 'Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=' with types Int32, {Int32, Int32}
Overloads are:
 - Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=(index : Int, count : Int, value : ({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class}))
 - Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=(index : Int, count : Int, values : Array(T))
 - Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=(index : Int, value : ({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class}))
 - Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=(range : Range(Int, Int), value : ({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class}))
 - Array({Symbol, Int32} | {Int32, Immutable::Trie::Subtrie(Symbol, Int32):Class})#[]=(range : Range(Int, Int), values : Array(T))

          @entries[entry_index] = new_entry
                  ^
```

At compile time, it thinks that `{K, V}` is `{Symbol, Int32}`, but it should be `{Int32, Int32}`. 

You can see that the first test uses `{Symbol, Int32}`:  https://github.com/rmosolgo/immutable-crystal/blob/master/spec/immutable/trie_spec.cr#L5
But the second test uses `{Int32, Int32}`: https://github.com/rmosolgo/immutable-crystal/blob/master/spec/immutable/trie_spec.cr#L16
The error comes in the second test: https://github.com/rmosolgo/immutable-crystal/blob/master/spec/immutable/trie_spec.cr#L17

Have I made an error here? Should I do something else to make a generic type like this? 

Thanks!

**Comment by asterite** [comment] 2015-11-26 17:22
I'm not sure why the error message is wrong (I'll have to investigate), but `@entries` should be `        @entries = Array({K, V} | {Bitmap, self}).new(0)`

**Comment by rmosolgo** [comment] 2015-11-26 20:24
:moneybag: that'll do it, thanks!

**Comment by rmosolgo** [comment] 2015-11-26 20:24
I knew to use `self` for the class inside the class level, eg `alias Child = {Bitmap, self}` but I didn't know to _also_ use `self` inside an instance method!

**Comment by asterite** [comment] 2015-11-26 20:29
I'll reopen because the error message is far from clear :-)

**Comment by straight-shoota** [comment] 2020-12-01 21:10
The originating source code is no longer available, so there's no way to reproduce the error. It seems nobody has been bothered in the last five years, so we can close this.

**Closed by straight-shoota** 2020-12-01 21:10 UTC
Labels: kind:bug, topic:compiler
