### ISSUE TITLE
Bug: trying to upcast Other <- Child

### ISSUE THREAD

**Issue by will** [crystal-lang/crystal#2527] opened 2016-04-27 20:28 UTC
``` crystal
struct Other
end

struct Child < Other
end

class Foo
  property proc : Other ->

  def initialize
    @proc = Proc(Other, Void).new { }
    # or @proc = ->(f : Other) {} as Other ->
    go
  end

  def go
    @proc.call(Child.new)
  end
end

Foo.new
```

Crystal 0.15.0 (Fri Apr  1 17:57:09 UTC 2016)
```
Bug: trying to upcast Other <- Child
[4330870267] *raise<String>:NoReturn +155
[4334986607] *Crystal::CodeGenVisitor#upcast<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+>:LLVM::Value +12431
[4335047424] *Crystal::CodeGenVisitor#codegen_primitive<Crystal::CodeGenVisitor, Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:LLVM::Value +1008
[4335021614] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +910
[4334909612] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1452
[4334969124] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +3732
[4334990843] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +2891
[4335024199] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +3495
[4334909612] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1452
[4334910950] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2790
[4334969124] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +3732
[4334990843] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +2891
[4335024199] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +3495
[4334909612] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1452
[4334910950] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2790
[4334969124] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +3732
[4334990843] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +2891
[4335024199] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +3495
[4334909612] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1452
[4334709069] *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:Nil +2861
[4333456579] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +9555
[4338246353] *Crystal::Command#run_command<Crystal::Command>:Nil +145
[4337887094] *Crystal::Command#run<Crystal::Command>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +12278
[4330868522] __crystal_main +24378
[4337837710] main +46

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

head: 60804e0
```
Bug: trying to upcast Other <- Child
[4557664322] *CallStack::unwind:Array(Pointer(Void)) +82
[4557664225] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4557664184] *CallStack::new:CallStack +40
[4557668313] *Exception#initialize<Exception, String, Nil>:CallStack +41
[4557668244] *Exception::new<String>:Exception +100
[4557496841] *raise<String>:NoReturn +9
[4568389825] *Crystal::CodeGenVisitor#upcast_distinct<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+>:NoReturn +97
[4568387885] *Crystal::CodeGenVisitor#upcast<Crystal::CodeGenVisitor, LLVM::Value, Crystal::Type+, Crystal::Type+>:LLVM::Value +2989
[4568501919] *Crystal::CodeGenVisitor#codegen_primitive_fun_call<Crystal::CodeGenVisitor, Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:LLVM::Value +415
[4568462150] *Crystal::CodeGenVisitor#codegen_primitive<Crystal::CodeGenVisitor, Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:LLVM::Value +2726
[4568457941] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +181
[4568427021] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +525
[4560377551] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4863
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568375049] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1977
[4568393011] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +99
[4568392192] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +336
[4568458029] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +269
[4568427021] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +525
[4560377551] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4863
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568393388] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +236
[4560374130] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1442
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568375049] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1977
[4568393011] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +99
[4568392192] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +336
[4568458029] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +269
[4568427021] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +525
[4560377551] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4863
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568393388] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +236
[4560374130] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1442
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568375049] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1977
[4568393011] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +99
[4568392192] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +336
[4568458029] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +269
[4568427021] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +525
[4560377551] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4863
[4568358744] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +24
[4568393388] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +236
[4560703365] *Crystal::Expressions@Crystal::ASTNode#accept<Crystal::Expressions, Crystal::CodeGenVisitor>:Nil +37
[4558307872] *Crystal::Program#codegen<Crystal::Program, Crystal::Expressions, (Array(String) | Bool | String | Nil), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +112
[4558307741] *Crystal::Program#codegen:debug:single_module:expose_crystal_main<Crystal::Program, Crystal::Expressions, Bool, (Array(String) | Bool | String | Nil), Bool>:Hash(String, LLVM::Module) +109
[4564703158] *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:Nil +1446
[4564698027] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +155
[4564711976] *Crystal::Command::CompilerConfig#compile<Crystal::Command::CompilerConfig, String>:Crystal::Compiler::Result +56
[4558009552] *Crystal::Command#run_command<Crystal::Command, Bool>:Nil +368
[4557997590] *Crystal::Command#run<Crystal::Command>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +1798
[4557995484] *Crystal::Command::run<Array(String)>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +44
[4557995357] *Crystal::Command::run:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +45
[4557495756] __crystal_main +50732
[4557518879] main +47

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by will** [comment] 2016-04-27 21:02
Updated the code sample to show ` @proc = Proc(Other, Void).new { }` also causes it, not just with `as`

**Comment by asterite** [comment] 2016-04-27 22:36
@will check #2382 (I just wrote it). If the real code behind the snippet involves a Frame from native_pg_driver, you could make `Frame` be a module and include it in every frame time (I just tried it and it works)

**Comment by asterite** [comment] 2016-04-27 22:37
I'll close this as a duplicate of #2529 (we basically need to solve that issue and then this will be solved too)

**Closed by asterite** 2016-04-27 22:37 UTC

**Comment by will** [comment] 2016-04-27 22:59
I solved my issue a different way, but I'll probably do that module thing also, thanks.

**Comment by asterite** [comment] 2016-04-27 23:12
Curious: how did you solve it?

**Comment by will** [comment] 2016-04-27 23:16
This was for the callback when you get async [notices and errors](http://www.postgresql.org/docs/current/static/plpgsql-errors-and-messages.html), and just getting it working I was passing the frame. I wasn't going to actually do that for real, rather something that wraps the data a bit nicer, so I went ahead with that, and those two frames cast themselves to a 3rd unrelated struct, which gets yielded.
