### ISSUE TITLE
Can't use with ... yield in initializer

### ISSUE THREAD

**Issue by Drenmi** [crystal-lang/crystal#9143] opened 2020-04-20 15:23 UTC
### Background

I attempted to construct an API like the following:

```crystal
Foo.new(42) do
  bar do |baz|
    # Configure some stuff here.
  end
end
```

To accomplish that I did the following:

```crystal
class Foo
  def initialize(qux)
    @config = Config.new # An object with a block capture and a getter.

    with @config yield
  end
end
```

### Expected behaviour

Expected `@config.bar` to capture the block.

### Actual behaviour

However, the compiler won't have it, and fails with the following:

```crystal
foo $ crystal foo.cr --error-trace
 
In foo.cr:3:8

 3 | Foo.new(3000) do
         ^--
Error: instantiating 'Foo.class#new(Int32)'


In foo.cr:3:8

 3 | Foo.new(3000) do
         ^--
Error: instantiating 'Foo.class#new(Int32)'


In foo.cr:4:3

 4 | bar do |baz|
     ^--
Error: undefined local variable or method 'bar' for top-level
```

### Things to note

1. It also does not work when yielding literals, e.g. `with "foo" yield`.
2. It works fine if I use this pattern in any other method than `#initialize`.
3. I am able to yield explicitly from `#initialize`, e.g. `yield(@config)`.

### Crystal version

```
Crystal 0.34.0 (2020-04-07)

LLVM: 10.0.0
Default target: x86_64-apple-macosx
```

**Comment by asterite** [comment] 2020-04-20 15:28
Duplicate of #4436

**Closed by asterite** 2020-04-20 15:28 UTC

**Comment by Drenmi** [comment] 2020-04-21 00:54
Thank you, @asterite! I tried searching, but my keyword-fu was not strong enough.
