### ISSUE TITLE
Crystal 1.8 : Enumerable(Range) error

### ISSUE THREAD

**Issue by hutou** [crystal-lang/crystal#13340] opened 2023-04-18 12:24 UTC
The following code compiles
```crystal
class Test(T)
  def initialize(@sources : Enumerable(T))
    @count = @sources.size
  end
end
p! Test.new(1..3)
``` 
Running the binary gives the following error message:
> Test.new(1..3) # => Invalid memory access (signal 11) at address 0x0
> [0x56474885c666] *Exception::CallStack::print_backtrace:Nil +118 in ./range
> [0x56474884bdd6] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +310 in ./range
> [0x7fac7266cf50] ?? +140378630442832 in /usr/lib/libc.so.6
> [0x564748872b63] *Slice(T)::new:read_only<Pointer(UInt8), Int32, Bool>:Slice(UInt8) +35 in ./range
> [0x5647488685c5] *String#to_slice:Slice(UInt8) +37 in ./range
> [0x564748871538] *String#to_s<IO::FileDescriptor>:Nil +24 in ./range
> [0x5647488c33fb] *IO::FileDescriptor +27 in ./range
> Erreur de segmentation (core dumped)

This refers to #13121

**Comment by beta-ziliani** [comment] 2023-04-18 12:28
Duplicate of #10518

**Closed by beta-ziliani** 2023-04-18 12:28 UTC
Labels: kind:bug, topic:stdlib:collection

**Comment by straight-shoota** [comment] 2023-04-18 17:48
For the record: This has nothing to do with https://github.com/crystal-lang/crystal/issues/13121. The code already fails with 1.7.3.
