### ISSUE TITLE
Weird Compiler Result In Terminal

### ISSUE THREAD

**Issue by nedpals** [crystal-lang/crystal#4427] opened 2017-05-18 13:46 UTC
Crystal version: `Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0`

So I had this little project which it parses PRX files with a custom parser I copied and modified from the INI library because I want to make the nestable hashes to get to work. 
I used a Recursive Alias with a hash that contains a string or a hash for inferring the type but when I tried to compile it, its outputs an infinite loop-ish result like this:
```shell
[0xa9e71f] ???
[0xa9e7fb] ???
[0xa439ba] ???
[0xa438ee] ???
[0xa4cfe7] ???
[0xa48509] ???
[0xa9e71f] ???
[0xa9e7fb] ???
[0xa439ba] ???
[0xa438ee] ???
```
My `prx_parser.cr` file
```ruby
require "./prx_parser/prx"
require "json"

module PrxParser
  file = ENV["HOME"] + "/Downloads/GAH Fastest PosternConfig v2.prx"
  output = PRX.parse_file(file)
  PRX.move_hash(output, "Host", "Rule")
  PRX.move_hash(output, "Rule", "PROXY GROUP")
  json_output = output.reject!("Host").to_pretty_json
  json_file = File.new("output.json", mode: "w+")
  json_file.puts(json_output)
  json_file.close
end
```

My `prx.cr` file
```ruby
class PRX
  # Parses INI-style configuration from the given string.
  #
  # ```
  # PRX.parse("[foo]\na = 1") # => {"foo" => {"a" => "1"}}
  # ```
  alias RecursiveHashType = String | Hash(String, RecursiveHashType | String)

  def self.parse_file(file : String)
    output = File.read_lines(file).join("\n")
    self.parse(output)
  end

  def self.parse(str) : PRX::RecursiveHashType
    prx = {} of String => PRX::RecursiveHashType

    section = ""
    str.lines.each do |line|
      if line =~ /\s*(.*[^\s])\s*=\s*(.*[^\s])/
        prx[section] ||= {} of String => PRX::RecursiveHashType if section == ""
        prx[section][$1] = $2
      elsif line =~ /\[(.*)\]/
        section = $1
        prx[section] = {} of String => PRX::RecursiveHashType
      end
    end
    prx
  end

  def self.move_hash(hash, del_key, new_key) : Hash
    hash[new_key][del_key] = hash.delete(del_key)
  end
end
```
Also, I am also confused if i will ask it here or in SO because I do not how to make this thing work in Crystal and also it is both a question and bug report lol.
Any suggestions how can I achieve of hash with nestable hashes inside to avoid that weird loop thing?

**Comment by bcardiff** [comment] 2017-05-18 15:17
The alias could be `alias RecursiveHashType = String | Hash(String, RecursiveHashType)` that will pass the compiler exception you are getting and point other type errors, but without crashing the compiler like:

```crystal
prx[section] ||= {} of String => PRX::RecursiveHashType if section == ""
prx[section][$1] = $2
```

there is no guarantee `prx[section]` is a Hash. it could be a `String` in the second line.

Something equivalent to `prx[section] ||= ({} of String => PRX::RecursiveHashType).tap { |h| h[$1] = $2 }` could work.

But there are more type issues.

Even so, the compiler should not crash that badly. I reduced to this, using different `h[""]` lines it crash in a different way.

```crystal
alias RecursiveHashType = String | Hash(String, RecursiveHashType | String)

h = {} of String => RecursiveHashType
h[""] = ({} of String => RecursiveHashType) # crash with log
h[""] = Hash(String, RecursiveHashType | String).new # crash with log
h[""] = ({} of String => (RecursiveHashType | String)) # crash without log
```

```
$ crystal build foo.cr 
Invalid memory access (signal 11) at address 0x7fff5b7e1fc0
[0x103c5c262] __crystal_sigfault_handler +66
[0x7fffdaceebba] _sigtramp +26
[0x104173f95] *Crystal::Type+@Crystal::Type#restrict<Crystal::Type+, Crystal::MatchContext>:(Crystal::Type+ | Nil) +21
[0x10412539d] *Crystal::GenericInstanceType+@Crystal::GenericInstanceType#restrict_type_var<Crystal::ASTNode+, Crystal::ASTNode+, Crystal::MatchContext>:(Bool | Crystal::NamedTupleInstanceType | Crystal::NumberLiteral | Nil) +2077
[0x104120209] *Crystal::GenericInstanceType+@Crystal::GenericInstanceType#restrict<Crystal::GenericInstanceType+, Crystal::MatchContext>:(Crystal::GenericInstanceType+ | Nil) +169
[0x104173c0f] *Crystal::Type+@Crystal::Type#restrict<Crystal::UnionType+, Crystal::MatchContext>:(Crystal::Type+ | Nil) +447
```

**Comment by asterite** [comment] 2017-05-20 16:01
Duplicate of https://github.com/crystal-lang/crystal/issues/3804

Not exactly *exactly* the same, but fixing one should fix the other.

**Closed by asterite** 2017-05-20 16:01 UTC
