### ISSUE TITLE
Endless method definition

### ISSUE THREAD

**Issue by VinnyVicious** [crystal-lang/crystal#11165] opened 2021-09-03 15:53 UTC
Crystal, like Ruby, has too many ends. I am paranoid that end ends Crystal. Let's make Crystal endless. 

```crystal
def hello(name):
  puts("Hello, #{ name }")

class Object
  def has_instance_var?(name): Bool
    {{ @type.instance_vars.map &.name.stringify }}.includes? name
```

Inspired by the following: https://bugs.ruby-lang.org/issues/16746

**Comment by Blacksmoke16** [comment] 2021-09-03 16:02
Duplicate of https://github.com/crystal-lang/crystal/issues/9080

**Closed** 2021-09-03 17:40 UTC
Labels: status:discussion
