### ISSUE TITLE
SCTP in standard library

### ISSUE THREAD

**Issue by CodeSteak** [crystal-lang/crystal#2997] opened 2016-07-14 18:59 UTC
Support for SCTP would be nice in a modern and new standard library. 
SCTP is really powerful and combines the best of UDP and TCP.

**Comment by jhass** [comment] 2016-07-14 19:10
I don't think it's beneficial to initially develop this in the standard library, it can perfectly fine live as a shard. Once there's an implementation that proves stable, regularly used and cross platform, we can talk about moving it to the standard library.

**Comment by ysbaddaden** [comment] 2016-07-18 21:30
[SCTP](https://en.wikipedia.org/wiki/Stream_Control_Transmission_Protocol) is an IP transport protocol, at the same level that TCP or UDP. We're not very likely to implement the protocol ourselves, but use the underlying kernel/os implementation (that reuses `socket`, `bind`, `connect`, `sendto`, `recvfrom`, etc). The problem is that the protocol is quite "new" (compared to TCP/UDP), it's not part of POSIX, so few kernels actually support it (eg: FreeBSD and Linux) and Linux apps still depend on libsctp.

Neither OSX nor Windows support SCTP, so it won't be easy to integrate, especially in the stdlib.

**Comment by CodeSteak** [comment] 2016-07-19 14:58
I think I will implement it.  The "one-to-one" mode behaves like TCP, expect you can have multiple streams and is therefore easy to do. The "one-to-many" mode is more like UDP. So I hope copy-pasting  will get me through most of the way :grin: .
I have already opened a repo https://github.com/CodeSteak/sctp-crystal

**Closed** 2016-09-27 18:55 UTC
Labels: draft, RFC, standard library
