### ISSUE TITLE
Math error in language

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#4212] opened 2017-03-29 22:30 UTC
I found a math error.

It's reproducible if you run this code in  https://play.crystal-lang.org/#/cr

This error exists from 0.16 -- 0.20..0 (as verified in play-crystal), and 0.21.1 on my system.

All other prime values for b (except 3) from {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41} produce the correct results, either 46446 or 1.

The equivalent code produces correct answers in Ruby.

```
require "big"

      def powmod(b, x, m)
        r = 1.to_big_i
        while x > 0
          r = (r * b) % m if x.odd?
          b = (b * b) % m
          x >>= 1
        end
        r
      end

 {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41}.each {|b|
    puts powmod(b, 23223, 46447) # outputs 40414 for b=3, should be 46446, where 46447 is prime
  }

Output:
1
40414        # incorrect for b = 3, should be 46446
46446
46446
46446
46446
46446
46446
1
46446
46446
1
46446
```

**Comment by asterite** [comment] 2017-03-29 22:35
It seems an overflow happens with `b`. If you use `Int64` or `BigInt` for everything it works well

**Comment by jzakiya** [comment] 2017-03-29 22:47
OK, thanks.  This works now, but it sure ain't intuitive I needed to do that for such small values.

Could that be a sign of something wrong with %, since all the other values for b give correct results?

```
require "big"

      def powmod(b, x, m)
        r = 1.to_big_i
        while x > 0
          r = (r * b) % m if x.odd?
          b = (b * b).to_big_i % m
          x >>= 1
        end
        r
      end

 {2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41}.each {|b|
    puts powmod(b, 23223, 46447) 
  }

Output:
1
46446
46446
46446
46446
46446
46446
46446
1
46446
46446
1
46446
```

**Comment by jzakiya** [comment] 2017-03-30 01:15
OK, an overflow/truncation happens when (b * b) becomes > 2**31, when b=46436.

```
require "big"

      def powmod(b, x, m)
        r = 1.to_big_i
        while x > 0
          r = (r * b) % m if x.odd?
          b = (b * b) % m 
          #b = (b * b).to_big_i % m
          puts "r = #{r}, b = #{b}, x = #{x.to_s(2)}"
          x >>= 1
        end
        r
      end
  puts powmod(3, 23223, 46447)
```
Internal output from powmod for incorrect and correct  cases.

```
[jzakiya@localhost Crystal Projects]$ crystal powmodtest.cr

Incorrect output when using b = (b * b) % m

r = 3, b = 9, x = 101101010110111
r = 27, b = 81, x = 10110101011011
r = 2187, b = 6561, x = 1011010101101
r = 2187, b = 36799, x = 101101010110
r = 33209, b = 4116, x = 10110101011
r = 41170, b = 34748, x = 1011010101
r = 41170, b = 33739, x = 101101010
r = 37095, b = 43492, x = 10110101
r = 37095, b = 46436, x = 1011010
r = 9978, b = 33362, x = 101101             # should b = 121
r = 9978, b = 13583, x = 10110
r = 45275, b = 10405, x = 1011
r = 20901, b = 42515, x = 101
r = 20901, b = 40220, x = 10
r = 40414, b = 38731, x = 1
40414

[jzakiya@localhost Crystal Projects]$ crystal powmodtest.cr

Correct output when using b = (b * b).to_big_i % m

r = 3, b = 9, x = 101101010110111
r = 27, b = 81, x = 10110101011011
r = 2187, b = 6561, x = 1011010101101
r = 2187, b = 36799, x = 101101010110
r = 33209, b = 4116, x = 10110101011
r = 41170, b = 34748, x = 1011010101
r = 41170, b = 33739, x = 101101010
r = 37095, b = 43492, x = 10110101
r = 37095, b = 46436, x = 1011010
r = 9978, b = 121, x = 101101
r = 9978, b = 14641, x = 10110
r = 12083, b = 5976, x = 1011
r = 29370, b = 41280, x = 101
r = 29370, b = 37311, x = 10
r = 46446, b = 1237, x = 1
46446
```

So what's happens is when b = 46436 the next (b * b) should be 2147951716, which is > 2**31, so it gets truncated as a 31-bit number, which then gets operated on by % 46447.

**Comment by ozra** [comment] 2017-03-30 01:39
I'll just take the opportunity to vote for Int64 as "standard int" ;-)

**Comment by jzakiya** [comment] 2017-03-30 05:43
I would also vote for that, and also for including in big_int library optimized versions from Ruby's BigDecimal library methods, so you can do these standard operations, which take care of intermediary results.

So you can then do

```
b = b.mod_exp(2, m)

or

b = b.to_big_i.mod_exp(2, m)
```
instead of 

```
b = (b * b) % m
```

**Comment by asterite** [comment] 2017-03-30 19:21
I'll close this as a duplicate of #3103 . Overflowing will come in the future, we just don't know yet in what form.

**Closed by asterite** 2017-03-30 19:21 UTC
