### ISSUE TITLE
Formatter removes line-break preceded by a backslash

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4533] opened 2017-06-08 22:14 UTC
The formatter tool removes the line-break from this code:

```crystal
puts \
  "foo"
```
Becomes:
```crystal
puts "foo"
```

While it might not be to disturbing in this case, imagine a longer expression instead of `puts`. The backslash codifies the line-break is there on purpose to keep the code better readable, thus it should not be removed by the formatter.

If there is a string in the first line the backslash plus newline is preserved:
```crystal
puts "foo" \
  "bar"
```

**Comment by bew** [comment] 2017-06-08 22:28
Duplicate of #3383

**Closed** 2017-06-08 23:57 UTC
Labels: status:duplicate
