### ISSUE TITLE
Unhelpful error message when `pkg-config` is missing

### ISSUE THREAD

**Issue by notramo** [crystal-lang/crystal#13153] opened 2023-03-04 23:12 UTC
Running `shards install` in a Lucky project gives the following error on Void Linux:
```
Error target lucky.watch failed to compile:
/bin/ld: _main.o: in function `__crystal_main':
/home/build/crystal/share/crystal/src/openssl/lib_ssl.cr:283: undefined reference to `SSL_library_init'
/bin/ld: /home/build/crystal/share/crystal/src/openssl/lib_ssl.cr:283: undefined reference to `SSL_load_error_strings'
/bin/ld: /home/build/crystal/share/crystal/src/openssl/lib_ssl.cr:283: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/bin/ld: /home/build/crystal/share/crystal/src/openssl/lib_ssl.cr:283: undefined reference to `ERR_load_crypto_strings'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /home/build/project/lib/lucky/bin/lucky.watch  -rdynamic -L/home/build/crystal/bin/../lib/crystal -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -lyaml -lpcre -lgc -levent`
```

Void Linux musl
Crystal 1.7.2, from official `.tar.gz`
OpenSSL 1.1.1 development libraries are installed

**Comment by Blacksmoke16** [comment] 2023-03-04 23:22
Do you have `pkg-config` installed? I'd try installing that and see if it works. If so, this is a duplicate of #11069.

**Comment by notramo** [comment] 2023-03-05 00:30
Yes, it works when `pkg-config` is installed.

However, the error message is unhelpful, as the user might think a shared library is missing.

Closing this in favor of #11069

**Closed** 2023-03-05 00:32 UTC
Labels: kind:bug, status:duplicate

**Comment by Blacksmoke16** [comment] 2023-03-05 00:35
Duplicate of #11069
