### ISSUE TITLE
BUG: called create_llvm_type for T (Exception)

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#8551] opened 2019-12-03 21:18 UTC
Minimal code to reproduce:
```crystal
abstract class Base(T)
  @array = [] of T
end

class Foo(T) < Base(T)
end

Foo(Bool).new
```

Moving `@array` to `Foo` removes the compiler error, but makes the abstract class useless.  In real code adding a `@bool` to a subclass triggered this bug and was order dependant.  Adding the `@bool` above other variables didn't trigger the bug.  Below did.

`Crystal 0.32.0-dev [4ad82dc54] (2019-11-11)`

**Comment by lbarasti** [comment] 2020-05-10 17:22
I stumbled upon the following
```crystal
class A(T)
  @identity : Proc(T, T) = ->(v : T) { v }
  def initialize(v : T)
  end
end

class B(T) < A(T)
end

c = A.new(0)
```
which explodes with
```
BUG: called create_llvm_type for T (Exception)
  from ???
  ...
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
I'm on `Crystal v0.34.0`

**Comment by Blacksmoke16** [comment] 2020-05-10 17:24
Ah, missed this issue.  Another way to reproduce: https://github.com/crystal-lang/crystal/issues/8968.

**Comment by BlobCodes** [comment] 2021-05-01 19:51
I cannot reproduce any of the two pieces of code.
Can this be closed?

**Comment by straight-shoota** [comment] 2021-05-01 21:29
The OP examples reproduces on 1.0: https://carc.in/#/r/b1nh

**Comment by HertzDevil** [comment] 2021-05-20 13:13
Duplicate of #4753.

**Closed** 2021-05-22 10:22 UTC
Labels: kind:bug, topic:compiler
