### ISSUE TITLE
macro #subclasses duplicates with generic class

### ISSUE THREAD

**Issue by Blacksmoke16** [crystal-lang/crystal#8093] opened 2019-08-17 19:31 UTC
Came across a really strange issue: https://play.crystal-lang.org/#/r/7f4x

```cr
annotation Assert::LessThan; end

abstract class Assertion
end

class LessThanAssertion(P) < Assertion
end

module CrSerializer
  def validate : Nil
    {% begin %}
      {% assertions = [] of Assertion %}
      {% for ivar in @type.instance_vars %}
        {% for assertion in Assertion.subclasses %}
          {% if (ann = ivar.annotation(Assert::LessThan)) %}
            "{{@type}} - {{ivar.name}} - {{ivar.type}} - {{assertion}} - {{ann}}"
            {% assertions << %(#{assertion.name[0...-3]}(#{ivar.type}).new).id %}
          {% end %}
        {% end %}
      {% end %}
      # Initializing the validator for `{{@type}}`.
      {{assertions}} of Assertion
      {{debug}}
    {% end %}
  end
end

class LessThanIntegerTest
  include CrSerializer

  @[Assert::LessThan(value: 6_i8)]
  property int8 : Int8? = 0_i8
end

class LessThanFloatTest
  include CrSerializer

  @[Assert::LessThan(value: 0.0001_f64)]
  property float64 : Float64? = 0.0
end

LessThanFloatTest.new.validate
LessThanIntegerTest.new.validate
```

The main things to note is the output.  Notice it prints twice for the `int8` ivar, with the only difference being the assertion class has a generic of `(P)` instead of the actual `(Float64 | Nil)`.

It seems removing one of the test classes, or the generic fixes the issue.

**Comment by RX14** [comment] 2019-09-03 18:03
Reduced: https://play.crystal-lang.org/#/r/7h6k

I think this is just how `.subclasses` works with generics, but @asterite can probably say more.

**Comment by asterite** [comment] 2019-09-03 18:07
The thing is that `LessThanAssertion(P)` is used as a subclass of `Assertion` internally by the compiler, which is called an uninstantiated generic type. Then there are the instantiated types. I think the compiler could ignore the uninstantiated types here.

But beware that subclasses like this change while the compiler is typing things. So if you call `subclasses` in some point of the program but then you do `LessThanAssertion(Foo)` then that wouldn't  be included in the `subclasses` method because it happened in the past.

So, overall, I think we should remove all these type refleciton nonsense.

**Comment by asterite** [comment] 2019-09-03 18:29
Alternatively we should make it work the other way around: only show uninstantiated types, because that's the only consistent thing to do.

**Comment by Blacksmoke16** [comment] 2021-07-15 03:27
Another way to reproduce: https://play.crystal-lang.org/#/r/bjrx

```cr
abstract struct Parent
end

abstract struct Child(T) < Parent
end

struct GrandDaughter < Child(String)
end

struct GrandSon < Child(Int32)
end

{{pp Parent.all_subclasses.reject &.abstract?}} # => [GrandDaughter, GrandSon, GrandDaughter, GrandSon]
 ```

**Comment by HertzDevil** [comment] 2021-07-24 10:16
Duplicate of #4035.

**Closed** 2021-07-24 10:54 UTC
Labels: kind:bug, status:duplicate, topic:compiler:semantic
