### ISSUE TITLE
.includes? misbehaves with non-ascii

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#9712] opened 2020-08-30 14:04 UTC
Code:
```crystal
require "random"

"#{String.new(Random.new.random_bytes)}PNG#{String.new(Random.new.random_bytes)}".includes?("PNG")
```
I would expect the above to always be true, but in most runs this comes back as false.

P.S
Same code with `.match(/PNG/)` works each time.

**Comment by jhass** [comment] 2020-08-30 14:07
One more reason why we should've kept `String` UTF-8 only...

**Comment by bararchy** [comment] 2020-08-30 14:20
:cry:

**Comment by asterite** [comment] 2020-08-30 14:37
Duplicate of https://github.com/crystal-lang/crystal/issues/8785

**Closed by asterite** 2020-08-30 14:37 UTC
