### ISSUE TITLE
Found a compiler bug

### ISSUE THREAD

**Issue by G4BB3R** [crystal-lang/crystal#4868] opened 2017-08-21 15:18 UTC
I was doing a production app using kemal + mysql last week. Today I created a digital ocean droplet with ubuntu 16 and then tried to compile there to preview my app in production.
Then this error occurred:

"fork: Cannot allocate memory
0x5c0015: ??? at ??
0xb50605: ??? at ??
0xd5f940: ??? at ??
0xd6862a: ??? at ??
0xcdacd3: ??? at ??
0xb9be25: ??? at ??
0xb73a09: ??? at ??
0xb70a3e: ??? at ??
0xac0f83: ??? at ??
0xa15295: ??? at ??
0xa13b97: ??? at ??
0xa137dc: ??? at ??
0xa130a8: ??? at ??
0x96c53c: ??? at ??
0xa0fb0a: ??? at ??
0xa0d257: ??? at ??
0x9699ac: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0xf7b343: ??? at ??
0xf7b42f: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xde3015: ??? at ??
0x969863: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0xf7b343: ??? at ??
0xf7b42f: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0xe49b8c: ??? at ??
0x96a7fa: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0xf7b343: ??? at ??
0xf7b42f: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xe49b8c: ??? at ??
0x96a7fa: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0xf7b343: ??? at ??
0xf7b42f: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0xf11a5d: ??? at ??
0x96c562: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0xf7b343: ??? at ??
0xf7b42f: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xe49b8c: ??? at ??
0x96a7fa: ??? at ??
0x96bb46: ??? at ??
0xe04b75: ??? at ??
0x969be4: ??? at ??
0xe49b8c: ??? at ??
0x96a7fa: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xff499b: ??? at ??
0x1010da5: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x9698f0: ??? at ??
0xa0d355: ??? at ??
0x9699ac: ??? at ??
0xa0fb0a: ??? at ??
0xa0d257: ??? at ??
0x9699ac: ??? at ??
0xe04b75: ??? at ??
0x969be4: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0xdf7da2: ??? at ??
0x96a1ea: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0x101268e: ??? at ??
0x100ca05: ??? at ??
0x61734d: ??? at ??
0xa0ee1d: ??? at ??
0x9699ac: ??? at ??
0x96bb46: ??? at ??
0xc9e329: ??? at ??
0xbc232d: ??? at ??
0x102b0b3: ??? at ??
0x60b056: ??? at ??
0x5e1dac: main at ??
0x7f07ea5b6830: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues"

**Comment by kazzkiq** [comment] 2017-08-21 15:24
Its probably due to the fact your VM do not have enough memory to compile your project.

You can create a new VM with more memory, compile the code, then copy the binary to your target VM.

I had a similar issue before: https://github.com/crystal-lang/crystal/issues/4343

**Comment by sdogruyol** [comment] 2017-08-21 15:31
@G4BB3R please use swap memory for a workaround

**Comment by asterite** [comment] 2017-08-21 16:00
See also: #4864

**Comment by ShalokShalom** [comment] 2017-08-28 06:30
Can this be closed?

**Comment by ysbaddaden** [comment] 2017-08-28 12:59
Yes, duplicate of #4343: your system doesn't have enough memory; see #4864 for an explanation. Also note that each new LLVM version brings new optimisations and features that may require more memory than previously required, too.

**Closed by ysbaddaden** 2017-08-28 12:59 UTC
