### ISSUE TITLE
Generic type not inferred with default arguments

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#4678] opened 2017-07-05 15:22 UTC
Hello,

It looks like the compiler cannot infer the type of the variable when using default arguments

```crystal
class Klass(T)
  property a : T

  def initialize(@a : T = 1)
  end
end

Klass(Int32).new 1 # ok
Klass.new 1 # ok
Klass.new # ko
```

```text
Using compiled compiler at `.build/crystal'
Error in test.cr:10: can't infer the type parameter T for the generic class Klass(T). Please provide it explicitly

Klass.new
```

**Comment by dakaii** [comment] 2017-08-02 09:15
I was able to reproduce the error, but do you have any tips on what to look for?
im new to this project.
im currently looking at the prepare_typed_def_with_args function inside call.cr and have been printing out random variables....

**Comment by asterite** [comment] 2017-09-13 16:27
Duplicate of #2456

**Comment by asterite** [comment] 2017-09-13 16:28
(not exactly the same, but inferring `T` from the default argument doesn't work right now)

**Closed by asterite** 2017-09-13 16:27 UTC
