### ISSUE TITLE
Failure with type restriction of method argument

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4568] opened 2017-06-14 19:52 UTC
```crystal
alias Type = Int32 | Array(Type)

def call_filter(target : Type)
  pp target.is_a?(Type) # => false
  pp typeof(target) # => Array(Int32)
  pp target.class # => Array(Int32)
end

call_filter([1, 2, 3])
```
https://carc.in/#/r/26oc

Somehow `Array(Int32)` is passing as `Type` in the method signature, but not with `.is_a?`.
The code should not compile and fail with `type must be Type, not Array(Int32)` as does this:
```crystal
alias Type = Int32 | Array(Type)

a = [1, 2, 3]
b : Type = a
```

**Comment by bew** [comment] 2017-06-14 20:02
From my understanding, it's correct code, but the outputs are wrong:
```cr
pp target.is_a?(Type) # should be true
pp typeof(target) # should be Type
```

**Comment by asterite** [comment] 2017-06-14 20:06
This is always the same "issue" regarding covariance and contravariance and how method restrictions work differently than `is_a?`. Here's another example:

```crystal
class Foo
end

class Bar < Foo
end

def foo(a : Array(Foo))
  p a.is_a?(Array(Foo))
end

a = [] of Bar
foo(a)
```

The above passes the method, but prints `false` because `a` isn't technically an `Array(Foo)`. 

It's the same with recursive type aliases. I'm not sure there's a way to solve this.

In any case, duplicate of #3803

**Closed by asterite** 2017-06-14 20:06 UTC
