### ISSUE TITLE
crystal tool format can't handle parentheses in both block args followed by parentheses in block body

### ISSUE THREAD

**Issue by petertseng** [crystal-lang/crystal#3422] opened 2016-10-15 08:49 UTC
As best as I can figure it, `crystal tool format` was unable to handle this (this is a minimized example, the original was in a larger file, but is of the same form as the example).

```crystal
[3, 4].each_cons(2).map { |(a, b)| (a + b) / 2 }
```

This will get me:

```
$ crystal tool format src/unformattable.cr
Error:, couldn't format 'src/unformattable.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues
```

A few variations:

* Removing parentheses from the block body will allow `crystal tool format` to work, but obviously would change the semantics of the block body, that's not desirable.
* Removing parentheses from the block arguments will cause a compile error `wrong number of block arguments (given 2, expected 1)`... but will also allow `crystal tool format` to work. Unless there is another way I should destructure the `each_cons` block arg?
* Putting something before the parentheses in the block body will also allow `crystal tool format` to work. For example, `map { |(a, b)| 0 + (a + b) / 2 }`. I probably won't want to keep the workaround for a while though.

**Comment by asterite** [comment] 2016-10-15 14:32
Already fixed in master, duplicate of #3407

**Closed by asterite** 2016-10-15 14:32 UTC
