### ISSUE TITLE
SVG content type

### ISSUE THREAD

**Issue by damianham** [crystal-lang/crystal#5604] opened 2018-01-18 12:43 UTC
crystal-lang/crystal/blob/master/src/http/server/handlers/static_file_handler.cr#mime_type

needs to return a content type of "image/svg+xml" when the path extension is ".svg"

**Comment by straight-shoota** [comment] 2018-01-18 12:47
Duplicate of #4632

**Closed** 2018-01-18 13:15 UTC
