### ISSUE TITLE
class variable bug

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#6745] opened 2018-09-19 04:31 UTC
```crystal
require "bit_array"

class A
  @@x = BitArray.new(1)
  @@x[0] = true

  def self.x_0
    return @@x[0]
  end
end

class B < A
end

b = B.new
puts b.class.x_0 # false
a = A.new
puts a.class.x_0 # true

```

**Comment by RX14** [comment] 2018-09-19 10:38
Not a bug, just confusing. `@@x` in each class is a separate variable with separate values. `@@x[0]` is top-level code and runs only once. You want to write

```cr
require "bit_array"

class A
  @@x : BitArray = begin
    arry = BitArray.new(1)
    arry[0] = true
    arry
  end

  def self.x_0
    return @@x[0]
  end
end

class B < A
end

b = B.new
puts b.class.x_0 # false
a = A.new
puts a.class.x_0 # true
```

**Comment by RX14** [comment] 2018-09-19 10:39
I'd like to experiment with removing the ability to run top-level code outside the `::` namespace.

**Comment by jhass** [comment] 2020-07-10 09:42
I guess we can actually close this?

**Closed** 2021-08-04 00:10 UTC
Labels: kind:question
