### ISSUE TITLE
File.expand_path produces invalid/broken string (bug and workaround)

### ISSUE THREAD

**Issue by sasa** [crystal-lang/crystal#4440] opened 2017-05-21 14:37 UTC
I hope this is a bug. It sure seems like it.
```
#!/usr/bin/env crystal
def slug(str : String) : String
  str = str.downcase
  str = str.gsub("ä", "ae")
  str = str.gsub("ö", "oe")
  str = str.gsub("ü", "ue")
  str = str.gsub("ß", "ss")
end

stdout = IO::Memory.new
Process.run("pwd", output: stdout) # the workaround
stdout.close
path = "/Users/sasa/bin/äöüÄÖÜß"
test = Dir.current
puts slug(path.split("/").last)        # should be aeoeueaeoeuess
puts slug(stdout.to_s.split("/").last) # should be aeoeueaeoeuess
puts slug(test.split("/").last)        # should be aeoeueaeoeuess
```

The output

```$ crystal test.cr
$ test.cr
aeoeueaeoeuess
aeoeueaeoeuess
äöüäöüss
```

The two strings are not identical. String.downcase works. Also `str = str.gsub("ß", "ss")`, but not äöü (and probably others too).

Sasa

**Comment by bcardiff** [comment] 2017-05-22 04:58
@sasa it seems a unicode normalization issue

https://unix.stackexchange.com/questions/90100/convert-between-unicode-normalization-forms-on-the-unix-command-line

`LibC.getcwd` that is used to implement `Dir.current` is returning the string with different representation for ä and others, and that is preventing the gsub to apply the substitutions.

To solve this we should extract the normalization data from unicode, add normalization operations and use the in `Dir.current` probably.

FWIW, I was able to reproduce it in osx 10.12.3.

**Comment by sasa** [comment] 2017-05-24 10:48
@bcardiff I thought as much. Thank you for looking into it and for the explanation. I hope it can get resolved in one of the next releases.

**Comment by asterite** [comment] 2017-06-08 21:14
Changing to a feature because unicode normalization is a (pretty complex to implement) feature

**Comment by akzhan** [comment] 2017-06-09 09:50
Will investigate for normalize (after String.compare with Fold) 17 Jun.

It should be

**Comment by straight-shoota** [comment] 2018-09-07 17:02
This issue seems to be resolved, it doesn't reproduce with latest Crystal version. See https://carc.in/#/r/4wnu

```cr
def slug(str : String) : String
  str.downcase.gsub("ä", "ae").gsub("ö", "oe").gsub("ü", "ue").gsub("ß", "ss")
end

`mkdir äöüÄÖÜß`

Dir.cd "äöüÄÖÜß"

p! slug("äöüÄÖÜß"),
   slug(File.basename(`pwd`).strip),
   slug(File.basename(Dir.current))
```

**Comment by straight-shoota** [comment] 2018-09-07 19:58
Judging from the provided output it is just the regular unicode characters for these umlauts.

So yes, the report doesn't make sense. Maybe there was some transformation in between or whatever, but riggt now its not reproducible.
@sasa any additions?

**Comment by opiation** [comment] 2019-05-20 02:18
I'm going through `community:help-wanted`-labeled issues from oldest to newest looking for a place to contribute.  This issue is quite dated and no longer seems reproducible [based on @straight-shoota's test](https://github.com/crystal-lang/crystal/issues/4440#issuecomment-419503528).  I was unable to reproduce the results from the original report given the code provided using the latest `0.28.0` version of crystal.  Should this issue be closed as [`invalid`](https://github.com/crystal-lang/crystal/blob/master/CONTRIBUTING.md#status) given it being not reproducible?

**Comment by straight-shoota** [comment] 2019-05-20 10:25
I wouldn't say it's an invalid issue, because the OP probably has validity, it just lacks information to reproduce it.
I'll close it anyway due to no activity and not being reproducible.

**Closed by straight-shoota** 2019-05-20 10:25 UTC
Labels: kind:feature, status:needs-more-info, topic:stdlib

**Comment by opiation** [comment] 2019-05-20 13:54
Oh excellent!  I hadn't noticed the `status:needs-more-info` label.  That does indeed seem more appropriate.
