### ISSUE TITLE
Improve Errno error handling

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#8305] opened 2019-10-10 18:05 UTC
Current issues with having `Errno` constants are:
- specific `Errno` exceptions can't be rescued specifically – that's either all or none.
- comparing integer `Errno#errno` is the only way to know the actual error type.

The solution would be to use classes for errno errors to be able to differentiate them, in order to prevent the user to deal with integers.

**Comment by asterite** [comment] 2019-10-10 18:39
Another solution if to have something like `rescue ex if ex.something?` which will work really well with Errno. See #1124

**Comment by asterite** [comment] 2019-10-10 18:39
So this might be just a duplicate of #1124

**Comment by oprypin** [comment] 2019-10-10 22:06
Actually is https://github.com/crystal-lang/crystal/pull/5003 "Change Errno into a hierarchy of OSError subclasses"

**Comment by straight-shoota** [comment] 2019-10-11 09:01
Thanks @oprypin for referencing your PR. I remembered there had been prior discussions, but couldn't find that specific one.

Currently, `Errno` simply wraps the error reporting mechanism provided by libc and places it into an exception. It's a legacy and bad design and doesn't represent idiomatic Crystal. This is strictly different for stdlib APIs that don't depend on libc functions. They use to raise specific exception classes depending on the type of error. Regular users shouldn't have to care about errno and how an API is implemented. The user experience should be identical whether a stdlib API is implemented in pure Crystal or based on libc. And it should be portable (see #4835).

**Comment by RX14** [comment] 2019-10-21 12:06
In my opinion, `Errno` needs to go. No other language apart from ruby couples their exception hierarchy to a decades old hack around C not being able to return tuples like this.

My vision for exceptions at `1.0` is that they not only are well-named and not platform-specific, but they contain accessible fields relating to the error. For example, a DNS lookup failure would have a getter for the name which was being resolved. A network connection failure would have the `IPAddress` attached. `errno` would still exist, as a property, for the few people who need it, but it'd largely be ignored because it's just not necessary.

There might be technical problems that need to be overcome to achieve a better API but they can be solved like any other.

**Comment by rdp** [comment] 2019-11-07 06:29
Dunno if related but here's an example where IO::Error was caught but it allowed Errno to still propagate up through (accidentally): https://github.com/crystal-lang/crystal/issues/7136#issuecomment-550747522 FWIW :)

**Comment by j8r** [comment] 2020-03-24 13:44
Closed with https://github.com/crystal-lang/crystal/pull/8885

**Closed** 2020-03-24 16:22 UTC
Labels: community:to-design, kind:feature, status:discussion
