### ISSUE TITLE
BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

### ISSUE THREAD

**Issue by orangeSi** [crystal-lang/crystal#8323] opened 2019-10-14 04:09 UTC
I download ```crystal-0.31.1-1-linux-x86_64.tar.gz``` then ```tar xjf crystal-0.31.1-1-linux-x86_64.tar.gz```, run ```crystal-0.31.1-1/bin/crystal eval 'puts "dd"' ``` will got error:
```
/usr/bin/ld: BFD version 2.20.51.0.2-5.47.el6_9.1 20100205 internal error, aborting at reloc.c line 443 in bfd_get_reloc_size

/usr/bin/ld: Please report this bug.

collect2: ld returned 1 exit status

```
```
$crystal -v
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

$cat /etc/centos-release 
CentOS release 6.9 (Final)
```

EDIT (@straight-shoota): Removed leftover boilerplate from issue template.

**Comment by straight-shoota** [comment] 2019-10-14 06:35
Thanks for reporting! This seems to be a bug in `ld`, not Crystal. The reported version 2.20 is 9 years old and there are similar errors described on the internet. So you'll simply need to upgrade binutils to a newer, bug-fixed version.

**Comment by orangeSi** [comment] 2019-10-15 02:36
> Thanks for reporting! This seems to be a bug in `ld`, not Crystal. The reported version 2.20 is 9 years old and there are similar errors described on the internet. So you'll simply need to upgrade binutils to a newer, bug-fixed version.

I need update my ``` ld ``` ?
and when I download  crystal 0.30.1, the bug disappear ~

**Comment by refi64** [comment] 2019-10-15 03:41
Most likely, the codegen changed in some subtle way so that 0.30.1 no
longer reproduces the issue.

**Comment by straight-shoota** [comment] 2019-10-15 06:24
> I need update my ld ?
> and when I download crystal 0.30.1, the bug disappear ~

Yes, update ld should fix this. The upgrade to LLVM 8 (between 0.30 and 0.31) probably produces different codegen which causes the bug in ld to appear.

**Comment by ysbaddaden** [comment] 2019-10-15 07:03
We can't ask a centos user to update a core package like binutils, thats the exact opposite of the centos goal (keep long stable packages not the latest shiny).

A better solution would be centos specific packages that someone must maintain —we probably won't do that ourselves. If Crystal 0.30.1 is working you could compile crystal 0.31.x with it, but you'll lack a recent enough LLVM version —I can only find LLVM 3.0 which isn't, and 3.4 which I dont think we support anymore. I believe we only support LLVM 3.8+ fir the time being.

Uograding to centos 7 if possible would probably be a better choice. Packages would probably work out of the box, and if not LLVM 5 and 7 are available for it.

**Comment by ysbaddaden** [comment] 2019-10-15 07:08
Closing, because there is nothing we can do. RPM and DEB packages are built for recent linux distributions, using recent LLVM releases. Significantly older distributions need specific packages and dedicated maintainers.

**Closed** 2019-10-15 07:08 UTC

**Comment by orangeSi** [comment] 2019-10-15 07:10
> > I need update my ld ?
> > and when I download crystal 0.30.1, the bug disappear ~
> 
> Yes, update ld should fix this. The upgrade to LLVM 8 (between 0.30 and 0.31) probably produces different codegen which causes the bug in ld to appear.

thanks~ I update binutil to 2.31.1 by conda, Crystal 0.31.1 does works~
