### ISSUE TITLE
Feature Request: `IO` Write Literal with Interpolation

### ISSUE THREAD

**Issue by chris-huxtable** [crystal-lang/crystal#5144] opened 2017-10-19 16:26 UTC
# `IO` Write Literal with Interpolation

Would it be possible to add an `IO` literal syntax that functions identically to the `String` literal syntax except writes to an arbitrary `IO` instead of a new `StringBuilder`?

## Motivation:
I am generating large text files. Currently if I use `String` literals it creates a `String` which is then immediately dumped into an `IO` (`File Descriptor`/`STDOUT`/`Socket`). This would cause a chunk of memory to be acquired, filled, copied to, copied from, and then deleted. Instead I have written some helper functions which take in a tuple and then writes each entry directly to the IO device. I am sure I am not the only one who has had to do similar. Something like an `IO` write literal would could dramatically reduce the complexity and improve the readability.

**Comment by asterite** [comment] 2017-10-19 16:29
I proposed this in https://github.com/crystal-lang/crystal/issues/1267 . It wasn't very liked (I like it, though).

Duplicate of #1267

**Closed by asterite** 2017-10-19 16:29 UTC

**Comment by chris-huxtable** [comment] 2017-10-19 16:30
Sorry for the duplicate, I looked but didn't find it. Thanks.
