### ISSUE TITLE
Can't define constant inside other constant definition ("nested" constants)

### ISSUE THREAD

**Issue by nbulaj** [crystal-lang/crystal#8158] opened 2019-09-06 15:04 UTC
Here an example of defining constants inside other constant definition that works in Ruby, but not in Crystal (btw compiler allows to write such code and don't produce any errors until runtime).

```cr
module Types
  ALL = [
    CREATED = "created",
    IN_PROGRESS = "in progress",
    DONE = "done",
    ACCEPTED = "accepted"
  ]
end

puts Types::ALL.inspect
```

Produces:

```cr
# Nil assertion failed (NilAssertionError)
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from ???
#  from __crystal_main
#  from main
#  from __libc_start_main
#  from _start
#  from ???
```

I know Crystal not Ruby :) but if such syntax is forbidden - I think compiler needs to notify developer, otherwise it's a valid syntax. WDYT?

Reproducible code - https://play.crystal-lang.org/#/r/7id0

Crystal -v:

```bash
$ crystal -v
Crystal 0.30.1 [5e6a1b672] (2019-08-12)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu # (actually Ubuntu 18.04)
```

**Comment by asterite** [comment] 2019-09-06 15:08
Duplicate of #2874

**Comment by nbulaj** [comment] 2019-09-06 15:09
Damn, sorry, didn't find this #2874 ! :(

**Closed by asterite** 2019-09-06 15:08 UTC

**Comment by asterite** [comment] 2019-09-06 15:09
I know it's not exactly the same as #2874 but it's still constants inside other constants. That will be forbidden in future versions, it's just that we didn't have time to implement it yet.

**Comment by asterite** [comment] 2019-09-06 15:10
@nbulaj No worries. This helps us know that this error affects more people :-)

**Comment by nbulaj** [comment] 2019-09-06 15:11
Thanks @asterite , got it. Crystal is awesome no matter what :)
