### ISSUE TITLE
The size of the compiled file on Crystal 0.27.2 is 80 kb more?

### ISSUE THREAD

**Issue by webmastak** [crystal-lang/crystal#7478] opened 2019-02-23 00:14 UTC
Why one and the same program compiled on Crystal 0.27.2 weighs 80 kb more than compiled on Crystal 0.27.0

 [Sources here](https://github.com/webmastak/rss-feed-notifications)

**Comment by asterite** [comment] 2019-02-23 00:52
Hi! Duplicate of #3745

You will find all the answers there.

**Closed by asterite** 2019-02-23 00:52 UTC
