### ISSUE TITLE
specs not working with u128

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#7088] opened 2018-11-15 03:04 UTC
Am I doing something wrong?

https://play.crystal-lang.org/#/r/5iwx
```crystal
221360928888809586640_u128 == 221360928888809586640_u128
```
This seems to throw and error

https://play.crystal-lang.org/#/r/5iwr
```crystal
require "spec"
221360928888809586640_u128.should eq 221360928888809586640_u128
```
This seems to also throw an erro

**Comment by Sija** [comment] 2018-11-15 03:12
See #5564

**Comment by RX14** [comment] 2018-11-22 13:06
Duplicate of #5564

**Closed by RX14** 2018-11-22 13:06 UTC

**Comment by wontruefree** [comment] 2018-11-25 23:02
@RX14 I am reopening this to finish it.  It seems like @omotorin has stopped working on it
