### ISSUE TITLE
HTTP::Server Fiber crash with "Header content contains invalid character" 

### ISSUE THREAD

**Issue by bararchy** [crystal-lang/crystal#5611] opened 2018-01-19 19:58 UTC
I have found that using some "invalid character", it's easy to crash a fiber at the server side using a simple get request.

```crystal
Unhandled exception on HTTP::Handler
Header content contains invalid character '\u{6}' (ArgumentError)
Unhandled exception on HTTP::Handler
Header content contains invalid character '\u{6}' (ArgumentError)
Unhandled exception on HTTP::Handler
Header content contains invalid character '\u{6}' (ArgumentError)
Unhandled exception on HTTP::Handler
Header content contains invalid character '\u{10}' (ArgumentError)
```

There should be some defense against this kind of abuse especially when HTTP::Server is used as the basis for all major web frameworks and crystal play.

**Comment by asterite** [comment] 2018-01-19 20:05
@bararchy This should have been fixed in https://github.com/crystal-lang/crystal/pull/5041

I'm checking the code, when the request headers are parsed from the IO the `add?` method is used so this should be working.

What Crystal version are you using?

**Comment by bararchy** [comment] 2018-01-19 20:07
0.24.1, this is by running ` crystal play`

**Comment by asterite** [comment] 2018-01-19 20:09
We probably need some code to reproduce, otherwise there's not much we can do.

**Comment by RX14** [comment] 2018-01-19 20:23
So, does it actually crash the server or just break that specific request?

**Comment by bararchy** [comment] 2018-01-19 20:29
The Fiber that is spawned to handle this request "breaks" with unhandled exception, this would have crash the whole server if it wouldn't have been saved by the Fiber, so Fiber dies, server is saved, but this is hardly a good solution, more of a lucky save.

I'm working on the exact payload to send to the server to cause this

**Comment by bararchy** [comment] 2018-01-19 21:04
@asterite 
This URL: `http://localhost:8080/%2Fabout%2F%0A%C3%92%C3%92%C3%92%C3%92%1E` against a running crystal play instance will produce the error:

```
Unhandled exception on HTTP::Handler
Header content contains invalid character '\n' (ArgumentError)
Unhandled exception on HTTP::Handler
Header content contains invalid character '\n' (ArgumentError)

```

Let me know if you need more info to tackle this

**Comment by bararchy** [comment] 2018-01-20 17:03
@asterite @RX14 Did you manage to see this using the above method ?

**Comment by asterite** [comment] 2018-01-20 20:49
No, I don't have time and probably won't have the time to investigate this. Someone else will have to take a look.

**Comment by straight-shoota** [comment] 2018-01-22 20:10
Reduced code to reproduce:
```crystal
require "http/server"

processor = HTTP::Server::RequestProcessor.new(HTTP::StaticFileHandler.new("."))
request = HTTP::Request.new("GET", File.basename(__FILE__) + "%0A")

io = IO::Memory.new
request.to_io(io)
io.rewind
processor.process(io, IO::Memory.new)
```

> I'm checking the code, when the request headers are parsed from the IO the add? method is used so this should be working.

This error is caused by `StaticFileHandler#redirect_to` which doesn't use `add?`. I guess we should just extend the validity check for `request_path` in `StaticFileHandler#call` beyond checking for null char.

**Comment by straight-shoota** [comment] 2018-01-22 20:37
A fix for the immediate issue is in #5628 but the error handling regarding fibers probably needs further investigation.

**Comment by asterite** [comment] 2018-01-22 20:41
@straight-shoota what do you think can be improved regarding unhandled exceptions in fibers?

**Comment by straight-shoota** [comment] 2018-01-22 21:16
I don't know.

**Closed** 2018-04-30 08:57 UTC
