### ISSUE TITLE
abstract method not work

### ISSUE THREAD

**Issue by delef** [crystal-lang/crystal#7509] opened 2019-03-04 20:24 UTC
```
abstract class Foo
  abstract def baz : String
end

class Bar < Foo
  def baz : Int32
    1
  end
end

pp Bar.new.baz # => 1
```
https://play.crystal-lang.org/#/r/6exw

Why? 😳

**Comment by z64** [comment] 2019-03-04 20:30
Duplicate of #3546 (also see #160)

**Closed** 2019-03-04 20:32 UTC
