### ISSUE TITLE
Instance method loses type inheriting from abstract generic class

### ISSUE THREAD

**Issue by jclem** [crystal-lang/crystal#5275] opened 2017-11-11 18:43 UTC
Given an abstract generic class with an abstract instance method that returns the generic type, when a concrete class inherits from that class, the compiler does not enforce that the concrete class's implementation of the instance method returns the generic type.

See https://play.crystal-lang.org/#/r/32ld

```
abstract class Foo(T)
  abstract def foo : T
end

class Bar < Foo(String)
  def foo
    1
  end
end

puts Bar.new.foo
```

Crystal v0.23.1, MacOS 10.13.1

**Comment by MakeNowJust** [comment] 2017-11-11 18:47
This happens against not only generics:

```crystal
abstract class Foo
  abstract def foo : String
end

class Bar < Foo
  def foo
    1
  end
end

puts Bar.new.foo
```

**Comment by bew** [comment] 2017-11-11 18:52
Note: Adding the type restriction on `Bar#foo` will error as we would expect.

Looks like a bug to me

**Comment by RX14** [comment] 2017-11-12 13:48
Duplicate of https://github.com/crystal-lang/crystal/issues/3546

See also https://github.com/crystal-lang/crystal/issues/160

**Closed by RX14** 2017-11-12 13:48 UTC
