### ISSUE TITLE
Hex Array Literals

### ISSUE THREAD

**Issue by stellarpower** [crystal-lang/crystal#14654] opened 2024-06-01 19:58 UTC
## Feature Request
Don't know if there's a neat and terse way to do this already (probably some way), but, when working with binary data or similar, it's be nice to have a percent syntax for creating array literals of UInts without having to type as much:

```Crystal
%x| 42 af e1 | == [ 0x42, 0xaf, 0xe1 ]
```

Ideally the length would be inferred from the number of characters, and enforced to be the same for all elements as well as enforced to fir exactly in one of the built-in unsigned integer types.I think anything other than unsigned integers would be fair to be out of scope and cause more confusion.

Thanks

**Comment by Blacksmoke16** [comment] 2024-06-01 20:02
Not exactly the same, but you can do like:

```cr
"42afe1".hexbytes # => Bytes[66, 175, 225]
```

**Comment by HertzDevil** [comment] 2024-06-01 20:04
#2886

**Comment by Blacksmoke16** [comment] 2024-06-01 20:04
Duplicate of #2886

**Closed by Blacksmoke16** 2024-06-01 20:04 UTC
Labels: kind:feature, topic:stdlib:text

**Comment by stellarpower** [comment] 2024-06-02 17:40
> Not exactly the same, but you can do like:
> 
> ```crystal
> "42afe1".hexbytes # => Bytes[66, 175, 225]
> ```

Thanks, I could definitely use that for now. The spaces I think would be very useful, having previously worked with HID Report desciptors where you wanna see the boundary between bytes - but I could split the string on whitespace, rejoin and then call hexbytes.
