### ISSUE TITLE
Iteration on descending range doesn't work

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#11526] opened 2021-12-02 05:26 UTC
There is no iteration in this example:
```crystal
(11..6).each do |i|
  p i
end
```

**Comment by Blacksmoke16** [comment] 2021-12-02 05:28
Duplicate of https://github.com/crystal-lang/crystal/issues/1391

**Closed by Blacksmoke16** 2021-12-02 05:28 UTC
Labels: kind:bug

**Comment by BrucePerens** [comment] 2021-12-02 05:30
@Blacksmoke16 Blacksmoke, I don't think it's a feature request, as today it _silently_ fails.

**Comment by Blacksmoke16** [comment] 2021-12-02 05:36
@BrucePerens Regardless of that, there is a ticket that already has some discussion on it, so that ticket should be used instead of a new one. Whether it should be treated as a feature request, or a bug, is up for debate. However, given how this has been the behavior since `Range` was implemented (at least as of [0.8.0](https://play.crystal-lang.org/#/r/cdnm)), it's more likely a feature request IMO.
