### ISSUE TITLE
Use abstract method's documentation when there's no documentation for implemented method

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7524] opened 2019-03-08 07:36 UTC
A good example is @Sija's PR: [`#7520`](https://github.com/crystal-lang/crystal/pull/7520/files#diff-cf769fe2e361e14888004d0eae8368fdR559).
There are two abstract methods added in `Int` and then implemented in all the integer types (`Int8`, `Int16`, `Int32` and so on). But right now there's no documentation for the methods (neither for `popcount`).

You wouldn't really know what for example `trailing_zeros_count` does when you would see it in `Int32`. You might think it counts the trailing zeroes of a number like `120000` but that returns `6` instead of `4` and you get confused because it actually returns the number of trailing zero *bits* of the number. But when the method would have the documentation `` Returns the number of trailing `0`-bits. `` then you probably clearly know what it does.

I think when no documentation is present for the implementation of an abstract method then the documentation should be copied from the abstract method. In that case all `trailing_zeros_count` methods would automatically have the `` Returns the number of trailing `0`-bits. `` documentation.

**Comment by straight-shoota** [comment] 2019-03-08 09:02
There is already an PR for this.

Duplicate of #6989

**Closed by straight-shoota** 2019-03-08 09:02 UTC
