### ISSUE TITLE
Issue using xpath with XML when not all namespaces are the same

### ISSUE THREAD

**Issue by jwoertink** [crystal-lang/crystal#12373] opened 2022-08-10 23:15 UTC
Take this code:

```crystal
require "xml"
 
xml = <<-XML
<bookstore xmlns="http://www.w3.org/2001/XMLSchema">
<book>
  <title lang="en">Learn Crystal</title>
  <price>29.99</price>
</book>
</bookstore>
XML
 
data = XML.parse(xml)
 
pp data.xpath("//bookstore/book")
```

This will print out an empty array, but if we change the `xmlns` from `xmlns="http...` to `xmlns:anything="http....` then you'll get the result.

I'm not familiar with the XML spec, so I don't know if that's just broken markup, or requires special options, so it's possible this could just be documentation. I saw the `xpath` method has these `namespaces` and `variables` args, but I wasn't sure what they should be/do

https://github.com/crystal-lang/crystal/blob/994c70b10e9939d73b561135b0822dea4f9979bb/src/xml/node.cr#L495

In my code, I'm fetching data from an API, and I get markup like this. To get around this, I have to gsub this value before parsing.

**Comment by Blacksmoke16** [comment] 2022-08-10 23:45
Duplicate of https://github.com/crystal-lang/crystal/issues/11078

You can do what you want via something like `pp data.xpath("//default:bookstore/default:book", {"default" => "http://www.w3.org/2001/XMLSchema"})`, as explained in more detail in the other issue.

**Closed by Blacksmoke16** 2022-08-10 23:45 UTC
Labels: kind:bug, status:duplicate, topic:stdlib:serialization
