### ISSUE TITLE
Unexpected abort when loading HTTP spec files in different order

### ISSUE THREAD

**Issue by benoist** [crystal-lang/crystal#1786] opened 2015-10-19 19:41 UTC
I'm running into some issues for the openssl pull request, when running the tests I was getting unexpected data.

expected: "DATADATADATADATADATA"
            got: "DATADATADATADATADATAorm from {\"foo\" => [\"bar\", \"baz\"]}"

I noticed this was caused when running the specs in combination with the HTTP spec.

Trying to figure which spec was causing this I noticed that running certain HTTP spec in a different order resulted in the following error:

```
Assertion failed: (Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"), function getTypeSizeInBits, file /tmp/llvm20150726-78491-1dqz88o/llvm-3.6.2.src/include/llvm/IR/DataLayout.h, line 500.
Abort trap: 6
```

The test file is as follows

```crystal
require "./std/http/request_spec"
require "./std/http/web_socket_spec"
require "./std/http/server_spec"
```

**Comment by jeromegn** [comment] 2016-03-01 13:37
I just got the same running my spec, which are passing on Travis, locally.

https://github.com/jeromegn/bson.cr
https://travis-ci.org/jeromegn/bson.cr

Locally I get:

```
$ crystal spec
Assertion failed: (Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"), function getTypeSizeInBits, file /tmp/llvm20150911-50397-fcfh6x/llvm-3.6.2.src/include/llvm/IR/DataLayout.h, line 500.
[1]    39518 abort      crystal spec
```

**Comment by asterite** [comment] 2016-03-01 18:34
This seems to be fixed in master. Can you try doing the same but using a compiled compiler?

**Comment by asterite** [comment] 2016-05-20 21:45
@benoist @jeromegn Is this still an issue? I don't know how to try to reproduce it anymore because repos changed.

**Comment by benoist** [comment] 2016-05-20 21:46
I havent seen this anymore

**Comment by jeromegn** [comment] 2016-05-22 17:02
Seems good here too.

**Closed** 2016-05-22 17:10 UTC
Labels: bug, compiler
