### ISSUE TITLE
Global and class macros having precedence over methods

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4431] opened 2017-05-19 14:11 UTC
Global macro methods seem to get precedence over instance methods of the same name.

Example code ([carc.in](https://carc.in/#/r/21nl)):
```
macro render(foo)
  {{ foo.downcase }}
end

class Foo  
  def render
     render(nil)
  end
  
  def render(env)
  end
end

Foo.new.render
```
Compiler output: 
```
Error in line 14: instantiating 'Foo#render()'

in line 7: expanding macro

in line 2: undefined macro method 'NilLiteral#downcase'

in line 7: undefined macro method 'NilLiteral#downcase'
```
The same happens when the macro is defined inside `Foo`.

In both cases this behaviour is highly unexpected and probably never really intended: If you try to call an instance method from within the scope of the same object, this should not at all trigger a macro instead. Neither from global nor from class scope. Especially when using libraries, they could not possibly take into account any macro that might be defined by an application. It would also suck to have to make `self` the explicit receiver of every method call.

I doubt that macro methods should be directly visible inside instance scope at all. It's easy to confuse them with instance methods. I'd expect their visibility to be equal to class methods, they can not be invoked from an instance method without scoping the call to the class (`self.class.class_method` or `MyClass.class_method`). To call a macro from inside an instance method, I think it should be prefixed with the class scope - or global scope (`::`) if it is a global macro - and not implicit.

A practical example of this isssue is described in kemalcr/kemal#359 . As already mentioned there, this issue can be worked around by adding an explicit scope: `self.render(nil)` in the sample code. The example for liquid.cr from @icyleaf is different, since `tpl.render(ctx)` has already an explicit scope but still invokes the global macro. I can't figure out why exactly this is failing but it also seems to be a naming conflict between instance method and macro method.
//cc @sdogruyol @jeromegn

**Comment by bcardiff** [comment] 2017-05-19 14:18
Duplicate of #236

**Closed by bcardiff** 2017-05-19 14:18 UTC
Labels: status:duplicate

**Comment by asterite** [comment] 2017-05-20 16:15
I fixed this. Now when macros are looked up and not found, but a method with the same name in the same scope is found, search doesn't continue up in the scope hierarchy. This should be much more intuitive and robust to program with.

It will be available in the next release.
