### ISSUE TITLE
Can't delegate "map", "map_with_index" methods

### ISSUE THREAD

**Issue by sudo-nice** [crystal-lang/crystal#7351] opened 2019-01-31 07:22 UTC
These two pieces of code fail to compile:

**delegating `map`** https://carc.in/#/r/64sa
```crystal
class Foo
  @foo = [1, 2, 3]
  delegate map, to: @foo
end

Foo.new.map do |name|
  "Hello, #{name}"
end
```

**delegating `map_with_index`** https://carc.in/#/r/64sb
```crystal
class Foo
  @foo = [1, 2, 3]
  delegate map_with_index, to: @foo
end

Foo.new.map_with_index do |name, i|
  "#{i}: #{name}"
end
```

With the same error:
```crystal
in macro 'delegate' /usr/lib/crystal/object.cr:1084, line 10:

   1.     
   2.       
   3.         def map(*args, **options)
   4.           @foo.map(*args, **options)
   5.         end
   6. 
   7.         
   8.           def map(*args, **options)
   9.             @foo.map(*args, **options) do |*yield_args|
> 10.               yield *yield_args
  11.             end
  12.           end
  13.         
  14.       
  15.     
  16.   

expected splat expression to be a tuple type, not Int32
```
---
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

  LLVM: 4.0.0
  Default target: x86_64-unknown-linux-gnu

**Comment by asterite** [comment] 2019-01-31 15:07
Duplicate of #6473

**Closed by asterite** 2019-01-31 15:07 UTC
