### ISSUE TITLE
Crystal compiler has infinite loop with recursive alias in certain situation

### ISSUE THREAD

**Issue by jasonl99** [crystal-lang/crystal#4126] opened 2017-03-09 19:50 UTC
I was trying figure out how to alias what are ulimately turned into JSON messages, and I've run across what seems to be a compiler bug.  I imagine this happens since the alias references itself.

First, the code that works the way I expect after trialing-and-erroring my way through:

```crystal
alias Message = Hash(String, String | Int32 | Float64 | Message)

def foo( m : Message)
  puts m
end

x = {"a"=>"b"}
y = {"a"=>1}
z = {"a"=>{"b"=>"c","c"=>3}}

foo x  # {"a"=>"b"}
foo y  # {"a"=>1}
foo z  # {"a"=>{"b"=>"c","c"=>3}}
```

Now some buggy code that crystal compiler will catch correctly, as I was trying to figure out if I could cast stuff:

```crystal
alias Message = Hash(String, String | Int32 | Float64 | Message)
x = {"a"=>"b"}.as(Message)   # can't cast Hash(String, String) to Message 
```

Now the problem.   If I add back my `foo` proc and call it later in the code:

```crystal
alias Message = Hash(String, String | Int32 | Float64 | Message)

def foo( m : Message)
  puts m
end

x = {"a"=>"b"}.as(Message)    # This was caught in the above example

foo x

```

Attempting to run that code results in what looks like crystal's compiler getting stuck in a loop (I have to ctrl-c to break out of it). 

```crystal
[10725118] ???
[10763943] ???
[10744601] ???
[11097723] ???
[10725118] ???
[10763943] ???
[10744601] ???
[11097723] ???
[10725118] ???
[10763943] ???
[10744601] ???
[11097723] ???
# repeats continue
```

**Comment by asterite** [comment] 2017-03-09 19:53
Recursive aliases without a base case are a known issue.

Duplicate of #3804

**Closed by asterite** 2017-03-09 19:53 UTC
