### ISSUE TITLE
Compiler crash when defining a constant inside a constant

### ISSUE THREAD

**Issue by aaronbronow** [crystal-lang/crystal#2874] opened 2016-06-18 19:27 UTC
Code

This is how I accidentally discovered an issue. Not a very likely scenario right? It was a typo. I gave a variable a capitol letter which made it a const. :)

``` cr
FOO = begin
  BAR = 1
end

puts FOO
```

Here is a more simple example.

``` cr
A = B = 1

puts A
```

Output

```
Nil assertion failed
[4335949203] *raise<String>:NoReturn +163
[4336000352] *Nil#not_nil!<Nil>:NoReturn +16
[4345468781] *Crystal::ASTNode+@Crystal::ASTNode#transform<Crystal::ASTNode+, Crystal::CleanupTransformer>:Crystal::ASTNode+ +18381
[4345455796] *Crystal::ASTNode+@Crystal::ASTNode#transform<Crystal::ASTNode+, Crystal::CleanupTransformer>:Crystal::ASTNode+ +5396
[4345449632] *Crystal::CleanupTransformer#transform<Crystal::CleanupTransformer, Crystal::Expressions>:Crystal::Expressions +112
[4345451313] *Crystal::ASTNode+@Crystal::ASTNode#transform<Crystal::ASTNode+, Crystal::CleanupTransformer>:Crystal::ASTNode+ +913
[4345449632] *Crystal::CleanupTransformer#transform<Crystal::CleanupTransformer, Crystal::Expressions>:Crystal::Expressions +112
[4345448805] *Crystal::Program#cleanup<Crystal::Program, Crystal::Expressions>:Crystal::Expressions +341
[4337356536] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +2552
[4346334439] *Crystal::Command#run_command<Crystal::Command, Bool>:Nil +151
[4336187718] *Crystal::Command#run<Crystal::Command>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +18774
[4336047297] main +17521

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Version

```
Crystal 0.18.2 (2016-06-17)
```

**Comment by jhass** [comment] 2016-07-06 18:55
Got this for triage, still reproduces on HEAD.

**Comment by asterite** [comment] 2016-07-06 19:05
Yeah, I didn't fix it yet because I don't know if this should be fixed, or if declaring a constant inside another constant should be an error. I don't see a very strong reason to allow that.

**Comment by jhass** [comment] 2016-07-06 19:27
We allow `a = b = 1`, it would only be consistent.

**Comment by asterite** [comment] 2016-07-16 22:05
The thing is that constants are only type-checked when you use them. This makes it possible to omit some constants in the final binary. For example if you don't use `ARGF` then it's never created.

But when you define a constant inside another constant, this constant doesn't exist unless you use the first constant.

Because I don't think defining constants in this way is super useful (in fact I don't know why there would be a reason to have two constants with the same value, defined one after the other), I think I'd prefer this to be a compile-time error.

**Comment by aaronbronow** [comment] 2017-01-09 23:21
This makes sense to me. Can this issue be closed?

**Comment by mverzilli** [comment] 2017-01-10 00:06
I'd rather make it a compile error than leaving it as a compiler error. It does no harm to leave it open :).

**Comment by straight-shoota** [comment] 2022-10-05 11:32
Could the compiler just transform `A = B = 1` into `B = 1; A = B`. I would presume that's semantically equivalent?
But I figure it could work as a general rule: When encountering a const assignment inside the assignment to a const, pull out the inner assignment and but it before the outer assignment, replacing it with a reference to the constant in its original place.
That should also work for the first example:
```cr
BAR = 1
FOO = begin
  BAR
end

puts FOO
```

I don't see huge use case for that though.
And maybe it's a bit odd to be coherent with the rest of the language syntax?

**Comment by caspiano** [comment] 2022-10-05 18:16
That would also work for this case as well.

```crystal
FOO = (BAR = 1)
```

Here's another issue that I have noticed that I'll spin into another issue, but programs with a constant declaration in an exception handler [also cause a crash](https://carc.in/#/r/dutz). This class of errors won't be resolved by the transform step.

```crystal
FOO = begin
  1
rescue
  BAR = 1
end

puts FOO
```

**Comment by straight-shoota** [comment] 2022-10-05 20:43
I would think the instructions should transform that code into this:
```cr
BAR = 1
FOO = begin
  1
rescue
  BAR
end
```

**Comment by straight-shoota** [comment] 2022-10-05 20:55
So it's probably good to just error early in the parser whenever a const assignment is in a place where it doesn't belong.

Maybe a good definition is to say constant assignments are only allowed directly in the scope of a type (including the top-level). Grouping of exceptions with parenthesis or `begin; end` is allowed, though (because that works currently). 
Or in other terms, the parent node of a const assignment must be a `ClassDef` or `ModuleDef`, with only zero ore more `Expressions` allowed in between. I think enum members are already handled separately.

**Closed** 2022-11-16 10:21 UTC
Labels: kind:bug, topic:compiler, community:help-wanted
