### ISSUE TITLE
Self-referential type declaration causes "Module validation failed:  Function return type does not match operand type of return inst!

### ISSUE THREAD

**Issue by BrucePerens** [crystal-lang/crystal#9708] opened 2020-08-28 19:45 UTC
I was experimenting with how to write an array type that can contain its own type, and hit an internal compiler bug check. Yes, I know this could never work.
```crystal
alias ArrayValue = Array(ArrayValue)
class MyArrayType < Array(ArrayValue)
end
x = MyArrayType.new
p x
x << x
```
The compiler emits:
```
Module validation failed: Function return type does not match operand type of return inst!
  ret i32* %1, !dbg !11
 %"Array(ArrayValue)"* (Exception)
  from ../../../../../crystal/src/int.cr:1091:11 in 'finish'
  from ../../../../../crystal/src/compiler/crystal/codegen/codegen.cr:69:7 in 'codegen'
  from ../../../../../crystal/src/compiler/crystal/compiler.cr:172:16 in 'compile'
  from ../../../../../crystal/src/compiler/crystal/command.cr:295:3 in 'run'
  from ../../../../../crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from ../../../../../crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```
Crystal version:
```
Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment] 2020-08-28 20:00
I'm on mobile now but if you search for an issue about alias without a base case you'll find this is a duplicate

**Comment by asterite** [comment] 2020-08-28 20:22
Duplicate of #3804

**Closed by asterite** 2020-08-28 20:22 UTC
