### ISSUE TITLE
Cannot use `as` on anything unioned with a pointer type

### ISSUE THREAD

**Issue by icy-arctic-fox** [crystal-lang/crystal#13000] opened 2023-01-24 22:23 UTC
The `as` method can't be used on a union when one of the types is a pointer.

The following doesn't compile:

```crystal
a = Pointer(UInt8).new(1) || 2
p! typeof(a), a
b = a.as(Pointer(UInt8))
p! typeof(b), b
```

Gives the error:

```text
 3 | b = a.as(Pointer(UInt8))
         ^
Error: can't cast (Int32 | Pointer(UInt8)) to Pointer(UInt8)
```

Crystal 1.7.2

**Comment by Blacksmoke16** [comment] 2023-01-24 22:31
Related to/duplicate of #9281?

**Comment by beta-ziliani** [comment] 2023-01-24 22:42
Definitively a duplicate

**Closed by beta-ziliani** 2023-01-24 22:42 UTC
Labels: kind:bug, topic:compiler:semantic
