### ISSUE TITLE
Class containing an instance variable of alias of itself type crash the compiler

### ISSUE THREAD

**Issue by TobiasGSmollett** [crystal-lang/crystal#4131] opened 2017-03-12 04:19 UTC
The following code will cause the compiler to crash:
```crystal
class A(T)
  alias B = C(T) 
  
  class C(T)
    @c : B = C.new
  end
end
```

Compiler output:

```
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-lang-20170307-71421-gdahpp/crystal-0.21.1/src/compiler/crystal/types.cr:1361
0x10e434681: *raise<TypeCastError>:NoReturn at ??
0x10f11d102: *Crystal::TypeParameter#solve<Crystal::Type+>:Crystal::ASTNode+ at ??
0x10f11e056: *Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::Type+>:Crystal::Type+ at ??
0x10f11856f: *Crystal::TypeDeclarationProcessor#process_owner_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::TypeDeclarationWithLocation>:Nil at ??
0x10f0e5a9c: *Crystal::TypeDeclarationProcessor#process<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor) at ??
0x10efadd28: *Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor) at ??
0x10efaa8c2: *Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+ at ??
0x10faeb125: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x10fb921c9: *Crystal::Command#run_command<Bool>:Nil at ??
0x10e3abf73: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x10e37276d: main at ?
```

Crystal compiler version: ```Crystal 0.21.1```, OS: ```Mac OS X```

**Comment by MakeNowJust** [comment] 2017-03-12 12:56
smallify

```crystal
class A(T)
  alias B = A(T)

  class C
    @c : B
  end
end
```

**Comment by asterite** [comment] 2017-03-23 19:55
@TobiasGSmollett Thank you!

Closing as duplicate of #3502 because the symptoms are the same (the compiler crashes for the same reason)

**Closed by asterite** 2017-03-23 19:55 UTC
