### ISSUE TITLE
Warnings on High Sierra related to libssl / libcrypto

### ISSUE THREAD

**Issue by mnshkv** [crystal-lang/crystal#5048] opened 2017-09-27 17:27 UTC
After running `crystal play` I have some warnings:

```
Desktop/mobile/network  master ✔                                          1d  ⍉
▶ crystal play
Listening on http://localhost:8080
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
```

Anything else is working fine (not tested ssl-related functionality). I notice the bug after updating to High Sierra.

Crystal version:

```
▶ crystal -v
Crystal 0.23.1 (2017-09-18) LLVM 4.0.1
```

Installed with homebrew. I also have installed openssl with `brew install openssl`

**Comment by akzhan** [comment] 2017-09-27 18:12
Duplicate of #4745.

Related to #4676.

**Closed** 2017-09-27 19:23 UTC
