### ISSUE TITLE
Bug: uninitialized getters

### ISSUE THREAD

**Issue by vladfaust** [crystal-lang/crystal#5292] opened 2017-11-14 19:28 UTC
1. https://carc.in/#/r/3349

```crystal
class Foo
  getter foo = uninitialized String
end
```

Output:

```
Syntax error in expanded macro: getter:4: unexpected token: =

           def foo = uninitialized String
```

2. https://carc.in/#/r/334a

```crystal
class Foo
  getter foo : String = uninitialized String
end
```

Output:

```
in macro 'getter' expanded macro: macro_77788480:113, line 4:

   1.       
   2.         
   3.           
>  4.             @foo : String = uninitialized(String)
   5. 
   6.             def foo : String
   7.               @foo
   8.             end
   9.           
  10.         
  11.       
  12.     

undefined method 'uninitialized'
```

The same with `property`. I assume it's a bug.

**Comment by straight-shoota** [comment] 2017-11-14 21:45
It's not really a bug, but the error message could probably be improved.

First of all, instance variables cannot be `uninitialized`, you can't do `@foo = unintialized String`. So, obviously, `getter foo : uninitialized String` is also invalid.

However, since it does not apply here, the compiler doesn't treat `uninitialized` as a keyword at this place - as it can only be used with local variables - and treats it as a method call.

I guess the compiler should probably recognize the keyword and raise an error that you can't use it here.

**Comment by vladfaust** [comment] 2017-11-14 22:01
@straight-shoota,

> you can't do @foo = unintialized String

I certainly can and I heavily use it in my code.

**Comment by ysbaddaden** [comment] 2017-11-15 08:25
`uninitialized` is a keyword, not a method. Remove parenthesis maybe?

**Comment by straight-shoota** [comment] 2017-11-15 08:56
@ysbaddaden Yeah, that should resolve the immediate failure.

But I'm actually surprised that you can have uninitialized instance variables. This seems really weird as it's just an open invitation to explode someplace when an uninitialized ivar is accessed.

@vladfaust Is there a valid use case for this? Having a nilable ivar with `getter!` should be mostly equivalent (at least when used with an accessor) and a failed nil assertion can be rescued instead of an invalid memory access which just blows up.

**Comment by ysbaddaden** [comment] 2017-11-15 10:20
Valid use case: a buffer?

**Comment by monouser7dig** [comment] 2017-11-15 14:38
@straight-Shoota
Is getter! documented somewhere?

**Comment by straight-shoota** [comment] 2017-11-15 14:54
Okay, I see how it is used in stdlib. However, this is for very low level stuff, and an uninitialized instance variable should probably not be exposed by a simple getter method because you need to keep track if it has been initialized or not.

So, I'd still say, while having an uninitialized ivar can be valid for some low level implementation, it should not be possible to use it with a getter because this can very easily lead to breaking code.

@monouser7dig https://crystal-lang.org/api/0.23.1/Object.html#getter%21%28%2Anames%29-macro

**Comment by vladfaust** [comment] 2017-11-15 15:01
@straight-shoota I agree with you. `getter!` seems more appropriate for high-level programming.

**Comment by monouser7dig** [comment] 2017-11-15 15:26
@straight-shoota thanks, looking forward to searchable docs!

**Comment by RX14** [comment] 2017-11-18 14:27
You can have a method called uninitialized, and this will actually work. I don't think we'll change that, so I'm closing as not a bug.

**Closed by RX14** 2017-11-18 14:27 UTC

**Comment by vladfaust** [comment] 2017-11-18 14:49
@RX14 could you please provide an example?

**Comment by RX14** [comment] 2017-11-18 19:35
@vladfaust https://carc.in/#/r/343f

The first example doesn't work still though, since `foo = uninitialized Type` gets parsed as an `UninitializedVar` node, while `foo : Type = uninitialized Type` gets [arsed as a typedeclaration.
