### ISSUE TITLE
Compiler Error: Module validation failed: Call parameter type does not match function signature!

### ISSUE THREAD

**Issue by rishavs** [crystal-lang/crystal#7253] opened 2019-01-02 20:42 UTC
The error message is;
```
Module validation failed: Call parameter type does not match function signature!
  %83 = load i8, i8* %82, !dbg !25
 %"Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32)"*  %84 = call %"Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32)"* @"*Hash(String, Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32) | String)@Hash(K, V)#[]=<String, Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32)>:Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32)"(%"Hash(String, Hash(String, Int16 | Int32 | Int64 | String | Time | UInt32) | String)"* %47, %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'data'" to %String*), i8 %83), !dbg !24
 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

The error comes during casting types when fetching postgres db data.
my table contains a JSONB field with a sample data tags = `{"nature":5, "news":7 }`

Doing this throws the error;

```
post = DB.query_one? "select unqid, tags, created_at from posts where unqid = $1", post_id, 
                    as: {unqid: String, tags: Hash(String, Int32), created_at: Time}
```
Changing Hash(String, Int32) to JSON::Any fixes the issue but the compiler should handle this error gracefully and give a much more user friendly message.

**Comment by RX14** [comment] 2019-01-03 14:05
Duplicate of https://github.com/crystal-lang/crystal/issues/6997

**Closed by RX14** 2019-01-03 14:05 UTC
