### ISSUE TITLE
Types Conformity

### ISSUE THREAD

**Issue by begin29** [crystal-lang/crystal#4818] opened 2017-08-10 11:16 UTC
Hey there, interesting bug appeared 
```
hash = {"start_date"=>"2016-03-01", "value"=>0.0}
puts hash["start_date"].class # String
puts Time.parse("2016-03-01", "%F") # 2016-03-01 00:00:00
Time.parse(hash["start_date"], "%F") # crash Couldn't find overloads for these types: Time.parse(time : Float64, pattern : String)
```
why it thinks that hash["start_date"] is a Float64? because it is a String 

Crystal 0.23.1, Ubuntu 15.04

**Comment by lbguilherme** [comment] 2017-08-10 11:20
hash there will be of type `Hash(String, String|Float64)` meaning the keys are strings and the values are either String or Float64. Hash does not keep track of the specific type of each key, it does that so that you can add keys at runtime.

Note that `hash["start_date"].class` says only String because it is evaluated at runtime, and it checks the dynamic type or the type union.

For what you want it would be better to use a NamedTuple:

```cr
namedtuple = {start_date: "2016-03-01", value: 0.0}
puts namedtuple["start_date"].class # String
puts Time.parse("2016-03-01", "%F")
Time.parse(namedtuple["start_date"], "%F")
```

It will keep track of the exact type of each key. But it happens to be immutable (you can't add/remove keys like you do with Hash).

**Comment by bew** [comment] 2017-08-10 11:39
Note: you can see the actual type of the hash's value using `typeof`:
```cr
hash = {"start_date"=>"2016-03-01", "value"=>0.0}
puts typeof(hash["start_date"]) # Float64 | String
```

**Comment by begin29** [comment] 2017-08-10 12:06
@lbguilherme, tnx for answer. 
is it possible to exact say that values of hash would be always strings?

**Comment by jhass** [comment] 2017-08-10 13:16
What do you mean with say? Define or find out?

For the latter just look at the output of `typeof`, either for something that returns the hash or something that returns a value of it.

For the latter you ideally define the type is `Hash(String, String)`,  say your initial example would've used `{"start_date"=>"2016-03-01", "value"=>"0.0"}`, then Crystal would infer it to that, you could also say `{"start_date"=>"2016-03-01", "value"=> 0.0} of String => String` which should throw an error as long as you keep the `0.0` in there. Finally if for some reason you can change the initial type of the hash but are certain that some value is a `String` you can cas't it like so: `hash["start_date"].as(String)`.

Of course using a `NamedTuple` or a custom struct (see the `record` macro) is preferable to all of that.

**Comment by Fryguy** [comment] 2017-08-11 18:17
In this case, I'd go with a NamedTuple as @lbguilherme says, but if you aren't able to you, and if you're saying you want to always retrieve them as strings, you can .tack a to_s onto the end of it, which ensures it is the String type.

```crystal
> Time.parse(hash["start_date"], "%F")
no overload matches 'Time.parse' with types (Float64 | String), String
> Time.parse(hash["start_date"].to_s, "%F")
# => 2016-03-01 00:00:00
```

**Comment by asterite** [comment] 2017-09-10 14:49
Closing because not a bug

**Closed by asterite** 2017-09-10 14:49 UTC
Labels: kind:question
