### ISSUE TITLE
Segfault at runtime when error at compile time would be better

### ISSUE THREAD

**Issue by Vici37** [crystal-lang/crystal#5813] opened 2018-03-12 04:36 UTC
Hello Crystal community! Long time reader, first time caller:

This is tangentially related to #5679, where I was experimenting with the same macro for subclasses. This code compiles and runs successfully:
```
abstract class A
  abstract def name : String

  def self.subclasses
    {{@type.subclasses}}
  end
end

abstract class B < A
end

class C < B
  def name
    "C"
  end
end

A.subclasses.each do |sub|
  puts sub.new.name
end
```

However, output is a single line "C", when `sub` is `B`. I suspect some inference is going on here, but I don't fully follow the logic on why printing "C" is preferable when `B` has a single child class. When modified to:

```
abstract class A
  abstract def name : String

  def self.subclasses
    {{@type.subclasses}}
  end
end

abstract class B < A
end

class C < B
  def name
    "C"
  end
end

class D < B
  def name
    "D"
  end
end

A.subclasses.each do |sub|
  puts sub.new.name
end
```
A segfault occurs at runtime with a very unhelpful stacktrace (can be included upon request). Adding an implementation of `name` to `B` fixes the issue at runtime, but it's difficult to track that down as the problem in the first place with the segfault exception not helping any. This is something I feel the compiler is better suited for finding and raising an issue about rather than using the inference logic as seen above.

```
> crystal -v
Crystal 0.24.1 (2017-12-22)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
Running on an antiquated Linux Mint 17 laptop :)

**Comment by bew** [comment] 2018-03-12 05:15
Right, I think it should tell you that there is no `new` for `B` or sth like that

**Comment by asterite** [comment] 2018-07-22 22:29
Duplicate of https://github.com/crystal-lang/crystal/issues/3835

**Closed** 2018-07-23 09:59 UTC
