### ISSUE TITLE
Dir.glob doesn't work well with some patterns

### ISSUE THREAD

**Issue by efi** [crystal-lang/crystal#3020] opened 2016-07-20 18:01 UTC
The functioning of Dir.glob / Dir[] is a bit shady to me... In #1754 already some tweaks were implemented, but the process seems to be more complex. When I compare Ruby 1.9.3 and 0.18.6:

R: `Dir[""] => []`
C: `Dir[""] => []`

R: `Dir["/"] => ["/"]`
C: `Dir["/"] !!!`

```
Empty glob pattern (ArgumentError)
[4389063] *CallStack::unwind:Array(Pointer(Void)) +87
[4388954] *CallStack#initialize:Array(Pointer(Void)) +10
[4388906] *CallStack::new:CallStack +42
[4374392] *raise<ArgumentError>:NoReturn +24
[4470509] *Dir::glob2regex<String>:Regex +109
```

R: `Dir["/*"] => ["/backup", "/bin", "/boot", ..., "/var", "/vmlinuz"]`
C: `Dir["/*"] => ["/backup", "/bin", "/boot", ..., "/var", "/vmlinuz"]`

R: `Dir["/*/"] => ["/backup", "/bin", "/boot", ..., "/var"]`
C: `Dir["/*/"] => ["/backup", "/bin", "/boot", ..., "/var"]`

R: `Dir["////*"] => ["////backup", "////bin", "////boot", ..., "////var", "////vmlinuz"]`
C: `Dir["////*"] !!! - takes seconds - & takes forever with more "/"es prepended!`

R: `Dir["/*/*/"].size => 608`
C: `Dir["/*/*/"].size => 637`

R: `Dir["/*/*/"].uniq.size => 607`
C: `Dir["/*/*/"].uniq.size => 637`

EDIT: More patterns that don't work well (copied from #5118):

```crystal
# Works as expected:
Dir["/home"] #=> [ "/home" ]
Dir["/home/../*"] #=> [ "/home/../usr", "/home/../bin", ... ]

# Breaks:
Dir["/home/.."] #=> [ ], but expected ["/home/.."]
Dir["/home/*/.."] #=> [ ], but expected ["/home/papierkorb/.."]

# Raises "empty glob pattern"
Dir["/"] #=> ?!
```

When I searched a fix for the ArgumentError, I stumbled upon https://github.com/crystal-lang/crystal/blob/6ccfb690eef31fdf3ca8ec8e9d3cb11afafc4883/src/dir/glob.cr#L109 where (amongst another check, that I do not unserstand) the String pattern argument is compared to a Char separator constant - which will always be false.

Could someone please look into that issues?

Thanks a lot!

**Comment by david50407** [comment] 2016-07-20 18:14
@asterite  related to https://github.com/crystal-lang/crystal/issues/3019 ?

**Comment by efi** [comment] 2016-07-20 18:18
Indeed!

alert IRC user vs. lazy bug reporter:
1:0

:smile:

**Comment by asterite** [comment] 2016-07-20 20:10
Yup, duplicate of #3019, I created the issue after seeing it on IRC. Thanks for reporting this, anyway :-)

**Comment by jhass** [comment] 2016-07-20 20:12
Well, the last three examples are not covered by #3019

**Comment by asterite** [comment] 2017-10-14 13:35
`Dir.glob` is a bit buggy, and probably slow because it uses regex (and maybe even a bit slow because `Dir` returns strings instead of file info which can already tell if something is a dir or not, avoiding many system calls). This should be re-written from scratch, without regex, and possibly avoiding extra syscalls (but for that `Dir.each` and others probably need to change to return a file info struct).

**Closed** 2018-01-11 18:32 UTC
Labels: kind:bug, topic:stdlib
