### ISSUE TITLE
Add non-ASCII case conversion to String#upcase/downcase/swapcase/capitalize

### ISSUE THREAD

**Issue by deepj** [crystal-lang/crystal#2889] opened 2016-06-21 18:35 UTC
It's same issue as in Ruby. See https://bugs.ruby-lang.org/issues/10085 and https://github.com/ruby/ruby/blob/trunk/NEWS

Basically, the current implementation of case conversion strings is currently limited to ASCII characters. 

Now (Crystal 0.18.2, note note lower-case ü):
```
 "Türkiye".upcase # =>  TüRKIYE
```

Would be:

```
"Türkiye".upcase # =>  TÜRKIYE
```

**Comment by asterite** [comment] 2016-06-21 18:37
Yes, I think we'll eventually do it, but it's **very hard**.

Duplicate of #1648

**Closed by asterite** 2016-06-21 18:37 UTC

**Comment by deepj** [comment] 2016-06-21 18:38
@asterite Ah, thanks for notice, second duplicate here :)

**Comment by asterite** [comment] 2016-06-21 18:39
@deepj No worries about duplicates, sometimes they are hard to find because different words are used. Duplicates mean there's interest on those issues so they help :-)
