### ISSUE TITLE
bug in the Crystal compiler

### ISSUE THREAD

**Issue by dygov** [crystal-lang/crystal#10833] opened 2021-06-18 19:19 UTC
Hello!

I am trying to write a small class, such as a map, that will allow me to "store" an object with an array in a hash. I have an error:

ERROR: called create_llvm_type for K (exception)
    from ???
    ...
Error: You encountered a bug in the Crystal compiler. Please open the issue, including the source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

Below is the part of the code that throws the error:

```crystal
class ConnTable
  getter arrWaiter = Set(Int32).new
  setter arrWaiter
  getter arrCustomer = Set(String).new
  setter arrCustomer
end


class HashArray(K, V)
  @hash = Hash(K, Int32).new
  @arrData = Array(V | Nil).new
  @arrKey = Array(K | Nil).new
  @hashFreeIndex = Hash(Int32, Nil).new
end

class HashArray2(K, V) < HashArray(K, V)
end

ha = HashArray(UInt32, ConnTable).new    # Ok
ha = HashArray2(UInt32, ConnTable).new    # Error
```

Regards,
Artur Dygov

**Comment by Blacksmoke16** [comment] 2021-06-18 19:23
Duplicate of https://github.com/crystal-lang/crystal/issues/9751?

**Comment by asterite** [comment] 2021-06-18 20:00
Yes, seems like a duplicate

**Closed by asterite** 2021-06-18 20:00 UTC

**Comment by HertzDevil** [comment] 2021-06-21 01:10
This is rather a duplicate of #4753 and has been fixed on master.
