### ISSUE TITLE
Proc that receives any argument type

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#3147] opened 2016-08-12 18:07 UTC
Is it possible to create a Proc, that receives any type of argument?

Something like this:
```crystal

proc = ->(arg : EverySingleType) {
  puts "arg is: #{arg}"
}

def num
  yield 25
end

def string
  yield "hello"
end

num &proc # This should be okay
string &proc # This should be okay too
```

Am I missing something?

**Comment by jhass** [comment] 2016-08-12 18:43
No, that's currently a limitation of the language.

Closing as a duplicate of #2733.

**Closed by jhass** 2016-08-12 18:43 UTC
