### ISSUE TITLE
Type checker: subclasses inside generics aren't treated as subclasses

### ISSUE THREAD

**Issue by mattrberry** [crystal-lang/crystal#10138] opened 2020-12-26 19:47 UTC
_Feel free to update the title of this issue_

Compiler version: 0.35.1
Operating system: Ubuntu 20.04

### Minimal Example

```crystal
def foo : Array(Int)
  [] of Int32
end

foo
```

```
 1 | def foo : Array(Int)
               ^
Error: method must return Array(Int) but it is returning Array(Int32)
```
### Another Example

This isn't just with Int, Array, or other builtin types. Another example:

```crystal
class A(T)  ; end
class B     ; end
class C < B ; end

def foo : A(B)
  A(C).new
end

foo
```

```
 5 | def foo : A(B)
               ^
Error: method must return A(B) but it is returning A(C)
```

### Note

The expected behavior here is up to the language designers. This works in TypeScript and mypy, but fails in Java.

```ts
class A<T> {}
class B {}
class C {}

function foo(): A<B> {
    return new A<C>();
}

foo();
```

```java
class Main {
    public static class A<T> {}
    public static class B {}
    public static class C extends B {}

    public static A<B> test() {
        return new A<C>();
    }   

    public static void main(String[] args) {
        test();
    }   
}
```

```
Main.java:7: error: incompatible types: A<C> cannot be converted to A<B>
        return new A<C>();
               ^
1 error
```

**Comment by straight-shoota** [comment] 2020-12-26 20:03
Duplicate of #3803

**Closed by straight-shoota** 2020-12-26 20:03 UTC

**Comment by mattrberry** [comment] 2020-12-26 20:06
Missed that one when I searched 👍
