### ISSUE TITLE
case and type-based pattern matching sometimes matches the wrong type

### ISSUE THREAD

**Issue by davidgiven** [crystal-lang/crystal#4303] opened 2017-04-17 10:13 UTC
Here's the test case:

```crystal
require "spec"

abstract class RootClass; end
class Class1 < RootClass; end
class Class2 < RootClass; end
class Class3 < RootClass; end

describe "case" do
  it "exhibits odd behaviour" do
    o = Class3.new
    case o
    when Class1 | Class2
      fail "o is Class3, this shouldn't match"
    when Class3
      # correct match
    end
  end
end
```

What's obviously happening is that because `Class1` and `Class2` are both subclasses of `RootClass`, then `Class1 | Class2` is being widened to `RootClass` rather than creating a new alternation type, and so it's matching the instance of `Class3` based on its superclass. Using `,` instead of "|", or changing the order of the `when` clauses, or using separate `when` clauses for `Class1` and `Class2` all cause the expected behaviour.

**Comment by asterite** [comment] 2017-05-20 16:24
Duplicate of #2661 or at least very related and it has to do with how types are combined. Use separate `when` clauses for this.

**Closed by asterite** 2017-05-20 16:24 UTC

**Comment by davidgiven** [comment] 2017-05-21 18:13
After thinking about it some more: this is catastrophically broken.

What's wrong here is that `case` behaviour now depends on implementation details of the class hierarchy of the types I'm matching against. If I've imported these types from I library I may not know this --- I certainly shouldn't have to care about it. If the library author rearranges the type hierarchy, the previously working code will stop working. What's worse, this all happens *silently*: there are no diagnostics, no warnings --- what happens is that the wrong clause of the `case` statement fires. I discovered this in real life code which was misbehaving obscurely. That's really bad.

If there isn't a near-term fix in the type system for this, then you need to change the way `case` works not to allow code like in my example. If I've understood it correctly, then forbidding `|` combinations where the classes share an ancestor ought to do it.
