### ISSUE TITLE
Cannot downcast nested iterators to non-nilable

### ISSUE THREAD

**Issue by nickbclifford** [crystal-lang/crystal#5363] opened 2017-12-08 00:39 UTC
I was trying to write some code in my Kemal project and noticed that I kept getting this error:

```
nick@2020-S20040:/mnt/c/Users/nclifford/Desktop/nickclifford.me-v2$ crystal index.cr
BUG: trying to downcast (Iterator::Zip(Iterator::Cycle(Indexable::ItemIterator(Array(String), String), String), Hash::EntryIterator(Time, Int32), String, Tuple(Time, Int32)) | Nil) <- Iterator::Zip(Iterator::Cycle(Indexable::ItemIterator(Array(String), String), String), Hash::EntryIterator(Time, Int32), String, Tuple(Time, Int32))
0x5bb9fe: ??? at ??
0xcfdd74: ??? at ??
0xd4f4e9: ??? at ??
0xd16a69: ??? at ??
0xd35612: ??? at ??
0xd1a432: ??? at ??
0xd3bf31: ??? at ??
0xd367b6: ??? at ??
0xd1a432: ??? at ??
0xd1762e: ??? at ??
0xd18f06: ??? at ??
0xd16b69: ??? at ??
0xd1b769: ??? at ??
0xd1b769: ??? at ??
0xd16b69: ??? at ??
0xd36f7f: ??? at ??
0xd1a432: ??? at ??
0xd16b69: ??? at ??
0xd36f7f: ??? at ??
0xd1a432: ??? at ??
0xd2fc41: ??? at ??
0xd170b4: ??? at ??
0xd16b69: ??? at ??
0xd3c2d4: ??? at ??
0xd367b6: ??? at ??
0xd1a432: ??? at ??
0xd16b69: ??? at ??
0xd29913: ??? at ??
0xd173ad: ??? at ??
0xd3683b: ??? at ??
0xd1a432: ??? at ??
0xd16b69: ??? at ??
0xcd7cdb: ??? at ??
0x102b0e5: ??? at ??
0x1098cbe: ??? at ??
0x611436: ??? at ??
0x5e1dac: main at ??
0x7f6763350830: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

I'm running Crystal 0.23.1 on Bash on Ubuntu on Windows.

Unfortunately, I wasn't able to reproduce this on a smaller scale, so I'll just link to the bugs in my project: [controller](https://github.com/nickbclifford/nickclifford.me-v2/blob/master/index.cr#L48) and [view](https://github.com/nickbclifford/nickclifford.me-v2/blob/3435cfe81f849458a61ce809d7450285c18d9595/index.cr#L48). Thanks a ton for your help!

**Comment by RX14** [comment] 2018-01-20 11:36
Was this fixed?

**Comment by straight-shoota** [comment] 2020-12-05 10:54
CLosing. A lot of time has passed and the issue isn't easily reproducible without porting that code to current Crystal and shard versions.

**Closed by straight-shoota** 2020-12-05 10:54 UTC
