### ISSUE TITLE
check class inheritance

### ISSUE THREAD

**Issue by adraenwan** [crystal-lang/crystal#3837] opened 2017-01-04 15:25 UTC
```crystal
class A
end

class B < A
end

b = B.new
puts b.class < A

# ruby => true
# crystal => in test.cr:8: undefined method '<' for B:Class
```
It would be really useful to be able to check class inheritance at runtime.

**Comment by asterite** [comment] 2017-01-04 15:27
Duplicate of #2060

**Closed by asterite** 2017-01-04 15:27 UTC
