### ISSUE TITLE
UNIXServer does not delete socket file on destruction

### ISSUE THREAD

**Issue by Bew78LesellB** [crystal-lang/crystal#3763] opened 2016-12-24 03:13 UTC
```crystal
require "socket"

def check_file(prefix, file)
  if File.exists? file
    puts "#{prefix} File exists"
  else
    puts "#{prefix} No file"
  end
end

path = "/tmp/unixtest_cr.sock"

check_file "1/", path
UNIXServer.new(path)
begin
  check_file "2/", path
  UNIXServer.new(path)
rescue err
  puts "Error raised !"
  puts
  check_file "Final/", path
  puts "Error was: #{err.message}"
end
```
Exemple run with carc.in using Crystal 0.20.1 : https://carc.in/#/r/1hp3
```
1/ No file
2/ File exists
Error raised !

Final/ No file
Error was: Error binding UNIX server at /tmp/unixtest_cr.sock: Address already in use
```
Exemple run on master, using Crystal 0.20.3 : 
```
Using compiled compiler at .build/crystal
1/ No file
2/ File exists
Error raised !

Final/ No file
Error was: bind: Address already in use
```

I'm expecting the output to be : 
```
1/ No file
2/ No file
```

I'm on Archlinux, kernel 4.8.13
@ysbaddaden you worked on this, any idea ? (Btw, awesome work on the sockets 👍)

**Comment by Bew78LesellB** [comment] 2016-12-24 03:56
It seems that there is no destructor, which could allow to close the socket..

It is not documented, but I think we can do this using [GC#add_finalizer](https://crystal-lang.org/api/0.19.2/GC.html#add_finalizer(object)-class-method), but I didn't find any usage of it..

**Comment by ysbaddaden** [comment] 2016-12-24 11:45
This is by design. You must either explicitly close the socket using `#close` or using the `.open` constructor, that will eventually close it.

The `IO::FileDescriptor` ancestor should already have a finalize that will call `#close`, but that will only happen when GC collects the memory.

**Comment by Bew78LesellB** [comment] 2016-12-24 15:44
Does the GC collects memory on program exit ?

So does the finalize functions get called on program normal quit (not crashed) ?

**Comment by ysbaddaden** [comment] 2016-12-24 18:15
> Does the GC collects memory on program exit ?

No, the OS will already to the cleaning (allocated memory, opened sockets, ...). Yet, it won't delete the socket created by UNIXServer. You may tell it to, thought:

```crystal
server = UNIXServer.new("/tmp/service.sock")
at_exit { server.close }
```

**Comment by ysbaddaden** [comment] 2016-12-24 18:32
`IO::FileDescriptor`'s finalizer does call `close`, so the socket file is eventually deleted when the object is collected by the GC. One should use the following examples (there are other solutions) to have better control over when the file is actually deleted.

```crystal
UNIXServer.open("/tmp/my.sock") do |server|
  # ...
end

server = UNIXServer.new("/tmp/my.sock")
at_exit { server.close }
```

**Closed by ysbaddaden** 2016-12-24 18:32 UTC

**Comment by Bew78LesellB** [comment] 2016-12-24 19:29
Thanks it's clear now!
