### ISSUE TITLE
Regex global capture

### ISSUE THREAD

**Issue by plukevdh** [crystal-lang/crystal#2223] opened 2016-02-24 20:07 UTC
After a fair bit of research, I realize that PCRE doesn't contain the `g` flag for global matching. However, this is a super useful feature to have with any Regex library. Moreover, with your `post_match` method in [`MatchData`](https://github.com/crystal-lang/crystal/blob/master/src/regex/match_data.cr#L187), this is a simple thing to implement:

```crystal
def global_captures
  captures = [] of String
  loc_string = @string.dup

  while capture = loc_string.match(@regex)
    captures << capture[1] if capture[1]?
    loc_string = capture.post_match
  end

  captures
end
```

If this idea is worthwhile, it probably belongs somewhere in `Regex` rather than `MatchData` but I'm not sure where it would reside. Any thoughts on including this as some part of the regex implementation in Crystal?

**Comment by asterite** [comment] 2016-02-24 20:13
I'm not sure I understand your problem (it would help if you can attach some code that shows the usage you want to achieve, how you do it right now and how it would get better), but is [String#scan](http://crystal-lang.org/api/String.html#scan%28pattern%3AString%29-instance-method) what you are looking for?

As a side note, strings are immutable in Crystal, so there's no need to invoke `dup`.

**Comment by plukevdh** [comment] 2016-02-24 20:33
```crystal
def gmatch(str, regex)
  captures = [] of String

  while match = regex.match(str)
    captures << match[1]
    str = match.post_match
  end

  captures
end

puts gmatch("/consumers/:username/credentials/:plugin/:credential", /(:\w+)/)
# => [":username", ":plugin", ":credential"] 
puts gmatch("/consumers/:username/credentials/:plugin/:credential", /nine/)
# => []

```

This is what I want to do. Seems I can achieve the same goal by replacing the internals of `gmatch` with `str.scan(regex).map &.[1]`. Seems like this is would be a common operation (to get all matches) so as to have it apart of stdlib? Maybe it's just me... Ruby's Regex has the `//g` option, but it's not based on PCRE.

**Comment by asterite** [comment] 2016-02-24 20:35
```
$ irb
irb(main):001:0> /foo/g
SyntaxError: (irb):1: unknown regexp option - g
```

**Comment by plukevdh** [comment] 2016-02-24 20:45
Oh man, you're right... This must use `scan` under the hood as well: http://rubular.com/: 

http://rubular.com/r/clpoYj9ZvW

however, note that scan returns the matches rather than MatchData: 

```ruby
`"/consumers/:username/credentials/:plugin/:credential".scan /(:\w+)/`
=> [[":username"], [":plugin"], [":credential"]]

"/consumers/:username/credentials/:plugin/:credential".scan(/(:\w+)/).map &:class
# => [Array, Array, Array]
```

tbh, I probably prefer getting MatchData back, just unexpected. Another Ruby => Crystal difference.

**Comment by asterite** [comment] 2016-02-24 20:57
Yes, Ruby is a bit more dynamic here and if the regex has captures, it returns them in arrays. So the possible result type is `Array(String)` or `Array(Array(String))`. But in Crystal if we return that union it becomes harder to use, so we chose to just return `Array(MatchData)` and let the user decide what to do with that.

**Comment by plukevdh** [comment] 2016-02-24 21:23
Fair enough! Thanks for the feedback and patience. Learning and trying to be useful :)

**Comment by jhass** [comment] 2016-02-25 10:55
Looks like the issue is resolved then and we can close this? :)

**Closed** 2016-02-25 12:45 UTC
