### ISSUE TITLE
Random Invalid memory access

### ISSUE THREAD

**Issue by karlseguin** [crystal-lang/crystal#4059] opened 2017-02-22 11:17 UTC
I've been getting these Invalid Memory Access errors on and off for a while now. Was hoping 0.21.0 might fix it, but no. I also can't reproduce it (yet), without most of my (relatively large) project included.

I'm more or less looking for directions on what I should look at or try or anything. The following happens when running our tests. But it only happens when running a group of tests, not this specific test by itself. I realize that would indicate that there's some weird state between our tests, but I honestly believe that it's more likely some weird *internal* crystal state.

```
Invalid memory access (signal 11) at address 0x0
[4350066123] *CallStack::print_backtrace:Int32 +107
[4349863703] __crystal_sigfault_handler +55
[4355360435] sigfault_handler +35
[140736329518010] _sigtramp +26
[140736327863527] snprintf +32
[4350191284] *Float32#to_s_internal<Pointer(UInt8)>:(Int32 | UInt64) +68
[4350192307] *Float32#to_s<IO::Memory>:Nil +659
[4350487278] *IO::Memory@IO#<<<(Float32 | Int32)>:IO::Memory +62
[4355298551] *Project::Query::AvgFloatCell(Project::Tests::Fakes::Any)@Project::Query::AvgCellHelper(T)#write<IO::Memory, Project::Query::Context>:Nil +119
[4349985628] *assert_output_cell<Project::Query::Cell(Project::Tests::Fakes::Any)+, Float32>:Nil +188
```

`assert_output_cell` is doing:

```crystal
def assert_output_cell(cell : OutputCell, expected)
  io = IO::Memory.new()
  cell.write(io) # this is what causes the cell's float value to be written to IO
  io.to_s.should eq(expected.to_s)
  io.close()
end
```

This seems to be crashing when a when we call `io << some_float` in our code. Not sure how that could be related to state in our tests or even accessing released memory or anything like that.

If I change the code a little and add, say `puts "doh"` inside the constructror of that cell, it now crashes a earlier in that same tests:

```
[4493552795] *CallStack::print_backtrace:Int32 +107
[4493349975] __crystal_sigfault_handler +55
[4498847315] sigfault_handler +35
[140736329518010] _sigtramp +26
[4493627144] *Slice(T)::new:read_only<Pointer(UInt8), Int32, Bool>:Slice(UInt8) +24
[4493593625] *String#to_slice:Slice(UInt8) +41
[4493594569] *String#to_s<IO::FileDescriptor>:Nil +25
[4493682504] *IO::FileDescriptor@IO#<<<String>:IO::FileDescriptor +24
[4493682437] *IO::FileDescriptor@IO#puts<String>:Nil +21
[4493352953] *puts<String>:Nil +41
[4498785494] *Project::Query::AvgFloatCell(Project::Tests::Fakes::Any)@Project::Query::AvgCellHelper(T)#initialize<Project::Query::LiteralFloatValue(Project::Tests::Fakes::Any), Project::Tests::Fakes::BoolPredicate>:Nil +70
[4498785413] *Project::Query::AvgFloatCell(Project::Tests::Fakes::Any)@Project::Query::AvgFloatCell(T)::new<Project::Query::LiteralFloatValue(Project::Tests::Fakes::Any), Project::Tests::Fakes::BoolPredicate>:Project::Query::AvgFloatCell(Project::Tests::Fakes::Any) +117
[4493471634] ~procProc(Nil)@spec/query/cells/avg_spec.cr:12 +66
```

It seems to imply my memory is completely messed up.

Could it possibly not be printing the right backtrace (and if so, any way to get the right one?)

**Comment by asterite** [comment] 2017-02-22 11:41
Can you provide some code that we can run to reproduce this error?

**Comment by karlseguin** [comment] 2017-02-22 15:34
Ok..that took a while, but I got something. I'm probably doing something silly. But I *think* it should still not segfault (???)

It's *super* sensitive. If you inline `assert_to_s` so that instead of having each test call it, you just do the same inside the test (`cells.cells[0].write(IO::Memory.new)`), it will pass.  If you don't pass `expected` (a parameter that isn't even used in this distilled version) ...it'll pass.  If I rename `write` to `to_s` and call that instead...it'll pass.

```
module Test
  struct Cells(T)
    getter cells : Array(Cell(T))
    def initialize(@cells) end
  end

  abstract class Cell(T)
    abstract def write(io : IO)
  end

  class SumInt(T) < Cell(T)
    @total = 0
    def write(io : IO)
      io << @total
    end
  end

  class SumFloat(T) < Cell(T)
    @total = 0_f32
    def write(io : IO)
      io << @total
    end
  end

  class AvgInt(T) < Cell(T)
    @total = 0
    @count = 1

    def write(io : IO)
      io << @total / @count
    end
  end

  class AvgFloat(T) < Cell(T)
    @total = 0_f32
    @count = 1

    def write(io : IO)
      io << @total / @count
    end
  end
end

def builder(cell)
  wrap = Array(Cell(Int32)).new(1)
  wrap << cell
  return Cells(Int32).new(wrap)
end

def assert_to_s(cell : Cell, expected)
  cell.write(IO::Memory.new())
end

require "spec"

include Test

describe "segfault" do
  it "int literal" do
    cells = builder(AvgInt(Int32).new())
    assert_to_s(cells.cells[0], 5)
  end

  it "float literal" do
    num = 90.0_f32
    cells = builder(AvgFloat(Int32).new())
    assert_to_s(cells.cells[0], num)
  end

  it "filtered true int field" do
    cells = builder(AvgInt(Int32).new())
    assert_to_s(cells.cells[0], 2)
    assert_to_s(cells.cells[0], 2.5)
  end

  it "int literal" do
    cells = builder(SumInt(Int32).new())
    assert_to_s(cells.cells[0],  4)
  end

  it "float literal" do
    cells = builder(SumFloat(Int32).new())
    assert_to_s(cells.cells[0], 90.01_f32)
  end
end
```

/cc @asterite

**Comment by karlseguin** [comment] 2017-02-28 09:15
Still need more info @matiasgarciaisaia ?

**Comment by asterite** [comment] 2017-03-03 18:46
Closing as duplicate of #2665 (generics inheritance is still broken)

**Closed by asterite** 2017-03-03 18:46 UTC
Labels: community:to-research, kind:bug, topic:compiler
