### ISSUE TITLE
Indexable with Range

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#10963] opened 2021-07-19 02:08 UTC
Can these methods be moved to `Indexible`?  It would make other Indexible type classes behave more like Arrays.

https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L573-L657

**Comment by HertzDevil** [comment] 2021-07-19 06:34
Duplicate of #7619.

**Closed** 2021-07-19 12:03 UTC
Labels: kind:feature, status:duplicate
