### ISSUE TITLE
Covariance of Method Return Types?

### ISSUE THREAD

**Issue by timscott** [crystal-lang/crystal#5982] opened 2018-04-21 21:54 UTC
_This is probably already reported, but I'm not clever enough to find the exact issue._

Given two classes:

```crystal
class Foo
end

class Bar < Foo
end
```

This compiles as expected:

```crystal
def do_it(input : Array(Foo))
  input
end

do_it(Array(Bar).new)
```

This fails with `type must be Array(Foo), not Array(Bar)`

```crystal
def do_it_again() : Array(Foo)
  Array(Bar).new
end

do_it_again()
```

It's unclear why covariance is allowed in the method arguments but not the return type. Seems like it must be a bug.

**Comment by asterite** [comment] 2018-04-21 22:00
Duplicate of https://github.com/crystal-lang/crystal/issues/3803

**Closed by asterite** 2018-04-21 22:00 UTC
