### ISSUE TITLE
Bug: trying to downcast Int32? <- Int32

### ISSUE THREAD

**Issue by semenovDL** [crystal-lang/crystal#2531] opened 2016-04-29 09:09 UTC
When try to check property class:
```ruby
class A
  def initialize(values)
    @values = [] of B
  end
  
  def to_s
    if @values.is_a?(Array)
	    @values.map(&.name).join("\n")
	  end
  end
end

class B
  property name
  def initialize(@name)
  end
end

values = ('a'..'z').to_a.map { |s| B.new(s) }
puts A.new(values).to_s
```
Get expection
`Bug: trying to downcast String? <- String`

**Comment by asterite** [comment] 2016-04-29 21:36
@semenovDL Your code works fine: https://play.crystal-lang.org/#/r/xpn

Is the code that giving you the bug different? Otherwise I'll close this in a few days.

**Comment by asterite** [comment] 2016-04-29 21:36
Please also check your crystal version with `crystal --version`

**Comment by semenovDL** [comment] 2016-05-04 10:30
@asterite 
```sh
$crystal --version
Crystal 0.15.0 (Fri Apr  1 17:57:09 UTC 2016)
```
on Mac OS X 10.11.4 (15E65)

**Comment by semenovDL** [comment] 2016-05-04 10:31
I localize the problem:
```ruby
# works fine
str = "" if true
puts str

# fails with trying to downcast String? <- String
def meth
	str = "" if true
end
puts meth
```

**Comment by asterite** [comment] 2016-05-04 11:46
Doesn't happen to me, and it doesn't happen in play: https://play.crystal-lang.org/#/r/xw0

I don't know why it's failing for you. Could you please also try the snippet in play.crystal-lang.org before submitting it here? If it doesn't fail in play there must be something wrong with your crystal installation.

**Comment by semenovDL** [comment] 2016-05-04 13:26
@asterite this snippet work fine in  https://play.crystal-lang.org
So the problem on my side.
I install crystal with brew.

Maybe there is a problem with llvm? I use:
```sh
$clang -v
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Which dependencies (compile time and runtime) crystal use?

**Comment by asterite** [comment] 2016-05-04 15:17
No, I don't think the issue is there. Can you please show output of this:

```bash
crystal --version
which crystal
crystal build foo.cr # assuming foo.cr is your test file
```

**Comment by semenovDL** [comment] 2016-05-04 16:12
```sh
$ crystal --version
Crystal 0.15.0 (Fri Apr  1 17:57:09 UTC 2016)
$ which crystal
/usr/local/bin/crystal
$ crystal build foo.cr --verbose
cc -o "/Users/semenovDL/projects/crystal/foo" "${@}"  -rdynamic  /usr/local/Cellar/crystal-lang/0.15.0/src/ext/libcrystal.a -levent -lpcre -liconv -lgc -lpthread -ldl _main.o UInt64.o Array40Int3241.o String5858Builder.o String.o ArgumentError.o CallStack.o Array40Pointer40Void4141.o Pointer40Pointer40Void4141.o Pointer40LibUnwind5858Exception41.o Exception.o GC.o Slice40T41.o Slice40UInt841.o IO5858Encoder.o StaticArray40UInt84432102441.o Iconv.o Pointer40UInt841.o Errno.o Int32.o IndexError.o Math.o Char.o StaticArray40UInt84432441.o StaticArray40UInt844326541.o DivisionByZero.o Pointer40Int3241.o Random5858MT19937.o StaticArray40UInt324432441.o Random.o Pointer40UInt3241.o StaticArray40UInt32443262441.o UInt32.o Fiber.o Pointer40Void41.o Deque40Fiber41.o Pointer40Fiber41.o Event5858Base.o IO5858FileDescriptor.o IO5858Error.o Scheduler.o LibEvent25858EventFlags.o Event5858Event.o Int64.o Nil.o IO5858Timeout.o Exception43.o Array40String41.o Pointer40String41.o 40Fiber3245623240-1912b1087c9beb04149becc06298e7e2.o Range40B4432E41.o Range40Int324432Int3241.o Array404032456232Nil4141.o Pointer404032456232Nil4141.o Event5858SignalHandler.o IO5858FileDescriptor43.o IO.o StaticArray40Int324432241.o Hash40Signal443240Signal32456232Void4141.o Hash5858StandardComparator.o Signal.o Pointer40Hash5858-53873ca918e49a5155e4e00c1c71dd1e.o Event5858SignalChildHandler.o Hash40Int324432Process5858Status41.o Pointer40Hash5858-5be03dfbff7189de5bb0166c94b5af88.o Hash40Int324432Ch-58936133be82407b4de468047ed7e7dc.o Pointer40Hash5858-9a1110bf3fc45b999f79e9061a2da0d2.o 40Int3232456232Void41.o Hash5858Entry40Signal443240Signal32456232Void4141.o Process5858Status.o Hash5858Entry40Int324432Process5858Status41.o AtExitHandlers.o Array4040Int3232456232Void4141.o Pointer4040Int3232456232Void4141.o LEBReader.o LibUnwind5858Action.o CallStack5858RepeatedFrame.o
```

**Comment by asterite** [comment] 2016-05-04 16:14
And `foo.cr` has the code that fails?

**Comment by semenovDL** [comment] 2016-05-04 16:20
yes

**Comment by asterite** [comment] 2016-05-04 16:23
But the last line shows it compiled well, because if `cc` was reached then it means the type checking succeeded.

**Comment by semenovDL** [comment] 2016-05-04 16:26
Oh, I forgot to write - the problem appear in local crystal playground (using crystal play)

**Comment by asterite** [comment] 2016-05-04 16:28
Yes, that I was able to reproduce :-)

**Comment by asterite** [comment] 2016-05-04 16:42
Reduced:

```crystal
def foo
  yield
end

def bar
  value = yield
  foo do
    if value
    end
  end
  value
end

bar do
  if true
    bar { 1 }
  end
end
```

(outside the playground)

**Closed** 2016-06-13 02:41 UTC
Labels: bug, compiler
