### ISSUE TITLE
Yaml::Any raise error on `.each` if `@raw` is empty

### ISSUE THREAD

**Issue by madeindjs** [crystal-lang/crystal#4028] opened 2017-02-13 13:01 UTC
Consider this small script

```crystal
YAML.parse(File.read(FILE_PATH)).each do |data|
  # blabla
end
```

It will raise an error if the file exists but is empty. 

```
expected Array or Hash for #each, not Nil
0x4c5912: *Task::all:Array(Task) at /home/arousseau/dev/crystal/fikri/src/fikri/task.cr 139:7
0x464e29: ~procProc(Nil) at /opt/crystal/src/spec/expectations.cr 191:7
0x464372: *it<String, String, Int32, Int32, &Proc(Nil)>:(Array(Spec::Result) | Nil) at /opt/crystal/src/spec/methods.cr 17:7
0x46414d: ~procProc(Nil) at /opt/crystal/src/spec/methods.cr 4:5
0x4a5077: *Spec::RootContext::describe<String, String, Int32, &Proc(Nil)>:Spec::Context+ at /opt/crystal/src/spec/context.cr 152:30
0x463e57: *describe<Fikri:Module, String, Int32, &Proc(Nil)>:Spec::Context+ at /opt/crystal/src/spec/methods.cr 4:5
0x4534bc: ??? at /home/arousseau/dev/crystal/fikri/spec/fikri_spec.cr 3:1
0x461949: main at /home/arousseau/.cache/crystal/macro64731920.cr 12:15
0x7ff18c898830: __libc_start_main at ??
0x452449: _start at ??
0x0: ??? at ??
```

The first problem is that line prompted by error is not correct: my task.cr file end at line # 135..

The second problem is that you need to be more verbose. In fact if you check the source code, the `ỲAML::Any` raise an error if it does not contain data

```crystal
# https://github.com/crystal-lang/crystal/blob/d1f8c42f82d3e6491cb7b3b536984c19a51b94ba/src/yaml/any.cr#L128
def each
    case object = @raw
    when Array
      object.each do |elem|
        yield Any.new(elem), Any.new(nil)
      end
    when Hash
      object.each do |key, value|
        yield Any.new(key), Any.new(value)
      end
    else
      raise "expected Array or Hash for #each, not #{object.class}"
    end
end
```
and something like this will not work anymore ..

```crystal
YAML.parse(File.read(FILE_PATH)).each do |data|
  if data
    # blabla
  end
end
```

... because in fact you need to check `@raw` property

```crystal
YAML.parse(File.read(FILE_PATH)).each do |data|
  if data.raw
    # blabla
  end
end
```

So now it works but it demand more code than it should be... I think it will be better to not raise an error and automatically to not loop in the block? For me the first syntax should be correct

What do you think about?

**Comment by asterite** [comment] 2017-02-13 13:17
Looks like a duplicate of #2873

**Comment by madeindjs** [comment] 2017-02-13 13:35
Sorry, I swear I used the search tool! :) But what do you think about just improve `YAML::Any.each` method like this:

```crystal
# https://github.com/crystal-lang/crystal/blob/d1f8c42f82d3e6491cb7b3b536984c19a51b94ba/src/yaml/any.cr#L128
def each
    case object = @raw
    when Array
      object.each do |elem|
        yield Any.new(elem), Any.new(nil)
      end
    when Hash
      object.each do |key, value|
        yield Any.new(key), Any.new(value)
      end
    when Nil
      return nil
    else
      raise "expected Array or Hash for #each, not #{object.class}"
    end
end
```

**Comment by asterite** [comment] 2017-02-13 13:45
I'm not sure. It's almost the same as wanting to add an `each` method to `Nil` so that it will work when you have a `nil` value.

Besides...

```
$ irb
irb(main):001:0> require "yaml"
=> true
irb(main):002:0> YAML.parse("").each {}
NoMethodError: undefined method `each' for false:FalseClass
```

In Ruby you can't iterate an empty YAML file.

What's your use case?

**Comment by madeindjs** [comment] 2017-02-13 14:09
A simple Todo application who save Task in a YAML file. I have a method `Task.all` who iterate on YAML data but I raise an error at the first opening

https://github.com/madeindjs/fikri/blob/feature/refactor/src/fikri/task.cr#L25

**Closed** 2017-02-13 19:06 UTC
