### ISSUE TITLE
Improve confusing error message `undefined method [name] for [class/struct]`

### ISSUE THREAD

**Issue by SamantazFox** [crystal-lang/crystal#11892] opened 2022-03-12 22:38 UTC
## Problem

I recently stumbled upon a compiler error with some code similar to this:
```crystal
struct Test
  def self.foo(str : String)
    pp str
  end
  
  def bar
    foo("baz")
  end
end

x = Test.new
x.bar # Expected to print "baz"
```

Result:
```
Showing last frame. Use --error-trace for full trace.

error in line 7
Error: undefined method 'foo' for Test
```

So I was super confused, as `Test.foo` is indeed a valid (class) method.

After discussing on IRC, blacksmoke16 explained that class and instance methods don't have the same scope, so I can't directly access a class method from an instance of that class. I need to use either of the following:
```
<Class>.<method>
self.class.<method>
```

## Improvement wanted

I'd like to see a more meaningful error message, like that:
```
Error: undefined instance method 'foo' for Test
Maybe you meant to use the class method `Test.foo`?
```

**Comment by HertzDevil** [comment] 2022-03-12 22:43
Duplicate of #10201.

**Closed by HertzDevil** 2022-03-12 22:43 UTC
Labels: topic:compiler, status:discussion
