### ISSUE TITLE
Compiler crashes when it found uninitialized instance vars

### ISSUE THREAD

**Issue by maiha** [crystal-lang/crystal#3600] opened 2016-11-28 02:23 UTC
#### minimum reproduce

```ruby
class Foo
  @a : String = uninitialized
  # @a : String = uninitialized String
end
```

Compiler crashes in both cases although this is 100% user's fault.

```shell
% crystal --version
Crystal 0.20.0 [b0cc6f7] (2016-11-22)

```shell
% crystal test.cr
Nil assertion failed
0x836cfe: *raise<Exception>:NoReturn at ??
0x836c37: ??? at ??
...
Error: you've found a bug in the Crystal compiler.
```

**Comment by asterite** [comment] 2016-11-28 13:14
Duplicate of #3580

This:

```cr
@a : String = uninitialized
```

parses `uninitialized` to a method call. And this:

```cr
@a : String = uninitialized String
```

also parses `uninitialized String` to a method call. So they match the issue in #3580.

The way to use `uninitialized` is:

```cr
@a = uninitialized String
```

But this is confusing... I'll probably make `uninitialized` a reserved keyword that, when used incorrectly, tells you the correct way to use it.

**Comment by asterite** [comment] 2016-11-28 13:54
Actually, I'll just leave it like this, if I change this it breaks some code, for example methods that define an `uninitialized` method, like [here](https://github.com/crystal-lang/crystal/blob/eff31e5fd4b0a070d9ef0ac94b5cd0975765261e/src/compiler/crystal/semantic/ast.cr#L460).

In any case, now this doesn't crash the compiler.

**Closed by asterite** 2016-11-28 13:54 UTC
Labels: compiler, enhancement

**Comment by maiha** [comment] 2016-11-28 14:12
I understood! thanks!
