### ISSUE TITLE
StringLiteral.camelcase does not handle (lower: true) parameter

### ISSUE THREAD

**Issue by wealth** [crystal-lang/crystal#8291] opened 2019-10-08 01:54 UTC
```cr
module A
  macro define_method(decl)
    def {{decl.var.camelcase(lower: true)}}
      puts "does not work!"
    end
  end
end

class Z
  include A
  define_method test_column : String
end

Z.new.testColumn
```
Result:
```
There was a problem expanding macro 'define_method'

Code in test.cr:11:3

 11 | define_method test_column : String
      ^
Called macro defined in test.cr:2:3

 2 | macro define_method(decl)

Which expanded to:

 > 1 | def TestColumn
                     ^
Error: unexpected token: NEWLINE
```
Expected: handles lowercase and defines testColumn method

```
Crystal 0.31.1 [0e2e1d067] (2019-09-30)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by Blacksmoke16** [comment] 2019-10-08 02:29
Duplicate of https://github.com/crystal-lang/crystal/issues/8292?

**Comment by wealth** [comment] 2019-10-08 02:33
yep, sorry for double post

**Comment by straight-shoota** [comment] 2019-10-09 18:01
Reduced:
```cr
{{"foo_bar".camelcase(lower: true)}} # => "FooBar"
```

**Comment by Blacksmoke16** [comment] 2019-10-09 19:27
Do we want to support the same UX?  Currently `named_args` aren't included in the macro method `interpret` method.  It would be doable but might take a bit of work.  If not the syntax would just be like `{{"foo_bar".camelcase(true)}}`.

@straight-shoota @asterite thoughts?

**Comment by asterite** [comment] 2019-10-09 19:37
It's something nice to have, but I know it's a bit tedious to implement.

**Closed** 2019-11-15 18:09 UTC
Labels: kind:feature, topic:lang:macros
