### ISSUE TITLE
Channel.new compilation error

### ISSUE THREAD

**Issue by msa7** [crystal-lang/crystal#5116] opened 2017-10-13 20:24 UTC
My code

```
@ch_done = Channel.new
```

Compailer output

```
cast from Nil to Crystal::GenericInstanceType+ failed, at /var/cache/omnibus/src/crystal/src/compiler/crystal/types.cr:1420:20:1420
0x5da275: ??? at ??
0xc78b82: ??? at ??
0xc7969c: ??? at ??
0xc76a24: ??? at ??
0xc70a93: ??? at ??
0xbc633f: ??? at ??
0xbc0410: ??? at ??
0x102b0b3: ??? at ??
0x60eca2: ??? at ??
0x5e1dac: main at ??
0x7f7c4dbcb830: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment] 2017-10-13 20:32
Duplicate of https://github.com/crystal-lang/crystal/issues/4460

Already fixed in master

**Closed by asterite** 2017-10-13 20:32 UTC
