### ISSUE TITLE
(Child+:Class) type is not convertible to (Base+:Class)

### ISSUE THREAD

**Issue by konovod** [crystal-lang/crystal#3007] opened 2016-07-16 20:39 UTC
Small example (https://play.crystal-lang.org#/r/1437)

    class Base
    end
    class Child < Base
    end
    class Child1 < Child
    end
    class Child2 < Child
    end
    
    $hash = {Base => 1, Child => 1, Child1 => 1, Child2 => 1}
    $hash[Child1] = 0 # compiles ok
    arr = [Child1, Child2]
    $hash[arr[0]] = 1 # instance variable '@key' of Hash::Entry(Base, Int32) must be Base+:Class, not Child+:Class

In addition, I have no idea how to convert Child+:Class to Base+:Class manually, naive way doesn't work:

    alias Needed = (Base.class | Child.class);
    $hash[arr[0].as(Needed)] = 1 # doesn't compiles

There is also another small issue with "constrained metaclasses", they are displayed in a same way as type of instances of that classes : https://play.crystal-lang.org#/r/142o

    class Base
    end
    class Child < Base
    end
    
    pp [Base, Child].class # => Array(Base)
    pp typeof([Base, Child]) # => Array(Base)
    pp [Base.new, Child.new].class # => Array(Base)
    pp typeof([Base.new, Child.new]) # => Array(Base)
Of course this one is minor and perhaps unrelated as only string representation is same, types are still different.

Oh, and thanks for the great language, it's wonderful.

**Comment by asterite** [comment] 2016-07-16 21:14
Slightly related to #2661, so I'll close as a duplicate of it.

In this case `[Child1, Child2]` is deduced to be of type `Child1:Class | Child2:Class`, which ends up being `Child+:Class`. If you want that to be an array of `Base+:Class`, simply say that to the compiler:

```cr
class Base
end

class Child < Base
end

class Child1 < Child
end

class Child2 < Child
end

$hash = {Base => 1, Child => 1, Child1 => 1, Child2 => 1}
$hash[Child1] = 0 # compiles ok
arr = [Child1, Child2] of Base.class
$hash[arr[0]] = 1
```

The compiler will try to figure out the most specific type, in an array literal, so if you want a more general type you'll have to be explicit about it.

**Comment by konovod** [comment] 2016-07-17 06:13
No, in my case i need an array of Child+, not Base+, it is used as Child+ in other places. The problem is how to use an items of this array when more general class is required - they are surely always correct substitutes, but compiler doesn't figure it.
Of course if #2661means complete removing of "class+" idea this will solve the issue, but saying "here can be class or any descendant of it" is usual in OOP.

**Comment by konovod** [comment] 2016-07-17 08:46
On the other hand, casting `item.as(Base.class)` solves the problem. I wasn't aware that is possible.

**Comment by asterite** [comment] 2016-07-17 15:11
I think I misunderstood the original problem, I think this is a bug

**Closed** 2016-07-17 17:05 UTC
Labels: bug, compiler
