### ISSUE TITLE
Compiler bug: no target defs

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#8411] opened 2019-10-31 19:51 UTC
This is how far I could reduce the code:
```cr
class Foo
end
 
class Baz(T) < Foo
  def baz
  end
end
 
class Bar
  @foos = Array(Foo).new
 
  def call_bazes
    @foos.each do |f|
      if f.is_a?(Baz)
        puts f.baz # Error: BUG: no target defs
      end
    end
  end
end
 
Bar.new.call_bazes
Baz(Int32).new
```

A few notes:
* Exchanging the last two lines everything works as intended. So it's solely an order dependend issue.
* If `p!` is omitted from the erroring line, the code compiles but would never actually call `f.baz` (assuming there are items in the array)
* The error only occurs if `@foos` is an ivar. Using a local or class variable is fine.
* If you store the return value of `f.baz` in a local variable and use that variable (for example for `puts tmp`) the code raises a runtime(!) exception: ``can't execute `puts(tmp)`: `tmp` has no type``

**Comment by asterite** [comment] 2019-10-31 20:16
Duplicate of #7583 ?

**Comment by straight-shoota** [comment] 2019-10-31 20:30
Oh that's definitely similar. Might be the same issue.

@Blacksmoke16 claims to have a workaround using `responds_to?` which didn't seem to work in my case.

**Comment by Blacksmoke16** [comment] 2019-10-31 20:46
Oh sorry no, I just meant that I was able to refactor my code in a different way to bypass the error.  Sadly I don't remember what the refactor was as it was never committed and ended up taking a different approach anyway.

**Comment by asterite** [comment] 2019-11-01 13:02
Reduced a bit more:

```crystal
class Foo
end

class Baz(T) < Foo
  def baz
  end
end

f = uninitialized Foo
if f.is_a?(Baz)
  puts f.baz
end

Baz(Int32).new
```

**Closed** 2019-11-01 19:20 UTC
Labels: kind:bug, topic:compiler:semantic

**Comment by jwoertink** [comment] 2021-03-02 23:44
I'm getting this error, but I'm not sure what to even look for on what's causing it... You can see the error on [this repo](https://github.com/luckyframework/breeze/pull/5/checks?check_run_id=2008754803). I'm able to get it locally too when trying to run `crystal spec`. It's sort of a lot of code though. Anyone have any clue on where I should start looking to reduce this?
