### ISSUE TITLE
Interpreter bug when `require "http/server"`

### ISSUE THREAD

**Issue by Vici37** [crystal-lang/crystal#14333] opened 2024-02-28 03:48 UTC
## Bug Report

When trying more things with the interpreter, I wanted to try setting up a very basic web server to experiment with. I immediately ran into this error.

Code to reproduce:
```crystal
$ crystal i
Crystal interpreter 1.12.0-dev [e3eb178f2] (2024-02-27).
EXPERIMENTAL SOFTWARE: if you find a bug, please consider opening an issue in
https://github.com/crystal-lang/crystal/issues/new/
icr:1> require "http/server"
```

Resulting error:
```
...[snipped]...
In src/http/web_socket/protocol.cr:122:9

 122 | @io.write_byte(flags.value | opcode.value)
           ^---------
Error: instantiating 'IO+#write_byte(UInt8)'


In src/io/buffered.cr:169:8

 169 | if sync?
          ^----
Error: instantiating 'sync?()'


In src/io/buffered.cr:215:15

 215 | def sync? : Bool
                   ^---
Error: method HTTP::Server::Response::Output#sync? must return Bool but it is returning (Bool | Nil)
```

Compiler has no issues with this code (as can be expected given the healthy web-app ecosystem of crystal). Reproduced with latest build of crystal 1.12-dev. It's strange since eye-balling the code, I can't find where the underlying `@sync` bool inherited from `IO::Buffered` can ever be nil :confused: 

LLVM 12, Linux Mint 20.3.

**Comment by straight-shoota** [comment] 2024-02-28 10:45
Duplicate of #13873.
The code works fine when interpreted as a whole (e.g. from a file). The failure is caused by the REPL needing to recalculate some types when instantiating `HTTP::Server::Response::Output`.

**Closed by straight-shoota** 2024-02-28 10:45 UTC
Labels: kind:bug, topic:stdlib:networking, topic:compiler:interpreter
