### ISSUE TITLE
Unable to Compile it in HPC | Error related to  libmetis.a

### ISSUE THREAD

**Issue by anikm21** [crystal-lang/crystal#12074] opened 2022-05-28 06:57 UTC
I am trying to compile this in HPC systems using Intel compiler 2017.3.196 and gcc version is 4.8.5.

It is throwing some error related to libmetis.a :

ld: libmetis.a(error.c.o): unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
make: *** [ucns3d_p] Error 1

I have attached the screenshot of the error below. Please help me to compile it on hpc. Thanks in advance

![image](https://user-images.githubusercontent.com/106423738/170814227-5e138822-4b75-45da-9450-6b47a9572f91.png)

Regards, 

Anik

**Comment by straight-shoota** [comment] 2022-05-28 12:25
Please provide some information in order to understand and possibly reproduce this error.

* What are you trying to compile? I'm not aware that `libmetis` is a runtime dependency of the standard library, so it's likely 'related to some third party software.
* How are you compiling it. Please include a full copy of the compiler command and full output as text, not an image.
* What is the Crystal compiler version and target platform (`crystal --version`)?

**Comment by HertzDevil** [comment] 2022-05-28 14:22
This looks like a Fortran project completely unrelated to Crystal.

**Comment by beta-ziliani** [comment] 2022-05-30 11:52
Closing it for the time being. With further evidence we can consider reopening it if necessary.

**Closed** 2022-05-30 20:15 UTC
Labels: kind:bug, platform

**Comment by anikm21** [comment] 2022-05-31 12:02
@straight-shoota :

1. What are you trying to compile? I'm not aware that libmetis is a runtime dependency of the standard library, so it's likely related to some third party software.
Response: Hi, We are trying to compile the UCNS3D using the Makefile supplied with the Zip folder on Github. We are using 'make -f Makefile clean all' command to compile it using mpiifort compiler [Intel compiler 2017.3.196 and gcc version is 4.8.5] . But its failing with the following errors:

ld: libmetis.a(error.c.o): unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
make: *** [ucns3d_p] Error 1


About libmetis: there is also a file name libmetis.a supplied in the CODE folder. I guess its related to that file. 

2. How are you compiling it. Please include a full copy of the compiler command and full output as text, not an image.
Response: We are using 'make -f Makefile clean all' command to compile it using mpiifort compiler [Intel compiler 2017.3.196 and gcc version is 4.8.5] . But its failing with the following errors:

ld: libmetis.a(error.c.o): unrecognized relocation (0x2a) in section `.text'
ld: final link failed: Bad value
make: *** [ucns3d_p] Error 1

Our Makefile is attached with the reply. 
[Makefile.txt](https://github.com/crystal-lang/crystal/files/8804843/Makefile.txt)
The error message is also attached with the log file:
[log.txt](https://github.com/crystal-lang/crystal/files/8804880/log.txt)


3. What is the Crystal compiler version and target platform (crystal --version)?
Response: Our HPC doesn't have any Crystal compiler. Is it required for the installation? or any C++ compiler like GCC or ICC will work?

Waiting for your quick response.
