### ISSUE TITLE
Macro thinks variable is actual variable name

### ISSUE THREAD

**Issue by IvRRimum** [crystal-lang/crystal#4357] opened 2017-04-30 17:46 UTC
Hey,

I think the best way is to show by example:

Working solution: https://play.crystal-lang.org/#/r/6m7
Not working solution: https://play.crystal-lang.org/#/r/1yd7

When you put a string in a variable and then pass it to macro, it uses the literary variable name as value.

Is this a bug?

**Comment by kirbyfan64** [comment] 2017-04-30 17:54
No, it's intentional. Variables are assigned at *runtime*, but macros run at *compile time*.

**Comment by IvRRimum** [comment] 2017-04-30 17:55
So what would be solution?

**Comment by kirbyfan64** [comment] 2017-04-30 17:56
@IvRRimum [Use a constant (all uppercase), and call `.resolve` to get the assigned value](https://play.crystal-lang.org/#/r/1ydo):

```crystal
macro get(route, handler)
  {% controller_and_action = handler.resolve.split '#' %}
  {% controller = controller_and_action[0] %}
  {% action = controller_and_action[1] %}
  {{ controller.id.capitalize }}Controller.new.{{action.id}}({{route}})
end

class WelcomeController
  def index(route)
    puts "Yay, I'm handling route '#{route}'"
  end
end

TEST = "welcome#index"
get "/", TEST
```

**Comment by kirbyfan64** [comment] 2017-04-30 17:58
You can also use [`.is_a?` to handle both constants *and* literals](https://play.crystal-lang.org/#/r/1ydu):

```crystal
macro get(route, handler)
  {% if handler.is_a? Path %}
    # It's a constant; get the underlying value.
    {% handler = handler.resolve %}
  {% end %}

  {% controller_and_action = handler.split '#' %}
  {% controller = controller_and_action[0] %}
  {% action = controller_and_action[1] %}
  {{ controller.id.capitalize }}Controller.new.{{action.id}}({{route}})
end

class WelcomeController
  def index(route)
    puts "Yay, I'm handling route '#{route}'"
  end
end

TEST = "welcome#index"
get "/", TEST
```

**Comment by IvRRimum** [comment] 2017-04-30 18:03
In my context `test` is a dynamic variable. All possible `test` outcomes are defined in runtime - example: `["Note", "Post", "Photo"]`. I don't think constants would work in this case.

**Comment by IvRRimum** [comment] 2017-04-30 18:07
This would be the case i am in: https://play.crystal-lang.org/#/r/1ydw

**Comment by kirbyfan64** [comment] 2017-04-30 18:12
@IvRRimum If `test` is really a dynamic variable, then you can't get its value at compile time. At all. If you're doing the `index` method every single time, maybe you could use a [normal function](https://play.crystal-lang.org/#/r/1ydx):

```crystal
class WelcomeController
  def index(route)
    puts "Yay, I'm handling route '#{route}'"
  end
end


CONTROLLERS = {
  "welcome" => WelcomeController,
  # Put more here...
}


def get(route, controller)
  CONTROLLERS[controller].new.index(route)
end


TEST = "welcome"
get "/", TEST
```

**Comment by IvRRimum** [comment] 2017-04-30 18:23
Yeah, that was my original idea, but here is the tricky part:

```
CONTROLLERS = {
  "welcome" => WelcomeController,
  # Put more here...
}
```

In my scenario that is `@@value` inside of a class. And when i try to do approach you wrote above, compiler asks me to define KeyType => KeyVale for the List.

And when i add Object as a value type, compiler says i need to be more specific :D

**Comment by IvRRimum** [comment] 2017-04-30 18:46
Please leave this open. When i will figure this out i will post the solution here. So other developers can have a reference.

**Comment by kirbyfan64** [comment] 2017-04-30 19:16
> In my scenario that is @@value inside of a class. And when i try to do approach you wrote above, compiler asks me to define KeyType => KeyVale for the List.

> And when i add Object as a value type, compiler says i need to be more specific :D

Can you give some more specifics? Do you mean something like [this](https://play.crystal-lang.org/#/r/1yep):


```crystal
abstract class Controller
  abstract def index(route)
end


class WelcomeController < Controller
  def index(route)
    puts "Yay, I'm handling route '#{route}'"
  end
end


CONTROLLERS = {
  "welcome" => WelcomeController,
  # Put more here...
} of String => Controller.class


def get(route, controller)
  CONTROLLERS[controller].new.index(route)
end


TEST = "welcome"
get "/", TEST
```

**Comment by IvRRimum** [comment] 2017-04-30 19:52
More specific would be https://github.com/drujensen/kemalyst models

On Compile time i fetch specific models and then want to make models object.

**Comment by asterite** [comment] 2017-06-04 23:28
I'm closing this because this is not a bug nor a missing feature. That's how the language works. You can't do some things that you can do in dynamic languages. You can, however, solve the same problems, but they need a different solution.

**Closed by asterite** 2017-06-04 23:28 UTC
