### ISSUE TITLE
Failing test not being counted

### ISSUE THREAD

**Issue by marceloboeira** [crystal-lang/crystal#3198] opened 2016-08-28 14:45 UTC
For some reason the test is failing, but the report is buggy, it prints:

```
Finished in 301.18 milliseconds
24 examples, 0 failures, 0 errors, 0 pending
```

However soon after:

```
expected: "error: 'invalid_counter' is not a valid key\n"
     got: "\n" (Spec::AssertionFailed)
[4464495698] *CallStack::unwind:Array(Pointer(Void)) +82
[4464495601] *CallStack#initialize:Array(Pointer(Void)) +17
[4464495560] *CallStack::new:CallStack +40
[4464457321] *raise<Spec::AssertionFailed>:NoReturn +25
[4464457281] *fail<String, String, Int32>:NoReturn +17
[4464534238] *String@Spec::ObjectExtensions#should<Spec::EqualExpectation(String), String, Int32>:Nil +78
[4464472238] ~procProc(Nil)@./spec/bojack/server_spec.cr:49 +190
```

The code is available here: https://github.com/marceloboeira/bojack/tree/bug
Failing CI source: https://travis-ci.org/marceloboeira/bojack/jobs/155739162

**Comment by ysbaddaden** [comment] 2016-08-29 09:31
Are you testing asynchronous code?

**Comment by RX14** [comment] 2016-08-29 09:41
This is because you place your specs in a `TCPSocket.open` block in [server_spec.cr](https://github.com/marceloboeira/bojack/blob/171caca335ee64fe561bfa65f883497e204aa306/spec/bojack/server_spec.cr#L9).

**Comment by marceloboeira** [comment] 2016-08-29 09:42
@ysbaddaden yes, @RX14 it is working actually, never failed before the change in the `bug` branch.

**Comment by jhass** [comment] 2016-08-29 09:58
I don't see a fiber spawned anywhere, so I think this might actually  be a bug in the exception handler codegen, probably some weird interaction between `TCPSocket.open` wrapping its block into a `begin/ensure` and `describe` and `it` both converting their blocks into procs and `it` wrapping calling its proc into a `begin/rescue`.

**Comment by Maroo-b** [comment] 2019-04-13 11:33
The link for the source code isn't working anymore and there are no details to check if it's still an issue. @straight-shoota should we close it?

**Comment by straight-shoota** [comment] 2019-04-13 11:37
Yes. Can be reopened if there is reproducible code.

**Closed by straight-shoota** 2019-04-13 11:37 UTC
Labels: kind:bug, topic:compiler
