### ISSUE TITLE
Compiler crash when using multiline assignment to initialize attributes

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#3368] opened 2016-09-30 12:18 UTC
I'm not sure this syntax is (or should be) valid ... Anyway it makes the compiler crash:

``` crystal
class C
  @a : Bool
  @b : Bool
  @a = @b = false
end

C.new
```

Crash dump:

```
Bug: `` at  has no type
[5604654] ???
[7141022] ???
[16040520] ???
[16037941] ???
[15999362] ???
[15970922] ???
[15821711] ???
[15915702] ???
[15824924] ???
[15822922] ???
[15903861] ???
[15911832] ???
[15976579] ???
[15821711] ???
[15633917] ???
[6979430] ???
[16508791] ???
[5826489] ???
[5697720] main +18872
[140330040594245] __libc_start_main +245
```

Crystal version impacted:

```
$ crystal --version
Crystal 0.18.7 [68783f1] (2016-07-03)
```

**Comment by robks** [comment] 2016-11-18 15:23
Note: This builds okay in 0.19.4

**Comment by asterite** [comment] 2016-11-18 17:26
It seems to crash when using C:

```cr
class C
  @a : Bool
  @b : Bool
  @a = @b = false
end

C.new
```

So the original report was incomplete.

**Comment by olbat** [comment] 2016-12-14 08:55
You're right, `C.new` was missing from the report.

**Comment by asterite** [comment] 2017-09-26 19:36
Duplicate of #2865

**Closed by asterite** 2017-09-26 19:36 UTC
Labels: kind:bug, topic:compiler
