### ISSUE TITLE
Linkage error when using overloading

### ISSUE THREAD

**Issue by nuxlli** [crystal-lang/crystal#2832] opened 2016-06-14 20:24 UTC
The following code will throw a linkage error on `0.17.4`:

```crystal
class TestEnable
  def hasEnable
    false
  end
end

class Test
  @enable : Bool | TestEnable
  def initialize(@enable = TestEnable.new)
  end

  def enabled?
    is_enable(@enable)
  end

  private def is_enable(enable : TestEnable)
    return enable.hasEnable
  end

  private def is_enable(enable : Bool)
    return enable
  end
end

obj = Test.new(enable: true)
obj.enabled?
```

The prompted error is:

```
Listening on http://localhost:8080
Invalid memory access (signal 11) at address 0x0
[4443030000] __crystal_sigfault_handler +64
[140735654346522] _sigtramp +26
[4454330834] _ZNK4llvm14TargetLowering11LowerCallToERNS0_16CallLoweringInfoE +1408
[4454335527] _ZN4llvm19SelectionDAGBuilder14lowerInvokableERNS_14TargetLowering16CallLoweringInfoEPNS_17MachineBasicBlockE +317
[4454269254] _ZN4llvm19SelectionDAGBuilder11LowerCallToENS_17ImmutableCallSiteENS_7SDValueEbPNS_17MachineBasicBlockE +940
[4454208652] _ZN4llvm19SelectionDAGBuilder11visitInvokeERKNS_10InvokeInstE +232
[4454201309] _ZN4llvm19SelectionDAGBuilder5visitERKNS_11InstructionE +69
[4454402613] _ZN4llvm16SelectionDAGISel16SelectBasicBlockENS_14ilist_iteratorIKNS_11InstructionEEES4_Rb +33
[4454402433] _ZN4llvm16SelectionDAGISel20SelectAllBasicBlocksERKNS_8FunctionE +1235
[4454399317] _ZN4llvm16SelectionDAGISel20runOnMachineFunctionERNS_15MachineFunctionE +819
[4452671967] _ZN12_GLOBAL__N_115X86DAGToDAGISel20runOnMachineFunctionERN4llvm15MachineFunctionE +41
[4455565660] _ZN4llvm19MachineFunctionPass13runOnFunctionERNS_8FunctionE +96
[4459276625] _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE +275
[4459277025] _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE +41
[4459277881] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +607
[4458300979] _ZL21LLVMTargetMachineEmitP23LLVMOpaqueTargetMachineP16LLVMOpaqueModuleRN4llvm21formatted_raw_ostreamE19LLVMCodeGenFileTypePPc +259
[4458300618] LLVMTargetMachineEmitToFile +268
[4451184654] *Crystal::Compiler#codegen_single_unit<Crystal::Compiler, Crystal::Program, Crystal::Compiler::CompilationUnit, String, Bool>:LLVM::Module? +2878
[4451191118] ~proc( -> Void)@./src/compiler/crystal/compiler.cr:274 +606
[4442923683] ~proc(Fiber -> (Int64 | Void))@./src/fiber/fiber.cr:26 +35
ld: file too small (length=0) file 'Test.o' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with code: 1: `cc -o "/Users/nuxlli/.cache/crystal/crystal-run-play-1-1.tmp" "${@}"  -rdynamic  -lssl -lcrypto -lz /Users/nuxlli/.anyenv/envs/crenv/versions/0.17.4/src/ext/libcrystal.a -levent -lpcre -lgc -lpthread -liconv -ldl`
```

However, calling `new` with no args and then with the desired args, it works:

```crystal
Test.new
obj = Test.new(enable: true)
obj.enabled?
```

In my code, I've changed to:

```crystal
private def is_enable(enable)
  enable.is_a?(TestEnable) ? enable.hasEnable : enable
end
```

I believe this is a bug on the compiler, so I'm reporting.

**Comment by asterite** [comment] 2016-06-14 20:27
Seems to be fixed in master :-)

**Comment by jhass** [comment] 2016-06-14 20:28
I can confirm, seems to compile with 0.18.0

**Closed by jhass** 2016-06-14 20:28 UTC

**Comment by nuxlli** [comment] 2016-06-15 01:20
Thanks @jhass and @asterite, I've tried and that worked.
