### ISSUE TITLE
Type class including a module is not a superset of it.

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#8889] opened 2020-03-07 11:46 UTC
A type class, including a given module, is not considered to be a superset of it.
To say differently, a type `S` including a module `M` is not considered to be a `M.class`:

```cr
module M
end
 
struct S
  include M
end

p S.is_a? M.class #=> false
 
# Works with instances
p S.new.is_a? M #=> true
 
# Workaround
def check_m(t : M.class) : Bool
  true
end
 
def check_m(t) : Bool
  false
end
 
p check_m ary S #=> true
```
A workaround is to use methods, one which restricts to the module type, and an other with no type restrictions.

**Comment by asterite** [comment] 2020-03-07 12:49
Note that when I mentioned this in gitter I meant it something that is like that and it makes sense for it work work like that (at least with Ruby semantics). There's nothing broken here.

**Comment by j8r** [comment] 2020-03-07 14:14
Maybe... then having a better way to do this, but this might be not worth it if this is a rare edge case.

**Comment by oprypin** [comment] 2020-03-08 08:27
This is expected behavior.

S is a subclass of M with `include`.
S is a M with `extend`.

I recommend closing.

**Comment by asterite** [comment] 2020-03-08 14:21
And the overload matches M.class because... M is an ancestor of S and M.class behaves a bit different than is_a?

We can keep this open to see if we want to change something of this.

**Comment by j8r** [comment] 2020-07-27 17:04
@oprypin is right, `extend` is the thing to use. Ididn't know `abstact def` was becoming a class method to implement by using `extend`.

This following behavior is not documented:
```cr
module A
  abstract def m
end

struct B
  extend A
  def self.m
  end
end

# Would be more intuitive to have met(a : A.class)
def met(a : A)
  pp a
  a.m
end

met B
```

I would be very glad if someone explains this to me, the reasoning behind this behavior :slightly_smiling_face:

**Closed** 2020-07-27 17:04 UTC
