### ISSUE TITLE
Make OAuth2::Client and OAuth::Consumer more configurable

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#4029] opened 2017-02-13 13:12 UTC
It seems [GitHub](https://developer.github.com/v3/oauth/#response) (and I guess other provides do whatever they want) doesn't respect the RFC and chooses to return form data instead of JSON, and demands an Accept header.

We should somehow make these types more configurable. Maybe a callback to configure an HTTP::Client or similar.

[Discussion in Google Groups](https://groups.google.com/forum/?fromgroups#!topic/crystal-lang/vyeMdlpb1N0)

**Comment by felipeelias** [comment] 2017-02-13 20:22
The Github OAuth2 implementation does not follow the RFC far beyond that. It turns out that the `access_token` response does not return `expires_in` [attribute](https://developer.github.com/v3/oauth/#response).

This breaks the client when parsing [the response](https://github.com/crystal-lang/crystal/blob/master/src/oauth2/access_token/access_token.cr#L29).

Here is an example of OAuth2 client that works with Github api: [link](https://github.com/felipeelias/crystal-github/blob/master/src/github/oauth2.cr)

**Comment by felipeelias** [comment] 2017-02-13 21:37
I made some initial changes [here](https://github.com/felipeelias/crystal/commit/e0cdbb234e9a7e304cad5999108fb1191f17c19b).

Letting a custom `HTTP::Client` be sent on the initializer looks ok, although the custom access token class I'm not sure

**Comment by asterite** [comment] 2017-02-14 12:47
I think that if GitHub's API is way too far from OAuth2 than it's OK if we don't touch anything on our side. People will have to implement this particular endpoint themselves.

**Comment by RX14** [comment] 2017-02-14 13:01
Would it hurt to send an `Accept: application/json` to requests which can only accept `application/json` anyway? This probably wouldn't help much with github but I can't see many downsides to introducing this change.

**Comment by asterite** [comment] 2017-02-14 13:05
I guess we can do that. I don't know if that can break servers not expecting any `Accept` header at all, but I guess not...

**Comment by felipeelias** [comment] 2017-02-14 20:05
If the client is expecting JSON response, it makes sense to send the corresponding `Accept` header.

I can prepare a pull-request with that change if we're ok with it. Thoughts?

**Comment by oltmannsdaniel** [comment] 2017-02-14 20:56
@felipeelias I think that makes sense. You should add it with a new pull request .

**Comment by spalladino** [comment] 2017-02-16 18:04
Closing the issue as implemented by #4038 and duplicate of #4041

**Closed by spalladino** 2017-02-16 18:04 UTC
Labels: community:to-design, kind:feature, status:discussion, topic:stdlib
