### ISSUE TITLE
Wrong YAML nil serialization and scalars deserialization

### ISSUE THREAD

**Issue by olbat** [crystal-lang/crystal#4175] opened 2017-03-22 18:54 UTC
Crystal's YAML builder/parser does not handle properly nil serialization and YAML scalars deserialization:
- Empty strings are serialized to nil
- [null](http://yaml.org/type/null.html), [bool](http://yaml.org/type/bool.html), [float](http://yaml.org/type/float.html) and [timestamp](http://yaml.org/type/timestamp.html) scalars are deserialized to strings

Here is an example:
```bash
$ cat test.cr
require "yaml"
p "".to_yaml
p [""].to_yaml
p({"a" => ""}.to_yaml)
p YAML.parse("---")
p YAML.parse("~")
p YAML.parse("null")
p YAML.parse("- ")
p YAML.parse("a: ")
p YAML.parse("true")
p YAML.parse("yes")
p YAML.parse("on")
p YAML.parse(".inf")
p YAML.parse(".nan")
p YAML.parse("01:01")
p YAML.parse("1970-01-01")
```

the output:
```bash
$ crystal run test.cr | nl
     1	"--- \n...\n"
     2	"---\n- \n"
     3	"---\na: \n"
     4	""
     5	"~"
     6	"null"
     7	[""]
     8	{"a" => ""}
     9	"true"
    10	"yes"
    11	"on"
    12	".inf"
    13	".nan"
    14	"01:01"
    15	"1970-01-01"

$ crystal --version
Crystal 0.21.1 [3c6c75e] (2017-03-06) LLVM 3.5.0
```

to compare, the output of Ruby's implementation:
```bash
$ sed 's/parse/load/' test.cr | ruby | nl
     1	"--- ''\n"
     2	"---\n- ''\n"
     3	"---\na: ''\n"
     4	nil
     5	nil
     6	nil
     7	[nil]
     8	{"a"=>nil}
     9	true
    10	true
    11	true
    12	Infinity
    13	NaN
    14	3660
    15	#<Date: 1970-01-01 ((2440588j,0s,0n),+0s,2299161j)>

$ ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

__edit__: deserialization of every YAML scalars seems to be impacted

**Comment by olbat** [comment] 2017-03-22 21:25
I'm not sure it will be useful but here is the Ruby's Psych [scalar scanner implementation](https://github.com/ruby/ruby/blob/ruby_2_4/ext/psych/lib/psych/scalar_scanner.rb#L32-L112).

**Comment by asterite** [comment] 2017-03-23 13:56
This is more or less a duplicate of #4175 . The current YAML parser only knows about String, Array and Hash. We need to extend this to support the core YAML schema, possibly other schemas too.

**Closed by asterite** 2017-03-23 13:56 UTC

**Comment by kirbyfan64** [comment] 2017-03-23 14:04
@asterite Did you mean #2873 or #3101? Right now, your link is giving me a recursion error...

**Comment by olbat** [comment] 2017-03-23 15:11
Oops, I tried to find a related issue but I missed both of them, thanks for the references.

**Comment by straight-shoota** [comment] 2017-08-01 08:16
This issue can't possibly be a duplicate of itself and I don't think it is a duplicate of #2873 or #3101 either. Please reopen.

**Comment by ysbaddaden** [comment] 2017-08-01 12:54
No. It's a duplicate of #3101 per "unsupported types (e.g. null, numbers)".
