### ISSUE TITLE
StaticArray combined with STDOUT won't compile

### ISSUE THREAD

**Issue by cfsamson** [crystal-lang/crystal#6677] opened 2018-09-07 18:25 UTC
This code:
```
buffer = StaticArray(UInt8, 5).new(0_u8)
STDOUT.write(buffer.to_slice)
```
Stalls the compiler. Both on my machine and in the playground.

Playground link: [https://play.crystal-lang.org/#/r/4wp3/edit](url)

Crystal 0.26.1 [391785249] (2018-08-27)
LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
Ubuntu 18.04

**Comment by asterite** [comment] 2018-09-07 18:28
Works for me. The playground can't handle non-visible output.

**Comment by asterite** [comment] 2018-09-07 18:29
I mean, it works as a regular program compiled with the `crystal` binary.

**Comment by asterite** [comment] 2018-09-07 18:40
Duplicate of https://github.com/crystal-lang/crystal/issues/5613

The playground doesn't currently support outputing non-visible characters.

**Closed by asterite** 2018-09-07 18:40 UTC

**Comment by cfsamson** [comment] 2018-09-07 18:53
Hmm, my compiler hangs when compiling it. When it hanged on the playground I just used that code and assumed that problem was the same. Using capacity of 5 works for me, but using capacity of 5001 does hang the compiler on my pc.

`buffer = StaticArray(UInt8, 5001).new(0_u8)`

**Comment by cfsamson** [comment] 2018-09-07 18:54
Hmm, my compiler hangs when compiling it. When it hanged on the playground I just used that code and assumed that problem was the same. Using capacity of 5 works for me, but using capacity of 5001 does hang the compiler on my pc.

**Comment by cfsamson** [comment] 2018-09-07 18:56
OK, I see.  So trying this exact code just that worked now. This was emberassing. 

The original code was a bit more complex so there can be something else causing it to hang. I'll close this and get back if I figure it out :)

**Comment by asterite** [comment] 2018-09-07 18:57
If you use big static arrays, LLVM (and thus Crystal) will take a really long time to compile, so you should avoid doing that.

**Comment by cfsamson** [comment] 2018-09-07 19:00
Aha, that might be it though. OK, but if I want a stack allocated array, are there any alternative?

**Comment by cfsamson** [comment] 2018-09-07 19:01
I waited 2-3 minutes several times before I stopped the compilation and tried it in the playground.
