### ISSUE TITLE
Can't use Time in NamedTuple with .to_h conversion

### ISSUE THREAD

**Issue by relonger** [crystal-lang/crystal#4203] opened 2017-03-28 14:43 UTC
```
def uni(**args)
  puts "#{args.to_h}"
end

uni(a:123, b: "opa")

uni(a:123, b: "opa", c: Time.now)
```

Produce an error: 
```in /usr/lib/crystal/named_tuple.cr:402: expanding macro

    {% begin %}
    ^

in macro 'macro_206236176' /usr/lib/crystal/named_tuple.cr:402, line 8:

   1. 
   2.       {
   3.         
   4.           :a => self[:a].clone,
   5.         
   6.           :b => self[:b].clone,
   7.         
>  8.           :c => self[:c].clone,
   9.         
  10.       }
  11.     

undefined method 'clone' for Time
```

version:
Crystal 0.21.1 (2017-03-14) LLVM 4.0.0

**Comment by asterite** [comment] 2017-03-28 14:45
Duplicate of https://github.com/crystal-lang/crystal/pull/4174 (already fixed in master)

**Comment by asterite** [comment] 2017-03-28 14:46
Actually, I'll reopen this. Why is there a `clone` in `NamedTuple#to_h` in the first place? :-S

**Closed** 2017-03-28 14:48 UTC
Labels: kind:bug, topic:stdlib

**Comment by Sija** [comment] 2017-03-28 17:27
@asterite heh, I was asking myself the same question but then I told to myself there must be a reason to that, and went ahead with #4174 ;)
