### ISSUE TITLE
Cast error ?

### ISSUE THREAD

**Issue by hutou** [crystal-lang/crystal#8268] opened 2019-10-04 09:58 UTC
Given the following code :
```
alias CellType = Bool | Char | Int::Signed | Int::Unsigned | Float32 | Float64 | String | Symbol
x = 7.as(CellType)
y = x.as(Number)
puts typeof(y)
puts y * 2
```
displayed results are : 
```
(Float32 | Float64 | Int128 | Int16 | Int32 | Int64 | Int8 | UInt128 | UInt16 | UInt32 | UInt64 | UInt8)
14
```
But if I try to multiply `y` with any other value than `2`, for example
`puts y * 3`
I get :
```
/usr/bin/ld: _main.o: in function `__crystal_main':
./eval:4: undefined reference to `__muloti4'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/crystal/.cache/crystal/crystal-run-eval.tmp'  -rdynamic  -lpcre -lm -lgc -lpthread /usr/lib/crystal/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```
This error appears from the 0.31 release

**Comment by oprypin** [comment] 2019-10-04 11:12
Yep, this is real
https://carc.in/#/r/7ozm

**Comment by bcardiff** [comment] 2019-10-04 17:43
@hutou can you describe your environment? arch/distro 

The issue is related to the partial Int128 bits support?

As a workaround, you should be able to

```crystal
alias CellType = Float32 | Float64 | Int16 | Int32 | Int64 | Int8 | UInt16 | UInt32 | UInt64 | UInt8
x = 7.as(CellType)
y = x.as(Number)
puts typeof(y)
puts y * 2
puts y * 3
```

**Comment by hutou** [comment] 2019-10-04 18:58
@bcardiff Environment is : Gnome 3.34.0 on Archlinux (5.3.1-arch1-1-ARCH - x86_64)
As you suggest, removing UInt128 and Int128 from CellType solves the problem

**Comment by RX14** [comment] 2019-10-06 22:02
`y * 2` will be optimized to a shift, avoiding the muloti4 call. This is just about compiler-rt.

**Comment by jhass** [comment] 2020-03-17 09:55
So is this something we need to fix in Archlinux packaging or in the compiler?

**Comment by straight-shoota** [comment] 2021-04-25 12:50
The reproduction is trivial: `1.to_i128 * 3`

We're just missing support for 128-bit arithmetics and the `Int::Signed` and `Int::Unsigned` unions include `Int128` and `UInt128` types. This is just a duplicate of #8373.

**Closed by straight-shoota** 2021-04-25 12:50 UTC
Labels: kind:bug, topic:stdlib
