### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by 7sedam7** [crystal-lang/crystal#4673] opened 2017-07-04 20:36 UTC
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  %105 = call i8* @__crystal_malloc(i32 ptrtoint (i32* getelementptr (i32, i32* null, i32 1) to i32))

0x101f16b63: *raise<String>:NoReturn at ??
0x102e1235b: *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) at ??
0x1036c2e54: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x101f84a8b: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x101f50711: main at ??

```
require "http/client"

BASE_URL = "https://url"

def bla(response)
  response.body.lines.each do |line|
    country = /some regex/.match(line).try &.[1]
    return country if country
  end
end

def request_id(id)
  url = "#{BASE_URL}/#{id}"

  response = HTTP::Client.get(
    url,
    headers: HTTP::Headers {
      "User-agent" => "AwesomeApp"
    }
  )
end

(1..999).each do |id|
  spawn do
    response = request_id(id)
    puts extract_country(response) if response.status_code == 200
  end
end
```

**Comment by Sija** [comment] 2017-07-05 05:47
Could you post your `crystal -v` please?

**Comment by 7sedam7** [comment] 2017-08-04 18:23
`Crystal 0.23.1 (2017-07-13) LLVM 4.0.1`

Although it could be that it was upgraded in the meantime

**Comment by 7sedam7** [comment] 2017-08-24 08:18
@OscarBarrett Is that expected behavior, and if yes, why, what's wrong with `each`

**Comment by RX14** [comment] 2017-08-27 12:54
This is probably also a dupe of #4600.

**Closed** 2017-08-27 13:42 UTC
