### ISSUE TITLE
Enumerable API consistency: inject raises for an empty array, sum happily returns 0

### ISSUE THREAD

**Issue by PragTob** [crystal-lang/crystal#1239] opened 2015-08-19 20:55 UTC
```crystal
assert { ([] of Int32).sum.should eq(0) }
([] of Int32).inject { |memo, i| memo + i } # => raises EmptyEnumerable
# Ruby
[].inject {|m, e| m + e} => nil
```

It seems weird to me that inject raises for an empty enumerable while sum (which in my head is an inject &:+) happily obliges. Consistent behavior would be nice I guess :)

But then again, I suspect that if we wanted to do the same behavior as ruby the return type of inject would include Nil leading to a lot of nil checks after every inject - as sum knows it's only numbers it can safely return its "type specific nil value"

if my last stated assumption is correct, then the not nil checking might outweight the inconsistency. Just wanted to mention it either way :)

**Comment by waterlink** [comment] 2015-08-19 22:17
This works though: http://carc.in/#/r/c0y

**Comment by waterlink** [comment] 2015-08-19 22:18
I think `sum` <=> `inject(0) {|m, e| m + e}`

**Comment by waj** [comment] 2015-08-19 23:08
For me it's more consistent that the sum of an empty set is zero: https://en.wikipedia.org/wiki/Empty_sum
It's also zero in Ruby (actually implemented in ActiveSupport): http://api.rubyonrails.org/classes/Enumerable.html#method-i-sum

**Comment by waj** [comment] 2015-08-19 23:15
Also, note that the version of `inject` that receives an initial value can work on empty sets (returning the same initial value). Only the `inject` without initial value raises if the enumerable is empty.

**Comment by mverzilli** [comment] 2015-08-19 23:18
What's the point of inject without an initial value?

**Comment by asterite** [comment] 2015-08-19 23:29
@mverzilli The initial value would be the first element in the enumerable (but if it's empty there's no such element to begin with, so an exception is raised)

**Comment by mverzilli** [comment] 2015-08-20 00:51
But the initial value is for the result, isn't it? If you want to compute sum it's 0, if you want to turn an array into a dictionary it's tipically {}, and so on. 

Inject is like a fold, it lets you collapse a collection into some result, so not giving a default value feels a bit counterintuitive.

**Comment by jhass** [comment] 2015-08-20 12:12
Using `inject` to build hashes is generally considered misuse. All usages where you have to return the same accumulator object from the block are better written with `each_with_object`.

```cr
# Bad
hash = [{"a", "b"}, {"c", "d"}].inject({} of String => String) {|hash, pair|
  hash[pair[0]] = pair[1]
  hash
}

# Better
hash = [{"a", "b"}, {"c", "d"}].each_with_object({} of String => String) {|pair, hash|
    hash[pair[0]] = pair[1]
}
```

**Comment by mverzilli** [comment] 2015-08-20 12:36
Thanks @jhass, didn't know about `each_with_object`. Anyway, that was just an unfortunate example. 

My point is that `inject` lets you transform a collection into something else by traversing it and accumulating a result. 

Failing to provide an initial value for that result seems a bit contrary to that notion, akin to not initialising variables properly.

Consider:

```
[1,2,3].inject { |m, e| m + e}
=> 6

[1,2,3].inject(0) { |m, e| m + e}
=> 6

["1","2","3"].inject {|m, e| m + e}
=> "123"

["1","2","3"].inject("") {|m, e| m + e}
=> "123"
```

So this works because Ruby knows what default value to use in each case, but it becomes less evident when you're injecting towards more complex structures. Of course you could use `each_with_object` for those cases, but at the expense of switching to a more stateful style. 

This reply is full of personal opinion and influenced by functional programming languages, so I totally understand it if seasoned rubyists don't like it and just discard it. Just wanted to add a different perspective on what I see as one of the root causes of the issue that @PragTob reported.

**Comment by waterlink** [comment] 2015-08-20 12:43
@mverzilli Your examples work because of different reason:

```ruby
[thing_a, thing_b, thing_c].inject { ... }
```

is the same as:

```ruby
a = [thing_a, thing_b, thing_c]
a[1..-1].inject(a[0]) { ... }
```

Ruby's and Crystal's `inject` when called without arguments uses first element as a default one.

So "Ruby knows default value to use in each case" is wrong, rather enumerable holds this information as a data itself, it is: `a[0]`.

**Comment by waterlink** [comment] 2015-08-20 12:44
So, going down to example with `+` and numbers:

```ruby
[1, 2, 3].inject { |m, e| m + e }
```

is not equivalent to:

```ruby
[1, 2, 3].inject(0) { |m, e| m + e }
```

But it is an equivalent to:

```ruby
[2, 3].inject(1) { |m, e| m + e }
```

**Comment by mverzilli** [comment] 2015-08-20 12:54
Apologies for my ignorance :). 

Still, the point remains, and it's even stronger: that behaviour forces you to bear in mind two input cases: empty enumerable vs. non-empty enumerable, when what you really care about is the result of the expression. 

Now that you explained it, I get that changing this would be a huge and at the same time subtle depart from Ruby's behaviour, which is a recipe for disaster in Crystal.

And, as a bonus, now I see why it's a bad idea to think of `inject` as a `fold` :).

Sorry for "spamming" this issue!

**Comment by waterlink** [comment] 2015-08-20 13:02
Well, I have no problem with diverging Crystal's behavior from Ruby's one, if it makes more sense of course.

The other way to look at the problem is to somehow define this `additive null` for each type you want to use `inject` without arguments on. So that:

```crystal
items = [a, b, c]
items.inject { ... }
# is equivalent to:
items.inject(items.elem_type.null_value) { ... }
```

But this may cause problems with union types and operations that are not additive.

**Comment by asterite** [comment] 2015-08-20 13:42
@waterlink And in fact this is what we did with [sum](https://github.com/manastech/crystal/blob/1c5b8806ace2e5006e70592858de42ae9a7c6116/src/enumerable.cr#L751). You see there's a `T.zero` as the initial value. Int32, Float64, etc., define a `zero` class method so it works.

But, what happens when T is a union type? Well, a couple of versions ago we decided that if all types in T implement the method, then the call is valid and the result is one of them (you don't know which one) but with a type that equals the union (the type of all methods). So if you do `[1, 1.5].sum` it'll work and give a result that's `Int32 | Float64`.

But I think that was a mistake, because now you can do `Array(Int32 | Float64).from_json(...)` and it compiles but fails at runtime.

And if you have an array of mixed integer types, maybe that's a mistake and you should have one with just one type.

But maybe we can leave that feature but only if the method call has no arguments, so `T.zero` will work but `T.from_json(...)`, which makes a bit more sense. I don't know.

**Comment by asterite** [comment] 2016-05-27 18:20
I think the behaviour of `sum` (and now `product`) are OK: 0 should be the default value for `sum` and `1` for `product`.

We could maybe add a `reduce?` method that returns nil if the enumerable is empty?

**Comment by asterite** [comment] 2016-06-10 15:42
I'm closing this. `sum` and `product` are mathematically known to have `0` and `1` has the initial element, implicitly, so it's not inconsistent with `reduce`. Please open a separate issue if `reduce?` is desired.

**Closed by asterite** 2016-06-10 15:42 UTC
Labels: draft, RFC, standard library
