### ISSUE TITLE
Optional strict mode for Crystal

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#4603] opened 2017-06-22 00:42 UTC
Hi people! :smile: 

@asterite I'm working with crystal code programmed by others developers, I think would be very useful to have **optionally** a `--strict` flag that allow to check that all types need to be explicit.

I got this idea because working with TypeScript projects is very awesome, not because the syntax but because Types help a lot when you need understand the type that a function needs to return by example.

```crystal
def process_data(data)
  # do some cool stuff
end
```

```crystal
def process_data(data : NotificationData) : ResponseData
   # do some cool stuff
end
```

I'm not saying to make types mandatory but something like `use strict` in JavaScript, Also don't need to add `var` or `let` or `const` keywords, instead when use `--strict` flag crystal checks that variables have typed specified:

Crystal normal mode `crystal build myprogram.cr`

```crystal
a = 10
puts a #=> 10
```

Crystal strict mode _optional_ `crystal build --strict myprogram.cr`

```crystal
a = 10
puts a # Type Error: in strict mode you need to specify types
```

Then you try again with type specified `crystal build --strict myprogram.cr`:

```crystal
a : Int32
a = 10
puts a #=> 10
```

All ok!

I really like type inference and write code without types but sometimes is useful to have Types in complex projects. The `--strict` mode proposal is not mandatory, just an tool to help to the programmer to remember where a type is missed. In fact the `--strict` mode could live inside `crystal tool strict` or something similar allowing to check `strict` mode in some files only checking that all code have types.

I know that crystal is strict about types but I'm saying that `--strict` flag do compiler just more strict :sweat_smile: 

Extract from Reddit by @RX14 :

> If you typo a variable, most of the time you will get a compile error

Yes, but I would wish don't wait until compile time to know what type a function must return.

Please let me now your opinions :smile: 

Reference: [#900](https://github.com/crystal-lang/crystal/issues/900) and [Reddit](https://www.reddit.com/r/crystal_programming/comments/5mnt1r/crystal_strict_mode_enforce_variable_declaration/)

**Comment by ysbaddaden** [comment] 2017-06-22 06:13
Closing as duplicate of #900.

This is the exact opposite of crystal goals: not having to bother with types (much).

**Closed by ysbaddaden** 2017-06-22 06:13 UTC

**Comment by faustinoaq** [comment] 2017-06-22 07:03
Ok @ysbaddaden :sweat_smile: Do you know if exist some way to implement this using a shard or macros?

**Comment by ysbaddaden** [comment] 2017-06-22 07:26
Well, you can use the parser, and from there check wheher as a type definition. But I really don't see the point.

What I would like, however, is a tool to printout inferred types. Something similar to `crystal tool hierarchy` but for methods arguments and return types.

**Comment by faustinoaq** [comment] 2017-06-22 07:31
> What I would like, however, is a tool to printout inferred types. Something similar to crystal tool hierarchy but for methods arguments and return types.

Yes, this is a better option. I had not thought!,

Thanks you @ysbaddaden :+1:

**Comment by konovod** [comment] 2017-06-22 10:23
Reddit link is about completely different suggestion - don't enforce types declaration, enforce variable declaration (differentiate it from variable assignment, but still let it be untyped). Personally i would like such feature, but yes, perhaps it's too late and it just don't fit in a language.

**Comment by faustinoaq** [comment] 2017-06-25 18:37
Hi, @ysbaddaden !

I use `show type on hover` in VSCode now:

![types on hover](https://i.imgur.com/5COCsQX.gif)
