### ISSUE TITLE
crystal compiler should run specs from code examples too

### ISSUE THREAD

**Issue by dseres** [crystal-lang/crystal#11394] opened 2021-11-01 19:25 UTC
## Discussion

- What aspect of the language would you like to see improved?

It would be useful, if code examples would be compiled as part of specs, and during testing, these code examples would be checked too

- What are the reasons?

This feature can lead to better documentation of code. 

- Include practical examples to illustrate your points.

The following code define a function with documentation. 'crystal spec' should compile and run the example in the comments as a separate test. 

``` crystal
# This function allways return 1
# 
# Example:
# ```
# function_to_test.should eq 1
# ```
def function_to_test
  1
end
```

**Comment by Sija** [comment] 2021-11-01 19:27
There's already a 3rd party tool that does that, see https://github.com/maiha/crystal-examples

**Comment by dseres** [comment] 2021-11-01 19:45
The existence of the linked project proves that there is need of this feature.

**Comment by straight-shoota** [comment] 2021-11-02 09:31
Duplicate of #9978

**Closed by straight-shoota** 2021-11-02 09:31 UTC
Labels: status:discussion
