### ISSUE TITLE
[] of Int32 should have been expanded (Exception)

### ISSUE THREAD

**Issue by smithtim** [crystal-lang/crystal#10940] opened 2021-07-14 01:10 UTC
I am getting:

`BUG: [] of Int32 at` ... `should have been expanded (Exception)`
...
`Error: you've found a bug in the Crystal compiler.`

from this code:
```crystal
List.find {|i| i > 0}
exit
List = [] of Int32
```

```
$ crystal -v
Crystal 1.0.0 (2021-03-22)

LLVM: 9.0.1
Default target: x86_64-apple-macosx
```

**Comment by HertzDevil** [comment] 2021-07-14 01:12
Duplicate of #5636.

**Closed** 2021-07-14 09:09 UTC
Labels: status:duplicate
