### ISSUE TITLE
cast from Nil to Crystal::GenericInstanceType+ failed at src/compiler/crystal/types.cr:1361

### ISSUE THREAD

**Issue by carsonbaker** [crystal-lang/crystal#4460] opened 2017-05-25 04:58 UTC
I mistakenly typed `Channel.new(Int32)` instead of `Channel(Int32).new` and got this:

Code:
```crystal
class Bar
  @bork = Channel.new(Int32)  
end
```

Execution:
```
 ± crystal doh.cr
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-lang-20170420-38199-6yf8tg/crystal-0.22.0/src/compiler/crystal/types.cr:1361
0x10c557cf1: *raise<TypeCastError>:NoReturn at ??
0x10d3144b0: *Crystal::TypeParameter#solve<Crystal::NonGenericClassType>:Crystal::ASTNode+ at ??
0x10d3153e0: *Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::NonGenericClassType>:Crystal::Type+ at ??
0x10d30fd06: *Crystal::TypeDeclarationProcessor#process_owner_guessed_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::InstanceVarTypeInfo>:(Crystal::MetaTypeVar | Crystal::TypeDeclarationProcessor::Error | Nil) at ??
0x10d2d51e4: *Crystal::TypeDeclarationProcessor#process<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor) at ??
0x10d19d108: *Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor) at ??
0x10d199ca2: *Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+ at ??
0x10dcd9735: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x10dd7f8a9: *Crystal::Command#run_command<Bool>:Nil at ??
0x10c59b903: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x10c562b9d: main at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Environment:
```
 ± crystal -v
Crystal 0.22.0 (2017-04-20) LLVM 4.0.0
```

**Comment by faustinoaq** [comment] 2017-05-25 16:00
I can reproduce this.

The correct error would be
`can't infer the type parameter T for the generic class Channel(T). Please provide it explicitly`

**Comment by asterite** [comment] 2017-09-09 22:35
Duplicate of #4604

**Closed** 2017-09-15 15:13 UTC
Labels: kind:bug, topic:compiler
