### ISSUE TITLE
Add a .to_bool method?

### ISSUE THREAD

**Issue by Fryguy** [crystal-lang/crystal#7538] opened 2019-03-11 03:10 UTC
I propose that Crystal should have a to_bool method for when you need a literal boolean.  I recently saw a PR that used the `!!` notation, and while I completely understand it, as it's used in Ruby as well, it just has always felt like a hack because a `.to_bool` method didn't already exist (both in Ruby and Crystal).  Additionally, less-learned readers of Ruby and Crystal see that and don't understand what it means.  IMO, `.to_bool` is more explicit, and more clearly expresses intent, as opposed to `!!`.  What do you think?

**Comment by sudo-nice** [comment] 2019-03-11 07:15
>`.to_bool` is more explicit, and more clearly expresses intent

Absolutely agree. But there are drawbacks:

- `!!` is much less typing
- `!!` is consistent with Ruby
- if we kept the old `!!`, that would mean one had to learn that `!!` anyway, because some people would prefer `!!` over `.to_bool`

**Comment by straight-shoota** [comment] 2019-03-11 10:59
@sudo-nice `!` is a part of the language anyway, `!!` is just calling it twice.

I think I'd prefer having an explicit method for converting the truthiness of a value to a `Bool`. 

Maybe `#truthy?` would be better than `#to_bool` though. It more clearly communicates the meaning whereas `#to_bool` is less specific.

**Comment by sudo-nice** [comment] 2019-03-11 11:17
@straight-shoota sure, my point was, the current `!!` has advantages over proposed `to_bool` or `truthy?`

**Comment by Fryguy** [comment] 2019-03-11 14:24
- `!!` is consistent with Ruby

Even in the Ruby world I run into many people who see this and don't know what it is.  It arrived out of necessity...I am certain that if `to_bool` existed in Ruby from the beginning we would never have seen `!!`

**Comment by bcardiff** [comment] 2019-03-11 14:40
I won't call it `to_bool` because some might expect `0.to_bool` to be `true` and others `false`.

I like `truthy?` since it's something defined in the language semantics. But I worry if, it is a regular method that people will be able to override if that will add confusion.

I never liked much the `!!` idiom, so 👍 on my side for `#truthy?` but only if others find it useful.

**Comment by Fryguy** [comment] 2019-03-11 14:52
> I won't call it to_bool because some might expect 0.to_bool to be true and others false.

That's a good counter-example...I'm starting to lean towards `#truthy?` myself.

> But I worry if, it is a regular method that people will be able to override if that will add confusion.

I think the same argument could be made for `+` or a whole other slew of methods.  While it's possible to create confusing situations with flexible languages like Ruby and Crystal, in my experience developers rarely, if ever, actually do this.

**Comment by straight-shoota** [comment] 2019-03-11 16:11
This would add another method with specific meaning to all objects and which can be overridden by any type. That's similar to `#nil?`, `#try` and operators. There is obviously a potential for causing issues if this method is overridden, which might happen even involuntarily, if the meaning of `#truthy` is not commonly known.
There are already implementations of `#truthy?`, in the compiler there is `ASTNode#truthy?`, crinja has `Crinja::Value#truthy?`. These would need to be renamed if `#truthy?` would have a meta meaning.

For reference, I found https://github.com/sam0x17/truthy which defines a `#to_b` method that also converts strings and integers to `Bool` depending on their value. (it also includes a `#truthy?` alias)

**Comment by RX14** [comment] 2019-03-11 17:49
I was a bit on the fence, until I saw the `#truthy?` naming. Very :+1: on this.

**Comment by j8r** [comment] 2019-03-11 18:08
We will be able to use `!!my_var.truthy?` :grin:

**Comment by asterite** [comment] 2019-03-11 18:31
👎 from me. `!!` is not that common, it's intuitive (negate twice, `!` gives Bool so it works), and `truthy?` will introduce a breaking change.

**Comment by ysbaddaden** [comment] 2019-03-11 18:59
I'm a bit puzzled about this.

The `!!` idiom is short, simple and common to many languages. I'm not sure it happens much (but would love some numbers, maybe I'm wrong).

But `!!` is also unequivocal, just like `.nil?` (is nil). I'm afraid `.truthy?` is equivocal and could be confusing. For example we could consider the string `"false"` as not being truthy.

Rewriting `.nil?` is certain to be bad idea. Writing a custom `+` should be done with care... but overloading `.truthy?` doesn't seem as dangerous at first glance.

Maybe I'm just wrong and it's a matter of habit, like `.blank?`

**Comment by bcardiff** [comment] 2019-03-11 19:03
`.nil?` can't be redefined. The compiler ensures that. 

If `truthy?` is added my fear is that control structures like `if` and `while` have their semantics on the truthiness of the condition. If someone wants to define `MyNullObject#truthy?` won't do the trick. 

So `truthy?` should not be a normal method, but restricted to be defined. I guess that is the breaking change @asterite is referring to.

**Comment by asterite** [comment] 2019-03-11 19:14
@bcardiff That, but also in @straight-shoota 's [comment](https://github.com/crystal-lang/crystal/issues/7538#issuecomment-471607928) he mentions that `truthy?` already exists as a method in the compiler's source code and in other shards. So if we add `truthy?` in the standard library it will break those shards... or maybe not, but they'll probably have to rename that method to something else.

**Comment by Sija** [comment] 2019-03-11 20:14
I'd very much like to have `#present?` and `#blank?` in the stdlib (as in Rails' ActiveSupport) instead of `#truthy?` / `#falsey?`.

**Comment by bcardiff** [comment] 2019-03-11 20:34
@asterite yeap we agree, I don't see much problem to introduce that breaking change, but also not that much gain.

@Sija that's unrelated. present/blank treat empty space different than truthy.

**Comment by j8r** [comment] 2019-03-11 20:49
To answer @ysbaddaden's question: `grep '!!' $(find src -iname '*.cr') | wc -l` returns 53, and 62 for spec (but includes some comments and test strings with `!!`)

**Comment by Terottaja** [comment] 2019-03-27 18:47
I don't think this should be added, i mean really you're going to learn how '!' works anyways if you're going to program for more than a minute.  -1 from me.

**Comment by hanyuone** [comment] 2019-03-28 23:19
@Terottaja The problem is that it's not exactly intuitive how `!!` works - `!` only really makes sense on booleans, to negate it, and using `!!` to cast any type to a boolean isn't clear at first glance (negating something twice, what does that do?) It's better to be explicit in what you're doing with `#truthy?` than to use an implicit feature of the language.

**Comment by asterite** [comment] 2019-03-28 23:27
> negating something twice, what does that do?

falsey -> true -> false
truthy -> false -> true

**Comment by hanyuone** [comment] 2019-03-28 23:35
@asterite It was to illustrate a point, like new programmers may be confused as to what `!!` twice does :smile:

**Comment by Sija** [comment] 2019-03-29 08:36
@hanyuone new programmers may be confused by a lot of things :P

**Comment by straight-shoota** [comment] 2019-03-29 09:28
Just thinking here: Most uses of `!!` are casting either method return values or arguments. Would it be an option to have some automatic casting with appropriate type restrictions?
```cr
def valid? : Bool
  method_returns_falsey_or_truthy
end
```
I doubt such an implicit conversion would be a good idea, but wanted to share in case someone has a good idea about that.

**Comment by wontruefree** [comment] 2019-03-29 19:58
I don't think this will get any traction and I don't know anyone else who does this but I kind of like the idea of using `¡`.  so something like.

```crystal
def invalid?
  ¡errors
end
```

Downsides:
It is new syntax other languages don't use
Need to use a meta key to get the character

Upsides:
I think its intent makes sense
Reduces functions added to base object

**Comment by j8r** [comment] 2019-03-29 20:27
@wontruefree We know Crystal comes from Argentina. Nevertheless, I'm pretty sure most people think that's better to stick to ASCII, really.

I imagine this :smile: :
```cr
def ¿inválido?
  ¡errores!
end
```

**Comment by wontruefree** [comment] 2019-03-30 01:19
Yeah it kind of made me smile and I dont think it would ever be accepted.  But, It was interesting to think about and I didnt hate it.

**Comment by Terottaja** [comment] 2019-04-01 09:36
> @asterite I know what `!!` does, it was to illustrate a point, like new programmers may be confused as to what `!!` twice does

yeah well you could say that about anything, that's why you have to learn things to become better.

**Comment by hanyuone** [comment] 2019-04-01 09:39
@Terottaja The main point of my argument is to decrease the learning curve by introducing `#truthy?` instead of confusing a new user with `!!`. Like, I know this out of necessity, but there's no need for someone to use the `!` in a sort-of hacky way (my opinion).

**Comment by j8r** [comment] 2019-04-01 09:54
I'd vote to close for this following reasons:
- `!!` is overall rarely used (~100 times on the stdlib)
- this is a matter of preference
- this adds a new way to learn to do the same thing (unless is `!!` removed)

**Comment by straight-shoota** [comment] 2019-04-03 21:22
Closing per @j8r 

Thanks everyone for the constructive discussion!

**Closed by straight-shoota** 2019-04-03 21:22 UTC
Labels: kind:feature, topic:stdlib
