### ISSUE TITLE
Suprising break expression behaviour

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6548] opened 2018-08-16 14:24 UTC
```crystal
def foo
  loop do
    break "foo"
  end
end

def bar
  while true
    break "bar"
  end
end

puts foo # returns "foo"
puts bar # returns nil
```
Not sure if it's a bug, but it's very counter-intuitive either way.

**Comment by asterite** [comment] 2018-08-16 14:26
Duplicate of https://github.com/crystal-lang/crystal/issues/1277

**Closed** 2018-08-16 14:28 UTC
