### ISSUE TITLE
Nested rescue block overwrites variable

### ISSUE THREAD

**Issue by Ragmaanir** [crystal-lang/crystal#11917] opened 2022-03-22 17:12 UTC
This code:

```crystal
x = nil

begin
  begin
    raise "error"
  rescue e1
    x = e1
  end

  p x
rescue e2
end

p x
```
([carc.in](https://carc.in/#/r/cxgq))

Produces:

```
#<Exception:error>
nil # incorrect, this should be: #<Exception:error>
```

I would say that this is a bug?

When the code is modified slightly:

```crystal
x = nil
 
begin
  begin
    raise "error"
  rescue e1
    x = e1
  end
 
  p x
# rescue e2 # <- the only change
end
 
p x
```
([carc.in](https://carc.in/#/r/cxgr))

then the output is as expected:

```
#<Exception:error>
#<Exception:error>
```

This could maybe be somewhat related to #9769

Crystal 1.3.2 [932f193ae] (2022-01-18)
LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu
Linux Mint 20.3

**Comment by asterite** [comment] 2022-03-22 17:30
It's also a bit worse if you use an int instead of nil:

```crystal
x = 1

begin
  begin
    raise "error"
  rescue e1
    x = e1
  end
rescue
end

p x
```

That prints a random number.

Definitely a bug. I think the type at the end is incorrectly determined to be `Int32` instead of a union, but I didn't fully look into this.

**Comment by straight-shoota** [comment] 2022-03-22 17:33
I'm pretty sure this is not just related to #9769 but actually the same bug.

**Comment by asterite** [comment] 2022-03-22 17:51
Duplicate of #9769

**Comment by asterite** [comment] 2022-03-22 17:51
(I'll try to see if I can fix this this week, but others feel free to tackle this too as that might not happen!)

**Closed by asterite** 2022-03-22 17:51 UTC
Labels: kind:bug, topic:compiler:semantic
