### ISSUE TITLE
Formatter bug

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7345] opened 2019-01-30 01:27 UTC
Hello, I received an error message requesting that I report this bug when running `crystal tool format` on [this file, at this commit](https://github.com/dscottboggs/flix.cr/blob/e3c6cb0b4310e4f46ea5de5d6b3cda5442b728f8/spec/scanner/config_data/video_file_spec.cr). The error message is as follows:

```
Error: couldn't format './spec/scanner/config_data/video_file_spec.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

expecting ., not `NEWLINE, `, at :16:81 (Exception)
  from ???
```
with the last line repeated a bunch.

The offending code seems to be this statement:

```crystal
subject = Flix::Scanner::VideoFile
  .from_file_path?(TEST_FILES[:video_one].path, TEST_FILES[:video_one].info)
  .as Flix::Scanner::VideoFile
```

Thanks

**Comment by asterite** [comment] 2019-01-30 01:30
Duplicate of #6006

**Closed by asterite** 2019-01-30 01:30 UTC

**Comment by dscottboggs** [comment] 2019-01-30 01:32
ok sorry to bother then

**Comment by asterite** [comment] 2019-01-30 01:34
No, not at all! On the contrary, this is the second duplicate of the issue, it means it's kind of popular. And that pushes me more to fix it, which I will this week. My brevity was because I'm on a cellphone. Thank you!
