### ISSUE TITLE
Platform Support: Android, iOS, Web-assembly 

### ISSUE THREAD

**Issue by sirinath** [crystal-lang/crystal#8909] opened 2020-03-16 17:25 UTC
Regarding the [Platform Support](https://github.com/crystal-lang/crystal/wiki/Platform-Support) I believe Android, iOS, Web-assembly should be at a higher tier at least 2 but ideally, they should be tier 1. Windows should be a tier 1 platform. 

Also, there should be at least 1 BSD variant as a tier 1 platform.

**Comment by jhass** [comment] 2020-03-16 18:03
The is more of page is a status page, not a roadmap :) Also putting everything on the highest point takes out focus and makes such a categorization useless in the first place.

For a lot of discussion about WebAssembly support see #829.

This feels like something for our forum, [have a look at it](https://forum.crystal-lang.org). Meanwhile closing here since there's nothing technical to discuss really or if they would be then the issue is in too broad scope to do it effectively :)

**Closed by jhass** 2020-03-16 18:03 UTC
