### ISSUE TITLE
GC collects local variables in --release builds

### ISSUE THREAD

**Issue by pgkos** [crystal-lang/crystal#1646] opened 2015-09-29 17:01 UTC
I have noticed that the GC collects reachable toplevel local variables (EDIT: not only toplevel, see comment below), but only when building using `crystal build --release`. This causes problems when using native libraries (bindings).

The example is unfortunately quite complicated (sorry!). It uses the CrSFML library, but the problem should manifest itself while using other libraries too.

``` crystal
require "crsfml"

window = SF::RenderWindow.new(
  SF.video_mode(400, 600), "Title", style: SF::Titlebar | SF::Close
)

window.framerate_limit = 60

                          # replace with any valid local font path:
font = SF::Font.from_file("/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-L.ttf")
text_field = SF::Text.new("foo", font)
text_field.color = SF::Color::White

while window.open?
  # puts font  # uncommenting this line fixes the problem!
  window.clear SF::Color::Black
  window.draw text_field  # crash, "font" variable just got collected by the GC!
  window.display
  GC.collect  # to speed up the crash (segmentation fault)
end
```

As I have determined by debugging using `gdb`, inside the `while` loop the `font` variable is somehow treated as unreachable and gets collected by the garbage collector. As the `font` object contains a `@this` field which is a pointer to the native `sf::Font` C++ object, the native object also gets collected and that causes the segmentation fault inside the C++ SFML method `sf::Font::getTexture(int)`. That C++ method is invoked while drawing the text on the window.

Putting the `font` variable into use inside the loop (e.g. `puts font`) **completely fixes the problem**.

Interestingly, wrapping everything inside a class also fixes the problem, **but only when using instance variables**:

``` crystal
require "crsfml"

class MainClass
  def initialize
    @window = SF::RenderWindow.new(
      SF.video_mode(400, 600), "Title", style: SF::Titlebar | SF::Close
    )
    @window.framerate_limit = 60
    @font = SF::Font.from_file(
      "/usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-L.ttf")
    @text_field = SF::Text.new("foo", @font)
    @text_field.color = SF::Color::White
  end

  def run
    while @window.open?
      @window.clear SF::Color::Black
      @window.draw @text_field
      @window.display
      GC.collect  # does not crash
    end
  end
end

mainobject = MainClass.new
mainobject.run
```

**Comment by pgkos** [comment] 2015-09-29 19:10
The problem also occurs inside functions and inside methods of classes, when using only local variables (no fields).

**Comment by technorama** [comment] 2015-09-30 15:58
I'm not sure this is really a bug.  The compiler is free to reorder statements.  

Does Text.new retain a reference to font?  If not that's the real issue.

Take this example:
```
def foo
  font = ...
  SF::Text.new("foo", font)
end

text = foo
window.draw text # crash
```

If a reference is not retained by SF::Text the program will crash.

**Comment by ozra** [comment] 2015-09-30 16:10
Yes, if no references are kept in "Crystal-space" they will be collected. If passed to C-functions (which obviously don't play along with the GC) you must keep a reference "manually" (for instance in a class which stays alive), or call GC ref and the unref, to keep the reference in the GC "registry".

**Comment by ysbaddaden** [comment] 2015-09-30 20:11
So, it's not a bug, but it's still troublesome: Crystal code becomes unsafe (ie. will segfault), despite looking correct. I think at least the documentation should be updated to state that we must retain references to data initialized in Crystal but sent to an external library, to avoid the GC from collecting it.

**Comment by kirbyfan64** [comment] 2015-09-30 20:40
I really think the compiler is unsafely over-optimizing here, since `font` is clearly still reachable.

**Comment by technorama** [comment] 2015-09-30 21:02
It's not used again.  I see no reason why the compiler can't optimize it away if that is what's happening.

@ysbaddaden I wouldn't say this code is safe at all.  `window.draw` relies on data inside of `font` but no references are kept to it in `SF::Text`.  That's a bug.  There are many ways to change the code slightly where it will segfault randomly if the GC runs or shortly thereafter.

Any code that relies on internal pointers to data without keeping references risks crashing randomly.  Just because the optimizer triggered the problem this time doesn't mean it can't crash with other seemingly innocuous changes (any memory allocation or deallocation could trigger a crash).

**Comment by kirbyfan64** [comment] 2015-09-30 21:14
Here are my two ideas:

1. Add a function that adds a GC root from an arbitrary area of memory. Wrappers would have to invoke this method on blocks of memory to prevent the GC from freeing objects contained within.

2. Add a variable annotation kind of like `volatile` that prevents the compiler from deleting/toying with it. The annotation should be more well-defined than C's, though...

In the end, both should be added, but 2 is a good short-term solution.

**Comment by technorama** [comment] 2015-09-30 21:45
There is a way to keep the GC from toying with memory.  Keep a reference to the object.  Instance variables, class variables, constants, any of these would work.  Special keywords aren't necessary.

If `SF::Text` keeps internal pointers to `SF::Font` then it should keep a reference to the `Font` object also.

If fonts can never be free'd:
```
class SF::Font
  # Internal font pointers are passed to C functions.  Don't let the GC reclaim them.
  FONTS = [] of SF::Font

  def self.new
    obj = allocate_and_initialize
    FONTS << obj
    obj
  end
end
```

**Comment by Nakilon** [comment] 2015-10-01 07:10
This reminds me the thing I do in Ruby a lot:
```
my_lambda_function_with_memory = lambda do
  n = 0
  lambda do
    n += 1
  end
end.call
```
I love it.

**Comment by waj** [comment] 2015-10-01 20:40
As explained by @technorama, this is not a bug. When you write bindings to native libraries you must be careful to keep references of required objects.

@ysbaddaden the code looks correct but it depends on how the bindings are implemented. Writing native bindings is unsafe, and it's responsibility of the library writer to keep things working. Exactly the same problem happens in Ruby and many other languages.

**Comment by waj** [comment] 2015-10-01 20:42
@Nakilon I think this is completely out of topic, but you can do that in Crystal already:
```crystal
my_lambda_function_with_memory = -> do
  n = 0
  -> do
    n += 1
  end
end.call

puts my_lambda_function_with_memory.call # => 1
puts my_lambda_function_with_memory.call # => 2
puts my_lambda_function_with_memory.call # => 3

```

**Comment by asterite** [comment] 2015-10-01 20:46
For the specific case of crsfml, it seems that when you assign a font to a text, the text becomes the owner of it, so font shouldn't be released. Or maybe font needs to have some sort of reference counting (incremented when assigned to another crsfml object, decremented when the GC collects it or collects another object that has a reference to the font). I faced a similar issue with LLVM, where it seems that once you create a JIT compiler you can't dispose the module: you must only dispose the JIT. I fixed it [like this](https://github.com/manastech/crystal/blob/master/src/llvm/jit_compiler.cr#L5).

I know I mentioned ownership and reference counting, but these are issues that appear in Crystal only because they are also issues in C. There are ways to solve them while still having a GC (as I've done), so please don't suggest adding ARC, lifetimes or ownership to Crystal :-)

**Comment by sdogruyol** [comment] 2017-09-10 16:01
Is this a bug or an expected behaviour @asterite ?

**Comment by asterite** [comment] 2017-09-10 16:20
Not a bug. @waj's comment and my comment above explain this. The bindings should be written with GC and ownership in mind.

**Closed by asterite** 2017-09-10 16:20 UTC
Labels: kind:bug, topic:compiler

**Comment by kovalensky** [comment] 2025-04-02 04:58
> please don't suggest adding ARC, lifetimes or ownership to Crystal :-)

ARC doesn't require complete rewrite of the language and could be a secondary memory model.

Judging from the psychology of the newcomers, they don't know a dime about the garbage collection mechanism and heard that it significantly reduces performance.

Thus they start with other & more popular programming languages.
