### ISSUE TITLE
Evaluate macro variables before attempting string interpolation

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7028] opened 2018-11-05 18:23 UTC
### Example:

https://play.crystal-lang.org/#/r/5ftm

```crystal
macro no_interpolation(something)
  def does_not_work_{{something.id}}
    "#{{something.id}}"
  end
end

no_interpolation :like_this

puts does_not_work_like_this
```

### Workaround:

```crystal
macro no_interpolation(something)
  def works_{{something.id}}
    "#" + "{{something.id}}"
  end
end

no_interpolation :like_this

puts works_like_this
```

Because there's a workaround I realize this isn't too high priority of a fix but I thought I'd bring it up in case someone knows an easy way to fix this.

**Comment by bcardiff** [comment] 2018-11-05 18:54
I am not sure what you want, but the following has the same output without the `String#+` call.

https://play.crystal-lang.org/#/r/5fus

```crystal
macro no_interpolation(something)
  def does_not_work_{{something.id}}
    {{"\##{something.id}"}}
  end
end

no_interpolation :like_this

puts does_not_work_like_this
```

**Comment by straight-shoota** [comment] 2018-11-05 22:21
Shouldn't this work, too?

```cr
macro no_interpolation(something)
  def does_not_work_{{something.id}}
    "\#{{something.id}}"
  end
end

no_interpolation :like_this

puts does_not_work_like_this
```

It doesn't work as I'd expected (returns `#{{something.id}}`).

**Comment by straight-shoota** [comment] 2018-11-05 22:37
Anyway, this is a duplicate of #5287.

**Closed** 2018-11-06 00:50 UTC
