### ISSUE TITLE
Returning `StaticArray`s of specific sizes behaves weirdly

### ISSUE THREAD

**Issue by BlobCodes** [crystal-lang/crystal#13514] opened 2023-05-28 15:36 UTC
## Bug Report

Returning StaticArrays seem to behave very weirdly on `v1.8.2`, but only for specific sizes.

The following code does not compile:
```cr
a = uninitialized UInt8[65536]
```

Also on `play.crystal-lang.org`:
https://play.crystal-lang.org/#/r/f4p0

### System information

```sh
$ crystal -v
Crystal 1.8.2 [7aa5cdd86] (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

**Comment by HertzDevil** [comment] 2023-05-28 17:07
Duplicate of #4452

**Closed** 2023-05-28 17:08 UTC
Labels: kind:bug, topic:compiler:codegen
