### ISSUE TITLE
Select always expected to be invoked with a block?

### ISSUE THREAD

**Issue by Demonstrandum** [crystal-lang/crystal#5210] opened 2017-10-29 15:22 UTC
I tried to use select with the `.with_index` method, but the select method always expects a block:
```crystal
'Array(String)#select' is expected to be invoked with a block, but no block was given

  %w{ a b c d e f }.select.with_index { |_, i| i.odd? }
                    ^~~~~~
```
Perhaps adding a non-block version of  the function would be useful

**Comment by bew** [comment] 2017-10-29 18:46
There is no `with_index` method, you should look at the `select_with_index` method.

_Edit:_ `select_with_index` _is currently missing_
You can patch `Enumerable` to add it with:
```cr
module Enumerable(T)
  def select_with_index(&block : T ->)
    ary = [] of T
    each_with_index { |e, i| ary << e if yield e, i }
    ary
  end
end

%w(a b c d e f).select_with_index { |_, i| i.odd? } # => ["b", "d", "f"]
```

**Comment by Demonstrandum** [comment] 2017-10-29 20:48
@bew
Adding a `select_with_index` method was proposed, but denied in favour of using the `with_index` method.

However, it does not seem to work with `select`, however I tested and `each` does work.

See https://github.com/crystal-lang/crystal/pull/3869 on adding a `select_with_index` method.

I think it would be a good idea if `.with_index` work with more methods.

**Comment by RX14** [comment] 2017-10-29 22:22
We should just add `reject_with_index` methods.

**Comment by RX14** [comment] 2017-10-29 22:23
Actually, I never really understood why we couldn't just `yield elem, i` and obviate `with_index` methods.

**Comment by asterite** [comment] 2017-10-30 17:09
I don't think wanting to do `select_with_index`, or for that matter `map_with_index`, is very common. Let's not add a thousand methods with combinations. In fact maybe it would be wise to drop `map_with_index` and other `_with_index` methods.

For this case you can always do:

```crystal
%w{ a b c d e f }.each.with_index.select { |(_, i)| i.odd? }.map(&.[0]).to_a
```

Or just:

i = 0
%w{ a b c d e f }.select { |e| i.odd?.tap { i += 1 } }
```

It's a bit more writing, I know, but I doubt it's that common.

Also, duplicate of #3869.

**Closed by asterite** 2017-10-30 17:09 UTC
