### ISSUE TITLE
Derived class including nested modules with instance vars results in signal 11

### ISSUE THREAD

**Issue by spindlebink** [crystal-lang/crystal#10979] opened 2021-07-21 20:53 UTC
```crystal
module Base
  @base = 10
end

module Implementation
  include Base

  @impl = 10
end

class IncludesBase
  include Base
end

class Derived < IncludesBase
  include Implementation

  # @der = 10
end

d = Derived.new
```

Leads to a signal 11:

```
Invalid memory access (signal 11) at address 0x0
[0x55e643a96a56] *Exception::CallStack::print_backtrace:(Int32 | Nil) +118
[0x55e643a7e0fa] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +330
[0x7f8cdb552bb0] ???
[0x7f8cdc4fd403] _ZN4llvm11PointerType3getEPNS_4TypeEj +19
[0x7f8cdc404ca0] ???
[0x7f8cdc426022] ???
[0x7f8cdc435295] ???
[0x7f8cdc4351ed] LLVMBuildInBoundsGEP +77
[0x55e6449dc62a] *LLVM::Builder#inbounds_gep<LLVM::Value, LLVM::Value, LLVM::Value, String>:LLVM::Value +218
[0x55e644a1f6d1] *Crystal::CrystalLLVMBuilder#inbounds_gep<LLVM::Value, LLVM::Value, LLVM::Value, String>:LLVM::Value +241
[0x55e64496c4fb] *Crystal::CodeGenVisitor +91
[0x55e64496c48f] *Crystal::CodeGenVisitor +127
[0x55e64496f788] *Crystal::CodeGenVisitor +72
[0x55e64496f72f] *Crystal::CodeGenVisitor#aggregate_index<LLVM::Value, Int32>:LLVM::Value +47
[0x55e64498783b] *Crystal::CodeGenVisitor#instance_var_ptr<Crystal::Type+, String, LLVM::Value>:LLVM::Value +1355
[0x55e64499c6e5] *Crystal::CodeGenVisitor#run_instance_vars_initializers_non_recursive<Crystal::Type+, (Crystal::ClassType+ | Crystal::GenericClassInstanceType+), LLVM::Value>:Nil +725
[0x55e64499c401] *Crystal::CodeGenVisitor#run_instance_vars_initializers<Crystal::Type+, (Crystal::ClassType+ | Crystal::GenericClassInstanceType+), LLVM::Value>:Nil +289
[0x55e64499bb77] *Crystal::CodeGenVisitor#allocate_aggregate<Crystal::Type+>:LLVM::Value +1239
[0x55e64499b554] *Crystal::CodeGenVisitor#codegen_primitive_allocate<Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:LLVM::Value +244
[0x55e6449ac321] *Crystal::CodeGenVisitor#codegen_primitive<Crystal::Call, Crystal::Primitive+, Crystal::Def+, Array(LLVM::Value)>:Nil +545
[0x55e6449ab488] *Crystal::CodeGenVisitor#codegen_call<Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +232
[0x55e64499fd60] *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool +512
[0x55e643df00cd] *Crystal::ASTNode+ +4765
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e6449b6268] *Crystal::CodeGenVisitor#codegen_assign<Crystal::ASTNode+, Crystal::ASTNode+, Crystal::Assign>:(Bool | Nil) +296
[0x55e6449b5fae] *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) +462
[0x55e643defab9] *Crystal::ASTNode+ +3209
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e6449b5474] *Crystal::CodeGenVisitor#visit<Crystal::Expressions>:Bool +276
[0x55e643def404] *Crystal::ASTNode+ +1492
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e64498fa1b] *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+, Bool, Crystal::CodeGenVisitor::ModuleInfo, Bool, Bool>:LLVM::Function +3499
[0x55e6449a7b18] *Crystal::CodeGenVisitor#codegen_fun<String, Crystal::Def+, Crystal::Type+>:LLVM::Function +184
[0x55e6449a743c] *Crystal::CodeGenVisitor#target_def_fun<Crystal::Def+, Crystal::Type+>:LLVM::Function +412
[0x55e6449ab4e9] *Crystal::CodeGenVisitor#codegen_call<Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +329
[0x55e64499fd60] *Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool +512
[0x55e643df00cd] *Crystal::ASTNode+ +4765
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e6449b6268] *Crystal::CodeGenVisitor#codegen_assign<Crystal::ASTNode+, Crystal::ASTNode+, Crystal::Assign>:(Bool | Nil) +296
[0x55e6449b5fae] *Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil) +462
[0x55e643defab9] *Crystal::ASTNode+ +3209
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e6449b5474] *Crystal::CodeGenVisitor#visit<Crystal::Expressions>:Bool +276
[0x55e643def404] *Crystal::ASTNode+ +1492
[0x55e6449832a1] *Crystal::CodeGenVisitor#accept<Crystal::ASTNode+>:Nil +17
[0x55e643c4387f] *Crystal::Program#codegen<Crystal::ASTNode+, (Bool | Crystal::Compiler::EmitTarget | Nil), Crystal::Debug>:Hash(String, Crystal::CodeGenVisitor::ModuleInfo)+ +95
[0x55e643c4381a] *Crystal::Program#codegen:debug:single_module<Crystal::ASTNode+, Crystal::Debug, (Bool | Crystal::Compiler::EmitTarget | Nil)>:Hash(String, Crystal::CodeGenVisitor::ModuleInfo)+ +74
[0x55e644880af7] *Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil) +615
[0x55e64488564c] *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +188
[0x55e644afff99] *Crystal::Command::CompilerConfig#compile<String>:Crystal::Compiler::Result +57
[0x55e644af3a4f] *Crystal::Command#run_command<Bool>:Nil +415
[0x55e644aee1d1] *Crystal::Command#run:(Bool | Nil) +1217
[0x55e644aedbd9] *Crystal::Command::run<Array(String)>:(Bool | Nil) +25
[0x55e644aedb9d] *Crystal::Command::run:(Bool | Nil) +29
[0x55e643a5f82a] __crystal_main +2394
[0x55e6446605f6] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6
[0x55e644660405] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +53
[0x55e643a6acc6] main +6
[0x7f8cdb303cb2] __libc_start_main +242
[0x55e643a5ee0e] _start +46
[0x0] ???
```

There a few very specific features at play:
* At least two of the classes or modules need to have an instance variable. If there's an instance variable in *only* `Base`, `Implementation`, or `Derived`, everything's fine.
* With that said, `IncludesBase` can have an instance variable even if another structure has one too.
* The names of the instance variables must be different. If an instance variable in `Implementation` redefines one in `Base`, everything's fine.
* `Implementation` has to `include` `Base`. If it doesn't, everything's fine.
* Probably unrelated (should I open another report?) replacing `include Base` in `IncludesBase` with `extend Base` (different meaning, I know) results in `BUG: Class doesn't implement instance_vars (Exception)`.

My use case is a node tree structure whose nodes can each implement their own child hierarchy model tailored toward what the node needs.
* The bottom-level `Hierarchy` module provides some basic features and a couple of abstract methods for specializations to implement
* There are several specialized `Hierarchy` modules which `include Hierarchy` and implement `Hierarchy`'s abstract methods (e.g. `IndexedHierarchy`, `SingleChildHierarchy`)
* The abstract `Node` class includes `Hierarchy`--it doesn't care how derived classes implement hierarchy, so long as they do so
* The error in this report occurs when a derived node type includes a specialized `Hierarchy` module to fulfill the base `Node` class's `Hierarchy` requirements

I'm on Ubuntu 20.10 running the `master` branch. The error occurs with 1.0 as well, just with a much shorter error message.

[This issue](https://github.com/crystal-lang/crystal/issues/8188) might be related (similar traceback?), but the conditions seem different.

**Comment by straight-shoota** [comment] 2022-01-25 20:50
Duplicate of #11673

**Closed by straight-shoota** 2022-01-25 20:50 UTC
Labels: kind:bug, topic:compiler:semantic, topic:compiler:codegen
