### ISSUE TITLE
Error: Negative size (ArgumentError) while array#push

### ISSUE THREAD

**Issue by JunSuzukiJapan** [crystal-lang/crystal#5741] opened 2018-02-23 01:09 UTC
I encountered the following error in my project.

error message:

```
Negative size (ArgumentError)
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/pointer.cr:0:7 in 'realloc'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/array.cr:1778:7 in 'resize_to_capacity'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/array.cr:1772:5 in 'double_capacity'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/array.cr:1768:5 in 'check_needs_resize'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/array.cr:1344:5 in 'push'
  from src/observable.cr:18:11 in 'to_ary'
  from src/realloc_bug.cr:7:5 in '__crystal_main'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/crystal/main.cr:101:7 in 'main'
  from /usr/local/Cellar/crystal-lang/0.24.1_2/src/crystal/main.cr:135:3 in 'main'
```

My environment is

- macOS 10.13.3
- Crystal 0.24.1

Projects that made it as simple as possible is [https://github.com/JunSuzukiJapan/crystal_realloc_bug](https://github.com/JunSuzukiJapan/crystal_realloc_bug).

Clone this repository, and run ```crystal run src/realloc_bug.cr```, please.

[The essence of the problem](https://github.com/JunSuzukiJapan/crystal_realloc_bug/blob/master/src/realloc_bug.cr) is only two lines below, but no error will occur no matter which line is omitted.

```
a = ReallocBug::Observable.range(0, 5).repeat(3).to_ary
b = ReallocBug::Observable.from_array([4, 5, 6, 7, 8, 9, 10]).filter{|x| x % 2 == 1}.to_ary
```

These two lines have nothing to do with each other, why?

**Comment by petoem** [comment] 2018-02-25 17:55
I tried running this, could not reproduce your error.
After it prints out `start` the cursor stands still at the new line for a while, it starts to use a lot of system resource. It nearly froze my system (e.g. my mouse wasn't responding anymore), I exited with `Ctrl-C`.

OS is Arch Linux and Crystal 0.24.1.

**Comment by JunSuzukiJapan** [comment] 2018-02-26 01:47
@petoem 

Thank you for your reply.

Will you try the following?

First, rewrite　```src/realloc_bug.cr```  to 

```
require "./realloc_bug/*"
require "./*"

puts "start"

a = ReallocBug::Observable.range(0, 5).repeat(3).to_ary
puts a

puts "end"
```

This code print the result soon.
In my environment, this puts like below.

```
start
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
end
```

Next, rewrite　```src/realloc_bug.cr```  to  rewrite　```src/realloc_bug.cr```  to 

```
require "./realloc_bug/*"
require "./*"

puts "start"

b = ReallocBug::Observable.from_array([4, 5, 6, 7, 8, 9, 10]).filter{|x| x % 2 == 1}.to_ary
puts b

puts "end"
```

This code print the result soon.
In my environment, the result is

```
start
[5, 7, 9]
end
```

In each case, there is no problem.
But, original code, like below, causes an error.

```
require "./realloc_bug/*"
require "./*"

puts "start"

a = ReallocBug::Observable.range(0, 5).repeat(3).to_ary
b = ReallocBug::Observable.from_array([4, 5, 6, 7, 8, 9, 10]).filter{|x| x % 2 == 1}.to_ary

puts "end"
```

Why does an error occur even though the original code is a code combining above two codes together?

**Comment by petoem** [comment] 2018-02-26 07:42
I tried running only A and only B separate, it works and shows the expected output.
Running both together still doesn't work. 

I don't know why but your code seems to somehow run into a very long or infinite(?) loop.
Because of this you keep pushing new elements to the array, which causes two things.
- You use a lot of memory.
- Array `@capacity` variable will wraparound and become negative, when you have more elements than `Int32::MAX / 2`.

This is why [`resize_to_capacity`](https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L1775) fails when it calls `realloc`.

A shorter code to reproduce this error, would be: 
```
array = [] of UInt8

Int32::MAX.times do
  array.push 0_u8
end

# Just to make sure it fails, in case we haven't yet. :)
# Because of `double_capacity` we never reach this point.
array.push 0_u8
```
Output:
```
Negative size (ArgumentError)
  from /usr/lib/crystal/pointer.cr:0:7 in 'realloc'
  from /usr/lib/crystal/array.cr:1778:7 in 'resize_to_capacity'
  from /usr/lib/crystal/array.cr:1772:5 in 'double_capacity'
  from /usr/lib/crystal/array.cr:1768:5 in 'check_needs_resize'
  from /usr/lib/crystal/array.cr:1344:5 in 'push'
  from array_test.cr:4:3 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:11:3 in '_crystal_main'
  from /usr/lib/crystal/crystal/main.cr:112:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:101:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:135:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by RX14** [comment] 2018-02-26 11:33
Duplicate of #4011

**Closed** 2018-02-26 11:35 UTC
