### ISSUE TITLE
Better import modules/shards with different versioning

### ISSUE THREAD

**Issue by proyb6** [crystal-lang/crystal#6936] opened 2018-10-13 09:46 UTC
This idea is lacking in many programming languages afaik and would benefit Crystal to speed up development time, reduce technical debts and reliable user experience.

- A ```version checker``` idea could be useful for checking/auditing which source code is using outdated modules/shards version and recommendation the compatible version rather than constantly compile and throwing errors, imagine fixing bugs for the next decade years.
- What you ```import with versioning``` is what you get will reduce programmer errors
- Verbose namespace avoid making an assumption of which API implemented from (Ruby vs Rails https://railshurts.com/quiz/)
- Co-exist both old and new modules/shards to support stable and pilot testing.
- We could quickly upgrade our existing code without breaking the old API
- Prevent conflict API naming (PHP namespace)
- Reduce time and cost to support when we only need some features from newer modules/shards
- ```Breaking changes``` could this be is a thing of a past?

A use case is useful for the huge codebase, web frameworks, Content Management System that has different plugins/modules.

If C libraries have different versions in any operating system, my thought if we could do this:

```
require “module” namespace Module #No version, always use the latest module version
require “module@1.1” namespace Module1
require “module@2.0” namespace Module2
require “partialmodule@2.1” namespace PModule2_1
require “vendor@0.1” namespace Dev3

p Module1::Random::Api.hex(8)
p Module2::Random::Api.hex(8)
p Dev3::Random::Api.hex(8)
```

**Comment by ysbaddaden** [comment] 2018-10-13 11:03
Never happen in Crystal. Search for previously closed & refused issues about this topic.

> This idea is lacking in many programming languages

And for good reasons. The JS world is a sad proof how bad & ugly this design leads to.

**Comment by ysbaddaden** [comment] 2018-10-13 11:06
Duplicate of #4439

**Closed by ysbaddaden** 2018-10-13 11:06 UTC
