### ISSUE TITLE
Setting a C struct's member with type Void -> Void to nil crashes the compiler

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#8575] opened 2019-12-11 16:07 UTC
```cr
lib Library
  struct Struct
    member : Void -> Void
  end
end

library_struct = Library::Struct.new
library_struct.member = nil
```
```
Module validation failed: Call parameter type does not match function signature!
%Nil (void)* null
 %"->" = type { i8*, i8* }  %65 = call i8* @"~check_proc_is_not_closure"(%Nil (void)* null), !dbg !80
 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment] 2020-02-10 14:33
I think we should disallow `Void` as an argument type.

**Comment by jhass** [comment] 2020-05-08 04:54
Duplicate of #7279

**Closed by jhass** 2020-05-08 04:54 UTC
Labels: kind:bug, topic:compiler
