### ISSUE TITLE
Inconsistent error with initialization of instance variable

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#4147] opened 2017-03-15 13:33 UTC
Consider the following class (tested on crystal v0.21.0):
````crystal
class Test
 @bar = 42
  
  def initialize
    initialize("foo")
    @bar = 12
  end
  
  def initialize(@value : String)
    puts self.inspect
  end
end
````

Initializing this class fails with error message "'self' was used before initializing instance variable '@bar', rendering it nilable". If `inspect` is called without `self`, it works fine. That seems strange to me, since as far as I understand, omitting `self` should behave identically for calls to public methods since it is the implicit receiver.

It's even more confusing since `@bar` should actually be initialized in every constructor because of catch-all initialization. So the error message makes no sense at all. Changing the order of lines 5 and 6 (i.e. first overwriting initialization of `@bar`, then calling the other constructor) works with `self.inspect` as well. Even if the initialization will never be evaluated:
```crystal
  def initialize
    @bar = 12 if false
    initialize("foo")
  end
```
And then even this lead to failure:
```crystal
  def initialize
    initialize("foo")
    @bar = @bar
  end
```

I at first suspected it has something to do with the way the compiler determines how each instance variable is initialized by each constructor in a way, that each variable is only initialized once. But this seems somewhat unlikely, because there are also issues when a variable is not explicitly initialized by an individual constructor, but rather reuses its already initialized value.

**Comment by asterite** [comment] 2017-09-10 16:52
More or less duplicate of #1687

**Closed by asterite** 2017-09-10 16:52 UTC
