### ISSUE TITLE
Multiline proc formatting errors

### ISSUE THREAD

**Issue by hanneskaeufler** [crystal-lang/crystal#7341] opened 2019-01-28 19:16 UTC
Running 

```
crystal tool format bla.cr
```

on the following file `bla.cr` error.

```crystal
foo = ->{
  12
    .as(Int32)
    .to_s
}
```
It compiles fine and runs correctly but the formatter errors with 

```
Error: couldn't format 'bla.cr', please report a bug including the contents of it: https://github.com/crystal-lang/crystal/issues

expecting ., not `NEWLINE, `, at :2:5 (Exception)
  from Crystal::Formatter#check<Symbol>:Nil
  from Crystal::Formatter#format_cast<Crystal::Cast, Symbol>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::Formatter>:(Bool | Nil)
  from Crystal::Formatter#visit<Crystal::Call>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::Formatter>:(Bool | Nil)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::Formatter>:(Bool | Nil)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::Formatter>:(Bool | Nil)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::Formatter>:(Bool | Nil)
  from Crystal::format<String, String>:String
  from Crystal::Command#tool:(Bool | Nil)
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from __crystal_main
  from main
```

I distilled the code from a similar pattern of aligning 

```
Object
   .method_call
   .method_call
```

even inside a proc if it reaches my line length limit.

I reproduced both on my mac locally
```
Crystal 0.27.0 (2018-11-04)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

as well as on docker `latest` tag.

```
docker run -v $(pwd):/src crystallang/crystal:latest crystal -v
Crystal 0.27.0 [c9d1eef8f] (2018-11-01)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by hanneskaeufler** [comment] 2019-01-28 19:34
Huh, maybe it's now even the proc that makes this error, but the `.as(Type)`?
I can also reproduce with

```crystal
def erroring_mutation
  FakeMutation
    .new(reported_status: Crytic::Mutation::Status::Errored)
    .as(Crytic::Mutation::MutationInterface)
end
```

**Comment by sudo-nice** [comment] 2019-01-29 06:15
Might be related to: https://github.com/crystal-lang/crystal/issues/6006

**Comment by asterite** [comment] 2019-01-29 12:34
Duplicate of #6006

**Closed by asterite** 2019-01-29 12:34 UTC
