### ISSUE TITLE
enum : Int64 does not works as expected

### ISSUE THREAD

**Issue by Djok39** [crystal-lang/crystal#7362] opened 2019-02-02 00:53 UTC
https://play.crystal-lang.org/#/r/65a2
looks like it still have 32 bits internal
```
@[Flags]
enum Test : Int64
Val1
Val2
Val3
Val4
Val5
Val6
Val7
Val8
Val9
Val10
Val11
Val12
Val13
Val14
Val15
Val16
Val17
Val18
Val19
Val20
Val21
Val22
Val23
Val24
Val25
Val26
Val27
Val28
Val29
Val30
Val31
Val32
Val33
end
test = Test::All & Test.flags(Val31, Val32, Val33)
puts "Actual #{ test }"
puts "Should be Val31 | Val32 | Val33"
```

**Comment by bcardiff** [comment] 2019-02-02 02:52
Duplicate of #7268 

The workaround for know is to assign explicit values to each member.

**Closed by bcardiff** 2019-02-02 02:52 UTC
