### ISSUE TITLE
Process.run() not returning in forked process

### ISSUE THREAD

**Issue by pcoenen** [crystal-lang/crystal#6416] opened 2018-07-20 13:02 UTC
Hi,

I had an error in the following code:

```
stdout = IO::Memory.new
stderr = IO::Memory.new
Process.run("echo", args: {"hello"}, output: stdout, error: stderr)
puts stdout.to_s
puts stderr.to_s

while true
  puts "======================="
  puts "LOOP"
  puts "======================="
  fork_new_process()
  sleep 10
end

def fork_new_process()
  process = Process.fork()
  if process
    # Parent process continues
    return
  else
    # Child process
    stdout = IO::Memory.new
    stderr = IO::Memory.new
    puts "START"
    Process.run("echo", args: {"hello"}, output: stdout, error: stderr)
    puts "END"
    puts stdout.to_s
    puts stderr.to_s
    exit 0 # Exit on end
  end
end
```
The first time 'hello' is printed. In the forked process, 'hello' is never printed and the Process.run() doesn't even return since 'END' is never printed

```
Crystal 0.25.1 [b782738ff] (2018-06-27)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by pcoenen** [comment] 2018-07-20 13:38
Your code does not exactly the same as mine. Your code lets the parent process exit, but I want it to continue the loop. In your notation this would look line:

```
def fork_new_process()
  Process.fork do
    puts "START"
    Process.exec("echo", args: {"hello"})
    puts "END"
    exit 0
  end
end
```

This works fine, so already thanks a lot, but I still don't see why my code seems to fail.

**Comment by 98-f355-f1** [comment] 2018-07-20 22:43
I believe that in a forked process, once a process is forked with exec... it's gone.  There will not be any return value from the main program.  I goes on to its own life and fulfills its destiny.  The only return value is the pid and I'd make sure that you put in a wait to make sure the parent fulfills its role and kills its zombie child.

I did a quick debug on your code and the return value of run that you got is the Process::Status... so within that run function in the Process module.. it shows a new process that is waited on... it appears that your arguments are a little off, as it can take up to 9 arguments.  And if you look at the docs... argument 7 is a Pipe in the second run, as opposed to a different socket type in the one you are using. If Crystal acts like Java (which appears to be true) and discovers which run to use by the use of it's arguments, then you probably need to look into your arguments. 

If this function acts like a C function, this probably is the root of the problem.

That is far as what I can tell from this.

**Comment by 98-f355-f1** [comment] 2018-07-20 23:03
`i = 0
while i < 5
  puts "======================="
  puts "LOOP"
  puts "======================="
  fork_new_process()
  sleep 1
  i += 1
end

def fork_new_process()
  process = Process.fork() do
        # Child process
        puts "Child == #{Process.pid}"
        stdout = IO::Memory.new
        stderr = IO::Memory.new
        puts "START"
        x = Process.run("echo", arg : {"hello"}, output : stdout, error : stderr, String : nil)
        puts x
        puts "END"
        puts stdout.to_s
        puts stderr.to_s
        # exit 0 # Exit on end
  end
  puts "Parent == #{Process.ppid}"
  process.wait
end`

As you can see, I tweeked it a bit.  I wouldn't use an open loop, that is scary stuff, esp. on forking.  A hard fork creates a process, and since I don't believe you are waiting for the parent to wait, you could have a process on a process on a process..... etc.... infinity.

So, the part asking about the parent is pointless, unless you want to get a group Id or ppid or something from it.

=======================
LOOP
=======================
Parent == 3132
Process terminated true
Process terminated false
Child == 3825
START
Process::Status
Am I a ZOMBIE??? true
END
hello

Am I a ZOMBIE??? 3817: true
=======================
LOOP
=======================
Parent == 3132
Process terminated true
Child == 3827
Process terminated false
START
^C

This is the output that I got from top before CTRL C:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0    8304    132    104 S   0.0  0.0   0:00.14 init
 2495 root      20   0    8308     96     52 S   0.0  0.0   0:00.00 init
 2496 saleen    20   0   19804   8488   8388 S   0.0  0.1   0:00.30 bash
 2932 saleen    20   0   16136   1984   1432 S   0.0  0.0   0:02.55 top
 3131 root      20   0    8308    100     56 S   0.0  0.0   0:00.00 init
 3132 saleen    20   0   20204   8796   8704 S   0.0  0.1   0:00.50 bash
 3817 saleen    20   0   96308   2168   2052 S   0.0  0.0   0:00.03 test
 3827 saleen    20   0   96308   2036   1920 S   0.0  0.0   0:00.00 test
 3829 root      20   0    8308    100     56 S   0.0  0.0   0:00.00 init

After CTRL C, and top shows, ZOMBIELAND:
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0    8304    132    104 S   0.0  0.0   0:00.14 init
 2495 root      20   0    8308     96     52 S   0.0  0.0   0:00.00 init
 2496 saleen    20   0   19804   8488   8388 S   0.0  0.1   0:00.30 bash
 2932 saleen    20   0   16136   1984   1432 S   0.0  0.0   0:02.66 top
 3131 root      20   0    8308    100     56 S   0.0  0.0   0:00.00 init
 3132 saleen    20   0   20204   8796   8568 S   0.0  0.1   0:00.50 bash
 3829 root      20   0    8308    100     56 S   0.0  0.0   0:00.00 init
 3830 saleen    20   0   19804   8488   8392 S   0.0  0.1   0:00.32 bash
 4147 saleen    20   0   16136   1988   1436 R   0.0  0.0   0:00.16 top

as you can see, there are ZOMBIE children running around... got go and kill them now.
Your code needs to be refactored to work properly.

**Comment by asterite** [comment] 2018-07-20 23:15
**It seems `fork` is broken**

Ruby/Crystal:

```crystal
system "echo 0"

unless fork
  puts "before"
  system "echo 1"
  puts "after"
end
```

Ruby output:

```
0
before
1
after
```

Crystal output:

```
0
before
1
```

Note that "after" is missing.

This works as expected if you remove the first `system` call.

Most probably a duplicate of https://github.com/crystal-lang/crystal/issues/5236

**Comment by 98-f355-f1** [comment] 2018-07-20 23:25
@asterite some refactoring may be needed to the base code..

But I have successfully implemented the fork function in Crystal.

Here is my code: (it works on Ruby and Crystal) and gets similar results, albeit, Crystal is significantly faster.

`def main(num, limit)
  puts "Ready!"

  total_time = stopwatch_start()
  pids = [] of Process

  num.times do |i|

    natural = Natural.new
    puts natural.class
    primes = Primes.new(natural)
    prnt_cnt = 97

    puts "Start. . . . ."

    prime_ctr = 1 #{ count: 1 }
    puts "working....."

    start = stopwatch_start()
    pids << Process.fork do
      puts "Fork-baby #{i} #{Process.pid} is starting >>> "
  
      loop do
        p = primes.next

        if p & 0x1 == 1
          prime_ctr += 1

          if prime_ctr ^ prnt_cnt == 0
            puts "Fork-baby #{i+1} #{Process.pid} computed #{prime_ctr} primes in #{elapsed_time(start).to_f} seconds. The last one is #{p}"
            prnt_cnt <<= 1
          end
        end

        break if prime_ctr >= limit
      end

      puts "Fork-baby #{i+1} #{Process.pid} is ending <<< \n"
      puts "Fork-baby #{i+1} #{Process.pid} processed #{prime_ctr} prime numbers in #{elapsed_time(start).to_f} seconds"
      puts
    end
    # pid.wait
    # puts Process.times
  end

  waitall(pids)
  puts "#{num * limit} prime numbers: TOTAL #{num} PROCESS TIME(includes wait): #{elapsed_time(total_time).to_f} \/ AVERAGE: #{elapsed_time(total_time).to_f / num.to_f} seconds" 
end`

The waitall(pids) is where I made my own function for the parent to wait to reap all of the children as a group from the Array of pid.. Or you can just use it wait for one child at a time with wait.

**Comment by asterite** [comment] 2018-07-20 23:27
@98-f355-f1 does the code posted by @c910335 or by me work for your case the same in Ruby and Crystal? If not, that's a bug. It doesn't matter if your code works well, that means there's no bug in that scenario. But there's definitely a bug in these other scenarios... that's what a bug is, after all, some wrong behavior under certain scenarios.

**Comment by ysbaddaden** [comment] 2018-07-20 23:40
Yeah, it feels like a duplicate of #5326 that is that it's unrelated to fork itself but to exec. The executed program resets O_NONBLOCK of STDIN, STDOUT and STDERR that are shared with the parent and fork/exec process which generates weird behavior.

This shouldn't happen with #6068 or by redirecting the STDOUT of the exec program (workaround) for example.

**Comment by 98-f355-f1** [comment] 2018-07-21 00:01
@asterite I got the Ruby output... but I guess the issue is known.

**Comment by asterite** [comment] 2018-07-21 00:44
I guess we could try merging #6068, if others agree. The STDIN/STDOUT/STDERR is probably one of the most common errors users stumble upon, so any fix that works better than the current behavior is good.

**Comment by 98-f355-f1** [comment] 2018-07-21 02:07
@asterite I could look into this problem, take some time though. It looks like a bear to tackle.

I would like some clarification though about the wait function in the Process module.

Does it wait for a queue of the PIDs? there is the @wait_count class variable that looks like it increments for each fork that is released.  Is this the way it works? OR it seems to receive any exception handling errors?

As opposed to MRI C Ruby just iterates over all of the PIDs and nulls them

Would Crystal benefit from a waitall function? I could write one up.

**Comment by asterite** [comment] 2018-07-21 02:15
I don't have much idea about all of this, plus I didn't write it, so someone else should answer that.

**Comment by forksaber** [comment] 2018-07-21 03:09
### How Signals  are handled in Crystal
```crystal
# Psuedo code
@@r, @@w = IO.pipe

# called by kernel when the signal arrives
# the signal is immediately recorded and this function returns
def signal_handler(sig : Int32)
   @@w.write(sig)
end

# this fiber reads the recorded signals from the pipe
# and processes them
spawn do
   loop do
     sig = @@r.read_bytes(Int32)
     @@handlers[sig].call
   end
end
```
As part of ```Process.fork```, the after_fork handlers are called and a new pipe is created so that the forked process doesn't keep on reading/writing to parent's signal pipe.
Now, the issue is when ```Process.fork``` is called this fiber is still alive and in the middle of a ```read`` call on parent's pipe's read end. So, it will block until the pipe is closed or a signal arrives.

So, the fix is to close the parent's pipe in ```after_fork``` handler. So this works.

```crystal
module Crystal::Signal
  def self.after_fork
    @@pipe[0].close
    @@pipe[1].close
    previous_def
  end
end

system "echo 0"

unless fork
  puts "before"
  system "echo 1"
  puts "after"
end
```
### Output
```
0
before
1
after
```
**But**, this isn't an entirely correct solution. The reason for that is before ```Crystal::Signal.after_fork``` handler is called a call to ```Scheduler.after_fork``` is made. If that call ends up resuming the ```signal loop``` fiber ( which it doesn't currently but might if crystal were multi-threaded), then this loop fiber will have just stolen some signals from the parent until the pipe is closed.

The correct solution would be to either keep only the forking fiber alive after fork or disabling fork without exec all together.

**Comment by RX14** [comment] 2018-07-21 17:05
@ysbaddaden the original example always redirects output and error to IOs though.

**Comment by RX14** [comment] 2018-07-21 17:06
I'm sure this will turn out to be fork and waitpid/signal handing interacting.

**Closed** 2018-09-06 15:18 UTC
