### ISSUE TITLE
Handle [CMD/CTRL]+S on Playground

### ISSUE THREAD

**Issue by matiasgarciaisaia** [crystal-lang/crystal#5672] opened 2018-02-02 12:44 UTC
When working on Crystal's Playground (`crystal play`, then visit http://localhost:8080/), I usually tend to hit `CMD+S` when trying something (the `Save file` shortcut in nearly every GUI text editor out there).

But, as I am in a browser, I end up with the browser's `Save page` dialog - which I don't want at all.

It would be nice to handle this shortcut in the playground, probably as an alternative shortcut for `Run` - usually, if I save a file in the editor is because I'm going to try it. But I'm open to discuss that - I can expect arguments for linking that shortcut to some "Save the current code snippet _somewhere_" feature (download a `snippet-#{timestamp}.cr` file? Create a Gist?). I'd prefer that to be a not-that-common shortcut (maybe `SHIFT+[CMD/CTRL]+S` downloads the snippet?).

But, in any case, downloading the page's HTML code doesn't seem a common enough use case to give it a shortcut.

**Comment by bcardiff** [comment] 2018-02-02 13:25
The playground has a save button when hover the run button. Also if you setup a GitHub Access Token in the settings page you can save/share as gist. 

I would say that making CMD+S to save the file as the download is an expected behaviour.

**Comment by vlazar** [comment] 2018-02-06 18:39
Looking into something to do for Crystal... Is there a consensus on this issue already?

BTW are there plans to make playground more future reach for Crystal 1.0 or is it minimalistic by design and you prefer to keep it this way? For example https://play.rust-lang.org/ has more features, other playgrounds can be inspirational too.

**Comment by matiasgarciaisaia** [comment] 2018-02-08 18:11
Hi @vlazar!

I don't think there'll be consensus until we see a PR and have to decide wether to merge it or not. I also think that, whenever a PR comes, the worst case scenario is that we want to implement the opposite action for the shortcut - so most of the work would get accepted anyway.

If you want to hack on this - I personally think it would be a nice thing to have. And maybe it isn't _that much_ work - so you're not wasting a year's work if we don't accept this for whatever reason.

Regarding features - they are not there probably just because no one implemented them. I don't think it is a decision to keep it "minimalistic". Not to bloat it either, but there probably are features missing that we would like to have - maybe open an issue for discussing them, or even a PR to show an example?

Anyway, thanks for willing to help with this :)

**Comment by CaDs** [comment] 2018-02-18 00:44
I will give this issue a try, if that is ok :)

**Comment by CaDs** [comment] 2018-03-01 23:23
@matiasgarciaisaia I did open a PR for this a couple of weeks ago.  Please take a look if you have the time.

**Comment by matiasgarciaisaia** [comment] 2018-03-02 03:37
Sorry, @CaDs - haven't seen it.

Thanks for the work - I've merged the PR.

I'd say we just close the issue. Should anyone feel that CMD+S shouldn't run but actually save (or something else), a new issue will probably pop up.

**Comment by CaDs** [comment] 2018-03-02 23:44
@matiasgarciaisaia sure, no problem about closing the issue. 
Thanks for taking the time to review and merge the PR 👍

**Closed** 2018-03-03 14:35 UTC
Labels: community:newcomer, kind:feature, topic:playground
