### ISSUE TITLE
Segmentation fault with long ARGV

### ISSUE THREAD

**Issue by kyku** [crystal-lang/crystal#9791] opened 2020-10-02 18:39 UTC
The following program crashes with 11 when given command line of about 193998 bytes:

```
ARGV.each do |arg|
  puts arg
end

```

I'm using default crystal from Arch linux:
$ crystal -v                
Crystal 0.35.1 (2020-06-21)

$ uname -a
Linux kyku 5.8.12-arch1-1 #1 SMP PREEMPT Sat, 26 Sep 2020 21:42:58 +0000 x86_64 GNU/Linux

LLVM: 10.0.0
Default target: x86_64-pc-linux-gnu

It seems that the signal arises from stack exhaustion:
...

> #124956 0x00007ffff7d4650d in GC_generic_malloc () from /usr/lib/libgc.so.1
> #124957 0x00007ffff7d46875 in GC_malloc_kind_global () from /usr/lib/libgc.so.1
> #124958 0x00005555555df97d in malloc (size=32) at /usr/lib/crystal/gc/boehm.cr:110
> #124959 0x00005555555a59d5 in __crystal_malloc64 (size=32) at /usr/lib/crystal/gc.cr:24
> #124960 0x00005555555e300b in *Thread::LinkedList(Fiber)@Thread::LinkedList(T)::new:Thread::LinkedList(Fiber) ()
> #124961 0x00005555555e1f2f in fibers () at /usr/lib/crystal/fiber.cr:48
> #124962 0x00005555555b0d69 in -> () at /usr/lib/crystal/fiber.cr:80
> #124963 0x00005555555b0e73 in -> () at /usr/lib/crystal/primitives.cr:255
> #124964 0x00007ffff7d3b397 in ?? () from /usr/lib/libgc.so.1
> #124965 0x00007ffff7d3d11d in ?? () from /usr/lib/libgc.so.1
> #124966 0x00007ffff7d41a8a in ?? () from /usr/lib/libgc.so.1
> #124967 0x00007ffff7d41eaf in ?? () from /usr/lib/libgc.so.1
> #124968 0x00007ffff7d42148 in ?? () from /usr/lib/libgc.so.1
> #124969 0x00007ffff7d424df in ?? () from /usr/lib/libgc.so.1
> #124970 0x00007ffff7d4650d in GC_generic_malloc () from /usr/lib/libgc.so.1
> #124971 0x00007ffff7d46875 in GC_malloc_kind_global () from /usr/lib/libgc.so.1
> #124972 0x00005555555df97d in malloc (size=32) at /usr/lib/crystal/gc/boehm.cr:110
> #124973 0x00005555555a59d5 in __crystal_malloc64 (size=32) at /usr/lib/crystal/gc.cr:24                                                                                                              
> #124974 0x00005555555e300b in *Thread::LinkedList(Fiber)@Thread::LinkedList(T)::new:Thread::LinkedList(Fiber) ()
> #124975 0x00005555555e1f2f in fibers () at /usr/lib/crystal/fiber.cr:48
> #124976 0x00005555555b0d69 in -> () at /usr/lib/crystal/fiber.cr:80
> #124977 0x00005555555b0e73 in -> () at /usr/lib/crystal/primitives.cr:255
> #124978 0x00007ffff7d3b397 in ?? () from /usr/lib/libgc.so.1
> #124979 0x00007ffff7d3d11d in ?? () from /usr/lib/libgc.so.1
> #124980 0x00007ffff7d41a8a in ?? () from /usr/lib/libgc.so.1
> #124981 0x00007ffff7d41eaf in ?? () from /usr/lib/libgc.so.1
> #124982 0x00007ffff7d42148 in ?? () from /usr/lib/libgc.so.1
> #124983 0x00007ffff7d424df in ?? () from /usr/lib/libgc.so.1
> #124984 0x00007ffff7d47764 in GC_generic_malloc_many () from /usr/lib/libgc.so.1
> #124985 0x00007ffff7d479d3 in GC_malloc_kind () from /usr/lib/libgc.so.1
> #124986 0x00005555555df4bd in malloc_atomic (size=43) at /usr/lib/crystal/gc/boehm.cr:115
> #124987 0x00005555555df49c in malloc_atomic (size=43) at /usr/lib/crystal/gc.cr:76
> #124988 0x00005555555ce2d3 in new (chars=0x7ffffffe2b75 "CSV/20200831_OB_556912_ADR.csv", bytesize=30, size=0) at /usr/lib/crystal/string.cr:239
> #124989 0x00005555555ce14b in new (chars=0x7ffffffe2b75 "CSV/20200831_OB_556912_ADR.csv", bytesize=30) at /usr/lib/crystal/string.cr:208
> #124990 0x00005555555ce100 in new (chars=0x7ffffffe2b75 "CSV/20200831_OB_556912_ADR.csv") at /usr/lib/crystal/string.cr:194
> #124991 0x00005555555b226c in ~ARGV:init () at /usr/lib/crystal/crystal/system/unix/event_loop_libevent.cr:71
> #124992 0x000055555567847f in once (self=0x7ffff7a1afe0, flag=0x55555569d6f0 <ARGV:init>, initializer=0x5555555b2150 <~ARGV:init>) at /usr/lib/crystal/primitives.cr:255
> #124993 0x00005555555a59a8 in __crystal_once (state=0x7ffff7a1afe0, flag=0x55555569d6f0 <ARGV:init>, initializer=0x5555555b2150 <~ARGV:init>) at /usr/lib/crystal/crystal/once.cr:50
> #124994 0x00005555555a38c6 in __crystal_main () at /usr/lib/crystal/kernel.cr:48
> #124995 0x000055555567922d in main_user_code (argc=6259, argv=0x7ffffffc2848) at /usr/lib/crystal/crystal/main.cr:105
> #124996 0x0000555555679085 in main (argc=6259, argv=0x7ffffffc2848) at /usr/lib/crystal/crystal/main.cr:91
> #124997 0x00005555555b0c9d in main (argc=6259, argv=0x7ffffffc2848) at /usr/lib/crystal/crystal/main.cr:114

**Comment by asterite** [comment] 2020-10-02 18:48
I think this is a duplicate of #8951

**Closed** 2020-10-03 13:21 UTC
