### ISSUE TITLE
Cannot use super.to_s in enum

### ISSUE THREAD

**Issue by silverweed** [crystal-lang/crystal#1329] opened 2015-08-30 17:30 UTC
Apparently, the [Enum class](https://github.com/manastech/crystal/blob/master/src/enum.cr) doesn't currently allow using the original `to_s` method, e.g. when overriding:
 
```crystal
enum MyEnum
        Foo
        Bar

        # the following code fails
        def to_s
                super.to_s.downcase
        end
end
```

This fails with:
```
Error in /opt/crystal/src/enum.cr:27: expanding macro

  macro def to_s : String
            ^~~~

in /opt/crystal/src/enum.cr:28: unknown macro instance var: '@enum_flags'

    {% if @enum_flags %}
          ^~~~~~~~~~~
```

As far as I can understand, the user-defined class cannot access the `@enum_flags` used in the macro of the parent's `to_s`.

Am I doing something wrong when overriding or is this a bug?

**Comment by waterlink** [comment] 2015-08-30 18:34
This works though: http://carc.in/#/r/d84

**Comment by waterlink** [comment] 2015-08-30 18:35
Or not really..

**Comment by waterlink** [comment] 2015-08-30 18:51
Played around a bit, and any variation of this code: http://carc.in/#/r/d90 - causes compiler errors and compile-time segfaults.

**Comment by javajax** [comment] 2016-03-05 22:17
I just ran the supplied code and it seems to work.
https://carc.in/#/r/to4

Are you still seeing this issue?

**Comment by jhass** [comment] 2016-03-05 22:28
Actually calling `to_s` then still fails though: https://carc.in/#/r/to5

**Comment by javajax** [comment] 2016-03-06 01:23
so in more reading about overloading the `to_s` it seems like you should overload `to_s(io)` that seems to work in a weird way but no compiler bugs.
https://carc.in/#/r/tru

It seems like `@type.constants` is not populated when expanding the macro.  I have found a work around but I don't know why that is not available when the macros are being expanded.

**Comment by jhass** [comment] 2016-03-06 08:23
Same issue still if you actually call it: https://carc.in/#/r/try

**Comment by asterite** [comment] 2016-03-06 13:41
The problem is that `Enum#to_s` is actually:

```crystal
struct Enum
  macro def to_s : String
    # ...
  end
end
```

A regular `enum` implicitly extends `Enum`... calling `super` on a `to_s` method ends up instantiating that method in `Enum`, and it doesn't have `@enum_flags`, nor it has enum members, because it's the base class.

In short, it makes no sense to invoke `super` there.

Solution:

```crystal
enum MyEnum
  Foo
  Bar

  def to_s
    {% for member in @type.constants %}
      return {{member.stringify.downcase}} if self == {{member}}
    {% end %}
    value.to_s
  end
end

p MyEnum::Foo.to_s
p MyEnum::Bar.to_s
```

I'll close this. If someone comes up with an idea on how to reuse `super` here, please reopen.

**Closed by asterite** 2016-03-06 13:41 UTC
Labels: bug, compiler
