### ISSUE TITLE
Crystal 1.10 cannot be installed on Ubuntu/arm64

### ISSUE THREAD

**Issue by jochenseeber** [crystal-lang/crystal#14103] opened 2023-12-16 11:00 UTC
## Bug Report

I tried to install Crystal 1.10 on Ubuntu as described in [Official Crystal deb repository](https://crystal-lang.org/install/on_ubuntu/):

```
docker run -i -t ubuntu:22.04 /bin/bash
apt-get update
apt-get install curl gpg
echo "deb http://download.opensuse.org/repositories/devel:/languages:/crystal/xUbuntu_22.04/ /" >/etc/apt/sources.list.d/crystal.list
curl -fsSL "https://download.opensuse.org/repositories/devel:languages:crystal/xUbuntu_22.04/Release.key" >/etc/apt/trusted.gpg.d/crystal.asc
apt-get update
apt-get install crystal
```

Output:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 crystal : Depends: crystal1.10 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Additional observations:

* Installing Crystal 1.9 with `apt-get install crystal1.9` works.
* Homebrew does not work on ARM, so that does not work either

**Comment by straight-shoota** [comment] 2023-12-16 11:39
Sorry, there are no official aarch64 packages available at the moment. You may use community-provided packages from https://packagecloud.io/84codes/crystal

Duplicate of #9833

**Closed by straight-shoota** 2023-12-16 11:39 UTC
Labels: kind:bug

**Comment by jochenseeber** [comment] 2023-12-21 15:22
Is there a reason why there are no official ARM images? Can we somehow help with this?
