### ISSUE TITLE
Returning `Array(Int32)` errors if method should return `Array(Int32 | String)`

### ISSUE THREAD

**Issue by akadusei** [crystal-lang/crystal#7178] opened 2018-12-11 22:51 UTC
While this works: https://play.crystal-lang.org/#/r/5ro7

```crystal
def foo(x : Array(Int32 | String))
  typeof(x)
end

# I can pass a Array(Int32) to a method that expects Array(Int32 | String)
puts  foo([1]) #=> Array(Int32)
```
But this gets a compile error: https://play.crystal-lang.org/#/r/5rmy

```crystal
def foo : Array(Int32 | String)
  [1]
end

puts foo
```
Output:

```
Error in line 5: instantiating 'foo()'

in line 18: type must be Array(Int32 | String), not Array(Int32)
```

I was kinda hoping returning `Array(Int32)` from a method that expects a return type of `Array(Int32 | String)` should pass.

**Comment by straight-shoota** [comment] 2018-12-11 22:59
This is covariance vs contravariance. See #3803 and related issues.

**Comment by asterite** [comment] 2018-12-11 23:16
As @straight-shoota says, it's indeed covariance and contravariance.

Right now there's a bit of inconsistency of what `Array(Int32 | String)` means depending on when you write it: a type restriction, a return value, the type of an instance variable. No decision has been taken yet.

But yeah, essentially a duplicate of #3803, so closing.

**Closed by asterite** 2018-12-11 23:16 UTC
