### ISSUE TITLE
[travis] nightly build gets stuck on [Y/N] prompt

### ISSUE THREAD

**Issue by waterlink** [crystal-lang/crystal#2400] opened 2016-04-02 22:30 UTC
The relevant config looks like this:

```yaml
sudo: required
dist: trusty

language: crystal
crystal:
  - nightly
```

Example failing build: https://travis-ci.org/trapped/sqlite_adapter.cr/builds/120331175

**Comment by jhass** [comment] 2016-04-03 09:33
Duplicate of https://github.com/travis-ci/travis-ci/issues/5808

**Closed by jhass** 2016-04-03 09:33 UTC

**Comment by waterlink** [comment] 2016-04-03 11:01
Thanks!
