### ISSUE TITLE
"too many block arguments" error when multiple constructors of the same class take block arguments

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6725] opened 2018-09-15 02:31 UTC
```crystal
class C
  def initialize(&f : String, Int32 ->)
  end

  def initialize(&f : Symbol ->)
  end
end

C.new { |a, b| }
```

> Error in line 9: instantiating 'C.class#new()'
> 
> in line 9: too many block arguments (given 2, expected maximum 1)

**Comment by bcardiff** [comment] 2018-09-15 04:10
This is the expected behavior. The second definition overrides the first one.

The block signature does not participate in the signature of the method, it only matters if there is or not a block.

When a method yields multiple arguments, the caller can discard some or all of them.

**Comment by straight-shoota** [comment] 2018-09-15 07:03
Duplicate of #5090

**Closed** 2018-09-15 10:05 UTC
Labels: status:invalid
