### ISSUE TITLE
Please add operators 'and' , 'or'

### ISSUE THREAD

**Issue by pannous** [crystal-lang/crystal#3421] opened 2016-10-14 23:14 UTC
Please add rubyish english operators
 `and` , `or`
instead of
`&&, ||`

**Comment by airinfection** [comment] 2016-10-14 23:29
I did

a = true
b = true  (false)

if a && b 
puts "true"
else
puts "false"
end

and it works.

**Comment by pannous** [comment] 2016-10-14 23:32
if a and b
 puts "no nice pythonic / ruby'ish / english operators :("

**Comment by asterite** [comment] 2016-10-14 23:57
Sorry, duplicate of #1449

What about `a ||= b`? This, `a or= 1`, looks kind of strange.

**Closed by asterite** 2016-10-14 23:57 UTC

**Comment by pannous** [comment] 2016-10-15 00:04
Why not add them as synonyms for && and || with the same precedence and without special meaning ???

We can rather abolish ||= which isn't even syntactic 'suggar'.

**Comment by ysbaddaden** [comment] 2016-10-15 10:40
The reason is to avoid duplicates (two different ways to do the same, exact, thing), and avoid a confusion with Ruby where they have a different behavior.

**Comment by RX14** [comment] 2016-10-15 11:00
After a while you learn to read `&&` and `||` as "and" and "or" in your head anyway.

**Comment by pannous** [comment] 2016-10-15 11:01
ok makes sense. 

Lesson learned: english is a bad substitute for math.
```
true or true and false
 => false
true || true && false
  => true
```

Do you want sugar or precision?
Yes

**Comment by pannous** [comment] 2016-10-15 11:02
> After a while you learn to read && and || as "and" and "or" in your head anyway.

@RX14 exactly that's why I am so shocked about rubies misbehavior.
