### ISSUE TITLE
Compiler variable type bug

### ISSUE THREAD

**Issue by Heaven31415** [crystal-lang/crystal#4935] opened 2017-09-08 12:13 UTC
Hi, if you try to compile this code, you will get a nasty error (I tried to search for it, but I'm not sure whether it is related to the issues I have found):

```
class Foo
  @bar = @baz = 1

  def initialize
    puts "#@bar, #@baz"
  end
end

foo = `Foo.new
```
I have tested this code on my Ubuntu 16.04 desktop with Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1 and on playground [(link)](https://play.crystal-lang.org/#/r/2onv) they both have yielded the same result:

```
BUG: `` at  has no type
0x5bb9fe: ??? at ??
0x7a237d: ??? at ??
0xd49bae: ??? at ??
0xd48e8d: ??? at ??
0xd3f528: ??? at ??
0xd37027: ??? at ??
0xd1a432: ??? at ??
0xd2fc41: ??? at ??
0xd170b4: ??? at ??
0xd16b69: ??? at ??
0xd29913: ??? at ??
0xd2d99c: ??? at ??
0xd37044: ??? at ??
0xd1a432: ??? at ??
0xd2fc41: ??? at ??
0xd170b4: ??? at ??
0xd16b69: ??? at ??
0xcd7cdb: ??? at ??
0x102b0e5: ??? at ??
0x1098cbe: ??? at ??
0x611436: ??? at ??
0x5e1dac: main at ??
0x7f4dd7c1e830: __libc_start_main at ??
0x5bb20d: ??? at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by straight-shoota** [comment] 2017-09-08 12:25
Putting `@bar = @baz = 1` into the constructor works.
Your puts string should probably be  `"#{@bar}, #{@baz}"`

```crystal
class Foo
  def initialize
    @bar = @baz = 1
    puts "#{@bar}, #{@baz}"
  end
end

foo = Foo.new
```
[carc.in](https://carc.in/#/r/2oo2)

**Comment by asterite** [comment] 2017-09-08 12:43
Duplicate of #3368

**Closed by asterite** 2017-09-08 12:43 UTC
