### ISSUE TITLE
make spec doesn't link

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#8556] opened 2019-12-05 01:27 UTC
Running `make spec` yields this (ubuntu 19.10)

```
$ ./bin/crystal ./spec/all_spec.cr 
...
/root/.cache/crystal/crystal-run-all_spec.tmp: symbol lookup error: /root/.cache/crystal/crystal-run-all_spec.tmp: undefined symbol: __libc_start_main, version Array(T)#double_capacity:Pointer(Tuple(Int32 | Nil, Array(Int32)))
$ ./bin/crystal -v
Using compiled compiler at .build/crystal
Crystal 0.32.0-dev [ef53f4c45] (2019-12-05)

LLVM: 7.0.1
Default target: x86_64-pc-linux-gnu
```

Not sure if I'm doing something wrong...

**Comment by Blacksmoke16** [comment] 2019-12-05 01:30
IIRC wasn't there an issue with llvm `7.0.1`?  Solution would be to use 8 or drop down to 7 I think?

**Comment by rdp** [comment] 2019-12-05 01:55
with 8.0.1 I seem to get this similar message, FWIW:

```
/root/.cache/crystal/crystal-run-all_spec.tmp: symbol lookup error: /root/.cache/crystal/crystal-run-all_spec.tmp: undefined symbol: __libc_start_main, version Array(T)#double_capacity:Pointer(Tuple(Int32 | Nil, Array(Int32)))
```

**Comment by straight-shoota** [comment] 2019-12-05 10:18
Maybe it's a corrupt cache issue. Try `rm -rf /root/.cache/crystal`

**Comment by rdp** [comment] 2019-12-05 14:27
OK tried it but seemed to get same result...19.10 ubuntu VM.

**Comment by straight-shoota** [comment] 2019-12-05 15:05
How did you get to compile with llvm 7? Ubuntu 19.10 ships with llvm 9 by default.
Can you provide reproducible instructions?

**Comment by rdp** [comment] 2019-12-06 06:51
oops, looks like I had manually installed lllvm-7 package.
Not sure why but if it finds 7 it seems to prefer it over the "default non numbered":

```
$ llvm-config --version
9.0.0
crystal_git $ make
Using /usr/bin/llvm-config-7 [version=7.0.1]
...
```
After removing 7 so I only have 9, it still gives
```
.build/all_spec: symbol lookup error: .build/all_spec: undefined symbol: __libc_start_main, version Hash(K, V)#entry_matches?<Hash::Entry(String, Crystal::FileModule), UInt32, (String | Nil)>:Bool
```

`make std_spec compiler_spec` links fine.

So basically just clone it, run `make spec`, it should fail to link?? :)

**Comment by RX14** [comment] 2019-12-07 01:11
This is a duplicate of #7177.

**Closed by RX14** 2019-12-07 01:11 UTC
