### ISSUE TITLE
Semantic (abstract def check) freezes

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#3156] opened 2016-08-14 23:10 UTC
When trying to compile [this repo](https://github.com/KCreate/livechat.cr/tree/24126bdf3a9e96384dd86715c37011a1ab0afa88) the compilation freezes.

I don't know what causes this but here is the output of the build command:

```
❯ crystal build src/main.cr --stats
Parse:                             00:00:00.0655490 (  20.84MB)
Semantic (top level):              00:00:00.1102560 (  35.79MB)
Semantic (new):                    00:00:00.0011450 (  35.79MB)
Semantic (abstract def check):    ^C
```

I waited about 4-5 minutes before cancelling.

An idea why this could happen?

**Comment by asterite** [comment] 2016-08-14 23:41
It seems this alias is problematic:

```cr
alias RecStringHash = Hash(String, String | RecStringHash)
```

I'm still not sure if that alias should compile or not, as it doesn't have a base, non-recursive type. On master it crashes the compiler instead of hanging indefinitely.

Regardless of the bug, do you need a recursive hash there? `@permissions` seems to be a hash of string to boolean... maybe a hash is not even needed in this case.

**Comment by KCreate** [comment] 2016-08-15 13:46
Weird, this doesn't compile
```crystal
alias RecStringHash = Hash(String, String | RecStringHash)
```
but this however does:
```crystal
alias RecStringHash = String | Hash(String, RecStringHash)
```

The second one matches a `Hash(String, String)` AND `String`, while the first one should only match a recursive Hash.

**Comment by KCreate** [comment] 2016-08-15 14:05
Shouldn't this work?
```crystal
alias A1 = String | Hash(String, A1)

def a1_only(arg : A1)
end

a1_only({ "name" => "Leonard" })
```

Gives me:
```
Parse:                             00:00:00.0403670 (  15.74MB)
Semantic (top level):              00:00:00.0258380 (  20.99MB)
Semantic (new):                    00:00:00.0005030 (  20.99MB)
Semantic (abstract def check):     00:00:00.0004680 (  20.99MB)
Semantic (type declarations):      00:00:00.0048480 (  27.99MB)
Semantic (cvars initializers):     00:00:00.0006240 (  27.99MB)
Semantic (ivars initializers):     00:00:00.0001990 (  27.99MB)
Semantic (main):                  Error in ./test.cr:6: no overload matches 'a1_only' with type Hash(String, String)
Overloads are:
 - a1_only(arg : A1)

a1_only({ "name" => "Leonard" })
^~~~~~~
```

**Comment by asterite** [comment] 2016-08-15 16:32
{...} of String => A1

**Comment by KCreate** [comment] 2016-08-15 19:10
A1 could be both a String or a Hash(String, A1). So Hash(String, String) should match A1

Could you please explain this?

**Comment by asterite** [comment] 2016-08-15 19:49
https://github.com/crystal-lang/crystal/issues/3064#issuecomment-236169557

**Comment by KCreate** [comment] 2016-08-15 22:51
Now I understand, thanks a lot!

**Comment by Maroo-b** [comment] 2019-04-13 11:19
This isn't reproducible with Crystal version 0.27.2. Should we close this issue?

**Closed** 2019-04-13 11:21 UTC
Labels: kind:bug, topic:compiler
