### ISSUE TITLE
Crystal API docs sidebar bad README indentation

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal#5940] opened 2018-04-11 01:10 UTC
On https://crystal-lang.org/api/0.24.2/index.html

![screenshot_20180410_200738](https://user-images.githubusercontent.com/3067335/38591131-d2ae2182-3cfa-11e8-9e81-0139b6d1a891.png)

Versus master: https://crystal-lang.org/api/master/index.html

**(See README indentation)**

![screenshot_20180410_200827](https://user-images.githubusercontent.com/3067335/38591153-efb6d38c-3cfa-11e8-91e3-6c345ded34f2.png)

/cc @straight-shoota @RX14 @ysbaddaden @oprypin

**Comment by faustinoaq** [comment] 2018-04-11 01:11
In master API the README looks unaligned

**Comment by straight-shoota** [comment] 2018-04-11 06:34
Yeah, that's because the search feature was intended to be based on #4755 but was merged without it

#5816 should fix that.

**Comment by sdogruyol** [comment] 2018-04-13 06:56
Fixed via https://github.com/crystal-lang/crystal/pull/5816

**Closed by sdogruyol** 2018-04-13 06:56 UTC
Labels: kind:bug, topic:docs
