### ISSUE TITLE
Dead code in crystal sources

### ISSUE THREAD

**Issue by bew** [crystal-lang/crystal#3801] opened 2016-12-30 02:59 UTC
While reading the crystal's lexer source I've found that `Crystal::Lexer#next_char_check_line` is not used anywhere, and thus, should be removed.

Generally speaking, even if the crystal compiler, when compiling itself, will remove unused code, don't you think there shouldn't be dead code in the crystal sources ?

Maybe we could add a flag when building (or as a tool) to spot unused code in the codebase ?

**Comment by asterite** [comment] 2016-12-30 12:49
The main issue is that `next_char_check_line` is not marked as private, so even if we add dead-code detection the compiler wouldn't know if that method is intended to be public API. So solving this is not as trivial as it may sound.

**Comment by bcardiff** [comment] 2016-12-30 12:52
Such tool is actually a coverage one. I started a POC for that to detect untested methods. It's something useful, but pretty slow for big projects.

**Comment by bcardiff** [comment] 2016-12-30 13:54
The initial POC tool is at https://github.com/bcardiff/crystal/tree/feature/tool-unreachable if someone want to pick it up (and have some fun).

**Comment by faustinoaq** [comment] 2018-05-16 20:04
Interesting issue, Maybe [ameba](https://github.com/veelenga/ameba) can help with this :wink:  /cc @veelenga

**Comment by veelenga** [comment] 2018-05-16 20:50
@faustinoaq it is actually on the [roadmap](https://github.com/veelenga/ameba/wiki) but far away from the working solution...

**Comment by straight-shoota** [comment] 2023-08-23 14:44
I have started to revive this effort.

The prototype from https://github.com/crystal-lang/crystal/issues/3801#issuecomment-269774018 basically still works.  :rocket: It only needed some minor updates for modern Crystal.

However, it's pretty basic and only covers simple standard defs. I was able to enhance the tool for some additional cases (yield, generics, previous_def, virtual).

But there are still a lot of false positives, some are hard to identify.

One issue I have discovered is with `super` calls. They don't have `target_defs` set, so the super def won't be identified as reachable.

Another issue I have seen while inspecting the compiler source code ([output](https://gist.github.com/straight-shoota/b89af7fbbbfbf7158ae7e78923485b8b)): That some types (e.g. `Crystal::ASTNode`, `Crystal::Type`, `Crystal::Transformer`) have a lot of defs show up as false positives. `ASTNode` and `Type` are abstract, so that might be an indication. But I have also confirmed that defs in abstract classes are properly identified in general. Maybe some other issue with virtualization? I'm not sure at this moment and could use a pointer here if anyone has and ideas on this.

My enhanced code is available: https://github.com/crystal-lang/crystal/compare/master...straight-shoota:crystal:feat/tool-unreachable

**Comment by straight-shoota** [comment] 2023-08-25 20:50
I found another hidden gem, also from @bcardiff: https://github.com/bcardiff/crystal-tool-demo/blob/master/src/unused.cr
It basically still works with current master, just needs the following patch:
```diff
--- i/src/unused.cr
+++ w/src/unused.cr
@@ -26,7 +26,7 @@
 # src/file.cr:5:1 ~> top-level bar
 # ```

-require "compiler/crystal/**"
+require "compiler/requires"
 include Crystal
```

This implementation seems to be more to the point. It modifies the compiler's `Def` data structure to add a back reference from a typed def to the untyped def.
I suppose that's a reason why it's implemented as a separate tool instead of being integrated directly into the compiler. I don't think this should prevent us from integrating it as a compiler tool, though.

The output and instructions are available here: https://gist.github.com/straight-shoota/6f915b2cd601211c9bfcb7c682f4e694
I haven't validated the results yet. The list is actually similar to the previous one.

**Comment by Sija** [comment] 2023-08-25 20:57
It would be enhanced by grouping the items by visibility + getters/setters/abstract/other defs

**Comment by straight-shoota** [comment] 2023-08-25 20:59
Yeah, that would be the next step. First we have to ensure it's actually reporting the right things. But the tool demo looks promising 👍

**Comment by bcardiff** [comment] 2023-08-25 22:24
I'm glad it helps. We also do back references on the lookup definition tool in a way it does not impact the main compiler IIRC. Maybe we could do something similar to that.

I mostly did the tool demo to experiment what is possible. And the unused tool was used on a sponsor codebase to do some cleanup.

But in general for coverage I also think that integrating with llvm-cov might offer more benefits. Although that would give use runtime coverage and you want static one. But maybe from llvm code with coverage information a static projection can be generated 🤔

**Comment by straight-shoota** [comment] 2023-08-26 10:30
Yeah, I agree that runtime coverage is probably more useful in general.
But static analysis is certainly more definite. If code is unreachable, it's definitely unused. Then it's clear that it can as well be removed.
Code that is technically reachable but never actually executes can have various reasons and might be more difficult to remove because it may still matter for typing.

**Comment by straight-shoota** [comment] 2023-09-08 14:22
While working on #13783 I have encountered some edge cases.
One of them is this:
```cr
class Foo
  @foo : Int32

  def initialize
    @foo = 1
  end
end

class Bar < Foo
  def initialize
    @foo = 2
  end
end

Bar.new
```

`Foo#initialize` is never called so the tool considers it unreachable. But its definition is necessary for a valid program.
Removing it results in the following error message:
> instance variable '<span>@</span>foo' of Foo was not initialized directly in all of the 'initialize' methods, rendering it nilable. Indirect initialization is not supported.

I think it's probably fine to consider it unreachable (because it is), yet it cannot be simply removed.

**Comment by beta-ziliani** [comment] 2023-09-08 14:31
This is perfectly fine. I think we need to document that "unreachable" is not "removing this will make the program compile fine". The tool just points out the unnecessary stuff, then the dev should do the cleaning manually.

**Closed** 2023-09-26 20:51 UTC
Labels: kind:feature, topic:compiler, community:help-wanted
