### ISSUE TITLE
llvm-config: error: components given, but unused

### ISSUE THREAD

**Issue by sdogruyol** [crystal-lang/crystal#2555] opened 2016-05-05 16:38 UTC
I've just compiled Crystal from the master to test out 0.16.0.

İ'm getting the following error when running any crystal command

```
llvm-config: error: components given, but unused

usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root LLVM was built from.
  --obj-root        Print the object root used to build LLVM.
  --bindir          Directory containing LLVM executables.
  --includedir      Directory containing LLVM headers.
  --libdir          Directory containing LLVM libraries.
  --cppflags        C preprocessor flags for files that include LLVM headers.
  --cflags          C compiler flags for files that include LLVM headers.
  --cxxflags        C++ compiler flags for files that include LLVM headers.
  --ldflags         Print Linker flags.
  --system-libs     System Libraries needed to link against LLVM components.
  --libs            Libraries needed to link against LLVM components.
  --libnames        Bare library names for in-tree builds.
  --libfiles        Fully qualified library filenames for makefile depends.
  --components      List of all possible components.
  --targets-built   List of all targets currently built.
  --host-target     Target triple used to configure LLVM.
  --build-mode      Print build mode of LLVM tree (e.g. Debug or Release).
  --assertion-mode  Print assertion mode of LLVM tree (ON or OFF).
Typical components:
  all               All LLVM libraries (default).
  engine            Either a native JIT or a bitcode interpreter.
Using compiled compiler at .build/crystal
```

P.S: The program actually works.

**Comment by asterite** [comment] 2016-05-05 18:14
In which platform? And what's your LLVM version?

**Comment by asterite** [comment] 2016-05-05 18:15
Also, how did you compile crystal from master?

**Comment by sdogruyol** [comment] 2016-05-05 18:16
Ah i forgot to add those here it is.

Mac OS X 10.11.2
LLVM 3.6.2

Compiled with

```
make clean
make crystal
```

First time seeing this error

**Comment by asterite** [comment] 2016-05-05 18:16
And what's your current crystal version, 0.15.0?

**Comment by sdogruyol** [comment] 2016-05-05 18:19
Yes

**Comment by asterite** [comment] 2016-05-05 18:25
I can't reproduce this.

Can you post here all the commands you typed, including the one that triggers the error?

By the way, 0.16.0 will be released soon, so maybe this isn't a big issue.

**Comment by asterite** [comment] 2016-05-05 18:26
I also found [this](https://llvm.org/bugs/show_bug.cgi?id=13430), which might suggest it's an LLVM bug and there's something configured in a different way in your case.

**Comment by kostya** [comment] 2016-05-05 18:32
same error, just checkout to master from 370c2f13 (here is ok)
```
make clean crystal
rm -rf .build
rm -rf ./doc
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
c++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/local/bin/llvm-config-3.6 --cxxflags`
cc -fPIC   -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
llvm-config: error: components given, but unused
....
```

**Comment by asterite** [comment] 2016-05-05 18:36
@kostya Do you mean this?

```
git checkout 370c2f13abd968a47bcfc45d861f77b86a579717
make clean crystal
```

It works fine for me. I still don't understand how to reproduce the problem, sorry.

**Comment by kostya** [comment] 2016-05-05 18:36
in 370c2f13a ok, in master error

**Comment by kostya** [comment] 2016-05-05 18:37
even this
```
git co 370c2f13abd968a47bcfc45d861f77b86a579717
./bin/crystal --version
Crystal 0.15.0 (Fri Apr  1 18:39:41 UTC 2016)

git co master
./bin/crystal --version
llvm-config: error: components given, but unused

usage: llvm-config <OPTION>... [<COMPONENT>...]
```

**Comment by asterite** [comment] 2016-05-05 18:42
@waj found a typo [here](https://github.com/crystal-lang/crystal/commit/00f1efa98af59816e61bbad292cebf7b3179c570#diff-90c25d52067645b7c1da382fd7ef478dR118) it says "lllvm" with three "L". If you change that to two "L"s, does it work?

**Comment by asterite** [comment] 2016-05-05 18:45
By the way, I tried all of this:

```crystal
$ git describe
0.16.0
$ git rev-parse HEAD
fc89c1aeaa7ce2443ac2f3c10a5adcf96bef23ec
$ make clean
rm -rf .build
rm -rf ./doc
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
$ which crystal
/usr/local/bin/crystal
$ crystal --version
Crystal 0.15.0 (Fri Apr  1 17:57:09 UTC 2016)
$ uname -ms
Darwin x86_64
$ bin/crystal --version
Crystal 0.15.0 (Fri Apr  1 17:57:09 UTC 2016)
$ make crystal
c++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/local/bin/llvm-config --cxxflags`
cc -fPIC   -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
$ bin/crystal --version
Using compiled compiler at .build/crystal
Crystal 0.16.0 [fc89c1a] (Thu May  5 18:40:40 UTC 2016)
$ cat foo.cr 
puts "Hello!"
$ bin/crystal foo.cr 
Using compiled compiler at .build/crystal
Hello!
```

**Comment by kostya** [comment] 2016-05-05 18:50
bagged commit by bisect 00f1efa98af59816e61bbad292cebf7b3179c570, 3l to 2l not change anything

**Comment by asterite** [comment] 2016-05-05 18:54
The strange this is that it doesn't happen to me.

What's your output of this?

```
command -v llvm-config-3.6 lllvm-config36 lvm-config-3.5 llvm-config35 llvm-config
```

And then, using that result, doing `... --version` and `... --host-target`?

**Comment by sdogruyol** [comment] 2016-05-05 18:56
@asterite 

```
➜  ~ command -v llvm-config-3.6 lllvm-config36 lvm-config-3.5 llvm-config35 llvm-config
/usr/local/bin/llvm-config-3.6
/usr/local/bin/llvm-config
➜  ~ /usr/local/bin/llvm-config-3.6 --version
3.6.2
➜  ~ /usr/local/bin/llvm-config-3.6 --host-target
x86_64-apple-darwin15.2.0
```

**Comment by asterite** [comment] 2016-05-05 18:59
Hm, but two results. I only have one results. Maybe that's the issue?

```
$ /usr/local/bin/llvm-config /usr/local/bin/llvm-config-3.6 --host-target
x86_64-apple-darwin15.4.0
llvm-config: error: components given, but unused
```

**Comment by asterite** [comment] 2016-05-05 19:01
So let's not worry about this. This was a workaround until 0.16.0, it will be gone once we release it (which should happen very soon). Then we'll remove those lines from the Makefile and everything will be working fine again :-)

**Comment by ysbaddaden** [comment] 2016-05-05 19:47
I'm sorry I broke the build!

There is indeed a double typo in the line outlined by asterite: one lllvm and one lvm, and it may also be miss a `| head -n 1` to only select the first matched command.

**Closed** 2016-05-05 22:48 UTC
