### ISSUE TITLE
Get list of methods for particular class

### ISSUE THREAD

**Issue by greyblake** [crystal-lang/crystal#2095] opened 2016-02-01 19:03 UTC
Hi! Is it possible to get list of methods for particular class/object? Something like `Object#methods` in ruby.
Or is there way to do it in static way?
Or in anyway?:)

Thanks!

**Comment by asterite** [comment] 2016-02-01 19:08
See #403

**Comment by jhass** [comment] 2016-05-27 16:08
Closing as a duplicate of #403.

**Closed by jhass** 2016-05-27 16:08 UTC
Labels: question
