### ISSUE TITLE
Bug with signal trap

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#5830] opened 2018-03-16 05:20 UTC
Code to reproduce this bug (need interactive terminal):

```crystal
system("echo call a subprocess")

Signal::INT.trap do
  puts "Canceled by user"
  exit
end

puts "Press CTRL+C"
gets
```

## Expected behavior

Print "Canceled by user" and exit the program 

## Current behavior

Do nothing when you press Ctrl+C

## Environment

Tested on MacOS with Crystal  0.24.1 / LLVM 5.0.1

## Additional notes

Happens when a child process is created through backslash quote or `system` call.

**Comment by NIFR91** [comment] 2018-05-03 23:00
Same problem 

```text
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
with code 

```
at_exit{ puts "Terminated"} 
Signal::INT.trap { exit } 
puts "Infinite Loop" 
loop { } 
```

Expected behavior:  
exit and print "Terminated" when sending interrupt signal with `kill -int [pid]`  or Ctrl+C

Current behavior:
block in trap is never executed, and the program continues execution.

---

The program works with 
```
at_exit{ puts "Terminated"} 
# Signal::INT.trap { exit } 
LibC.signal Signal::INT.value,->(s : Int32){ exit } 
puts "Infinite Loop" 
loop { } 
```

The program exit and print "Terminated" after `kill -int [pid]` or Ctrl+C

**Comment by ysbaddaden** [comment] 2018-05-04 12:48
@NIFR91 this is unrelated to the initial issue, and this can't work in Crystal: signals are handled through the event loop; you can't use signal handling to exit a busy loop in crystal, because the busy loop prevents the event loop to resume and handle the signal... Inserting a `sleep 0` or anything IO related inside the busy loop will do the job.

Note that you need crystal master for the `at_exit` block to be actually run (and thus print `Terminated`).

**Comment by ysbaddaden** [comment] 2018-05-04 13:26
Initial issue fixed in ff56d94.

**Comment by NIFR91** [comment] 2018-05-04 15:56
@ysbaddaden , yes, you are right i didn't think it thoroughly. Maybe in my program i never yield to the event loop, ill check it. I can confirm this issue  is fixed.

**Comment by ysbaddaden** [comment] 2018-05-05 18:41
Duplicate of #2713.

**Closed** 2018-07-06 22:07 UTC
