### ISSUE TITLE
Attempt to bind a C library resulted in a compiler error

### ISSUE THREAD

**Issue by sherjilozair** [crystal-lang/crystal#5996] opened 2018-04-23 19:43 UTC
This is the line which caused the error: https://github.com/sherjilozair/cudnn.cr/blob/master/spec/cudnn_spec.cr#L18

**The relevant pieces of code are:**

```
describe CuDNN do
 it "allocates memory" do
   p = ::CuDNN.malloc(100)
   p.should be_a(Pointer(Void))
 end
end
```
 
**which calls**

```
module CuDNN
 extend self
 def malloc(size)
   check_success(LibCUDA.malloc(out ptr, size))
   return ptr
 end
end
```
 
**which calls**
 
```
@[Link("cudart")]
lib LibCUDA
 enum ErrorT
   Success
 end
 fun malloc = cudaMalloc(ptr : Void**, size : LibC::Int) : ErrorT
end
```

**The error is:**

```
Module validation failed: Incorrect number of arguments passed to called function!
  %0 = call %"String::Builder"* @"*Pointer(Void)@Object::to_s<String::Builder>:String::Builder"(i32 %obj, %"String::Builder"* %self), !dbg !148
 
???
???
???
???
???
???
???
???
 
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
 
```

**Comment by straight-shoota** [comment] 2018-04-27 10:53
If module validation fails, it's a compiler bug, regardless of whether the input is valid or not.

`p` is not a keyword but a global method. It shouldn't be an issue if you name a local variable `p`.

**Comment by asterite** [comment] 2018-04-27 19:57
Note that the reduce code doesn't reproduce the bug. Someone will have to remove the real bug from the git repo.

**Comment by sherjilozair** [comment] 2018-04-27 20:45
@bararchy fixed this on the repository, so he might have more information on how to extract the bug.

**Comment by straight-shoota** [comment] 2020-12-06 14:26
Closing, there's no reproducible code. This has likely been fixed in the meantime.

**Closed by straight-shoota** 2020-12-06 14:26 UTC
Labels: kind:bug, topic:compiler

**Comment by HertzDevil** [comment] 2021-12-22 12:10
Duplicate of #8544 (which is not fixed, see latest comment)
