### ISSUE TITLE
Class variable from parent to child

### ISSUE THREAD

**Issue by Nephos** [crystal-lang/crystal#2594] opened 2016-05-14 18:02 UTC
Hello,
I've one question about this code

https://play.crystal-lang.org/#/r/ygh

```crystal
class A
  @@c : UInt32
  @@c = 0_u32
  
  @id : UInt32
  getter id
  
  def initialize
    @id = (@@c += 1)
  end
  
end

class B < A
  def initialize
    super
  end
end
```

```text
Error in line 26: instantiating 'B:Class#new()'

instantiating 'B#initialize()'

in line 16: instantiating 'super()'

in line 9: Can't infer the type of class variable '@@c' of B

The type of a class variable, if not declared explicitly with
`@@c : Type`, is inferred from assignments to it across
the whole program.

The assignments must look like this:

  1. `@@c = 1` (or other literals), inferred to the literal's type
  2. `@@c = Type.new`, type is inferred to be Type
  3. `@@c = Type.method`, where `method` has a return type
     annotation, type is inferred from it
  4. `@@c = arg`, with 'arg' being a method argument with a
     type restriction 'Type', type is inferred to be Type
  5. `@@c = arg`, with 'arg' being a method argument with a
     default value, type is inferred using rules 1, 2 and 3 from it
  6. `@@c = uninitialized Type`, type is inferred to be Type
  7. `@@c = LibSome.func`, and `LibSome` is a `lib`, type
     is inferred from that fun.
  8. `LibSome.func(out @@c)`, and `LibSome` is a `lib`, type
     is inferred from that fun argument.

Other assignments have no effect on its type.

Can't infer the type of class variable '@@c' of B
```

I understand the issue if @@c was used in B.initialize but, as it is in A.initialize I'm not sure.

PS: I already resolved this with a class method in A

**Comment by asterite** [comment] 2016-05-16 23:21
Right now class variables are not inherited, so the error is actually valid. There's no `@@c` for `B`.

**Comment by kostya** [comment] 2016-05-16 23:27
you can use global variables and macro inherited for this: https://play.crystal-lang.org/#/r/ymo

**Comment by asterite** [comment] 2016-05-17 12:38
Also related or kind of duplicate of #916

**Closed by asterite** 2016-05-17 12:38 UTC
Labels: bug, compiler
