### ISSUE TITLE
strange sigfault in 0.21

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#4079] opened 2017-02-25 06:13 UTC
with shard https://github.com/kostya/myhtml
```crystal
require "myhtml"
p Myhtml.version_string
```

```
~/crystal-0.20.5-1/bin/crystal 1.cr
"0.17 (libmyhtml 3.0.1)"
```

```
~/crystal-0.21.0-1/bin/crystal 1.cr
Invalid memory access (signal 11) at address 0x0
[5671965] __crystal_sigfault_handler +61
[41857780] sigfault_handler +40
[140343694294192] ???
[140343678837599] ???
[20835650] ???
[20854506] ???
[21147658] ???
[21212011] ???
[20989632] ???
[21161936] ???
[20992072] ???
[20990565] ???
[21122903] ???
[21147635] ???
[21212011] ???
[20989632] ???
[21203584] ???
[20989632] ???
[21204477] ???
[20989632] ???
[21203584] ???
[20989632] ???
[21203584] ???
[20989632] ???
[21122903] ???
[21147635] ???
[21212011] ???
[20989632] ???
[21204477] ???
[20989632] ???
[20990565] ???
[20645285] ???
[29255557] ???
[29913929] ???
[5892694] ???
[5670349] main +18269
[140343677687661] __libc_start_main +237
[5486641] ???
```

i tried to reduce it more, but no luck

**Comment by kirbyfan64** [comment] 2017-02-25 16:38
Maybe related to #4078?

**Comment by ysbaddaden** [comment] 2017-02-26 12:10
Confirmed, duplicate of #4078

**Closed by ysbaddaden** 2017-02-26 12:10 UTC

**Comment by ysbaddaden** [comment] 2017-02-26 12:14
The resulting LLVM validation error:
```
Module validation failed: Stored value type does not match pointer operand type!
  store %0 %3, { i64, i64 }* %0, !dbg !14
 { i64, i64 }
```
