### ISSUE TITLE
Expose a file's inode

### ISSUE THREAD

**Issue by weirdbricks** [crystal-lang/crystal#13634] opened 2023-07-04 22:08 UTC
## Feature Request

It would be great if we could get the inode of a file directly - currently I use this to get a file's inode: 

```
ic
ic(1.8.0):001> File.info("/tmp/goat").to_s.split("@st_ino=")[1].split(",")[0].to_i
 => 28313375
```

Thanks!

**Comment by weirdbricks** [comment] 2023-07-04 22:26
... that's beautiful. Thanks @z64 !!

I still think it would be cool to get the same without having to add a method though, so I'll leave this issue open as a feature request.

**Comment by Blacksmoke16** [comment] 2023-07-04 22:29
Duplicate of #8357

**Closed by Blacksmoke16** 2023-07-04 22:29 UTC
Labels: kind:feature
