### ISSUE TITLE
Yet another segfault with proc variable capture

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#9970] opened 2020-11-25 19:56 UTC
```crystal
require "http"

def get(host, &block)
  HTTP::Client.new(host).exec("GET", "/") do
    block.call
  end
end

a = "example.org"
while a
  get(a) do
    a = nil
  end
end
```
```
Invalid memory access (signal 11) at address 0xc
[0x55c0dbf2cf76] print_backtrace at crystal/src/exception/call_stack.cr:121:5
[0x55c0dbf1576c] __crystal_sigfault_handler at crystal/src/signal.cr:347:3
[0x55c0dc043a00] sigfault_handler +40
[0x7facdc9170f0] ???
[0x55c0dbf238a6] [] at crystal/src/pointer.cr:117:6
[0x55c0dbf46a17] calc_excess_left at crystal/src/string.cr:1921:11
[0x55c0dbf469a3] strip at rystal/src/string.cr:1705:5
[0x55c0dc02cce5] initialize at crystal/src/uri/uri_parser.cr:17:16
[0x55c0dc02cc95] new at crystal/src/uri/uri_parser.cr:15:5
[0x55c0dbfd2b61] parse at crystal/src/uri.cr:477:5
[0x55c0dc02b69b] check_host_only at crystal/src/http/client.cr:164:11
[0x55c0dc02b5c8] initialize at crystal/src/http/client.cr:132:5
[0x55c0dc02b580] new at crystal/src/http/client.cr:129:3
[0x55c0dbf18fec] get at /tmp/test.cr:4:3
[0x55c0dbf10f3d] __crystal_main at /tmp/test.cr:11:3
[0x55c0dc0439d6] main_user_code at crystal/src/crystal/main.cr:105:5
[0x55c0dc04386c] main at crystal/src/crystal/main.cr:91:7
[0x55c0dbf120c6] main at crystal/src/crystal/main.cr:114:3
[0x7facdc6de152] __libc_start_main +242
[0x55c0dbf0295e] _start +46
```
This is on master.

Possibly related to #9935

**Comment by asterite** [comment] 2020-11-25 20:00
I have a fix for #9935 but unfortunately it doesn't seem to be related.

**Comment by Blacksmoke16** [comment] 2020-11-25 20:05
Reduced a bit more, removing the `HTTP::Client` stuff:

```cr
require "uri"

def get(uri, &block)
  ->(uri : String) do
    URI.parse(uri)
    block.call
  end.call uri
end

url = "example.org"
while url
  get(url) do
    url = nil
  end
end
```

```
Invalid memory access (signal 11) at address 0xc
[0x563da561cb76] print_backtrace at /home/george/dev/git/crystal/src/exception/call_stack.cr:121:5
[0x563da560ed1c] __crystal_sigfault_handler at /home/george/dev/git/crystal/src/signal.cr:347:3
[0x563da56905c0] sigfault_handler +40
[0x7f978b0a50f0] ???
[0x563da56138e6] [] at /home/george/dev/git/crystal/src/pointer.cr:117:6
[0x563da562e8d7] calc_excess_left at /home/george/dev/git/crystal/src/string.cr:1921:11
[0x563da562e863] strip at /home/george/dev/git/crystal/src/string.cr:1705:5
[0x563da5685b65] initialize at /home/george/dev/git/crystal/src/uri/uri_parser.cr:17:16
[0x563da5685b15] new at /home/george/dev/git/crystal/src/uri/uri_parser.cr:15:5
[0x563da56852a1] parse at /home/george/dev/git/crystal/src/uri.cr:477:5
[0x563da560f391] -> at /home/george/dev/git/athena-framework/athena/test.cr:5:5
[0x563da560f376] get at /home/george/dev/git/crystal/src/primitives.cr:255:3
[0x563da560ad01] __crystal_main at /home/george/dev/git/athena-framework/athena/test.cr:12:3
[0x563da5690596] main_user_code at /home/george/dev/git/crystal/src/crystal/main.cr:105:5
[0x563da569042c] main at /home/george/dev/git/crystal/src/crystal/main.cr:91:7
[0x563da560be86] main at /home/george/dev/git/crystal/src/crystal/main.cr:114:3
[0x7f978ae6a152] __libc_start_main +242
[0x563da560055e] _start +46
[0x0] ???
```

It seems the internal `URI::Parser` is working with a pointer of the input `uri`.  https://github.com/crystal-lang/crystal/blob/master/src/uri/uri_parser.cr#L17

**Comment by oprypin** [comment] 2020-11-25 20:09
Thanks!
That lets me reduce more

```crystal
def get(host, &block)
  p host  # crash
  block.call
end

a = "foo"
while a
  get(a) do
    a = nil
  end
end
```

**Comment by oprypin** [comment] 2020-11-25 20:12
Of course, this is not about nil. `a = <anything non-string>`

If I write `a = 5`, the crash is at address `0x55a800000011` *consistently*

So this is definitely about unions and still likely related to #9935

**Comment by asterite** [comment] 2020-11-25 20:13
Oh... duplicate of #5609

**Closed by asterite** 2020-11-25 20:13 UTC
Labels: kind:bug, topic:compiler, topic:compiler:codegen
