### ISSUE TITLE
crystal playground crashes on this invalid syntax

### ISSUE THREAD

**Issue by dscottboggs** [crystal-lang/crystal#7006] opened 2018-10-29 15:55 UTC
# Bug

You've reached a bug in the playground. Please let us know about it.
# Code
```crystal
r = Random.new

newarr = [] of Int64

p! old = Array(Int64).new 10 { r.rand Int64::MIN..Int64::MAX }

done = Channel(Bool).new
spawn do
  old.each { |i| newarr << i }
  done.send true
end

done.receive

p! newarr
```

# Exception

Error in line 15: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 15: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 17: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 17: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 18: undefined local variable or method 'old'

**Comment by straight-shoota** [comment] 2020-07-11 11:05
Duplicate of #7091

**Closed by straight-shoota** 2020-07-11 11:05 UTC
Labels: kind:bug, topic:tools:playground
