### ISSUE TITLE
Cosmopolitan port

### ISSUE THREAD

**Issue by fithisux** [crystal-lang/crystal#15024] opened 2024-09-23 06:58 UTC
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.
> With cosmopolitan the codebase of Crystal will be more Posix Oriented and possibly less polluted with if/else.
- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem
>
>
>
- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here
>
> Alternate solution can be to accept the status quo
>
- Does it break backward compatibility, if yes then what's the migration path?
>
> It shouldn't
>

**Comment by ysbaddaden** [comment] 2024-09-23 08:10
Duplicate of #12753
See the [relevant discussion](https://forum.crystal-lang.org/t/cosmopolitan-libc/5218/2) in the forum.

**Closed by ysbaddaden** 2024-09-23 08:10 UTC
Labels: kind:feature
