### ISSUE TITLE
Nil Assertion Compiler Bug

### ISSUE THREAD

**Issue by rinkimekari** [crystal-lang/crystal#10679] opened 2021-05-05 21:32 UTC
I came across this issue with the compiler while starting a project that consists of a "shell" made with crystal. It is mostly just an experiment to mess around with crystal, so code optimization was not in mind. I am using Crystal v1.0.0, and am running Garuda Linux (based on Arch). Here is the code (I am sorry for the size, it was necessary because when shrinking it down to something that focused only on the error, I was not able to get the compiler to tell me there was a bug):

```crystal
require "colorize"

Permission = begin
  io = IO::Memory.new
  Process.run("echo $UID", shell: true, output: io)
  if io.to_s.to_i == 0
    "#"
    Root = true # I believe the issue is caused from this
  else
    "$"
    Root = false # and this
  end
end

Root = begin
  if Permission == '#'
    true
  else
    false
  end
end

Err = "[".colorize(:blue).to_s + "!".colorize(:red).to_s + "]".colorize(:blue).to_s

SynErr = Err + " Not recognized as a command, file, or program".colorize(:blue).to_s

Signal::INT.trap do
  puts "\b\b  \n#{Err} Type \"exit\" or \"quit\" to leave"
  prompt
end

def parse(s)
  if s.index(' ')
    parseArgs s.split(' ')
  else
    parseSingle s
  end
end

def parseArgs(args)
  case args[0]
  when "ch"
    begin
      Dir.cd(args[1])
    rescue File::NotFoundError
      puts Err + " No such directory"
    end
  else puts SynErr
  end
end

def parseSingle(arg)
  case arg
  when "exit", "quit" then exit
  when "me", "who", "whoami", "?"
    if Root
      puts "root"
    else
      puts "normal user (this is not fully implemented yet)"
    end
  when "back"  then Dir.cd("..")
  when "clear" then print "\33c\e[3J"
  else
    puts SynErr
  end
end

def prompt
  while 1
    dir = Dir.current.split('/').last.colorize(:magenta).to_s
    dir = "/".colorize(:magenta).to_s if dir == ""
    print "╭─[ ".colorize.magenta.bold.to_s + dir + " ]".colorize.magenta.bold.to_s + "\n╰─#{Permission}> "
    ans = gets
    parse ans.chomp.strip if ans && ans.chomp.strip != ""
  end
end

prompt
```

The issue goes away when I comment out 'Root = something' in the 'Permission' block, however, when I tested it where i only had those two blocks of code, the issue did not appear, hence the reason I did not want to shrink it down any further. Here is the shrunken down code that did not reproduce the issue:

```crystal
Var1 = begin
  if rand(2) == 0
    "0"
    Bool1 = true
  else
    "1"
    Bool1 = false
  end
end

Bool1 = begin
  if rand(2..4) == 2
    true
  else
    false
  end
end
```

And here is the bug report that the compiler gave me:
```
$ crystal build myst.cr
Nil assertion failed (NilAssertionError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

I wish I could give more detail on exactly what is going wrong, but I am still pretty new to the Crystal language.

**Comment by Sija** [comment] 2021-05-05 21:37
Duplicate of #2874

**Comment by rinkimekari** [comment] 2021-05-05 21:39
I did not see that issue when I searched. Sorry about that

**Closed** 2021-05-06 11:12 UTC
Labels: status:duplicate
