### ISSUE TITLE
Returning Proc ending-up as nil

### ISSUE THREAD

**Issue by naqvis** [crystal-lang/crystal#10001] opened 2020-11-30 09:13 UTC
Contrived example to reproduce the behavior

```crystal
class Foo
  def meth1
    pp "meth1"
    Proc(Nil).new { meth2 }
  end

  def meth2
    pp "meth2"
    Proc(Nil).new { meth3 } # this value never get returned
  end

  def meth3
   # this will never get triggered
    pp "meth3"
  end

  def run
    m = ->meth1
    while (m)
      m = m.call
      p! m
    end
  end
end

f = Foo.new
f.run

```

https://carc.in/#/r/a0p6

**Comment by jhass** [comment] 2020-11-30 09:23
IIRC this is not a bug but explicit behavior. A proc typed to return `Nil` always does return `nil`. This allows to cast any other proc with the same arity but a different return value into a `Nil` returning proc implicitly, which is very handy for using the `->` literal which gets its return type likely inferred to be something other than `Nil`.

**Comment by straight-shoota** [comment] 2020-11-30 11:46
+1 @jhass 

This needs to be documented, though.

**Comment by asterite** [comment] 2020-11-30 17:53
Why would `Proc(Nil).new { ... }` return anything other than `nil` when executed?

By the way, this way of creating a proc is undocumented because it's hardcoded in the compiler. Maybe there was no way to implement it in Crystal at the time I introduced it, but now it's very simple:

```crystal
struct Proc(*T, R)
  def self.new(&block : Proc(*T, R)) : Proc(*T, R)
    block
  end
end
```

I will send a PR for that later this week, and then we can document it like everything else.

**Comment by HertzDevil** [comment] 2021-01-15 12:38
It is technically documented in `Proc`'s [summary](https://github.com/crystal-lang/crystal/blob/master/src/proc.cr#L20):

> A special new method is provided too:
>
> ```crystal
> Proc(Int32, String).new { |x| x.to_s } # Proc(Int32, String)
> ```
>
> This form allows you to specify the return type and to check it
> against the proc's body.

**Comment by asterite** [comment] 2021-01-15 12:45
Note that I already tried removing this rule from the language and implementing it as a regular method and it doesn't work nice with `type`defs, or something like that, so I gave up on that idea for now.

Maybe when we remove `type` from the language we'll be able to do it.

**Comment by HertzDevil** [comment] 2021-01-15 12:58
Yeah I tried the same because it seemed to fix #9813 (it actually did), and it broke this one test:

```crystal
it "allows new on proc type that is a typedef" do
  assert_type("
    lib LibC
      type F = Int32 -> Int32
    end

    LibC::F.new { |x| x + 1 }
    ") { proc_of(int32, int32) }
end
```

However this is not any different from the case when `F` isn't a `Proc` instance:

```crystal
lib LibC
  type F = Int32
end

LibC::F.new(0) # error, Int32.new is not available on LibC::F
```

So the solution is to simply use `alias` instead of `type` in these situations. In fact if we follow `type`'s semantics correctly, then the only `LibC::F`s you obtain are the ones returned by C code, and never values created in Crystal. So these specs ought to fail too:

```crystal
it "allows passing proc type if it is typedef'd" do
  assert_type("
    lib LibC
      type Callback = Int32 -> Int32
      fun foo(x : Callback) : Float64
    end

    f = ->(x : Int32) { x + 1 }
    LibC.foo f
    ") { float64 }
end

it "allows passing nil as proc callback" do
  assert_type("
    lib LibC
      type Cb = Int32 ->
      fun bla(Cb) : Int32
    end

    LibC.bla(nil)
    ") { int32 }
end
```

The only other use of a `type` `Proc` in the entire repository is `LibGC::Finalizer`. This too can be replaced by an `alias`.

**Comment by asterite** [comment] 2021-01-15 13:02
Good point. In fact, `type` with an underlying `Proc` has a special rule right now to treat that as an `alias`... I think because in the beginning we (I) got `type` wrong and treated it sometimes as an alias.

So I think it's fine to go with that change and change `type` to `alias` for `Proc` types. It's a small breaking change but I think we should do it.

**Comment by HertzDevil** [comment] 2021-01-15 15:30
Actually, one more spec is failing:

```crystal
it "says can't send closure to C with new notation" do
  assert_error %(
    lib LibC
      fun foo(x : ->)
    end

    a = 1
    LibC.foo(Proc(Void).new do
      a
    end)
    ),
    "can't send closure to C function (closured vars: a)"
end
```

Because the compiler performs closure analysis on `ProcLiteral`s, including ones currently emitted by `Proc.new(&)`, but not block literals. I don't have an idea on how to implement this yet, but it has a low priority because the runtime exception should still exist. Contrast the spec with the following:

```crystal
lib LibC
  fun foo(x : ->)
end

a = 1
fn = Proc(Void).new do
  a
end
LibC.foo(fn) # Unhandled exception: passing a closure to C is not allowed
```

**Comment by asterite** [comment] 2021-01-15 15:37
Oh, I see...

Maybe letting the rule in the compiler is slightly better then, I don't know.

**Comment by HertzDevil** [comment] 2021-01-16 16:49
I was dumb, the block's equivalent `ProcLiteral` is also accessible through `Crystal::Block#fun_literal`. Let's see how this goes...

**Comment by HertzDevil** [comment] 2021-01-17 21:58
Is anything from the original issue here actionable, anyway?

**Comment by asterite** [comment] 2021-01-17 22:18
Not an issue, so closing.

**Closed by asterite** 2021-01-17 22:18 UTC
