### ISSUE TITLE
Crystal's REPL

### ISSUE THREAD

**Issue by ArthurZ** [crystal-lang/crystal#4363] opened 2017-05-01 03:09 UTC
Hi,
Are we going to get REPL in Crystal?

**Comment by bew** [comment] 2017-05-01 04:19
There is [crystal-icr](https://github.com/greyblake/crystal-icr), which is more a hack that works than a fully supported crystal REPL.
Quoting @asterite from https://github.com/crystal-lang/crystal/issues/681#issuecomment-106538018 "I think it's possible, just hard."

More informations https://github.com/crystal-lang/crystal/issues/681

**Comment by drosehn** [comment] 2017-05-01 13:46
See also:  `crystal play`.  Not quite a REPL, but pretty useful.

**Comment by ysbaddaden** [comment] 2017-05-01 15:46
Closing as duplicate of #681

Refactoring icr to use the instrumentation created for crystal play would be interesting.

**Closed by ysbaddaden** 2017-05-01 15:46 UTC
