### ISSUE TITLE
When I run crystal play I get an error

### ISSUE THREAD

**Issue by jaysg** [crystal-lang/crystal#4100] opened 2017-03-02 23:01 UTC
I just installed crystal through brew and tried to use `crystal play` 
and got this error....

**Crystal version**
Crystal 0.21.0 (2017-02-21)

## **CODE**
```
def find_string(text, word)
  (0..text.size-word.size).each do |i|
    { i, text[i..i+word.size-1] }
    if text[i..i+word.size-1] == word
      return i
    end
  end

  nil
end

find_string "Crystal is awesome!", "awesome"
find_string "Crystal is awesome!", "not sure"
```

##**Exception**
```
Error in line 5: instantiating 'Crystal::Playground::Agent:Class#new(String, Int32)'

in /usr/local/Cellar/crystal-lang/0.21.0/src/compiler/crystal/tools/playground/agent.cr:8: instantiating 'HTTP::WebSocket:Class#new(URI)'

    @ws = HTTP::WebSocket.new(URI.parse(url))
                          ^~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/web_socket.cr:28: instantiating 'HTTP::WebSocket::Protocol:Class#new(URI)'

    new(Protocol.new(uri))
                 ^~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/web_socket/protocol.cr:285: instantiating 'new(String, String, (Int32 | Nil), Bool)'

      return new(host, path, uri.port, tls)
             ^~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/web_socket/protocol.cr:251: expanding macro

    {% if !flag?(:without_openssl) %}
    ^

in macro 'macro_4686407424' /usr/local/Cellar/crystal-lang/0.21.0/src/http/web_socket/protocol.cr:251, line 8:

   1. 
   2.       if tls
   3.         if tls.is_a?(Bool) # true, but we want to get rid of the union
   4.           context = OpenSSL::SSL::Context::Client.new
   5.         else
   6.           context = tls
   7.         end
>  8.         socket = OpenSSL::SSL::Socket::Client.new(socket, context: context, sync_close: true)
   9.       end
  10.     

instantiating 'OpenSSL::SSL::Socket::Client:Class#new(TCPSocket)'
in /usr/local/Cellar/crystal-lang/0.21.0/src/openssl/ssl/socket.cr:4: instantiating 'super(TCPSocket, OpenSSL::SSL::Context::Client, Bool)'

      super(io, context, sync_close)
      ^~~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/openssl/ssl/socket.cr:86: instantiating 'OpenSSL::BIO:Class#new(TCPSocket)'

    @bio = BIO.new(io)
               ^~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/openssl/bio.cr:18: instantiating 'IO#read(Slice(UInt8))'

      io.read(Slice.new(buffer, len)).to_i
         ^~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/flate/reader.cr:68: instantiating 'IO#peek()'

        @peek = @io.peek
                    ^~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/content.cr:107: instantiating 'read_chunk_start()'

          read_chunk_start
          ^~~~~~~~~~~~~~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/content.cr:138: instantiating 'read_chunk_end()'

      read_chunk_end
      ^~~~~~~~~~~~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/http/content.cr:146: instantiating 'IO#skip(Int32)'

      @io.skip(2)
          ^~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/io.cr:893: instantiating 'read(Slice(UInt8))'

      read_count = read(buffer.to_slice[0, Math.min(bytes_count, 4096)])
                   ^~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/gzip/reader.cr:107: instance variable '@extra' of Gzip::Header must be Slice(UInt8), not Nil

          Header.new(first_byte, @io)
                 ^~~
```

**Comment by matiasgarciaisaia** [comment] 2017-03-02 23:04
@jaysg this is an exact duplicate of #4084 - please come by and add any relevant info you have in there 👍

**Closed by matiasgarciaisaia** 2017-03-02 23:04 UTC
