### ISSUE TITLE
Digest::SHA1.digest returns inconsistent data in --release build 

### ISSUE THREAD

**Issue by jasonl99** [crystal-lang/crystal#4057] opened 2017-02-21 19:07 UTC
I've finally tracked down some compiler wierdness that happens when doing `--release`.  It's easy to duplicate, and it was happening in 0.20.5 and now 0.21.0

First the code.  Run a SHA1.digest on the same string numerous times.  

```crystal
require "digest/sha1"

puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
puts Digest::SHA1.digest("This is a test")
```

When building without `--release` you get what you'd probably expect:
```crystal
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
```

But watch what happens when `--release` is added to the build
```crystal
StaticArray[165, 77, 188, 224, 102, 18, 0, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 144, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 32, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 176, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 64, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 208, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 96, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 240, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
StaticArray[165, 77, 188, 224, 102, 18, 128, 32, 188, 59, 40, 40, 119, 199, 86, 37, 123, 86, 112, 25]
```
Trying it with different strings seems to always cause the 7th element to change, and no matter what the string, it seems to cycle between 0, 144, 32, 176, 64, 208, 96, 240, 128, 16, 160, 48, 192, 80, 224, 112.   It seems very fibonacci-sequencey to me.  Maybe that's a hint what's going on?  Since this is only happening in --release, I assume this is an LLVM issue?

Incidentally, calling `hexdigest` always returns the correct result.

**Comment by matiasgarciaisaia** [comment] 2017-02-21 19:26
Which OS is this happening on?

I couldn't repro this on macOS 10.12.3 with Crystal 0.21.0 from Homebrew.

**Comment by need47** [comment] 2017-02-21 19:34
I could reproduce it. My OS is:

Linux structuredev21 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I'm using pre-built linux binary 0.21.0

**Comment by matiasgarciaisaia** [comment] 2017-02-21 19:42
Could repro on Ubuntu 64-bits 16.04.01 with Crystal 0.21.0 from dist.crystal-lang.org/apt

**Comment by jasonl99** [comment] 2017-02-21 19:53
My OS is  Linux 4.8.0-37-generic #39-Ubuntu SMP Thu Jan 26 02:27:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.

**Comment by asterite** [comment] 2017-02-21 21:12
I'm almost sure this is a duplicate of #3695, as I'm almost sure it's a bug in llvm 3.5 (we are still using it in the linux distributions)

**Comment by RX14** [comment] 2017-02-21 21:28
I'm pretty sure i've reproduced [this bug](https://crystal-ci.rx14.co.uk/job/crystal/job/feature%252Fjenkinsfile/17/console) on crystal on latter LLVM versions.

I'll go and make sure by reproducing using this exact code.

**Comment by RX14** [comment] 2017-02-21 21:42
Failed to reproduce on LLVM 3.9.1: https://gist.github.com/RX14/ae9549afb540a03f7730c061b74e1e3f

Seems like i've always accidentally been using llvm 3.5 when i've reproduced this bug, interesting.

**Comment by luislavena** [comment] 2017-02-22 13:28
I've failed to reproduce this on local builds with LLVM 3.8.0

```
$ llvm-config --version
3.8.0

$ bin/crystal build --release issue-4057.cr

$ ./issue-4057
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
StaticArray[165, 77, 136, 224, 102, 18, 216, 32, 188, 59, 231, 40, 119, 199, 79, 37, 123, 86, 27, 25]
```

**Comment by oprypin** [comment] 2017-02-24 20:45
#3013

**Comment by asterite** [comment] 2017-03-03 19:10
Closing as duplicate of #3695

**Comment by asterite** [comment] 2017-03-03 19:11
Closing as duplicate of #4014

**Closed by asterite** 2017-03-03 19:10 UTC
Labels: kind:bug, status:accepted
