### ISSUE TITLE
Compiler can't infer seemingly obvious type

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2757] opened 2016-06-05 16:41 UTC
I have this:

```ruby
module Sidekiq
  module WebHelpers
    @@strings = Hash(String, Hash(String, String)).new
```

I mix it in:

```ruby
class HTTP::Server::Context
  include Sidekiq::WebHelpers
end
```

I use it here:

```ruby
    # Given a browser request Accept-Language header like
    # "fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4,ru;q=0.2", this function
    # will return "fr" since that"s the first code with a matching
    # locale in web/locales
    def locale
      locale = "en"
      languages = request.headers["HTTP_ACCEPT_LANGUAGE"] || "en"
      languages.downcase.split(",").each do |lang|
        next if lang == "*"
        lang = lang.split(";")[0]
        break locale = lang if @@strings[lang]? # <==========
      end
      locale
    end
```

and get this:

```
in ./src/sidekiq/web_helpers.cr:37: Can't infer the type of class variable '@@strings' of HTTP::Server::Context

The type of a class variable, if not declared explicitly with
`@@strings : Type`, is inferred from assignments to it across
the whole program.
```

Why doesn't the initial assignment up top lock in the type?  I never reassign the @@strings variable anywhere so I'd think its type of `Hash(String, Hash(String, String))` would be obvious.

**Comment by rmosolgo** [comment] 2016-06-05 20:09
Here's a really minimal reproduction: https://carc.in/#/r/10ts

Is this a result of Crystal's divergence from Ruby when it comes to class variables? 

> Class variables are always associated to a single type and are not inherited... Class variables can also be associated to modules and structs. Like above, they are not inherited by including types.

(from [class variables](http://crystal-lang.org/docs/syntax_and_semantics/class_variables.html))

**Comment by asterite** [comment] 2016-06-05 20:22
Yes, duplicate of #2458

I'll try to enhance this soon as this is probably the tenth time someone reports this :-)

**Closed by asterite** 2016-06-05 20:22 UTC

**Comment by rmosolgo** [comment] 2016-06-05 20:55
> Their value won't be shared.

😌
