### ISSUE TITLE
OpenBSD ports Crystal not building

### ISSUE THREAD

**Issue by TheWanderer1983** [crystal-lang/crystal#14026] opened 2023-11-29 06:05 UTC
Hello all,

Not really specific to the package but I thought I would reach out given https://crystal-lang.org/install/on_openbsd/ page.

Currently the ports version is broken and needs repair. I've seen not initiative via the ports mailing list  to fix it. Is there any kind soul who would like to fix this? 

Regards
Dylan

**Comment by GeopJr** [comment] 2023-11-29 09:51
I'll take a look

**Comment by GeopJr** [comment] 2023-11-29 10:53
Duplicate of https://github.com/crystal-lang/crystal/issues/13665

**Comment by straight-shoota** [comment] 2024-10-31 11:56
This should be resolved with #15122

**Closed by straight-shoota** 2024-10-31 11:56 UTC
Labels: kind:bug, platform:bsd

**Comment by TheMBL09898** [comment] 2024-12-22 13:16
Compiling in OpenBSD 7.6 still fails, `gmake` returns:
```
Using /usr/local/bin/llvm-config-17 [version=17.0.6]
c++ -c  -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc -I/usr/local/llvm17/include -std=c++17   -fno-exceptions -funwind-tables -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
CRYSTAL_CONFIG_BUILD_COMMIT="c5455ce" CRYSTAL_CONFIG_PATH='$ORIGIN/../share/crystal/src' SOURCE_DATE_EPOCH="1734780009"  CRYSTAL_CONFIG_LIBRARY_PATH='$ORIGIN/../lib/crystal' ./bin/crystal build -D strict_multi_assign -D preview_overload_order -Dwithout_interpreter  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib -D use_pcre2
Showing last frame. Use --error-trace for full trace.

In /usr/local/lib/crystal/compiler/crystal/syntax/ast.cr:125:5

 125 | enum Keyword
       ^
Error: can't reopen enum and add more constants to it
gmake: *** [Makefile:246: .build/crystal] Error 1
```

**Comment by GeopJr** [comment] 2024-12-22 20:01
Probably open a new issue, this was specifically about indirect branch tracking

**Comment by ysbaddaden** [comment] 2024-12-22 22:59
Yeah, that's a crystal path issue.

**Comment by TheMBL09898** [comment] 2024-12-23 00:31
Could you guys hint me on how to fix that or the build commands you used to compile successfully on OpenBSD?... I know it's not the appropriate place, but I can't find any information anywhere else. Sorry

**Comment by straight-shoota** [comment] 2024-12-23 11:32
@TheMBL09898 It's probably best to ask in the support section on the Crystal forum: https://forum.crystal-lang.org/c/help-support/11 (or in a [community chat channel](https://crystal-lang.org/community/#chat)). Please include repeatable steps (the exact commands you ran that ended up with that error message).

**Comment by ysbaddaden** [comment] 2024-12-23 21:03
The crystal binary is probably a shell script that sets some environment vars then calls the actual crystal binary. Those env vars likely conflict with the ones declared by the Makefile and the compiler ends up loading the stdlib twice (from install then got clone) which conflicts.

You may copy the actual binary as `.build/crystal` then force a rebuild with `gmake -B` or adapt the shell script to only set the env vars when unset.

For further help please reach to the forum, thanks :)
