### ISSUE TITLE
Support of HTTP/2 in standard library

### ISSUE THREAD

**Issue by deepj** [crystal-lang/crystal#2863] opened 2016-06-17 00:13 UTC
I'd appreciate to see the support in near future 😃 Some inspiration can be gotten from pure Ruby HTTP/2 library https://github.com/igrigorik/http-2

**Comment by asterite** [comment] 2016-06-17 00:15
Definitely! :-)

Duplicate of #2125

**Closed by asterite** 2016-06-17 00:15 UTC

**Comment by deepj** [comment] 2016-06-17 00:16
@asterite Ah, thanks. I haven't noticed it. Sorry :)
