### ISSUE TITLE
Additive JSON mapping?

### ISSUE THREAD

**Issue by mperham** [crystal-lang/crystal#2987] opened 2016-07-12 17:52 UTC
Right now a class can define its properties:

``` ruby
class Sidekiq::Job
  JSON.mapping({
    jid: String,
    queue: String,
  })
end
```

I would like 3rd party software/plugins to be able to add properties to the Job that they can use:

``` ruby
# reopen the class and add a new property that users can customize
# and middleware can access when processing jobs
class Sidekiq::Job
  JSON.mapping({
    unique_for: Time::Span?,
  })
end
```

Obviously they can reopen the class and add a `property` but that doesn't help when I want to serialize the whole thing to JSON and push it to Redis.  Ideas?

**Comment by asterite** [comment] 2016-07-12 19:56
I thought of one way to do it. It uses the fact that constants can be modified with macro code. But to make it work you'll have to organize your code, and plugins will have to make only some `require`s so that the mapping is the last thing that happens (so order matters a lot here). Here's an example:

```cr
require "json"

# Base definition of your model
class Point
  MAPPING = {
    x: Int32,
  }
end

# Here plugins can modify the mapping via macro code
{{ Point::MAPPING[:y] = Int32 }}

# With a little macro it's easier for the user
class Point
  # This is to allow named arguments
  macro extra_mapping(**properties)
    ::Point.extra_mapping({{properties}})
  end

  # This is to receive a named tuple or hash literal
  macro extra_mapping(properties)
    {% for key, value in properties %}
      {{ ::Point::MAPPING[key] = value }}
    {% end %}
  end
end

# Now let's use the helper
Point.extra_mapping z: Int32, w: Int32

# Finall you apply the mapping
class Point
  JSON.mapping {{MAPPING}}
end

# And then you use it
point = Point.from_json %({"x": 1, "y": 2, "z": 3, "w": 4})
p point # => #<Point:0x106f55ea0 @x=1, @y=2, @z=3, @w=4>
```

[In play](https://play.crystal-lang.org/#/r/13p4)

So you'll want the base definition to be in `sidekiq/base` or something like that, and plugins will need to require that. They don't need to require the code that invokes `JSON.mapping`, that code is probably needed to be required by the "main" app that loads all plugins.

There are probably other ways to do this, though...

**Comment by kostya** [comment] 2016-07-13 15:44
what if unparsed keys from initialize saved to special hash @extra, and then just add method to class

```crystal
class Bla
  JSON.mapping({
    a: Int
  })
end

class Bla
  JSON.extra_mapping({
    bla: String?
  })
end
```

extra_mapping would convert to something like this:
```crystal
@bla : String?
def bla
   @bla ||= (String?).from_json(@extra["bla"])
end
```

**Comment by asterite** [comment] 2016-07-13 16:03
@kostya Yes, that's basically https://github.com/crystal-lang/crystal/pull/2834 so this issue is almost a duplicate of that.

**Comment by mperham** [comment] 2016-07-13 16:09
@asterite To me they are different requirements.  This issue covers the need for 3rd party plugins to extend the JSON mapping at compile time, the elements aren't "extra" at all.  That issue covers the need to expose unmapped JSON elements at runtime.

**Comment by asterite** [comment] 2016-07-13 16:19
But maybe there's no need to extend the mapping at compile time, if at runtime you can still get and set elements that need to be serialized in the JSON? I'm thinking about how you would model this in other compiled languages and without being able to "setup" things at compile-time that's the only way, and it works well.

**Comment by mperham** [comment] 2016-07-13 16:24
In a perfect world I'd want JSON mapping extension too.  It keeps type safety and a cleaner API to the user.  No need to inspect the hash contents or do type conversions in user-code.

**Comment by asterite** [comment] 2016-07-13 17:28
Yes, type safety for the win :-)

Does the first approach I mentioned work for you?

**Comment by mperham** [comment] 2016-07-13 18:06
Well, I'm sure your approach works but it's a bit of a hack and deeply invasive to my library's implementation.  I have to restructure how people require and use my APIs for it.

**Comment by asterite** [comment] 2016-07-13 18:26
I don't think there's another way to setup the code at compile-time without preparing it, at compile time, before invoking `JSON.mapping`. All other solutions will happen at runtime, and then we can use what @kostya said, or #2834, or callbacks invoked on unknown keys.

**Comment by kostya** [comment] 2016-07-13 18:37
if you can invoke callback when all definitions of class done: `class_finalized`, then in it you can define initialize of full mapping

**Comment by asterite** [comment] 2016-07-13 18:50
Yes, something like a `macro at_exit` could be useful for this, I guess, that would be executed as being considered the last thing in the whole code. I think this idea was mentioned in the past for other use cases.

I still don't know if modifying constants at compile-time is hacky enough to remove that "feature" from the language.

**Closed** 2016-12-01 16:53 UTC
Labels: question
