### ISSUE TITLE
Macro infinite recursion throw a invalide memory access error

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10409] opened 2021-02-17 09:27 UTC
Hi,

Take this (dumb) code:

```
macro one(name)
  {% puts name %}
  one({{name}})
end

one(Test)
```

When compiling it, after a lot of `puts` (8567) it fails with:
```
Invalid memory access (signal 11) at address 0x7ffca5ffaf18
[0x7f80c148b366] ???
[0x7f80c13d607d] ???
[0x7f80c2422326] ???
```

I know the compiler cannot know if the code will ever stop (halting problem), but maybe it should stop after an arbitrary level of macro recursion. 8k seems to be too much, somethink like a few tens or a couple of hundreds should be enough.

**Comment by HertzDevil** [comment] 2021-07-14 01:38
Duplicate of #9413.

**Closed** 2021-07-14 09:11 UTC
Labels: status:duplicate
