### ISSUE TITLE
Add coprime? method

### ISSUE THREAD

**Issue by jzakiya** [crystal-lang/crystal#13984] opened 2023-11-14 21:12 UTC
Following in the footsteps, and in the spirit of the forum discussion on the use of
`divisible_by?` here https://forum.crystal-lang.org/t/should-divisible-by-be-preferd-over-x-y-0/6161
I propose adding `coprime?(m, n)`, or better `m.coprime?(n)`
which returns `true` if the integers are **coprime** (have no common factors) or `false` otherwise.

One way to determine if 2 integers are coprime is to perform the test: `m.gcd(n) == 1`
However, I found this to be significantly slower when the values are > `UInt64`, i.e,
outside of 64-bits (for native 64-bit systems).

Below is a customized truncated implementation of the Euclid gcd algorithm that returns
`1` if coprime and `0` otherwise, which is tested for to create a boolean output.

```
def coprime?(m, n)
  until m|1 == 1; t = m; m = n % m; n = t end
  m > 0     # coprime if 1; 0 otherwise
end
```
Here is real code where using the `coprime?` method doubled the speed on average
from using `gcd`, because it was within a hot loop.  In this case all the inputs were `UInt64`.

```
def gapcounts(first, last, modpn)       # count residue gaps within a range segment
  gaps = Array(UInt64).new(55, 0)       # store|return array of residue range gap values
  rc = prev_res = first                 # init residue candidate (rc), et al, values
  inc = rc % 6 == 5 ? 2 : 4             # set P3 PGS start increment for first range rc
  while rc <= last                      # while current rc still in segment

    #if rc.gcd(modpn) == 1              # if it's a residue, i.e. the numbers are coprime
    if coprime?(rc, modpn)              # if it's a residue

      gap = (rc - prev_res).to_i32      # compute its gap with previous residue
      gaps[gap // 2] += 2               # incr count by 2 for mirror image gap also
      prev_res = rc                     # set its value to current residue
    end
    rc += inc; inc ^= 0b0110            # get next P3 sequence rc val: 5 7 11 13 17 19...
  end
  gaps[0] = 0                           # pn gaps start at index [1]
  gaps                                  # gaps[i] from i=1 have cnts for gap sizes 2*i
end
```

Here is benchmark output on my rudimentary implementation.
For all around best performance maybe a hybrid implementation should be done to get
the best performance when inputs fit within 64-bits, and another using `gcd` when not.
These are implementation details.

However, as with `divisible_by?`, `zero?`, `array.empty?`, et al, the main benefit is making code more clear and 
maintainable for users, as it directly expresses what the code is doing, and not how.

```
require "big"
require "benchmark"

x, y = 44328732141, 59357243

Benchmark.ips do |b|
  b.report("coprime?") { coprime?(x, y) }
  b.report("gcd test") { x.gcd(y) == 1 }
end

puts
x1, y1 =  44328732141_u64, 59357243_u64

Benchmark.ips do |b|
  b.report("coprime?") { coprime?(x1, y1) }
  b.report("gcd test") { x1.gcd(y1) == 1 }
end

puts
x2, y2 = 44328732141_u128, 59357243_u128

Benchmark.ips do |b|
  b.report("coprime?") { coprime?(x2, y2) }
  b.report("gcd test") { x2.gcd(y2) == 1 }
end

puts
x3, y3 = 44328732141.to_big_i, 59357243.to_big_i

Benchmark.ips do |b|
  b.report("coprime?") { coprime?(x3, y3) }
  b.report("gcd test") { x3.gcd(y3) == 1 }
end
```
Here are results on my Linux based, AMD Ryzen 9 5900HZ system, using Crystal 1.10.1.

```
coprime?  38.78M ( 25.78ns) (± 0.66%)  0.0B/op        fastest
gcd test  37.27M ( 26.83ns) (± 0.48%)  0.0B/op   1.04× slower

coprime?  46.75M ( 21.39ns) (± 0.35%)  0.0B/op        fastest
gcd test  37.68M ( 26.54ns) (± 0.92%)  0.0B/op   1.24× slower

coprime?  11.14M ( 89.76ns) (± 0.28%)  0.0B/op   1.17× slower
gcd test  13.02M ( 76.82ns) (± 0.27%)  0.0B/op        fastest

coprime?   1.23M (815.40ns) (± 0.29%)   706B/op  15.81× slower
gcd test  19.39M ( 51.56ns) (± 0.48%)  16.0B/op        fastest

coprime?  10.72M ( 93.30ns) (± 0.29%)  0.0B/op   1.22× slower
gcd test  13.10M ( 76.31ns) (± 0.41%)  0.0B/op        fastest
```

**Comment by oprypin** [comment] 2023-11-15 00:07
This should be part of a dedicated math library. Only hardcore math-focused programming languages would have this in the standard library.

**Comment by straight-shoota** [comment] 2023-11-15 14:04
I believe we already have quite some features in stdlib that I would expect either in a dedicated math library, or the standard library of a hardcore math-focused programming language. 😆 Say `Complex`, for example.

This is just an observation. It may count as a minor argument that there are already precedents for this. But of course we don't need to pile up on that.

**Comment by HertzDevil** [comment] 2023-11-28 16:06
Duplicate of #13380.

**Closed by HertzDevil** 2023-11-28 16:06 UTC
Labels: kind:feature, topic:stdlib:numeric
