### ISSUE TITLE
Nested block arguments can't be unpacked

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#8237] opened 2019-09-26 00:37 UTC
Currently, it seems that unpacking tuples nested more than one level deep does not work:

```crystal
boxes = [
  { { 0,  0}, {15, 10} },
  { {30, 10}, {40, 20} },
  { { 9, 14}, {99, 58} }
]
boxes.each_with_index do |((x1, x2), (y1, y2)), i|
  puts "#{i}: (#{x1}, #{x2}), (#{y1}, #{y2})"
end
```
```
Error: expecting block argument name, not (
```

This isn't necessarily the biggest problem on its own (although it's certainly cumbersome), since it at least allows for a single level of nesting, but compared with #7706 it turns ugly:

```crystal
positions = [
  { 0,  0},
  {30, 10},
  { 9, 14}
]
positions.each_with_index.reject{ |((x, y), i)| x < 5 || y < 5 }.each do |(x, y), i|
  puts "#{i}: (#{x}, #{y})"
end
```
```
Error: expecting block argument name, not (
```

The `|(x, y), i|` for `each` works fine, but due to #7706, the outer level has to be manually unpacked for `reject` as `|((x, y), i)|`, which doesn't work since that leads to nesting. Normally you get one level of nesting, as the outer level is implicit, but for methods like `select`, `reject`, and `map`, you don't get any nesting at all.

If tuple unpacking recursed arbitrarily, this would be no problem!

This was tested on Crystal 0.31.0, on Ubuntu running via WSL! ⭐️

**Comment by jhass** [comment] 2019-09-26 08:07
Do you agree this is more or less a duplicate of #132?

**Comment by obskyr** [comment] 2019-09-26 08:25
Hmm. That would be adding a new feature, whereas this is just extending the block argument unpacking that's already there – but I suppose implementing nested block argument unpacking would solve tuple decomposition in other contexts too. If #132 is slated to be implemented, and not just in tentative discussion, feel free to close this and make a note there! Otherwise, though, I think nested block arguments are separate and expected enough that they should be implemented regardless of where the rest of #132 goes.

**Comment by will** [comment] 2021-12-14 23:22
For what it's worth, I recently ran into a situation where I tried to do do something like `|((x, y), i)|` and was surprised it didn't work.

**Closed** 2023-07-25 09:03 UTC
Labels: kind:feature, topic:compiler:semantic
