### ISSUE TITLE
only wrap `->foo` pointers where scope capture might be required

### ISSUE THREAD

**Issue by stakach** [crystal-lang/crystal#11711] opened 2022-01-06 13:36 UTC
## Feature Request

- Is your feature request related to a problem? Please describe clearly and concisely what is it.
when #9972 was merged it added a wrapper to `->foo` function pointers to capture scoped variables
however this wrapper isn't required for functions without arguments as there is nothing to scope

discussion here https://forum.crystal-lang.org/t/obtain-the-address-of-a-function/4237/2

- Describe the feature you would like, optionally illustrated by examples, and how it will solve the above problem.
removing the wrapper for functions with no arguments would improve performance and allow one to obtain a direct memory address of the function

- Describe considered alternative solutions, and the reasons why you have not proposed them as a solution here.
none currently

- Does it break backward compatibility, if yes then what's the migration path?
no

**Comment by asterite** [comment] 2022-01-06 14:29
A diff to implement this is:

```diff
diff --git a/src/compiler/crystal/semantic/main_visitor.cr b/src/compiler/crystal/semantic/main_visitor.cr
index fa2e80870..1f6354367 100644
--- a/src/compiler/crystal/semantic/main_visitor.cr
+++ b/src/compiler/crystal/semantic/main_visitor.cr
@@ -1219,11 +1219,19 @@ module Crystal
         end)
       end
 
+      args = node.args
+
+      # If it's something like `->foo(...)` then we also turn it into a closure
+      # because it could be doing a mutlidispatch and that's not supported in ProcPointer.
+      # However, if it's `->foo` (no args) then it can never be a multidispatch.
+      if !obj && !args.empty?
+        expand(node)
+        return false
+      end
+
       # If it's something like `->foo.bar` we turn it into a closure
       # where `foo` is assigned to a temporary variable.
-      # If it's something like `->foo` then we also turn it into a closure
-      # because it could be doing a mutlidispatch and that's not supported in ProcPointer.
-      if !obj || obj.is_a?(Var) || obj.is_a?(InstanceVar) || obj.is_a?(ClassVar)
+      if obj.is_a?(Var) || obj.is_a?(InstanceVar) || obj.is_a?(ClassVar)
         expand(node)
         return false
       end
```

No idea how to test it. Well, at runtime if you do:

```crystal
def foo
  1
end

puts (->foo).pointer.address
puts (->foo).pointer.address
```

you should always get the same value.

**Comment by HertzDevil** [comment] 2022-01-06 14:35
Would `self` not cause a multidispatch here?

**Comment by asterite** [comment] 2022-01-06 14:42
I don't think so, because `self` is always a single type (never a union)... but maybe you are right. What would be that case?

**Comment by straight-shoota** [comment] 2022-01-21 23:15
As I understand the description of #9972 and the examples in the issues, it seems to be *explicitly* about resolving multi-dispatch on `self`.
Method arguments are irrelevant to that. I don't see how #11743  would improve anything.

In fact, it brings back the "2 target defs for ..." compiler error back (the one that was fixed in #9972) for methods that have no arguments.
So this approach seems to be completely misleading.

I'm not sure what could be effective to improve this situation. I presume it depends on pulling up information about whether multi-dispatch actually happens or if it's just a possibility. If the compiler knew at this point that a method won't need multi-dispatch, there would be no need for a wrapper.

**Comment by asterite** [comment] 2022-01-21 23:23
@straight-shoota can you show code that reproduces that "2 target defs" with this PR?

**Comment by straight-shoota** [comment] 2022-01-21 23:29
This is the example from #9823 with method parameters removed:

```cr
abstract struct Parent
  abstract def work
  def get
    ->work
  end
end

struct Child1 < Parent
  def work
    1
  end
end

struct Child2 < Parent
  def work
    2
  end
end

pp [Child1.new,Child2.new].map(&.get)
```

**Comment by asterite** [comment] 2022-01-21 23:53
Oooh... Self can be a virtual type.

Thabk you for the patience!

**Closed by asterite** 2022-01-21 23:53 UTC
Labels: kind:feature

**Comment by HertzDevil** [comment] 2022-01-23 15:15
The original forum thread is really about top-level fun defs, which cannot cause multidispatch because there is no `self`, so there should be a new issue for that.
