### ISSUE TITLE
cast from Nil to Crystal::GenericInstanceType+ failed

### ISSUE THREAD

**Issue by watzon** [crystal-lang/crystal#4859] opened 2017-08-19 23:37 UTC
While trying to convert a Ruby code sample into a Crystal sample I came across what could be a bug (because the compiler told me it was a bug).

The following code sample is the problem causer, and the issue is the lack of a type declaration in the Array's in the `validate_pixel` method. When type declarations are included it compiles.

```crystal
class RGBColor
  getter :red, :green, :blue

  def initialize(@red : Int32, @green : Int32, @blue : Int32)
    unless (0 <= @red <= 255) && (0 <= @green <= 255) && (0 <= @blue <= 255)
      raise ArgumentError.new("invalid RGB parameters: #{[@red, @green, @blue].inspect}")
    end
  end
 
  RED   = RGBColor.new(255,0,0)
  GREEN = RGBColor.new(0,255,0)
  BLUE  = RGBColor.new(0,0,255)
  BLACK = RGBColor.new(0,0,0)
  WHITE = RGBColor.new(255,255,255)
end
 
class Pixmap
  getter :width, :height  

  def initialize(@width : Int32, @height : Int32)
    @data = fill(RGBColor::WHITE)
  end
 
  def fill(color : RGBColor)
    @data = Array.new(@width) {Array.new(@height, color)}
  end
 
  def validate_pixel(x, y)
    unless (0 <= x <= @width-1) && (0 <= y <= @height-1)
      raise ArgumentError.new("requested pixel (#{x}, #{y}) is outside dimensions of this bitmap")
    end
  end
 
  def [](x, y)
    validate_pixel(x,y)
    @data[x][y]
  end
 
  def []=(x, y, color)
    validate_pixel(x, y)
    @data[x][y] = color
  end
end
```

Here is a running (well not really running) example https://carc.in/#/r/2kfz

**Comment by asterite** [comment] 2017-08-19 23:46
Reduced:

```crystal
class Gen(T)
  def self.new(&block)
    Gen(T).new
  end
end

class Foo
  def foo
    @x = Gen.new { }
  end
end
```

Workaround:

```crystal
class Pixmap
  @data : Array(Array(RGBColor))
end
```

**Comment by Fryguy** [comment] 2017-09-09 16:25
I just hit this same compiler error and narrowed it down to the following:

```crystal
class Foo
  property bar = Array.new(2) { Array(DoesntMatter).new(2) }
end
```

which gives 

```text
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-lang-20170713-99958-vd502v/crystal-0.23.1/src/compiler/crystal/types.cr:1420:20:1420
0x1017517e8: *raise<TypeCastError>:NoReturn at ??
0x101e14864: *Crystal::TypeParameter#solve<Crystal::NonGenericClassType>:Crystal::ASTNode+ at ??
0x101e15520: *Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::NonGenericClassType>:Crystal::Type+ at ??
0x101e1259a: *Crystal::TypeDeclarationProcessor#process_owner_guessed_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::InstanceVarTypeInfo>:(Crystal::MetaTypeVar | Crystal::TypeDeclarationProcessor::Error | Nil) at ??
0x101e0c233: *Crystal::TypeDeclarationProcessor#process_instance_vars_declarations:Nil at ??
0x101d5e97b: *Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor) at ??
0x101d58999: *Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+ at ??
0x1021d7145: *Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result at ??
0x1022468ce: *Crystal::Command#run_command<Bool>:Nil at ??
0x10179608c: *Crystal::Command#run:(Bool | Crystal::Compiler::Result | IO::FileDescriptor | Nil) at ??
0x101766b86: main at ??

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Searching led me to this issue, but I'm not sure if it's actually the same as any of the 3 open issues with the same error.

**Comment by mverzilli** [comment] 2017-09-09 21:30
So `@data` is an ivar whose type is not explicitly annotated neither can be inferred from constructors bodies, right? The fix for this should be for the compiler to report that instead gracefully instead of blowing up then.

**Comment by asterite** [comment] 2017-09-09 22:36
Duplicate of #4460

@mverzilli Yes, it's a problem with the type guesser and generic types. I think it deduces that the type is `Array(T)` but `T` is not bound. I tried to fix it once but it's not clear for me how to do it because of the current code layout.

**Closed by asterite** 2017-09-09 22:36 UTC
Labels: kind:bug, topic:compiler
