### ISSUE TITLE
Trying to downcast Bool <- Int32

### ISSUE THREAD

**Issue by uSide** [crystal-lang/crystal#5009] opened 2017-09-19 20:58 UTC
Crystal: `Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1`
OS: `Ubuntu 14.04 on VirtualBox (Windows 10 host)`

Code to reproduce
```crystal
struct Test
  def initialize(**args, @w = false)
  end

  def self.test(**args)
    self.new(**args, false)
  end
end

Test.test(s: 2)
```

**Comment by asterite** [comment] 2017-09-19 21:15
Fixed a few days ago. Will be available in the next release :-)

Well, "fixed". Arguments after a double splat will not be allowed (they are accidentally allowed, that's the bug).

Duplicate of #4965

**Closed by asterite** 2017-09-19 21:15 UTC

**Comment by bew** [comment] 2017-09-19 21:35
@asterite do you know why the current error message is `Trying to downcast Bool <- Int32` ? What is happening for this to happen? (just curious)

**Comment by asterite** [comment] 2017-09-19 21:39
No idea :-D
