### ISSUE TITLE
BUG: called create_llvm_type for I when doint array.compact!

### ISSUE THREAD

**Issue by solovieff** [crystal-lang/crystal#7791] opened 2019-05-17 18:23 UTC
```
def get_accounts(shopExternalId : Int8)
        registerUrl : String = "/Portfolio/Representatives/" + shopExternalId.to_s + "/Accounts"

        accountResponse = @resource[registerUrl].get()

        puts accountResponse.status_code

        puts accountResponse.body

        #projects = JSON.parse(json).as(Array)
        #project = projects.first.as(Hash)["project"].as(Hash)
        #id = project["id"].as(Int64)

        accounts = JSON.parse(accountResponse.body).as(Array)

        accounts.compact!

        puts accounts.to_s
        accounts.each do |account|
          account = account.as(Hash)
          id = account["id"].as(String)
          puts id
          #name = account["name"]
          #number = account["number"]
          #puts id + " " + name + " " + number
        end

        #JSON.parse_raw(accountResponse.body) : Hash(String, JSON::Type)
      end
```

```
| => crystal -v
Crystal 0.28.0 (2019-04-24)

LLVM: 6.0.1
Default target: x86_64-apple-macosx
```

> crystal src/main.cr 
> BUG: called create_llvm_type for I (Exception)
>   from Crystal::LLVMTyper#create_llvm_type<Crystal::Type+, Bool>:NoReturn
>   from Crystal::LLVMTyper#llvm_type<Crystal::Type+, Bool>:LLVM::Type
>   from Crystal::MainVisitor#visit<Crystal::SizeOf>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::MainVisitor@Crystal::SemanticVisitor#expand_inline_macro<Crystal::MacroIf, Nil>:Crystal::ASTNode+
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::MainVisitor#visit<Crystal::If>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:search_in_parents:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in<Crystal::UnionType+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Call#instantiate<Crystal::Matches, Crystal::Type+, Nil, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in_type<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Nil, String, Bool, Bool, Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches_in:with_literals<Crystal::Type+, Array(Crystal::Type+), (Array(Crystal::NamedArgumentType) | Nil), Bool>:Array(Crystal::Def+)
>   from Crystal::Call#lookup_matches:with_literals<Bool>:Array(Crystal::Def+)
>   from Crystal::Call#recalculate:Nil
>   from Crystal::MainVisitor#visit<Crystal::Call>:Bool
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::MainVisitor>:Nil
>   from Crystal::Program#visit_main<Crystal::ASTNode+, Crystal::MainVisitor, Bool, Bool>:Crystal::ASTNode+
>   from Crystal::Program#semantic<Crystal::ASTNode+, Bool>:Crystal::ASTNode+
>   from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
>   from Crystal::Command#run_command<Bool>:Nil
>   from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
>   from main
> Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

**Comment by asterite** [comment] 2019-05-17 18:41
Probably duplicate of #5927

**Comment by asterite** [comment] 2019-05-17 21:58
Yes, duplicate. Check that `JSON.parse` doesn't return `Array`, it returns `JSON::Any` which can't be casted to `Array`. Your code is probably too old. But the next compiler version will give you a proper error message.

**Closed by asterite** 2019-05-17 21:58 UTC
