### ISSUE TITLE
crystal choose wrong initialize method

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#4086] opened 2017-02-27 19:28 UTC
```crystal
class A
  def initialize
  end
end

class A::B(T) < A
  def initialize(@v : T)
  end
end

class A::C::B(T) < A
  def initialize(@v : T, @v2 : Int32)
  end
end

A::C::B(Int32).new(1, 10)
```

```
wrong number of arguments for 'A::B(Int32)#initialize' (given 2, expected 1)
Overloads are:
 - A::B(T)#initialize(v : T)

  def initialize(@v : T, @v2 : Int32)
  ^
```

**Comment by asterite** [comment] 2017-03-03 18:54
Closing as duplicate of #2665 (generics inheritance is still broken)

**Comment by HertzDevil** [comment] 2021-07-07 23:25
`A::C::B.new` is expanded into the following:

```crystal
class A::C::B(T) < A
  def self.new(v : T, v2 : Int32)
    obj = B(T).allocate
    obj.initialize(v, v2)
    ::GC.add_finalizer(obj) if obj.responds_to?(:finalize)
    obj
  end
end
```

Here path lookup for `B(T)` in the constructor returns `A::B(T)` because for some reason lookup proceeds in `A::C::B`'s superclass first. It actually can happen without generics at all:

```crystal
class A
  class B
  end

  module C
    class B < A
      def self.foo
        B
      end
    end
  end
end

A::C::B.foo # => A::B
```

**Closed** 2021-09-07 14:59 UTC
Labels: kind:bug, topic:compiler:generics
