### ISSUE TITLE
"Broken pipe" error on crystal tool hierarchy 

### ISSUE THREAD

**Issue by dinko-pehar** [crystal-lang/crystal#11772] opened 2022-01-26 23:13 UTC
While using `crystal tool hierarchy` on some of the files, I get broken pipe error:

> $ crystal tool hierarchy src/entry_point_file.cr | /usr/bin/less 

```
Error writing file: Broken pipe (IO::Error)
  from /build/source/src/io/evented.cr:156:7 in 'unbuffered_write'
  from /build/source/src/io/buffered.cr:219:5 in 'write_byte'
  from /build/source/src/io.cr:174:5 in 'print_type'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:144:7 in 'print_subtypes'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:168:9 in 'print_type'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:144:7 in 'print_subtypes'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:168:9 in 'print_type'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:144:7 in 'print_subtypes'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:168:9 in 'print_type'
  from /build/source/src/compiler/crystal/tools/print_hierarchy.cr:122:9 in 'tool'
  from /build/source/src/compiler/crystal/command.cr:108:7 in 'run'
  from /build/source/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /build/source/src/crystal/main.cr:110:5 in 'main'
  from /nix/store/563528481rvhc5kxwipjmg6rqrl95mdx-glibc-2.33-56/lib/libc.so.6 in '__libc_start_main'
  from ../sysdeps/x86_64/start.S:122:0 in '_start'
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues

```

Crystal 1.2.2 (2021-11-23)
LLVM: 10.0.1
Default target: x86_64-unknown-linux-gnu

**Comment by Sija** [comment] 2022-01-26 23:41
Duplicate of #9065

**Comment by asterite** [comment] 2022-01-26 23:43
Right, it affects all Crystal programs, and Crystal is made in Crystal.

**Closed by asterite** 2022-01-26 23:43 UTC
Labels: kind:bug
