### ISSUE TITLE
RFC: no limit to block arguments inside parentheses

### ISSUE THREAD

**Issue by asterite** [crystal-lang/crystal#11567] opened 2021-12-10 14:52 UTC
Right now you can do something like this:

```crystal
ary = [[1, 2], [3, 4]]
ary.each do |(x, y)|
  puts x, y
end
```

The above roughly translates to this:

```crystal
ary = [[1, 2], [3, 4]]
ary.each do |temp|
  x, y = temp
  puts x, y
end
```

However, nesting parentheses inside other parentheses is a syntax error:

```crystal
ary = [
  [[1, 2],
   [3, 4]],
  [[5, 6],
   [7, 8]],
]
ary.each do |((a, b), (c, d))| # syntax error
  puts a, b, c, d
end
```

However, the above works perfectly fine in Ruby (*)

It would be nice if Crystal supported the same thing. I originally implemented the parentheses thing with just one level because of:
- laziness
- not having found in real life that I needed multiple parentheses levels, so why bother implementing it?

But doing advent of code this year I found it would have been nice to have this. If not for the actual functionality, just for consistency.

The above should roughly translate to:

```crystal
ary = [
  [[1, 2],
   [3, 4]],
  [[5, 6],
   [7, 8]],
]
ary.each do |temp|
  temp1, temp2 = temp
  a, b = temp1
  c, d = temp2
  puts a, b, c, d
end
```

## (*) Ruby

It turns out, you can do a lot more things in Ruby! For example:

```ruby
ary = [{a: 1, b: 2}]
ary.each do |a:, b:|
  p a, b
end
```

And you can even do this:

```ruby
def foo((x, y))
  puts x, y
end

foo [1, 2]
```

That is, method definition syntax and block syntax have in fact the same syntax.

But I don't think we should go that far. For now just allowing nested parentheses would be nice.

**Comment by HertzDevil** [comment] 2021-12-10 22:19
Duplicate of #8237?

**Comment by asterite** [comment] 2021-12-10 23:04
You are right! Thanks.

**Closed** 2021-12-11 05:22 UTC
Labels: kind:feature, status:discussion
