### ISSUE TITLE
clang bindings not working on windows

### ISSUE THREAD

**Issue by dsisnero** [crystal-lang/crystal#12871] opened 2022-12-25 19:19 UTC
## Bug Report

Not sure why require is not working on windows. I downloaded crystal_lib and tried to build it.

f:\programming\source\repos\git\crystal_lib>crystal build --error-trace --release --debug --verbose src\main.cr
Error: while requiring “./crystal_lib”

main.cr is in the same directory as crystal_lib.cr

f:\programming\source\repos\git\crystal_lib>crystal env
CRYSTAL_CACHE_DIR=“C:\Users\Dominic E Sisneros\AppData\Local\crystal\cache”
CRYSTAL_PATH=lib;F:\windows\scoop\apps\crystal\current\src
CRYSTAL_VERSION=1.6.2
CRYSTAL_LIBRARY_PATH=F:\windows\scoop\apps\crystal\current\lib
CRYSTAL_OPTS=“”

--------------------------
Reply from 
[straight-shoota](https://forum.crystal-lang.org/u/straight-shoota)
[Core Team](https://forum.crystal-lang.org/g/core-team)
[1d](https://forum.crystal-lang.org/t/crystal-on-windows-require-not-working/5201/2?u=dsisnero)
This means there is an error within ./crystal_lib. But for some reason the compiler doesn’t report the error message, only that it happened while requiring ./crystal_lib.
I have seen this before on Windows, but I think I also saw it on linux once. Not sure what’s causing this. Haven’t been able to isolate it.

The underlying error here is from lib_clang:

Error executing process: '[ -n \"$LLVM_CONFIG\" ] && command -v \"$LLVM_CONFIG\" || command -v 
llvm-config-8 || command -v llvm-config-7 || command -v llvm-config-6.0 || command -v llvm-config60 || 
command -v llvm-config-5.0 || command -v llvm-config50 || command -v llvm-config-4.0 || command -v 
llvm-config40 || command -v llvm-config\r\n                  ': Das System kann die angegebene Datei nicht 
finden. (File::NotFoundError)
Looks like theclang bindings are not ported to windows.

**Comment by straight-shoota** [comment] 2022-12-28 20:49
Duplicate of #12874 (which has a more elaborate description of the incomplete compiler error message and explains the reasons).

The original problem, missing Windows support in clang shard would be a feature request on the shard (https://github.com/crystal-lang/clang.cr/issues).

**Closed by straight-shoota** 2022-12-28 20:49 UTC
Labels: kind:bug
