### ISSUE TITLE
Spec fails in Colorize if stdout is not TTY

### ISSUE THREAD

**Issue by lugia-kun** [crystal-lang/crystal#8609] opened 2019-12-22 11:30 UTC
Following two spec fails if standard output is not TTY (redirected):
```
$ CC="gcc -fuse-ld=gold" bin/crystal spec spec/std_spec.cr >spec.log
$ cat spec.log
(omit)

Failures:

  1) colorize colorizes with surround
     Failure/Error: io.to_s.should eq("\e[31mhello\e[0;32mworld\e[0;31mbye\e[0m")

       Expected: "\e[31mhello\e[0;32mworld\e[0;31mbye\e[0m"
            got: "\e[31mhelloworldbye\e[0m"

     # spec/std/colorize_spec.cr:141

  2) colorize colorizes with to_s
     Failure/Error: ColorizeToS.new.colorize.red.to_s.should eq("\e[31mhello\e[0;34mworld\e[0;31mbye\e[0m")

       Expected: "\e[31mhello\e[0;34mworld\e[0;31mbye\e[0m"
            got: "helloworldbye"

     # spec/std/colorize_spec.cr:181

```

### crystal version

```
$ bin/crystal version
Using compiled compiler at .build/crystal
Crystal 0.33.0-dev [5704b9e6c] (2019-12-22)

LLVM: 9.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment] 2020-02-10 14:32
I can't reproduce this on master.

**Comment by RX14** [comment] 2020-02-11 01:33
Fixed by https://github.com/crystal-lang/crystal/pull/8673

**Closed by RX14** 2020-02-11 01:33 UTC
Labels: kind:bug
