### ISSUE TITLE
Segmentation fault: 11 on OSX 10.7.5

### ISSUE THREAD

**Issue by tomas** [crystal-lang/crystal#1097] opened 2015-08-03 06:01 UTC
On a somewhat old version of OSX, running bin/crystal from the new 0.7.5 tarball yields an ugly error.

```
~/Downloads/crystal-0.7.5-1 $ bin/crystal 
bin/crystal: line 6: 24327 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

I also tried 0.7.4 and got the same result. I'm assuming this is due to this older version of OSX.

Is there anything we can do about this? I think it would also help to document this somewhere (In case it can't be fixed). The [homebrew formula](https://github.com/manastech/homebrew-crystal) should also refuse to continue unless the OSX version is supported.

**Comment by waj** [comment] 2015-08-03 18:39
More details could be helpful. Please open the "Console" app and find the crystal crash dump under "User Diagnostic Reports" section.

**Comment by tomas** [comment] 2015-08-04 02:01
![image](https://cloud.githubusercontent.com/assets/10574/9051631/d481d2cc-3a11-11e5-9a72-9fae2bdfa7a6.png)

This is what the crash log says:

```
Process:         bash [24768]
Path:            /Users/USER/*/bash
Identifier:      bash
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  bash [20933]

Date/Time:       2015-08-03 19:01:12.575 -0700
OS Version:      Mac OS X 10.7.5 (11G63)
Report Version:  9

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_PROTECTION_FAILURE at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
Logical CPU: 2

Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7313
    thread_create: 0
    thread_set_state: 0
```

**Comment by waj** [comment] 2015-08-06 13:32
The "bash" process crashed? Isn't there any other crash dump?

**Comment by tomas** [comment] 2015-08-06 16:15
Nope. Cleared the log, ran `crystal` directly, and that's what appeared.

**Comment by waj** [comment] 2015-08-08 15:29
I'm testing on Lion now and I got the same error. It happens because the binaries are linked with some missing symbols. We should use the same approach we use for Linux, creating the binaries in an older environment. Custom binaries can later be customized for each OS version, using these more portable ones.

I'm working on creating a base and reproducible build environment with Vagrant and VirtualBox. Then I'll re-release the Darwin packages.

**Comment by tomas** [comment] 2015-08-08 16:46
Sweet! Gracias Juan.

**Comment by javajax** [comment] 2016-03-05 22:15
Are you still experiencing compilation issues?
have you tried this since 0.7.5?

**Comment by tomas** [comment] 2016-03-05 22:22
Will try again now.

**Comment by tomas** [comment] 2016-03-05 22:24
Same story:

```
$ bin/crystal 
bin/crystal: line 6: 73750 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"```

**Comment by javajax** [comment] 2016-03-05 22:55
what version of crystal are you trying to run?
This is what I have from homebrew.
```
crystal -v
Crystal 0.12.0 (Tue Feb 16 15:18:18 UTC 2016)
```

**Comment by tomas** [comment] 2016-03-05 23:15
crystal-0.12.0-1-darwin-x86_64.tar.gz

Downloaded from the releases section.

**Comment by javajax** [comment] 2016-03-05 23:28
The bin script is just a bash script that seems to be running `./embedded/bin/crystal`
Does something like this work for you?
```
$ ./embedded/bin/crystal -v
Crystal 0.12.0 [90eaec1] (Tue Feb 16 14:21:22 UTC 2016)
```

It looks from your error that the executable is being reached but it would be good to check.

**Comment by tomas** [comment] 2016-03-05 23:35
```
$ embedded/bin/crystal -v
Illegal instruction: 4
```

Crystal is probably using something that's not supported/available in older versions of OSX.

**Comment by javajax** [comment] 2016-03-05 23:41
Totally.
After some google reading there might be a way to build with a min version of the kernel.
That might at least provide better feedback.

http://stackoverflow.com/a/14285922

**Comment by javajax** [comment] 2016-03-05 23:42
interesting in the output you have listed above your version is unknown.
```
Version:         ??? (???)
```

**Comment by tomas** [comment] 2016-03-06 00:08
Yeah, no clue as to what that means. I guess we'll have to wait for news from @waj.

**Comment by javajax** [comment] 2016-03-06 01:15
I made a branch with a makefile that could solve your problem.
Would you be comfortable in trying to make a build?

**Comment by asterite** [comment] 2016-05-27 18:19
@tomas Are you still experiencing this issue with Crystal 0.17.4?

**Comment by tomas** [comment] 2016-05-27 19:01
@asterite No, but I can try and see next week, when I expect to get that Macbook working again, haha.

**Comment by tomas** [comment] 2016-06-12 17:50
Yes, still happenning on 0.17.4:

```
$ embedded/bin/crystal 
Illegal instruction: 4
````

**Comment by asterite** [comment] 2016-06-12 18:10
We should probably create the binaries on an old osx. Problem is, we don't have one.

@tomas What happens if you install it from homebrew? Do you get the same error or does it work?

**Comment by tomas** [comment] 2016-06-12 18:21
@asterite I'm actually trying to build it right now using the patch from #2273. I'm having some trouble building llvm but I'll get there. :)

**Comment by sdogruyol** [comment] 2017-09-10 15:54
Any updates on this with Crystal 0.23.1? If not can we close this please @asterite ?

**Comment by asterite** [comment] 2017-09-10 16:13
Closing. Please reopen if you have more info.

**Closed by asterite** 2017-09-10 16:13 UTC
Labels: kind:bug, topic:infrastructure

**Comment by liseki** [comment] 2018-03-28 13:41
Trying to build crystal on an old machine (OS X 10.7.5) and I still get a segfault on Crystal 0.24.2-1.

```
% bin/crystal
bin/crystal: line 102: 75537 Segmentation fault: 11  "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

Like with @tomas the crashing program just shows bash. Any thoughts?
