### ISSUE TITLE
Compiler ignoring runtime typecheck

### ISSUE THREAD

**Issue by KCreate** [crystal-lang/crystal#4168] opened 2017-03-20 15:04 UTC
The following code produces a compilation error.

```crystal
def call(&block)
  block.call
end

foo = rand > 0.5 ? "hello world" : 25

call do
  if foo.is_a? String
    foo.downcase
  end
end
```

Output:
```
Error in bug.cr:19: undefined method 'downcase' for Int32 (compile-time type is (Int32 | String))

    foo.downcase
        ^~~~~~~~

Rerun with --error-trace to show a complete error trace.
```

Weirdly, this only happens inside captured blocks. The following compiles and works just fine

```crystal
def call
  yield
end

foo = rand > 0.5 ? "hello world" : 25

call do
  if foo.is_a? String
    foo.downcase
  end
end
```

Changing `foo.downcase` to `foo.as(String).downcase` makes it work, which makes me assume this is a bug where the compiler ignores the `.is_a?` call.

I'm on `Crystal 0.21.1 (2017-03-14) LLVM 4.0.0`, `macOS 10.12.3`.

**Comment by asterite** [comment] 2017-03-20 15:06
Duplicate of #3093

**Closed by asterite** 2017-03-20 15:06 UTC

**Comment by KCreate** [comment] 2017-03-20 15:09
It's pretty similar to #3093, but this does the type check inside the captured block, while the example in #3093 does it outside.

**Comment by asterite** [comment] 2017-03-20 15:11
@KCreate True, but it happens because of the same reason: once a variable is captured, it has all the types assigned to it in every place. Type restrictions won't work with such variables. You can, however, assign it to a local variable inside the captured block and then check against that one.

**Comment by KCreate** [comment] 2017-03-20 15:18
@asterite Okay thanks for clearing that up!
