### ISSUE TITLE
`expect_raises` failure breaks spec reporting.

### ISSUE THREAD

**Issue by faultyserver** [crystal-lang/crystal#5460] opened 2017-12-26 21:44 UTC
When running a spec that uses `expect_raises`, if the actual error raised does not match the given error class, the spec report will break when trying to output the failure.

Here's a minimized example:
```crystal
require "spec"

describe "expect_raises" do
  it "can handle wrong error types" do
    expect_raises(ArgumentError) do
      raise "wrong"
    end
  end
end
```

And the output it generates:

```shell
$ crystal spec
E

Failures:

  1) expect_raises can handle wrong error types

       Index out of bounds
Error running at_exit handler: Index out of bounds
$
```

The program immediately exits after `Error running at_exit...`. Any other spec failures from the run are not reported.

From the testing I did, this happens when the raised exception does not match the given type (i.e., using `Exception` as the given type will always work). This bug does _not_ occur if the block for `expect_raises` does not raise an exception.

Running Crystal 0.24.1 on macOS Sierra.

**Comment by bcardiff** [comment] 2017-12-26 21:55
@faultyserver I noticed this as well while releasing 0.24.1 but it seems that it was present since 0.22 and only affects osx. Probably using `--no-debug` would avoid the Index out of bounds.

I think is related to dwarf parsing. cc: @ysbaddaden

**Comment by kostya** [comment] 2017-12-26 22:12
https://github.com/crystal-lang/crystal/issues/5224

**Comment by straight-shoota** [comment] 2017-12-26 22:17
And #5413

**Comment by bcardiff** [comment] 2017-12-26 23:21
@straight-shoota Related but I don't think that's the issue.

I'm closing this as duplicate of #5224

**Closed by bcardiff** 2017-12-26 23:21 UTC
