### ISSUE TITLE
Compiler gets stuck

### ISSUE THREAD

**Issue by Fusion** [crystal-lang/crystal#2302] opened 2016-03-14 00:10 UTC
I apologize in advance for the vagueness of this report. I hope you can point me in the right direction to debug the issue.

Basically, when I compile this project: https://github.com/Fusion/cfrbck sometimes the compiler gets stuck. From a user standpoint, I am not sure what is going on. Simply it never returns to my shell's prompt.

When I was running crystal12.0, I could work around the issue by deleting the .crystal directory.

With 13.0, this does not seem to help. If I Ctrl/c, `rm -rf .crystal` and `crystal build` several times in a row,  it eventually works.

This is on OS X, crystal installed using `brew`

**Comment by asterite** [comment] 2016-03-14 00:21
I have experiences this myself too, though it doesn't happen very frequently. I don't know why it happens, I'm sure there must be a bug in the code generation that triggers this bug on certain conditions (for example we recently found a bug in some `if cond` checking, when `cond` was a Pointer type).

Does it happen a lot in that project? If you have a build script to compile it many times, does it soon happen? If so, I can try to use that to find out why it happens.

**Comment by asterite** [comment] 2016-04-02 13:42
The problem seems to be related to `fork`. The way to reproduce it is this:

```crystal
# foo.cr
require "file_utils"

def foo
  File.read(__FILE__)
  File.size(__FILE__)
  FileUtils.cmp(__FILE__, __FILE__)
end

jobs_count = 0
n_threads = 8

1_000.times do |i|
  fork { foo }

  jobs_count += 1

  if jobs_count >= n_threads
    LibC.waitpid(-1, out stat_loc, 0)
    jobs_count -= 1
  end
end

puts "Done!"
```

Then in bash:

```
crystal build foo.cr --release
while true; do ./foo; done
```

The output I get is this:

```
$ while true; do ./foo; done
Done!
(and many more...)
Done!
Could not raiseDone!
Done!
(and many more...)
Done!
Could not raiseDone!
Done!
Done!
Could not raiseDone!
Could not raiseDone!
Done!
Done!
Done!
Done!
Done!
Could not raiseDone!
Done!
(and a few more...)
Done!
(stuck!)
```

**Comment by asterite** [comment] 2016-04-02 13:45
And sometimes in the output I get this:

```
libc++abi.dylib: terminating with uncaught foreign exception
```

And this:

```
Invalid memory access (signal 11) at address 0x1
[4500577904] __crystal_sigfault_handler +64
[140735680644394] _sigtramp +26
[140735573696421] _ZNSt3__113basic_ostreamIcNS_11char_traitsIcEEE5flushEv +143
[140735573732760] _ZNSt3__18ios_base4InitD2Ev +16
[140735727902975] __cxa_finalize_ranges +345
Could not raise[140735727903747] exit +55
```

Something seems to be pretty broken there.

**Comment by ysbaddaden** [comment] 2016-04-02 14:49
On linux I sometimes have `Error running at_exit handler: File not open for writing`. Maybe that's the exception that usually can't be raised? BTW crystal can't raise, because `LibUnwind.raise_exception` returns `_URC_END_OF_STACK` which means:

> the unwinder encountered the end of the stack during phase one without finding a handler.

It won't get stuck, though, nor do I have `invalid memory access` errors.

**Comment by waj** [comment] 2016-04-04 01:55
I found the problem and working on the fix. Basically `LibC.waitpid` is still used during codegen (https://github.com/crystal-lang/crystal/blob/master/src/compiler/crystal/compiler.cr#L247-L253) but there is now a dedicated signal handling for SIGCHLD, so it leads to a race condition.

@technorama I'm not sure why the signal handling pipe must be closed before finishing: https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L170. What could happen if I remove that line?

**Comment by waj** [comment] 2016-04-04 02:25
I just committed what I think should fix this issue (but sent the commit with the wrong issue number :disappointed:) 1ecc607

Please try it and let me know.

BTW, the example that @asterite posted will continue to fail. Basically it's wrong to use `LibC.waitpid`. Instead `Process#wait` must be used.

**Comment by asterite** [comment] 2016-05-10 19:39
This never happened to me anymore, so I guess it's fixed.

**Closed by asterite** 2016-05-10 19:39 UTC
Labels: bug, compiler
