### ISSUE TITLE
Invalid memory access (signal 11)

### ISSUE THREAD

**Issue by petoem** [crystal-lang/crystal#4391] opened 2017-05-08 15:37 UTC
I recently ported a haste-client from ruby to crystal.
My crystal version: [https://github.com/petoem/haste-client](https://github.com/petoem/haste-client)

Operation System: Solus OS, Kernel 4.9.26
Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0

When trying to compile the haste-client it gives this output:
```
crystal build src/haste.cr --release
Invalid memory access (signal 11) at address 0x8
[0x56ef3f] __crystal_sigfault_handler +63
[0x28c3914] sigfault_handler +40
[0x7f01b3be9b30] ???
[0x229c03b] ???
[0x229cea1] ???
[0x229f361] ???
[0x22a0fb1] ???
[0x27f5fdf] _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE +607
[0x27f601b] _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE +43
[0x27f5c57] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +759
[0x2623047] ???
[0x26237f5] LLVMTargetMachineEmitToFile +325
[0x14f585b] ???
[0x14343cf] ???
[0x1cb6645] ???
[0x5a23f9] ???
[0x56e86d] main +18893
[0x7f01b3554671] __libc_start_main +241
[0x53b871] ???
```

The same with this:
```
crystal deps build --release
Building: haste
Error target haste failed to compile:
Invalid memory access (signal 11) at address 0x8
[0x56ef3f] __crystal_sigfault_handler +63
[0x28c3914] sigfault_handler +40
[0x7f019f8d7b30] ???
[0x229c03b] ???
[0x229cea1] ???
[0x229f361] ???
[0x22a0fb1] ???
[0x27f5fdf] _ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE +607
[0x27f601b] _ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE +43
[0x27f5c57] _ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE +759
[0x2623047] ???
[0x26237f5] LLVMTargetMachineEmitToFile +325
[0x14f585b] ???
[0x14343cf] ???
[0x1cb6645] ???
[0x5a23f9] ???
[0x56e86d] main +18893
[0x7f019f242671] __libc_start_main +241
[0x53b871] ???
```

i can successfully compile it with the following commands:
`crystal deps build`
`crystal build src/haste.cr`

It seems that adding `--release` makes it fail.

oh, by the way it compiles with `crystal deps build --production` but i have no idea what `--production` flag does.

**Comment by ysbaddaden** [comment] 2017-05-08 15:42
Would you be able to compile crystal itself against LLVM 3.8? We have known issues with older LLVM versions which we're removing support for (further releases will use LLVM 3.8.1).

**Comment by petoem** [comment] 2017-05-08 17:23
@ysbaddaden i have just noticed that my installed LLVM version is 3.9.1 but `crystal --version` reports 3.5.0.

I tried to compile crystal as described in the [docs](https://crystal-lang.org/docs/installation/from_source_repository.html). (with additional git checkout tags/0.22.0)
But running `make spec` gives this.
```
Using /usr/bin/llvm-config [version=3.9.1]
./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
Error in spec/all_spec.cr:1: while requiring "prelude"

require "spec"
^

in src/prelude.cr:15: while requiring "exception"

require "exception"
^

in src/exception.cr:1: while requiring "callstack"

require "callstack"
^

in src/callstack.cr:1: while requiring "c/dlfcn": can't find file 'c/dlfcn' relative to '/home/akai/Projects/crystal/src'

require "c/dlfcn"
^

make: *** [Makefile:102: .build/all_spec] Error 1
```

**Comment by ysbaddaden** [comment] 2017-05-08 18:03
We don't seem to have a libc bindings for your host, or we don't understand/support the target to select one. What does `llvm-config --host-target` prints?

**Comment by petoem** [comment] 2017-05-08 18:23
```
llvm-config --host-target
x86_64-solus-linux
```

What are the supported target triples?

**Comment by kirbyfan64** [comment] 2017-05-08 18:45
I think maybe you could just do something like `crystal build --triple x86_64-linux-gnu thing.cr`.

**Comment by petoem** [comment] 2017-05-08 19:38
I made a hello world test file, with this code:
```
puts "Hello World !"
```
I tried to compile it and it works normally. With `--release` and `--target` set to `x86_64-linux-gnu`.

But compiling my haste-client works only without `--release` mode.
If I try to use `--release` mode it fails as before.

**Comment by RX14** [comment] 2017-05-08 20:07
So, why does solus have a separate target triple, and what are the differences (if any) between it and x86_64-linux-gnu? I can't find any info on the internet. If there are none then we should just alias it.

**Comment by petoem** [comment] 2017-05-08 20:26
You can take a look at the llvm package or others here.
[https://git.solus-project.com/packages/llvm/](https://git.solus-project.com/packages/llvm/)

**Comment by ysbaddaden** [comment] 2017-05-09 08:12
About the **--release** issue: it would seem the issue isn't related to the LLVM version, thanks for testing. Now we have another bug :disappointed: 

About the **host target**, this is part a Solus issue, part a Crystal issue.

The Solus issue is that the `x86_64-solus-linux` target tiple is invalid. We understand it as:
- `arch=x86_64` (correct)
- `sys=solus`  (wrong: it's the `vendor`)
- `abi=linux` (wrong: it's the `sys`)

The triple is missing an actual ABI (libc) to target. Assuming the libc is glibc, it should be `x86_64-solus-linux-gnu` instead, or plainly `x86_64-linux-gnu`, or `x86_64-linux-musl` for musl-libc, or `arm-linux-gnueabi` for glibc on ARM, `arm-linux-android` for Android (unsupported), ...

The Crystal issue is that we use pre-generated libc bindings. Ideally we should generate them automatically from C headers. That would avoid the issue, but it's more complicated to put in place and would require more libraries (i.e. `libclang`).

**Comment by petoem** [comment] 2017-05-09 10:40
Yes, Solus OS uses glibc.
I thought, maybe `x86_64-linux-gnu` works and @RX14 said it could be aliased, but i didn't know how.
So i just copied `src/lib_c/x86_64-linux-gnu` to `src/lib_c/x86_64-solus-linux`. :laughing: 
It compiles "`make`" successfully as before, but now `make spec` works too.  

Output:
```
 make spec
Using /usr/bin/llvm-config [version=3.9.1]
./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
.build/all_spec 
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*.........................................................................................................................................................................................................................................................................................................................................................................**.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*.........................................................................................................................................................................................................................................................**...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*..............................................*.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Using compiled compiler at .build/crystal
.Using compiled compiler at .build/crystal
.Using compiled compiler at .build/crystal
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................*.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................***................................................................................................................................................................................................................................................................................................................................

Pending:
  Code gen: lib codegens lib var set and get
  Code gen: primitives codegens pointer of int
  Code gen: primitives sums two numbers out of an [] of Number
  Semantic: cast casts from union to incompatible union gives error
  Semantic: def overload restricts on generic type with free type arg
  Semantic: def overload restricts on generic type without type arg
  Semantic: instance var doesn't infer type to be nilable if using self.class in call in assign
  Semantic: pointer allows using pointer with subclass
  Semantic: primitives types pointer of int
  Math Functions for computing quotient and remainder
  Thread::ConditionVariable signals
  Thread::ConditionVariable broadcasts
  Thread::ConditionVariable waits and send signal

Failures:

  1) File touch raises if file cannot be accessed
     Failure/Error: expect_raises Errno, "Operation not permitted" do

       Expected Errno but nothing was raised

     # spec/std/file_spec.cr:1023

Finished in 28:42 minutes
12143 examples, 1 failures, 0 errors, 13 pending

Failed examples:

crystal spec spec/std/file_spec.cr:1022 # File touch raises if file cannot be accessed
make: *** [Makefile:77: spec] Error 1
```

**Comment by petoem** [comment] 2017-05-09 10:57
Copying the directory `src/lib_c/x86_64-linux-gnu` to `src/lib_c/x86_64-solus-linux` solved it.
Now my haste-client compiles successfully with `--release` mode added.

**Comment by ysbaddaden** [comment] 2017-05-09 12:10
Maybe create a symlink instead of copying, so pulling a new Crystal version will automatically update the libc (it might change), but I guess it doesn't matter much since the next release should be compiled with LLVM 3.8.1

Closing, since this is an LLVM issue...

**Closed by ysbaddaden** 2017-05-09 12:10 UTC
Labels: kind:bug, topic:compiler
