### ISSUE TITLE
Interpreter : command literal hangs

### ISSUE THREAD

**Issue by hutou** [crystal-lang/crystal#12821] opened 2022-12-03 22:13 UTC
Literal commands, either  `%x` or backticks hang in interpreter, for example:
`%x(tput lines)`

**Comment by asterite** [comment] 2022-12-03 22:16
This is essentially https://github.com/crystal-lang/crystal/issues/12241

**Comment by Blacksmoke16** [comment] 2022-12-03 23:10
Duplicate of #12241

**Closed by Blacksmoke16** 2022-12-03 23:10 UTC
Labels: kind:bug, status:duplicate, topic:compiler:interpreter

**Comment by ysbaddaden** [comment] 2023-03-08 11:21
For anyone wondering, this is caused by the SIGCHLD signal being received and handled by the crystal executable but not being "forwarded" to the interpreted code in the VM, which ends up  waiting forever.
