### ISSUE TITLE
Segfault Invalid Memory Access

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3555] opened 2016-11-17 21:00 UTC
Trying to reproduce the bizarre error I mention on the mailing list, I ran into this:

```crystal
abstract class X
  alias Type = String | Array(Type) | Hash(Type, Type)

  def as_type(x)
    x.as(Type)
  end

  def foo(x)
    as_type(x)
  end

  def foo(x : Array)
    x.map{ |e| as_type(e) }
  end
end

class Y < X
  alias Type = String | Int32 | Array(Type) | Hash(Type, Type)

  def as_type(x)
    x.as(Type)
  end

  def foo(x)
    as_type(x)
  end
end

class Z < Y
  alias Type = String | Int32 | Array(Type) | Hash(Type, Type)

  def as_type(x)
    x.as(Type)
  end

  def foo(x)
    as_type(x)
  end
end

def odds(i : Int32)
  case i
  when 0
    1
  when 1
    "One"
  end
end

y = Y.new
p y.foo([1, "s", 1])
p y.foo(odds(0))
p y.foo(odds(1))

p typeof(y.foo([1, "s", 1]))
p typeof(y.foo(odds(0)))
p typeof(y.foo(odds(1)))

z = Z.new
p z.foo([1,2,3])
p typeof(z.foo([1,2,3]))

```

```
$ crystal build s.cr 
$ ./s 
Z::Type
Invalid memory access (signal 11) at address 0x67f700
[4377589] *CallStack::print_backtrace:Int32 +117
[4366072] __crystal_sigfault_handler +56
[4551768] sigfault_handler +40
[140494271886288] ???
[6813440] ???
```

**Comment by asterite** [comment] 2016-11-18 11:53
Reduced:

```cr
alias Type = Int32 | Array(Type)
([] of Int32).as(Type).to_s
```

That cast should fail. So this is basically a duplicate of #3524

**Closed by asterite** 2016-11-18 11:53 UTC
Labels: bug, compiler
