### ISSUE TITLE
can't apply visibility modifier

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2838] opened 2016-06-15 14:37 UTC
https://play.crystal-lang.org/#/r/11o3
i think error message is wrong

**Comment by asterite** [comment] 2016-06-15 14:46
Maybe it could say something like "`delegate to_s, @some` isn't a macro call, visibility modifiers can only be applied to defs, macros, and macro calls."?

The problem is that visibility modifiers are applied in a first pass, before resolving calls. The `delegate` call doesn't match the macro method `delegate` because it requires a `to:` named argument.

**Closed** 2016-06-23 19:59 UTC
Labels: compiler, enhancement

**Comment by asterite** [comment] 2016-06-23 20:01
It now gives a different error:

```
Error in ./foo.cr:6: can't use instance variables at the top level

  private delegate to_s, @some
                         ^~~~~
```

Basically, now the call is tried to be analyzed. Because it doesn't match the macro it tries to solve it as a call, and `@some` can't be used there.

I don't think it can be improved further, but the error gives you a hint that `delegate` wasn't found as a macro, which is better than before.
