### ISSUE TITLE
+= operator doesn't work for pointer.value

### ISSUE THREAD

**Issue by chenkovsky** [crystal-lang/crystal#5365] opened 2017-12-08 10:26 UTC
```crystal
struct A
  @b : Int32

  def initialize(@b)
  end

  def b=(x)
    @b = x
  end

  def b
    @b
  end
end

a = A.new 0
a.b += 1
puts a.b
ap = pointerof(a)
ap.value.b += 1
puts a.b
ap.value.b = ap.value.b + 1
puts a.b
```

output
```
1
1
2
```

**Comment by RX14** [comment] 2017-12-08 12:58
This is basically a duplicate of https://github.com/crystal-lang/crystal/issues/4933.

**Closed** 2017-12-08 17:51 UTC
Labels: status:duplicate
