### ISSUE TITLE
Process.on_terminate proc cannot be executed?

### ISSUE THREAD

**Issue by lost22git** [crystal-lang/crystal#14836] opened 2024-07-26 11:16 UTC
```
❯ hostnamectl
Operating System: Debian GNU/Linux 12 (bookworm)
          Kernel: Linux 5.15.153.1-microsoft-standard-WSL2
    Architecture: x86-64

❯ crystal version
Crystal 1.12.1 [4cea10199] (2024-04-11)

LLVM: 15.0.7
Default target: x86_64-unknown-linux-gnu
```

When I press CTRL+C, the program will be blocked all the time, and the on_termiante proc will not be executed to print and exit the program.

I want to know under what circumstances will it be blocked?
Or how can I debug the program to find out what is causing it to get blocked?

```crystal
Process.on_terminate do |reason|
  case reason
  when .interrupted?
    puts "Signal : interrupted"
  when .terminal_disconnected?
    puts "Signal : terminal disconnected"
  when .session_ended?
    puts "Signal : session ended"
  end
  Process.exit
end

```

![Screenshot 2024-07-26 191613](https://github.com/user-attachments/assets/d5a2d9c5-3b03-490f-b64c-471223478597)

**Comment by devnote-dev** [comment] 2024-07-26 12:14
With just the above code, the program will always exit with no output because there is no interrupt/terminate signal sent to the program, it terminates itself. The `#on_terminate` method and its underlying implementations also do not block, so I believe there is other code being executed in the program. Can you share more of the source?

**Comment by lost22git** [comment] 2024-07-26 13:06
>  because there is no interrupt/terminate signal sent to the program, it terminates itself.
why CTRL+C not sent interrupt/terminate signal sent to the program?

**Comment by lost22git** [comment] 2024-07-26 13:14
> Can you share more of the source?

the code mainly is spawnning 16 fibers to consume downloading task from task queue and download something from remote server

**Comment by Blacksmoke16** [comment] 2024-07-26 13:35
In that case it's possible there is some fiber in a tight loop that is not blocking/yielding which is not allowing the main fiber to run/execute the `#on_terminate` handler. Crystal also doesn't have any form of preemption. Hard to say without seeing the code, but I'm pretty sure the problem is going to be in your code, rather than the stdlib/compiler.

**Comment by devnote-dev** [comment] 2024-07-26 15:22
`chan.receive` is blocking which will switch to the first available fiber, in this case it's one of the 16 spawned. All of those fibers will remain blocked because of `loop { }` which is the same as `while true`.

**Comment by Blacksmoke16** [comment] 2024-07-26 17:58
Going to close this as a duplicate of https://github.com/crystal-lang/crystal/issues/1454

**Comment by Blacksmoke16** [comment] 2024-07-26 17:58
Duplicate of #1454

**Closed by Blacksmoke16** 2024-07-26 17:58 UTC
Labels: kind:bug, topic:stdlib:runtime

**Comment by lost22git** [comment] 2024-07-27 04:32
Skill issue 

Solution: I should use Go lang ;-)
