### ISSUE TITLE
File.join should handle "" separately

### ISSUE THREAD

**Issue by obskyr** [crystal-lang/crystal#5905] opened 2018-04-03 09:28 UTC
When using `File.join` with empty strings, some unexpected results can be seen:

```crystal
File.join("", "file.cr")
File.join(["dir", "", "file.cr"])
```

These should evaluate to `"file.cr"` and `"dir/file.cr"` respectively, but instead they evaluate to `"/file.cr"` (whoops, absolute path out of nowhere) and `"dir//file.cr"`.

**Comment by ysbaddaden** [comment] 2018-04-03 09:42
1. the behavior is identical to Ruby's, but maybe we should change it, the absolute path is probably unexpected;
2. double file separator is wrong, yes.

**Comment by RX14** [comment] 2018-04-03 09:48
I'm not sure 1 is unexpected. 2 can be fixed though.

**Comment by straight-shoota** [comment] 2018-04-03 13:51
The empty path `""` equals to the current directory `"."`. Joining `"", "file.cr"` should be equivalent to joining `".", "file.cr"`. Otherwise you could end up with really be unexpected behaviour, if an empty path as first argument would somehow turn into the root directory.

Both behaviours are currently wrong. Thy are fixed in #5635, although it includes a bigger refactoring.

**Comment by ysbaddaden** [comment] 2018-04-04 08:57
@straight-shoota can you extract a pull request to just fix these 2 behaviors? We could merge it quickly :)

**Closed** 2018-04-04 13:59 UTC
Labels: kind:bug, topic:stdlib

**Comment by AlexWayfer** [comment] 2018-06-11 11:43
> The empty path "" equals to the current directory ".".

No. Looks like `"a" equals to "b"`.

What does `File.join` do? 

> Returns a new string formed by joining the strings using File::SEPARATOR.

What `["", "file"].join(File::SEPARATOR)` will return? `"/file"`.

This is expected behavior.

I'm using this for web-paths in Ruby framework (`File.join(nil, static_dir, file_name)`)

**Comment by straight-shoota** [comment] 2018-06-11 12:00
Why would `""` equal to `"/"`? That's as much `"a" equals "b"`. And it's not even universally applicable.

If `File.join("", "file")` equals to `"/file"`, what would `File.join("foo", "", "file")` equal to? One could argue, it should also be `"/file`" if `""` refers to the root `"/"`. That doesn't make sense.

In fact, it is very logical to treat the *path component* `""` equal to `"."`, as for example `foo//bar` consists of three components: `["foo", "", "bar"]`. The second one is empty and semantically equivalent to `".  That applies anywhere in a path. Interpreting an empty path at the beginning of `File.join` as referring to the file system root `"/"` is a hack. It's inconsistent and platform-specific. This would not work as expected on a windows system.

If you need to join absolute paths, use an explicit root. It's just `"/"` instead of `""`.

Please be aware that `nil` isn't even a valid path component for `File.join` in Crystal.

**Comment by AlexWayfer** [comment] 2018-06-11 13:08
> Why would "" equal to "/"

It's not equal. `""` is member of parameters (Array), `"/"` is separator. Yeah, you're joining a-like things (path parts) with b-like separator.

> If File.join("", "file") equals to "/file", what would File.join("foo", "", "file") equal to?

`foo/file`, because `File.join` doesn't allow multiple `/` in a row. It's a feature.

>  if "" refers to the root "/"

Yeah, your root is empty-named: `%root_like_""%/file`

> Please be aware that nil isn't even a valid path component for File.join in Crystal.

I know, it's just an example.

> It's inconsistent and platform-specific.

OK, maybe it's argument.
