### ISSUE TITLE
Playground issue related to different type math

### ISSUE THREAD

**Issue by renich** [crystal-lang/crystal#9600] opened 2020-07-11 04:46 UTC
Sorry for the super-bad tittle, but I have no idea what to call it since I don't understand it myself. 

Here's my info:

```
[renich@introdesk ~]$ crystal -v
Crystal 0.35.1 (2020-06-19)

LLVM: 10.0.0
Default target: x86_64-unknown-linux-gnu

[renich@introdesk ~]$ cat /etc/fedora-release 
Fedora release 32 (Thirty Two)
```

The failing code:

```crystal
p int8 = 1_i8
p int16 = 16_i16
p int32 = 132_i32
p int64 = 164_i64
p uns64 = 264_u64

p int8 + int64
p int64 + int32 + uns64
```

I'll include a screenshot. 
![image](https://user-images.githubusercontent.com/225115/87216664-75fe2a00-c307-11ea-9802-959e203f61ac.png)

Also, I ran the code on a file and got this:

```
[renich@introdesk ~]$ crystal run test.cr 
1
16
132
264
364
Unhandled exception: Arithmetic overflow (OverflowError)
  from test.cr:7:8 in '__crystal_main'
  from ../../usr/share/crystal/src/crystal/main.cr:105:5 in 'main_user_code'
  from ../../usr/share/crystal/src/crystal/main.cr:91:7 in 'main'
  from ../../usr/share/crystal/src/crystal/main.cr:114:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by straight-shoota** [comment] 2020-07-11 11:04
Duplicate of #7091

**Closed by straight-shoota** 2020-07-11 11:04 UTC
