### ISSUE TITLE
Assignment to nested static arrays is tricky

### ISSUE THREAD

**Issue by dawkot** [crystal-lang/crystal#6542] opened 2018-08-15 17:09 UTC
```crystal
a = StaticArray(Int32, 1).new(0)
puts "before", a[0]
a[0] = 1
puts "after", a[0]

puts

b = StaticArray(StaticArray(Int32, 1), 1).new(StaticArray[0])
puts "before", b[0][0]
b[0][0] = 1
puts "after", b[0][0]
ptr = pointerof(b).as(Pointer(Int32))
ptr.value = 1
puts "after pointer use", b[0][0]
```
Output:

> before
> 0
> after
> 1
> 
> before
> 0
> after
> 0
> after pointer use
> 1

**Comment by asterite** [comment] 2018-08-15 18:32
StaticArray is a struct, so when you ask it with `[0]` it returns a copy. This is true for every struct.

What's your use case? Without knowing what you need, I'm 99% sure you don't need static arrays in your code. Static arrays are fairly low-level and are mostly used for interfacing with C and using them as static buffers for IO.

**Comment by jhass** [comment] 2018-08-15 18:53
Also duplicate of #3073 and the related issues, so closing :)

**Closed by jhass** 2018-08-15 18:53 UTC
Labels: status:invalid

**Comment by dawkot** [comment] 2018-08-15 19:03
"What's your use case?"
I'm writing a linear algebra library as exercise and figured I should use stack if I can.
