### ISSUE TITLE
Nil assertion in the Compiler when defining constants

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#12023] opened 2022-04-22 17:46 UTC
This code:

```cr
A = B
B = A = 1

p B
```

Crashes the compiler:

```
Nil assertion failed (NilAssertionError)
  from /crystal/src/nil.cr:108:5 in 'not_nil!'
  from /crystal/src/compiler/crystal/semantic/cleanup_transformer.cr:300:10 in 'transform'
  from /crystal/src/compiler/crystal/syntax/transformer.cr:7:14 in 'transform'
  from /crystal/src/compiler/crystal/semantic/cleanup_transformer.cr:288:20 in 'transform'
  from /crystal/src/compiler/crystal/syntax/transformer.cr:7:14 in 'transform'
  from /crystal/src/compiler/crystal/semantic/cleanup_transformer.cr:161:18 in 'transform'
  from /crystal/src/compiler/crystal/syntax/transformer.cr:7:14 in 'transform'
  from /crystal/src/compiler/crystal/semantic/cleanup_transformer.cr:14:14 in 'cleanup'
  from /crystal/src/compiler/crystal/semantic/cleanup_transformer.cr:11:5 in 'semantic:cleanup'
  from /crystal/src/compiler/crystal/compiler.cr:172:14 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:215:5 in 'run_command'
  from /crystal/src/compiler/crystal/command.cr:122:7 in '__crystal_main'
  from /crystal/src/crystal/main.cr:115:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by asterite** [comment] 2022-04-22 18:04
Most likely a duplicate of https://github.com/crystal-lang/crystal/issues/2874 ?

**Comment by beta-ziliani** [comment] 2022-04-22 18:53
Yup, closing it.

**Comment by beta-ziliani** [comment] 2022-04-22 18:54
BTW, @lbguilherme did you find out by chance, or did you happen to actually want to do that?

**Closed by beta-ziliani** 2022-04-22 18:53 UTC
Labels: kind:bug, topic:compiler:semantic

**Comment by lbguilherme** [comment] 2022-04-22 19:07
No, it was by chance.
