### ISSUE TITLE
[FEATURE] "No overload matches" output confusing

### ISSUE THREAD

**Issue by didactic-drunk** [crystal-lang/crystal#8179] opened 2019-09-13 08:45 UTC
Problem: 
* It's hard to pick which argument has the wrong type with lots of overloads or lots arguments.

Example:
```
Error: no overload matches 'Sodium::Cipher::Aead::Xchacha20Poly1305Ietf#decrypt_detached'
 with types Slice(UInt8), nonce: Sodium::Nonce, mac: Slice(UInt8), additional: String

Overloads are:
 - Sodium::Cipher::Aead::Xchacha20Poly1305Ietf#decrypt_detached(src : Bytes,
 - - dst : Bytes | ::Nil = nil, *, nonce : Nonce, 
 - - mac : Bytes, additional : Bytes | ::Nil = nil)
 - Sodium::Cipher::Aead::Chalsa#decrypt_detached(data, 
 - - dst : Bytes | ::Nil = nil, *, 
 - - mac : Bytes | ::Nil = nil, additional = nil)
```

Feature request:
*  Colorize the output for matching and nonmatching types to quickly see which types are incorrect.

**Comment by straight-shoota** [comment] 2019-09-13 09:09
Colorize could help, but only when color is supported (for example on a TTY). 

A good improvement would probably already be when we get the types at call site and the overloads formatted in the same way, using a proper `crystal format` style. This would make it easier to read the signatures and help compare them.

Additionally, it would be super great if matching arguments could be lined up similarly. This should work great for short signatures. But as soon as there are many arguments which span multiple lines and optional arguments not present everywhere, this becomes super complicated.

Example for a relatively simple set of overloads:
```
Call:
- foo(String,                             c: Nil)

Overloads are:
 - foo(a : String,         b : Int32 = 0, c : Bool = true)
 - foo(a : String,         b : Float64,   c : Bool = false)
 - foo(a : String,         b : Int64,     c : Bool)
 - foo(a : Time::Location, b,             c : Nil)
```

**Comment by didactic-drunk** [comment] 2019-09-13 11:48
The class and method name take a lot of horizontal space.  Show it once?
`Sodium::Cipher::Aead::Xchacha20Poly1305Ietf#decrypt_detached`

**Comment by straight-shoota** [comment] 2021-08-23 12:15
Closing as duplicate of #11106

**Closed by straight-shoota** 2021-08-23 12:15 UTC
