### ISSUE TITLE
Typed fibonnaci Arithmetic overflow (OverflowError)

### ISSUE THREAD

**Issue by LeandroRezendeCoutinho** [crystal-lang/crystal#10003] opened 2020-11-30 12:16 UTC
# Typed fibonnaci Arithmetic overflow (OverflowError)

### Code

```
def fib(n : UInt64)
  if n <= 1
    1
  else
    fib(n - 1) + fib(n - 2)
  end
end

puts fib(47)
```
### Error

Unhandled exception: Arithmetic overflow (OverflowError)
  from fib.cr:5:16 in 'fib'
  from fib.cr:5:5 in 'fib'
  from fib.cr:9:6 in '__crystal_main'
  from ../../../.asdf/installs/crystal/0.35.1/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from __libc_start_main
  from _start
  from ???
./fib_cr  10,38s user 0,00s system 99% cpu 10,383 total

### Environment
Ubuntu 20.04

Crystal 0.35.1 [5999ae29b] (2020-06-19)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu

**Comment by asterite** [comment] 2020-11-30 12:22
in the first branch you must return 1_u64

**Comment by straight-shoota** [comment] 2020-11-30 12:28
Best add UInt64 return type to the method signature, then the compiler would tell you that you return an incorrect type in that branch.

**Comment by asterite** [comment] 2020-12-02 14:18
Closing because it's not a bug.

**Closed by asterite** 2020-12-02 14:18 UTC
