### ISSUE TITLE
Strange behavior calling methods on derived generic types

### ISSUE THREAD

**Issue by ezrast** [crystal-lang/crystal#3990] opened 2017-02-03 02:05 UTC
This appears related to https://github.com/crystal-lang/crystal/issues/2665. Feel free to mark as dupe.

I expect the following code to work, but the Registry class raises an ArgumentError at runtime even though all of my NamedThings have different names. Unfortunately, behavior varies based on minor changes to unrelated code, so I can't find a smaller repro case. See the comments inline.
```crystal
abstract class Thing
  # Adding this makes the error go away:
  # def name; :x; end
end

class NamedThing(T) < Thing
  property name

  def initialize(@name : Symbol, registry : Registry?)
    registry.try &.register(self)
  end
end

class Registry
  property things = [] of Thing

  def register(thing : Thing)
    # Switching these if statements causes a segfault instead of an ArgumentError.
    # if @things.find { |th| thing.name == th.name; thing.name == th.name }
    if @things.find { |th| thing.name == th.name }
      raise ArgumentError.new "#{thing.name} - Registered things must have unique names"
    end
    @things << thing

    # Removing this sort makes the error go away.
    @things.sort_by! {|th| th.name}
    puts "Registered #{thing.name}!"
  end
end

class Empty1
end
class Empty2
end
class Empty3
end

reg1 = Registry.new
reg2 = Registry.new

# Changing the order of these assignments makes the error go away.
# Empty1/2/3 aren't strictly required; you can replace them with
# any three different types and the bug stays.
NamedThing(Empty1).new(:name1, reg1)
NamedThing(Empty2).new(:name2, nil)
NamedThing(Empty3).new(:name3, reg2)

# Removing this puts makes the error go away.
# Removing just one argument makes the error go away, unless
# you also remove the other puts in Registry#register.
puts(' ', ' ')
NamedThing(Empty1).new(:name4, reg2)

p reg1.things # => [#<NamedThing(Empty1):0x24ddfb0 @name=:name1>]
p reg2.things # => [#<NamedThing(Empty3):0x24ddfa0 @name=:name3>,
              #     #<NamedThing(Empty1):0x24ddf90 @name=:name4>]
```
I'm on Arch Linux and have tested with current and master versions of Crystal.
```
$  crystal version
Crystal 0.20.5 [ccf46c0] (2017-01-20)

$  ~/opt/crystal/bin/crystal version
Using compiled compiler at .build/crystal
Crystal 0.20.5+33 [d45fbff38] (2017-02-02)
```

**Comment by asterite** [comment] 2017-03-03 18:46
Closing as duplicate of #2665 (generics inheritance is still broken)

**Closed by asterite** 2017-03-03 18:46 UTC
Labels: community:to-research, kind:bug, topic:compiler
