### ISSUE TITLE
pass arguments to spawn

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#2962] opened 2016-07-06 16:21 UTC
would be nice if this works:
```crystal

x = rand < 0.5 ? 1 : nil

spawn(args: {x}) do |x|
  p(x + 1) if x
end

p(x + 1) if x 

sleep 0.1
```

because right now i cant just compare with `if x`, i should write this, which is noise in big code:
```crystal

x = rand < 0.5 ? 1 : nil

spawn do
  if y = x
    p y + 1
  end
end

if y = x
  p y + 1
end

sleep 0.1
```

**Comment by asterite** [comment] 2016-07-06 16:24
I think the compiler should just be a bit smarter and notice that `x` doesn't change, so `if x` should just work

**Comment by asterite** [comment] 2016-08-04 13:20
Closing as duplicate of #3093 (which describes the problem in a better way)

**Closed by asterite** 2016-08-04 13:20 UTC
Labels: draft, RFC, standard library
