### ISSUE TITLE
Can't call macro from Proc literal

### ISSUE THREAD

**Issue by hangyas** [crystal-lang/crystal#3083] opened 2016-08-03 14:42 UTC
```cr
macro foo
end

bar = ->{
  foo
}
```
`Error in line 5: macro 'foo' must be defined before this point but is defined later`

**Comment by jhass** [comment] 2016-08-03 15:01
Actually a duplicate of #2984 and fixed on master / with 0.19

**Closed by jhass** 2016-08-03 15:01 UTC
Labels: bug, compiler
