### ISSUE TITLE
Compiler crash when autofilled array assigns instance variable in class without type reference

### ISSUE THREAD

**Issue by SlayerShadow** [crystal-lang/crystal#6091] opened 2018-05-12 22:00 UTC
Similar to #2665 scope.

```crystal
class Foo
  def some_action
    @value = Array.new( 64 ){ 64 }
  end
end
```
Raises compiler error (will be shown below). But other declarations works correctly:
1. `value = Array.new( 64 ){ 64 }` - all ok (out of class or local variable).
2.
    ```crystal
    class Foo
      def some_action
        value = Array.new( 64 ){ 64 }
      end
    end
    ```
    All ok (local variable).
3) 
    ```crystal
    class Foo
      def bar
        @value = Array( Int32 ).new( 64 ){ 64 }
      end
    end
    ```
    All ok (type reference).

```
$ crystal -v
Crystal 0.24.2 [4f9ed8d03] (2018-03-08)

LLVM: 4.0.0
Default target: x86_64-unknown-linux-gnu
```
```
$ uname -a
Linux pc 4.16.0-1-amd64 #1 SMP Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux
```

Error:
```
cast from Nil to Crystal::GenericInstanceType+ failed, at /crystal/src/compiler/crystal/types.cr:1428:20:1428
???
...
???
Error: you've found a bug in the Crystal compiler.
```
Backtrace is filled by "?" signs, and nothing helped to display it.

**Comment by asterite** [comment] 2018-05-23 17:18
Duplicate of #5383

**Closed by asterite** 2018-05-23 17:18 UTC
Labels: kind:bug, topic:compiler
