### ISSUE TITLE
Interpreter: Reached the unreachable (Exception) with generic class

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12304] opened 2022-07-22 01:41 UTC
## Bug Report
Example code:
```crystal
class A
  def foo
    puts "foo"
  end
end

class B(T) < A
end

a1 = B(Int32).new.as(A)
a2 = B(String).new.as(A) # It doesn't error after removing this line.
a1.as(B).foo
```
It works fine in compiled mode but raises error in interpreted mode.

Interpreter error:
```
In: B(T)#foo
Node: raise "unreachable"
Reached the unreachable (Exception)
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/interpreter.cr:337:7 in 'interpret'
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/interpreter.cr:235:13 in 'interpret'
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/repl.cr:100:5 in 'interpret_and_exit_on_error'
  from /home/chao/git/personal/crystal/src/gc/boehm.cr:129:5 in 'run'
  from /home/chao/git/personal/crystal/src/compiler/crystal/command.cr:51:5 in '__crystal_main'
  from /home/chao/git/personal/crystal/src/crystal/main.cr:115:5 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from /home/chao/git/personal/crystal/.build/crystal in '_start'
  from ???
```

crystal version:
```
Crystal 1.6.0-dev [c4799c628] (2022-07-21)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu

OS: Ubuntu 22.04
```

**Comment by asterite** [comment] 2022-07-24 11:27
Yet another compiler bug:

```crystal
class A
end

class B(T) < A
end

a = B(Int32).new.as(A)
b = a.as(B)

puts a.is_a?(B(Int32)) # Correctly prints true
puts b.is_a?(B(Int32)) # Incorrectly prints false
```

**Comment by HertzDevil** [comment] 2022-07-24 11:31
That one is probably a duplicate of #10831

**Comment by asterite** [comment] 2022-07-24 12:56
Could #10831 be split into individual failures? It seems like a general issue, but maybe if it's split into individual ones it's going to be easier to track.

**Closed** 2022-07-24 20:45 UTC
Labels: kind:bug, topic:compiler:interpreter
