### ISSUE TITLE
subclasses macro allows the instantiation of abstract classes

### ISSUE THREAD

**Issue by untied** [crystal-lang/crystal#6525] opened 2018-08-11 17:43 UTC
Behold! I can instantiate the abstract subclasses using subclasses macro:

```crystal
abstract class MainClass # Abstract!
  abstract def test: String
  
  def self.trace
    subs = {{@type.subclasses}}
    subs.each do |s|
      inst = s.new
      puts "--INSTANTIATED-->> #{s.name} -->> #{inst.test}"
    end
  end
end

abstract class MainSubClassA < MainClass # Also abstract!
  def test: String
    "Ta-da! #1"
  end
end

abstract class MainSubClassB < MainClass # Abstract as well!
  def test: String
    "Ta-da! #2"
  end
end

MainClass.trace
```

Live example is here: https://play.crystal-lang.org/#/r/4prz/edit

**Comment by asterite** [comment] 2018-08-11 19:38
Duplicate of https://github.com/crystal-lang/crystal/issues/3835

**Closed** 2018-08-12 22:07 UTC
