### ISSUE TITLE
BUG: trying to downcast Language::Definition (Crystal::NonGenericClassType) <- Language (Crystal::NonGenericClassType) (Exception)

### ISSUE THREAD

**Issue by dorianmariefr** [crystal-lang/crystal#12137] opened 2022-06-19 16:52 UTC
Hi, I'm trying to reuse my parsers in other parsers and hit this bug:

```cr
Code::Array = Language.create do
  rule(:element) do
    Code::Nothing | Code::Boolean | Code::String | Code::Number
  end

  root do
    element.repeat.aka(:array)
  end
end
```

Maybe related to my use of `method_missing`:

```cr
    macro method_missing(method)
      def {{method}}
        @language.find_atom({{method.symbolize}}) ||
          raise(NoRuleFound.new({{method.stringify}}))
      end
    end
```

Here is the version of repository with the bug https://github.com/dorianmariefr/language/tree/ebfca9b88d263de5abb7ec6ea064af5e4e923b77

```
BUG: trying to downcast Language::Definition (Crystal::NonGenericClassType) <- Language (Crystal::NonGenericClassType) (Exception)
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'raise<Exception>:NoReturn'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'raise<String>:NoReturn'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#downcast_distinct<LLVM::Value, Crystal::Type+, Crystal::Type+>:NoReturn'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#downcast<LLVM::Value, Crystal::Type+, Crystal::Type+, Bool>:LLVM::Value'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#prepare_call_args_non_external<Crystal::Call, Crystal::Def+, Crystal::Type+>:Tuple(Array(LLVM::Value), Bool)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Call>:Bool'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#initialize_const<Crystal::Const>:LLVM::Value'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::CodeGenVisitor#visit<Crystal::Assign>:(Bool | Nil)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::CodeGenVisitor>:Nil'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'Crystal::Command#spec:NoReturn'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in '__crystal_main'
  from /Users/dorianmariefr/.asdf/installs/crystal/1.4.1/embedded/bin/crystal in 'main'
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by Blacksmoke16** [comment] 2022-06-19 17:19
Duplicate of #12099? It's probably the same bug for both I would guess.

**Closed** 2022-06-21 20:48 UTC
Labels: kind:bug, topic:compiler:semantic
