### ISSUE TITLE
Object#then

### ISSUE THREAD

**Issue by tenebrousedge** [crystal-lang/crystal#8367] opened 2019-10-23 02:17 UTC
This may already have been discussed, but "then" is a little hard to search for. Ruby has an `Object#then` method:
```crystal
class Object
  def then
    yield self
  end
end
```
This can be seen as complimentary to `tap`, but returning the value of the executed block rather than the receiver. There is of course nothing which cannot already be done without this, but it is occasionally useful for function chaining:
```crystal
5.then &.+(2) #=> 7

n = 15
[{3, "Fizz"}, {5, "Buzz"}].select { |i, _| n.divisible_by? i }.then do |result|
  result.empty? ? n.to_s : result.join &.last
end

# instead of
method_three(method_two(method_one(arg)))
# one could write
method_one(arg).then &.method_two.then &.method_three
```
I would find it convenient if this were added to the language. The Ruby implementation is slightly more complex, returning an iterator if no block is given. That to me sounds like an unnecessary trouble; I'd be just fine with using the implementation given above. I appreciate any thoughts or feedback on this matter.

**Comment by bcardiff** [comment] 2019-10-23 02:42
If the receiver is not `nil` this is equivalent to `Object#try`.

I would say that`expr.then &.m(args)` is equivalent to `expr.m(args)` and

```crystal
expr.then do |result|
   expr_using_result
end

# equivalent

result = expr
expr_using_result
```

The chaining example is a good one and since the following are all equivalent it plays nice and fit

```crystal
method_one(arg).then &.method_two.then &.method_three
method_one(arg).then(&.method_two.then(&.method_three))
method_one(arg).then(&.method_two).then(&.method_three)
```

But for that the methods will need to be in the receiver, so

```crystal
method_one(arg).method_two.method_three
```

can be used.

Maybe the people that wanted the pipe-operator will found it useful.

But unless there is some other use case for that construct I am hesitant (yet not necessarily against) to incorporate it.

**Comment by straight-shoota** [comment] 2019-10-23 08:06
Duplicate of #7188 and #5110

**Comment by ysbaddaden** [comment] 2019-10-23 20:09
The fizzbuzz example doesn't need `then`, it's merely chaining:
```crystal
[{3, "Fizz"}, {5, "Buzz"}]
  .select { |i, _| n.divisible_by? i }
  .empty? ? n.to_s : result.join &.last
```

The next example is wrong: you transform *nested* calls to *chained* calls, and actually do `method_one(arg).method_two().method_three()` that doesn't need `then`, and `then` isn't a pipe like operator.

The actual equivalent with `then` is:
```crystal
method_one(arg)
  .then { |result_one| method_two(result_one) }
  .then { |result_two| method_three(result_two) }
```

But I fail to see the benefit over mere local variables; it doesn't even spare the need to name intermediary variables:
```ruby
result_one = method_one(arg)
result_two = method_two(result_one)
method_three(result_two)
```

Unless we also implement numbered block arguments... maybe:
```ruby
method_one(arg).then { method_two(_1) }.then { method_three(_1) }
```

**Comment by tenebrousedge** [comment] 2019-10-23 20:18
@ysbaddaden your `FizzBuzz` example invokes a non-existent `result` variable. In general, I don't like to declare local variables unless they are used more than once.

**Comment by ysbaddaden** [comment] 2019-10-23 20:32
Sorry, I corrected.

**Comment by tenebrousedge** [comment] 2019-10-23 21:12
The other issues had several people who were of the opinion that using a block argument instead of a local variable was "ugly". I'd like to register disagreement with that. It's sort of the point of this construct.

The argument that `then` is very nearly the same thing as `try` is fairly persuasive. `nil` is by definition a non-useful value. If there are any cases where `then` would be more useful than `try`, then this could be a sensible construct. Nothing springs to mind. There is a slight semantic difference between the two.

**Comment by RX14** [comment] 2019-10-23 21:33
I don't think anybody is going to change their minds on this. It's not a technical argument, at the end of the day.

I'm going to close this as a duplicate of #5110, either way.

**Closed by RX14** 2019-10-23 21:33 UTC
