### ISSUE TITLE
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

### ISSUE THREAD

**Issue by luo820802** [crystal-lang/crystal#3335] opened 2016-09-21 10:51 UTC
I am running Crystal 0.19.2 on macOS Sierra and keep receiving this warning message `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0` either from the command line or from the playground. Anyone knows where is wrong?

**Comment by waj** [comment] 2016-09-21 11:10
Duplicate of #3278

**Closed by waj** 2016-09-21 11:10 UTC
Labels: duplicate
