### ISSUE TITLE
Crystal compile-time error: cannot infer type in initialize for fields assigned with function results

### ISSUE THREAD

**Issue by lgo** [crystal-lang/crystal#5653] opened 2018-01-28 23:54 UTC
In the example below, the compiler does not seem to be able to compile if `initialize` has a instance variable being assigned from an instance method result. Even though the types are declared and should not be inferred (except for `@start`). Additionally, if a class type declaration for`@start` is added the compiler seems to think that the variable is not being set during `initialize`.

```bash
$ crystal -v
Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx`Crystal
```

Bug: https://play.crystal-lang.org/#/r/3h1l
```crystal
class Test
  def initialize
    @start = self.read_start
  end

  def read_start : String
    return "a"
  end
end

t = Test.new
```

In this example, the error is as follows:

```
Error in test.cr:11: instantiating 'Test:Class#new()'

t = Test.new
         ^~~

in test.cr:3: Can't infer the type of instance variable '@start' of Test

The type of a instance variable, if not declared explicitly with
`@start : Type`, is inferred from assignments to it across
the whole program.

The assignments must look like this:

  1. `@start = 1` (or other literals), inferred to the literal's type
  2. `@start = Type.new`, type is inferred to be Type
  3. `@start = Type.method`, where `method` has a return type
     annotation, type is inferred from it
  4. `@start = arg`, with 'arg' being a method argument with a
     type restriction 'Type', type is inferred to be Type
  5. `@start = arg`, with 'arg' being a method argument with a
     default value, type is inferred using rules 1, 2 and 3 from it
  6. `@start = uninitialized Type`, type is inferred to be Type
  7. `@start = LibSome.func`, and `LibSome` is a `lib`, type
     is inferred from that fun.
  8. `LibSome.func(out @start)`, and `LibSome` is a `lib`, type
     is inferred from that fun argument.

Other assignments have no effect on its type.

Can't infer the type of instance variable '@start' of Test

    @start = self.read_start
    ^~~~~~
```

If go ahead and add `@start : String` inside the class, we get this error:
```
Error in test.cr:2: instance variable '@start' of Test was not initialized directly in all of the 'initialize' methods, rendering it nilable. Indirect initialization is not supported.

  @start : String
  ^~~~~~
```

**Comment by ysbaddaden** [comment] 2018-01-29 09:14
The list of inferences tells you that `Type.method` will be inferred if `.method` has a specified return type, but it never tells you that `instance.method` will be inferred, even if `#method` has a specified return type.

I don't know the specifics, thought.

**Comment by RX14** [comment] 2018-01-29 10:12
We can't do this because we can't tell if `read_start` will attempt to read `@start`.

**Comment by straight-shoota** [comment] 2018-01-29 12:40
@RX14 Actually, the compiler can already tell in other cases:
```crystal
class Foo
  def initialize
    not_use_foo
    @foo = 1
    use_foo
  end
  
  def not_use_foo
  end
  
  def use_foo
    pp @foo
  end
end

Foo.new
```
The above code compile fine, but if you switch the method calls `use_foo` and `not_use_foo`, it correctly triggers an compile error: `instance variable '@foo' was used before it was initialized in one of the 'initialize' methods, rendering it nilable`.

Unless I'm missing something, this should be applicable for figuring out the type of an instance variable based on the return type of an instance method.

But I guess there might be other issues as well, dunno how this would behave with subclasses overwriting the return type and such.

**Comment by caspiano** [comment] 2022-11-03 14:11
No longer reproduces in Crystal 1.6.1

https://play.crystal-lang.org/#/r/e014

**Closed by caspiano** 2022-11-03 14:11 UTC
