### ISSUE TITLE
Why does crystal produce a list with an empty string when calling .split on an empty string?

### ISSUE THREAD

**Issue by xfbs** [crystal-lang/crystal#5710] opened 2018-02-12 12:50 UTC
When I use the `.split()` function on strings, for example to split a string of words into individual words, I expect the resulting list to reflect the number of inputs. However I found that when I try to split a list with no words, I get a weird edge case where this isn't true.

```crystal
pp "three words here".split(" ").size # => 3
pp "two words".split(" ").size # => 2
pp "word".split(" ").size # => 1

# why does this return one?
pp "".split(" ").size # => 1
```

So I looked at the output and found that it returns a list with an empty string:

```crystal
pp "a b c".split(" ") # => ["a", "b", "c"]
pp "a b".split(" ") # => ["a", "b"]
pp "a".split(" ") # => ["a"]
pp "".split(" ") # => [""]
```

This is a little bit unexpected, I'm coming from ruby and it doesn't have this behaviour. So is this a bug or is this behaviour expected?

**Comment by Sija** [comment] 2018-02-12 12:56
Duplicate of #4644

**Comment by jhass** [comment] 2018-02-12 12:58
Also note #5119

Closing...

**Closed by jhass** 2018-02-12 12:58 UTC
