### ISSUE TITLE
Initializing a badly written class with named arguments may result in unsafe code when it should result in a compile-time error.

### ISSUE THREAD

**Issue by shelvacu** [crystal-lang/crystal#4917] opened 2017-09-02 08:54 UTC
```crystal
class Foo
  @a : String
  @b : String

  property a
  def initialize(
        @a,
        @b = @a,
      )
  end

  def print
    puts @a
    puts @b
  end
end

f = Foo.new a: "a"
f.print
```

This results in `Invalid memory access (signal 11) at address 0x4` at run time. Changing `Foo.new a: "a"` to `Foo.new "a"` produces the expected error at compile time: `Error: instance variable '@a' was used before it was initialized in one of the 'initialize' methods, rendering it nilable`

Version: `Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1` - Linux x86_64

**Comment by bew** [comment] 2017-09-02 09:10
Using `@b = a` instead of `@b = @a` works though:
```cr
class Foo
  @a : String
  @b : String

  def initialize(@a, @b = a)
  end

  def print
    pp @a
    pp @b
  end
end

f = Foo.new a: "a"
f.print
```
https://carc.in/#/r/2nhk

**Comment by RX14** [comment] 2017-09-02 10:56
I think this gets normalized to
```cr
def initialize(a, b = @a)
  @a = a
  @b = b
end
```

which makes it fairly clear where the segfault comes from: `b` is set to `@a` before it's initialized so printing the string will dereference a garbage pointer.

**Comment by asterite** [comment] 2017-09-02 13:14
Duplicate of #3413

**Closed** 2017-09-02 14:38 UTC
Labels: kind:bug, status:duplicate, topic:compiler
