### ISSUE TITLE
Trouble finding failure in stack trace

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#8233] opened 2019-09-25 16:20 UTC
I am upgrading a lib from an earlier version of crystal.  I am have been trying to debug this error and cannot find what the compiler is complaining about.

```bash
crystal run  test/*_test.cr -- 
Module validation failed: !dbg attachment points at wrong subprogram for function
!10 = distinct !DISubprogram(name: "initialize", linkageName: "initialize", scope: !5, file: !5, line: 115, type: !6, isLocal: true, isDefinition: true, scopeLine: 115, isOptimized: false, unit: !0, variables: !2)
i8* (%"OpenSSL::BIO"*, %TCPSocket*)* @"*OpenSSL::BIO#initialize<TCPSocket>:Pointer(Void)"
  %2 = call %"struct.LibCrypto::BioMethod"** @"~OpenSSL::BIO::CRYSTAL_BIO:read"(), !dbg !12
!12 = !DILocation(line: 13, column: 3, scope: !13)
!13 = distinct !DISubprogram(name: "set_data", linkageName: "set_data", scope: !5, file: !5, line: 13, type: !6, isLocal: true, isDefinition: true, scopeLine: 13, isOptimized: false, unit: !0, variables: !2)
!13 = distinct !DISubprogram(name: "set_data", linkageName: "set_data", scope: !5, file: !5, line: 13, type: !6, isLocal: true, isDefinition: true, scopeLine: 13, isOptimized: false, unit: !0, variables: !2)
 (Exception)
  from Crystal::CodeGenVisitor#finish:Nil
  from Crystal::Compiler#codegen<Crystal::Program, Crystal::ASTNode+, Array(Crystal::Compiler::Source), String>:(Tuple(Array(Crystal::Compiler::CompilationUnit), Array(String)) | Nil)
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run_command<Bool>:Nil
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from main
```

It seems like `!5` should be a value that I should be able to read.

**Comment by asterite** [comment] 2019-09-25 16:26
Run with `--no-debug`, problem solved. 

It's a problem with how debug info is (incorrectly) generated.

If you have a small snippet that reproduces the problem it will be helpful, otherwise we can't really help.

**Comment by wontruefree** [comment] 2019-09-25 16:32
I have been removing chunks of code but have not been able to narrow it down.  Is this a duplication of an ongoing issue?

**Comment by asterite** [comment] 2019-09-25 16:35
There's #4858

But each one is different depending on the input.

If you give me the code I can reduce it. But only in about a month.

**Comment by wontruefree** [comment] 2019-09-25 16:40
This is the code I am working on https://github.com/wontruefree/earl/

If you remove the debug flag (here)[https://github.com/wontruefree/earl/blob/master/Makefile#L13] I think you should get the same error.

It is an error surrounding SSL and I have been modify these files.
https://github.com/wontruefree/earl/blob/master/src/sock_server.cr
https://github.com/wontruefree/earl/blob/master/src/socket/ssl_server.cr

**Comment by asterite** [comment] 2019-09-25 18:36
Duplicate of #7060

**Closed by asterite** 2019-09-25 18:36 UTC
