### ISSUE TITLE
HTTP Request output with pipe occures stdout error on macOS 

### ISSUE THREAD

**Issue by decors** [crystal-lang/crystal#4320] opened 2017-04-21 04:18 UTC
Crystal: 0.21.1 and 3c71228
LLVM: 4.0.0
OS: macOS Sierra
Shell: Bash and Fish

Codes
```crystal
require "http/client"

response = HTTP::Client.get "http://www.example.com"
print response.body
```

Crystal 0.21.1
```bash
$ crystal [FILENAME] | cat
.
.
.
<body>
<div>
    <h1>Example Domain</hstdout:
```

Crystal 3c71228 
```bash
$ crystal [FILENAME] | cat
.
.
.
<body>
<div>
    <h1>Example Domain</hcat: stdout: Resource temporarily unavailable
```

No problems on CentOS 7 and Crystal 0.21.1 (install via yum repos).

**Comment by asterite** [comment] 2017-04-21 13:07
Duplicate of #2065 ?

**Comment by decors** [comment] 2017-04-24 01:49
Thanks.

Seems to same to issue #2713.
Should I close this Issue?

**Comment by asterite** [comment] 2017-05-20 16:21
Duplicate of #2065

**Closed by asterite** 2017-05-20 16:21 UTC
