### ISSUE TITLE
Can't build on ArchLinux

### ISSUE THREAD

**Issue by MrSorcus** [crystal-lang/crystal#4097] opened 2017-03-02 16:39 UTC
PKGBUILD - https://aur.archlinux.org/packages/crystal-git
```
Pending:
  Code gen: lib codegens lib var set and get
  Code gen: primitives codegens pointer of int
  Code gen: primitives sums two numbers out of an [] of Number
  Semantic: cast casts from union to incompatible union gives error
  Semantic: def overload restricts on generic type with free type arg
  Semantic: def overload restricts on generic type without type arg
  Semantic: instance var doesn't infer type to be nilable if using self.class in call in assign
  Semantic: pointer allows using pointer with subclass
  Semantic: primitives types pointer of int
  Math Functions for computing quotient and remainder
  Thread::ConditionVariable signals
  Thread::ConditionVariable broadcasts
  Thread::ConditionVariable waits and send signal

Failures:

  1) Process find_executable searches within PATH
     Failure/Error: (path = Process.find_executable("crystal")).should_not be_nil

       Expected: actual_value != nil
            got: nil

     # spec/std/process_spec.cr:234

Finished in 9:35 minutes
12102 examples, 1 failures, 0 errors, 13 pending

Failed examples:

crystal spec spec/std/process_spec.cr:230 # Process find_executable searches within PATH
make: *** [Makefile:76: spec] Error 1
==> ERROR: A failure occurred in check().
    Aborting...
```

**Comment by watzon** [comment] 2017-07-31 12:21
I can confirm that this is an issue. I’ve gotten it recently

**Comment by ysbaddaden** [comment] 2017-08-01 16:19
This is a PKGBUILD issue: no `crystal` binary can be found in `PATH`. Since the PKGBUILD must install a working crystal binary somewhere, it should alter the PATH to include that location; then the spec would pass.

**Comment by sdogruyol** [comment] 2017-09-10 17:07
Crystal 0.23.1 works on Arch and this is not an actual Crystal issue as @ysbaddaden mentioned. Let's close this :+1:

**Closed** 2017-09-10 17:09 UTC
