### ISSUE TITLE
Hash literals in puts statements are parsed differently

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#10039] opened 2020-12-05 21:53 UTC
When debugging I realized adding `puts` or `pp` in front of a nested hash breaks the parser.  There is an easy work around  to assign it to a variable and then print it or to prepend the statement with `Hash`.  But I think this is unexpected and probably a bug.

https://play.crystal-lang.org/#/r/a2bm
```crystal
puts { "varibles" => { "input" => "10.00" } }
```
```
syntax error in eval:1
Error: unexpected token: =>
```

https://play.crystal-lang.org/#/r/a2bk
```crystal
x = { "varibles" => { "input" => "10.00" } }
pp x
```

https://play.crystal-lang.org/#/r/a2bu
```crystal
puts Hash{ "varibles" => { "input" => "10.00" } }
```

**Comment by jhass** [comment] 2020-12-05 22:09
Add parenthesis 

```
puts({ "varibles" => { "input" => "10.00" } })
```
https://play.crystal-lang.org/#/r/a2bv

This is not a bug, `puts` is a method call and block syntax simply takes precedence.

**Comment by Blacksmoke16** [comment] 2020-12-05 22:41
https://github.com/crystal-lang/crystal/issues/7923#issuecomment-505412984

Add another to the list ;P

**Comment by jhass** [comment] 2020-12-06 11:18
Alright, duplicate of #1051 :P

**Closed by jhass** 2020-12-06 11:18 UTC
