### ISSUE TITLE
Bug in compiler with as?(Array)

### ISSUE THREAD

**Issue by atlantis** [crystal-lang/crystal#9342] opened 2020-05-22 22:35 UTC
Ok so this isn't causing me any actual problems, but it does say to report bugs in the compiler so here goes:

```crystal
class AllowedParams
  property raw

  def initialize()
    @raw = {} of Symbol => Array(String) | Array(Float64)	# also works if i remove either of these
  end

  def []?(k)
    @raw[k]?
  end
end

allowed_params = AllowedParams.new

#Works
#puts "#{allowed_params["param1"]?.as?(Array(String))}"

#Nice compiler message about Unhandled Exception
#puts "#{allowed_params["param1"]?.as(Array)}"

#Bug in compiler
puts "#{allowed_params["param1"]?.as?(Array)}"
```

I'm on: 

Crystal 0.34.0 (2020-04-07)
LLVM: 10.0.0
Default target: x86_64-apple-macosx

Thanks for all your work!

**Comment by oprypin** [comment] 2020-05-22 23:02
The error message for posterity
https://carc.in/#/r/94ic
```
Module validation failed: Call parameter type does not match function signature!
i32* %value
 %"Array(Float64)"*  %5 = call %String* @"*Array(Float64)@Object#to_s:String"(i32* %value), !dbg !898
Call parameter type does not match function signature!
i32* %value
 %"Array(String)"*  %7 = call %String* @"*Array(String)@Object#to_s:String"(i32* %value), !dbg !898
 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from __crystal_main
  from main
  from __libc_start_main
  from _start
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

**Comment by Blacksmoke16** [comment] 2020-05-22 23:06
Duplicate of #9249?

**Comment by asterite** [comment] 2020-06-02 13:49
> Duplicate of #9249?

No. The LLVM error message is the same, but that error message is very common.

**Comment by asterite** [comment] 2020-06-02 13:49
`as?` doesn't work as well as `as` for some reason. I personally avoid it because I now that's true. I don't know why, though.

**Comment by asterite** [comment] 2020-06-03 19:21
Reduced:

```crystal
struct Nil
  def foo
    "Nil"
  end
end

class Gen(T)
  def foo
    "foo"
  end
end

a = Gen(String).new || Gen(Int32).new
a.as?(Gen).foo
```

**Closed** 2020-06-05 12:58 UTC
Labels: kind:bug, topic:compiler
