### ISSUE TITLE
Command 'crystal docs' provides unfriendly error message

### ISSUE THREAD

**Issue by spencerking** [crystal-lang/crystal#7563] opened 2019-03-19 20:35 UTC
Version:
Crystal 0.27.2 (2019-02-05)
LLVM: 6.0.1
Default target: x86_64-apple-macosx

Running 'crystal docs' in any Crystal project (or any other directory) outputs the following error:

```while requiring "./src/**" (Exception)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::TopLevelVisitor>:Nil
  from Crystal::TopLevelVisitor#visit<Crystal::Expressions>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::TopLevelVisitor>:Nil
  from Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor)
  from Crystal::Compiler#top_level_semantic<Array(Crystal::Compiler::Source)>:Crystal::Compiler::Result
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from __crystal_main
  from main
Caused by: can't find file './src/**' relative to '.' (Crystal::CrystalPath::Error)
  from Crystal::Program#find_in_path<String, (String | Nil)>:Array(String)
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::TopLevelVisitor>:Nil
  from Crystal::TopLevelVisitor#visit<Crystal::Expressions>:Bool
  from Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::TopLevelVisitor>:Nil
  from Crystal::Program#top_level_semantic<Crystal::ASTNode+>:Tuple(Crystal::ASTNode+, Crystal::TypeDeclarationProcessor)
  from Crystal::Compiler#top_level_semantic<Array(Crystal::Compiler::Source)>:Crystal::Compiler::Result
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from __crystal_main
  from main
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues```

**Comment by asterite** [comment] 2019-03-19 20:49
Duplicate of #7385 , fixed in #7386

**Closed by asterite** 2019-03-19 20:49 UTC
