### ISSUE TITLE
Can't build 'release' binary

### ISSUE THREAD

**Issue by pepa65** [crystal-lang/crystal#4827] opened 2017-08-13 15:30 UTC
To reproduce:
* install *crystal* on a fresh Ubuntu install (I use 16.04) according to [the official recipe](https://crystal-lang.org/docs/installation/on_debian_and_ubuntu.html) At this point it's **Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1**
* `echo 'puts "Hello World!"' >hw.cr`
* `crystal build --release hw.cr`
```
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102: 13365 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

I would love to try *crystal*. I am sure there must be something missing in the toolchain somehow. I've browsed around similar issues here, and there is obviously a problem, but I haven't encountered a fix.

**Comment by RX14** [comment] 2017-08-13 15:48
Duplicate of #4719, please search before making an issue.

**Closed by RX14** 2017-08-13 15:48 UTC

**Comment by pepa65** [comment] 2017-08-13 15:52
I hadn't seen that one, that is pretty identical to this issue. So there is no resolution or fix for this??

**Comment by RX14** [comment] 2017-08-13 16:05
Not currently, no. There's a workaround: don't build with release, and use `--no-debug`.

**Comment by straight-shoota** [comment] 2017-08-13 21:57
@RX14 You can build with `--release --no-debug`.

**Comment by pepa65** [comment] 2017-08-14 01:34
The next exercise in the tutorial is compiling the simple webserver, which doesn't work, but that should probably be a new issue.
