### ISSUE TITLE
`Random::Secure#next_u` is broken on OpenBSD and NetBSD

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#10847] opened 2021-06-24 10:44 UTC
https://github.com/crystal-lang/crystal/pull/10585 added a type restriction `Random::Secure#next_u : UInt8`. But the underlying arc4random implementation of `Crystal::System::Random#next_u` used on OpenBSD and NetBSD returns `UInt32`.

The documentation for the internal method `Crystal::System::Random#next_u` states:
> Implementations may choose the integer size to return based on what the system source provides. They may choose to return a single byte (UInt8) in which case `::Random` will prefer `#random_bytes` to read as many bytes as required at once, avoiding multiple reads or reading too many bytes.

I think it makes sense to use wider integer types internally if the implementation provides that.

The question is if and how to expose that in the public API. Having `Random::Secure#next_u` return different types based on platform is not ideal. At the very least, we could widen the return type restriction to `UInt8 | UInt32` (or `Int::Unsigned`). That helps for documentation (and makes it compile again). But it doesn't force users to take care of `UInt32` until they actually build for an OpenBSD or NetBSD target.

I was wondering if we could just force the compiler to a union type like this:

```cr
  def next_u : Int::Unsigned
    Crystal::System::Random.next_u || 0_u8 || 0_u32
  end
```

But that breaks all the `sizeof(typeof(next_u))` and similar use cases in many `Random` methods. It can probably be worked around if we want to go with this. But it needs some careful refactoring.

**Comment by Sija** [comment] 2021-06-24 10:52
@straight-shoota Again, this shouldn't be qualified as a _regression_ since the PR in question wasn't shipped in any release, yet.

**Comment by asterite** [comment] 2021-06-24 11:13
To me, a regression is something that was working and something happened and it's not working anymore. If this isn't fixed, it will be a real regression. So, yes, this is a regression.

Does the implementation check for UInt8 or UInt32? Otherwise, why not always return UInt32?

**Comment by asterite** [comment] 2021-06-24 11:14
Why not remove the type restriction altogether?

**Comment by asterite** [comment] 2021-06-24 11:15
I think the main method which all randoms should rely on is a method that fills a buffer of bytes with random bytes.

**Comment by straight-shoota** [comment] 2021-06-24 13:48
> why not always return UInt32?

All other implementations except arc4random return `UInt8`. If we just cast to `UInt32`, it would have 3 bytes with 0 entropy. If we fill it with multiple calls to the source, it would use the purpose of being a minimal unit of randomness.

> Why not remove the type restriction altogether?

Yes, we can do that. And we'll probably have to do that at least short term for 1.1. But whether there's a type restriction or nor, doesn't change that there are different return types per platform. And the goal was to avoid that to have portable stdlib APIs.

**Comment by asterite** [comment] 2021-06-24 14:08
This is the definition of arc4random:

```crystal
module Crystal::System::Random
  # Fills *buffer* with random bytes using arc4random.
  def self.random_bytes(buffer : Bytes) : Nil
    LibC.arc4random_buf(buffer.to_unsafe.as(Void*), buffer.size)
  end

  def self.next_u : UInt32
    LibC.arc4random
  end
end
```

What I'm proposing is to do this:

```crystal
module Crystal::System::Random
  # Fills *buffer* with random bytes using arc4random.
  def self.random_bytes(buffer : Bytes) : Nil
    LibC.arc4random_buf(buffer.to_unsafe.as(Void*), buffer.size)
  end

  def self.next_u : UInt8
    byte = uninitialized UInt8
    LibC.arc4random_buf(pointerof(byte).as(Void*), 1)
    byte
  end
end
```

Then all implementations return `UInt8` and everything is consistent.

What do you think?

Maybe `arc4random_buf` is slower than the current approach? No idea (I can't test it)

**Comment by straight-shoota** [comment] 2021-06-24 14:19
Yeah, that should essentially have the same result as `LibC.arc4random.to_u8!`. And avoids a potential performance impact at this point.

That's easy to do. But it creates a bigger problem: it we let `Random#next_u` always return `UInt8`, that invalidates a lot of assumptions about that method in other places. The `Random` documentation explicitly states that it can return any type. And implementations using that method (such as `Random#rand_it`) make use of that (I assume for performance reasons).

So if we want to unify on `UInt8`, we also need to look at places where this method is used.

In the end, we should probably consider making `Random#random_bytes` be an abstract method that needs to be implemented by inheriting types. That means, they can effectively choose to use a single value type if the byte slice is small.
I think this is ultimately a much better design because it reduces the interface to a single method (instead of two) and delegates the choice for an efficient strategy entirely to the implementation.

**Comment by asterite** [comment] 2021-06-24 14:29
So I guess for now, for compatibility reasons, we can't do anything and we should just revert the annotation?

**Comment by straight-shoota** [comment] 2021-06-24 14:42
It would appear so, yes.

However, I could see a way to introduce a change to at least the stdlib implementations and any 3rd party implementation that wants to follow the new API, yet keep it backwards-compatible with the older API. That would be after 1.1 though.

**Comment by oprypin** [comment] 2021-06-24 16:36
Indeed please just revert the annotation. Sorry for my mistake.

@Sija Thanks for pointing out that this is not a regression.

On a very related matter, I am certain that the fix for this must not make it into the release notes. Because if it appears there as a "regression fix", that'd be worse than useless.

**Comment by straight-shoota** [comment] 2021-06-24 16:46
Okay, so I've created #10849 to revert that type restriction.

I'll initiate a separate discussion about refactoring the `Random` API later.

**Closed** 2021-06-25 17:49 UTC
Labels: kind:bug, kind:regression, platform, topic:stdlib:crypto

**Comment by straight-shoota** [comment] 2021-06-25 17:56
> the fix for this must not make it into the release notes. Because if it appears there as a "regression fix", that'd be worse than useless.

Definitely. It's only a regression with respect to the current development branch. The `[Revert]` prefix in the PR title should make it clear that this is not supposed to be in the changelog, because it just nullifies a previous change (partially).

**Comment by Sija** [comment] 2021-06-25 20:16
@straight-shoota IMO Identifying it (via label) as a regression makes it harder to compile changelog with respect to those. I might be wrong, just a thought.
