### ISSUE TITLE
abstract + Serializable + useless property = Invalid memory access

### ISSUE THREAD

**Issue by 636f7374** [crystal-lang/crystal#10541] opened 2021-03-23 23:41 UTC
# Summary

* This bug was accidentally triggered during testing.
* abstract + Serializable + useless property = Invalid memory access.
* Maybe there should be a better title. 
  * (But I don’t know how to describe it better).

## Example

```crystal
require "json"

abstract struct Frames
  include JSON::Serializable

  property frameType : String
end

abstract struct Frames
  struct Assign < Frames
    property createdAt : Time

    def initialize
      @createdAt = Time.local
      @stepType = "assign"
    end
  end
end

assign = Frames::Assign.new
```

## Verbose

```text
Invalid memory access (signal 11) at address 0xc
[0x108a46abb] *Exception::CallStack::print_backtrace:(Int32 | Nil) +107
[0x108a18ce4] __crystal_sigfault_handler +292
[0x7fff71ce25fd] _sigtramp +29
[0x108a5036a] *Pointer(UInt8)@Pointer(T)#[]<Int32>:UInt8 +10
[0x108a4ebbe] *Char::Reader#byte_at<Int32>:UInt32 +30
[0x108a4da74] *Char::Reader#decode_current_char:Char +36
[0x108a4da47] *Char::Reader#initialize<String, Int32>:Char +87
[0x108a4d9e7] *Char::Reader#initialize<String>:Char +39
[0x108a4d966] *Char::Reader::new<String>:Char::Reader +102
[0x108a2cbb4] *String#inspect<String::Builder>:Nil +84
[0x108b41f4a] *Frames::Assign@Struct#inspect<String::Builder>:Nil +90
[0x108b41ed2] *Frames::Assign@Object#inspect:String +66
[0x108b2862a] *Crystal::Playground::Agent#to_value<Frames::Assign>:String +74
[0x108b285a8] *Crystal::Playground::Agent#safe_to_value<Frames::Assign>:String +104
[0x108a04cd0] __crystal_main +2064
[0x108b4c0c4] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +36
[0x108b4bf3b] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +43
[0x108a105f9] main +9

exit status: 11
```

## Version

```text
$ crystal -v
Crystal 1.0.0 (2021-03-22)

LLVM: 9.0.1
Default target: x86_64-apple-macosx

$ uname -a
Darwin iMac.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by asterite** [comment] 2021-03-23 23:55
Duplicate of #9775

**Closed by asterite** 2021-03-23 23:55 UTC
Labels: kind:bug, status:duplicate
