### ISSUE TITLE
Compile Error: must be Array(NamedTuple(name: Symbol, type: TestBase.class)), not Array(NamedTuple(name: Symbol, type: TestA.class))

### ISSUE THREAD

**Issue by syalon** [crystal-lang/crystal#11341] opened 2021-10-20 07:26 UTC
Error: instance variable '@fields' of TestExt must be Array(NamedTuple(name: Symbol, type: TestBase.class)), not Array(NamedTuple(name: Symbol, type: TestA.class))
```
class TestBase
end

class TestA < TestBase
end

class TestExt < TestBase
  def initialize(@fields : Array(NamedTuple(name: Symbol, type: TestBase.class)))
  end
end

pp TestExt.new([{name: :test_name, type: TestA}])
```

But the code below to remove Array compiles normally.
```
class TestBase
end

class TestA < TestBase
end

class TestExt < TestBase
  def initialize(@fields : NamedTuple(name: Symbol, type: TestBase.class))
  end
end

pp TestExt.new({name: :test_name, type: TestA})
```

**Comment by asterite** [comment] 2021-10-20 13:18
Duplicate of https://github.com/crystal-lang/crystal/issues/3803

**Closed by asterite** 2021-10-20 13:18 UTC
Labels: kind:question, topic:lang:type-system
