### ISSUE TITLE
HTTP::Client is failing on some urls

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#6352] opened 2018-07-07 20:34 UTC
Using "HTTP::Client" seems to fail on some urls for me.

```crystal
require "http/client"
HTTP::Client.get("https://www.google.com") # => works
HTTP::Client.get("https://www.facebook.com") # => Unhandled exception: Invalid encoding: "utf-8" (ArgumentError)
```

I have tried a variety of Accept headers and other clients including curl and ruby.
Am I missing something in setting up the web request or is there an unknown UTF-8 character here?

**Comment by asterite** [comment] 2018-07-07 20:48
Duplicate of https://github.com/crystal-lang/crystal/issues/6353

**Closed** 2018-07-08 06:59 UTC
