### ISSUE TITLE
Type decuction for subtypes in class templates

### ISSUE THREAD

**Issue by HOMODELUNA** [crystal-lang/crystal#12234] opened 2022-07-09 17:19 UTC
## Type decuction for type-parameters in generic class
Nowadays, A variant can be constructed from either of its member types.
```crystal
alias Entry = String | Symbol
e : Entry 
e = "case" #ok
e = :expr  #ok
```
however, when it comes to a generic class, things will be somehow problematic.
```crystal
alias Pattern = Array(String | Symbol)

if_else : Pattern = ["if" , :expr , "then" ,:expr,"else", :expr] #ok
puts "if_else= #{if_else.inspect}" #=>  if_else= ["if", :expr, "then", :expr, "else", :expr]


# empty_yield  : Pattern = ["do" , "yield","end"] 
# Error: type must be Array(String | Symbol), not Array(String)
```
Literal works,but it's not what I expect: 
```
#this is legal
empty_yield = Pattern{"do","yield","end"}
```
Our type system is clever enough to discover that `String` isn't equal to `String | Symbol`,thus `Array(String) is not equal to `Array(String | Symbol)`.However , `String | Symbol`  constructable from `String`. Therefore, I expect that there is an auto conversion from the stronger type to the weaker type, that is:

**For a generic `G(T,U, ...)`,and `G(T1,U1, ...)`, if `T` is constructable from `T1` , and `U` is constructable from `U1` (and so on),then `G(T,U, ...)`should be constructable from `G(T1,U1, ...)`.**

```
    G(T1,U1, ...) ==> G(T,U, ...)
        ↑                ↑
      T1,U1, ...  ==>   T,U, ...  
```
One example is the above one. And, generally, `Array(String | Symbol | MyClass)` should be constructable from either `Array(String)`, `Array(Symbol)`, `Array(MyClass)` or thier combinations, such as `Array(String | MyClass)` (because the variant provided is included by the variant required).

This is a rough idea, because these subclasses may have some inner correlations(for example, `T` is a subclass of `U`),if so maybe we should make more restrictions from these classes, for which we need something like interface(Java), concept(C++), or trait(Rust) to **specify the behavior of classes**. Now we already have modules and abstract classes, but they are not powerful enough for this work. 

Our compilers often runs into problems when a class referred by a function doesn't have a method and therefore the whole function can't be implemented. In this case, it throws an error from the depth of layers of layers of function call stack. These redundant work can be prevented if the compiler found the class imcompatible for the restriction, and quit trying to struggle finishing the function.

### About opening a completed class

The *completed class* means a generic with all its type parameters filled in.

Back to the first problem. Firstly I tried to open the class Array(String | Symbol) and overload the method `#initialize` with argument `Array(String)`,but I can't do it, because `Array` is an generic class.
```crystal
alias Pattern =Array( String | Symbol)
#Error: Pattern is not a class, it's a generic class
class Pattern 
  def initialize( arr : Array(String) )
    arr.map{ |e| e.as(T) }
  end
end
```
I think although `Array` is generic, `Array(String|Symbol)` should not,because there's nothing uncertain for the class.

### About using restraints
Also, if I can directly overload methods in a generic(with a little restraints), things will be much easier:
```crystal
class Array(T)
  #maybe we can utilize annotations, or we create a new grammar for this
  @[assert T.constructible_from?(U)]
  def initialize(arr : Array(U))
    #...
  end
end
```

**Comment by HertzDevil** [comment] 2022-07-09 17:45
The only covariant containers in the language are `Tuple` and `NamedTuple`, so `Tuple(T) <= Tuple(U)` whenever `T <= U`. This is unlikely to change because `Pointer` needs to be invariant if we want to do the same for most other containers, and that is far from trivial.

The second case is a duplicate of #3298.

The last case can be done by #11908:

```crystal
class Array(T)
  def self.new(arr : Array(U)) forall U <= T
    arr.map &.as(T)
  end
end
```

Related: #3803

**Comment by straight-shoota** [comment] 2022-07-09 21:54
Yeah, I think the topics presented here are already covered in existing issues. Let's continue the specific discussion there.

**Closed by straight-shoota** 2022-07-09 21:54 UTC
Labels: status:discussion, topic:compiler:generics
