### ISSUE TITLE
Crash when compiling lots of files

### ISSUE THREAD

**Issue by miketheman** [crystal-lang/crystal#2332] opened 2016-03-20 12:32 UTC
Hi there!

I've tried a few times over the past month or so to "get started" on OSX, with either running the compiler, testing the stdlib - both have never passed, making the experience somewhat frustrating.

In attempts to try and understand how to do this, I read through the Contributing.md docs, then followed a link to the wiki for the required libraries, then read through some of the open/closed issues with compiling, llvm versions, etc.

When attempting to "do the minimum" - checkout code, run `make libcrystal` and test the build - I get:

``` shellsession
$ bin/crystal spec/all_spec.cr
Invalid memory access (signal 11) at address 0x10000001f
[4387032720] __crystal_sigfault_handler +64
[140735500416298] _sigtramp +26
[4390894111] *Process#initialize<Process, String, Array(String), Nil, Bool, Bool, Bool, Bool, Bool, Nil>:Nil +1039
[4390892173] *Crystal::Compiler#system<Crystal::Compiler, String, Array(String)>:Nil +221
[4390874442] *Crystal::Compiler#codegen<Crystal::Compiler, Array(Crystal::Compiler::CompilationUnit), String, String>:Nil +5594
[4389349342] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +19054
[4393915537] *Crystal::Command#run_command<Crystal::Command>:Nil +145
[4393732497] *Crystal::Command#run<Crystal::Command>:(Nil | Bool | Array(Crystal::ImplementationTrace) | Array(String) | IO::FileDescriptor+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +9233
[4387026097] __crystal_main +23905
[4393722123] main +43
Error: execution of command failed with code: 11: `cc -o "/Users/miketheman/Dropbox/code/github/miketheman/crystal/.crystal/crystal-run-all_spec.tmp" "${@}"  -rdynamic  -lxml2 -lreadline -lgmp -lyaml -lz -lssl -lcrypto /Users/miketheman/Dropbox/code/github/miketheman/crystal/src/llvm/ext/llvm_ext.o `(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)` -lstdc++ /Users/miketheman/Dropbox/code/github/miketheman/crystal/src/ext/libcrystal.a -levent -lpcre -liconv -lgc -lpthread -ldl`
```

This uses llvm 3.6.2 from Homebrew, as suggested in the wiki. Switching to llvm 3.5.1 produces the same error.

Looking at [travis builds, I can see that llvm 3.5.0 is installed and used](https://travis-ci.org/crystal-lang/crystal/jobs/117203640#L2535), and following similar steps, I still get failures:

``` shellsession
$ ./bin/crystal build  -o .build/all_spec spec/all_spec.cr
Using compiled compiler at .build/crystal
Error: execution of command failed with code: 127: `cc -o ".build/all_spec" "${@}"  -rdynamic  -lxml2 -lreadline -lgmp -lyaml -lz -lssl -lcrypto /Users/miketheman/Dropbox/code/github/miketheman/crystal/src/llvm/ext/llvm_ext.o `(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)` -lstdc++ /Users/miketheman/Dropbox/code/github/miketheman/crystal/src/ext/libcrystal.a -levent -lpcre -liconv -lgc -lpthread -ldl`
```
- Do I need to match llvm 3.5.0 explicitly?
- Is there some other problem in my setup?
- What else can I look for to help debug and get this going?

**Comment by asterite** [comment] 2016-03-20 12:41
I was able to reproduce it. The problem seems to happen when you are inside a long path, like in your case:

```
/Users/miketheman/Dropbox/code/github/miketheman/crystal
```

(I also wouldn't advise coding in the Dropbox folder, because the compiler generates lots of temporary files and they will (maybe?) be synchronized by Dropbox)

Can you try compiling in a less deep directory?

**Comment by asterite** [comment] 2016-03-20 13:39
I improved the issue a bit in the above commit. I'll still leave this open because it will happen again once we add lots more files, or if you have a huge project (it'll have to be bigger than the compiler and the standard library).

**Comment by miketheman** [comment] 2016-03-20 14:30
Awesome! I'm glad I'm not the only person seeing this, and during the time @asterite went and committed a fix above, I went on a bug-hunt, notes here.

The Dropbox location has typically been fine for other projects - I even disabled the running process for the purpose of debugging this further. Here we go!

# Shorter path
Per recommendation, I cloned to a fresh, shorter path.
Even with a shorter path, I get a failure, this time, an error on `llvm_ext.o`:
```shellsession
$ make clean libcrystal && bin/crystal spec/all_spec.cr
rm -rf .build
rm -rf ./doc
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
cc -fPIC   -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
clang: error: no such file or directory: '/Users/miketheman/tmp/crystal/src/llvm/ext/llvm_ext.o'
Error: execution of command failed with code: 1: `cc -o "/Users/miketheman/tmp/crystal/.crystal/crystal-run-all_spec.tmp" "${@}"  -rdynamic  -lxml2 -lreadline -lgmp -lyaml -lz -lssl -lcrypto /Users/miketheman/tmp/crystal/src/llvm/ext/llvm_ext.o `(llvm-config-3.6 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config-3.5 --libs --system-libs --ldflags 2> /dev/null) || (llvm-config --libs --system-libs --ldflags 2>/dev/null)` -lstdc++ /Users/miketheman/tmp/crystal/src/ext/libcrystal.a -levent -lpcre -liconv -lgc -lpthread -ldl`
```

So it appears that to even run specs for stdlib from the docs, I need to compile the compiler itself for the llvm_ext.o file? (The docs might be wrong for stdlib hacking).
```
$ make crystal && bin/crystal spec/all_spec.cr
c++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/local/bin/llvm-config-3.5 --cxxflags`
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr
Using compiled compiler at .build/crystal
................................. <snip>
```
Nope - only the `llvm_ext` job needs to be run to have llvm_ext.so.

## Shorter path, working
Here's the invocation that appears to work on the shorter path:
```shellsession
$ make clean llvm_ext libcrystal && bin/crystal spec/all_spec.cr
rm -rf .build
rm -rf ./doc
rm -rf src/llvm/ext/llvm_ext.o
rm -rf src/ext/sigfault.o src/ext/libcrystal.a
c++ -c -o src/llvm/ext/llvm_ext.o src/llvm/ext/llvm_ext.cc `/usr/local/bin/llvm-config-3.5 --cxxflags`
cc -fPIC   -c -o src/ext/sigfault.o src/ext/sigfault.c
ar -rcs src/ext/libcrystal.a src/ext/sigfault.o
........................................................<snip>
```

So a shorter path seems to solve the immediate problem.

# Deep path

In my Dropbox (deep) path, on `master`, running `make clean llvm_ext libcrystal && bin/crystal spec/std/<some specific spec>` typically results in a successful run.

But running the `spec/all_spec.cr` results in failure (per the original report).

I ran a bisect from 0.13.0 tag, and it reports:
```
52fde0c2c2e16f9130a604a54a63292cea52f6e5 is the first bad commit
commit 52fde0c2c2e16f9130a604a54a63292cea52f6e5
Author: Ary Borenszweig <aborenszweig@manas.com.ar>
Date:   Thu Mar 10 17:45:57 2016 -0300

    More type annotations

:040000 040000 558e80dba9b7903ad6b9f198dfea52f4b99ebb0f 7317c416113641a10b7b24b50bdf5493a7fe61d3 M	spec
:040000 040000 f8e7f2efc091dd0d752b30195d75c0ed8fc5a0e3 fbab92628fcb116dc1c7cea45806fc30b0cbee2d M	src
```

I don't really understand how adding more type annotations would make the spec test suite longer, especially since the commit in question only adds more annotations, not more specs themselves.

### Bisect notes
```shell
git bisect start
git bisect bad # from current master
git bisect good 60777f31ea84f8fd627bfec448ac86bd6221c161 # 0.13.0 tag
git bisect run sh -c 'make clean llvm_ext libcrystal && bin/crystal spec/all_spec.cr'
```

Two passes produced the same results for the Deep path test.

First bisect approach did not include recompiling the compiler, so may have included false-positive failures when the compiler & specs change together. A second, using:
```shell
git bisect run sh -c 'make clean crystal && bin/crystal spec/all_spec.cr'
```
produces the same result (failure on the 52fde0c2c2e16f9130a604a54a63292cea52f6e5 commit), confirming the original test result.

# Conclusions

- 52fde0c2c2e16f9130a604a54a63292cea52f6e5 introduced "something" that makes testing all specs fail on deep paths. I don't understand how or why yet.
- docs (or makefile deps) for stdlib-only work should handle the `llvm_ext` dependency
- a target of stdlib-only specs should exist - something like `bin/crystal spec/std/all_spec.cr`
- `git bisect` is pretty awesome
- 51f63e816151b3fa8a3f5842b539586a41fb5e1c appears to resolve the immediate problem of "deep path" testing
- `make clean llvm_ext libcrystal && bin/crystal spec/all_spec.cr` continues to fail, even on master, showing that in order to run all_specs.cr, `make crystal` needs to be run.

**Comment by asterite** [comment] 2016-03-20 15:11
I think more types are created after that commit because some variables are annotated with `IO`. Before that, no variable could have a type `IO` because when a union of several IOs is created they stay as a union. Only when you assign one or many IO types to a variable with type `IO` then it will have `IO` as a type. Kind of hard to explain without knowing how the compiler does things.

In the contributing section to contribute to the compiler we could probably mention that `make deps` is needed, although `make crystal` already takes care of that.

**Comment by asterite** [comment] 2017-09-26 18:36
I'll close this as this didn't happen anymore. If some day it happens again, we'll think of a solution.

**Closed by asterite** 2017-09-26 18:36 UTC
Labels: kind:bug, topic:compiler
