### ISSUE TITLE
Int#bits does not except range with negative one

### ISSUE THREAD

**Issue by jkthorne** [crystal-lang/crystal#12878] opened 2022-12-29 06:50 UTC
bits does not accept a range like other enumerable features.  
For example [this code](
https://play.crystal-lang.org/#/r/eamp) returns and `IndexError`
```crystal
Int32::MAX.bits(0..-1)
```

**Comment by HertzDevil** [comment] 2022-12-29 07:17
Duplicate of #11401

**Closed** 2022-12-29 07:18 UTC
Labels: kind:bug
