### ISSUE TITLE
Compiler crash when using `-d` (debug) flag

### ISSUE THREAD

**Issue by waghanza** [crystal-lang/crystal#2782] opened 2016-06-08 20:10 UTC
Hi,

I'm trying to create a REST-like API in `crystal`.
On compilation, with **--debug** flag, I have 

``` crystal
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

I have created a gist with debug output => https://gist.github.com/138698f5a44a6a221786f20d0a27b0d3

My code is here => https://github.com/waghanza/forest/blob/master/src/forest.cr
- Dist => `fedora 24`
- Arch => `amd64`
- `PATH` => /opt/crystal/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
- **Version** => `Crystal 0.17.4 [032ab91] (2016-05-26)`

PS : Without debug i can **compile**, but I have

``` crystal
./forest: symbol lookup error: ./forest: undefined symbol: GC_push_all_eager
```

**Comment by jhass** [comment] 2016-06-08 21:04
The latter is sort of a setup issue, you should be able to workaround it by setting `LIBRARY_PATH` to `/opt/crystal/embedded/lib`.

**Comment by jhass** [comment] 2016-06-08 21:09
Here's the full stack, kemal and crystal-pg need some little fixes to compile on HEAD. This is with LLVM 3.6.
```
Bug: called llvm_struct_type for (PQ::Frame::ErrorResponse | PQ::Frame::NoticeResponse)
[10923671] *CallStack::unwind:Array(Pointer(Void)) +87
[10923562] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +10
[10923514] *CallStack::new:CallStack +42
[10773192] *raise<Exception>:NoReturn +24
[10773166] ???
[26242786] ???
[26238631] ???
[25921890] *Crystal::CodeGenVisitor +50
[25918012] *Crystal::CodeGenVisitor#create_debug_type<Crystal::CodeGenVisitor, (Crystal::GenericClassInstanceType+ | Crystal::MetaclassType | Crystal::NonGenericClassType
+ | Crystal::VirtualType)>:Pointer(Void) +156
[25915892] *Crystal::CodeGenVisitor#get_debug_type<Crystal::CodeGenVisitor, Crystal::Type+>:LibLLVMExt::Metadata? +516
[26012931] *Crystal::CodeGenVisitor#declare_variable<Crystal::CodeGenVisitor, String, Crystal::Type+, LLVM::Value, Crystal::Def+>:LLVM::Value? +131
[26003042] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2402
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[16252338] *Crystal::Call +50
[26107485] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::Call>:Nil +29
[26107196] *Crystal::CodeGenVisitor#codegen_dispatch<Crystal::CodeGenVisitor, Crystal::Call, Array(Crystal::Def+)>:Bool +4780
[26101243] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +299
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26054162] *Crystal::CodeGenVisitor#codegen_if_branch<Crystal::CodeGenVisitor, Crystal::CodeGenVisitor::Phi, Crystal::ASTNode+, LLVM::BasicBlock, Bool>:LLVM::Value? +82
[26049841] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::If>:Bool +449
[12579590] *Crystal::ASTNode+ +3350
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +34
4
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26003294] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +2654
[26018401] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+>:LLVM::Function +113
[26017428] *Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +388
[26135608] *Crystal::CodeGenVisitor#codegen_call<Crystal::CodeGenVisitor, Crystal::Call, Crystal::Def+, Crystal::Type+, Array(LLVM::Value)>:(Bool | LLVM::Value | Nil) +344
[26101602] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +658
[12581814] *Crystal::ASTNode+ +5574
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26022300] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:Bool? +844
[12580093] *Crystal::ASTNode+ +3853
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[12578022] *Crystal::ASTNode+ +1782
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26020955] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::ModuleDef>:Bool +43
[12578316] *Crystal::ASTNode+ +2076
[25959997] *Crystal::CodeGenVisitor#accept<Crystal::CodeGenVisitor, Crystal::ASTNode+>:Nil +29
[26018848] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +288
[15582994] *Crystal::Expressions +50
[12962988] *Crystal::Program#codegen<Crystal::Program, Crystal::Expressions, (Array(String) | Bool | String | Nil), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +124
[12962854] *Crystal::Program#codegen:debug:single_module:expose_crystal_main<Crystal::Program, Crystal::Expressions, Bool, (Array(String) | Bool | String | Nil), Bool>:Hash(String, LLVM::Module) +118
[22392928] *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:Array(String)? +1600
[22386807] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +183
[22403588] *Crystal::Command::CompilerConfig#compile<Crystal::Command::CompilerConfig, String>:Crystal::Compiler::Result +100
[11891676] *Crystal::Command#run_command<Crystal::Command, Bool>:Nil +476
[11878256] *Crystal::Command#run<Crystal::Command>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +1408
[11876508] *Crystal::Command::run<Array(String)>:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +44
[11876378] *Crystal::Command::run:(Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class) | Array(String) | Bool | Crystal::Compiler::Result | Hash(String, String) | IO::FileDescriptor+ | Nil) +42
[10731375] ???
[10799716] main +52
[139669673379649] __libc_start_main +241
[10727737] _start +41
[0] ???
```

**Comment by jhass** [comment] 2016-06-08 21:09
Related to #1614

**Comment by asterite** [comment] 2016-06-08 21:48
I think duplicate of #1321, `-d` or `--debug` is basically incomplete, so broken.

**Comment by jhass** [comment] 2016-06-08 21:50
Still seeing this with `--single-module`

**Comment by asterite** [comment] 2016-12-13 11:35
The original code seems to be gone, so there's no way to reproduce this anymore. Closing...

**Closed by asterite** 2016-12-13 11:35 UTC
Labels: bug, debugger
