### ISSUE TITLE
no overload matches 'Socket::Addrinfo.resolve'

### ISSUE THREAD

**Issue by tleydxdy** [crystal-lang/crystal#10965] opened 2021-07-19 18:31 UTC
When rebuilding my code with the updated crystal 1.1.0 it pops up with this error, which seems to be from the socket library itself. I'm using the debain repo from obs

```
In /usr/share/crystal/src/socket/addrinfo.cr:192:7

 192 | resolve(domain, service, family, Type::STREAM, Protocol::TCP) { |addrinfo| yield addrinfo }
       ^------
Error: no overload matches 'Socket::Addrinfo.resolve' with types Int32, Socket::Family, Bool, Socket::Type, Socket::Protocol

Overloads are:
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil)
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil, &block)
 ```

**Comment by asterite** [comment] 2021-07-19 18:44
What was the previous version you were using? It seems the code didn't compile either before, `family` is Bool in your code but it should be `Family` or `Nil`

**Comment by tleydxdy** [comment] 2021-07-19 20:23
it works fine with 1.0.0, I guess it was something in our code afterall. I tried to look into the changelogs/issues see if there was anything seemingly related :(
https://github.com/iv-org/invidious/issues/2256

**Comment by straight-shoota** [comment] 2021-07-19 21:52
It looks like the custom `TCPSocket#initialize` somehow method overrides the initializer receiving a file descriptor. 
I don't know why, though.

https://github.com/iv-org/invidious/blob/0d57a887ea59b6111d9a19b1ea1cea619ad9f129/src/invidious/helpers/helpers.cr#L763-L773

Adding proper type restrictions to the parameters should probably fix this.

**Comment by straight-shoota** [comment] 2021-07-19 22:13
From the error trace it seems this is what's happening:

<details>
<summary>Error Trace</summary>

```
In src/invidious.cr:37:22

 37 | PG_DB           = DB.open CONFIG.database_url
                           ^---
Error: instantiating 'DB:Module#open(URI)'


In lib/db/src/db.cr:119:5

 119 | build_database(uri)
       ^-------------
Error: instantiating 'build_database(URI)'


In lib/db/src/db.cr:155:14

 155 | Database.new(build_driver(uri), uri)
                ^--
Error: instantiating 'DB::Database.class#new(DB::Driver+, URI)'


In lib/db/src/db/database.cr:57:24

 57 | conn = @driver.build_connection(self).as(Connection)
                     ^---------------
Error: instantiating 'DB::Driver+#build_connection(DB::Database)'


In lib/pg/src/pg/driver.cr:3:16

 3 | Connection.new(context)
                ^--
Error: instantiating 'PG::Connection.class#new(DB::Database)'


In lib/pg/src/pg/connection.cr:13:38

 13 | @connection = PQ::Connection.new(conn_info)
                                   ^--
Error: instantiating 'PQ::Connection.class#new(PQ::ConnInfo)'


In lib/pg/src/pq/connection.cr:30:27

 30 | soc = TCPSocket.new(@conninfo.host, @conninfo.port)
                      ^--
Error: instantiating 'TCPSocket.class#new(String, Int32)'


In src/invidious/helpers/helpers.cr:764:3

 764 | def initialize(host, port, dns_timeout = nil, connect_timeout = nil, family = Socket::Family::UNSPEC)
       ^---------
Error: instantiating 'initialize(String, Int32, Nil, Nil, Socket::Family)'


In src/invidious/helpers/helpers.cr:765:14

 765 | Addrinfo.tcp(host, port, timeout: dns_timeout, family: family) do |addrinfo|
                ^--
Error: instantiating 'Socket::Addrinfo.class#tcp(String, Int32)'


In /usr/share/crystal/src/socket/addrinfo.cr:192:7

 192 | resolve(domain, service, family, Type::STREAM, Protocol::TCP) { |addrinfo| yield addrinfo }
       ^------
Error: instantiating 'resolve(String, Int32, Socket::Family, Socket::Type, Socket::Protocol)'


In /usr/share/crystal/src/socket/addrinfo.cr:60:7

 60 | getaddrinfo(domain, service, family, type, protocol, timeout) do |addrinfo|
      ^----------
Error: instantiating 'getaddrinfo(String, Int32, Socket::Family, Socket::Type, Socket::Protocol, Nil)'


In /usr/share/crystal/src/socket/addrinfo.cr:60:7

 60 | getaddrinfo(domain, service, family, type, protocol, timeout) do |addrinfo|
      ^----------
Error: instantiating 'getaddrinfo(String, Int32, Socket::Family, Socket::Type, Socket::Protocol, Nil)'


In /usr/share/crystal/src/socket/addrinfo.cr:63:9

 63 | loop do
      ^---
Error: instantiating 'loop()'


In /usr/share/crystal/src/socket/addrinfo.cr:63:9

 63 | loop do
      ^---
Error: instantiating 'loop()'


In /usr/share/crystal/src/socket/addrinfo.cr:192:7

 192 | resolve(domain, service, family, Type::STREAM, Protocol::TCP) { |addrinfo| yield addrinfo }
       ^------
Error: instantiating 'resolve(String, Int32, Socket::Family, Socket::Type, Socket::Protocol)'


In src/invidious/helpers/helpers.cr:765:14

 765 | Addrinfo.tcp(host, port, timeout: dns_timeout, family: family) do |addrinfo|
                ^--
Error: instantiating 'Socket::Addrinfo.class#tcp(String, Int32)'


In src/invidious/helpers/helpers.cr:766:7

 766 | super(addrinfo.family, addrinfo.type, addrinfo.protocol)
       ^----
Error: instantiating 'super(Socket::Family, Socket::Type, Socket::Protocol)'


In /usr/share/crystal/src/socket.cr:49:5

 49 | initialize(fd, family, type, protocol, blocking)
      ^---------
Error: instantiating 'initialize(Int32, Socket::Family, Socket::Type, Socket::Protocol, Bool)'


In src/invidious/helpers/helpers.cr:765:14

 765 | Addrinfo.tcp(host, port, timeout: dns_timeout, family: family) do |addrinfo|
                ^--
Error: instantiating 'Socket::Addrinfo.class#tcp(Int32, Socket::Family)'


In /usr/share/crystal/src/socket/addrinfo.cr:192:7

 192 | resolve(domain, service, family, Type::STREAM, Protocol::TCP) { |addrinfo| yield addrinfo }
       ^------
Error: no overload matches 'Socket::Addrinfo.resolve' with types Int32, Socket::Family, Bool, Socket::Type, Socket::Protocol

Overloads are:
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil)
 - Socket::Addrinfo.resolve(domain, service, family : Family | ::Nil = nil, type : Type = nil, protocol : Protocol = Protocol::IP, timeout = nil, &block)
```

</details>

`instantiating 'initialize(Int32, Socket::Family, Socket::Type, Socket::Protocol, Bool)'` is supposed to hit this initializer:

`def initialize(fd, @family : Family, @type : Type, @protocol : Protocol = Protocol::IP, blocking = false)` ([socket.cr](https://github.com/crystal-lang/crystal/blob/af095d72d68b903ea3def7829fb4351c2e768369/src/socket.cr#L53))

But the custom initializer added as helper in invidious seems to override that for some reason:

`def initialize(host, port, dns_timeout = nil, connect_timeout = nil, family = Socket::Family::UNSPEC)` ([helpers.cr](https://github.com/iv-org/invidious/blob/0d57a887ea59b6111d9a19b1ea1cea619ad9f129/src/invidious/helpers/helpers.cr#L764))

**Comment by tleydxdy** [comment] 2021-07-19 23:50
I have fixed this issue, then another issue crops up, text.rindex want to return a Int32 but the number given to it was explicitly Int64. you can see the patch https://github.com/iv-org/invidious/pull/2263/files#diff-c7fb42237f52a2684edf3d22d5f0b36f7f0ac8940f71c53886fe4a294ef73357L135

I wonder why isn't these issues showing up before. did something changed in the type inferencer? or it's simply a bug got fixed.

**Comment by straight-shoota** [comment] 2021-07-20 08:38
@tleydxdy I have created a new issue for `String#rindex`. That seems like a backwards-incompatible change slipped through.

There were some changes to the way method overloads are matched, they were supposed to be only improvements fixing incorrect behaviour. I'm not yet sure about the reason for your issue with the `TCPSocket` initializer. It doesn't look right what the compiler is doing there.

**Comment by SamantazFox** [comment] 2021-08-01 22:16
There seem to be a huge inheritance problem here.

From the log provided by @straight-shoota:

1. We hit our overridle of `TCPSocket.initialize()` (in `helpers.cr`, L765) => **OK**
1. We hit `Addrinfo.tcp(...)` (the following line) => **OK**
1. We hit `Addrinfo.resolve(...)` (from `src/socket/addrinfo.cr`, L192) => **OK**
1. It `yield addrinfo`, so for each result we hit the following:
    a. `getaddrinfo() do |addrinfo|` => **OK**
    b. `loop do` => **OK**
1. We return from `Addrinfo.resolve(...)` (at `src/socket/addrinfo.cr`, L192)
1. We return from `Addrinfo.tcp(...)` (at `helpers.cr`, L765)

So up to that part, we're good. But then:

1. We call `super()`, so we should hit `Socket.initialize()`
1. Which we do (`src/socket.cr`, L44-50)
1. And then, we hit the other `initialize` function (the one which takes a file descriptor, `src/socket.cr`, L49)

And finally, we hit `Addrinfo.tcp()` (from `helpers.cr` L765) again?

It looks like calling `initialize` from `Socket.initialize` used `TCPSocket.initialize`, hence passing a file descriptor (`Int32`) to `TCPSocket.new`, which in turn sends it to `Addrinfo.resolve`, hence the error.

Correct me if my logic is wrong.

**Comment by SamantazFox** [comment] 2021-08-01 22:22
And if it happens in this case, it may probably happen in other classes. This can possibly lead to endless loops when trying to compile.

**Comment by asterite** [comment] 2021-08-01 22:58
I didn't read anything, but it's most likely a duplicate of https://github.com/crystal-lang/crystal/issues/2293

**Comment by straight-shoota** [comment] 2021-08-02 09:47
@asterite Yes, that seems to be a contributing factor.

But it should actually not be relevant here, because the methods have different signatures. The custom `TCPSocket#initialize` from invidious' `helpers.cr` has no type restrictions whatsoever.
There's a `Socket#initialize` overload with matching type restrictions, but that one is not visible due to `TCPSocket`'s initializers overshadowing all of `Socket`s (#4546, #4762). There is a similar initializer on `TCPSocket` that delegates to the `super` implementation, but it's missing the `blocking` parameter:

https://github.com/crystal-lang/crystal/blob/55ebfbfe75e93ffdc9373acf649a473b00b24526/src/socket/tcp_socket.cr#L41-L43

And indeed, applying this patch to stdlib fixes the invidious build error:
```diff
--- i/src/socket/tcp_socket.cr
+++ w/src/socket/tcp_socket.cr
@@ -38,8 +38,8 @@ class TCPSocket < IPSocket
     super family, type, protocol
   end

-  protected def initialize(fd : Handle, family : Family, type : Type, protocol : Protocol)
-    super fd, family, type, protocol
+  protected def initialize(fd : Handle, family : Family, type : Type, protocol : Protocol, blocking = false)
+    super fd, family, type, protocol, blocking
   end

   # Creates a TCPSocket from an already configured raw file descriptor
```

The reason for this particular failure was that the `blocking` parameter was added to `Socket#initialize` at a later time and was not copied over to the delegating `TCP#initialize`.

**Comment by straight-shoota** [comment] 2021-08-02 10:28
An overrides annotation could help avoiding such issues when those inherited constructors don't override the complete super method signature (see #1647). It's a very special case, though.

**Comment by SamantazFox** [comment] 2021-08-02 20:45
> I didn't read anything, but it's most likely a duplicate of #2293

Yep, that looks very similar.

Ideally, calling `initialize` in some class shouldn't be able to loop back to sub-classes. But not for other methods.

**Closed** 2021-09-07 09:15 UTC
Labels: kind:bug, topic:compiler:semantic
