### ISSUE TITLE
Add Number#positive? and #negative?

### ISSUE THREAD

**Issue by nard-tech** [crystal-lang/crystal#8917] opened 2020-03-19 10:52 UTC
# Summary

For example, when an array `[-2, -1, 0, 1, 2]` is given, I'd like to write
```crystal
[-2, -1, 0, 1, 2].select(&.positive?)
[-2, -1, 0, 1, 2].select(&.negative?)
```
instead of
```crystal
[-2, -1, 0, 1, 2].select { |i| i > 0 }
[-2, -1, 0, 1, 2].select { |i| i < 0 }
```

So I  want to add `Number#positive?` and `#negative?` like Ruby.

**Comment by straight-shoota** [comment] 2020-03-19 12:58
Duplicate of #6552

**Comment by Sija** [comment] 2020-03-19 13:04
IMO it's sad they were rejected.

**Comment by asterite** [comment] 2020-03-19 13:08
I probably wasn't around when this was rejected, but I think it's harmless to add those two methods, and they might be a bit more descriptive than `{ |x| x > 0 }` or `&.>(0)`.

**Comment by naqvis** [comment] 2020-03-19 13:49
I'll argue against bloating stdlib API, as such use-case isn't standard, and app specific functionality should be treated differently. IMHO stdlib does provide enough mechanism to extend and shouldn't be bloated to cater all use-cases needs. Just my two cents

**Comment by asterite** [comment] 2020-12-11 22:32
Let's do it 👍

**Closed** 2021-04-12 18:27 UTC
Labels: kind:feature, status:discussion, topic:stdlib
