### ISSUE TITLE
Rename YAML mapping

### ISSUE THREAD

**Issue by trans** [crystal-lang/crystal#3500] opened 2016-11-04 15:12 UTC
The term "mapping" is part of the YAML spec. It is the name of one the three fundamental *kinds* of data.

Eventually I expect there is a good chance, as the Crystal YAML implementation improves, that it will need classes to represent these fundamental kinds, `YAML::Mapping`, `YAML::Sequence` and `YAML::Scalar`.

The reason this has occurred to me at all is because I needed access to tags, so I am having to create my own parser (built using the `PullParser`) and the clear approach to implementation was to create such classes. I am using a separate namespace, of course, but it made me realize that similar classes would only make sense in a more complete Crystal YAML implementation eventually.   

So I suggest a renaming to `class_schema`. It is a more appropriate name in any case. Perhaps the simpler name of just `schema` would be better, but I hesitated to suggest this shorter name because I think some one suggested there were plans for a more generalized representation of schemas, not those just tied to the building classes?

To the end user the change would translate to:

```ruby
class Person
  YAML.class_schema(
    ...
  )
```

**Comment by ysbaddaden** [comment] 2016-11-04 15:56
Is it for sure that a `YAML.mapping` method will create a conflict? Or is this proposed to avoid a potential confusion?

I kind of like `YAML.schema`, but we'd have to rename `JSON.mapping` as `JSON.schema` too for consistency.

**Comment by luislavena** [comment] 2016-11-04 16:31
@ysbaddaden but then `JSON.schema` will open the confusion against [JSON Schema](http://json-schema.org/) :confused:

**Comment by trans** [comment] 2016-11-04 16:40
Yes, mainly confusion. Although the file name `yaml/mapping.cr` might ultimately have some contention.

**Comment by luislavena** [comment] 2016-11-04 16:43
@trans please bear with me, but I'm not fully understanding the confusion between `YAML.mapping` (a macro) and `YAML::Mapping` (a class you're implementing).

Perhaps the issue is the require itself? `require "yaml/mapping"` and *not* the naming?

**Comment by trans** [comment] 2016-11-04 18:01
@luislavena Maybe the best way to put it is this: If a Crystal newbe comes to you and asks "What's a YAML mapping?" What do you say?

About `JSON.schema`, that might not actually be an issue b/c wouldn't it seems like to could well make sense to add a method `JSON.schema(schema : JSON::Schema)`.

**Comment by trans** [comment] 2016-11-19 19:36
I've been working on Crystal's YAML library, I've been having difficulty with the construction side of things, so I've decide to put that aside for now and focus on the other parts. The first thing, which I've nearly finished, is an API for working with Intermediate Representation (aka YAML DOM). I would like to submit it in a pull request for inclusion with Crystal. It doesn't effect any of the rest of the YAML library in any significant way, it's pretty much completely additive. But I do run into the problem of this issue. One of the classes is `class YAML::Mapping < YAML::Node`, and the proper file to store that in is obviously `yaml/mapping.cr`.

So can I go ahead and submit a pull request for this issue? If you all want to do this very incrementally, for now I can just change the name of the file from `yaml/mapping.cr` to `yaml/schema.cr` and leave everything else the same. Or if you want, I can go the rest of the way and rename `mapping` to `schema`, but keep the old name for backward compatibility and add a warning.

**Comment by asterite** [comment] 2016-12-13 18:57
We'll eventually support yaml schemas, but I don't see why `YAML.mapping` needs to be renamed, so I'm closing this.

**Closed by asterite** 2016-12-13 18:57 UTC
