### ISSUE TITLE
Formatter regression with hashes inside array

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#7443] opened 2019-02-16 22:18 UTC
Code below:

```cr
very_long_variable_name = [{
  :foo => :bar,
}]
```

gets formatted to:

```cr
very_long_variable_name = [{
                             :foo => :bar,
                           }]
```

which seems like a regression after merging #7048.

IMHO it should keep the format from the original snippet, i.e. 2 space indentation.

/cc @MakeNowJust

**Comment by asterite** [comment] 2019-02-17 00:42
It would be nice to know what #7048 fixed because it doesn't show the wrong formatting.

**Comment by Sija** [comment] 2019-02-17 00:44
@asterite It's stated in the description that it's suppose to fix #7046 ;)

**Comment by asterite** [comment] 2019-02-17 00:48
Oh, right. Thanks! Well, with a couple of regression tests both will be fixed forever.

**Comment by MakeNowJust** [comment] 2019-02-17 00:51
@asterite What is "a couple of regression tests"? A #7946's example and here's?

**Comment by Sija** [comment] 2019-02-17 00:51
I certainly hope so :)

**Comment by asterite** [comment] 2019-02-17 00:53
I mean, just tests that fix this new issue/regression while also fixing the other issue. (as always, sorry for the confusion)

**Comment by Sija** [comment] 2019-02-17 00:55
I'd add couple more:

```cr
very_long_variable_name = [
  {
    :foo => :bar,
  }, {
    :bar => :baz
  },
]
```

```cr
very_long_variable_name = [
  {
    :foo => :bar,
  },
  {
    :bar => :baz
  },
]
```

**Comment by MakeNowJust** [comment] 2019-02-17 01:11
It is hard to be fixed.

One of solutions is use current indent as a new indent instead of `@column` if `[` doesn't follow a newline.

```crystal
diff --git a/src/compiler/crystal/tools/formatter.cr b/src/compiler/crystal/tools/formatter.cr
index 0df6ca258..d07eda85e 100644
--- a/src/compiler/crystal/tools/formatter.cr
+++ b/src/compiler/crystal/tools/formatter.cr
@@ -802,7 +802,7 @@ module Crystal
         found_first_newline = true
       else
         # indent contents at the same column as starting token if no newline
-        offset = @column
+        offset = @indent
       end

       elements.each_with_index do |element, i|
```

However it makes a wrong output to this case:

Input:

```crystal
foo = [1, 2, 3,
       4, 5, 6]
```

Output:

```crystal
foo = [1, 2, 3,
4, 5, 6]
```

**Comment by Sija** [comment] 2019-02-17 01:21
@MakeNowJust Both forms seems off to me, I'd suggest formatting

this:

```cr
foo = [1, 2, 3,
       4, 5, 6]
```

to:

```cr
foo = [
  1, 2, 3,
  4, 5, 6
]
```

**Comment by MakeNowJust** [comment] 2019-02-17 01:27
@Sija It is impossible for now. The formatter does not backtrack, so it cannot know this literal contains a newline at `[`.

**Comment by Sija** [comment] 2019-02-17 01:50
@MakeNowJust Oh, didn't now that. it complicates things a bit... :/

**Comment by asterite** [comment] 2019-02-17 22:45
I will try to fix this.

**Closed** 2019-02-21 12:46 UTC
Labels: kind:bug, topic:tools:formatter
