### ISSUE TITLE
Local variables not defined if set by module-instance variables

### ISSUE THREAD

**Issue by drosehn** [crystal-lang/crystal#4246] opened 2017-04-06 14:31 UTC
This is on:
```cr
# crystal --version
Crystal 0.21.1 (2017-03-18) LLVM 4.0.0
# uname -a
Darwin my.host 14.5.0 Darwin Kernel Version 14.5.0: Sun Sep 25 22:07:15 PDT 2016; root:xnu-2782.50.9~1/RELEASE_X86_64 x86_64
# # aka macOS 10.10.5 (Yosemite)
```
I happened to run into this oddity.  I avoided it by rearranging my code slightly, and the re-arranged code is slightly better than the code which got the compile-time error.  So maybe the correct answer for this issue is **"Don't Do That!"**.  Still, I like to document these things as I trip over them.

Building this program:
```cr
module SomeMod

@@lo_val = 20
@@hi_val = 10

tmp_val = @@hi_val
@@hi_val = @@lo_val
@@lo_val = tmp_val

puts "range = #{@@lo_val} to #{@@hi_val}"

end
```
Results in this compile-time error message:
```cr
# crystal run PR_module-if1.cr
Error in PR_module-if1.cr:9: undefined local variable or method 'tmp_val'

@@lo_val = tmp_val
           ^~~~~~~

```
If I change the instance-variables to local-variables, and build:
```cr
module SomeMod

lo_val = 20
hi_val = 10

tmp = hi_val
hi_val = lo_val
lo_val = tmp

puts "range = #{lo_val} to #{hi_val}"

end
```
then it does produce the expected result:
```cr
# crystal run PR_module-if2.cr
range = 10 to 20
```

**Comment by asterite** [comment] 2017-04-06 15:15
Class instance variables initializers don't have access to output scope. This is the same for constant initializers.

Basically:

```crystal
class Foo
  exp = 1
  @@class_var = exp # Error: exp is not visible here
end
```

Here `exp` isn't visible because the initializer is run in a different scope.

This is not a bug, it's expected behaviour, we are probably missing docs for this somewhere.

**Comment by drosehn** [comment] 2017-04-06 15:31
The documentation may be perfectly fine, and I simply missed it (or missed the significance of what is described).  I understand your description as I read it right now, but if I had read the same words a month ago I wouldn't have understood what you're saying.  Thanks.

**Comment by straight-shoota** [comment] 2020-12-03 00:02
Closing as not a bug.

**Closed by straight-shoota** 2020-12-03 00:02 UTC
Labels: community:to-document, kind:docs
