### ISSUE TITLE
Remove `case ... in` in favor of `case! ... when`

### ISSUE THREAD

**Issue by ALANVF** [crystal-lang/crystal#9674] opened 2020-08-14 01:35 UTC
Ruby has recently gotten pattern matching support, which uses `in` instead of `when`.
Seeing #9258 get merged was very disappointing, because it not only interferes with the previously mentioned pattern matching syntax (which I would also love to see in Crystal), but it also just doesn't really make sense from a developer viewpoint. How should I be able to remember the difference between `in` and `when` if they have similar meanings in this context? Why make the syntax different for every single case instead of just one part of the entire construct itself?
I would like to propose a change, which removes the need for `in`, and just uses `when` instead.

Non-exhaustive match:
```cr
# Works
case 1 || "a"
when Int32
when String
end

# Also works
case 1 || "a"
when Int32
end
```

Exhaustive match:
```cr
# Works
case! 1 || "a"
when Int32
when String
end

# Doesn't compile
case! 1 || "a"
when Int32
end
```

Not only only does the notation make sense (`!` signifies that the case is exhaustive), but it also opens the door to Ruby-like pattern matching syntax in the future since it removes the usage of the `in` keyword.

I have not started a PR for this yet, but I can do so if others like this idea as well.

**Comment by Blacksmoke16** [comment] 2020-08-14 02:00
FWIW this was brought up before.  See https://github.com/crystal-lang/crystal/issues/9020.

**Comment by asterite** [comment] 2020-08-14 11:14
This was my initial suggestion, nobody liked it. Let's move on.

By the way, it's impossible to implement the level of pattern matching in Crystal like in Ruby.

**Comment by ALANVF** [comment] 2020-08-14 11:38
Ah I must have missed that, thanks!
(Hopefully this also means there's a chance that Crystal will one day get pattern matching)

**Comment by ALANVF** [comment] 2020-08-14 11:38
Ah I must have missed that, thanks!
(Hopefully this also means there's a chance that Crystal will one day get pattern matching)

**Comment by ALANVF** [comment] 2020-08-14 11:38
Ah I must have missed that, thanks!
(Hopefully this also means there's a chance that Crystal will one day get pattern matching)

**Comment by ALANVF** [comment] 2020-08-14 11:38
Ah I must have missed that, thanks!
(Hopefully this also means there's a chance that Crystal will one day get pattern matching)

**Comment by straight-shoota** [comment] 2020-11-02 00:54
Closing as duplicate of #9020. This has been discussed in length before being implemented, and I doubt we'd consider this change at the current state.

**Closed by straight-shoota** 2020-11-02 00:54 UTC
