### ISSUE TITLE
Garbage byte written to a struct in release mode

### ISSUE THREAD

**Issue by oprypin** [crystal-lang/crystal#3013] opened 2016-07-19 19:11 UTC
``` crystal
struct Color
  def initialize(@r : UInt8, @g : UInt8, @b : UInt8, @a = 255u8)
    p pointerof(@r)
  end
end

p({Color.new(1u8, 2u8, 3u8), Color.new(4u8, 5u8, 6u8)})
```

Output with Crystal 0.18.7 or master, LLVM 3.5:

``` console
$ crystal run --release bug.cr
Pointer(UInt8)@0x7ffc2f860600
Pointer(UInt8)@0x7ffc2f860600
{Color(@r=1, @g=224, @b=3, @a=255), Color(@r=4, @g=224, @b=6, @a=255)}
```

(`@g` is a random byte, seems to be always a multiple of 16)

Does not reproduce without `--release` or on LLVM 3.8

**Comment by asterite** [comment] 2016-07-19 23:46
I have no idea what's going on... maybe an LLVM bug?

I tried it with LLVM 3.8 and it doesn't happen anymore, as you say.

**Comment by sdogruyol** [comment] 2016-11-05 20:47
LLVM 3.6 on OS X 10.11 with Crystal 0.19.4

```
Pointer(UInt8)@0x7fff54f5dfc8
Pointer(UInt8)@0x7fff54f5dfc0
{Color(@r=1, @g=2, @b=3, @a=255), Color(@r=4, @g=5, @b=6, @a=255)}
```

With master

```
Pointer(UInt8)@0x7fff5a9fdf30
Pointer(UInt8)@0x7fff5a9fdf30
{Color(@r=1, @g=48, @b=3, @a=255), Color(@r=4, @g=48, @b=6, @a=255)}
```

Maybe this is related with Crystal itself?

**Comment by matiasgarciaisaia** [comment] 2017-03-01 20:46
I'm testing this code:

```
struct Color
  def initialize(@r : UInt8, @g : UInt8, @b : UInt8, @a = 255u8)
    p pointerof(@r)
  end
end

pp Crystal::VERSION, Crystal::LLVM_VERSION
p({Color.new(1u8, 2u8, 3u8), Color.new(4u8, 5u8, 6u8)})
```

Using the code at #4095, and here are the results:

```
Crystal::VERSION      # => "0.21.0+4"
Crystal::LLVM_VERSION # => "3.5.2"
Pointer(UInt8)@0x7fffab38fd50
Pointer(UInt8)@0x7fffab38fd50
{Color(@a=255, @b=3, @g=48, @r=1), Color(@a=255, @b=6, @g=48, @r=4)}
```

```
Crystal::VERSION      # => "0.21.0+4"
Crystal::LLVM_VERSION # => "3.9.1"
Pointer(UInt8)@0x7ffd65512bc8
Pointer(UInt8)@0x7ffd65512bc8
{Color(@a=255, @b=3, @g=2, @r=1), Color(@a=255, @b=6, @g=5, @r=4)}
```

It seems to _really_ be an LLVM issue. I'll try to see if I can get any more info by seeing the emitted code or something like that - I don't have much knowledge, but I can take advantage of the rest of the team being around here hehe

**Comment by asterite** [comment] 2017-03-03 19:10
Closing as duplicate of #3695

**Closed by asterite** 2017-03-03 19:10 UTC
Labels: kind:bug, topic:compiler
