### ISSUE TITLE
Rarely failing nil assertion in signal_spec

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#7243] opened 2018-12-31 14:03 UTC
```
Nil assertion failed (Exception)
  from src/class.cr:148:0 in 'not_nil!'
  from spec/std/signal_spec.cr:0:23 in '->'
  from src/signal.cr:255:3 in '->'
  from src/signal.cr:255:3 in 'process'
  from src/signal.cr:198:9 in '->'
  from src/fiber.cr:255:3 in 'run'
  from src/fiber.cr:29:34 in '->'
  from ???
FATAL: uncaught exception while processing handler for CHLD, exiting
```

It seems to be a race condition in the `Singal::CHLD` handler and happens very rarely.

I' might have seen this error more often, but here are at least two instances where it failed in unrelated CI runs:

* [circleci/test_linux](https://circleci.com/gh/crystal-lang/crystal/11987)
* [travis-ci/linux64](https://travis-ci.org/crystal-lang/crystal/jobs/424542591) (unfortunately, travis doesn't seem to keep the logs of a job after it has been restarted)

**Comment by straight-shoota** [comment] 2019-02-10 16:31
Another occurrance: https://circleci.com/gh/crystal-lang/crystal/18298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by asterite** [comment] 2019-02-10 17:16
I GOT IT!!! 💡 

This is the spec:

```crystal
it "CHLD.trap is called after default Crystal child handler" do
  called = false
  child = nil

  Signal::CHLD.trap do
    called = true
    Process.exists?(child.not_nil!.pid).should be_false
  end

  child = Process.new("true", shell: true)
  child.not_nil!.wait # doesn't block forever
  called.should be_true
end
```

TIL I learned about SIGCHLD: it's trapped when a child process **ends**.

The spec fails because of a `not_nil!` (the trace isn't entirely correct with the filenames and line numbers). But my guess was that `child.not_nil!` is raising. How could that happen?

Well, if `Process.new("true", shell: true)` runs and ends **before** it gets assigned to `child`, which is super rare, then the handler will be invoked and `child` will still be `nil` ⚠️ 

This race condition can be reproduced if you change the `child` assignment to:

```crystal
child = begin
  sleep 1
  Process.new("true", shell: true)
end
```

Now to fix it. I guess if `child` is `nil` I'll just `Fiber.yield` until `child` gets a non-`nil` value. It's a bit hard fixing this because something happens before an expression gets assigned to a variable 🤔

**Closed** 2019-02-11 07:19 UTC
Labels: kind:bug, topic:stdlib:runtime
