### ISSUE TITLE
Shebang usage best practices? Currently "#!/usr/bin/env crystal" does not work as-is.

### ISSUE THREAD

**Issue by ssvb** [crystal-lang/crystal#546] opened 2015-04-16 00:41 UTC
The crystal compiler uses the "run" command by default (which is convenient), but still needs "--" separator for the command line arguments (which is not so convenient). It is not necessarily wrong and can be surely handled by an extra wrapper script. But maybe a better solution exists?

**Comment by asterite** [comment] 2015-04-16 17:26
Maybe we can add another command, "wrapper", that just accepts a single argument as a filename and other arguments are arguments for the program, not for the compiler. Then you would do:

```
#!/usr/bin/env/crystal wrapper
```

Would that work?

**Comment by ssvb** [comment] 2015-04-16 18:07
Admittedly I'm not a big expert here, but maybe that would not work (unless this "wrapper" command becomes the new default instead of "run"). The "#!/usr/bin/env crystal" line is there to allow different absolute path to the crystal binary (which is launched by the "env" program). The env program is a little bit dumb and can't handle launching "perl -w" or anything else with extra command line options - http://stackoverflow.com/questions/570183/can-i-use-perls-switches-with-bin-env-in-the-shebang-line

Why does crystal want to have multiple files in the command line for the "run" command? Is using the "require"/"require_relative" directives in the source code not good enough?

**Comment by asterite** [comment] 2015-04-16 18:17
I initially thought the problem was accepting multiple files (we originally added this to run many spec files at once, but honestly I only used it once or twice). But the real problem is that right now you can do, for example `crystal program.cr --release`, which compiles in release mode and runs it, so those flags are passed to the compiler, not the program. You can also use other flags, like `crystal program.cr -s` which shows some stats, but still compiles and runs the program. But I think that, except maybe for `--release`, those other flags go better with the `build` command.

I guess we'll have to weight the tradeoffs and choose a reasonable default :-)

**Comment by kirbyfan64** [comment] 2015-04-16 18:34
I don't really get why is such an issue, since this:

```
#!/usr/bin/env crystal
```

currently works. Other languages have this problem (just try to disable warnings via the command-line arguments inside the hashbang) and they mostly just avoid it. If you want a release program, there's also a good chance that it's a binary for distribution or a simple speed test, i.e. not something you're going to want to use every time you're testing the program.

**Comment by ssvb** [comment] 2015-04-16 18:52
@asterite Toggling of the "--release"  option on/off can be probably also handled by setting some special environment variables. But it's probably best to look at what the other interpreters, compilers and virtual machines are typically doing and try to provide something similar (having less surprises for the users is generally a good idea).

@kirbyfan64 Yes, it works. Except when you want to pass some extra command line arguments to the program. And in this case it becomes a bit inconsistent:

    crystal build test.cr
    ./test foo bar

vs.

    ./test.cr -- foo bar

**Comment by waterlink** [comment] 2015-04-17 06:07
Then, why not create `crystal wrapper` command and make it a default one?
run and build is left untouched for the cases when you want to pass in
compiler args.

**Comment by waterlink** [comment] 2015-04-17 21:34
Another idea that strikes my mind is to have different executable, that
gets installed into the system, ie: `crystal-wrapper`, that can be used in
script's shebang line.

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-04-17 8:07 GMT+02:00 Alex Fedorov <waterlink000@gmail.com>:

**Comment by jhass** [comment] 2015-08-31 22:35
I'd actually vote to close this as a won't fix.

As pointed out for the simple case, `#!/usr/bin/env crystal` already works. For more complex cases you'll ship compiled binaries or a `Makefile` or similar to install a compiled binary. After all recompiliing it every time is just unnecessary overhead.

Where I see these useful are little helper scripts inside a project, not actually meant for the endusers. Things to download something or aid in the build. These needing the power of --release is highly unlikely and for the few occasions where they do it's not too much to ask to use `crystal run`.

`crystal wrapper` would provide a huge overlap with `crystal run`, making the CLI more confusing to use for little benefit in an ecosystem like Crystals.

**Comment by stugol** [comment] 2016-01-31 00:37
It's important to be able to pass arguments to the script on the command line. This is important, and should be fixed.

@jhass: The problem isn't that passing arguments to the Crystal compiler is difficult; the problem is that passing arguments to the _script_ is difficult.

Until we have a decent solution to this, can we at least change the compiler so it assumes _any_ additional arguments after `run` (aside from the name of the script, obviously) are arguments to the script? i.e. an implicit `--` after the script name.

**Comment by kirbyfan64** [comment] 2016-01-31 00:39
FYI, a lot of programming languages I know of (Python, Felix, Nim, Perl, etc.) automatically assume all arguments after the script are FOR the script.

**Comment by stugol** [comment] 2016-01-31 00:40
So basically what I said, then ;)

**Closed** 2016-04-19 20:25 UTC
Labels: compiler, enhancement

**Comment by rafapolo** [comment] 2017-11-15 23:39
Being more used to Ruby or Python, is important to understand the differences in between a interpretor and a compiler. I see no problem in developing and testing a program full of arguments in Crystal as simple as

> crystal build app.cr; ./app -d --full -p 5 -w

**Comment by ssvb** [comment] 2017-11-16 01:17
@rafalchmiel This has been resolved a long time ago, there is nothing to talk about anymore.

**Comment by Beyarz** [comment] 2017-12-09 16:35
This one works fine #!/usr/bin/env crystal

**Comment by NightMachinary** [comment] 2021-03-23 11:06
[**@ssvb**](https://github.com/ssvb) commented on [Nov 16, 2017, 4:47 AM GMT+3:30](https://github.com/crystal-lang/crystal/issues/546#issuecomment-344783948 "2017-11-16T01:17:57Z - Replied by Github Reply Comments"):
> [@rafapolo](https://github.com/rafapolo) This has been resolved a long time ago, there is nothing to talk about anymore.

Is there any info on it on the docs?

**Comment by ssvb** [comment] 2021-03-23 11:25
> Is there any info on it on the docs?

Do you mean somewhere in the Crystal docs? It's a common knowledge that "#!/usr/bin/env <whatever>" in the first line is the way to invoke the interpreter. Such as "#!/usr/bin/env ruby", "#!/usr/bin/env python" and "#!/usr/bin/env crystal" too.

https://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script

**Comment by NightMachinary** [comment] 2021-03-23 11:44
[**@ssvb**](https://github.com/ssvb) commented on [Mar 23, 2021, 3:55 PM GMT+4:30](https://github.com/crystal-lang/crystal/issues/546#issuecomment-804825151 "2021-03-23T11:25:26Z - Replied by Github Reply Comments"):
> > Is there any info on it on the docs?
> 
> Do you mean somewhere in the Crystal docs? It's a common knowledge that "#!/usr/bin/env whatever" in the first line is a way to invoke the interpreter. Such as "#!/usr/bin/env ruby", "#!/usr/bin/env python" and "#!/usr/bin/env crystal" too.
> 
> [stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script](https://stackoverflow.com/questions/2429511/why-do-people-write-usr-bin-env-python-on-the-first-line-of-a-python-script)

I know about the shebang lines; I wanted some details, e.g., is compile caching done on the script, or is it just recompiled on each run, and which options are available (via, say, env vars).

**Comment by asterite** [comment] 2021-03-23 11:53
It's compiled from scratch on each run.

If you really want to use it, go ahead. I prefer to compile it in release mode once and put it somewhere in the path. Crystal is not a scripting language.

**Comment by NightMachinary** [comment] 2021-03-23 13:01
[**@asterite**](https://github.com/asterite) commented on [Mar 23, 2021, 4:23 PM GMT+4:30](https://github.com/crystal-lang/crystal/issues/546#issuecomment-804840464 "2021-03-23T11:53:00Z - Replied by Github Reply Comments"):
> It's compiled from scratch on each run.
> 
> If you really want to use it, go ahead. I prefer to compile it in release mode once and put it somewhere in the path. Crystal is not a scripting language.

I added a [guide](https://github.com/NightMachinary/crystal-book/blob/patch-1/docs/getting_started/scripting.md) on scripting with Crystal, if anyone's interested.

**Comment by jadonk** [comment] 2022-08-28 15:58
There seems to be a lingering issue with `crystal` installed using `snap`.

Because `snap` is a recommended approach to installing `crystal`, I'd recommend providing instructions on how to call it using a shebang. The only way I was able to quickly make it work was to rename my script to "cyrstal" such that the execution of /usr/bin/snap knew what program it should execute. I'm sure there is a better way to deal with this limitation of `snap`.

What I thought would work and proof that `crystal` is in my path:
```
jkridner@slotcar:~/workspace/crystal$ ls -l /snap/bin/crystal
lrwxrwxrwx 1 root root 13 Aug 28 11:33 /snap/bin/crystal -> /usr/bin/snap
jkridner@slotcar:~/workspace/crystal$ cat hello_world.cr 
#!/usr/bin/env cyrstal
puts "Hello World!"
jkridner@slotcar:~/workspace/crystal$ ./hello_world.cr 
/usr/bin/env: ‘cyrstal’: No such file or directory
jkridner@slotcar:~/workspace/crystal$ echo $PATH
/home/jkridner/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/jkridner/.local/bin
jkridner@slotcar:~/workspace/crystal$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

Treating this as an environment problem won't work, because the problem turns out to be the name of the first argument when `/usr/bin/snap` is called:
```
jkridner@slotcar:~/workspace/crystal$ vim hello_world.cr 
jkridner@slotcar:~/workspace/crystal$ cat hello_world.cr 
#!/snap/bin/cyrstal
puts "Hello World!"
jkridner@slotcar:~/workspace/crystal$ ./hello_world.cr 
bash: ./hello_world.cr: /snap/bin/cyrstal: bad interpreter: No such file or directory
jkridner@slotcar:~/workspace/crystal$ file /snap/bin/crystal
/snap/bin/crystal: symbolic link to /usr/bin/snap
```

Proof that running the real executable works:
```
jkridner@slotcar:~/workspace/crystal$ cat hello_world.cr 
#!/snap/crystal/current/bin/crystal
puts "Hello World!"
jkridner@slotcar:~/workspace/crystal$ ./hello_world.cr 
Hello World!
```

Finally, my work-around to show the source of the issue:
```
jkridner@slotcar:~/workspace/crystal$ mv hello_world.cr crystal
jkridner@slotcar:~/workspace/crystal$ vim crystal 
jkridner@slotcar:~/workspace/crystal$ cat crystal 
#!/usr/bin/env crystal
puts "Hello World!"
jkridner@slotcar:~/workspace/crystal$ ./crystal 
Hello World!
```

**Comment by Sija** [comment] 2022-08-29 10:24
@jadonk Perhaps it's just a copy/paste issue, but there's a typo (`cyrstal`) in the examples you've provided.

**Comment by jadonk** [comment] 2022-08-30 18:01
:blush: even worse, I made the same mistake twice.
