### ISSUE TITLE
Linker warnings in Mac OS Ventura

### ISSUE THREAD

**Issue by PascalLeMerrer** [crystal-lang/crystal#13846] opened 2023-09-27 09:38 UTC
## Bug Report

I installed Crystal on MacOS Ventura, using Homebrew.
It worked, however compiling a simple hello world generates 280 warnings like:

```
ld: warning: no platform load command found in '/Users/pascal/.cache/crystal/Users-pascal-Documents-tutorials-crystal-hello_world.cr/F-loat32.o', assuming: macOS
ld: warning: no platform load command found in '/Users/pascal/.cache/crystal/Users-pascal-Documents-tutorials-crystal-hello_world.cr/C-rystal.o', assuming: macOS
```

Crystal version: 1.9.2
OS Version: Ventura, then Sonoma (I upgraded it, but it did not change anything)
Brew doctor does not signal anything wrong.

The steps I followed:

```
brew update
brew install crystal

echo 'puts "Hello, World!"' > hello.cr

crystal hello.cr
```

**Comment by HertzDevil** [comment] 2023-09-27 12:51
This seems to be related to a "new linker" in Xcode 15, see https://projects.blender.org/blender/blender/pulls/110243 for example

**Comment by PascalLeMerrer** [comment] 2023-09-27 15:08
`crystal hello.cr --link-flags=-Wl,-ld_classic` has no visible effect on this issue

**Comment by PascalLeMerrer** [comment] 2023-09-28 07:42
It works much better indeed! Thanks @beta-ziliani

**Comment by fnordfish** [comment] 2023-09-28 12:07
Just an observation:
`crystal eval` has the same issue, and it doesn't take `--link-flags`.
`export LDFLAGS="-Wl,-ld_classic"` doesn't seem to get picked up.

**Comment by HertzDevil** [comment] 2023-09-28 12:35
You should be able to do `CRYSTAL_OPTS="--link-flags=-Wl,-ld_classic"

**Comment by mloughran** [comment] 2023-09-28 22:28
Just to note that macOS Sonoma (14) is also affected (as one might expect) by the same issue, and that setting the `--link-flags` as above avoids the warnings.

Out of interest: I happened to notice that binaries created with the "new linker" are about 10% smaller than when using these flags.

**Comment by Mark24Code** [comment] 2023-10-09 13:20
Same problem

**Comment by crimson-knight** [comment] 2023-10-16 20:41
FYI, I upgrade to Sonoma today and was getting link warnings. There is also an update for xcode-tools that once installed resolved the linker warnings.

**Comment by Narven** [comment] 2023-10-24 21:09
```bash
CRYSTAL_OPTS="--link-flags=-Wl,-ld_classic" crystal run hello.cr
```

works for me . I'm on:
macOS 14.0 23A344 x86_64 Sonoma

**Comment by w-A-L-L-e** [comment] 2023-12-29 16:13
Yes even better is to just put this export in your bashrc or .zshrc
```
export CRYSTAL_OPTS="--link-flags=-Wl,-ld_classic"
```
then crystal build, crystal run etc all work without the ld warnings.

**Comment by hovsater** [comment] 2024-04-05 15:51
I've been investigating this and it's related to the default target triple produced by Crystal during compilation. It seems like in order to fix a [bug](https://github.com/crystal-lang/crystal/issues/1402) back in 2015, we stripped the minimum deployment target from the target triple in this [commit](https://github.com/crystal-lang/crystal/commit/5bbf4d193aba0663b70ee3fbf750ac86b9e966b0). Since then, further work has been put into place to normalize target triples from different architectures.

https://github.com/crystal-lang/crystal/blob/16751451e8618e84d66ee97b8388441e31b7fd3e/src/llvm.cr#L91-L109.

With the release of Xcode 15, a [new linker was introduced](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking) and with it came these error messages. It appears that the new linker is stricter in which target triples it considers valid. Specifically, it looks like the minimum deployment target is required. E.g., `aarch64-apple-darwin23.3.0` is valid, while `aarch64-apple-darwin` is not.

Before I go ahead and submit the pull request, I'd love to discuss what the correct path forward is. We could change the behaviour of `LLVM#default_target_triple` to only strip the minimum deployment target for macOS versions below a certain threshold or we could drop the stripping behaviour entirely. I'm not entirely sure how backwards compatible we want to be.

**Comment by HertzDevil** [comment] 2024-04-05 16:25
Does this also explain why I couldn't reproduce this on my M2 since the normalization fails due to #14052?

**Comment by hovsater** [comment] 2024-04-05 16:40
It does, yes. I'm seeing the same behaviour on my machine since the default triple returned by LLVM is `arm64-apple-darwin23.3.0` and thus it doesn't get normalised by `LLVM#default_target_triple`. The architecture still gets normalized by `Crystal::Codegen::Target`:

https://github.com/crystal-lang/crystal/blob/16751451e8618e84d66ee97b8388441e31b7fd3e/src/compiler/crystal/codegen/target.cr#L22-L34

but the new linker seem to accept that anyway.

**Comment by hovsater** [comment] 2024-04-05 17:00
It turns out we [hard-code](https://github.com/crystal-lang/distribution-scripts/blob/104c978ff9d9fe0c5e2d7721c63074cc98a8ea04/omnibus/config/software/crystal.rb#L71-L79) the target in the [distribution-scripts](https://github.com/crystal-lang/distribution-scripts). This is definitely also an issue.

**Comment by straight-shoota** [comment] 2024-04-06 11:00
This is great work, thanks Kevin for digging into this 🚀 

I guess there's a reason why LLVM doesn't normalize target triples. Our normalization is quite significant in some places.
Before we change this, we need to check where these triples are used and whether some use cases may depend on normalized values. We may have to offer both, the full raw triple as well as a normalized version.

**Comment by oprypin** [comment] 2024-04-27 12:21
I am running into this issue when I use Intel macs on GitHub Actions since this week.
Moreover, presumably due to the same root cause, I am unable to link against any C libraries that I built myself in CI, whereas just a week ago I was able to. This is an **error** in addition to the warnings that others already reported.
This is probably because GitHub Actions updated their Xcode.

```
ld: warning: REFERENCED_DYNAMICALLY flag on symbol '_catch_exception_raise' is deprecated
...
ld: warning: no platform load command found in '/Users/runner/.cache/crystal/Users-runner-work-crystal-chipmunk-crystal-chipmunk-spec/T-uple40U-I-nt6441.o0.o', assuming: macOS
dyld[15199]: Symbol not found: _cpArbiterGetContactPointSet
```

https://github.com/oprypin/crystal-chipmunk/actions/runs/8859208139/job/24329593971
https://github.com/oprypin/crsfml/actions/runs/8859272671/job/24328862277

**Comment by oprypin** [comment] 2024-04-27 12:31
The warnings are now always reproducible on GitHub Actions with `runs_on: macos_13`.
https://github.com/crystal-lang/install-crystal/actions/runs/8859670657/job/24329698775

**Comment by oprypin** [comment] 2024-04-27 12:34
Back to the C library troubles-
Even if I apply `CRYSTAL_OPTS="--link-flags=-Wl,-ld_classic"` I am still building my C libraries with the new linker. (Presumably would need to apply such flags to the step that builds the C library as well).
As such, I get this error instead:
```
ld: warning: dylib (/usr/local/lib/libchipmunk.dylib) was built for newer macOS version (13.6) than being linked (13.0)
```
https://github.com/oprypin/crystal-chipmunk/actions/runs/8859789088/job/24329985809

**Comment by yanecc** [comment] 2024-05-01 18:15
I met the same warnings on GitHub Actions, with the full warning message here.

https://github.com/yanecc/MockGPT/actions/runs/8913041997/job/24477764716#step:4:24

**Comment by hovsater** [comment] 2024-05-01 18:45
Those warnings should be gone whenever https://github.com/crystal-lang/crystal/pull/14466 gets merged.

**Comment by GrantBirki** [comment] 2024-05-06 00:47
I am also getting errors in GitHub Actions when using MacOS based runners. Builds on Linux work fine:

```console
[14/13] Codegen (linking)                 
cc _main.o3.o -o /Users/runner/work/runway/runway/bin/runway  -rdynamic -L/Users/runner/work/_temp/crystal-latest-true-undefined/embedded/lib -lssh2 -lxml2 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -L/opt/homebrew/Cellar/libyaml/0.2.5/lib -lyaml -lpcre2-8 -lgc -L/opt/homebrew/Cellar/libevent/2.1.12_1/lib -levent_pthreads -levent -L/opt/homebrew/Cellar/libevent/2.1.12_1/lib -levent -liconv
E: Error target runway failed to compile:
ld: warning: ignoring duplicate libraries: '-levent'
ld: library 'ssh2' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of command failed with exit status 1: cc "${@}" -o /Users/runner/work/runway/runway/bin/runway  -rdynamic -L/Users/runner/work/_temp/crystal-latest-true-undefined/embedded/lib -lssh2 -lxml2 -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` -L/opt/homebrew/Cellar/libyaml/0.2.5/lib -lyaml -lpcre2-8 -lgc -L/opt/homebrew/Cellar/libevent/2.1.12_1/lib -levent_pthreads -levent -L/opt/homebrew/Cellar/libevent/2.1.12_1/lib -levent -liconv
```

[source logs](https://github.com/runwaylab/runway/actions/runs/8962378635/job/24611172955#step:6:56)

**Closed** 2024-06-15 14:42 UTC
Labels: kind:bug, platform:darwin
