### ISSUE TITLE
{{ @type.name.stringify }} (Crystal::MacroExpression) at class.cr:161:11

### ISSUE THREAD

**Issue by boulme** [crystal-lang/crystal#15126] opened 2024-10-24 16:04 UTC
The file `bug.cr` copy-pasted here
```crystal
def inspect(x : Object) : Nil
  puts("(#{x}) of #{x.class} < #{typeof(x)} ")  
end

[ Int32, Float64, Array(Int32) ].each { |x| inspect(x) }

inspect(Number)
inspect(Object)

# commenting the next line removes the bug 
[ Number, Object ].each { |x| inspect(x) }
```
while compiling with `crystal bug.v`, produces:
```
BUG: {{ @type.name.stringify }} (Crystal::MacroExpression) at /usr/share/crystal/src/class.cr:161:11 should have been expanded (Exception)
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2482:7 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:28:11 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2461:9 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2478:7 in 'codegen_fun'
  from /crystal/src/compiler/crystal/codegen/fun.cr:60:3 in 'target_def_fun'
...
Error: you've found a bug in the Crystal compiler. Please open an issue,  ...
```
Crystal version:
```
Crystal 1.14.0 [dacd97bcc] (2024-10-09)
LLVM: 18.1.6
Default target: x86_64-unknown-linux-gnu
```
OS: Ubuntu 24.04.1 LTS

**Comment by Blacksmoke16** [comment] 2024-10-24 16:08
Duplicate of #9667

**Closed by Blacksmoke16** 2024-10-24 16:08 UTC
Labels: kind:bug, topic:compiler:semantic
