### ISSUE TITLE
C++ interop

### ISSUE THREAD

**Issue by kennymalac** [crystal-lang/crystal#3916] opened 2017-01-18 23:34 UTC
Crystal allows for the use of C, however my question is if there are plans to have interop for C++ as well. Well, there are cleary not, but wouldn't it be cool? It would complicate things quite a bit but Rust for example has C++ interop as their planned feature for 2017.
Some of us love scripting languages yet need them to be efficient, and I'm sure C++ interop would be used as much as C if not more. C is often used for UNIX software. C++ is used for industrial software where OO is necessary. I don't think people who use a lot of C like OOP. And I think most would agree C++14/17 and later is a much better language than C++03 or even C11. (Please no flaming...)

Another argument for this: it'd be a huge differentiator from languages like Python, Ruby, and Perl where C++ developers have to work with a CFFI and then wrap objects around it. Having it be seamlessly available in the language would open up the gateway to having it work with game engines and various industrial-grade solutions. It would also save a lot of people from having to use Python anywhere. :)

Just look at this shit: https://docs.python.org/2/extending/extending.html
PyArg_ParseTuple(args, "s", &command)  # why even live?

**Comment by kirbyfan64** [comment] 2017-01-19 00:09
I'd personally recommend it, *but after 1.0*. C++ interop is hard as hell, especially once you get into crap like mangling and custom calling conventions and such.

**Comment by Sija** [comment] 2017-01-19 04:10
See https://github.com/crystal-lang/crystal/issues/3098

**Comment by kennymalac** [comment] 2017-01-19 05:32
Okay it is obvious using C++ libs in Crystal would be hard to do.
But why not just take a look at how the Rust guys will be doing it?

**Comment by konovod** [comment] 2017-01-19 07:41
D interop has plenty of limitations. No constructors\destructors, no stdcall and i'm pretty sure no STL or other templates in the functions interface (of course they can be inside implementation, but same is true for C interop). Is it much better than C interop?

**Comment by asterite** [comment] 2017-01-19 10:48
@kennymalac Any link to Rust code implementing C++ interop?

**Comment by Sija** [comment] 2017-01-19 12:09
Some links regarding the topic:
- https://www.reddit.com/r/rust/comments/3cj1fg/rust_c_interop/
- https://www.reddit.com/r/rust/comments/4yz59h/cc_interop/
- https://internals.rust-lang.org/t/interfacing-d-to-legacy-c-code-a-summary-of-a-competing-languages-capabilities/1406
- http://swig.org/

**Comment by ysbaddaden** [comment] 2017-01-19 13:08
By the way, `libclang` would help, both for parsing C++ headers obviously, but also for mangling symbols, targeting the MSVC or GNU "standards".

**Comment by spalladino** [comment] 2017-01-19 16:52
Closing as duplicate of #3098 as Sija brought up

**Closed by spalladino** 2017-01-19 16:52 UTC
Labels: status:duplicate, status:someday
