### ISSUE TITLE
WebSocket: Unexpected end of http request (Exception)

### ISSUE THREAD

**Issue by oltmannsdaniel** [crystal-lang/crystal#4588] opened 2017-06-18 14:41 UTC
My code:
```crystal
require "http/web_socket"

socket = HTTP::WebSocket.new(URI.parse("wss://ws.blockchain.info/inv"))

socket.on_message do |m|
  puts m
end

spawn do
  socket.run # Not solved pretty good with the loop stuff cause of send
end

socket.send "{\"op\":\"unconfirmed_sub\"}"
```

Output:
```
daniel@daniel-desktop:~/code/bitcoin$ crystal run src/test.cr 
Unexpected end of http request (Exception)
0x48fbd7: *CallStack::unwind:Array(Pointer(Void)) at ??
0x570b56: from_io at /opt/crystal/src/http/client/response.cr 88:7
0x570afb: from_io at /opt/crystal/src/http/client/response.cr 86:3
0x541422: new at /opt/crystal/src/http/web_socket/protocol.cr 272:5
0x540f93: new at /opt/crystal/src/http/web_socket/protocol.cr 285:14
0x561e66: new at /opt/crystal/src/http/web_socket.cr 28:5
0x477184: __crystal_main at /home/daniel/code/bitcoin/src/test.cr 3:1
0x487fe9: main at /opt/crystal/src/main.cr 12:15
0x7f91e021d830: __libc_start_main at ??
0x4767f9: _start at ??
0x0: ??? at ??
```

What **should** happen: Get a message....

My setup:
- Ubuntu 16.04
- Crystal 0.22.0-1
- Installed all required libaries and updated them

What I tried:
- Works fine in any other language....

**Comment by Sija** [comment] 2017-06-18 15:04
Duplicate of #4340. Next time please use search before posting an issue.

**Comment by oltmannsdaniel** [comment] 2017-06-18 15:22
Ok. Sorry, but I didn't found it. Thanks.

Am 18.06.2017 17:04 schrieb "Sijawusz Pur Rahnama" <notifications@github.com

**Closed** 2017-06-18 15:23 UTC
