### ISSUE TITLE
Want: Parameterized type support via alias

### ISSUE THREAD

**Issue by RomanHargrave** [crystal-lang/crystal#4264] opened 2017-04-10 02:57 UTC
Some languages allow for the definition of parameterized types, or type aliases that accept parameters. While not strictly essential (they are just an alias, after all), they can greatly help in managing your code.

Example & expected behaviour:

```crystal
class GenericClass(X, Y)
    alias Operation(Z) = Proc(Y, Z)
end
```

Expect: `GenericClass(Type1, Type2)::Operation(Type3) # => Proc(Type2, Type3)`

The gitbook doesn't suggest it is available, and the compiler doesn't like what would be the assumed syntax.

**Comment by jhass** [comment] 2017-04-10 06:11
The question is how do you access it outside the class, and how can it be made obvious to the consumer whether the alias needs the "namespaces" generic type or not. Currently you can always access all constants of a generic class without a parameter. 

We already had this discussion in some other issue if somebody wants to go for a hunt.

**Comment by asterite** [comment] 2017-04-10 12:46
Closing as duplicate of #1920 and #2803 (this last one is still open so the discussion can continue there, but because of reasons pointed out by @jhass I don't think this will ever be implemented)

**Closed by asterite** 2017-04-10 12:47 UTC
