### ISSUE TITLE
Domain resolution always fails on the second use

### ISSUE THREAD

**Issue by lbguilherme** [crystal-lang/crystal#2568] opened 2016-05-07 10:51 UTC
The following Crystal code fails for me:

```crystal
require "socket"

p TCPSocket.new("google.com", 80)
p TCPSocket.new("google.com", 80)
```

It always raises on the second connection:

```
#<TCPSocket:fd 12>
Error connecting to 'google.com:80': Network is unreachable (Errno)
[4364583] *CallStack::unwind:Array(Pointer(Void)) +87
[4364474] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +10
[4364426] *CallStack::new:CallStack +42
[4372071] *Exception +39
[4371992] *Errno#initialize<Errno, String>:CallStack +120
[4371841] *Errno::new<String>:Errno +113
[4414852] *TCPSocket +324
[4411046] *TCPSocket#initialize<TCPSocket, String, Int32, Nil, Nil>:Nil +1206
[4409816] *TCPSocket::new<String, Int32, Nil, Nil>:TCPSocket +184
[4409627] *TCPSocket::new<String, Int32>:TCPSocket +27
[4341583] ???
[4349481] main +41
[139866884900224] __libc_start_main +240
[4339577] _start +41
[0] ???
```

I'm having a hard time trying to understand why this happens. The exactly equal ruby code works as expected. And the error is reproduced every time I run: The first works, the second fails. The domain name might be relevant, with some others the error changes to `getaddrinfo: Non-recoverable failure in name resolution (Socket::Error)`, but I found no pair of domains that work.

The odd thing is that I was unable to reproduce it on other machines. But still looks to be a crystal issue because every other program works and I don't think I have any fancy configuration.

I'm running Linux, Fedora 23, 64-bit.

**Comment by lbguilherme** [comment] 2016-05-07 10:52
Similar to #2562, The ruby code takes 0.137 seconds to work, and the crystal version takes 6.054 seconds to fail. Consistent with the 3 seconds for one connection reported there.

**Comment by luislavena** [comment] 2016-05-07 13:00
@lbguilherme it works for me without issues:

```
$ crystal --version
Crystal 0.16.0 [fc89c1a] (Thu May  5 16:38:39 UTC 2016)
$ crystal 6.cr 
#<TCPSocket:fd 9>
#<TCPSocket:fd 10>
```

Most of these issues are network related issues, perhaps caused by cached DNS entries in your machine or your local network and sometimes fail to respond.

Any more details that you can provide will be appreciated.

**Comment by ysbaddaden** [comment] 2016-05-07 13:14
Since this happens on a single machine, and can't be reproduced elsewhere makes it complicated to help debug.

We use libevent's DNS resolver (evented), not `getaddrinfo` or `gethostbyname` syscalls that are blocking the whole process. This explains why other languages are unaffected: Ruby and Curl both use `getaddrinfo`. Maybe the installed libevent has a bug that is triggered with your network or OS configuration?

There has been some discussions (in another related issue) to use alternative, but not portable, syscalls like `getaddrinfo_r` that are non blocking, but this will require non trivial and per target work (Linux, Darwin), and sometimes there are no such alternatives (FreeBSD).

**Comment by jhass** [comment] 2016-05-27 15:04
Closing in favor of #2660

**Closed by jhass** 2016-05-27 15:04 UTC
Labels: bug, needs more info, standard library
