### ISSUE TITLE
recursive alias of union type not working as expected

### ISSUE THREAD

**Issue by galvertez** [crystal-lang/crystal#4118] opened 2017-03-06 01:22 UTC
## the issue
union type created using recursive alias doesn't work as intended (this code is copied directly from the [alias page](https://crystal-lang.org/docs/syntax_and_semantics/alias.html) with 2 lines added at the bottom. with this configuration, i expected to be able to create an empty hash and then add another hash to it later, as long as the key was a string.

i have tried  transforming `Json` to a class and instantiating it where `x` is an instance variable instead (in case there was some namespace weirdness that i haven't learned about yet)

i have also tried explicitly naming `Hash(String, Hash(String, String)).new` and adding a `String => String` hash to the higher level hash, and that worked fine, which seems to rule out everything except the recursive alias. i am also wondering if this is an os specific thing, because i was only able to find one similar issue, which was already closed. the solution was provided by the user, and it didn't work for me either, but since there are so few instances of this complaint, it makes me think it is specific to my environment.

### code
```
# copied from https://crystal-lang.org/docs/syntax_and_semantics/alias.html
module Json
  alias Type = Nil |
               Bool |
               Int64 |
               Float64 |
               String |
               Array(Type) |
               Hash(String, Type)
end

x = Hash(String, Json::Type).new
x["key"] = {"value" => "z"}
```

### error
```
$ crystal build doc-test.cr 
Error in doc-test.cr:13: instantiating 'Hash(String, Json::Type)#[]=(String, Hash(String, String))'

x["key"] = {"value" => "z"}
 ^

in /usr/local/Cellar/crystal-lang/0.21.0/src/hash.cr:43: instantiating 'insert_in_bucket(Int32, String, Hash(String, String))'

    entry = insert_in_bucket index, key, value
            ^~~~~~~~~~~~~~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/hash.cr:842: instantiating 'Hash::Entry(String, Json::Type)#value=(Hash(String, String))'

          entry.value = value
                ^~~~~

in /usr/local/Cellar/crystal-lang/0.21.0/src/hash.cr:881: expanding macro

    property value : V
    ^

in macro 'property' expanded macro: macro_4468492592:567, line 10:

   1.       
   2.         
   3.           
   4.             @value : V
   5. 
   6.             def value : V
   7.               @value
   8.             end
   9. 
> 10.             def value=(@value : V)
  11.             end
  12.           
  13.         
  14.       
  15.     

instance variable '@value' of Hash::Entry(String, Json::Type) must be Json::Type, not Hash(String, String)
```

### os info
```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.12.2 (16C67)
      Kernel Version: Darwin 16.3.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ****
      User Name: ****
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 38 days 5:18
```

### version
```
$ crystal -v
Crystal 0.21.0 (2017-02-21)
```

### question
i am a little confused as to the purpose of enforcing type restriction on hashes to begin with. 
why should a hash not accept any type for keys/values, and then optionally restrict types?

e.g.
```
# no type restriction, can accept any type as a key or value
Hash.new 

# Symbol => String style hash as it is currently
Hash(Symbol, String).new 

# blank hash with no type restriction
{} 

# Symbol => String style hash as it is currently
{} of Symbol => String 
```

i'm not asking this as a feature request, just trying to understand the philosophy. i am finding the `Hash` class prohibitively restrictive and difficult to use, so i think i'm not using it correctly, and maybe you guys could lend me some insight?

Thanks,
gvtz

**Comment by CaptainPhilipp** [comment] 2017-03-06 09:35
Maybe, the First reason is that the Type must be declared before you nest it into another type.
Even if it can worked, there would be endless recursion.

alias Type = Nil | Bool | Int64 | Float64 | String
alias OtherType = Array(Type) | Hash(String, Type)

But here we have another problem:
# => error:  ... ... ... must be (Bool | Nil | Hash(String, Bool | Nil)), not Hash(String, Bool)
(here alias Type = Nil | Bool)

For another example, Array(String | Int32) MUST have both of types:
["foo", 666, 0] # => works, we have Array(String | Int32)
["foo", "bar"] # => error, we have Array(Int32), not Array(String | Int32)

# sorry for my english =|

**Comment by asterite** [comment] 2017-03-06 13:03
Duplicate of #2587 and probably many others.

Read [this](https://github.com/crystal-lang/crystal/issues/2587#issuecomment-219014981)

**Closed by asterite** 2017-03-06 13:03 UTC

**Comment by galvertez** [comment] 2017-03-06 14:38
but #2587  doesn't deal with recursion at all. 
the problem i have is with recursion in aliases. `Hash` is just how i discovered it, and not the actual problem itself. 
recursive alias also fails with `Array` or any other collection type i've tried.

the code from [this page](https://crystal-lang.org/docs/syntax_and_semantics/alias.html) doesn't work in my environment. 
so is it a bug, or is the documentation out of date?

**Comment by asterite** [comment] 2017-03-06 14:41
@galvertez What code doesn't work? I'll copy the snippets from the page you link:

Works:
```crystal
alias PInt32 = Pointer(Int32)

ptr = PInt32.malloc(1) # : Pointer(Int32)
```

Works:
```crystal
alias RecArray = Array(Int32) | Array(RecArray)

ary = [] of RecArray
ary.push [1, 2, 3]
ary.push ary
ary #=> [[1, 2, 3], [...]]
```

Works:
```crystal
module Json
  alias Type = Nil |
               Bool |
               Int64 |
               Float64 |
               String |
               Array(Type) |
               Hash(String, Type)
end
````

The snippet that doesn't work is the one you submitted here, which isn't what the docs are saying. I'll copy it:

```crystal
module Json
  alias Type = Nil |
               Bool |
               Int64 |
               Float64 |
               String |
               Array(Type) |
               Hash(String, Type)
end

x = Hash(String, Json::Type).new

# This line is wrong
x["key"] = {"value" => "z"}

# Use this
x["key"] = {"value" => "z"} of String => Json::Type
```

This is not a bug, that's how the language works.

**Comment by Sija** [comment] 2017-03-06 15:18
@galvertez Checkout [any_hash.cr](https://github.com/Sija/any_hash.cr). I've created it out of my frustrations with recursive hashes and type casting - maybe you'll find some inspiration ;)

**Comment by galvertez** [comment] 2017-03-06 15:33
@asterite my mistake... not totally sure how that got by me.
@CaptainPhilipp i see now, that makes sense. and your english is fine :)
@Sija thanks, i will check it out. i was going to start working on something like that for myself because of general confusion surrounding the stdlib offering.

**Comment by RX14** [comment] 2017-03-06 19:12
@galvertez I'd suggest you learn how crystal hashes work and why they don't accept any type before trying any_hash.cr. Crystal is a strongly-typed language, which means the compiler has to know the type of every variable in the program. If you could put any type into a `Hash` object, the compiler wouldn't be able to tell the type of the variable when you retrieved an object from it. The huge advantage of the compiler knowing the type of every variable is that it can enforce that there will be no runtime errors from using the variable. When you use any_hash.cr you're converting a compile-time error into a runtime error, which has obvious downsides.

Hashes in Ruby are used as a general data storage container, in Crystal you'd either use a class, or use a named tuple if you want something quick and ugly. If you want some tips on how to solve problems "the crystal way" ask in gitter or IRC, you'll get much further than trying to think "in ruby".

**Comment by Sija** [comment] 2017-03-06 19:22
@RX14 sometimes you'd just want exactly that - flexible container for the types you know you're going to handle - `JSON::Any` came out such frustration, _any_hash.cr_ is another example.

**Comment by RX14** [comment] 2017-03-06 20:15
@Sija `JSON::Any` exists to minimise the impedance mismatch between JSON, which is dynamically typed, and Crystal which is statically typed. If you're using `any_hash` to wrap "dynamically typed" data which perhaps was emitted by a dynamically typed language then that's a good usecase. However - just as with `JSON::Any` - you should convert that data into a structure which the crystal compiler can more easilly understand as soon as possible to get the best from Crystal.

If you're storing some data in a container, that's only useful if you're going to retrieve the data from the container and do some processing with it. To process the data, you have to use it, and to use it you have to call methods on it, and to do that you have to know what type(s) it is. There's very little you can do with just `Object`. If you take that knowledge of what the types are and encode that in the type system you're going to be better off.

There are three possible scenarios I can think of:
1. Every key in the hash is the same type, or could contain one of several types but you can't tell which from the key. Solution: use `Hash(KeyType, ValueType)`.
2. You know some keys contain type(s) a, and some keys contain type(s) b. Solution: use 2 hashes, choose which one to use depending on which type of key you're querying.
3. You know exactly which keys contain which types. This means you know exactly how many keys there are beforehand, and can enumerate them. Solution: use a class/struct/`Tuple`/`NamedTuple`. Regarding `NamedTuple` being immutable, why not just use a class?

**Comment by Sija** [comment] 2017-03-06 21:04
That's a very sound theory regarding IMO almost any other use case than storing arbitrary user data where the only thing you know is type of the key and union of value types - like a typical JSON-related scenario :)

**Comment by asterite** [comment] 2017-03-06 21:13
@Sija If you store arbitrary data then how can you process it? I pretty much agree 100% with @RX14 here.

**Comment by Sija** [comment] 2017-03-06 21:19
@asterite It's mostly for keeping around (for sending later), not much of a processing although that's not an issue - see [raven.cr](https://github.com/Sija/raven.cr) data sanitization [processor](https://github.com/Sija/raven.cr/blob/develop/src/raven/processors/sanitize_data.cr) for example.

I'd love to do it with just stdlib but there's no flexible way I've found to achieve that.
So I wrote a shard, yikes...

**Comment by asterite** [comment] 2017-03-06 21:41
@Sija Wow, nice! We are currently using Sentry at Manas for some projects.

If the data is mostly for keeping it around, can't it be kept as a opaque String?

**Comment by Sija** [comment] 2017-03-06 23:06
@asterite as you can see there are cases when the data needs to be transformed in between (storing and sending) so serializing and de-serializing them would be a killer...

Sentry was my choice yrs ago and I still use it with success as well, long live opensource! :)

**Comment by RX14** [comment] 2017-03-06 23:13
@Sija That sounds like a very good use case for the library you wrote, but that's quite a specific usecase which I wouldn't advertise to newcomers. It's probably just going to mislead them. (lead them off the typed path :P)

**Comment by galvertez** [comment] 2017-03-06 23:37
the more i am thinking about it (and reading this thread) the more i agree with rx14 and asterite. it is actually easier/safer/generally better to just build from the inside out, rather than outside in, making modifications as the hash tumbles through the program. this would be the same as the second scenario from [this comment](https://github.com/crystal-lang/crystal/issues/4118#issuecomment-284518488). 

i'm only kind of new! i've been following this repo for over a year now, but i haven't had an excuse to actually use it and i got tired of waiting so i am rewriting something i made with ruby a while ago. clearly this is going to take more work than i originally thought to reach feature parity.

i changed my syntax to every permutation i could think of, and when none of them did what i thought they would, i thought there must be something wrong w/ my environment, 

i still think it would be nice to have something a bit more flexible in stdlib, but i might change my tune soon.

i'll be less trigger happy with the issue button from here on, and thanks for carrying on the discussion after closing. it has been hugely enlightening.

**Comment by Sija** [comment] 2017-03-07 00:10
@RX14 yes, it's important to follow the right *cough* typed path! ;)
It's important to handle (semi-)arbitrary typed collections too, I admit tho' it **is** a specific use-case so forgive me for being so jumpy with it (`Json::Type` in code example gave me a hint).
