### ISSUE TITLE
Vim cursor disappears after running crystal scripts in Vim subshell

### ISSUE THREAD

**Issue by chaniks** [crystal-lang/crystal#3367] opened 2016-09-30 07:35 UTC
Mac OS X 10.11.6 / Crystal 0.19.2 and master

### Reproduce:

1. Run vim
2. Type `:!crystal` and press Enter
3. Press Enter

Now the cursor disappears.

### Details:

When already editing some files in Vim (not always but sometimes, usually with syntax-enabled files), some lines become invisible. (e.g. mbox file?)

In some cases, the cursor shows up again if I move the cursor with keyboard, but sometimes it doesn't.

Running ***crystal-compiled executables*** in Vim subshell produces the same problem.

Also tested with a fresh new account and on a different Mac machine (same OS version though), but the results were same.

### Workaround

After running the script, 

* `<CTRL+Z>` and then `fg` (return to parent shell and come back)
*  press `:` and press `<Enter>` => does not fix the vanished lines
* or any other behavior that refreshes screen or resets the cursor position of Vim.

**Comment by ozra** [comment] 2016-09-30 10:36
Cursor color commands not reset at end of crystal output?

**Comment by asterite** [comment] 2016-09-30 12:43
@chaniks Are you using [this](https://github.com/rhysd/vim-crystal)? If so, this should probably be reported there (this repository is about the compiler and standard library). Thank you!

**Comment by chaniks** [comment] 2016-09-30 12:49
@asterite Yes.  But it is not vim-crystal dependent. (The machines that don't have vim-crystal installed also produce the same result.)

**Comment by asterite** [comment] 2016-09-30 12:57
Maybe related to #2713, though I'll have to know what these crystal executables you use do (do they replace the buffer or modify it?)

**Comment by chaniks** [comment] 2016-09-30 13:00
@ozra I guess there is a little bit more.

The (visible) position of the cursor also changes, and before returning back to Vim main screen, Vim waits for user to press `Enter` and the cursor is visible at the right position.  It disappears when I get back to the main screen.

This is what I've found while research: https://github.com/mitmproxy/mitmproxy/issues/357#issuecomment-55536677

**Comment by chaniks** [comment] 2016-09-30 13:36
@asterite actually, now it does nothing at all. (I tried to narrow it down)

```bash
$ touch a.cr
$ crystal build a.cr
```

and `!./a` in Vim produces the same result.

By the way, what I was mostly worried about was that the compiler itself is also a crystal-compiled executable. Do you have to compile all from the first version again to fix this?

**Comment by RX14** [comment] 2016-09-30 14:14
@asterite Maybe the crystal stdlib shouldn't treat ttys differently until it needs to. I'm pretty sure crystal changes tty modes and settings in the stdlib by default, and I think that this should be explicit.

**Comment by chaniks** [comment] 2016-09-30 16:26
@RX14 hmm.. I don't know about the history on this, but current way of handling tty sounds ~~cute~~ good, or maybe okay. This might be just a small bug, compared to its advantages.

**Comment by chaniks** [comment] 2016-10-02 01:32
I guess I found the problem.

The bug appears 0.7.2, which introduced `STDIN`, `STDOUT`, and `STDERR` as `FileDescriptor`s in prelude. ([0.7.2:src/main.cr] which is now [master:src/kernel.cr])

It overwrites the blocking option of `fcntl` depending on `isatty`. I am not sure if it is intended and is required, but preserving the original value **seems** to fix this bug. (Please double check. I had to compile various versions of crystal in random order during the test. I cleaned it up as much as possible, but I still doubt.)

However, writing a fix for this issue may require some design considerations.  I am too new to crystal to do that.

Whoever can handle it, please go on.


[master:src/kernel.cr]: https://github.com/crystal-lang/crystal/blob/master/src/kernel.cr#L3-L5
[0.7.2:src/main.cr]: https://github.com/crystal-lang/crystal/blob/0.7.2/src/main.cr#L41-L43

**Comment by asterite** [comment] 2016-10-02 01:36
@chaniks Exactly! This is an exact duplicate of #2713, as I mentioned before, so I'm closing this. I still don't know what the fix for this is...

**Closed by asterite** 2016-10-02 01:36 UTC
