### ISSUE TITLE
0.23.0 introduces compiler bug

### ISSUE THREAD

**Issue by mixflame** [crystal-lang/crystal#4677] opened 2017-07-05 13:56 UTC
Cross post: https://github.com/Amber-Crystal/amber/issues/125

### Description

App compiles and runs perfectly fine on 0.22.0

Yet on 0.23.0 I get:

```
Error in lib/amber/src/amber/router/pipe/static.cr:15: this 'initialize' doesn't initialize instance variable '@directory_listing' of HTTP::StaticFileHandler,
                  with Amber::Pipe::Static < HTTP::StaticFileHandler, rendering it nilable
```

Any insight on what causes this error?

For reference:
[lib/amber/src/amber/router/pipe/static.cr](https://github.com/Amber-Crystal/amber/blob/master/src/amber/router/pipe/static.cr)

### Steps to Reproduce

1. Write an Amber app
2. Compile and run it with 0.22.0
3. Try compiling it with 0.23.0

**Expected behavior:** App should compile and run like on 0.22.0

**Actual behavior:** ```amber w```, ```amber r```, and ```crystal run src/myapp.cr``` won't work.

**Reproduces how often:** 100%

### Versions

```Amber CMD (ambercr.io) - v0.1.15```

```Darwin Jonathans-MacBook-Pro-2.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64```

```Linux mixflame 4.9.15-x86_64-linode81 #1 SMP Fri Mar 17 09:47:36 EDT 2017 x86_64 GNU/Linux```

```
Crystal 0.22.0 (2017-04-20) LLVM 4.0.0
```

```
Crystal 0.23.0 [3c3d3e2] (2017-06-28) LLVM 3.8.1
```

```
Crystal 0.23.0 (2017-06-30) LLVM 4.0.1
```

**Comment by sdogruyol** [comment] 2017-07-05 13:58
This is actually not a bug in Crystal but a breaking change. This should be an issue for Amber to support Crystal 0.23.0 //cc @elorest

**Comment by mixflame** [comment] 2017-07-05 13:59
Thanks @sdogruyol. Can you link to the change?

**Comment by sdogruyol** [comment] 2017-07-05 14:10
This is now actually fixed in https://github.com/Amber-Crystal/amber/pull/126 😄 . @mixflame can you close this issue?

**Closed** 2017-07-05 14:10 UTC

**Comment by RX14** [comment] 2017-07-05 14:17
I don't think crystal actually makes any guarantees on the stability of it's internals. After 1.0.0 we'll have to make the distinction of classes which should be extended and must remain compatible internally and classes which should not. I actually can't think of any classes which must remain stable, at least after we switched `HTTP::Handler` to a module.
