### ISSUE TITLE
Instanciating abstract class

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#4334] opened 2017-04-24 17:50 UTC
It's possible, with indirect syntaxing :

```crystal
abstract class A; end

class Test
  class_property i_instanciate_abstract = A

  def initialize(sub_elm : A = Test.i_instanciate_abstract.new)
    pp sub_elm
  end
end

Test.new # > #<A:0x10b459fe0>
```

https://play.crystal-lang.org/#/r/1x60

It let me think that it's impossible for the compiler to know at compile time if the class is instanciable or abstract for now.
It would be great to have sort of compile time check to allow only concrete *class-as-a-variable*

example:

```crystal

@some_class : A #Any sub-class of A are allowed.

def initialize(@some_class); end

def after
  @some_class.new # Raise a compile-time error : A can be abstract, we can't use #new
end

# The solution

@some_class : concrete A #Only sub-class of A which are not abstract are allowed.

def after
  @some_class.new #It's ok now :) !
end

T.new(A) #Raise a compile time error: Allow only concrete class

```

**Comment by asterite** [comment] 2017-05-20 16:17
Duplicate of #3835

**Closed by asterite** 2017-05-20 16:17 UTC
