### ISSUE TITLE
Compiler crashes with Iterator#first an iterator in intialize

### ISSUE THREAD

**Issue by erdnaxeli** [crystal-lang/crystal#10062] opened 2020-12-09 09:34 UTC
Hi,

This code makes the compiler crash. It eats all my memory, than crashes.

```Crystal
class T
  def initialize(@a : Iterator(Int32))
	@b = Array(Int32).new
	@a.first(25).each { |x| @b << x }
  end
end

a = (0..99).each
t = T.new(a)

puts t
```

I am not sure if it is related to #9924 .

This one works:
```Crystal
class T
  def initialize(@a : Iterator(Int32))
	@b = Array(Int32).new
    25.times do
      x = @a.next
      break if x.is_a?(Iterator::Stop)
      @b << x
    end
  end
end
```

**Comment by asterite** [comment] 2020-12-09 11:49
Sorry, right now you can't have an instance variable of type Iterator.

Duplicate of https://github.com/crystal-lang/crystal/issues/7044

**Comment by erdnaxeli** [comment] 2020-12-09 12:32
But I do have an instance variable of type iterator. In both examples, `@a` is an Iterator :thinking:

**Comment by straight-shoota** [comment] 2020-12-09 12:38
It works fine when you use `a` as a local variable instead of an ivar.
Reduced example:
```cr
class Foo
  def initialize(@a : Iterator(Int32))
	@a.each { } # Make this `a.each { }` and it compiles
  end
end

Foo.new((0..99).each)
```

**Closed** 2020-12-09 12:38 UTC

**Comment by asterite** [comment] 2020-12-09 12:53
> But I do have an instance variable of type iterator. In both examples, @a is an Iterator

That's what I said. You **can't** have an instance variable of such type yet. Well, you can, but it leads to a crash. I should have said "You can't **practically** have an instance variable of such type yet because it will crash the compiler".

**Comment by erdnaxeli** [comment] 2020-12-09 13:24
I don't understand. I do have an instance variable that is an iterator. And I can use it in some ways (calling `next` or `each(&block)` on it) but not on others (calling `first`). I feel like the problem is not really having an instance variable which is an iterator, but that **and** some usage. Something like "methods returning a wrapping iterator don't work, the rest is ok".

@straight-shoota that is event weirder oO
Also I can use instance variables without the `@`?

**Comment by asterite** [comment] 2020-12-09 13:26
It's explained in https://github.com/crystal-lang/crystal/issues/7044#issuecomment-528823407 and it depends on what methods you end up calling on Iterator.

**Comment by erdnaxeli** [comment] 2020-12-09 13:40
Yeah I read it… and I can't say I fully understand :sweat_smile: 

But anyway thanks :)
