### ISSUE TITLE
Inconsistent closure type inference with conditional branch type restriction

### ISSUE THREAD

**Issue by rumenzu** [crystal-lang/crystal#7817] opened 2019-05-23 12:03 UTC
```crystal
def foo
  yield
end

bar = rand > 0.5 ? 42 : nil
if b = bar
  c = ->() { puts "hello #{b.succ}" } # => undefined method 'succ' for Nil (compile-time type is (Int32 | Nil))
  foo(&c)
end
```

Since `b` is restricted to `Int32` in this condition branch, the closure should also capture it as an `Int32`, not `(Int32 | Nil)`.

Probably related to: #6037

**Comment by asterite** [comment] 2019-05-23 12:08
Duplicate of #3093

**Closed by asterite** 2019-05-23 12:08 UTC

**Comment by asterite** [comment] 2019-05-23 12:12
@rumenzu No problem, it serves as a count of how many people are affected by the bug :-)
