### ISSUE TITLE
Compilation dependency issue on Debian 9

### ISSUE THREAD

**Issue by elrok123** [crystal-lang/crystal#4911] opened 2017-09-01 16:51 UTC
Getting a strange compilation error, but I think it's probably related to the Mongo.cr lib dependencies, as I'm struggling to suss out what's wrong, I've installed all of the libs it seems to be complaining about. For reference the mongo lib I'm using in particular is this one:
[Mongo.cr](https://github.com/datanoise/mongo.cr)

```$ crystal build --no-debug ./mxmongo.cr
/usr/bin/ld: /opt/crystal/embedded/lib/../lib/libgc.a(os_dep.o): undefined reference to symbol '_end'
//usr/lib/x86_64-linux-gnu/libyajl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/home/conner/itags/step1/cronMongoCampaignRebuild/mxmongo'  -rdynamic  `command -v pkg-config > /dev/null && pkg-config --libs libcrypto || printf %s '-lcrypto'` -lmongoc-1.0 -lbson-1.0 -lpcre -lm -lgc -lpthread /opt/crystal/src/ext/libcrystal.a -levent -lrt -ldl -L/usr/lib -L/usr/local/lib`
```

The version of the compiler I'm using is:
```
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1
```

Here is my shards file as well, for reference:
```
name: *****
version: 0.1.0

authors:
  - ******
targets:
  mxmongo:
    main: src/mxmongo.cr

dependencies:
  redis:
    github: stefanwille/crystal-redis
    version: 1.8.0
  db:
    github: crystal-lang/crystal-db
    version: 0.4.2
  mysql:
    path: lib/crystal-mysql
  chalk_box:
    github: azukiapp/crystal-chalk-box
  mongo:
    github: datanoise/mongo.cr
    branch: master
version: 0.2.0

crystal: 0.22.0

license: MIT
```

Debian version details:
```
Linux ******** 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
```

Any help would be greatly appreciated, and if you need further details please don't hesitate to ask. Apologies if I have posted this in the wrong place as it maybe should be posted under mongo.cr, but wasn't 100% sure if it was the mongo lib causing it.

**Comment by asterite** [comment] 2017-09-01 16:52
Duplicate of #1269

**Closed** 2017-09-01 17:15 UTC
