### ISSUE TITLE
Crystal bug while compiling

### ISSUE THREAD

**Issue by Polands-in-the-sky** [crystal-lang/crystal#6183] opened 2018-06-12 01:47 UTC
I was using the Crystal compiler the first time on Windows Subsystem for Linux(Ubuntu) and got the following error. How can I fix that?

`Poland@Poland:/mnt/e/kurwa/руст$ crystal hello.cr
String contains null byte
???
???
???
???
???
???
???
???

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues`
```

**Comment by straight-shoota** [comment] 2018-06-12 08:00
We'll need to see the source code you try to compile in order to help you.

**Comment by straight-shoota** [comment] 2018-06-12 09:36
I can't reproduce this error.

What Crystal version are you using and which operating system version?

Tip: Use triple backticks and put them on a separte line for block code format. Add `crystal` after the opening backticks to get syntax highlighting.

**Comment by ZaWertun** [comment] 2018-06-15 10:11
It's duplicate of #5348 (see also #5799). It's not fixed in 0.25 yet.

**Comment by bcardiff** [comment] 2018-06-15 10:27
@ZaWertun #5350 which is referenced for those issues is included in 0.25.0

**Comment by ZaWertun** [comment] 2018-06-15 10:44
@bcardiff Sorry, it's really fixed, looks like I'm using version older then 0.25 for tests.

**Comment by bcardiff** [comment] 2018-06-15 10:53
It's great to confirm it works for you in 0.25. I'm wanted to double check.

**Closed** 2018-06-18 14:37 UTC
