### ISSUE TITLE
HTTP Server + OpenSSL seems to not close handles in case of connection failure

### ISSUE THREAD

**Issue by rdp** [crystal-lang/crystal#3953] opened 2017-01-29 04:55 UTC
I seem to be seeing a leak using http/server + TLS

```
$ cat use_it_ssl.cr
require "http/server"

context = OpenSSL::SSL::Context::Server.new
context.private_key = "key.pem"
context.certificate_chain = "cert.pem"

server = HTTP::Server.new("0.0.0.0", 8081) do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world!"
  puts "hello #{context}"
end
server.tls = context
puts "Listening on https://:8081"
server.listen
```

start it, then run this script to simulate an "aborted" connection attempt:
```

$ cat attach_bad.rb
require 'socket'
s = TCPSocket.new ARGV[1] || 'localhost', ARGV[0]
puts s.addr[1] # output port
Process.kill("KILL", Process.pid)
```

with HTTP (i.e. the tls context line commented out) I get the following behavior, which I believe is expected:

```
$ ruby attach_bad.rb 8081
39284
Killed
$ sudo netstat -anp | grep 8081
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      11805/crystal-run-u
tcp        0      0 127.0.0.1:39284         127.0.0.1:8081          TIME_WAIT   -
```

with tls enabled:

```
$ ruby attach_bad.rb 8081
39285
Killed
rdp@canary-big-now:~/temp$ sudo netstat -anp | grep 8081
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      11940/crystal-run-u
tcp        0      0 127.0.0.1:39285         127.0.0.1:8081          FIN_WAIT2   -
tcp        0      0 127.0.0.1:8081          127.0.0.1:39285         CLOSE_WAIT  11940/crystal-run-u
```

the socket appears to enter CLOSE_WAIT and only actually be closed much later, possibly this behavior is unexpected.

Cheers!

**Comment by rdp** [comment] 2017-02-02 01:18
Interestingly, GC does seem to clean these up "eventually" so it's not a game killer.
 
Also (possibly related) if you run this ruby script against a TLS crystal server:

`loop { system("wrk -d 1  https://localhost:8081") }
`
eventually the server will die with `accept: Too many open files (Errno)`

lsof seems to show about 1000 open handles of type "sock" whatever that even means: 

`use_it_ssl 8064  name  776u  sock        0,8      0t0 134356327 can't identify protocol`

**Comment by rdp** [comment] 2017-02-02 02:00
(github won't let me edit previous comment).  Anyway I was able to reproduce the "sock" failure on ubuntu 16.10.  It doesn't seem to be a problem on OS X however, though RAM usage seems to grow slowly, FWIW.  HTTP seems fine.

**Comment by bararchy** [comment] 2017-02-02 04:39
You just need to increase your allowed number of open files (ulimit , sysctl , limits.conf)

**Comment by rdp** [comment] 2017-02-02 19:45
Here is a trace for the initial failure

```
Unhandled exception in spawn:
SSL_accept: Unexpected EOF (OpenSSL::SSL::Error)
0x1092d64f2: *CallStack::unwind:Array(Pointer(Void)) at ??
0x1092d6491: *CallStack#initialize:Array(Pointer(Void)) at ??
0x1092d6468: *CallStack::new:CallStack at ??
0x1092d32d1: *raise<OpenSSL::SSL::Error>:NoReturn at ??
0x1093a512a: *OpenSSL::SSL::Socket::Server#initialize<TCPSocket+, OpenSSL::SSL::Context::Server, Bool>:Nil at ??
0x1093a509e: *OpenSSL::SSL::Socket::Server::new:sync_close<TCPSocket+, OpenSSL::SSL::Context::Server, Bool>:OpenSSL::SSL::Socket::Server at ??
0x109396da8: *HTTP::Server#handle_client<(TCPSocket+ | Nil)>:Nil at ??
0x1092d4be6: ~procProc(Nil)@//crystal/src/http/server.cr:148 at ??
0x1092e0a84: *Fiber#run:(IO::FileDescriptor | Nil) at ??
0x1092d2179: ~proc2Proc(Fiber, (IO::FileDescriptor | Nil))@/crystal/src/fiber.cr:29 at ??
```

from some examination, appears to be blowing up in the call to 
` io = OpenSSL::SSL::Socket::Server.new(io, tls, sync_close: true)`

in server.cr

which line isn't in the try finally block to ensure the io is afterward closed, seemingly...

So I suppose multiple ways to fix it, not sure the right way...here's a hacky one, for followers:

https://gist.github.com/rdp/7ed933de9180c13295793d2ace89e619

Sadly, this did not fix memory leaks, or socket leak, will open separate issue for those.

**Comment by ysbaddaden** [comment] 2017-02-02 20:42
Thanks for the reproducible code and investigation! The problem is that we don't close the underlying IO when the SSL handcheck fails. Since the socket is left in an indeterminate state, we should just close it, at least if `sync_close` is truthy. For example the following avoids the `FIN_WAIT2` state:

```crystal
unless LibSSL.ssl_accept(@ssl) == 1
  io.close if sync_close
  raise OpenSSL::SSL::Error.new(@ssl, ret, "SSL_accept")
end
```

**Comment by rdp** [comment] 2017-02-05 01:28
That seems to fix it, and is much better :)

**Closed** 2017-02-10 18:50 UTC
Labels: kind:bug, topic:stdlib

**Comment by codenoid** [comment] 2017-07-15 09:27
how to fix it ? i  just run wrk with c60000 and same, i got
`accept: Too many open files (Errno)`

**Comment by bararchy** [comment] 2017-07-15 09:39
@codenoid how many handler are open ? Is it an SSL connection ? What is your nofile configuration in /etc/security/limits.conf ?
