### ISSUE TITLE
Interpreter: simple spec test raises `unreachable` error

### ISSUE THREAD

**Issue by cyangle** [crystal-lang/crystal#12218] opened 2022-07-08 02:52 UTC
Given a really simple spec test file:
```crystal
require "spec"

it "tests" do
  ("a" == "b").should eq(false)
end

```

Interpreting it gives below error:
```
In: Spec::Context+#report
Node: raise "unreachable"
Reached the unreachable (Exception)
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/interpreter.cr:342:7 in 'interpret'
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/interpreter.cr:240:13 in 'interpret'
  from /home/chao/git/personal/crystal/src/compiler/crystal/interpreter/repl.cr:146:5 in 'repl'
  from /home/chao/git/personal/crystal/src/compiler/crystal/command.cr:100:7 in '__crystal_main'
  from /home/chao/git/personal/crystal/src/crystal/main.cr:115:5 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from /home/chao/git/personal/crystal/.build/crystal in '_start'
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Debugging tests is a major use case of the interpreter.

System info:
```
Crystal 1.5.0 [994c70b10] (2022-07-06)

LLVM: 14.0.6
Default target: x86_64-pc-linux-gnu

OS: Ubuntu 22.04
```

**Comment by cyangle** [comment] 2022-07-08 03:34
Below patch bypasses this interpreter bug:
```diff
diff --git a/src/spec/example.cr b/src/spec/example.cr
index 01f46a6fa..ff548499e 100644
--- a/src/spec/example.cr
+++ b/src/spec/example.cr
@@ -43,7 +43,7 @@ module Spec
     private def internal_run(start, block)
       @parent.run_before_each_hooks
       block.call
-      @parent.report(:success, description, file, line, Time.monotonic - start)
+      @parent.as(Spec::RootContext).report(:success, description, file, line, Time.monotonic - start)
     rescue ex : Spec::AssertionFailed
       @parent.report(:fail, description, file, line, Time.monotonic - start, ex)
       Spec.abort! if Spec.fail_fast?
```

**Comment by asterite** [comment] 2022-07-08 12:59
Duplicate of #11782

**Closed by asterite** 2022-07-08 12:59 UTC
Labels: kind:bug, topic:compiler:interpreter
