### ISSUE TITLE
Confusing error when calling typeof on macro

### ISSUE THREAD

**Issue by r00ster91** [crystal-lang/crystal#7010] opened 2018-10-31 14:23 UTC
```cr
macro mac
end
typeof(mac)
```
results in:
```
Error in line 3: macro 'mac' must be defined before this point but is defined later
```
Actually the macro `mac` *is* defined before this point so this error doesn't make much sense.

**Comment by HertzDevil** [comment] 2021-08-06 04:28
Duplicate of https://github.com/crystal-lang/crystal/issues/6536#issuecomment-740639489.

**Closed by HertzDevil** 2021-08-06 04:28 UTC
