### ISSUE TITLE
Error only when #map's block is delimited with `do` .. `end`

### ISSUE THREAD

**Issue by alainravet** [crystal-lang/crystal#2535] opened 2016-04-30 07:37 UTC
`#map{..}` and `#map do .. end` are equivalent :

```
arr = [1, 2]
a = arr.map {|i| i.to_s}.join        # "12"
b = arr.map do |i| i.to_s end.join   # "12"
```

but replace `a = ` by `puts ` and only `{..}` compiles in the code below
```
puts arr.map {|i| i.to_s}.join       # "12"

puts arr.map do |i| i.to_s end.join
'Array(Int32)#map' is expected to be invoked with a block, but no block was given
```

**Comment by kumpelblase2** [comment] 2016-04-30 07:52
Workaround: Assigning to a variable works. https://carc.in/#/r/xpt

**Comment by lbguilherme** [comment] 2016-04-30 10:19
`method {...}` and `method do ... end` are not really equivalent. When you have a method chain without parenteses, this happens:

```crystal
puts arr.map {|i| i.to_s }.join        # read as   puts(arr.map() {|i| i.to_s }).join
puts arr.map do |i| i.to_s end.join    # read as   puts(arr.map()) {|i| i.to_s }.join
```

A `do` block refers to the most far method, in this case `puts`. But `{}` refers to the closest one, and works as intended.

You will need to do this:

```crystal
puts(arr.map do |i| i.to_s end.join)
```

Or this:

```crystal
arr.map do |i| i.to_s end.join.tap {|x| puts x }
```

**Comment by alainravet** [comment] 2016-04-30 11:29
@lbguilherme 
It's consistent with Ruby (see example below). 
The question is: does it make the most sense in this case?

```
# in Ruby
arr = [1, 2]
puts  (arr.map do |i| i.to_s end.join )  # 12
puts   arr.map do |i| i.to_s end.join    # NoMethodError: undefined method ‘join’ for nil:NilClass
```

**Comment by asterite** [comment] 2016-04-30 15:00
I've updated the [docs](http://crystal-lang.org/docs/syntax_and_semantics/blocks_and_procs.html) to explain the difference between `do ... end` and `{ ... }`. We won't change this behaviour.

**Closed by asterite** 2016-04-30 15:00 UTC
