### ISSUE TITLE
Assignment required for type restriction when using OptionParser

### ISSUE THREAD

**Issue by j8r** [crystal-lang/crystal#7851] opened 2019-06-02 14:29 UTC
This code requires to assign a new variable to restrict the type. Usually it isn't required, but here it is:

```cr
require "option_parser"

cmd : String? = nil

OptionParser.parse! do |parser|
  parser.on("-u CMD", "--u CMD") { |command| cmd = command }
end

if cmd
  # Should be String
  puts typeof(cmd) #=> String | Nil
  # Fails
  # cmd + " "
end
```
I suspect to be related to Proc passing (https://github.com/crystal-lang/crystal/blob/master/src/option_parser.cr#L112)

**Comment by jhass** [comment] 2019-06-04 08:47
Yes, it's due to proc passing. Do you know an alternative implementation that avoids this? Otherwise it's by design. We could talk about marking procs as not run asynchronously or something, but I think that's post 1.0 talk :)

**Comment by straight-shoota** [comment] 2019-06-04 18:38
Theoretically, the compiler might be smart enough to figure out that `cmd` can't be set to `nil` from the closure context. But that's probably going to add a lot of complexity.
This is similar to #6041.

**Comment by bcardiff** [comment] 2019-06-04 23:07
I would close this as a duplicate of #6041. 

Once a proc is captured there is no way in the language semantics to restrict when / if / how-many-times it will be executed. Unless there is some notion of ownership or lifecycle of the Proc it won't happen.

**Closed** 2019-06-05 00:12 UTC
Labels: status:duplicate
