### ISSUE TITLE
Time zones read from Windows Registry lack historic DST rules

### ISSUE THREAD

**Issue by straight-shoota** [crystal-lang/crystal#14563] opened 2024-05-04 14:58 UTC
Windows has time zone information available in the registry. We reading that data, but only the currently active rules and extrapolate them to historic and future dates. This is error prone because DST rules tend to change over time.

Historical data is available in the `Dynamic DST` key under a time zone entry.

https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/ns-timezoneapi-dynamic_time_zone_information

**Comment by HertzDevil** [comment] 2024-05-04 15:45
Duplicate of #13518?

**Closed** 2024-05-05 08:24 UTC
Labels: kind:bug, status:discussion, platform:windows, topic:stdlib:time
