### ISSUE TITLE
Better Type Unions

### ISSUE THREAD

**Issue by neelsudhakaran** [crystal-lang/crystal#13225] opened 2023-03-25 03:05 UTC
## Discussion
_**Disclaimer:** New Crystal developer, so this issue may lack a deeper understanding of the language. (P.S.—loving it so far!)_
- What aspect of the language would you like to see improved?
_Union Types are very wonky at the moment, especially in "complex" data structures._
- What are the reasons?
_If you type a variable as a complex data type—say as an array or a map—you cannot assign it to a "pure valued" data structure even if logically it is valid._
- Include practical examples to illustrate your points.
_The following example wouldn't work because you are trying to assign purely `Int32` or `Float64` hashes into a union hash. Logically however, all of the below hashes should be valid under the union. The same thing applies for arrays, and probably more data types that I simply haven't tried this with yet._

```cr
map : Hash(String, Int32 | Float64) = {
    "A" => 0,
    "B" => 0.5,
    "C" => 1,
    "D" => 1.5
}

map = {
    "A" => 0.1,
    "B" => 0.2,
    "C" => 0.3,
    "D" => 0.4
}

map = {
    "A" => 0,
    "B" => 4,
    "C" => 6,
    "D" => 8
}
```
- Optionally add one (or more) proposals to improve the current situation.
_I've never coded a compiler before, but perhaps for union types with complex data structures, rather than comparing the raw data type, you do some kind of a recursive check to see that all values within it fit the union type spec? It sounds kind performance costly, I guess, but I presume this is what other languages (e.g. TypeScript) do?_

**Comment by Blacksmoke16** [comment] 2023-03-25 03:17
You can accomplish this by being more explicit with your hash literal to tell the compiler that it allows values/keys other than those in the literal.

```cr
map = {
    "A" => 0.1,
    "B" => 0.2,
    "C" => 0.3,
    "D" => 0.4
} of String => Int32 | Float64
```

or

```cr
map = Hash(String, Int32 | Float64){
    "A" => 0,
    "B" => 4,
    "C" => 6,
    "D" => 8
}
```

**Comment by straight-shoota** [comment] 2023-03-25 10:20
Duplicate of #9797.
The underlying issue isn't actually union types, this is an application for covariance/contravariance which is tracked in #3803.

**Closed by straight-shoota** 2023-03-25 10:20 UTC
Labels: status:discussion, topic:lang:type-system

**Comment by neelsudhakaran** [comment] 2023-03-25 17:35
Thank you! I appreciate the help :)
