### ISSUE TITLE
compile bug around subclassing generic class

### ISSUE THREAD

**Issue by pbrumm** [crystal-lang/crystal#10352] opened 2021-02-02 00:52 UTC
I found this long running issue  but don't see the exact scenario.    
https://github.com/crystal-lang/crystal/issues/2665

I am trying to use the generics to store an array of the parent class type and hitting compile bug.

even overwriting the add in the subclass doesn't fix the issue.

```
class Animal(T)
  @arr = Array(Animal(T)).new

  def add(a = Animal(T))
    @arr << a
  end
end

class Dog(T) < Animal(T)
end

a = Dog(UInt32).new
a.add(Dog(UInt32).new)
```

BUG: trying to assign Array(Animal(UInt32)) <- Array(Animal(T)) (Exception)
  from /crystal/src/compiler/crystal/codegen/cast.cr:274:5 in 'assign_distinct'
  from /crystal/src/compiler/crystal/codegen/cast.cr:85:7 in 'assign'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:1952:11 in 'run_instance_vars_initializers_non_recursive'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:1923:9 in 'allocate_aggregate'
  from /crystal/src/compiler/crystal/codegen/primitives.cr:708:5 in 'codegen_primitive_allocate'
  from /crystal/src/compiler/crystal/codegen/primitives.cr:27:15 in 'codegen_primitive'
  from /crystal/src/compiler/crystal/codegen/call.cr:440:7 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2179:9 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:619:9 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2184:7 in 'codegen_fun'
  from /crystal/src/compiler/crystal/codegen/fun.cr:51:3 in 'target_def_fun'
  from /crystal/src/compiler/crystal/codegen/call.cr:445:5 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2179:9 in 'visit'
  from /crystal/src/compiler/crystal/syntax/visitor.cr:27:12 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:619:9 in 'accept'
  from /crystal/src/compiler/crystal/codegen/codegen.cr:2149:7 in 'codegen'
  from /crystal/src/compiler/crystal/compiler.cr:172:16 in 'compile'
  from /crystal/src/compiler/crystal/command.cr:210:5 in 'run_command'
  from /crystal/src/compiler/crystal/command.cr:117:7 in 'run'
  from /crystal/src/compiler/crystal.cr:11:1 in '__crystal_main'
  from /crystal/src/crystal/main.cr:110:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'

If I don't instanciate the instance variable and move it to initializer it works correctly.

```
class Animal(T)
  @arr : Array(Animal(T))

  def initialize
    @arr = Array(Animal(T)).new
  end

  def add(a = Animal(T))
    @arr << a
  end
end

class Dog(T) < Animal(T)
end

a = Dog(UInt32).new
a.add(Dog(UInt32).new)
```

**Comment by bcardiff** [comment] 2021-02-02 15:57
FYI the methods should use `:`, not `=` to indicate the type restriction.

```diff
--- def add(a = Animal(T))
+++ def add(a : Animal(T))
```

---

The bug is how ivars initializers in generic types are handled, but the workaround is to do the initialization in the initialize method manually.

**Comment by pbrumm** [comment] 2021-02-02 17:57
sorry, my example had a bug.    

thanks for the quick response.  I will continue along with initializing var in initiallize.

**Comment by HertzDevil** [comment] 2021-05-20 09:46
Reduced:

```crystal
class A(T)
end

class B(T)
  @x = A(T).new
end

class C(T) < B(T)
end

C(Int32).new # BUG: trying to assign A(Int32) <- A(T) (Exception)
```

Duplicate of #4753.

**Closed** 2021-05-22 10:22 UTC
Labels: kind:bug, topic:compiler:generics
