### ISSUE TITLE
`TCPSocket.closed?` not working when remote is closing

### ISSUE THREAD

**Issue by CodeSteak** [crystal-lang/crystal#3058] opened 2016-07-27 22:17 UTC
The method `TCPSocket.closed?` does not give right results when the connection was closed at the remote socket. 

Example:
```crystal
require "socket"

server = TCPServer.new "127.0.0.1", 9123

spawn do
  client = TCPSocket.new "127.0.0.1", 9123
  client.close
end

sock = server.accept
sleep 1 # Wait for client to close
puts sock.read_byte == nil # true 
puts sock.closed? # is false ; should be true
```
Tested on master.

**Comment by asterite** [comment] 2016-07-27 22:20
`sock.read_byte == nil` means the socket was closed by the remote end. `closed?` tells you if you closed the client.

You can try this in Ruby with the same results:

```rb
require "socket"

server = TCPServer.new "127.0.0.1", 9123

Thread.new do
  # spawn do
  client = TCPSocket.new "127.0.0.1", 9123
  client.close
end
# end

sock = server.accept
sleep 1 # Wait for client to close
p sock.gets # => nil
p sock.closed? # => false
```

I think this is expected behaviour, but I might be wrong.

**Comment by CodeSteak** [comment] 2016-07-27 23:06
Ohh.. Hmmm...
Now I also tested it in Java. Same behaviour as Crystal and Ruby. 

But I still think this is unexpected and could lead to programming bugs with dead sockets.

On the other hand you will probably notice that a socket is closed when reading or wrinting to it.

**Comment by asterite** [comment] 2016-07-27 23:18
I think the fact that we all implement it this way is because you can't know if the other end closed the socket unless you try to read from it, but I can be wrong. So the problem could be at the protocol level. I don't know if the remote endpoint can send a shutdown packet or something like that...

**Comment by CodeSteak** [comment] 2016-07-27 23:27
There could be two ways in implementing it :
1. You could just update `@closed` in `IO::FileDescriptor` when reading or writing fails.
2. You could also do this [trick](http://stackoverflow.com/questions/17705239/is-there-a-way-to-detect-that-tcp-socket-has-been-closed-by-the-remote-peer-wit).

**Comment by ysbaddaden** [comment] 2016-07-27 23:28
You can't know the state of a socket, at least at the POSIX level. You must try to read or write from it for its state to be discovered. Maybe the TCP protocol level is capable to know whether a connection is alive or not (I doubt it) but even if we could, it would still be prone to race conditions or the connection could get broken (not closing properly) resulting in an EPIPE errno that must be dealt with.

**Comment by CodeSteak** [comment] 2016-07-27 23:36
Maybe you are right.

Thank you for the explanations. :+1:

**Closed** 2016-07-28 08:42 UTC
