### ISSUE TITLE
Scroll lock on API docs in Safari

### ISSUE THREAD

**Issue by paddor** [crystal-lang/crystal#3123] opened 2016-08-09 04:12 UTC
After browsing the [API docs](https://crystal-lang.org/api/0.18.7/) for a few days using Safari, I noticed a reocurring pattern: After going back in browser history, the scrolling is often locked and I need to reload the page before I can scroll anywhere.

Haven't tried it with another browser though. Any ideas?

**Comment by drosehn** [comment] 2016-08-09 15:59
Seems to me that I've seen that in the past (probably with safari on MacOS Yosemite).  But I haven't been able to recreate it right now when I'm trying it in Opera on MacOS.

**Comment by david50407** [comment] 2016-08-09 17:06
Safari on El Capitan also has this problem

**Comment by asterite** [comment] 2016-08-09 17:17
It also happens on Chrome, seems to be an issue with WebKit. Not that the issue is WebKit, but we are doing something wrong... I don't know if it's some JS or CSS fault.

**Comment by drosehn** [comment] 2016-08-09 17:50
Hmm.  I do very little work on web pages, but sometimes I have used iCab on MacOS when I am debugging web pages.  It has a little "smiley face" checker, which shows a smile if the page is good and a frown if iCab notes some mistakes on the page.  If you click on the frowning-face iCab will tell you what it thinks is wrong with the page.  There are times when this has been very useful to me.  However I'm not sure that the author (Alexander Clauss) has been updating it for the latest in CSS, etc.  iCab is at:

[http://www.icab.de/](http://www.icab.de/)

and while it does show a few warnings on the web pages for the Crystal API's, they don't seem to be all that bad.  Certainly nothing that seems tied to scrolling.  If you click on some "[View source]" page (which opens a page on github), then iCab lists many more warnings for those pages.  But those open in a separate window or tab, so I don't see how any errors there would cause scroll-lock errors back on the API-doc pages.

**Comment by samueleaton** [comment] 2016-11-10 13:03
I wonder if this is a problem with "swiping" or just scrolling down in general. When this happens, can you still click in the page and use the arrow keys to scroll? If so then this would seem like a problem with the browser not recognizing scrolling swipe gestures.

**Comment by Maroo-b** [comment] 2019-04-13 11:12
Is this still an issue? It's not reproducible with macOS Mojave.

**Comment by paddor** [comment] 2019-04-13 12:28
I don’t know. I don’t own a working Mac these days.

**Comment by bcardiff** [comment] 2019-04-13 15:33
Seems to be fixed so far. Closing for now. Thanks @Maroo-b and @paddor.

**Closed by bcardiff** 2019-04-13 15:33 UTC
Labels: kind:bug, kind:docs
