### ISSUE TITLE
Need improve the error output when user type incorrect type.

### ISSUE THREAD

**Issue by zw963** [crystal-lang/crystal#13575] opened 2023-06-18 17:44 UTC
Check following example:

```crystal
class Foo
  property x = [] of String | Integer
end

foo = Foo.new
```

will get error like this:

```
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'property'

Code in 2.cr:2:3

 2 | property x = [] of String | Integer
     ^
Called macro defined in macro 'macro_140331473620992'

 630 | macro property(*names, &block)

Which expanded to:

 > 2 |         
 > 3 |           
 > 4 |             @x = [] of String | Integer
                   ^-
Error: can't infer the type of instance variable '@x' of Foo

Could you add a type annotation like this

    class Foo
      @x : Type
    end

replacing `Type` with the expected type of `@x`?
```

## the expected behavior:

It should point out user typing wrong type, like this:

```
 > 2 |         
 > 3 |           
 > 4 |             @x = [] of String | Integer
                                       ^-
Error: undefined constant Integer
```

The same issue happen on other cases, e.g.

```crystal
class Myip
  getter chan = Channel(Integer).new
end

myip = Myip.new

```

------------

```sh
 ╰─ $ 1  crystal version
Crystal 1.8.2 [7aa5cdd86] (2023-05-09)

LLVM: 15.0.7
Default target: x86_64-pc-linux-gnu
```

**Comment by HertzDevil** [comment] 2023-11-01 17:58
Duplicate of #6727

**Closed by HertzDevil** 2023-11-01 17:58 UTC
Labels: kind:bug, topic:compiler
