### ISSUE TITLE
Failed to compile a very basic HTTP server with --release flag

### ISSUE THREAD

**Issue by mamantoha** [crystal-lang/crystal#8191] opened 2019-09-16 14:58 UTC
```crystal
# server.cr
require "http/server"

server = HTTP::Server.new do |context|
  context.response.content_type = "text/plain"
  context.response.print "Hello world, got #{context.request.path}!"
end

address = server.bind_tcp("127.0.0.1", 8090)

puts "Listening on http://127.0.0.1:8090"

server.listen
```

```console
crystal server.cr --release 
Module validation failed: inlinable function call in a function with debug info must have a !dbg location
  call void @__crystal_raise_overflow()
inlinable function call in a function with debug info must have a !dbg location
  call void @__crystal_raise_overflow()
 (Exception)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/crystal-lang/crystal/issues
```

Ubuntu 19.04.
Crystal installed from Snap store.

```console
crystal -v                         
Crystal 0.31.0-dev [d1a8e7723] (2019-09-16)

LLVM: 8.0.0
Default target: x86_64-unknown-linux-gnu
```

**Comment by asterite** [comment] 2019-09-16 15:03
@mamantoha Thanks!

@bcardiff This seems like something that should be fixed before 0.31.0 is released.

**Comment by asterite** [comment] 2019-09-16 15:16
@bcardiff this line:

https://github.com/crystal-lang/crystal/blob/d1a8e77237aa8af11a63ac4f98368d6d432cd113/src/compiler/crystal/codegen/primitives.cr#L17

seems a bit weird. It's using `name_location` if `location` is defined, but that won't always be non-nil. Additionally, it seems for calls like `+` and `-` `name_location` isn't correctly set (it's `nil`). So we should either fix that or doing `@call_location = call.name_location || call.location` seem to work fine too.

**Comment by asterite** [comment] 2019-09-16 15:25
Hm! Upon further investigating this, it seems stuff like `a += 1` will not set the `name_location` correctly. I'll try to fix it now.

**Comment by bcardiff** [comment] 2019-09-16 16:44
@asterite maybe those were part of the cases I was finding when https://github.com/crystal-lang/crystal/pull/7334#discussion_r250621065 .

In this release overflow is activated by default. For future reference, `-Ddisable_overflow` can be used if is a blocking issue and to validate if using the codegen of overflow is the cause.

**Closed** 2019-09-16 19:18 UTC
Labels: kind:bug, topic:compiler:debugger
