### ISSUE TITLE
Overloading methods arity and order matters

### ISSUE THREAD

**Issue by naqvis** [crystal-lang/crystal#12853] opened 2022-12-18 15:25 UTC
Overloading a method with arity higher than successor definition causes compiler to fail with `wrong number of arguments ...` ,  fix is to re-order the overloads with lower arity definition first.

```crystal
module Foo
  def self.foo(a, b, c, d, e = false)
    puts a, b, c, d, e
  end

  def self.foo(a, b, c, d = false)
    puts a, b, c, d
  end
end


Foo.foo(1,2,3,4,true)
```

above snippet will fail with 

```
error in line 12
Error: wrong number of arguments for 'Foo.foo' (given 5, expected 3..4)

Overloads are:
 - Foo.foo(a, b, c, d = false)
 ```

playground link: https://carc.in/#/r/e9as

**Comment by Blacksmoke16** [comment] 2022-12-18 16:00
Just as extra information, it outputs the following with the `preview_overload_orde` flag:
```
$ crystal run -Dpreview_overload_order test.cr 
1
2
3
4
true
```

**Comment by HertzDevil** [comment] 2022-12-18 16:44
This is definitely a duplicate of #10231

**Comment by Blacksmoke16** [comment] 2022-12-18 18:06
Duplicate of #10231

**Closed by Blacksmoke16** 2022-12-18 18:06 UTC
Labels: kind:bug
