### ISSUE TITLE
Compiler error when using ||= in #initialize

### ISSUE THREAD

**Issue by Sija** [crystal-lang/crystal#4014] opened 2017-02-10 07:05 UTC
Provided sample shows the problem:

```cr
class Foo
  def initialize
    @bar ||= true
  end
end

Foo.new
```

Above fails with:

```
Error in line 7: instantiating 'Foo:Class#new()'

instance variable '@bar' of Foo must be Bool, not Nil

Error: instance variable '@bar' was used before it was initialized in one of the 'initialize' methods, rendering it nilable
```

See https://carc.in/#/r/1me0

**Comment by shelvacu** [comment] 2017-02-10 07:18
Isn't this the expected behaviour? It expands to `@bar = @bar || true`, and since `@bar` is not initialized it doesn't work.

**Comment by Sija** [comment] 2017-02-10 08:05
Technically it's correct, although Ruby for instance treats it just as `nil` and invokes the _else_ branch which is more intuitive to me as well.

**Comment by david50407** [comment] 2017-02-10 09:51
Crystal evaluate the type of instance variable from initializer (both `initialize` method and [catch-all initialization](https://crystal-lang.org/docs/syntax_and_semantics/methods_and_instance_variables.html)

So when Crystal saw your code above, it considered `@bar` as `Bool` from `@bar ||= true`.
(that will be treat as`@bar = @bar || true` and the only type known in the right side is `true : Bool`)

You can do this now for nilable instance variable:

```crystal
class Foo
  @bar : Bool?

  def initialize
    @bar ||= true
  end
end

Foo.new
```

**Comment by asterite** [comment] 2017-02-10 13:02
Whenever I see such code in Ruby I think "But... why?". An initializer initializes an object. There's no previous state for the object. So it doesn't make sense to do `||=` there. So basically this is equivalent, and simpler:

```crystal
class Foo
  def initialize
    @bar = true
  end
end

Foo.new
```

So here the compiler is forcing you to have simpler code. I think that's something good.

@Sija Unless there's a really strong reason you need this, I'd say to close this issue.

**Comment by asterite** [comment] 2017-02-10 20:15
I'll close this. Please reopen if you need to.

**Closed by asterite** 2017-02-10 20:15 UTC
Labels: kind:question, status:discussion, topic:compiler

**Comment by Sija** [comment] 2017-02-10 20:36
I agree, thanks for review!
