### ISSUE TITLE
Create a FreeBSD package

### ISSUE THREAD

**Issue by yonas** [crystal-lang/crystal#4185] opened 2017-03-24 11:41 UTC
Crystal looks very interesting. Can we create a package for FreeBSD?

**Comment by tosmi** [comment] 2017-08-02 07:05
i'm also interested in a freebsd package. what is the current state of freebsd support? there are packages for 0.19.x, but not for newer releases. are there any build instructions available?

**Comment by ysbaddaden** [comment] 2017-08-02 07:36
FreeBSD is supported, just like OpenBSD. We didn't update the omnibus that builds crystal releases to compile one for FreeBSD. It's also not easy to know which version(s) of FreeBSD to support —nobody in the team uses it regularly.

You can download a 0.19.x binary and use it to build a newer release. Hoping the binary is compatible with newer FreeBSD releases.

You may try to build 0.23.x directly but it's likely 0.19 won't be capable to build it (breaking changes), so you'll may want to build some intermediate versions.

Alternatively, if you have access to a Linux or macOS, you may cross compile an object file then link it on the target host, but that's more complicated.

**Comment by tosmi** [comment] 2017-08-02 09:23
ok, i'll use the 0.19 binaries and will try to build a newer version. i'm a freebsd user and could offer some help getting regular crystal builds working. i'm far from an expert but willing to learn...
i could also work on getting crystal into the freebsd ports system. i'm not a commiter but know the procedures necessary.

if you are interested just tell me where to start.

thanks
toni

**Comment by yonas** [comment] 2017-08-06 20:57
@ysbaddaden I get this error when building v0.23.1 using `crystal-0.19.4-2-freebsd10.1-x86_64.tar.gz` on FreeBSD 11.1-RELEASE.

```
# gmake
Using /usr/local/bin/llvm-config39 [version=3.9.1]         
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build  -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib                                                                                                               
Error in ./src/compiler/crystal.cr:4: while requiring "./crystal/**"                                                   

require "./crystal/**"                                     
^                                                          

in ./src/compiler/crystal/command.cr:11: while requiring "json"                                                        

require "json"                                             
^                                                          

in ./src/json.cr:70: while requiring "./json/*"            

require "./json/*"                                         
^                                                          

in ./src/json/to_json.cr:96: JSON::Builder is not a module, it's a class                                               

module JSON::Builder                                       
       ^                                                   

gmake: *** [Makefile:117: .build/crystal] Error 1          
```

**Comment by yonas** [comment] 2017-08-06 21:00
@ysbaddaden Which intermediate versions do you recommend we build to avoid the issue of breaking changes?

**Comment by tosmi** [comment] 2017-08-07 07:53
i did a build of 0.23.1 on 10.3 and 11.1. i had to compile all intermediate versions that contain breaking changes (see the releases page). so 0.19.4 -> 0.20.0 -> 0.20.1 -> 0.20.3 -> 0.20.5 -> 0.21.0 -> 0.22.0 -> 0.23.1.

i'm currently working on a [port](https://github.com/tosmi/crystal-freebsd-port) of crystal. hopefully i should have a working version by the end of this week.

**Comment by tosmi** [comment] 2017-08-07 07:57
on more note: you are using llvm 3.9 i actually had problems compiling version 0.21.0 with the 0.20.5 binary, see bug #4719. i used lvm 3.5 for all intermediate versions.

**Comment by Sija** [comment] 2017-08-07 09:07
@tosmi llvm 3.5 is buggy, see #4104.

**Comment by RX14** [comment] 2017-08-07 09:41
`--no-debug` seems to work around all the issues regarding llvm assertions. I'd recommend using that and llvm 4.0.

**Comment by sdogruyol** [comment] 2017-09-10 17:10
Can we close this? It's a known issue with LLVM

**Comment by RX14** [comment] 2017-09-10 20:59
I'm not sure, we still don't have a freebsd package, but is this the right place for this issue?

**Comment by myfreeweb** [comment] 2017-10-28 14:24
So `--no-debug` does not help with 0.20.5 building itself (or 0.21.0), with llvm 4.0.1

```
Using llvm-config40 [version=4.0.1]
CRYSTAL_CONFIG_PATH=`pwd`/src ./bin/crystal build --no-debug -o .build/crystal src/compiler/crystal.cr -D without_openssl -D without_zlib
Using compiled compiler at .build/crystal
Assertion failed: (!FnScope || SP == FnScope->getScopeNode()), function endFunction, file /wrkdirs/usr/ports/devel/llvm40/work/llvm-4.0.1.src/lib/CodeGen/AsmPrinter/DwarfDebug.cpp, line 1213.
gmake: *** [Makefile:113: .build/crystal] Abort trap (core dumped)
```

Looks like this ONLY affects 0.20.5. So the path that worked for me is 0.20.3 [llvm39] → 0.20.5 [llvm35] → 0.21.0 [llvm40].

**Comment by myfreeweb** [comment] 2017-10-28 21:47
Here's some packages!

https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/crystal-0.23.1-freebsd11.1.txz
https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/shards-0.7.1-freebsd11.1.txz

https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/crystal-0.23.1-freebsd12.0.txz
https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/shards-0.7.1-freebsd12.0.txz

And [the port used to build them](https://github.com/myfreeweb/freebsd-ports-dank/commit/e4e7a4c4913f218b6b76fda23774458c7f31cf39).

(includes https://github.com/crystal-lang/crystal/pull/5199 for 12 compatibility)

I'd like to send the port to the official ports collection eventually, so please test these :)

**Comment by yonas** [comment] 2017-12-05 12:16
@myfreeweb Awesome work!! Works for me :+1:

**Comment by papilip** [comment] 2017-12-20 07:36
@myfreeweb Génial ! It’s fine ! A big thank you !

With FreeBSD 11.1, as root:  (You can see my [gist]( https://gist.github.com/papilip/6ccab1b21202ee1b6408a441f57e432a))
```
pkg install llvm40
pkg install boehm-gc-threaded
wget https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/crystal-0.23.1-freebsd11.1.txz
wget https://unrelentingtech.s3.dualstack.eu-west-1.amazonaws.com/crystal/shards-0.7.1-freebsd11.1.txz
cd / && tar Jxvf crystal-0.23.1-freebsd11.1.txz
cd / && tar Jxvf shards-0.7.1-freebsd11.1.txz
```

**Comment by myfreeweb** [comment] 2018-02-19 13:45
The ports have been committed to the official tree! [r462317](https://svnweb.freebsd.org/ports?view=revision&revision=462317) [r462318](https://svnweb.freebsd.org/ports?view=revision&revision=462318) Soon, there will be official binary packages so you'll be able to `pkg install crystal shards`.

I'll send a PR to crystal-book with installation instructions soon.

(btw @papilip these were pkg packages, you could've `pkg add`ed them instead of using `tar`)

This issue can be closed now :)

**Closed** 2018-02-19 13:52 UTC

**Comment by RX14** [comment] 2018-02-19 16:24
@myfreeweb A few comments:
- Are you planning to remove the bootstrap compiler after the next release, and depend on the previously-built freebsd package (i'd recommend this if at all possible)
- The `pkg-message` says "When building Crystal code with the --release flag, add the --no-debug flag to avoid LLVM assertion errors." but you're building crystal with LLVM 5, so that advice is outdated. Unless that bug isn't fixed on freebsd?
- I see a few patches, are they upstreamed?

**Comment by myfreeweb** [comment] 2018-02-19 16:30
> depend on the previously-built freebsd package

Yes, of course I'm planning to do that.

> that advice is outdated

Maybe it's a different bug, but there are failures:

```
$ crystal run --release /usr/local/share/examples/crystal/tree.cr                   
Assertion failed: (cast<DISubprogram>(Scope)->describes(MF->getFunction())), function getOrCreateRegularScope, file /wrkdirs/usr/ports/devel/llvm50/work/llvm-5.0.1.src/lib/CodeGen/LexicalScopes.cpp, line 176.
zsh: abort (core dumped)  crystal run --release /usr/local/share/examples/crystal/tree.cr
```

> I see a few patches, are they upstreamed?

Yeah, it's this one: https://github.com/crystal-lang/crystal/commit/a3f2ecc30d77b8146f49fdd3564f409495765dde (upstreamed after `v0.24.1`)

**Comment by RX14** [comment] 2018-02-19 16:32
@myfreeweb that's... very strange. That's the exact same bug that we see in LLVM 3.9, but it doesn't appear to happen on LLVM 4.0+. I'm extremely surprised to see it pop up on what appears to be a compiler built on LLVM 5.0.

What's `cryatal -v` on that specific crystal compiler?

**Comment by RX14** [comment] 2018-02-19 16:56
@myfreeweb oh well. Well that's something to investigate because at least on linux the problem is solved.

Perhaps you could bisect on linux to see which commit solved it and see why it might not have been solved on freebsd. Other than that, you're stuck with the `--no-debug` workaround unfortunately.

**Comment by XaRuLa** [comment] 2018-04-17 02:36
---Shared object "libevent-2.1.so.6" not found, required by "crystal"---
i got this error on freebsd11
