### ISSUE TITLE
IO#gets is delayed by one character

### ISSUE THREAD

**Issue by BlaXpirit** [crystal-lang/crystal#3270] opened 2016-09-06 23:06 UTC
```crystal
require "http/server"

SEP = '\n'

spawn do
  HTTP::Server.new(8080) do |context|
    context.response.print p "111#{SEP}"
    context.response.flush
    sleep 0.2
    context.response.print p "222#{SEP}@"
    context.response.flush
    sleep 0.2
    context.response.print p "333#{SEP}"
  end.listen
end

HTTP::Client.get("http://localhost:8080/") do |resp|
  resp.body_io.each_line(SEP) do |line|
    puts "got #{line.inspect}"
  end
end
```

```
"111\n"
"222\n@"
got "111\n"
got "222\n"
"333\n"
got "@333\n"
```

This example shows that a line is not acknowledged until one extra character after the line separator has been received in the stream.

This causes problems for streaming protocols.

**Comment by BlaXpirit** [comment] 2016-09-06 23:23
So far I've tracked the problem to [this line](https://github.com/crystal-lang/crystal/blob/d4f50a96359fb7fafadaa42b90a43e2ffdca7e03/src/http/content.cr#L59) (gets stuck somewhere inside this call)

**Comment by asterite** [comment] 2016-09-07 00:24
@BlaXpirit Interesting! Indeed, the problem is that ChunkedContent, when it consumed a chunk, tries to read the next chunk before returning whatever was read so far. This can be problematic if the server is streaming data line by line, for example new tweets: the client will effectively receive delayed updates.

I have a fix for this with a spec, I'll soon submit it :-)

**Closed** 2016-09-07 00:29 UTC
Labels: bug, standard library

**Comment by asterite** [comment] 2016-09-07 00:30
@BlaXpirit I think that fixed it, but let me know if there's still a problem
