### ISSUE TITLE
Doc generation and custom annotations issue

### ISSUE THREAD

**Issue by anykeyh** [crystal-lang/crystal#6449] opened 2018-07-26 16:52 UTC
When a comment appears on top of attribute annotation, it won't be catch by crystal docs generation.

Example:
```crystal
    class BillingProperties
      include JSON::Serializable

      # When set to true, Requester Pays is enabled for this bucket.
      @[JSON::Field(key: "requesterPays")]
      property requester_pays : Bool
    end
```

```bash
crystal docs example.cr
```

Obviously, changing the order of the lines appears to work, however I do think the readability of the code would be impacted, further more if the comment is multi-lines.

**Comment by asterite** [comment] 2019-05-23 23:25
The actual issue is a comment on top of an annotation on top of a macro call which in turns defines a method. Comment on top of annotation on top of regular method works fine.

**Comment by asterite** [comment] 2019-05-23 23:35
Actually, the issue is that `property` expands to several things and the docs aren't copied to all of them.

**Comment by bew** [comment] 2019-05-24 04:47
I think that macros should not copy docs automatically, but add a way to insert the doc where we want, for ex:
```cr
macro foo
  {{ @doc }}
  def bar
  end
end

# some doc
foo
```
So we have precise control of where to doc is applied (and how)

**Comment by KimBurgess** [comment] 2019-10-22 17:57
I've just been taking a look at this - the issue doesn't appear to be on the macro expansion side (that I can see). To narrow the scope a little though, the same behavior occurs with the `getter` macro.

In existing setup, the expansion is:
```crystal
@var : Type

def var : Type
  @var
end
```

If this is flipped around to
```crystal
def var : Type
  @var
end

@var : Type
```
the doc generation works as intended with an without annotations.

Is there a downside to flipping these around until the root issue can be resolved?

**Comment by Blacksmoke16** [comment] 2019-10-22 18:01
Wouldn't that make the annotation apply to the method and not the ivar?

**Comment by straight-shoota** [comment] 2019-10-22 18:39
There is already a mechanism implemented in the `PropagateDocVisitor` which duplicates the doc comment of a macro to the features defined in it. A result of this is that the doc comment of a `property` macro is assigned to both the setter and getter method it defines.
So that should be all good.

It seems the issue here is just that for some reason this somehow gets mixed up when an annotation is involved, as per https://github.com/crystal-lang/crystal/issues/6449#issuecomment-495419391

**Comment by KimBurgess** [comment] 2019-10-22 18:39
@Blacksmoke16 the annotation applies to both the `InstanceVar` and `Def`(s) that these macros pump out.

**Comment by Blacksmoke16** [comment] 2019-10-22 18:44
> @Blacksmoke16 the annotation applies to both the `InstanceVar` and `Def`(s) that these macros pump out.

It only gets applied to the first type.  See https://play.crystal-lang.org/#/r/7ut6.

**Comment by KimBurgess** [comment] 2019-10-22 19:19
Ah you're absolutely right. I was thrown off by my quick test the with `JSON::Field` annotation - looks like the parser there [loads values into all ivars](https://github.com/crystal-lang/crystal/blob/cbf651affab414c0f8f02c5d4ed3c77fd69b744d/src/json/serialization.cr#L146-L162) where keys match, regardless of annotations.

**Closed** 2024-08-06 20:46 UTC
Labels: kind:bug, topic:compiler, topic:tools:docs-generator
