### ISSUE TITLE
LLVM - Assertion failed at `--release` build

### ISSUE THREAD

**Issue by oldaniel** [crystal-lang/crystal#4819] opened 2017-08-10 13:03 UTC
So my command I want to execute and the followed error message:
```
daniel@daniel-fbFED23sd:~/projects/kemal$ crystal build src/server.cr --release
crystal: /var/cache/omnibus/src/llvm/llvm-3.8.1.src/lib/CodeGen/LexicalScopes.cpp:160: llvm::LexicalScope* llvm::LexicalScopes::getOrCreateRegularScope(const llvm::DILocalScope*): Assertion `cast<DISubprogram>(Scope)->describes(MF->getFunction())' failed.
/usr/bin/crystal: line 102: 15601 Aborted                 (core dumped) "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

Infos:
- I installed crystal newly onto my system 1 hour ago, and installed all required libaries as it says in the wiki.
- `crystal run src/server.cr` works fine
- I am running Ubuntu 17.04

**Comment by bew** [comment] 2017-08-10 13:21
Can you provide the minimal source code that triggers this error?

**Comment by straight-shoota** [comment] 2017-08-10 13:23
Duplicate of #4719

**Comment by straight-shoota** [comment] 2017-08-10 13:25
As a temporary workaround until this is resolved you can just add `--no-debug` together with `--release`.

**Comment by oltmannsdaniel** [comment] 2017-08-10 13:29
My source @bew

```
require "kemal"

get "/" do
    "Hello World!"
end

Kemal.run
```

@straight-shoota Workaround works find, didn't found the other issued 😞

**Comment by Sija** [comment] 2017-08-10 14:26
@oltmannsdaniel Please close this issue, since it's a duplicate.

**Closed** 2017-08-10 14:27 UTC
