### ISSUE TITLE
Playground compiling with Logical Union and assigning variables

### ISSUE THREAD

**Issue by Daniel-Worrall** [crystal-lang/crystal#4548] opened 2017-06-11 17:21 UTC
# Reproduction
The code: 
```
false || (a = true)
a
```
in `crystal play`
v0.22.0
OS: Bash on Ubuntu for Windows (W10 Pro 64bit)
## Result
Exception of 
```
Error in line 4: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 4: instantiating 'Crystal::Playground::Agent#i(Int32)'

in line 5: undefined local variable or method 'a' (did you mean 'p'?)
```

## Meta
```
$ crystal --version
Crystal 0.22.0 [3c71228] (2017-04-20) LLVM 3.5.0
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

**Comment by asterite** [comment] 2017-06-11 17:22
In the playground, anything that declares a variable inside another expression will break.

**Comment by Daniel-Worrall** [comment] 2017-06-11 17:25
So will this just be a side-effect of using the playground or will this be eventually "fixed"?

**Comment by asterite** [comment] 2017-06-11 17:35
I can't see a way to fix this, though I didn't do the playground so @bcardiff might find a way

**Comment by bcardiff** [comment] 2017-06-14 01:15
duplicate of #4467
In that issue there are some workaround mentioned and a possible way to go to fix this.

**Closed by bcardiff** 2017-06-14 01:15 UTC
