### ISSUE TITLE
cast from Nil to Crystal::GenericInstanceType+ failed

### ISSUE THREAD

**Issue by Hamdan85** [crystal-lang/crystal#6433] opened 2018-07-23 02:35 UTC
I declared the following override:

```ruby
class Hash
  def self.recursive
   Hash(K, V).new { |hash, key| hash[key] = recursive }
  end
end
```

then called:
```ruby
foo = Hash.recursive
````

And have received a bug found message:
```
cast from Nil to Crystal::GenericInstanceType+ failed, at /private/tmp/crystal-20180630-93001-yc6bct/crystal-0.25.1/src/compiler/crystal/types.cr:1543:20:1543 (TypeCastError)
  from Crystal::TypeParameter#solve<Crystal::NonGenericClassType>:Crystal::ASTNode+
  from Crystal::GenericInstanceType+@Crystal::GenericInstanceType#replace_type_parameters<Crystal::NonGenericClassType>:Crystal::Type+
  from Crystal::TypeDeclarationProcessor#process_owner_guessed_instance_var_declaration<Crystal::Type+, String, Crystal::TypeDeclarationProcessor::InstanceVarTypeInfo>:(Crystal::MetaTypeVar | Crystal::TypeDeclarationProcessor::Error | Nil)
  from Crystal::TypeDeclarationProcessor#process_instance_vars_declarations:Nil
  from Crystal::Program#top_level_semantic<(Crystal::Expressions | Crystal::Nop)>:Tuple(Crystal::Expressions | Crystal::Nop, Crystal::TypeDeclarationProcessor)
  from Crystal::Program#semantic<(Crystal::Expressions | Crystal::Nop), Bool>:Crystal::ASTNode+
  from Crystal::Compiler#compile<Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result
  from Crystal::Command#run_command<Bool>:Nil
  from Crystal::Command#run:(Bool | Crystal::Compiler::Result | Nil)
  from main
```

**Comment by Qwerp-Derp** [comment] 2018-07-23 09:02
You can get rid of the `at` part in your issue title, pretty sure that's just the path for a temporary file anyway.

**Comment by asterite** [comment] 2018-07-23 12:12
The original code doesn't reproduce the problem.

The actual code is this:

```crystal
class Hash
  def self.recursive
    Hash(K, V).new { |hash, key| hash[key] = recursive }
  end
end

class Bar
  @foo = Hash.recursive
end
```

but that's a duplicate of #6390

I really wish people would read the instructions before submitting bug (original poster didn't search for existing issues, didn't mention crystal version, etc.) :-(

**Comment by Hamdan85** [comment] 2018-07-23 12:22
Im sorry for that.

This is my version:
```
Crystal 0.25.1 (2018-06-30)

LLVM: 5.0.2
Default target: x86_64-apple-macosx
```
But the code is really not compiling... you can see it even in your play environment:
https://play.crystal-lang.org/#/r/4l13

**Comment by asterite** [comment] 2018-07-23 12:29
I know, it's a duplicate of #6390 (the bug is known)

But once it's fixed, you'll get a (nicer) compile-time error. The code makes no sense.

**Closed** 2018-07-23 17:08 UTC
