### ISSUE TITLE
Syntax error parsing NamedTuple

### ISSUE THREAD

**Issue by hugoabonizio** [crystal-lang/crystal#3940] opened 2017-01-25 16:39 UTC
This code (from [docs](https://crystal-lang.org/docs/syntax_and_semantics/literals/named_tuple.html)) fails: https://play.crystal-lang.org/#/r/1l1q
```crystal
puts {name: "Crystal", year: 2011}
# => Syntax error in eval:1: expecting token 'CONST', not 'DELIMITER_START'
```

But this is fine: https://play.crystal-lang.org/#/r/1l1n
```crystal
puts({name: "Crystal", year: 2011})
# => {name: "Crystal", year: 2011}
```

**Comment by Sija** [comment] 2017-01-25 17:30
Code in the docs does **not** include `puts`. Compiler thinks you're passing a closure, that's why you need to enclose passed `NamedTuple` in parentheses.

**Comment by asterite** [comment] 2017-01-25 17:52
Closing as duplicate of #2746

**Closed by asterite** 2017-01-25 17:52 UTC
