### ISSUE TITLE
Turning a variable into an instance variable makes types work differently?

### ISSUE THREAD

**Issue by MistressRemilia** [crystal-lang/crystal#13378] opened 2023-04-21 22:38 UTC
```crystal
module Program
  class Base
  end

  class A < Base
    def foo(val : Int32)
      puts val
    end
  end

  class B < Base
    def foo(val : Int32)
      puts val
    end
  end

  class C < Base
  end
end

module Other
  class OtherClass
    @obj : Program::A|Program::B|Nil = nil
    def initialize
      @obj = Program::A.new
      @obj.try &.foo(42)
    end
  end
end

Other::OtherClass.new
```

For some reason, when I run the above code, the `obj` an instance variable seems to lose some of its type information.  I'm explicitly declaring it as either A, B, or Nil, but it seems to think it might be its parent class.  When I make `obj` a normal local variable, it doesn't exhibit this behavior.

This is the error I get:

```
In playground.cr:26:18

 26 | @obj.try &.foo(42)
                 ^--
Error: undefined method 'foo' for Playground::Base (compile-time type is Playground::Base+)
```

I did some searching for similar things, but I may have missed a previous issue because I wasn't exactly sure how to describe this :sweat_smile:  Sorry about that if this is a duplicate or Not A Bug.  I discovered this when working on some real code, and my temporarily solution was to just [monkey patch in](https://chiselapp.com/user/MistressRemilia/repository/benben/file?ci=3a20bb70fc93a73654f8646aaeadb88f914eb8cdbf5a4c3421a1bb1ca294523d&name=src/reverb.cr&ln=138) the never-used methods.

Crystal version v1.8.1, but I noticed it with v1.7.3 and v1.8.0 as well.

**Comment by Blacksmoke16** [comment] 2023-04-21 22:49
Duplicate of https://github.com/crystal-lang/crystal/issues/9050?

**Comment by MistressRemilia** [comment] 2023-04-21 22:51
That looks like it, yes.

**Closed** 2023-04-21 22:52 UTC
Labels: kind:bug, status:duplicate, topic:compiler:semantic
