### ISSUE TITLE
bug nil check

### ISSUE THREAD

**Issue by kostya** [crystal-lang/crystal#3412] opened 2016-10-11 21:30 UTC
this is expected to work:
```crystal
def bla
  x = rand > 0.5 ? 1 : nil
  return if !x || x == 2
  x + 1
end

p bla
```

```
undefined method '+' for Nil (compile-time type is (Int32 | Nil))

  x + 1
```

**Comment by raydf** [comment] 2016-10-11 22:23
Is this related to the possibility of a new mutation after the return?

```crystal
def bla
  x = rand > 0.5 ? 1 : nil
  return if !x || x == 2
  x = nil
  x + 1
end
```
Would be a very nice feature if the compiler can decide smartly based on the logic of the program anyway, as you're pointing out in the issue.

**Comment by Val** [comment] 2016-10-11 23:01
This works
```Crystal
def bla
  x = rand > 0.5 ? 1 : nil
  return if x.nil?
  return if x == 2
  x + 1
end

p bla
```

```
2
```

It's the logical `OR`

**Comment by asterite** [comment] 2016-10-12 00:06
Seems to be a duplicate of #3266

**Closed** 2016-10-12 16:23 UTC
Labels: compiler, enhancement
