### ISSUE TITLE
keyword args ordering

### ISSUE THREAD

**Issue by wontruefree** [crystal-lang/crystal#11458] opened 2021-11-16 04:22 UTC
Seems like you cannot splat keyword args after a args.

So this works. https://play.crystal-lang.org/#/r/c9v1
```crystal
class Foo
  def initialize(@x : Int32, @y : Int32)
  end
end

def bar(**kargs)
  Foo.new(**kargs, x: 1)
end

p bar(y: 2)
```

This does not work. https://play.crystal-lang.org/#/r/c9v2
```crystal
class Foo
  def initialize(@x : Int32, @y : Int32)
  end
end

def bar(**kargs)
  Foo.new(x: 1, **kargs)
end

p bar(y: 2)
```

**Comment by HertzDevil** [comment] 2021-11-16 04:28
Duplicate of #2651.

**Closed by HertzDevil** 2021-11-16 04:28 UTC
Labels: kind:bug
